export type ProductType = 'physical' | 'digital'
export type ProductCategory = 'Équipements' | 'Nutrition' | 'Vêtements' | 'Programmes' | 'Cardio' | 'Recovery' | 'Tech'

export interface AmazonProduct {
  asin: string
  affiliateUrl: string
}

export interface Product {
  id: string
  slug: string
  name: string
  brand: string
  description: string
  longDescription: string
  type: ProductType
  price_cents: number
  original_price_cents?: number
  stripe_price_id: string
  images: string[]
  badge?: string | null
  category: ProductCategory
  tags: string[]
  rating: number
  reviews: number
  inStock: boolean
  download_url?: string
  features: string[]
  amazon?: AmazonProduct
  disciplines?: string[]
  isAffiliate: boolean
  imageFit?: 'cover' | 'contain'
  imagePosition?: string // ex: '50% 65%' pour recadrer sur une zone précise
  level?: string         // programmes digitaux : niveau affiché (ex. « Tous niveaux »)
  duration?: string      // programmes digitaux : durée affichée (ex. « 12 semaines »)
  featured?: boolean     // mis en avant dans la section « Produits vedette » de la boutique
}

// Tags affiliés Amazon (programme Associates EU) — un tag par marketplace.
export const AMAZON_TAG = 'xenotif-21'        // amazon.fr
export const AMAZON_TAG_DE = 'xenotif21-21'   // amazon.de

// Lien de recherche Amazon affilié — ne tombe jamais en 404 et conserve la commission.
export function amazonSearchUrl(domain: string, keywords: string, tag: string = AMAZON_TAG): string {
  return `https://${domain}/s?k=${encodeURIComponent(keywords)}&tag=${tag}`
}

// Version FR par défaut (catalogue products.ts) → amazon.fr, mots-clés français.
const amazonUrl = (keywords: string) => amazonSearchUrl('www.amazon.fr', keywords)

export const AMAZON_ASSOCIATE_TAG = AMAZON_TAG

export const PRODUCTS: Product[] = [
  // ─── ÉQUIPEMENTS ──────────────────────────────────────────────────
  {
    id: 'e1', slug: 'kettlebell-20kg-fonte-pro',
    name: 'Kettlebell Fonte Pro 20 kg — CORENGTH',
    brand: 'CORENGTH / Decathlon',
    description: 'Kettlebell fonte 20 kg avec base caoutchouc antidérapante et poignée sablée pour CrossFit, HIIT et musculation fonctionnelle.',
    longDescription: 'Conçue pour les athlètes exigeants, cette kettlebell en fonte à 80% recyclée offre une prise sablée pour un grip parfait même en sueur. La base caoutchouc protège le sol et assure une stabilité parfaite. Idéale pour swings, Turkish get-up, clean & press et snatch.',
    type: 'physical', price_cents: 6499, stripe_price_id: 'price_kettlebell_20kg',
    images: ['https://m.media-amazon.com/images/I/71qk-GtYqPS._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '⭐ Bestseller', category: 'Équipements', rating: 4.8, reviews: 2847, inStock: true,
    tags: ['kettlebell', 'crossfit', 'musculation', 'force'],
    disciplines: ['crossfit', 'musculation', 'hiit'],
    features: ['20 kg — idéal CrossFit & HIIT', 'Fonte 80% recyclée', 'Base caoutchouc antidérapant', 'Poignée sablée grip optimal', 'Garantie 2 ans'],
    amazon: { asin: 'B07CWRS8BD', affiliateUrl: amazonUrl('kettlebell 20kg fonte') },
    isAffiliate: true,
  },
  {
    id: 'e2', slug: 'bandes-elastiques-portentum-5',
    name: 'Kit Bandes Élastiques Résistance × 5 — PORTENTUM',
    brand: 'PORTENTUM',
    description: 'Set de 5 bandes de résistance pour musculation et fitness. Résistances progressives de 25 à 125 lbs. Idéal entraînement complet à la maison.',
    longDescription: 'Le kit PORTENTUM comprend 5 bandes de résistance de couleurs différentes (de 25–65 lbs à 50–125 lbs) pour un entraînement progressif et complet. Parfaites pour la musculation, le crossfit, le yoga, la rééducation et le renforcement musculaire à la maison ou en déplacement. Durables, anti-glisse et faciles à transporter.',
    type: 'physical', price_cents: 3499, original_price_cents: 4999, stripe_price_id: 'price_bandes_elastiques',
    images: ['https://m.media-amazon.com/images/I/71RjVeMZPrL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🔥 Promo', category: 'Équipements', rating: 4.7, reviews: 1523, inStock: true,
    tags: ['bandes élastiques', 'résistance', 'fitness', 'musculation'],
    disciplines: ['musculation', 'yoga', 'stretching', 'running-cardio', 'boxing'],
    features: ['5 niveaux : 25 à 125 lbs', 'Musculation & fitness complet', 'Anti-glisse durable', 'Idéal à la maison', 'Faciles à transporter'],
    amazon: { asin: 'B0FP5BCCRL', affiliateUrl: amazonUrl('bandes élastiques musculation set') },
    isAffiliate: true,
  },
  {
    id: 'e3', slug: 'tapis-yoga-premium-10mm',
    name: 'Tapis Yoga Premium Antidérapant 10mm',
    brand: 'Gaiam',
    description: 'Tapis yoga double-face 10mm en TPE écologique. Antidérapant parfait, 183×61cm. Sangle transport incluse.',
    longDescription: 'Le tapis Gaiam premium offre une épaisseur de 10mm pour un amorti parfait des articulations. Sa surface texturée double-face garantit une adhérence maximale sur tous sols. Le matériau TPE est exempt de PVC, latex et phtalates — idéal pour les pratiquants soucieux de l\'environnement.',
    type: 'physical', price_cents: 3999, stripe_price_id: 'price_tapis_yoga',
    images: ['https://m.media-amazon.com/images/I/71wagkMna0L._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: null, category: 'Équipements', rating: 4.6, reviews: 3241, inStock: true,
    tags: ['tapis yoga', 'pilates', 'méditation', 'stretching'],
    disciplines: ['yoga', 'stretching', 'hiit'],
    features: ['10mm confort premium', 'Double face antidérapant', 'TPE sans PVC ni latex', '183×61 cm', 'Sangle transport incluse'],
    amazon: { asin: 'B003JIW3EC', affiliateUrl: amazonUrl('tapis yoga antidérapant 10mm') },
    isAffiliate: true,
  },
  {
    id: 'e4', slug: 'corde-sauter-crossfit-reebok',
    name: 'Corde à Sauter Speed CrossFit — Reebok',
    brand: 'Reebok',
    description: 'Corde à sauter câble acier revêtu, roulements à billes aluminium. Réglable 2,5—3,5m. Parfaite pour HIIT et boxe.',
    longDescription: 'La corde à sauter Reebok Speed est conçue pour les athlètes CrossFit et boxeurs. Câble acier ultra-léger, roulements à billes de précision pour une rotation fluide à haute vitesse. Poignées ergonomiques en aluminium brossé. Idéale pour double-unders et HIIT intensif.',
    type: 'physical', price_cents: 2999, stripe_price_id: 'price_corde_sauter',
    images: ['https://m.media-amazon.com/images/I/71EaV9mKomL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '⚡ Pro', category: 'Équipements', rating: 4.5, reviews: 892, inStock: true,
    tags: ['corde à sauter', 'cardio', 'crossfit', 'boxe'],
    disciplines: ['crossfit', 'hiit', 'boxing', 'running-cardio'],
    features: ['Câble acier revêtu', 'Roulements alu précision', 'Réglable 2,5—3,5m', 'Poignées ergonomiques', 'Bag de transport'],
    amazon: { asin: 'B07D7XR895', affiliateUrl: amazonUrl('corde à sauter speed rope crossfit') },
    isAffiliate: true,
  },
  {
    id: 'e5', slug: 'halteres-reglables-bowflex',
    name: 'Haltères Réglables 2—24 kg — Bowflex SelectTech',
    brand: 'Bowflex',
    description: 'Remplacement de 15 paires d\'haltères. Sélection du poids en 2 secondes de 2 à 24 kg. Design ergonomique.',
    longDescription: 'Les haltères Bowflex SelectTech 552i sont la référence mondiale en matière d\'haltères réglables. Un simple tournage du sélecteur remplace jusqu\'à 15 paires d\'haltères classiques. Gain de place et de budget considérable. Structure en acier chromé avec revêtement antidérapant.',
    type: 'physical', price_cents: 34900, original_price_cents: 42900, stripe_price_id: 'price_halteres_bowflex',
    images: ['https://m.media-amazon.com/images/I/71qO9g1eqEL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '💪 Premium', category: 'Équipements', rating: 4.9, reviews: 5623, inStock: true,
    tags: ['haltères', 'musculation', 'home gym', 'force'],
    disciplines: ['musculation', 'hiit', 'crossfit'],
    features: ['2 à 24 kg en 2 secondes', 'Remplace 15 paires', 'Construction acier chromé', 'Revêtement antidérapant', 'Garantie 2 ans'],
    amazon: { asin: 'B001ARYU58', affiliateUrl: amazonUrl('haltères réglables set') },
    isAffiliate: true, featured: true,
  },
  {
    id: 'e6', slug: 'velo-appartement-domyos',
    name: 'Vélo d\'Appartement Connecté — DOMYOS VC500',
    brand: 'DOMYOS',
    description: 'Vélo cardio connecté avec 24 niveaux de résistance magnétique. Écran LCD. Selle et guidon réglables. Connecté apps fitness.',
    longDescription: 'Le vélo DOMYOS VC500 est idéal pour le cyclisme indoor. Résistance magnétique ultra-silencieuse, 24 niveaux progressifs. Compatible avec les applications Decathlon Coach, Zwift et Kinomap via Bluetooth. Selle confort large réglable en hauteur et profondeur. Console LCD affichant vitesse, distance, calories, fréquence cardiaque.',
    type: 'physical', price_cents: 44900, original_price_cents: 59900, stripe_price_id: 'price_velo_domyos',
    images: ['https://m.media-amazon.com/images/I/71Pt-qyfotL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🚴 Connecté', category: 'Cardio', rating: 4.4, reviews: 1876, inStock: true,
    tags: ['vélo', 'cardio', 'indoor cycling', 'connected'],
    disciplines: ['cyclisme', 'running-cardio', 'hiit'],
    features: ['24 niveaux magnétiques', 'Connecté Bluetooth', 'Compatible Zwift/Kinomap', 'Selle confort réglable', 'Console LCD complète'],
    amazon: { asin: 'B086C2L1B7', affiliateUrl: amazonUrl('vélo appartement ergomètre') },
    isAffiliate: true,
  },
  {
    id: 'e7', slug: 'roue-abdominale-pro-double',
    name: 'Roue Abdominale Pro — Double Roue + Tapis Genoux',
    brand: 'PROIRON',
    description: 'Roue abdominale à double roulement avec tapis genoux. Renforce abdos, gainage et dos. Antidérapante, montage en 1 minute.',
    longDescription: 'La roue abdominale PROIRON sollicite en profondeur toute la sangle abdominale, le dos et les épaules en un seul mouvement. Sa double roue large assure une stabilité parfaite pour un travail contrôlé, sans déséquilibre. Poignées ergonomiques antidérapantes pour un grip sûr même en sueur. Livrée avec un tapis de genoux pour protéger les articulations. Compacte, elle se range partout et se monte en moins d\'une minute — idéale pour renforcer le tronc à la maison.',
    type: 'physical', price_cents: 1999, original_price_cents: 2999, stripe_price_id: 'price_roue_abdominale',
    images: ['https://m.media-amazon.com/images/I/71Pz1ewpf3L._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🔥 Promo', category: 'Équipements', rating: 4.7, reviews: 1340, inStock: true,
    tags: ['roue abdominale', 'abdominaux', 'gainage', 'core'],
    disciplines: ['musculation', 'crossfit', 'hiit'],
    features: ['Double roue ultra-stable', 'Tapis de genoux inclus', 'Renforce abdos, dos & gainage', 'Poignées antidérapantes', 'Compacte — montage 1 min'],
    amazon: { asin: 'B08PF38B9F', affiliateUrl: amazonUrl('roue abdominale ab wheel') },
    isAffiliate: true,
  },

  // ─── NUTRITION ────────────────────────────────────────────────────
  {
    id: 'n1', slug: 'whey-myprotein-chocolat-1kg',
    name: 'Impact Whey Protein Chocolat 1 kg — MyProtein',
    brand: 'MyProtein',
    description: 'N°1 en Europe. 22g protéines, 103 kcal, 5g BCAAs par portion. Lait de vaches en pâturage. Goût chocolat intense.',
    longDescription: 'La whey la plus vendue en Europe depuis 15 ans. Formulée à partir de lactosérum ultra-filtré provenant de vaches de pâturages irlandais. Profil aminé complet avec 5g de BCAAs par portion. Se mélange parfaitement dans l\'eau ou le lait. Idéale en post-workout pour maximiser la synthèse protéique.',
    type: 'physical', price_cents: 2999, original_price_cents: 4499, stripe_price_id: 'price_whey_chocolat',
    images: ['https://m.media-amazon.com/images/I/71ivSQXrUVL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🏆 N°1 Europe', category: 'Nutrition', rating: 4.8, reviews: 89432, inStock: true,
    tags: ['whey', 'protéine', 'musculation', 'récupération'],
    disciplines: ['musculation', 'crossfit', 'running-cardio', 'nutrition'],
    features: ['22g protéines / portion', '103 kcal seulement', '5g BCAAs naturels', 'Fabriquée en Europe', 'Sans sucres ajoutés'],
    amazon: { asin: 'B000GIQT2Q', affiliateUrl: amazonUrl('whey protéine chocolat 1kg') },
    isAffiliate: true, featured: true,
    imagePosition: '50% 72%',
  },
  {
    id: 'n2', slug: 'creatine-monohydrate-myprotein-300g',
    name: 'Créatine Monohydrate Pure 300g — MyProtein',
    brand: 'MyProtein',
    description: 'Créatine micronisée 99,9% pure. 60 doses. Certifiée Informed Sport. Force et puissance en 4 semaines.',
    longDescription: 'La créatine monohydrate est le supplément le plus étudié en science du sport avec des centaines d\'études confirmant son efficacité. La version micronisée de MyProtein se dissout instantanément et est absorbée plus rapidement. Certifiée Informed Sport — testée antidopage. Sans goût pour se mélanger à n\'importe quelle boisson.',
    type: 'physical', price_cents: 1999, stripe_price_id: 'price_creatine',
    images: ['https://m.media-amazon.com/images/I/61AWk5yQQsL._AC_SL1080_.jpg'], imageFit: 'contain',
    badge: null, category: 'Nutrition', rating: 4.9, reviews: 45123, inStock: true,
    tags: ['créatine', 'force', 'puissance', 'musculation'],
    disciplines: ['musculation', 'crossfit', 'hiit', 'nutrition'],
    features: ['Pureté 99,9%', '60 portions de 5g', 'Informed Sport certifiée', 'Sans goût', 'Résultats en 4 semaines'],
    amazon: { asin: 'B000GIQT3A', affiliateUrl: amazonUrl('créatine monohydrate poudre') },
    isAffiliate: true,
  },
  {
    id: 'n3', slug: 'bcaa-myprotein-500g-fruit',
    name: 'BCAA 2:1:1 Fruit Punch 500g — MyProtein',
    brand: 'MyProtein',
    description: 'BCAAs ratio 2:1:1. 7g par dose, 83 portions. Certifié vegan. Récupération, anti-catabolisme, endurance.',
    longDescription: 'Les BCAAs (acides aminés branchés) en ratio 2:1:1 optimisé : Leucine, Isoleucine, Valine. La Leucine stimule directement la synthèse protéique, l\'Isoleucine aide à l\'utilisation du glucose et la Valine réduit la fatigue centrale. Idéals pendant l\'entraînement pour préserver la masse musculaire.',
    type: 'physical', price_cents: 2499, stripe_price_id: 'price_bcaa',
    images: ['https://m.media-amazon.com/images/I/718cF6-QSgL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '💊 Vegan', category: 'Nutrition', rating: 4.6, reviews: 12847, inStock: true,
    tags: ['bcaa', 'récupération', 'endurance', 'vegan'],
    disciplines: ['musculation', 'running-cardio', 'crossfit', 'nutrition'],
    features: ['Ratio 2:1:1 optimal', '7g BCAAs/dose', '83 portions', 'Certifié vegan', 'Anti-catabolisme'],
    amazon: { asin: 'B00BXZ5Y8A', affiliateUrl: amazonUrl('bcaa poudre') },
    isAffiliate: true,
  },

  // ─── RECOVERY ─────────────────────────────────────────────────────
  {
    id: 'r1', slug: 'foam-roller-trigger-point',
    name: 'Foam Roller Pro Massage — TriggerPoint GRID',
    brand: 'TriggerPoint',
    description: 'Rouleau de massage multizone avec surface GRID brevetée. Simule les mains d\'un masseur. Récupération optimale.',
    longDescription: 'Le GRID de TriggerPoint est le foam roller de référence des professionnels. Sa surface à 3 zones distinctes (creux, tubulaire, plat) simule les doigts, paumes et pouces d\'un masseur. Le corps creux au centre assure la durabilité et l\'absorption de poids jusqu\'à 160kg. Inclus : accès à la bibliothèque vidéo complète.',
    type: 'physical', price_cents: 4499, stripe_price_id: 'price_foam_roller',
    images: ['https://images.pexels.com/photos/20890283/pexels-photo-20890283.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🔵 Pro', category: 'Recovery', rating: 4.7, reviews: 8921, inStock: true,
    tags: ['foam roller', 'récupération', 'massage', 'mobilité'],
    disciplines: ['running-cardio', 'musculation', 'yoga', 'stretching'],
    features: ['Surface GRID 3 zones', 'Simule massage pro', 'Support 160kg', 'Corps creux durable', 'Vidéos incluses'],
    amazon: { asin: 'B0093VBBZA', affiliateUrl: amazonUrl('rouleau massage foam roller') },
    isAffiliate: true,
  },
  {
    id: 'r2', slug: 'pistolet-massage-theragun',
    name: 'Pistolet de Massage Percussion — Theragun Mini',
    brand: 'Therabody',
    description: 'Mini pistolet percussion 2400 RPM, 3 vitesses, silencieux. Batterie 150min. Compact et puissant pour récupération rapide.',
    longDescription: 'Le Theragun Mini est la version compacte du pistolet de massage professionnel plébiscité par les athlètes NBA, NFL et olympiques. 2400 percussions/minute pénétrant 16mm en profondeur pour activer la circulation et libérer les tensions musculaires. 3 vitesses adaptées. Fonctionnement ultra-silencieux. Autonomie de 150 minutes.',
    type: 'physical', price_cents: 17900, original_price_cents: 21900, stripe_price_id: 'price_theragun_mini',
    images: ['https://m.media-amazon.com/images/I/71OEKl766uL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🏅 Pro Athlete', category: 'Recovery', rating: 4.8, reviews: 15234, inStock: true,
    tags: ['pistolet massage', 'percussion', 'récupération', 'theragun'],
    disciplines: ['musculation', 'running-cardio', 'crossfit', 'yoga', 'stretching'],
    features: ['2400 RPM puissants', '3 vitesses adaptées', '150min autonomie', 'Ultra-silencieux 60dB', 'Compact & voyager'],
    amazon: { asin: 'B08F9P2BYD', affiliateUrl: amazonUrl('pistolet massage musculaire') },
    isAffiliate: true, featured: true,
  },

  // ─── MONTRES CONNECTÉES (TECH) ────────────────────────────────────
  {
    id: 't1', slug: 'montre-connectee-sport-gps',
    name: 'Montre Connectée Sport GPS Multisport',
    brand: 'Garmin / Polar / Coros',
    description: 'Montre GPS multisport avec cardio au poignet, suivi du sommeil, VO2 max et 100+ modes sport. Autonomie longue durée.',
    longDescription: 'La montre connectée idéale pour les athlètes : GPS intégré ultra-précis, capteur de fréquence cardiaque au poignet, suivi du sommeil et du stress, estimation de la VO2 max et plus de 100 profils sportifs (course, vélo, natation, musculation, HIIT). Compatible avec Strava, Apple Santé et Google Fit. Étanche et autonomie de plusieurs jours.',
    type: 'physical', price_cents: 19900, original_price_cents: 24900, stripe_price_id: 'price_montre_gps',
    images: ['https://images.pexels.com/photos/5081914/pexels-photo-5081914.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '⌚ GPS', category: 'Tech', rating: 4.7, reviews: 6842, inStock: true,
    tags: ['montre connectée', 'gps', 'cardio', 'running', 'multisport'],
    disciplines: ['running-cardio', 'cyclisme', 'natation', 'crossfit', 'hiit'],
    features: ['GPS multisport précis', 'Cardio au poignet', 'Suivi sommeil & VO2 max', '100+ modes sport', 'Compatible Strava & Apple Santé'],
    amazon: { asin: '', affiliateUrl: amazonUrl('montre sport gps cardio multisport') },
    isAffiliate: true, featured: true,
  },
  {
    id: 't2', slug: 'bracelet-fitness-tracker',
    name: 'Bracelet Fitness Tracker d\'Activité',
    brand: 'Fitbit / Xiaomi / Huawei',
    description: 'Bracelet connecté léger : podomètre, calories, fréquence cardiaque, sommeil et notifications. Écran AMOLED. 14 jours d\'autonomie.',
    longDescription: 'Le compagnon fitness parfait au quotidien. Ce bracelet d\'activité suit automatiquement tes pas, calories brûlées, fréquence cardiaque et qualité de sommeil. Écran AMOLED couleur lumineux, étanche pour la natation, et jusqu\'à 14 jours d\'autonomie. Reçois tes notifications (appels, SMS, apps) directement au poignet. Synchronisation avec l\'app Xenotif via Apple Santé / Google Fit.',
    type: 'physical', price_cents: 4900, original_price_cents: 6900, stripe_price_id: 'price_bracelet_tracker',
    images: ['https://m.media-amazon.com/images/I/71bSq0qkF9L._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🔥 Promo', category: 'Tech', rating: 4.5, reviews: 23184, inStock: true,
    tags: ['bracelet connecté', 'fitness tracker', 'podomètre', 'sommeil'],
    disciplines: ['running-cardio', 'hiit', 'musculation', 'yoga', 'natation', 'cyclisme'],
    features: ['Podomètre & calories', 'Cardio 24/7', 'Suivi sommeil', 'Écran AMOLED couleur', '14 jours d\'autonomie'],
    amazon: { asin: '', affiliateUrl: amazonUrl('bracelet connecté fitness cardio') },
    isAffiliate: true,
  },
  {
    id: 't3', slug: 'montre-connectee-tactile-running',
    name: 'Smartwatch Tactile Running & Cardio',
    brand: 'Apple Watch / Samsung / Amazfit',
    description: 'Smartwatch écran tactile AMOLED, GPS, ECG, SpO2 et coach running intégré. Appels Bluetooth, paiement sans contact, 100+ cadrans.',
    longDescription: 'Une smartwatch premium pour transformer ton entraînement. Grand écran tactile AMOLED, GPS intégré pour tracer tes parcours, capteurs avancés (ECG, oxygène sanguin SpO2, fréquence cardiaque). Coach running intégré avec plans personnalisés, alertes de zones cardiaques et récupération. Passe tes appels en Bluetooth, paie sans contact, et personnalise parmi 100+ cadrans. Compatible iOS & Android.',
    type: 'physical', price_cents: 12900, stripe_price_id: 'price_smartwatch_tactile',
    images: ['https://images.pexels.com/photos/7671474/pexels-photo-7671474.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '⌚ AMOLED', category: 'Tech', rating: 4.6, reviews: 11237, inStock: true,
    tags: ['smartwatch', 'apple watch', 'ecg', 'running', 'cardio'],
    disciplines: ['running-cardio', 'crossfit', 'hiit', 'musculation', 'yoga', 'cyclisme'],
    features: ['Écran tactile AMOLED', 'GPS + ECG + SpO2', 'Coach running intégré', 'Appels Bluetooth', 'Compatible iOS & Android'],
    amazon: { asin: '', affiliateUrl: amazonUrl('montre connectée fitness gps cardio') },
    isAffiliate: true,
  },

  // ─── VÊTEMENTS ────────────────────────────────────────────────────
  {
    id: 'v1', slug: 'short-training-gymshark-homme',
    name: 'Short Entraînement Sport Performance Homme',
    brand: 'XENOTIF',
    description: 'Short 4-way stretch, Dry-Fit moisture-wicking. Poche zippée. Tailles S-XXL. Noir, gris, marine.',
    longDescription: 'Conçu pour les athlètes qui ne font aucun compromis sur la performance. Le tissu 4-way stretch épouse parfaitement le corps sans contraindre les mouvements. La technologie Dry-Fit évacue la transpiration 3x plus vite que le coton. Poche zippée latérale sécurisée pour smartphone. Coutures renforcées résistantes aux lavages intensifs.',
    type: 'physical', price_cents: 3499, stripe_price_id: 'price_short_homme',
    images: [
      'https://images.pexels.com/photos/4803921/pexels-photo-4803921.jpeg?auto=compress&cs=tinysrgb&w=800',
    ],
    badge: null, category: 'Vêtements', rating: 4.7, reviews: 1892, inStock: true,
    tags: ['short', 'training', 'running', 'homme'],
    disciplines: ['running-cardio', 'hiit', 'crossfit', 'boxing'],
    features: ['Tissu 4-way stretch', 'Dry-Fit moisture-wicking', 'Poche zippée', 'S à XXL', '3 coloris disponibles'],
    amazon: { asin: '', affiliateUrl: amazonUrl('short sport homme training fitness') },
    isAffiliate: true,
  },
  {
    id: 'v2', slug: 'legging-compression-femme-premium',
    name: 'Legging Compression Taille Haute Femme',
    brand: 'XENOTIF',
    description: 'Compression graduée, taille haute, tissu opaque anti-UV. Poche téléphone. XS-XL. 5 coloris.',
    longDescription: 'Le legging de compression XENOTIF offre un maintien optimal pour toutes les disciplines. La taille haute plate-forme assure un maintien du ventre sans comprimer. Le tissu opaque (280 GSM) est certifié anti-UV et résiste aux transparences même lors des squats. La compression graduée améliore la circulation sanguine et réduit les courbatures.',
    type: 'physical', price_cents: 4499, original_price_cents: 5499, stripe_price_id: 'price_legging_femme',
    images: ['https://m.media-amazon.com/images/I/61vNHqZSO-L._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '❤️ Best Seller', category: 'Vêtements', rating: 4.8, reviews: 3421, inStock: true,
    tags: ['legging', 'compression', 'femme', 'yoga'],
    disciplines: ['yoga', 'running-cardio', 'crossfit', 'hiit'],
    features: ['Compression graduée', 'Taille haute plate', 'Opaque anti-UV', 'Poche téléphone', 'XS à XL · 5 coloris'],
    amazon: { asin: '', affiliateUrl: amazonUrl('legging sport femme taille haute') },
    isAffiliate: true, featured: true,
  },
  {
    id: 'v3', slug: 'legging-compression-homme-premium',
    name: 'Legging Compression Performance Homme',
    brand: 'XENOTIF',
    description: 'Legging de compression homme, tissu technique respirant. Maintien musculaire, séchage rapide. Idéal running, muscu, crossfit. S-XXL.',
    longDescription: 'Le legging de compression XENOTIF pour homme offre un maintien musculaire optimal qui réduit les vibrations et la fatigue. Le tissu technique 4-way stretch évacue la transpiration et sèche rapidement. Coutures plates anti-frottement, taille élastiquée confortable et poche latérale. Parfait porté seul ou sous un short pour le running, la musculation, le CrossFit ou comme couche de base.',
    type: 'physical', price_cents: 3999, original_price_cents: 4999, stripe_price_id: 'price_legging_homme',
    images: ['https://images.pexels.com/photos/5327453/pexels-photo-5327453.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🆕 Nouveau', category: 'Vêtements', rating: 4.7, reviews: 2156, inStock: true,
    tags: ['legging', 'compression', 'homme', 'running'],
    disciplines: ['running-cardio', 'musculation', 'crossfit', 'hiit'],
    features: ['Compression musculaire', 'Tissu 4-way stretch', 'Séchage rapide', 'Coutures anti-frottement', 'S à XXL'],
    amazon: { asin: '', affiliateUrl: amazonUrl('legging compression homme sport') },
    isAffiliate: true,
  },

  // ─── PROGRAMMES DIGITAUX ──────────────────────────────────────────
  {
    id: 'd1', slug: 'programme-prise-masse-12-semaines',
    name: 'Programme Prise de Masse — 12 Semaines Complet',
    brand: 'XENOTIF Coach',
    description: '84 séances structurées, split 4j/semaine, progression de charge guidée. Plan nutrition + macros. PDF + vidéos.',
    longDescription: 'Le programme prise de masse le plus complet du marché français. 84 séances réparties sur 12 semaines avec progression en charge semaine par semaine. Includes : split musculaire détaillé, calcul macros personnalisé par morphotype, guide récupération, 40+ exercices illustrés en vidéo HD. Suivi de progression intégré sous Excel.',
    type: 'digital', price_cents: 2900, stripe_price_id: 'price_programme_masse',
    images: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=800&q=80',
    ],
    badge: '📥 Bestseller', category: 'Programmes', rating: 4.9, reviews: 4127, inStock: true,
    tags: ['prise de masse', 'musculation', 'programme', 'PDF'],
    disciplines: ['musculation'],
    features: ['84 séances sur 12 semaines', 'Split 4j/semaine', 'Progression charge guidée', 'Plan nutrition + macros', 'Vidéos HD incluses'],
    level: 'Intermédiaire', duration: '12 semaines',
    download_url: '/downloads/programme-prise-masse.pdf',
    isAffiliate: false,
  },
  {
    id: 'd2', slug: 'plan-nutrition-seche-8-semaines',
    name: 'Plan Nutrition Sèche — 8 Semaines',
    brand: 'XENOTIF Coach',
    description: '56 jours de menus détaillés, 40+ recettes fitness, liste de courses, macros. Compatible vegan.',
    longDescription: 'Le plan nutrition sèche le plus téléchargé de la plateforme. 56 jours de menus variés calculés par notre nutritionniste certifiée. Chaque repas est optimisé pour maintenir la satiété tout en créant le déficit calorique nécessaire. Recettes simples et rapides (moins de 15 min). Compatible avec le régime vegan sur simple sélection.',
    type: 'digital', price_cents: 1900, stripe_price_id: 'price_plan_nutrition',
    images: [
      'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=800&q=80',
    ],
    badge: '📥 PDF Instant', category: 'Programmes', rating: 4.8, reviews: 2891, inStock: true,
    tags: ['nutrition', 'sèche', 'régime', 'PDF'],
    disciplines: ['musculation', 'running-cardio', 'hiit', 'nutrition'],
    features: ['56 jours de menus', '40+ recettes fitness', 'Liste courses hebdo', 'Macros personnalisés', 'Compatible vegan'],
    level: 'Tous niveaux', duration: '8 semaines',
    download_url: '/downloads/plan-nutrition-seche.pdf',
    isAffiliate: false,
  },
  {
    id: 'd3', slug: 'programme-hiit-6-semaines',
    name: 'Programme HIIT Brûle-Graisses — 6 Semaines',
    brand: 'XENOTIF Coach',
    description: '24 séances 20–30 min, 100% au poids du corps. Aucun matériel. Débutant → avancé. Résultats garantis.',
    longDescription: 'Le programme HIIT XENOTIF est conçu par notre coach certifié CrossFit Level 2. 4 séances par semaine de 20 à 30 minutes maximum, 100% au poids du corps — aucun matériel requis. La progressivité garantit une adaptation optimale sans risque de blessure. Chaque séance inclut un timer intégré et des vidéos de démonstration.',
    type: 'digital', price_cents: 1490, stripe_price_id: 'price_hiit_programme',
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80',
    ],
    badge: '🔥 Populaire', category: 'Programmes', rating: 4.7, reviews: 3654, inStock: true,
    tags: ['HIIT', 'brûle-graisses', 'poids du corps', 'cardio'],
    disciplines: ['hiit', 'running-cardio'],
    features: ['24 séances 20–30 min', 'Sans matériel', 'Débutant → avancé', 'Timer intégré', 'Vidéos démo HD'],
    level: 'Débutant à avancé', duration: '6 semaines',
    download_url: '/downloads/programme-hiit.pdf',
    isAffiliate: false,
  },
  {
    id: 'd4', slug: 'guide-running-marathon-complet',
    name: 'Guide Running — Du 5K au Marathon',
    brand: 'XENOTIF Coach',
    description: 'E-book 120 pages. Plans 5K/10K/semi/marathon. Nutrition course, prévention blessures, mental de compétiteur.',
    longDescription: 'Le guide running XENOTIF couvre tout le spectre du coureur moderne. Rédigé par un coach athlétisme FFA, il inclut des plans personnalisés pour 4 distances, des conseils nutrition avant/pendant/après course, un protocole anti-blessures en 7 points et une préparation mentale éprouvée. 120 pages richement illustrées.',
    type: 'digital', price_cents: 1490, stripe_price_id: 'price_guide_running',
    images: [
      'https://images.unsplash.com/photo-1571008887538-b36bb32f4571?auto=format&fit=crop&w=800&q=80',
    ],
    badge: '📥 E-book 120p', category: 'Programmes', rating: 4.8, reviews: 1987, inStock: true,
    tags: ['running', 'marathon', 'course à pied', 'e-book'],
    disciplines: ['running-cardio'],
    features: ['120 pages expert', 'Plans 5K/10K/semi/marathon', 'Nutrition course', 'Anti-blessures', 'Mental compétiteur'],
    level: 'Tous niveaux', duration: '8 à 16 semaines',
    download_url: '/downloads/guide-running-marathon.pdf',
    isAffiliate: false,
  },

  // ─── CYCLISME (affiliation Amazon) ────────────────────────────────
  {
    id: 'c1', slug: 'casque-velo-route',
    name: 'Casque Vélo Route Aérodynamique',
    brand: 'ROCKBROS',
    description: 'Casque vélo léger et ventilé, coque renforcée et molette d\'ajustement. Sécurité et confort pour la route comme le VTT.',
    longDescription: 'Un bon casque est le premier équipement non négociable du cycliste. Ce modèle aérodynamique allie une coque in-mold renforcée à une structure ultra-légère (~250 g) pour une protection optimale sans gêne. Ses larges aérations maintiennent la tête au frais sur les longues sorties, et la molette d\'ajustement micrométrique assure un maintien parfait quelle que soit la morphologie. Sangles déperlantes et visière amovible incluses.',
    type: 'physical', price_cents: 4990, original_price_cents: 6990, stripe_price_id: 'price_aff_casque_velo',
    images: ['https://images.pexels.com/photos/12956080/pexels-photo-12956080.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🚴 Sécurité', category: 'Équipements', rating: 4.6, reviews: 2143, inStock: true,
    tags: ['casque vélo', 'sécurité', 'cyclisme', 'route'],
    disciplines: ['cyclisme'],
    features: ['Coque in-mold renforcée', 'Ultra-léger (~250 g)', 'Aérations multiples', 'Molette d\'ajustement', 'Visière amovible'],
    amazon: { asin: 'B07VND8R9P', affiliateUrl: amazonUrl('casque vélo route adulte') },
    isAffiliate: true,
  },
  {
    id: 'c2', slug: 'compteur-gps-velo',
    name: 'Compteur GPS Vélo sans Fil',
    brand: 'iGPSPORT',
    description: 'Compteur GPS étanche : vitesse, distance, dénivelé, parcours. Grand écran lisible au soleil, autonomie 25 h, montage rapide.',
    longDescription: 'Mesure chaque sortie avec précision grâce à ce compteur GPS sans fil. Il enregistre vitesse, distance, temps, altitude, dénivelé et tracé GPS, et se synchronise avec Strava et Komoot. Écran transflectif parfaitement lisible en plein soleil, autonomie de 25 heures et étanchéité IPX7. Le support guidon fourni s\'installe sans outil en quelques secondes. Compatible capteurs ANT+ (cardio, cadence, vitesse).',
    type: 'physical', price_cents: 3990, stripe_price_id: 'price_aff_gps_velo',
    images: ['https://images.pexels.com/photos/7340701/pexels-photo-7340701.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '📡 GPS', category: 'Tech', rating: 4.5, reviews: 1689, inStock: true,
    tags: ['compteur gps', 'cyclisme', 'strava', 'vélo'],
    disciplines: ['cyclisme'],
    features: ['GPS vitesse/distance/dénivelé', 'Sync Strava & Komoot', 'Écran lisible au soleil', 'Autonomie 25 h · IPX7', 'Compatible ANT+'],
    amazon: { asin: 'B08T1Y2QRX', affiliateUrl: amazonUrl('compteur gps vélo sans fil') },
    isAffiliate: true,
  },
  {
    id: 'c4', slug: 'maillot-cuissard-velo',
    name: 'Cuissard Vélo Rembourré 4D',
    brand: 'Van Rysel',
    description: 'Cuissard cycliste avec peau de chamois 4D respirante. Tissu compressif, bandes anti-glisse. Confort sur les longues distances.',
    longDescription: 'Le confort sur le vélo se joue d\'abord sur la selle : ce cuissard intègre une peau de chamois 4D haute densité qui amortit les chocs et évite les irritations, même après plusieurs heures. Le tissu compressif et respirant évacue la transpiration et soutient les muscles, tandis que les bandes silicone en bas de cuisse maintiennent le cuissard en place. Coutures plates anti-frottement. La base de toute tenue de cycliste sérieux.',
    type: 'physical', price_cents: 3490, stripe_price_id: 'price_aff_cuissard_velo',
    images: ['https://images.pexels.com/photos/5789228/pexels-photo-5789228.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🩳 Confort', category: 'Vêtements', rating: 4.5, reviews: 1254, inStock: true,
    tags: ['cuissard vélo', 'cyclisme', 'vêtement', 'route'],
    disciplines: ['cyclisme'],
    features: ['Peau de chamois 4D', 'Tissu compressif respirant', 'Bandes anti-glisse', 'Coutures plates', 'Longues distances'],
    amazon: { asin: 'B08YDH7J5K', affiliateUrl: amazonUrl('cuissard vélo homme rembourré') },
    isAffiliate: true,
  },
  {
    id: 'c5', slug: 'gants-velo-demi-doigts',
    name: 'Gants de Vélo Demi-Doigts Anti-Choc',
    brand: 'GripGrab',
    description: 'Gants cyclistes demi-doigts avec gel anti-choc, paume respirante et tirette de retrait. Meilleur grip, moins de fatigue.',
    longDescription: 'Les gants protègent les mains des vibrations et des chutes, tout en améliorant le grip sur le guidon. Ce modèle demi-doigts intègre des coussinets gel aux points de pression pour absorber les chocs et réduire l\'engourdissement sur les longues sorties. Dos en mesh respirant, paume en suédine antidérapante, et languettes de retrait pratiques. Zone éponge sur le pouce pour s\'essuyer le front.',
    type: 'physical', price_cents: 1690, stripe_price_id: 'price_aff_gants_velo',
    images: ['https://images.pexels.com/photos/12266473/pexels-photo-12266473.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🧤 Grip', category: 'Vêtements', rating: 4.6, reviews: 2071, inStock: true,
    tags: ['gants vélo', 'cyclisme', 'anti-choc', 'grip'],
    disciplines: ['cyclisme'],
    features: ['Gel anti-choc', 'Paume antidérapante', 'Dos respirant', 'Languettes de retrait', 'Demi-doigts'],
    amazon: { asin: 'B07QF9V6T2', affiliateUrl: amazonUrl('gants vélo demi doigts') },
    isAffiliate: true,
  },
  {
    id: 'c7', slug: 'bidon-velo-porte-bidon',
    name: 'Bidon Vélo 750 ml + Porte-Bidon',
    brand: 'Zéfal',
    description: 'Bidon 750 ml sans BPA + porte-bidon léger en aluminium. Hydratation facile d\'une main, montage sur le cadre.',
    longDescription: 'S\'hydrater régulièrement est clé sur le vélo. Cet ensemble réunit un bidon souple de 750 ml sans BPA, au bec anti-fuite et au débit généreux pour boire d\'une seule main, et un porte-bidon léger en aluminium qui se fixe sur les inserts du cadre. Le bidon est compressible, facile à presser et passe au lave-vaisselle. Le porte-bidon maintient fermement le bidon même sur terrain accidenté.',
    type: 'physical', price_cents: 1290, stripe_price_id: 'price_aff_bidon_velo',
    images: ['https://images.pexels.com/photos/17755959/pexels-photo-17755959.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '💧 Hydratation', category: 'Équipements', rating: 4.5, reviews: 968, inStock: true,
    tags: ['bidon vélo', 'porte-bidon', 'hydratation', 'cyclisme'],
    disciplines: ['cyclisme'],
    features: ['Bidon 750 ml sans BPA', 'Bec anti-fuite', 'Porte-bidon aluminium', 'Boire d\'une main', 'Passe au lave-vaisselle'],
    amazon: { asin: 'B0026ROS8Q', affiliateUrl: amazonUrl('bidon vélo porte-bidon') },
    isAffiliate: true,
  },

  // ─── NATATION (affiliation Amazon) ────────────────────────────────
  {
    id: 's1', slug: 'lunettes-natation-anti-buee',
    name: 'Lunettes de Natation Anti-Buée',
    brand: 'Arena',
    description: 'Lunettes de natation étanches, verres anti-buée et anti-UV, joints en silicone souple. Vision claire et confort, sans fuite.',
    longDescription: 'Des lunettes qui ne s\'embuent pas et ne fuient pas changent une séance de natation. Ce modèle combine un traitement anti-buée durable et une protection anti-UV pour une vision nette en piscine comme en eau libre. Les joints en silicone souple épousent le contour des yeux sans marquer, et le pont de nez interchangeable (3 tailles fournies) s\'adapte à toutes les morphologies. Sangle double réglable d\'une seule main.',
    type: 'physical', price_cents: 1490, original_price_cents: 1990, stripe_price_id: 'price_aff_lunettes_natation',
    images: ['https://images.pexels.com/photos/5915306/pexels-photo-5915306.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🥽 Anti-buée', category: 'Équipements', rating: 4.6, reviews: 3120, inStock: true,
    tags: ['lunettes natation', 'anti-buée', 'natation', 'piscine'],
    disciplines: ['natation'],
    features: ['Verres anti-buée durables', 'Protection anti-UV', 'Joints silicone souple', '3 ponts de nez fournis', 'Sangle réglable d\'une main'],
    amazon: { asin: 'B00KMU3R8A', affiliateUrl: amazonUrl('lunettes natation anti buée') },
    isAffiliate: true,
  },
  {
    id: 's2', slug: 'bonnet-bain-silicone',
    name: 'Bonnet de Bain Silicone',
    brand: 'Speedo',
    description: 'Bonnet de bain 100 % silicone, étanche et confortable. Réduit la traînée, protège les cheveux du chlore. Mixte, taille unique.',
    longDescription: 'Le bonnet en silicone est l\'accessoire de base de tout nageur : il protège les cheveux du chlore, réduit la traînée dans l\'eau et garde la tête au chaud. Ce modèle 100 % silicone est doux, durable et facile à enfiler sans tirer les cheveux. Il reste parfaitement en place pendant les longueurs et n\'irrite pas le front. Taille unique adaptée aux hommes, femmes et adolescents.',
    type: 'physical', price_cents: 990, stripe_price_id: 'price_aff_bonnet_bain',
    images: ['https://images.pexels.com/photos/18090671/pexels-photo-18090671.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🏊 Essentiel', category: 'Équipements', rating: 4.5, reviews: 2480, inStock: true,
    tags: ['bonnet de bain', 'silicone', 'natation', 'piscine'],
    disciplines: ['natation'],
    features: ['100 % silicone souple', 'Étanche & confortable', 'Réduit la traînée', 'Protège les cheveux', 'Taille unique mixte'],
    amazon: { asin: 'B001HBHNH0', affiliateUrl: amazonUrl('bonnet de bain silicone') },
    isAffiliate: true,
  },
  {
    id: 's3', slug: 'planche-natation-kickboard',
    name: 'Planche de Natation (Kickboard)',
    brand: 'Arena',
    description: 'Planche en mousse EVA pour renforcer le battement de jambes. Légère, ergonomique, haute flottabilité. Idéale à l\'entraînement.',
    longDescription: 'La planche est l\'outil indispensable pour travailler le battement de jambes et la position du corps. En mousse EVA haute densité, elle offre une flottabilité élevée tout en restant légère et résistante au chlore. Sa forme ergonomique avec découpes pour les mains assure une prise confortable quel que soit l\'exercice. Elle convient aux nageurs débutants comme confirmés pour les éducatifs et le renforcement.',
    type: 'physical', price_cents: 1290, stripe_price_id: 'price_aff_planche_natation',
    images: ['https://images.pexels.com/photos/8028663/pexels-photo-8028663.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🏊 Entraînement', category: 'Équipements', rating: 4.7, reviews: 1654, inStock: true,
    tags: ['planche natation', 'kickboard', 'entraînement', 'natation'],
    disciplines: ['natation'],
    features: ['Mousse EVA haute densité', 'Flottabilité élevée', 'Découpes ergonomiques', 'Résistante au chlore', 'Débutant à confirmé'],
    amazon: { asin: 'B0788KZJV2', affiliateUrl: amazonUrl('planche natation kickboard') },
    isAffiliate: true,
  },
  {
    id: 's4', slug: 'maillot-bain-natation-chlororesistant',
    name: 'Maillot de Bain Natation Chlororésistant',
    brand: 'Arena',
    description: 'Maillot d\'entraînement chlororésistant, séchage rapide, coupe ajustée anti-traînée. Tient des centaines de séances en piscine.',
    longDescription: 'Conçu pour l\'entraînement intensif, ce maillot en tissu chlororésistant garde sa forme et ses couleurs séance après séance, là où un maillot classique se détend en quelques semaines. La coupe ajustée réduit la traînée dans l\'eau, le séchage est rapide et les coutures plates évitent les irritations. Le choix durable pour qui enchaîne les longueurs.',
    type: 'physical', price_cents: 2490, stripe_price_id: 'price_aff_maillot_natation',
    images: ['https://images.pexels.com/photos/8688609/pexels-photo-8688609.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🩱 Endurance', category: 'Vêtements', rating: 4.6, reviews: 1290, inStock: true,
    tags: ['maillot de bain', 'natation', 'chlororésistant', 'piscine'],
    disciplines: ['natation'],
    features: ['Tissu chlororésistant', 'Séchage rapide', 'Coupe ajustée anti-traînée', 'Coutures plates', 'Tenue longue durée'],
    amazon: { asin: 'B07PGSC9LR', affiliateUrl: amazonUrl('maillot de bain natation chlore résistant') },
    isAffiliate: true,
  },

  // ─── SÉLECTION AMAZON — best-sellers fitness (affiliation) ─────────
  {
    id: 'a1', slug: 'barre-traction-porte',
    name: 'Barre de Traction de Porte Sans Vis',
    brand: 'Pullup & Dip',
    description: 'Barre de traction multi-prises pour cadre de porte, sans perçage. Jusqu\'à 130 kg. Travail dos, biceps et gainage à la maison.',
    longDescription: 'La barre de traction incontournable du training maison : installation sans vis ni perçage en quelques secondes, multiples positions de prise (large, serrée, neutre) pour varier le travail du dos, des biceps et des abdos. Mousses de protection antidérapantes, acier renforcé supportant jusqu\'à 130 kg.',
    type: 'physical', price_cents: 2999, original_price_cents: 3999, stripe_price_id: 'price_aff_a1',
    images: ['https://m.media-amazon.com/images/I/61gFT3yR0FL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🔥 Best Seller', category: 'Équipements', rating: 4.7, reviews: 8930, inStock: true,
    tags: ['barre de traction', 'dos', 'musculation', 'maison'],
    disciplines: ['musculation', 'crossfit'],
    features: ['Sans vis ni perçage', 'Multi-prises', 'Jusqu\'à 130 kg', 'Mousses antidérapantes', 'Acier renforcé'],
    amazon: { asin: 'B07TRACTION', affiliateUrl: amazonUrl('barre de traction porte sans vis') },
    isAffiliate: true, featured: true,
  },
  {
    id: 'a2', slug: 'banc-musculation-reglable-pliable',
    name: 'Banc de Musculation Réglable Pliable',
    brand: 'BangTong&Li',
    description: 'Banc inclinable 7 positions, pliable et compact. Idéal développé couché, curls et exercices haltères à domicile.',
    longDescription: 'Un banc réglable transforme une paire d\'haltères en salle complète. 7 inclinaisons (du décliné au militaire), dossier et assise rembourrés haute densité, structure acier stable jusqu\'à 250 kg. Pliable pour se ranger dans un placard. La pièce centrale du home gym.',
    type: 'physical', price_cents: 8990, original_price_cents: 11990, stripe_price_id: 'price_aff_a2',
    images: ['https://m.media-amazon.com/images/I/81GBn0uijGL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '💪 Home Gym', category: 'Équipements', rating: 4.6, reviews: 4210, inStock: true,
    tags: ['banc musculation', 'haltères', 'développé couché', 'maison'],
    disciplines: ['musculation'],
    features: ['7 inclinaisons', 'Pliable & compact', 'Jusqu\'à 250 kg', 'Rembourrage haute densité', 'Structure acier'],
    amazon: { asin: 'B08BANC0001', affiliateUrl: amazonUrl('banc de musculation réglable pliable') },
    isAffiliate: true, featured: true,
  },
  {
    id: 'a3', slug: 'anneaux-gymnastique-bois',
    name: 'Anneaux de Gymnastique Bois + Sangles',
    brand: 'WODFitters',
    description: 'Paire d\'anneaux en bois avec sangles réglables numérotées. Dips, tractions, muscle-ups — calisthénie et CrossFit.',
    longDescription: 'Les anneaux de gymnastique développent une force et une stabilité que les machines ne permettent pas. Bois véritable au grip naturel même en sueur, sangles longues (4,5 m) réglables et numérotées pour retrouver son réglage, boucles à serrage rapide. Pour dips, tractions, L-sit et muscle-ups.',
    type: 'physical', price_cents: 3490, stripe_price_id: 'price_aff_a3',
    images: ['https://m.media-amazon.com/images/I/71PITcaG7fL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🆕 Nouveau', category: 'Équipements', rating: 4.8, reviews: 3120, inStock: true,
    tags: ['anneaux gymnastique', 'calisthénie', 'crossfit', 'street workout'],
    disciplines: ['crossfit', 'musculation'],
    features: ['Bois grip naturel', 'Sangles 4,5 m numérotées', 'Serrage rapide', 'Dips & tractions', 'Muscle-ups'],
    amazon: { asin: 'B07ANNEAU01', affiliateUrl: amazonUrl('anneaux de gymnastique bois') },
    isAffiliate: true,
  },
  {
    id: 'a4', slug: 'poignees-pompes-rotatives',
    name: 'Poignées à Pompes Rotatives (paire)',
    brand: 'Perfect Fitness',
    description: 'Push-up bars rotatives qui réduisent la tension sur poignets et épaules. Amplitude accrue pour des pectoraux ciselés.',
    longDescription: 'Les poignées rotatives suivent le mouvement naturel des bras pendant la pompe : moins de tension sur les poignets, recrutement musculaire optimisé et amplitude augmentée pour des pectoraux et triceps plus sollicités. Base large antidérapante, prise ergonomique. Légères et nomades.',
    type: 'physical', price_cents: 1990, stripe_price_id: 'price_aff_a4',
    images: ['https://images.pexels.com/photos/4162487/pexels-photo-4162487.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🤲 Grip', category: 'Équipements', rating: 4.5, reviews: 2640, inStock: true,
    tags: ['pompes', 'push-up', 'pectoraux', 'poids du corps'],
    disciplines: ['musculation', 'crossfit', 'hiit'],
    features: ['Rotation naturelle', 'Préserve les poignets', 'Amplitude accrue', 'Base antidérapante', 'Nomades'],
    amazon: { asin: 'B07POMPES01', affiliateUrl: amazonUrl('poignées à pompes rotatives') },
    isAffiliate: true,
  },
  {
    id: 'a5', slug: 'sac-sport-resistant-40l',
    name: 'Sac de Sport 40L avec Compartiment Chaussures',
    brand: 'Under Armour',
    description: 'Sac de sport résistant 40L, compartiment chaussures aéré et poche humide. Idéal salle, voyage et week-end.',
    longDescription: 'Un sac pensé pour l\'athlète : 40 L de volume, compartiment chaussures séparé et ventilé, poche étanche pour les affaires humides, bandoulière rembourrée et tissu déperlant ultra-résistant. Assez grand pour la salle comme pour un week-end, assez solide pour durer des années.',
    type: 'physical', price_cents: 3990, original_price_cents: 5490, stripe_price_id: 'price_aff_a5',
    images: ['https://m.media-amazon.com/images/I/81uEkxwPQeL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🎒 Bestseller', category: 'Vêtements', rating: 4.8, reviews: 6740, inStock: true,
    tags: ['sac de sport', 'gym bag', 'voyage', 'accessoire'],
    disciplines: ['musculation', 'crossfit', 'running-cardio', 'natation', 'boxing'],
    features: ['40 L', 'Compartiment chaussures aéré', 'Poche humide étanche', 'Tissu déperlant', 'Bandoulière rembourrée'],
    amazon: { asin: 'B08SAC00001', affiliateUrl: amazonUrl('sac de sport compartiment chaussures') },
    isAffiliate: true, featured: true,
  },
  {
    id: 'a6', slug: 'gourde-isotherme-2l',
    name: 'Gourde Isotherme Sport 2L Inox',
    brand: 'BOTC',
    description: 'Gourde 2L double paroi inox, garde froid 24h. Graduée, anti-fuite, large goulot. Hydratation des longues séances.',
    longDescription: 'Rester hydraté change tout à la performance. Cette gourde 2 L en inox double paroi garde l\'eau fraîche 24 h, ne transpire pas, et son large goulot facilite le remplissage et les glaçons. Graduations pour suivre sa consommation, bouchon anti-fuite et poignée de transport. Sans BPA.',
    type: 'physical', price_cents: 2290, stripe_price_id: 'price_aff_a6',
    images: ['https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80'],
    badge: '💧 Hydratation', category: 'Recovery', rating: 4.6, reviews: 5120, inStock: true,
    tags: ['gourde', 'hydratation', 'inox', 'sport'],
    disciplines: ['musculation', 'running-cardio', 'crossfit', 'hiit', 'nutrition', 'cyclisme', 'natation', 'boxing', 'yoga'],
    features: ['2 L double paroi', 'Froid 24 h', 'Graduée', 'Anti-fuite', 'Sans BPA'],
    amazon: { asin: 'B08GOURDE01', affiliateUrl: amazonUrl('gourde isotherme sport 2L inox') },
    isAffiliate: true,
  },
  {
    id: 'a7', slug: 'shaker-proteine-700ml',
    name: 'Shaker Protéine 700ml Anti-Fuite + Boule',
    brand: 'BlenderBottle',
    description: 'Shaker 700ml avec boule mélangeuse inox, sans grumeaux. Bouchon hermétique anti-fuite, graduations, sans BPA.',
    longDescription: 'Le shaker de référence : boule fil inox BlenderBall qui dissout whey, BCAA et pre-workout sans grumeaux, bouchon hermétique 100 % anti-fuite (même dans le sac), graduations en oz et ml, plastique sans BPA. Le compagnon indispensable de chaque séance.',
    type: 'physical', price_cents: 1290, stripe_price_id: 'price_aff_a7',
    images: ['https://m.media-amazon.com/images/I/71TwGJa9u9L._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🥤 Essentiel', category: 'Nutrition', rating: 4.8, reviews: 14820, inStock: true,
    tags: ['shaker', 'protéine', 'whey', 'nutrition'],
    disciplines: ['musculation', 'crossfit', 'hiit', 'running-cardio', 'nutrition'],
    features: ['Boule inox sans grumeaux', '700 ml', 'Anti-fuite hermétique', 'Graduations oz/ml', 'Sans BPA'],
    amazon: { asin: 'B08SHAKER01', affiliateUrl: amazonUrl('shaker protéine blender bottle') },
    isAffiliate: true, featured: true,
  },
  {
    id: 'a8', slug: 'ecouteurs-sport-bluetooth',
    name: 'Écouteurs Sport Bluetooth Étanches IPX7',
    brand: 'SoundPEATS',
    description: 'Écouteurs sans fil à crochets, maintien parfait, étanches IPX7. 40h d\'autonomie, basses profondes. Running et muscu.',
    longDescription: 'Conçus pour le sport : crochets souples pour un maintien à toute épreuve, certification étanche IPX7 (sueur et pluie), 40 h d\'autonomie avec le boîtier, basses profondes et appels clairs. Bluetooth 5.3 stable, commandes tactiles. Ta playlist te suit du warm-up au dernier sprint.',
    type: 'physical', price_cents: 3490, original_price_cents: 4990, stripe_price_id: 'price_aff_a8',
    images: ['https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=800&q=80'],
    badge: '🎧 IPX7', category: 'Tech', rating: 4.6, reviews: 9870, inStock: true,
    tags: ['écouteurs', 'bluetooth', 'sport', 'running'],
    disciplines: ['running-cardio', 'musculation', 'hiit', 'cyclisme'],
    features: ['Maintien à crochets', 'Étanches IPX7', '40 h d\'autonomie', 'Basses profondes', 'Bluetooth 5.3'],
    amazon: { asin: 'B08ECOUTE01', affiliateUrl: amazonUrl('écouteurs sport bluetooth étanche') },
    isAffiliate: true, featured: true,
  },

  // ─── BOXE (affiliation Amazon) ────────────────────────────────────
  {
    id: 'b1', slug: 'gants-boxe-12oz', name: 'Gants de Boxe 12oz Cuir Synthétique', brand: 'RDX',
    description: 'Gants de boxe 12oz rembourrage multicouche, maintien du poignet, intérieur respirant. Sac, sparring et fitness boxing.',
    longDescription: 'Gants polyvalents au rembourrage multicouche absorbant les chocs, fermeture velcro maintenant le poignet et doublure anti-odeur respirante — pour le sac, le sparring léger et les cours de boxe fitness.',
    type: 'physical', price_cents: 2990, original_price_cents: 3990, stripe_price_id: 'price_aff_b1',
    images: ['https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?auto=format&fit=crop&w=800&q=80'],
    badge: '🥊 Best Seller', category: 'Équipements', rating: 4.7, reviews: 7320, inStock: true,
    tags: ['gants de boxe', 'boxe', 'sac de frappe', 'sparring'], disciplines: ['boxing', 'hiit', 'crossfit'],
    features: ['12oz multicouche', 'Maintien du poignet', 'Doublure respirante', 'Cuir synthétique durable', 'Sac & sparring'],
    amazon: { asin: 'B08BOXE0001', affiliateUrl: amazonUrl('gants de boxe 12oz') }, isAffiliate: true, featured: true,
  },
  {
    id: 'b2', slug: 'bandes-boxe-maintien', name: 'Bandes de Maintien Boxe 4,5m (paire)', brand: 'Venum',
    description: 'Bandes semi-élastiques 4,5m, protègent poignets et articulations. Velcro et boucle pouce. Indispensable avant les gants.',
    longDescription: 'Les bandes de maintien protègent poignets et phalanges sous les gants : tissu semi-élastique de 4,5 m, boucle pouce et velcro large pour un serrage précis. Lavables et durables.',
    type: 'physical', price_cents: 990, stripe_price_id: 'price_aff_b2',
    images: ['https://m.media-amazon.com/images/I/71x9jOulKML._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🥊 Essentiel', category: 'Équipements', rating: 4.8, reviews: 9140, inStock: true,
    tags: ['bandes de boxe', 'wraps', 'boxe', 'protection'], disciplines: ['boxing', 'hiit'],
    features: ['4,5 m par bande', 'Protège poignets & phalanges', 'Boucle pouce', 'Velcro large', 'Lavables'],
    amazon: { asin: 'B08BOXE0002', affiliateUrl: amazonUrl('bandes de boxe maintien wraps') }, isAffiliate: true,
  },
  {
    id: 'b3', slug: 'sac-frappe-120cm', name: 'Sac de Frappe Lesté 120cm + Chaîne', brand: 'Outshock',
    description: 'Sac de frappe 120cm garni, suspension chaîne et émerillon anti-torsion. Boxe, kickboxing et défoulement cardio.',
    longDescription: 'Sac de frappe de 120 cm au garnissage dense et homogène, livré avec chaîne renforcée et émerillon anti-torsion. Surface résistante aux frappes répétées — pieds-poings, boxe et cardio défouloir.',
    type: 'physical', price_cents: 6990, original_price_cents: 8990, stripe_price_id: 'price_aff_b3',
    images: ['https://images.unsplash.com/photo-1517438476312-10d79c077509?auto=format&fit=crop&w=800&q=80'],
    badge: '🥊 Pro', category: 'Équipements', rating: 4.6, reviews: 3210, inStock: true,
    tags: ['sac de frappe', 'boxe', 'kickboxing', 'cardio'], disciplines: ['boxing', 'crossfit', 'hiit'],
    features: ['120 cm garni', 'Chaîne + émerillon', 'Anti-torsion', 'Surface résistante', 'Boxe & cardio'],
    amazon: { asin: 'B08BOXE0003', affiliateUrl: amazonUrl('sac de frappe 120cm') }, isAffiliate: true,
  },
  {
    id: 'b4', slug: 'pattes-ours-focus-mitts', name: 'Pattes d\'Ours / Focus Mitts (paire)', brand: 'RDX',
    description: 'Paire de pattes d\'ours incurvées, cible de frappe rembourrée. Travail vitesse, précision et combos à deux.',
    longDescription: 'Cibles de frappe incurvées au rembourrage multicouche absorbant l\'impact, gant ergonomique respirant. Idéales pour travailler vitesse, précision et enchaînements à deux.',
    type: 'physical', price_cents: 2490, stripe_price_id: 'price_aff_b4',
    images: ['https://images.pexels.com/photos/4754146/pexels-photo-4754146.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🥊 Duo', category: 'Équipements', rating: 4.7, reviews: 2180, inStock: true,
    tags: ['pattes d\'ours', 'focus mitts', 'boxe', 'précision'], disciplines: ['boxing', 'hiit'],
    features: ['Incurvées multicouche', 'Absorbent l\'impact', 'Gant respirant', 'Vitesse & précision', 'Travail à deux'],
    amazon: { asin: 'B08BOXE0004', affiliateUrl: amazonUrl('pattes d\'ours focus mitts boxe') }, isAffiliate: true,
  },
  {
    id: 'b5', slug: 'sac-frappe-autoportant', name: 'Sac de Frappe sur Pied Autoportant', brand: 'FITVED',
    description: 'Sac de frappe autoportant, base à remplir (eau/sable), hauteur réglable. Aucun perçage, idéal appartement.',
    longDescription: 'Sac de frappe sur pied avec base lestable (eau ou sable) et hauteur réglable : s\'installe partout sans perçage, revient en position après chaque frappe. Parfait pour la boxe et le cardio à domicile.',
    type: 'physical', price_cents: 9990, original_price_cents: 12990, stripe_price_id: 'price_aff_b5',
    images: ['https://images.unsplash.com/photo-1591117207239-788bf8de6c3b?auto=format&fit=crop&w=800&q=80'],
    badge: '🥊 Sans perçage', category: 'Équipements', rating: 4.5, reviews: 4760, inStock: true,
    tags: ['sac de frappe', 'autoportant', 'boxe', 'maison'], disciplines: ['boxing', 'hiit', 'crossfit'],
    features: ['Base lestable eau/sable', 'Hauteur réglable', 'Sans perçage', 'Retour automatique', 'Idéal appartement'],
    amazon: { asin: 'B08BOXE0005', affiliateUrl: amazonUrl('sac de frappe sur pied autoportant') }, isAffiliate: true,
  },

  // ─── YOGA / MOBILITÉ / ÉTIREMENT (affiliation Amazon) ──────────────
  {
    id: 'm1', slug: 'briques-yoga-liege', name: 'Briques de Yoga Liège (lot de 2)', brand: 'Lzcasac',
    description: 'Paire de briques en liège naturel, antidérapantes, soutiennent les postures et améliorent l\'alignement.',
    longDescription: 'Briques en liège naturel au grip ferme et antidérapant : soutiennent les postures, sécurisent les étirements profonds et améliorent l\'alignement. Légères et durables.',
    type: 'physical', price_cents: 1790, stripe_price_id: 'price_aff_m1',
    images: ['https://m.media-amazon.com/images/I/81uRmVePuZL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🧘 Naturel', category: 'Équipements', rating: 4.8, reviews: 5630, inStock: true,
    tags: ['brique yoga', 'liège', 'yoga', 'étirement'], disciplines: ['yoga', 'stretching'],
    features: ['Liège naturel', 'Antidérapantes', 'Soutien des postures', 'Alignement', 'Lot de 2'],
    amazon: { asin: 'B08YOGA0001', affiliateUrl: amazonUrl('briques de yoga liège') }, isAffiliate: true, featured: true,
  },
  {
    id: 'm2', slug: 'sangle-etirement-yoga', name: 'Sangle d\'Étirement Yoga 10 Boucles', brand: 'REEHUT',
    description: 'Sangle d\'étirement à 10 boucles, gagne en souplesse en sécurité. Idéale yoga, mobilité et rééducation.',
    longDescription: 'Sangle à 10 boucles numérotées pour progresser en souplesse en toute sécurité, sans partenaire : étirements guidés des ischios, hanches et épaules. Tissu résistant non extensible.',
    type: 'physical', price_cents: 1290, stripe_price_id: 'price_aff_m2',
    images: ['https://images.pexels.com/photos/4327024/pexels-photo-4327024.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🧘 Souplesse', category: 'Équipements', rating: 4.7, reviews: 4120, inStock: true,
    tags: ['sangle étirement', 'yoga', 'mobilité', 'souplesse'], disciplines: ['stretching', 'yoga'],
    features: ['10 boucles', 'Étirement guidé', 'Sans partenaire', 'Tissu non extensible', 'Yoga & mobilité'],
    amazon: { asin: 'B08YOGA0002', affiliateUrl: amazonUrl('sangle d\'étirement yoga boucles') }, isAffiliate: true,
  },
  {
    id: 'm3', slug: 'roue-yoga-dorsale', name: 'Roue de Yoga Dorsale Anti-Douleur', brand: 'UPCircleSeven',
    description: 'Roue de yoga pour ouvrir la poitrine, étirer le dos et soulager les tensions. Supporte jusqu\'à 150 kg.',
    longDescription: 'La roue de yoga ouvre la cage thoracique, étire la colonne et relâche les tensions dorsales : surface rembourrée antidérapante, structure ABS supportant jusqu\'à 150 kg. Mobilité et bien-être.',
    type: 'physical', price_cents: 2290, stripe_price_id: 'price_aff_m3',
    images: ['https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80'],
    badge: '🧘 Mobilité', category: 'Équipements', rating: 4.6, reviews: 3240, inStock: true,
    tags: ['roue de yoga', 'dos', 'mobilité', 'étirement'], disciplines: ['yoga', 'stretching'],
    features: ['Ouvre la poitrine', 'Étire le dos', 'Jusqu\'à 150 kg', 'Antidérapante', 'Anti-tensions'],
    amazon: { asin: 'B08YOGA0003', affiliateUrl: amazonUrl('roue de yoga dorsale') }, isAffiliate: true,
  },
  {
    id: 'm4', slug: 'bandes-mobilite-loop', name: 'Bandes de Mobilité Loop (set de 5)', brand: 'Fit Simplify',
    description: 'Set de 5 mini-bandes loop, 5 résistances. Activation, mobilité hanches/épaules, fessiers et rééducation.',
    longDescription: 'Cinq mini-bandes en boucle (5 résistances) pour l\'échauffement, l\'activation des fessiers, la mobilité hanches et épaules et la rééducation. Tissu antidérapant qui ne roule pas, pochette incluse.',
    type: 'physical', price_cents: 1490, stripe_price_id: 'price_aff_m4',
    images: ['https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=80'],
    badge: '🧘 Activation', category: 'Équipements', rating: 4.7, reviews: 8910, inStock: true,
    tags: ['bandes loop', 'mobilité', 'fessiers', 'activation'], disciplines: ['stretching', 'yoga', 'musculation'],
    features: ['5 résistances', 'Anti-roulement', 'Mobilité & activation', 'Fessiers', 'Pochette incluse'],
    amazon: { asin: 'B08YOGA0004', affiliateUrl: amazonUrl('bandes de mobilité loop fessiers') }, isAffiliate: true,
  },
  {
    id: 'm5', slug: 'balles-massage-trigger', name: 'Balles de Massage Trigger (set de 3)', brand: 'TriggerPoint',
    description: 'Set de 3 balles de densités variées, ciblent les points de tension. Auto-massage, mobilité et récupération.',
    longDescription: 'Trois balles de densités progressives pour libérer les points de tension (pieds, dos, fessiers, épaules) : auto-massage myofascial précis, parfait avant l\'effort et en récupération.',
    type: 'physical', price_cents: 1590, stripe_price_id: 'price_aff_m5',
    images: ['https://m.media-amazon.com/images/I/811xXVVv42L._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🧘 Récup', category: 'Recovery', rating: 4.8, reviews: 6210, inStock: true,
    tags: ['balle de massage', 'trigger point', 'mobilité', 'récupération'], disciplines: ['stretching', 'yoga'],
    features: ['3 densités', 'Auto-massage ciblé', 'Points de tension', 'Avant/après effort', 'Compactes'],
    amazon: { asin: 'B08YOGA0005', affiliateUrl: amazonUrl('balle de massage trigger point') }, isAffiliate: true,
  },
  {
    id: 'm6', slug: 'elastique-stretching-pro', name: 'Élastique de Stretching Pro Multi-Boucles', brand: 'PROIRON',
    description: 'Élastique d\'étirement multi-boucles pour danse, gym et mobilité. Progression de souplesse guidée et douce.',
    longDescription: 'Élastique multi-boucles épais pour étirements guidés (danse, gym, arts martiaux, mobilité) : progression douce et mesurée de la souplesse, sans à-coups. Compact et nomade.',
    type: 'physical', price_cents: 1190, stripe_price_id: 'price_aff_m6',
    images: ['https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=800&q=80'],
    badge: '🧘 Souplesse', category: 'Équipements', rating: 4.6, reviews: 2740, inStock: true,
    tags: ['élastique étirement', 'stretching', 'souplesse', 'mobilité'], disciplines: ['stretching', 'yoga'],
    features: ['Multi-boucles épais', 'Étirement guidé', 'Progression douce', 'Danse & gym', 'Nomade'],
    amazon: { asin: 'B08YOGA0006', affiliateUrl: amazonUrl('élastique de stretching multi boucles') }, isAffiliate: true,
  },

  // ─── NUTRITION (affiliation Amazon) ───────────────────────────────
  {
    id: 'u1', slug: 'pre-workout-energie', name: 'Pré-Workout Énergie & Focus', brand: 'Optimum Nutrition',
    description: 'Booster pré-entraînement : caféine, bêta-alanine et citrulline pour énergie, congestion et focus. Sans sucre.',
    longDescription: 'Formule pré-entraînement dosée en caféine, bêta-alanine et L-citrulline pour plus d\'énergie, de congestion musculaire et de concentration, sans sucre. Saveur fruitée, dissolution rapide.',
    type: 'physical', price_cents: 2790, stripe_price_id: 'price_aff_u1',
    images: ['https://m.media-amazon.com/images/I/71kR0P7izKL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '⚡ Énergie', category: 'Nutrition', rating: 4.6, reviews: 11240, inStock: true,
    tags: ['pre-workout', 'caféine', 'énergie', 'nutrition'], disciplines: ['nutrition', 'musculation', 'crossfit'],
    features: ['Caféine + bêta-alanine', 'L-citrulline', 'Énergie & focus', 'Sans sucre', 'Dissolution rapide'],
    amazon: { asin: 'B08NUTR0001', affiliateUrl: amazonUrl('pre workout énergie focus') }, isAffiliate: true, featured: true,
  },
  {
    id: 'u2', slug: 'electrolytes-hydratation', name: 'Électrolytes Hydratation (tablettes)', brand: 'High5',
    description: 'Tablettes effervescentes sodium/potassium/magnésium. Réhydratation et anti-crampes pour l\'endurance.',
    longDescription: 'Tablettes effervescentes apportant sodium, potassium et magnésium pour compenser les pertes en sueur : réhydratation efficace et prévention des crampes sur les efforts longs. Peu de calories.',
    type: 'physical', price_cents: 990, stripe_price_id: 'price_aff_u2',
    images: ['https://images.pexels.com/photos/4397833/pexels-photo-4397833.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '💧 Endurance', category: 'Nutrition', rating: 4.7, reviews: 8420, inStock: true,
    tags: ['électrolytes', 'hydratation', 'endurance', 'nutrition'], disciplines: ['nutrition', 'running-cardio', 'cyclisme'],
    features: ['Sodium/potassium/magnésium', 'Anti-crampes', 'Réhydratation', 'Effervescentes', 'Peu caloriques'],
    amazon: { asin: 'B08NUTR0002', affiliateUrl: amazonUrl('électrolytes hydratation tablettes') }, isAffiliate: true,
  },
  {
    id: 'u3', slug: 'barres-proteinees-12', name: 'Barres Protéinées 20g (boîte de 12)', brand: 'Barebells',
    description: 'Barres 20g de protéines, faibles en sucre, enrobage gourmand. En-cas idéal post-training ou nomade.',
    longDescription: 'Barres apportant 20 g de protéines, faibles en sucres, à la texture moelleuse et l\'enrobage gourmand : l\'en-cas parfait après l\'entraînement ou en déplacement. Boîte de 12.',
    type: 'physical', price_cents: 2490, stripe_price_id: 'price_aff_u3',
    images: ['https://m.media-amazon.com/images/I/71uG6aW4HEL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🍫 En-cas', category: 'Nutrition', rating: 4.7, reviews: 15320, inStock: true,
    tags: ['barres protéinées', 'protéine', 'en-cas', 'nutrition'], disciplines: ['nutrition', 'musculation', 'running-cardio'],
    features: ['20 g de protéines', 'Faible en sucre', 'Enrobage gourmand', 'Boîte de 12', 'Nomade'],
    amazon: { asin: 'B08NUTR0003', affiliateUrl: amazonUrl('barres protéinées 20g') }, isAffiliate: true,
  },
  {
    id: 'u4', slug: 'omega-3-epa-dha', name: 'Oméga-3 EPA/DHA (120 capsules)', brand: 'MyProtein',
    description: 'Huile de poisson concentrée EPA/DHA. Cœur, articulations et récupération. Sans arrière-goût.',
    longDescription: 'Capsules d\'huile de poisson concentrée en EPA et DHA pour soutenir le cœur, les articulations et la récupération : qualité purifiée, sans arrière-goût. 120 capsules.',
    type: 'physical', price_cents: 1490, stripe_price_id: 'price_aff_u4',
    images: ['https://m.media-amazon.com/images/I/71SzJT1cSGL._AC_SL1500_.jpg'], imageFit: 'contain',
    badge: '🐟 Récup', category: 'Nutrition', rating: 4.8, reviews: 9870, inStock: true,
    tags: ['oméga-3', 'epa dha', 'récupération', 'nutrition'], disciplines: ['nutrition', 'running-cardio', 'musculation'],
    features: ['EPA/DHA concentré', 'Cœur & articulations', 'Récupération', 'Sans arrière-goût', '120 capsules'],
    amazon: { asin: 'B08NUTR0004', affiliateUrl: amazonUrl('oméga 3 epa dha capsules') }, isAffiliate: true,
  },

  // ─── NATATION (affiliation Amazon) ────────────────────────────────
  {
    id: 'w1', slug: 'plaquettes-natation', name: 'Plaquettes de Natation (paire)', brand: 'Arena',
    description: 'Plaquettes mains pour renforcer le haut du corps et perfectionner l\'appui. Sangles réglables.',
    longDescription: 'Plaquettes de natation augmentant la surface d\'appui pour renforcer dos, épaules et bras tout en affinant la technique de traction. Sangles silicone réglables, plusieurs tailles.',
    type: 'physical', price_cents: 1690, stripe_price_id: 'price_aff_w1',
    images: ['https://images.pexels.com/photos/863988/pexels-photo-863988.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🏊 Technique', category: 'Équipements', rating: 4.6, reviews: 2980, inStock: true,
    tags: ['plaquettes', 'natation', 'technique', 'force'], disciplines: ['natation'],
    features: ['Renforce le haut du corps', 'Perfectionne l\'appui', 'Sangles réglables', 'Plusieurs tailles', 'Entraînement piscine'],
    amazon: { asin: 'B08SWIM0001', affiliateUrl: amazonUrl('plaquettes de natation') }, isAffiliate: true,
  },
  {
    id: 'w2', slug: 'pull-buoy-natation', name: 'Pull Buoy Flotteur Jambes', brand: 'Speedo',
    description: 'Pull buoy entre les cuisses : isole le travail des bras et améliore la position du corps. Mousse durable.',
    longDescription: 'Le pull buoy se cale entre les cuisses pour immobiliser les jambes et concentrer l\'effort sur les bras et le gainage, tout en améliorant l\'alignement du corps dans l\'eau. Mousse EVA durable.',
    type: 'physical', price_cents: 1390, stripe_price_id: 'price_aff_w2',
    images: ['https://images.pexels.com/photos/1263348/pexels-photo-1263348.jpeg?auto=compress&cs=tinysrgb&w=800'],
    badge: '🏊 Gainage', category: 'Équipements', rating: 4.7, reviews: 3410, inStock: true,
    tags: ['pull buoy', 'natation', 'flotteur', 'technique'], disciplines: ['natation'],
    features: ['Isole le travail des bras', 'Améliore la position', 'Mousse EVA durable', 'Gainage', 'Entraînement piscine'],
    amazon: { asin: 'B08SWIM0002', affiliateUrl: amazonUrl('pull buoy natation') }, isAffiliate: true,
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return PRODUCTS.find(p => p.slug === slug)
}

export function getProductById(id: string): Product | undefined {
  return PRODUCTS.find(p => p.id === id)
}

export function getProductsByCategory(category: string): Product[] {
  return PRODUCTS.filter(p => p.category === category)
}

export function getProductsByDiscipline(discipline: string): Product[] {
  return PRODUCTS.filter(p => p.disciplines?.includes(discipline))
}

export function getCategories(): ProductCategory[] {
  return [...new Set(PRODUCTS.map(p => p.category))] as ProductCategory[]
}

export function getAffiliateProducts(): Product[] {
  return PRODUCTS.filter(p => p.isAffiliate)
}

export function formatPrice(cents: number): string {
  return new Intl.NumberFormat('fr-FR', { style: 'currency', currency: 'EUR' }).format(cents / 100)
}

export const CATEGORY_ICONS: Record<string, string> = {
  'Équipements': '🏋️',
  'Nutrition':   '🥗',
  'Vêtements':   '👕',
  'Programmes':  '📋',
  'Cardio':      '🚴',
  'Recovery':    '💆',
  'Tech':        '⌚',
}

