/* ── Catalogue produits - version allemande ───────────────────── */
/* On réutilise PRODUCTS (FR) pour tout le structurel (id, slug, prix, images,
   category-clé, amazon, disciplines…) et on ne surcharge que les champs texte. */

import { PRODUCTS, amazonSearchUrl, AMAZON_TAG_DE, type Product } from './products'

type ProductText = Pick<Product, 'name' | 'description' | 'features' | 'tags'> & {
  badge?: string | null
  level?: string
  duration?: string
  longDescription?: string // optionnel : repli FR (non affiché sur les cartes affiliées)
}

const TEXT_DE: Record<string, ProductText> = {
  e1: {
    name: 'Gusseisen-Kettlebell Pro 20 kg - CORENGTH',
    badge: '⭐ Bestseller',
    description: '20-kg-Kettlebell aus Gusseisen mit rutschfester Gummibasis und sandgestrahltem Griff für CrossFit, HIIT und funktionelles Krafttraining.',
    longDescription: 'Für anspruchsvolle Athleten konzipiert, bietet diese zu 80% recycelte Gusseisen-Kettlebell einen sandgestrahlten Griff für perfekten Halt auch beim Schwitzen. Die Gummibasis schützt den Boden und sorgt für perfekte Stabilität. Ideal für Swings, Turkish Get-ups, Clean & Press und Snatches.',
    features: ['20 kg - ideal für CrossFit & HIIT', 'Zu 80% recyceltes Gusseisen', 'Rutschfeste Gummibasis', 'Sandgestrahlter Griff, optimaler Halt', '2 Jahre Garantie'],
    tags: ['kettlebell', 'crossfit', 'kraft', 'training'],
  },
  e2: {
    name: 'Widerstandsband-Set × 5 - PORTENTUM',
    badge: '🔥 Sale',
    description: 'Set aus 5 Widerstandsbändern für Kraft und Fitness. Progressiver Widerstand von 25 bis 125 lbs. Ideal für ein komplettes Heimtraining.',
    longDescription: 'Das PORTENTUM-Set umfasst 5 Widerstandsbänder in verschiedenen Farben (von 25-65 lbs bis 50-125 lbs) für ein progressives, komplettes Training. Perfekt für Kraft, CrossFit, Yoga, Reha und Muskelkräftigung zu Hause oder unterwegs. Langlebig, rutschfest und leicht zu transportieren.',
    features: ['5 Stufen: 25 bis 125 lbs', 'Komplett Kraft & Fitness', 'Langlebig rutschfest', 'Ideal für zu Hause', 'Leicht zu transportieren'],
    tags: ['widerstandsbänder', 'widerstand', 'fitness', 'kraft'],
  },
  e3: {
    name: 'Premium rutschfeste Yogamatte 10 mm',
    description: 'Doppelseitige, umweltfreundliche TPE-Yogamatte mit 10 mm. Perfekt rutschfest, 183×61 cm. Tragegurt inklusive.',
    longDescription: 'Die Gaiam-Premium-Matte bietet eine Dicke von 10 mm für perfekte Gelenkdämpfung. Ihre strukturierte doppelseitige Oberfläche garantiert maximalen Halt auf jedem Boden. Das TPE-Material ist frei von PVC, Latex und Phthalaten - ideal für umweltbewusste Praktizierende.',
    features: ['10 mm Premium-Komfort', 'Rutschfest doppelseitig', 'TPE, PVC- und latexfrei', '183×61 cm', 'Tragegurt inklusive'],
    tags: ['yogamatte', 'pilates', 'meditation', 'stretching'],
  },
  e4: {
    name: 'Speed-CrossFit-Springseil - Reebok',
    badge: '⚡ Pro',
    description: 'Springseil mit beschichtetem Stahlkabel, Aluminium-Kugellager. Verstellbar 2,5-3,5 m. Perfekt für HIIT und Boxen.',
    longDescription: 'Das Reebok-Speed-Springseil ist für CrossFit-Athleten und Boxer gemacht. Ultraleichtes Stahlkabel, Präzisions-Kugellager für reibungslose Rotation bei hoher Geschwindigkeit. Ergonomische Griffe aus gebürstetem Aluminium. Ideal für Double-Unders und intensives HIIT.',
    features: ['Beschichtetes Stahlkabel', 'Präzisions-Aluminiumlager', 'Verstellbar 2,5-3,5 m', 'Ergonomische Griffe', 'Tragetasche'],
    tags: ['springseil', 'cardio', 'crossfit', 'boxen'],
  },
  e5: {
    name: 'Verstellbare Hanteln 2-24 kg - Bowflex SelectTech',
    badge: '💪 Premium',
    description: 'Ersetzt 15 Hantelpaare. Wähle das Gewicht in 2 Sekunden von 2 bis 24 kg. Ergonomisches Design.',
    longDescription: 'Die Bowflex-SelectTech-552i-Hanteln sind die weltweite Referenz bei verstellbaren Hanteln. Eine einfache Drehung am Rad ersetzt bis zu 15 klassische Hantelpaare. Enorme Einsparung an Platz und Budget. Struktur aus verchromtem Stahl mit rutschfester Beschichtung.',
    features: ['2 bis 24 kg in 2 Sekunden', 'Ersetzt 15 Paare', 'Bauweise aus verchromtem Stahl', 'Rutschfeste Beschichtung', '2 Jahre Garantie'],
    tags: ['hanteln', 'kraft', 'home gym', 'training'],
  },
  e6: {
    name: 'Vernetztes Heimtrainer-Fahrrad - DOMYOS VC500',
    badge: '🚴 Vernetzt',
    description: 'Vernetztes Cardio-Fahrrad mit 24 Stufen magnetischem Widerstand. LCD-Display. Verstellbarer Sitz und Lenker. Verbindet sich mit Fitness-Apps.',
    longDescription: 'Das DOMYOS-VC500-Fahrrad ist ideal für Indoor-Cycling. Ultraleiser magnetischer Widerstand, 24 progressive Stufen. Kompatibel mit Decathlon Coach, Zwift und Kinomap via Bluetooth. Breiter Komfortsitz, in Höhe und Tiefe verstellbar. LCD-Konsole zeigt Geschwindigkeit, Distanz, Kalorien und Herzfrequenz.',
    features: ['24 magnetische Stufen', 'Bluetooth vernetzt', 'Zwift/Kinomap-kompatibel', 'Verstellbarer Komfortsitz', 'Komplette LCD-Konsole'],
    tags: ['fahrrad', 'cardio', 'indoor cycling', 'vernetzt'],
  },
  e7: {
    name: 'Pro-Bauchroller - Doppelrad + Kniematte',
    badge: '🔥 Sale',
    description: 'Bauchroller mit Doppellager und Kniematte. Stärkt Bauch, Rumpf und Rücken. Rutschfest, in einer Minute montiert.',
    longDescription: 'Der PROIRON-Bauchroller trainiert in einer einzigen Bewegung tief deinen gesamten Rumpf, Rücken und die Schultern. Sein breites Doppelrad sorgt für perfekte Stabilität für kontrollierte Wiederholungen ohne Wackeln. Ergonomische rutschfeste Griffe geben sicheren Halt auch beim Schwitzen. Mit Kniematte zum Schutz deiner Gelenke. Kompakt, verstaubar überall und in unter einer Minute montiert - ideal für Rumpftraining zu Hause.',
    features: ['Ultrastabiles Doppelrad', 'Kniematte inklusive', 'Stärkt Bauch, Rücken & Rumpf', 'Rutschfeste Griffe', 'Kompakt - 1-Min-Montage'],
    tags: ['bauchroller', 'bauch', 'rumpf', 'kraft'],
  },
  n1: {
    name: 'Impact Whey Protein Schokolade 1 kg - MyProtein',
    badge: '🏆 Nr. 1 in Europa',
    description: 'Nr. 1 in Europa. 22 g Protein, 103 kcal, 5 g BCAAs pro Portion. Von grasgefütterten Kühen. Intensiver Schokoladengeschmack.',
    longDescription: 'Das meistverkaufte Whey in Europa seit 15 Jahren. Hergestellt aus ultragefiltertem Whey von irischen grasgefütterten Kühen. Komplettes Aminosäureprofil mit 5 g BCAAs pro Portion. Mischt sich perfekt in Wasser oder Milch. Ideal nach dem Training, um die Proteinsynthese zu maximieren.',
    features: ['22 g Protein / Portion', 'Nur 103 kcal', '5 g natürliche BCAAs', 'Hergestellt in Europa', 'Ohne Zuckerzusatz'],
    tags: ['whey', 'protein', 'kraft', 'erholung'],
  },
  n2: {
    name: 'Reines Kreatin-Monohydrat 300 g - MyProtein',
    description: 'Zu 99,9% reines mikronisiertes Kreatin. 60 Dosen. Informed-Sport-zertifiziert. Kraft und Power in 4 Wochen.',
    longDescription: 'Kreatin-Monohydrat ist das am besten untersuchte Supplement der Sportwissenschaft, mit Hunderten Studien, die seine Wirksamkeit bestätigen. Die mikronisierte Version von MyProtein löst sich sofort auf und wird schneller aufgenommen. Informed-Sport-zertifiziert - auf Doping getestet. Geschmacksneutral zum Einrühren in jedes Getränk.',
    features: ['99,9% Reinheit', '60 Portionen à 5 g', 'Informed-Sport-zertifiziert', 'Geschmacksneutral', 'Ergebnisse in 4 Wochen'],
    tags: ['kreatin', 'kraft', 'power', 'training'],
  },
  n3: {
    name: 'BCAA Xplode 2:1:1 Fruit Punch 500 g - Olimp',
    badge: '💊 Vegan',
    description: 'BCAAs im Verhältnis 2:1:1. 7 g pro Dosis, 83 Portionen. Vegan-zertifiziert. Erholung, Anti-Katabolismus, Ausdauer.',
    longDescription: 'BCAAs (verzweigtkettige Aminosäuren) im optimierten Verhältnis 2:1:1: Leucin, Isoleucin, Valin. Leucin stimuliert direkt die Proteinsynthese, Isoleucin unterstützt die Glukoseverwertung und Valin reduziert die zentrale Ermüdung. Ideal während des Trainings, um die Muskelmasse zu erhalten.',
    features: ['Optimales Verhältnis 2:1:1', '7 g BCAAs/Dosis', '83 Portionen', 'Vegan-zertifiziert', 'Anti-Katabolismus'],
    tags: ['bcaa', 'erholung', 'ausdauer', 'vegan'],
  },
  r1: {
    name: 'Pro-Massage-Faszienrolle - TriggerPoint GRID',
    badge: '🔵 Pro',
    description: 'Multizonen-Massagerolle mit patentierter GRID-Oberfläche. Simuliert die Hände eines Masseurs. Optimale Erholung.',
    longDescription: 'Die TriggerPoint GRID ist die Faszienrolle der Wahl für Profis. Ihre Oberfläche mit 3 unterschiedlichen Zonen (hohl, röhrenförmig, flach) simuliert Finger, Handflächen und Daumen eines Masseurs. Der hohle Kern sorgt für Haltbarkeit und trägt Gewicht bis 160 kg. Inklusive Zugang zur kompletten Videobibliothek.',
    features: ['GRID-Oberfläche mit 3 Zonen', 'Simuliert eine Profi-Massage', 'Trägt 160 kg', 'Langlebiger Hohlkern', 'Videos inklusive'],
    tags: ['faszienrolle', 'erholung', 'massage', 'mobilität'],
  },
  r2: {
    name: 'Perkussions-Massagepistole - Theragun Mini',
    badge: '🏅 Profi-Athlet',
    description: 'Mini-Perkussionspistole 2400 U/min, 3 Geschwindigkeiten, leise. 150 Min Akku. Kompakt und kraftvoll für schnelle Erholung.',
    longDescription: 'Die Theragun Mini ist die kompakte Version der professionellen Massagepistole, die von NBA-, NFL- und Olympia-Athleten bevorzugt wird. 2400 Schläge/Minute, die 16 mm tief eindringen, um die Durchblutung anzukurbeln und Muskelverspannungen zu lösen. 3 angepasste Geschwindigkeiten. Ultraleiser Betrieb. 150 Minuten Akkulaufzeit.',
    features: ['Kraftvolle 2400 U/min', '3 angepasste Geschwindigkeiten', '150 Min Akku', 'Ultraleise 60 dB', 'Kompakt & reisetauglich'],
    tags: ['massagepistole', 'perkussion', 'erholung', 'theragun'],
  },
  t1: {
    name: 'Multisport-GPS-Smartwatch',
    badge: '⌚ GPS',
    description: 'Multisport-GPS-Uhr mit Handgelenk-Herzfrequenz, Schlaf-Tracking, VO2max und 100+ Sportmodi. Lange Akkulaufzeit.',
    longDescription: 'Die ideale Smartwatch für Athleten: ultrapräzises integriertes GPS, Herzfrequenzsensor am Handgelenk, Schlaf- und Stress-Tracking, VO2max-Schätzung und über 100 Sportprofile (Laufen, Radfahren, Schwimmen, Kraft, HIIT). Kompatibel mit Strava, Apple Health und Google Fit. Wasserdicht mit mehreren Tagen Akkulaufzeit.',
    features: ['Präzises Multisport-GPS', 'Herzfrequenz am Handgelenk', 'Schlaf- & VO2max-Tracking', '100+ Sportmodi', 'Strava- & Apple-Health-kompatibel'],
    tags: ['smartwatch', 'gps', 'cardio', 'running', 'multisport'],
  },
  t2: {
    name: 'Fitness-Aktivitätsarmband',
    badge: '🔥 Sale',
    description: 'Leichtes vernetztes Armband: Schrittzähler, Kalorien, Herzfrequenz, Schlaf und Benachrichtigungen. AMOLED-Display. 14 Tage Akku.',
    longDescription: 'Der perfekte tägliche Fitness-Begleiter. Dieses Aktivitätsarmband erfasst automatisch deine Schritte, verbrannten Kalorien, Herzfrequenz und Schlafqualität. Helles farbiges AMOLED-Display, wasserdicht zum Schwimmen und bis zu 14 Tage Akkulaufzeit. Erhalte deine Benachrichtigungen (Anrufe, SMS, Apps) direkt am Handgelenk. Synchronisiert mit der Xenotif-App via Apple Health / Google Fit.',
    features: ['Schrittzähler & Kalorien', 'Herzfrequenz 24/7', 'Schlaf-Tracking', 'Farbiges AMOLED-Display', '14 Tage Akku'],
    tags: ['fitnessarmband', 'fitness tracker', 'schrittzähler', 'schlaf'],
  },
  t3: {
    name: 'Touchscreen-Smartwatch für Running & Cardio',
    badge: '⌚ AMOLED',
    description: 'AMOLED-Touchscreen-Smartwatch, GPS, EKG, SpO2 und integrierter Lauf-Coach. Bluetooth-Anrufe, kontaktloses Bezahlen, 100+ Ziffernblätter.',
    longDescription: 'Eine Premium-Smartwatch, um dein Training zu transformieren. Großer AMOLED-Touchscreen, integriertes GPS zum Verfolgen deiner Routen, fortschrittliche Sensoren (EKG, Blutsauerstoff SpO2, Herzfrequenz). Integrierter Lauf-Coach mit personalisierten Plänen, Herzfrequenzzonen-Warnungen und Erholung. Nimm Bluetooth-Anrufe an, bezahle kontaktlos und individualisiere aus 100+ Ziffernblättern. Kompatibel mit iOS & Android.',
    features: ['AMOLED-Touchscreen', 'GPS + EKG + SpO2', 'Integrierter Lauf-Coach', 'Bluetooth-Anrufe', 'iOS- & Android-kompatibel'],
    tags: ['smartwatch', 'apple watch', 'ekg', 'running', 'cardio'],
  },
  v1: {
    name: 'Herren-Performance-Trainingsshorts',
    description: '4-Wege-Stretch-Shorts, Dry-Fit feuchtigkeitsableitend. Reißverschlusstasche. Größen S-XXL. Schwarz, grau, navy.',
    longDescription: 'Für Athleten konzipiert, die bei der Leistung keine Kompromisse machen. Das 4-Wege-Stretch-Gewebe umschließt den Körper perfekt, ohne die Bewegung einzuschränken. Die Dry-Fit-Technologie leitet Schweiß 3-mal schneller ab als Baumwolle. Sichere seitliche Reißverschlusstasche für ein Smartphone. Verstärkte Nähte, die intensives Waschen aushalten.',
    features: ['4-Wege-Stretch-Gewebe', 'Dry-Fit feuchtigkeitsableitend', 'Reißverschlusstasche', 'S bis XXL', '3 Farben verfügbar'],
    tags: ['shorts', 'training', 'running', 'herren'],
  },
  v2: {
    name: 'Damen-Kompressionsleggings mit hohem Bund',
    badge: '❤️ Bestseller',
    description: 'Abgestufte Kompression, hoher Bund, blickdichtes Anti-UV-Gewebe. Handytasche. XS-XL. 5 Farben.',
    longDescription: 'Die XENOTIF-Kompressionsleggings bieten optimalen Halt für jede Disziplin. Der flache hohe Bund hält den Bauch, ohne einzuengen. Das blickdichte Gewebe (280 g/m²) ist Anti-UV-zertifiziert und bleibt auch bei Kniebeugen blickdicht. Die abgestufte Kompression verbessert die Durchblutung und reduziert Muskelkater.',
    features: ['Abgestufte Kompression', 'Flacher hoher Bund', 'Blickdicht Anti-UV', 'Handytasche', 'XS bis XL · 5 Farben'],
    tags: ['leggings', 'kompression', 'damen', 'yoga'],
  },
  v3: {
    name: 'Herren-Performance-Kompressionsleggings',
    badge: '🆕 Neu',
    description: 'Herren-Kompressionsleggings, atmungsaktives Funktionsgewebe. Muskelhalt, schnelltrocknend. Ideal für Running, Kraft, CrossFit. S-XXL.',
    longDescription: 'Die XENOTIF-Herren-Kompressionsleggings bieten optimalen Muskelhalt, der Vibration und Ermüdung reduziert. Das 4-Wege-Stretch-Funktionsgewebe leitet Schweiß ab und trocknet schnell. Flache Anti-Scheuer-Nähte, bequemer elastischer Bund und eine Seitentasche. Perfekt allein oder unter Shorts für Running, Kraft, CrossFit oder als Baselayer.',
    features: ['Muskelkompression', '4-Wege-Stretch-Gewebe', 'Schnelltrocknend', 'Anti-Scheuer-Nähte', 'S bis XXL'],
    tags: ['leggings', 'kompression', 'herren', 'running'],
  },
  d1: {
    name: 'Masseaufbau-Programm - Komplett 12 Wochen',
    badge: '📥 Bestseller',
    description: '84 strukturierte Einheiten, 4-Tage/Woche-Split, geführte Laststeigerung. Ernährungsplan + Makros. PDF + Videos.',
    longDescription: 'Das kompletteste Masseaufbau-Programm am Markt. 84 Einheiten über 12 Wochen mit Woche-für-Woche-Laststeigerung. Enthält: detaillierten Muskel-Split, personalisierte Makro-Berechnung nach Körpertyp, Erholungs-Leitfaden, 40+ Übungen in HD-Video illustriert. Integriertes Fortschritts-Tracking in Excel.',
    features: ['84 Einheiten über 12 Wochen', '4-Tage/Woche-Split', 'Geführte Laststeigerung', 'Ernährungsplan + Makros', 'HD-Videos inklusive'],
    tags: ['masseaufbau', 'kraft', 'programm', 'PDF'],
    level: 'Fortgeschritten', duration: '12 Wochen',
  },
  d2: {
    name: 'Definitions-Ernährungsplan - 8 Wochen',
    badge: '📥 Sofort-PDF',
    description: '56 Tage detaillierte Menüs, 40+ Fitness-Rezepte, Einkaufsliste, Makros. Vegan-kompatibel.',
    longDescription: 'Der meistgeladene Definitions-Ernährungsplan der Plattform. 56 Tage abwechslungsreiche Menüs, berechnet von unserer zertifizierten Ernährungsberaterin. Jede Mahlzeit ist optimiert, um die Sättigung zu erhalten und gleichzeitig das nötige Kaloriendefizit zu schaffen. Einfache, schnelle Rezepte (unter 15 Min). Vegan-kompatibel mit einer einzigen Auswahl.',
    features: ['56 Tage Menüs', '40+ Fitness-Rezepte', 'Wöchentliche Einkaufsliste', 'Personalisierte Makros', 'Vegan-kompatibel'],
    tags: ['ernährung', 'definition', 'diät', 'PDF'],
    level: 'Alle Level', duration: '8 Wochen',
  },
  d3: {
    name: 'Fettverbrennungs-HIIT-Programm - 6 Wochen',
    badge: '🔥 Beliebt',
    description: '24 Einheiten à 20-30 Min, 100% Körpergewicht. Keine Ausrüstung. Anfänger → Fortgeschritten. Garantierte Ergebnisse.',
    longDescription: 'Das XENOTIF-HIIT-Programm ist von unserem CrossFit-Level-2-zertifizierten Coach entwickelt. 4 Einheiten pro Woche à 20 bis maximal 30 Minuten, 100% Körpergewicht - keine Ausrüstung erforderlich. Der progressive Aufbau garantiert optimale Anpassung ohne Verletzungsrisiko. Jede Einheit enthält einen integrierten Timer und Demonstrationsvideos.',
    features: ['24 Einheiten à 20-30 Min', 'Keine Ausrüstung', 'Anfänger → Fortgeschritten', 'Integrierter Timer', 'HD-Demovideos'],
    tags: ['HIIT', 'fettverbrennung', 'körpergewicht', 'cardio'],
    level: 'Anfänger bis Fortgeschritten', duration: '6 Wochen',
  },
  d4: {
    name: 'Lauf-Leitfaden - Von 5 km bis Marathon',
    badge: '📥 120-Seiten-E-Book',
    description: '120-Seiten-E-Book. Pläne für 5 km/10 km/Halb/Marathon. Wettkampfernährung, Verletzungsprävention, Wettkämpfer-Mindset.',
    longDescription: 'Der XENOTIF-Lauf-Leitfaden deckt das gesamte Spektrum des modernen Läufers ab. Geschrieben von einem zertifizierten Leichtathletik-Coach, enthält er personalisierte Pläne für 4 Distanzen, Ernährungsrat vor/während/nach einem Wettkampf, ein 7-Punkte-Anti-Verletzungs-Protokoll und eine bewährte mentale Vorbereitung. 120 reich illustrierte Seiten.',
    features: ['120 Experten-Seiten', 'Pläne 5 km/10 km/Halb/Marathon', 'Wettkampfernährung', 'Verletzungsprävention', 'Wettkämpfer-Mindset'],
    tags: ['running', 'marathon', 'laufen', 'e-book'],
    level: 'Alle Level', duration: '8 bis 16 Wochen',
  },
  c1: {
    name: 'Aerodynamischer Rennrad-Helm',
    badge: '🚴 Sicherheit',
    description: 'Leichter, belüfteter Fahrradhelm mit verstärkter Schale und Verstellrad. Sicherheit und Komfort auf Straße und Trail.',
    longDescription: 'Ein guter Helm ist die erste nicht verhandelbare Ausrüstung eines Radfahrers. Dieses aerodynamische Modell verbindet eine verstärkte In-Mold-Schale mit einer ultraleichten Bauweise (~250 g) für optimalen Schutz ohne Beschwerden. Breite Belüftungsöffnungen halten deinen Kopf kühl auf langen Fahrten, und das Mikro-Verstellrad sorgt für perfekte Passform bei jeder Kopfform. Wasserabweisende Riemen und ein abnehmbares Visier inklusive.',
    features: ['Verstärkte In-Mold-Schale', 'Ultraleicht (~250 g)', 'Mehrere Belüftungsöffnungen', 'Verstellrad', 'Abnehmbares Visier'],
    tags: ['fahrradhelm', 'sicherheit', 'radfahren', 'straße'],
  },
  c2: {
    name: 'Kabelloser Fahrrad-GPS-Computer',
    badge: '📡 GPS',
    description: 'Wasserdichter GPS-Computer: Geschwindigkeit, Distanz, Höhenmeter, Route. Großes, bei Sonne lesbares Display, 25 h Akku, schnelle Montage.',
    longDescription: 'Verfolge jede Fahrt präzise mit diesem kabellosen GPS-Computer. Er erfasst Geschwindigkeit, Distanz, Zeit, Höhe, Höhenmeter und GPS-Route und synchronisiert mit Strava und Komoot. Transflektives Display, perfekt lesbar bei direkter Sonne, 25 Stunden Akku und IPX7-Wasserschutz. Die mitgelieferte Lenkerhalterung lässt sich in Sekunden ohne Werkzeug montieren. Kompatibel mit ANT+-Sensoren (Herzfrequenz, Trittfrequenz, Geschwindigkeit).',
    features: ['GPS Geschwindigkeit/Distanz/Höhe', 'Strava- & Komoot-Sync', 'Bei Sonne lesbares Display', '25 h Akku · IPX7', 'ANT+-kompatibel'],
    tags: ['fahrradcomputer', 'radfahren', 'strava', 'fahrrad'],
  },
  c4: {
    name: 'Radhose mit 4D-Polster',
    badge: '🩳 Komfort',
    description: 'Radhose mit atmungsaktivem 4D-Sitzpolster. Kompressives Gewebe, rutschfeste Beinabschlüsse. Komfort über lange Distanzen.',
    longDescription: 'Komfort auf dem Rad beginnt im Sattel: Diese Hose hat ein hochdichtes 4D-Sitzpolster, das Stöße dämpft und Scheuern verhindert, selbst nach mehreren Stunden. Das kompressive, atmungsaktive Gewebe leitet Schweiß ab und stützt die Muskeln, während Silikon-Beinabschlüsse die Hose an Ort und Stelle halten. Flache Anti-Reibungs-Nähte. Die Basis jeder ernsthaften Radfahrer-Ausstattung.',
    features: ['4D-Sitzpolster', 'Atmungsaktives kompressives Gewebe', 'Rutschfeste Beinabschlüsse', 'Flache Nähte', 'Lange Distanzen'],
    tags: ['radhose', 'radfahren', 'bekleidung', 'straße'],
  },
  c5: {
    name: 'Halbfinger-Anti-Schock-Fahrradhandschuhe',
    badge: '🧤 Grip',
    description: 'Halbfinger-Fahrradhandschuhe mit Anti-Schock-Gel, atmungsaktiver Handfläche und Abziehlaschen. Besserer Grip, weniger Ermüdung.',
    longDescription: 'Handschuhe schützen deine Hände vor Vibration und Stürzen und verbessern gleichzeitig den Grip am Lenker. Dieses Halbfinger-Modell hat Gelpolster an den Druckpunkten, um Stöße zu absorbieren und Taubheit auf langen Fahrten zu reduzieren. Atmungsaktiver Mesh-Rücken, rutschfeste Wildleder-Handfläche und praktische Abziehlaschen. Eine Frottee-Zone am Daumen zum Abwischen der Stirn.',
    features: ['Anti-Schock-Gel', 'Rutschfeste Handfläche', 'Atmungsaktiver Rücken', 'Abziehlaschen', 'Halbfinger'],
    tags: ['fahrradhandschuhe', 'radfahren', 'anti-schock', 'grip'],
  },
  c7: {
    name: 'Fahrrad-Trinkflasche 750 ml + Halter',
    badge: '💧 Hydration',
    description: '750-ml-BPA-freie Flasche + leichter Aluminiumhalter. Einfaches einhändiges Trinken, Montage am Rahmen.',
    longDescription: 'Regelmäßig hydriert zu bleiben ist auf dem Rad entscheidend. Dieses Set kombiniert eine 750-ml-BPA-freie Squeeze-Flasche mit auslaufsicherem Ventil mit hohem Durchfluss zum einhändigen Trinken und einen leichten Aluminiumhalter, der an die Rahmeninserts geschraubt wird. Die Flasche ist drückbar, leicht zu betätigen und spülmaschinenfest. Der Halter hält die Flasche fest, selbst auf rauem Gelände.',
    features: ['750-ml-BPA-freie Flasche', 'Auslaufsicheres Ventil', 'Aluminiumhalter', 'Einhändiges Trinken', 'Spülmaschinenfest'],
    tags: ['trinkflasche', 'flaschenhalter', 'hydration', 'radfahren'],
  },
  s1: {
    name: 'Anti-Beschlag-Schwimmbrille',
    badge: '🥽 Anti-Beschlag',
    description: 'Wasserdichte Schwimmbrille mit Anti-Beschlag-, Anti-UV-Gläsern und weichen Silikondichtungen. Klare Sicht und Komfort, kein Auslaufen.',
    longDescription: 'Eine Brille, die nicht beschlägt oder ausläuft, verwandelt eine Schwimmeinheit. Dieses Modell kombiniert eine langlebige Anti-Beschlag-Beschichtung mit Anti-UV-Schutz für klare Sicht im Becken und Freiwasser. Die weichen Silikondichtungen schmiegen sich an die Augenkontur, ohne Abdrücke zu hinterlassen, und der austauschbare Nasensteg (3 Größen inklusive) passt auf jedes Gesicht. Doppelter Riemen einhändig verstellbar.',
    features: ['Langlebige Anti-Beschlag-Gläser', 'Anti-UV-Schutz', 'Weiche Silikondichtungen', '3 Nasenstege inklusive', 'Einhändige Riemenverstellung'],
    tags: ['schwimmbrille', 'anti-beschlag', 'schwimmen', 'becken'],
  },
  s2: {
    name: 'Silikon-Badekappe',
    badge: '🏊 Unverzichtbar',
    description: '100%-Silikon-Badekappe, wasserdicht und bequem. Reduziert Widerstand, schützt Haare vor Chlor. Unisex, Einheitsgröße.',
    longDescription: 'Die Silikonkappe ist das Basis-Accessoire jedes Schwimmers: Sie schützt die Haare vor Chlor, reduziert den Widerstand im Wasser und hält den Kopf warm. Dieses Modell aus 100% Silikon ist weich, langlebig und leicht aufzusetzen, ohne an den Haaren zu ziehen. Sie bleibt während der Bahnen fest sitzen und reizt die Stirn nicht. Einheitsgröße für Männer, Frauen und Jugendliche.',
    features: ['Weiches 100% Silikon', 'Wasserdicht & bequem', 'Reduziert Widerstand', 'Schützt die Haare', 'Unisex Einheitsgröße'],
    tags: ['badekappe', 'silikon', 'schwimmen', 'becken'],
  },
  s3: {
    name: 'Schwimmbrett (Kickboard)',
    badge: '🏊 Training',
    description: 'EVA-Schaumbrett zur Stärkung des Beinschlags. Leicht, ergonomisch, hoher Auftrieb. Ideal fürs Training.',
    longDescription: 'Das Schwimmbrett ist das unverzichtbare Werkzeug, um an deinem Beinschlag und deiner Körperposition zu arbeiten. Aus hochdichtem EVA-Schaum gefertigt, bietet es hohen Auftrieb und bleibt dabei leicht und chlorbeständig. Seine ergonomische Form mit Handaussparungen sorgt für bequemen Halt bei jeder Übung. Geeignet für Anfänger und fortgeschrittene Schwimmer gleichermaßen für Technikarbeit und Konditionierung.',
    features: ['Hochdichter EVA-Schaum', 'Hoher Auftrieb', 'Ergonomische Handaussparungen', 'Chlorbeständig', 'Anfänger bis Fortgeschritten'],
    tags: ['kickboard', 'schwimmbrett', 'training', 'schwimmen'],
  },
  s4: {
    name: 'Chlorbeständiger Badeanzug',
    badge: '🩱 Ausdauer',
    description: 'Chlorbeständiger Trainings-Badeanzug, schnelltrocknend, eng anliegend. Hält Hunderte Beckeneinheiten.',
    longDescription: 'Für intensives Training gebaut, behält dieser Badeanzug aus chlorbeständigem Gewebe Form und Farbe Einheit für Einheit - wo ein normaler Anzug binnen Wochen ausleiert. Die eng anliegende Passform reduziert den Widerstand im Wasser, er trocknet schnell und die flachen Nähte verhindern Scheuern. Die langlebige Wahl für alle, die viele Bahnen ziehen.',
    features: ['Chlorbeständiges Gewebe', 'Schnelltrocknend', 'Eng anliegend, widerstandsarm', 'Flache Nähte', 'Langlebig'],
    tags: ['badeanzug', 'schwimmen', 'chlorbeständig', 'becken'],
  },
  a1: {
    name: 'Türrahmen-Klimmzugstange ohne Bohren',
    badge: '🔥 Bestseller',
    description: 'Multigriff-Klimmzugstange für Türrahmen, ohne Bohren. Bis 130 kg. Rücken, Bizeps und Core zu Hause trainieren.',
    features: ['Ohne Schrauben/Bohren', 'Multigriff', 'Bis 130 kg', 'Rutschfester Schaum', 'Verstärkter Stahl'],
    tags: ['klimmzugstange', 'rücken', 'kraft', 'zuhause'],
  },
  a2: {
    name: 'Verstellbare Klappbare Hantelbank',
    badge: '💪 Home Gym',
    description: 'Schrägbank mit 7 Positionen, klappbar und kompakt. Ideal für Bankdrücken, Curls und Hantelübungen zu Hause.',
    features: ['7 Neigungen', 'Klappbar & kompakt', 'Bis 250 kg', 'Hochdichte Polsterung', 'Stahlrahmen'],
    tags: ['hantelbank', 'hanteln', 'bankdrücken', 'zuhause'],
  },
  a3: {
    name: 'Turnringe aus Holz + Gurte',
    badge: '🆕 Neu',
    description: 'Paar Holzringe mit nummerierten, verstellbaren Gurten. Dips, Klimmzüge, Muscle-ups - Calisthenics und CrossFit.',
    features: ['Holz mit natürlichem Grip', '4,5 m nummerierte Gurte', 'Schnellverschluss', 'Dips & Klimmzüge', 'Muscle-ups'],
    tags: ['turnringe', 'calisthenics', 'crossfit', 'street workout'],
  },
  a4: {
    name: 'Drehbare Liegestützgriffe (Paar)',
    badge: '🤲 Grip',
    description: 'Drehbare Liegestützgriffe, schonen Handgelenke und Schultern. Größere Amplitude für definierte Brust.',
    features: ['Natürliche Rotation', 'Handgelenkschonend', 'Größere Amplitude', 'Rutschfeste Basis', 'Mobil'],
    tags: ['liegestütze', 'push-up', 'brust', 'körpergewicht'],
  },
  a5: {
    name: 'Sporttasche 40L mit Schuhfach',
    badge: '🎒 Bestseller',
    description: 'Robuste 40-L-Sporttasche mit belüftetem Schuhfach und Nassfach. Ideal für Gym, Reise und Wochenende.',
    features: ['40 L', 'Belüftetes Schuhfach', 'Wasserdichtes Nassfach', 'Wasserabweisend', 'Gepolsterter Gurt'],
    tags: ['sporttasche', 'gym bag', 'reise', 'zubehör'],
  },
  a6: {
    name: 'Isolierte Sport-Trinkflasche 2L Edelstahl',
    badge: '💧 Hydration',
    description: '2-L-Edelstahlflasche, doppelwandig, 24h kalt. Skaliert, auslaufsicher, weite Öffnung. Für lange Einheiten.',
    features: ['2 L doppelwandig', '24h kalt', 'Skaliert', 'Auslaufsicher', 'BPA-frei'],
    tags: ['trinkflasche', 'hydration', 'edelstahl', 'sport'],
  },
  a7: {
    name: 'Protein-Shaker 700ml Auslaufsicher + Ball',
    badge: '🥤 Essenziell',
    description: '700-ml-Shaker mit Edelstahl-Mixball, klumpenfrei. Luftdichter, auslaufsicherer Deckel, Skala, BPA-frei.',
    features: ['Edelstahlball, klumpenfrei', '700 ml', 'Luftdicht auslaufsicher', 'oz/ml-Skala', 'BPA-frei'],
    tags: ['shaker', 'protein', 'whey', 'ernährung'],
  },
  a8: {
    name: 'Wasserdichte Sport-Bluetooth-Kopfhörer IPX7',
    badge: '🎧 IPX7',
    description: 'Kabellose Ohrbügel-Kopfhörer, sicherer Sitz, IPX7 wasserdicht. 40h Akku, tiefe Bässe. Laufen und Krafttraining.',
    features: ['Sichere Ohrbügel', 'IPX7 wasserdicht', '40h Akku', 'Tiefe Bässe', 'Bluetooth 5.3'],
    tags: ['kopfhörer', 'bluetooth', 'sport', 'laufen'],
  },
  b1: { name: 'Boxhandschuhe 12oz Kunstleder', badge: '🥊 Bestseller', description: '12oz-Boxhandschuhe, mehrschichtige Polsterung, Handgelenkstütze, atmungsaktiv. Sack, Sparring und Fitnessboxen.', features: ['12oz mehrschichtig', 'Handgelenkstütze', 'Atmungsaktives Futter', 'Robustes Kunstleder', 'Sack & Sparring'], tags: ['boxhandschuhe', 'boxen', 'boxsack', 'sparring'] },
  b2: { name: 'Box-Handbandagen 4,5m (Paar)', badge: '🥊 Essenziell', description: 'Halbelastische 4,5-m-Bandagen, schützen Handgelenke und Gelenke. Klett und Daumenschlaufe. Pflicht vor den Handschuhen.', features: ['4,5 m pro Bandage', 'Schützt Handgelenke & Knöchel', 'Daumenschlaufe', 'Breiter Klett', 'Waschbar'], tags: ['handbandagen', 'bandagen', 'boxen', 'schutz'] },
  b3: { name: 'Hängender Boxsack 120cm + Kette', badge: '🥊 Pro', description: 'Gefüllter 120-cm-Boxsack, Kettenaufhängung und Anti-Dreh-Wirbel. Boxen, Kickboxen und Cardio.', features: ['120 cm gefüllt', 'Kette + Wirbel', 'Anti-Dreh', 'Schlagfest', 'Boxen & Cardio'], tags: ['boxsack', 'boxen', 'kickboxen', 'cardio'] },
  b4: { name: 'Gebogene Handpratzen (Paar)', badge: '🥊 Duo', description: 'Paar gebogene Handpratzen, gepolstertes Schlagziel. Schnelligkeit, Präzision und Kombos zu zweit.', features: ['Gebogen mehrschichtig', 'Stoßabsorbierend', 'Atmungsaktiver Handschuh', 'Schnelligkeit & Präzision', 'Partnerarbeit'], tags: ['pratzen', 'handpratzen', 'boxen', 'präzision'] },
  b5: { name: 'Freistehender Standboxsack', badge: '🥊 Ohne Bohren', description: 'Freistehender Boxsack, befüllbare Basis (Wasser/Sand), höhenverstellbar. Ohne Bohren, ideal für Wohnungen.', features: ['Befüllbare Basis', 'Höhenverstellbar', 'Ohne Bohren', 'Rückkehr-Automatik', 'Ideal für Wohnungen'], tags: ['boxsack', 'standboxsack', 'boxen', 'zuhause'] },
  m1: { name: 'Yogablöcke Kork (2er-Set)', badge: '🧘 Natürlich', description: 'Paar Korkblöcke, rutschfest, stützen Posen und verbessern die Ausrichtung.', features: ['Naturkork', 'Rutschfest', 'Posen-Stütze', 'Ausrichtung', '2er-Set'], tags: ['yogablock', 'kork', 'yoga', 'dehnen'] },
  m2: { name: 'Yoga-Stretchgurt 10 Schlaufen', badge: '🧘 Flexibilität', description: 'Stretchgurt mit 10 Schlaufen, sicher beweglicher werden. Ideal für Yoga, Mobilität und Reha.', features: ['10 Schlaufen', 'Geführtes Dehnen', 'Ohne Partner', 'Nicht dehnbar', 'Yoga & Mobilität'], tags: ['stretchgurt', 'yoga', 'mobilität', 'flexibilität'] },
  m3: { name: 'Yoga-Rad gegen Rückenschmerzen', badge: '🧘 Mobilität', description: 'Yoga-Rad zum Öffnen der Brust, Dehnen des Rückens und Lösen von Spannungen. Bis 150 kg.', features: ['Öffnet die Brust', 'Dehnt den Rücken', 'Bis 150 kg', 'Rutschfest', 'Anti-Spannung'], tags: ['yoga rad', 'rücken', 'mobilität', 'dehnen'] },
  m4: { name: 'Mobility-Loop-Bänder (5er-Set)', badge: '🧘 Aktivierung', description: '5 Mini-Loop-Bänder, 5 Stärken. Aktivierung, Hüft-/Schultermobilität, Gesäß und Reha.', features: ['5 Stärken', 'Rutschen nicht', 'Mobilität & Aktivierung', 'Gesäß', 'Beutel inklusive'], tags: ['loop bänder', 'mobilität', 'gesäß', 'aktivierung'] },
  m5: { name: 'Trigger-Massagebälle (3er-Set)', badge: '🧘 Erholung', description: '3 Bälle unterschiedlicher Dichte, gezielt gegen Verspannungen. Selbstmassage, Mobilität und Erholung.', features: ['3 Dichten', 'Gezielte Selbstmassage', 'Triggerpunkte', 'Vor/nach Training', 'Kompakt'], tags: ['massageball', 'trigger point', 'mobilität', 'erholung'] },
  m6: { name: 'Pro Stretchband Multi-Schlaufen', badge: '🧘 Flexibilität', description: 'Multi-Schlaufen-Stretchband für Tanz, Gym und Mobilität. Geführte, sanfte Flexibilitätssteigerung.', features: ['Dick, Multi-Schlaufe', 'Geführtes Dehnen', 'Sanfte Steigerung', 'Tanz & Gym', 'Mobil'], tags: ['stretchband', 'dehnen', 'flexibilität', 'mobilität'] },
  u1: { name: 'Pre-Workout Energie & Fokus', badge: '⚡ Energie', description: 'Pre-Workout-Booster: Koffein, Beta-Alanin und Citrullin für Energie, Pump und Fokus. Zuckerfrei.', features: ['Koffein + Beta-Alanin', 'L-Citrullin', 'Energie & Fokus', 'Zuckerfrei', 'Schnell löslich'], tags: ['pre-workout', 'koffein', 'energie', 'ernährung'] },
  u2: { name: 'Hydrations-Elektrolyte (Tabletten)', badge: '💧 Ausdauer', description: 'Brausetabletten mit Natrium/Kalium/Magnesium. Rehydration und Anti-Krampf für Ausdauer.', features: ['Natrium/Kalium/Magnesium', 'Anti-Krampf', 'Rehydration', 'Brausetabletten', 'Kalorienarm'], tags: ['elektrolyte', 'hydration', 'ausdauer', 'ernährung'] },
  u3: { name: 'Proteinriegel 20g (12er-Box)', badge: '🍫 Snack', description: '20g-Proteinriegel, zuckerarm, leckere Hülle. Der perfekte Snack nach dem Training oder unterwegs.', features: ['20g Protein', 'Zuckerarm', 'Leckere Hülle', '12er-Box', 'Unterwegs'], tags: ['proteinriegel', 'protein', 'snack', 'ernährung'] },
  u4: { name: 'Omega-3 EPA/DHA (120 Kapseln)', badge: '🐟 Erholung', description: 'Konzentriertes EPA/DHA-Fischöl. Herz, Gelenke und Erholung. Ohne Nachgeschmack.', features: ['Konzentriertes EPA/DHA', 'Herz & Gelenke', 'Erholung', 'Ohne Nachgeschmack', '120 Kapseln'], tags: ['omega-3', 'epa dha', 'erholung', 'ernährung'] },
  w1: { name: 'Schwimm-Handpaddles (Paar)', badge: '🏊 Technik', description: 'Handpaddles zum Stärken des Oberkörpers und Verfeinern des Wasserfassens. Verstellbare Riemen.', features: ['Stärkt den Oberkörper', 'Verfeinert den Zug', 'Verstellbare Riemen', 'Mehrere Größen', 'Beckentraining'], tags: ['handpaddles', 'schwimmen', 'technik', 'kraft'] },
  w2: { name: 'Pull Buoy Bein-Schwimmhilfe', badge: '🏊 Core', description: 'Pull Buoy zwischen den Oberschenkeln: isoliert die Armarbeit und verbessert die Wasserlage. Robuster Schaum.', features: ['Isoliert die Armarbeit', 'Bessere Wasserlage', 'Robuster EVA-Schaum', 'Core', 'Beckentraining'], tags: ['pull buoy', 'schwimmen', 'schwimmhilfe', 'technik'] },
}

// Mots-clés de recherche en allemand → liens affiliés amazon.de pour la locale DE.
const AMAZON_DE_KEYWORDS: Record<string, string> = {
  e1: 'kettlebell 20kg gusseisen',
  e2: 'widerstandsbänder fitness set',
  e3: 'yogamatte rutschfest 10mm',
  e4: 'springseil speed rope crossfit',
  e5: 'verstellbare hanteln set',
  e6: 'heimtrainer fahrrad ergometer',
  e7: 'ab roller bauchtrainer bauchroller',
  n1: 'whey protein schokolade 1kg',
  n2: 'kreatin monohydrat pulver',
  n3: 'bcaa pulver',
  r1: 'faszienrolle foam roller',
  r2: 'massagepistole muskel',
  t1: 'sportuhr gps pulsuhr multisport',
  t2: 'fitness tracker armband pulsmesser',
  t3: 'smartwatch fitness gps herzfrequenz',
  v1: 'sport shorts herren training fitness',
  v2: 'sport leggings damen high waist fitness',
  v3: 'kompression leggings herren sport tights',
  c1: 'fahrradhelm rennrad',
  c2: 'fahrradcomputer gps kabellos',
  c4: 'radhose herren gepolstert',
  c5: 'fahrradhandschuhe halbfinger',
  c7: 'fahrrad trinkflasche flaschenhalter',
  s1: 'schwimmbrille antibeschlag',
  s2: 'badekappe silikon',
  s3: 'schwimmbrett kickboard',
  s4: 'badeanzug schwimmen chlorresistent',
  a1: 'klimmzugstange türrahmen ohne bohren',
  a2: 'hantelbank verstellbar klappbar',
  a3: 'turnringe holz gymnastik',
  a4: 'liegestützgriffe drehbar',
  a5: 'sporttasche schuhfach',
  a6: 'isolierte trinkflasche 2l edelstahl',
  a7: 'protein shaker blender bottle',
  a8: 'sport kopfhörer bluetooth wasserdicht',
  b1: 'boxhandschuhe 12oz', b2: 'boxbandagen handbandagen', b3: 'boxsack hängend 120cm',
  b4: 'pratzen boxen handpratzen', b5: 'standboxsack freistehend',
  m1: 'yogablöcke kork', m2: 'yoga gurt stretching schlaufen', m3: 'yoga rad rücken',
  m4: 'mobility bänder loop', m5: 'massagebälle trigger point', m6: 'stretchband gymnastik schlaufen',
  u1: 'pre workout booster', u2: 'elektrolyte tabletten', u3: 'proteinriegel 20g', u4: 'omega 3 epa dha kapseln',
  w1: 'schwimm paddles handpaddles', w2: 'pull buoy schwimmen',
}

export const PRODUCTS_DE: Product[] = PRODUCTS.map((p) => {
  const merged: Product = { ...p, ...TEXT_DE[p.id] }
  const deKeywords = AMAZON_DE_KEYWORDS[p.id]
  if (p.amazon && deKeywords) {
    merged.amazon = { ...p.amazon, affiliateUrl: amazonSearchUrl('www.amazon.de', deKeywords, AMAZON_TAG_DE) }
  }
  return merged
})
