import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// fitness-maison — Heim-Fitness-Programm ohne Geräte (DE-Mirror von fitness-maison.ts). Premium-Vorlage XENOTIF® (≈30 Seiten).
export const fitnessMaisonDe: Guide = {
  id: 'fitness-maison',
  title: 'Heim-Fitness-Programm',
  subtitle: '8 Wochen, 100 % Körpergewicht, keine Ausrüstung nötig — wo immer du bist',
  author: 'XENOTIF Coach — Athletiktraining zertifiziert',
  level: 'Anfänger - Mittel',
  duration: '8 Wochen · 4 Einheiten/Woche',
  coverImage: 'cover.jpg',
  blocks: [
    { type: 'h1', text: 'Dein Zuhause ist dein Fitnessstudio' },
    { type: 'p', text: `Kein Studio, keine Geräte, keine Ausrede. Dieses 8-Wochen-Programm läuft komplett mit dem eigenen Körpergewicht, auf 2 m², zuhause oder unterwegs. Du straffst deinen Körper, baust funktionelle Kraft auf, verbrennst Fett und schaffst dir eine Routine, die hält — mit deinem Körper als einziger Ausrüstung.` },
    { type: 'p', text: `Jede Übung hat einen QR-Code zu ihrem Demovideo auf XENOTIF®. Bei Unsicherheit einfach scannen.` },
    { type: 'meta', items: [
      { label: 'Ziel', value: 'Straffen, verbrennen, kräftigen' },
      { label: 'Niveau', value: 'Anfänger bis Mittel' },
      { label: 'Dauer', value: '8 Wochen' },
      { label: 'Häufigkeit', value: '4 Einheiten pro Woche' },
      { label: 'Ausrüstung', value: 'Keine (Matte optional)' },
      { label: 'Ort', value: 'Zuhause, unterwegs, überall' },
    ] },
    { type: 'h2', text: 'Programmziele' },
    { type: 'list', items: [
      `Den ganzen Körper straffen und kräftigen — ganz ohne Geräte.`,
      `Fett verbrennen mit kurzen, intensiven Zirkeln.`,
      `Funktionelle Kraft, Beweglichkeit und Ausdauer verbessern.`,
      `Eine Routine aufbauen, die du überall durchhältst — ganz ohne Zwang.`,
    ] },
    { type: 'h2', text: 'So nutzt du diesen Leitfaden' },
    { type: 'list', items: [
      `Lies den Leitfaden einmal komplett durch, dann folge dem 8-Wochen-Kalender.`,
      `Wärme dich vor jeder Einheit 5 Min. auf (eigenes Kapitel).`,
      `Scanne den QR-Code einer Übung, um die Technik im Video zu sehen.`,
      `Steigere dich, indem du zu den angegebenen schwereren Varianten wechselst.`,
      `Zieh jeden Sonntag Bilanz (Tracking + Checkliste).`,
    ] },
    { type: 'note', text: `Goldene Regel für Körpergewichtstraining: Ohne Zusatzgewichte steigerst du dich über die Schwierigkeit der Variante, das Tempo, die Anzahl der Wiederholungen und die Dichte (weniger Pause). Fortschritt ist also durchaus möglich — du musst ihn nur gezielt herbeiführen.` },

    { type: 'h1', text: 'So funktioniert es' },
    { type: 'list', items: [
      `4 Einheiten/Woche: 2 Ganzkörper-Kräftigungseinheiten + 2 Cardio-/HIIT-Zirkel.`,
      `Zirkelformat: Reihe die Übungen mit wenig Pause aneinander, um die Intensität hochzuhalten.`,
      `Wiederholungen oder Zeit: „3 × 12" = 3 Sätze à 12; „40 s" = 40 Sekunden Belastung.`,
      `Kontrolliertes Tempo: 2 s beim Absenken, 1 s beim Hochdrücken. Langsamer erhöht die Schwierigkeit.`,
      `Pause: 30 bis 60 s zwischen Sätzen/Übungen, je nach deinem Niveau.`,
      `Intensität (RPE /10): ziele auf 7-8; bei den HIIT-Zirkeln geh auf 9 hoch.`,
    ] },
    { type: 'h2', text: 'Fortschritt ohne Gewichte' },
    { type: 'p', text: `Das ist DIE Frage beim Training zuhause. Hier sind die 5 Hebel, mit denen du dich weiter steigerst, ohne je eine Hantel anzufassen.` },
    { type: 'table', headers: ['Hebel', 'Wie', 'Beispiel'], rows: [
      ['Schwerere Variante', 'Eine anspruchsvollere Version wählen', 'Liegestütz → Decline-Liegestütz'],
      ['Mehr Wiederholungen', 'Jede Woche Wiederholungen ergänzen', '10 → 12 → 15'],
      ['Langsames Tempo', 'Die exzentrische Phase verlangsamen', 'Kniebeuge in 4 s absenken'],
      ['Dichte', 'Die Pause verkürzen', '60 s → 30 s'],
      ['Einseitig', 'Jeweils eine Seite trainieren', 'Kniebeuge → Bulgarische Kniebeuge'],
    ] },

    { type: 'h1', text: 'Aufwärmen' },
    { type: 'p', text: `5 Minuten vor jeder Einheit, um den Körper vorzubereiten und deine Leistung zu steigern.` },
    { type: 'table', headers: ['Bewegung', 'Dauer'], rows: [
      ['Gehen / Laufen auf der Stelle', '60 s'],
      ['High Knees', '45 s'],
      ['Arm- & Hüftkreisen', '45 s'],
      ['Langsame Kniebeugen', '45 s'],
      ['Dynamische Ausfallschritte', '45 s'],
      ['Plank 20 s + langsame Liegestütze', '40 s'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Der Erfolg entsteht auch auf dem Teller.' },
    { type: 'h1', text: 'Ernährung' },
    { type: 'p', text: `Egal welches Ziel du hast (straffen, definieren, kräftigen) — die Basis bleibt gleich: genug Eiweiß, einfache Lebensmittel und eine zu deinem Ziel passende Kalorienzufuhr.` },
    { type: 'meta', items: [
      { label: 'Zum Definieren', value: 'Leichtes Defizit (−300/−500 kcal)' },
      { label: 'Zum Kräftigen', value: 'Erhaltung bis leichter Überschuss' },
      { label: 'Eiweiß', value: '1,6 bis 2 g pro kg' },
      { label: 'Trinken', value: '2 bis 3 L pro Tag' },
    ] },
    { type: 'list', items: [
      `Eine Eiweißquelle bei jeder Mahlzeit (Eier, Hähnchen, Fisch, Skyr, Hülsenfrüchte).`,
      `Gemüse nach Belieben, Kohlenhydrate rund um die Einheiten.`,
      `Reduziere flüssigen Zucker (Softdrinks, Säfte, Alkohol).`,
      `Trink regelmäßig Wasser, besonders während der Zirkel.`,
    ] },
    { type: 'h2', text: 'Deine Makros verstehen' },
    { type: 'table', headers: ['Makro', 'Rolle', 'Pro g', 'Priorität'], rows: [
      ['Eiweiß', 'Muskeln & Sättigung', '4 kcal', 'HOCH — 1,6-2 g/kg'],
      ['Kohlenhydrate', 'Energie', '4 kcal', 'Rund um die Einheiten'],
      ['Fette', 'Hormone, Gesundheit', '9 kcal', 'Moderat, Qualität'],
    ] },
    { type: 'note', text: `Du brauchst weder Geräte … noch komplizierte Küche. Stell jeden Teller so zusammen: 1 Eiweißquelle + 1 Kohlenhydratquelle + Gemüse + etwas gutes Fett.` },

    { type: 'h1', text: 'Express-Rezepte' },
    { type: 'h2', text: 'Rührei mit Haferflocken' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 400 kcal' }, { label: 'Eiweiß', value: '28 g' }] },
    { type: 'list', items: [`3 Eier`, `40 g Haferflocken`, `1 Stück Obst`, `Gewürze`] },
    { type: 'p', text: `Zubereitung: Eier verrühren und braten, Haferflocken separat anrühren. Komplettes Frühstück in 5 Min.` },
    { type: 'h2', text: 'Kichererbsensalat mit Thunfisch' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 450 kcal' }, { label: 'Eiweiß', value: '35 g' }] },
    { type: 'list', items: [`1 Dose Kichererbsen`, `1 Dose Thunfisch`, `Tomaten, Zwiebel, Petersilie`, `Zitrone, Olivenöl`] },
    { type: 'p', text: `Zubereitung: alles vermengen. Kein Kochgeschirr nötig, blitzschnell und sättigend.` },
    { type: 'h2', text: 'Eiweiß-Skyr' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 350 kcal' }, { label: 'Eiweiß', value: '32 g' }] },
    { type: 'list', items: [`250 g Skyr`, `Beeren`, `30 g Haferflocken`, `Mandeln`] },
    { type: 'p', text: `Zubereitung: mischen. Perfekt als Snack oder nach der Einheit.` },
    { type: 'h2', text: 'Hähnchen-Gemüse-Pfanne' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 470 kcal' }, { label: 'Eiweiß', value: '40 g' }] },
    { type: 'list', items: [`140 g Hähnchen`, `200 g Gemüse (frisch oder tiefgekühlt)`, `100 g gekochter Reis`, `Gewürze, Sojasoße`] },
    { type: 'p', text: `Zubereitung: Hähnchen scharf anbraten, Gemüse dazugeben, auf dem Reis servieren. Nur eine Pfanne, 12 Min.` },
    { type: 'h2', text: 'Avocado-Ei-Toast' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 380 kcal' }, { label: 'Eiweiß', value: '22 g' }] },
    { type: 'list', items: [`2 Scheiben Vollkornbrot`, `1/2 Avocado`, `2 Eier`, `Zitrone, Salz, Pfeffer`] },
    { type: 'p', text: `Zubereitung: Avocado auf dem Brot zerdrücken, Eier dazugeben (Spiegelei oder pochiert). Sättigendes Frühstück oder Snack.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Gut erholen, um Einheit für Einheit Fortschritte zu machen.' },
    { type: 'h1', text: 'Erholung' },
    { type: 'list', items: [
      `Schlafe 7 bis 9 h: genau dann baut sich der Körper wieder auf.`,
      `Halte dir mindestens 1 komplett freien Tag pro Woche.`,
      `Muskelkater in den ersten Wochen ist normal.`,
      `Dehne dich 5-10 Min. nach jeder Einheit.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: '4 Einheiten pro Woche, wo immer du bist.' },
    { type: 'h1', text: '8-Wochen-Kalender' },
    { type: 'p', text: `Wechsle zwischen Kräftigung und Zirkeln ab. Erhöhe die Wiederholungen, verlangsame das Tempo oder wechsle zu schwereren Varianten, sobald es leicht wird.` },
    { type: 'table', headers: ['Wochen', 'Fokus', 'Volumen', 'Hinweis'], rows: [
      ['W1-W2', 'Anpassung', '3 Runden', 'Bewegungen erlernen'],
      ['W3-W4', 'Volumen', '4 Runden', '+ Wiederholungen'],
      ['W5-W6', 'Intensität', '4 Runden', 'Schwerere Varianten, kurze Pausen'],
      ['W7-W8', 'Spitze', '5 Runden', 'Persönliche Bestleistung, Bilanz'],
    ] },
    { type: 'h2', text: 'Typische Woche' },
    { type: 'table', headers: ['Tag', 'Einheit', 'Dauer'], rows: [
      ['Montag', 'Kräftigung A (Unterkörper + Core)', '35 Min.'],
      ['Dienstag', 'HIIT-Zirkel', '25 Min.'],
      ['Mittwoch', 'Pause / Gehen', '—'],
      ['Donnerstag', 'Kräftigung B (Oberkörper + Core)', '35 Min.'],
      ['Freitag', 'Ganzkörper-Cardio-Zirkel', '30 Min.'],
      ['Wochenende', 'Aktive Pause + Tracking', '—'],
    ] },

    { type: 'h2', text: 'Tag für Tag im Detail (Wochen 1 bis 4)' },
    { type: 'p', text: `Die Wochen 5 bis 8 folgen demselben Schema mit mehr Runden, schwereren Varianten und weniger Pause (siehe „Progression über 8 Wochen").` },
    { type: 'table', headers: ['Tag', 'W1-W2', 'W3-W4'], rows: [
      ['Montag', 'Kräftigung A', 'Kräftigung A (+ Wdh.)'],
      ['Dienstag', 'HIIT-Zirkel', 'HIIT-Zirkel'],
      ['Mittwoch', 'Pause / Gehen', 'Pause / Gehen'],
      ['Donnerstag', 'Kräftigung B', 'Kräftigung B (+ Wdh.)'],
      ['Freitag', 'Cardio-Zirkel', 'Cardio-Zirkel (4 Runden)'],
      ['Samstag', 'Aktive Pause', 'Aktive Pause'],
      ['Sonntag', 'Pause + Tracking', 'Pause + Tracking'],
    ] },

    { type: 'h1', text: 'Deine Einheiten im Detail' },
    { type: 'h2', text: 'Kräftigung A — Unterkörper & Core' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Kniebeugen', '4', '15 bis 20', '45 s'],
      ['Abwechselnde Ausfallschritte', '3', '12 / Bein', '45 s'],
      ['Hüftheben', '3', '20', '40 s'],
      ['Wandsitz', '3', '40 s', '40 s'],
      ['Plank', '3', '40 s', '40 s'],
    ] },
    { type: 'h2', text: 'Kräftigung B — Oberkörper & Core' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Liegestütze (passende Variante)', '4', 'Saubere Maximalzahl', '45 s'],
      ['Stuhl-Dips', '3', '12', '45 s'],
      ['Rudern mit beschwerter Tasche (oder Superman)', '3', '12', '45 s'],
      ['Pike-Liegestütze (Schultern)', '3', '10', '45 s'],
      ['Side-Plank', '3', '25 s / Seite', '30 s'],
    ] },
    { type: 'h2', text: 'HIIT-Zirkel (25 Min.)' },
    { type: 'table', headers: ['Block', 'Belastung', 'Erholung', 'Runden'], rows: [
      ['Burpees (oder Sprungkniebeugen)', '40 s', '20 s', '4'],
      ['Mountain Climbers', '40 s', '20 s', '4'],
      ['Sprung-Ausfallschritte (oder Ausfallschritte)', '40 s', '20 s', '4'],
      ['Hampelmänner', '40 s', '20 s', '4'],
      ['Dynamischer Plank', '40 s', '20 s', '4'],
    ] },

    { type: 'h1', text: 'Übungsbibliothek' },
    { type: 'p', text: `Beherrsche diese Körpergewichtsübungen. Scanne den QR-Code für das Demovideo.` },
    { type: 'exercise', name: 'Körpergewichts-Kniebeuge', muscles: 'Quadrizeps, Gesäß, Beinbeuger', level: 'Anfänger', video: `${D}/musculation`, technique: `Füße schulterbreit, absenken, indem du das Gesäß nach hinten schiebst, Rücken gerade, Fersen am Boden, bis die Oberschenkel parallel sind, dann hochdrücken.`, mistakes: `Knie fallen nach innen, Fersen heben ab, runder Rücken.` },
    { type: 'exercise', name: 'Abwechselnde Ausfallschritte', muscles: 'Gesäß, Quadrizeps, Gleichgewicht', level: 'Anfänger', video: `${D}/musculation`, technique: `Großer Schritt nach vorn, hinteres Knie Richtung Boden, Oberkörper aufrecht, vorderes Knie über dem Knöchel, zurückdrücken.`, mistakes: `Zu kurzer Schritt, vorgebeugter Oberkörper, Gleichgewichtsverlust.` },
    { type: 'exercise', name: 'Liegestütze', muscles: 'Brust, Trizeps, Schultern, Core', level: 'Anfänger - Mittel', video: `${D}/musculation`, technique: `Körper fest in einer Linie, Brust zum Boden senken, Ellbogen ~45°, dann drücken. Varianten: schräg mit erhöhten Händen (leicht) → am Boden → Decline (schwer).`, mistakes: `Hüften sacken ab, Ellbogen zu weit abgespreizt, kurzer Bewegungsumfang.` },
    { type: 'exercise', name: 'Hüftheben', muscles: 'Gesäß, Beinbeuger', level: 'Anfänger', video: `${D}/musculation`, technique: `Auf dem Rücken, Knie gebeugt, durch die Fersen drücken, um das Becken zu heben, oben das Gesäß anspannen, ohne abzusetzen wieder senken. Variante: auf einem Bein.`, mistakes: `Hohlkreuz, zu hoch heben, Füße zu weit weg.` },
    { type: 'exercise', name: 'Wandsitz', muscles: 'Quadrizeps, Core', level: 'Anfänger', video: `${D}/musculation`, technique: `Rücken an der Wand, so weit heruntergleiten, bis die Oberschenkel parallel sind, Knie im 90°-Winkel, Position halten, Bauch angespannt.`, mistakes: `Knie ragen über die Zehenspitzen hinaus, Rücken löst sich von der Wand, Luft anhalten.` },
    { type: 'exercise', name: 'Stuhl-Dips', muscles: 'Trizeps, Schultern, Brust', level: 'Anfänger - Mittel', video: `${D}/musculation`, technique: `Hände auf der Kante eines stabilen Stuhls, Beine nach vorn gestreckt, durch Beugen der Ellbogen nach hinten absenken, dann hochdrücken. Gestreckte Beine = schwerer.`, mistakes: `Schultern ziehen hoch, kurzes Absenken, instabiler Stuhl.` },
    { type: 'exercise', name: 'Pike-Liegestütze', muscles: 'Schultern, Trizeps', level: 'Mittel', video: `${D}/musculation`, technique: `Im umgekehrten „V" (Gesäß hoch), den Scheitel zum Boden senken, indem du die Ellbogen beugst, dann drücken. Bereitet auf den Handstand-Liegestütz vor.`, mistakes: `Runder Rücken, kurzer Bewegungsumfang, Ellbogen zu weit abgespreizt.` },
    { type: 'exercise', name: 'Superman', muscles: 'Unterer Rücken, Gesäß, Rücken', level: 'Anfänger', video: `${D}/musculation`, technique: `Bauchlage, Arme und Beine gleichzeitig anheben, dabei Rücken und Gesäß anspannen, 1-2 s halten, kontrolliert absenken.`, mistakes: `Ruckartige Bewegung, überstreckter Nacken, fehlende Anspannung.` },
    { type: 'exercise', name: 'Plank', muscles: 'Bauchmuskulatur', level: 'Anfänger', video: `${D}/musculation`, technique: `Unterarme und Zehenspitzen am Boden, Körper in einer Linie, Bauch und Gesäß angespannt, atmen und halten.`, mistakes: `Hüften sacken ab, Gesäß zu hoch, Kopf angehoben.` },
    { type: 'exercise', name: 'Side-Plank', muscles: 'Schräge Bauchmuskeln, Core', level: 'Anfänger', video: `${D}/musculation`, technique: `Auf der Seite, auf einem Unterarm gestützt, Körper in einer Linie, Hüften angehoben. Halten, dann die Seite wechseln.`, mistakes: `Hüften sacken ab, Körper kippt.` },
    { type: 'exercise', name: 'Mountain Climbers', muscles: 'Bauch, Schultern, Cardio', level: 'Mittel', video: `${D}/hiit`, technique: `Im hohen Plank mit gestreckten Armen abwechselnd ein Knie zur Brust ziehen, immer schneller, Hüften tief, Core aktiv.`, mistakes: `Gesäß zu hoch, durchhängender Rücken, unsauberer Rhythmus.` },
    { type: 'exercise', name: 'Burpee', muscles: 'Ganzer Körper, Cardio', level: 'Fortgeschritten', video: `${D}/hiit`, technique: `Stehen → Hände auf den Boden → Füße nach hinten springen (Plank) → Liegestütz (optional) → Füße heranziehen → Strecksprung. Flüssig aneinanderreihen.`, mistakes: `Runder Rücken, Landung mit gestreckten Beinen. Landung abfedern, gleichmäßiger Rhythmus.` },
    { type: 'exercise', name: 'Sprungkniebeugen', muscles: 'Beine, Gesäß, Cardio', level: 'Mittel', video: `${D}/hiit`, technique: `Kniebeuge, dann explosiver Sprung nach oben, weiche und kontrollierte Landung in der Kniebeugenposition, wiederholen.`, mistakes: `Landung mit steifen Knien, vorgebeugter Oberkörper, zu geringer Bewegungsumfang bei der Kniebeuge.` },
    { type: 'exercise', name: 'Hampelmänner', muscles: 'Cardio, Schultern, Beine', level: 'Anfänger', video: `${D}/hiit`, technique: `Springe und spreize Beine und Arme, dann zurück. Weiche Landung, gleichmäßiger Rhythmus.`, mistakes: `Steife Landung, unvollständige Armbewegung.` },
    { type: 'exercise', name: 'Crunch', muscles: 'Gerader Bauchmuskel', level: 'Anfänger', video: `${D}/musculation`, technique: `Auf dem Rücken, Knie gebeugt, Schultern durch Einrollen des Oberkörpers vom Boden heben, ausatmen, langsam absenken. Der untere Rücken bleibt am Boden.`, mistakes: `Am Nacken ziehen, den ganzen Rücken abheben, die Luft anhalten.` },
    { type: 'exercise', name: 'Beinheben', muscles: 'Unterer Bauch, Core', level: 'Anfänger - Mittel', video: `${D}/musculation`, technique: `Liegend, Hände unter dem Gesäß, Beine (gestreckt oder gebeugt) zur Senkrechten heben, langsam absenken, ohne den Boden zu berühren. Unterer Rücken bleibt angedrückt.`, mistakes: `Hohlkreuz, zu schnelles Absenken, Schwung holen.` },
    { type: 'exercise', name: 'Einbeiniges Hüftheben', muscles: 'Gesäß, Beinbeuger, Core', level: 'Mittel', video: `${D}/musculation`, technique: `Klassisches Hüftheben, aber ein Bein gestreckt in der Luft. Durch die Ferse am Boden drücken, das Becken sauber waagerecht anheben, Gesäß anspannen. Bein wechseln.`, mistakes: `Verdrehtes Becken, Hohlkreuz im unteren Rücken, kurzer Bewegungsumfang.` },

    { type: 'h1', text: 'Cardio, Gehen & NEAT' },
    { type: 'p', text: `Über die Einheiten hinaus macht deine tägliche Aktivität (NEAT) einen riesigen Unterschied beim Energieverbrauch und Fettabbau — ohne zu ermüden und ohne Geräte.` },
    { type: 'list', items: [
      `Ziele auf 8 000 bis 10 000 Schritte am Tag: Gehen, Treppen, Wege zu Fuß.`,
      `2 bis 3 zügige Spaziergänge à 30 Min. pro Woche, idealerweise an Ruhetagen.`,
      `Stückle es: 3 × 10 Min. Gehen sind so viel wert wie ein 30-Min.-Block.`,
      `Morgens nüchtern, mit Musik oder Podcast: der beste Moment, um die Gewohnheit durchzuhalten.`,
    ] },
    { type: 'table', headers: ['Aktivität', 'Dauer', 'Häufigkeit', 'Effekt'], rows: [
      ['Gehen (NEAT)', 'Über den ganzen Tag verteilt', 'Täglich', 'Verbrauch, Erholung'],
      ['Zügiges Gehen', '30 Min.', '2-3×/Woche', 'Sanftes Cardio, Fettabbau'],
      ['HIIT-Zirkel', '20-25 Min.', '2×/Woche', 'Fettverbrennung, EPOC'],
    ] },

    { type: 'h1', text: 'Progression über 8 Wochen' },
    { type: 'table', headers: ['Woche', 'Volumen / Format', 'Ziel'], rows: [
      ['W1', '3 Runden, 60 s Pause', 'Bewegungen erlernen'],
      ['W2', '3 Runden, +2 Wdh.', 'Technik festigen'],
      ['W3', '4 Runden', 'Volumen erhöhen'],
      ['W4', '4 Runden, 45 s Pause', 'Zwischenbilanz'],
      ['W5', '4 Runden, schwerere Varianten', 'Schwierigkeit steigern'],
      ['W6', '4 Runden, langsames Tempo', 'Kontrolle verbessern'],
      ['W7', '5 Runden', 'Volumenspitze'],
      ['W8', '5 Runden, 30 s Pause', 'Höhepunkt, Abschlussmessung'],
    ] },

    { type: 'h1', text: 'Passe jede Übung deinem Niveau an' },
    { type: 'p', text: `Beim Körpergewichtstraining läuft der Fortschritt über die Variante. Wähle die Version, mit der du die Wiederholungszahl sauber schaffst, und steigere dann die Schwierigkeit.` },
    { type: 'table', headers: ['Übung', 'Leichter', 'Standard', 'Schwerer'], rows: [
      ['Liegestütz', 'Schräg (Hände erhöht)', 'Am Boden', 'Decline / mit Zusatzgewicht'],
      ['Kniebeuge', 'Auf einen Stuhl', 'Körpergewicht', 'Sprungkniebeuge / bulgarisch'],
      ['Ausfallschritt', 'Statisch, mit Halt', 'Abwechselnd', 'Sprung'],
      ['Plank', 'Auf den Knien', 'Voller Plank', 'Dynamisch / 3 Stützpunkte'],
      ['Dips', 'Füße nah dran', 'Beine halb gestreckt', 'Beine gestreckt'],
      ['Hüftheben', 'Beidbeinig', 'Oben betont halten', 'Einbeinig'],
    ] },

    { type: 'h1', text: 'Plan B: 10-Minuten-Express-Einheit' },
    { type: 'p', text: `Keine Zeit? Eine kurze Einheit ist immer besser als gar keine: sie erhält die Gewohnheit. Mach diesen Zirkel 2-mal, 40 s Belastung / 20 s Übergang, 1 Min. Pause zwischen den Runden.` },
    { type: 'table', headers: ['Übung', 'Dauer', 'Erholung'], rows: [
      ['Kniebeugen', '40 s', '20 s'],
      ['Liegestütze', '40 s', '20 s'],
      ['Mountain Climbers', '40 s', '20 s'],
      ['Abwechselnde Ausfallschritte', '40 s', '20 s'],
      ['Plank', '40 s', '20 s'],
    ] },

    { type: 'h1', text: 'HIIT zuhause' },
    { type: 'p', text: `HIIT ist dein bester Verbündeter, um Fett zu verbrennen — ohne Geräte und ohne viel Platz. Das Prinzip: kurze, intensive Belastungen, unterbrochen von Erholungsphasen.` },
    { type: 'list', items: [
      `Klassisches Format: 40 s Belastung / 20 s Pause, 4 bis 5 Übungen, 3 bis 5 Runden.`,
      `Während der Belastung solltest du keine Unterhaltung führen können.`,
      `2 HIIT-Einheiten pro Woche reichen aus; mehr kann die Erholung beeinträchtigen.`,
      `Passe den Impact an: ersetze Sprünge durch bodennahe Versionen bei empfindlichen Gelenken.`,
    ] },

    { type: 'h1', text: 'Zu vermeidende Fehler' },
    { type: 'list', items: [
      `Glauben, ohne Geräte gäbe es keinen Fortschritt: falsch — nutze die 5 Progressionshebel.`,
      `Die Technik vernachlässigen, um schneller zu sein: Qualität geht vor, gerade beim Körpergewichtstraining.`,
      `Nur Cardio machen: behalte 2 Kräftigungseinheiten pro Woche bei.`,
      `Das Aufwärmen auslassen, besonders vor Zirkeln mit Sprüngen.`,
      `Die Ernährung ignorieren: die Einheit gleicht keine schlechte Ernährung aus.`,
    ] },
    { type: 'h2', text: 'Problem → Lösung' },
    { type: 'table', headers: ['Du erlebst…', 'Die Lösung'], rows: [
      ['Liegestütze sind zu schwer', 'Starte schräg (Hände erhöht)'],
      ['Es ist zu leicht geworden', 'Schwerere Variante, langsames Tempo, Pause −15 s'],
      ['Knieschmerzen (Sprünge)', 'Durch Versionen ohne Impact ersetzen'],
      ['Keine Motivation', 'Lieber eine kurze 15-Min.-Einheit als gar keine'],
    ] },

    { type: 'h1', text: 'Motiviert bleiben' },
    { type: 'list', items: [
      `Leg dir einen festen Zeitpunkt fest: zuhause macht die Routine den Unterschied.`,
      `Leg deine Trainingskleidung und Matte am Vorabend bereit.`,
      `Fotos & Maße alle 4 Wochen: die Veränderung wird sichtbar.`,
      `Halte eine „Plan B"-Einheit von 15 Min. für Tage ohne Zeit bereit.`,
    ] },
    { type: 'h2', text: 'Bau dir die Gewohnheit auf' },
    { type: 'list', items: [
      `Verknüpfe deine Einheit mit einem festen Moment (nach dem Aufstehen, vor dem Abendessen).`,
      `2-Minuten-Regel: fang einfach mit dem Aufwärmen an.`,
      `Lass nie 2 Einheiten hintereinander ausfallen.`,
    ] },

    { type: 'h1', text: 'Häufige Fragen' },
    { type: 'h2', text: 'Kann man wirklich ohne Gewichte Muskeln aufbauen?' },
    { type: 'p', text: `Ja, besonders als Anfänger oder im mittleren Niveau. Indem du die Schwierigkeit der Varianten, die Wiederholungen und das Tempo erhöhst und die Pause verkürzt, erzeugst du genug Spannung, um Muskeln aufzubauen.` },
    { type: 'h2', text: 'Wie viel Platz brauche ich?' },
    { type: 'p', text: `2 m² reichen: genug, um dich hinzulegen und einen Ausfallschritt zu machen. Keine Geräte nötig; eine Matte verbessert den Komfort am Boden.` },
    { type: 'h2', text: 'Und wenn ich keinen Stuhl für die Dips habe?' },
    { type: 'p', text: `Nutze ein Sofa, ein niedriges Bett oder Stufen. Sonst ersetze sie durch enge Liegestütze (Hände nah beieinander), die ebenfalls den Trizeps ansprechen.` },
    { type: 'h2', text: 'Ich wohne in einer Wohnung, Sprünge stören. Was tun?' },
    { type: 'p', text: `Ersetze alle Sprungbewegungen durch ihre Versionen ohne Impact (Kniebeuge statt Sprungkniebeuge, High Knees statt Hampelmänner). Die Wirksamkeit bleibt hervorragend.` },
    { type: 'h2', text: 'Cardio oder Kräftigung, um Fett zu verlieren?' },
    { type: 'p', text: `Beides. Kräftigung erhält den Muskel, HIIT und Gehen erhöhen den Verbrauch. Und vor allem: die Ernährung. Das Programm kombiniert bereits alles.` },

    { type: 'h1', text: 'Sicherheit & Impact' },
    { type: 'p', text: `Training zuhause ist sehr sicher. Hier ein paar Anhaltspunkte, um intensiv zu trainieren, ohne dich zu verletzen — auch auf hartem Boden oder in einer Wohnung.` },
    { type: 'list', items: [
      `Wärme dich immer auf, besonders vor Sprungbewegungen.`,
      `Weiche Landung auf dem Vorfuß, Knie gebeugt, bei jedem Sprung.`,
      `Harter Boden oder Nachbarn unter dir: ersetze Sprünge durch Versionen ohne Impact.`,
      `Halte den Rücken bei Liegestützen, Ausfallschritten und Plank fest und neutral.`,
      `Gelenkschmerz = Stopp. Wähle eine sanftere Variante.`,
    ] },

    { type: 'h1', text: 'Dehnen & Beweglichkeit' },
    { type: 'p', text: `5-10 Min. nach jeder Einheit, halte jede Position 20-30 s.` },
    { type: 'table', headers: ['Dehnung', 'Bereich', 'Dauer'], rows: [
      ['Quadrizeps stehend', 'Oberschenkelvorderseite', '30 s / Seite'],
      ['Beinbeuger gestrecktes Bein', 'Oberschenkelrückseite', '30 s / Seite'],
      ['Tiefer Ausfallschritt', 'Hüften', '30 s / Seite'],
      ['Brust an der Wand', 'Brust, Schultern', '30 s / Seite'],
      ['Katze-Kuh', 'Wirbelsäule', '45 s'],
    ] },

    { type: 'h1', text: 'Morgen-Mobilitätsroutine (5 Min.)' },
    { type: 'p', text: `Direkt nach dem Aufstehen oder an Ruhetagen: 5 Minuten, um den Körper zu wecken, die Haltung zu verbessern und die Gelenke vorzubereiten. Keine Geräte, flüssig aneinanderreihen.` },
    { type: 'table', headers: ['Bewegung', 'Ziel', 'Dauer'], rows: [
      ['Katze-Kuh', 'Wirbelsäule', '45 s'],
      ['Schulter- & Hüftkreisen', 'Gelenke', '45 s'],
      ['Tiefer Ausfallschritt + Rotation', 'Hüften, Rücken', '30 s / Seite'],
      ['Gehaltene tiefe Kniebeuge', 'Hüften, Knöchel', '45 s'],
      ['Beckenkippen im Stehen', 'Unterer Rücken', '45 s'],
      ['Nacken- & Halsdehnung', 'Halswirbelsäule', '30 s'],
    ] },

    { type: 'h1', text: 'Deinen Fortschritt messen (mehr als die Waage)' },
    { type: 'p', text: `Die Waage erzählt nur einen Teil der Geschichte. Beim Körpergewichtstraining sind Leistung und der Spiegel deine besten Indikatoren.` },
    { type: 'list', items: [
      `Leistung: mehr Wiederholungen, schwerere Varianten, längerer Plank, weniger Pause.`,
      `Fotos: gleiches Licht, gleicher Winkel, gleiche Uhrzeit, alle 4 Wochen.`,
      `Maße: Taillenumfang, Hüfte, Oberschenkel, Arme — oft aussagekräftiger als das Gewicht.`,
      `Gefühl: Energie, Schlaf, weiter sitzende Kleidung, verbesserte Haltung.`,
      `Wiege dich nur einmal pro Woche, nüchtern, am selben Tag: das Gewicht schwankt täglich.`,
    ] },

    { type: 'h1', text: 'Tracking deines Fortschritts' },
    { type: 'p', text: `Fülle diese Tabellen jede Woche unter den gleichen Bedingungen aus.` },
    { type: 'h2', text: 'Gewicht & Maße' },
    { type: 'tracker', columns: ['Datum', 'Gewicht (kg)', 'Taillenumfang', 'Energie /10'], rows: 8 },
    { type: 'h2', text: 'Leistungen (Wdh. oder Zeit)' },
    { type: 'tracker', columns: ['Übung', 'W1', 'W3', 'W5', 'W8'], rows: 6 },

    { type: 'h1', text: 'Wöchentliche Checkliste' },
    { type: 'p', text: `Hake jedes Kästchen am Ende der Woche ab. Ziel: mindestens 5 von 7.` },
    { type: 'checklist', items: [
      `Ich habe meine 4 Einheiten diese Woche gemacht.`,
      `Ich habe auf eine saubere Technik geachtet.`,
      `Ich habe Fortschritte gemacht (Wdh., Variante oder kürzere Pause).`,
      `Ich habe bei jeder Mahlzeit Eiweiß gegessen.`,
      `Ich habe 2 L Wasser pro Tag getrunken.`,
      `Ich habe die meisten Nächte 7 bis 9 h geschlafen.`,
      `Ich habe meine Leistungen notiert.`,
    ] },

    { type: 'h1', text: 'Persönliche Notizen' },
    { type: 'tracker', columns: ['Meine Notizen, Empfindungen und Erfolge der Woche'], rows: 16 },

    { type: 'h1', text: 'Und nach deinen 8 Wochen?' },
    { type: 'list', items: [
      `Starte einen neuen Zyklus mit den schwersten Varianten und überall 5 Runden.`,
      `Hast du Zugang zu Geräten? Wechsle zum Programm Krafttraining für Anfänger.`,
      `Ziel Fettabbau: mach direkt weiter mit dem Programm Gewichtsverlust.`,
      `Behalte deine „Plan B"-Heimroutine für Tage ohne Studio bei.`,
    ] },

    { type: 'note', text: `8 Wochen ganz ohne Ausrede — das ist bereits ein Sieg. Mach erneut deine Maße und dein Foto, vergleiche mit deinem Ausgangspunkt und bleib am Ball. Erstelle dein Konto auf xenotif.com.` },
  ],
}
