import type { Guide } from '@/lib/boutique/guides'

// d3 - HIIT Fettverbrennungs-Programm 6 Wochen (DE-Mirror von hiit-6s.ts).
// 24 Einheiten à 20-30 Min., 100% Körpergewicht, ohne Ausrüstung, 3 Level, Timer, Video-QR.
export const hiit6sDe: Guide = {
  id: 'd3',
  title: 'HIIT Fettverbrennungs-Programm - 6 Wochen',
  subtitle: '24 Einheiten à 20-30 Min., 100% Körpergewicht, ganz ohne Ausrüstung',
  author: 'XENOTIF Coach - CrossFit & Athletiktraining zertifiziert',
  level: 'Anfänger → Fortgeschritten',
  duration: '6 Wochen · 24 Einheiten · 20-30 Min.',
  coverImage: 'hiit-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Verbrenne das Maximum in der kürzesten Zeit' },
    { type: 'p', text: `In 6 Wochen verwandelt dieses Programm deine Fitness und lässt Fett schmelzen - ohne Studio, ohne Ausrüstung, wo immer du bist, in kurzen, aber intensiven Einheiten von 20 bis 30 Minuten. Du findest darin die 24 detaillierten Einheiten mit ihren Timern, die Technik jeder Bewegung und drei Level, um vom Anfänger zum Fortgeschrittenen zu kommen.` },
    { type: 'p', text: `Jede Übung hat einen QR-Code zu ihrem Demovideo. Behalte den Leitfaden auf deinem Handy und starte deinen Timer: los geht's.` },
    { type: 'meta', items: [
      { label: 'Ziel', value: 'Fett verbrennen, Ausdauer aufbauen' },
      { label: 'Niveau', value: 'Anfänger bis Fortgeschritten' },
      { label: 'Dauer', value: '6 Wochen · 24 Einheiten' },
      { label: 'Einheit', value: '20 bis 30 Minuten' },
      { label: 'Ausrüstung', value: 'Keine (Körpergewicht)' },
      { label: 'Häufigkeit', value: '4 Einheiten pro Woche' },
    ] },
    { type: 'h2', text: 'Was du bekommst' },
    { type: 'list', items: [
      `Sichtbaren Fettabbau (HIIT verbrennt WÄHREND und NACH dem Effort).`,
      `Deutlich verbesserte Ausdauer und Kondition.`,
      `Einen straffer und athletischeren Körper.`,
      `Eine Express-Routine, die du sogar an vollen Tagen durchhältst.`,
    ] },
    { type: 'h2', text: 'So nutzt du diesen Leitfaden' },
    { type: 'list', items: [
      `Wähle dein Level (Anfänger / Mittel / Fortgeschritten) - siehe eigenes Kapitel.`,
      `Folge den 24 Einheiten der Reihe nach (4 pro Woche).`,
      `Starte einen Intervall-Timer (Belastung / Erholung) für jede Einheit.`,
      `Scanne den QR-Code einer Übung, um die Technik zu sehen.`,
      `Wärme dich 5 Min. vorher auf, dehne dich 5 Min. danach.`,
    ] },
    { type: 'note', text: `Intensität = Schlüssel. In den Belastungsphasen solltest du keine Unterhaltung führen können. In der Erholung holst du aktiv Luft (auf der Stelle marschieren, tief atmen).` },

    { type: 'h1', text: 'Warum HIIT funktioniert' },
    { type: 'p', text: `HIIT (High Intensity Interval Training) wechselt intensive Belastungen mit kurzen Erholungen ab. Ergebnis: du verbrennst Kalorien während des Efforts UND bis zu 24 h danach, dank des EPOC-Effekts (Nachbrenneffekt durch erhöhten Sauerstoffverbrauch).` },
    { type: 'list', items: [
      `Eine 20-Min.-Einheit kann so viel verbrennen wie ein 45-Min.-Lauf.`,
      `Der Körper verbrennt nach der Einheit weiter Kalorien (Nachbrenneffekt).`,
      `HIIT bewahrt den Muskel besser als langes, monotones Cardio.`,
      `Keine Ausrüstung: du kannst überall und jederzeit trainieren.`,
    ] },

    { type: 'chapter', title: 'Wähle dein Level & deinen Timer', src: 'hiit-1.jpg', intro: `Jede Einheit folgt einem Intervallformat. Wähle das Belastungs-/Erholungsverhältnis passend zu deinem Level, stelle dann deinen Timer (oder die XENOTIF-App). Du kannst über die Wochen aufsteigen.` },
    { type: 'table', headers: ['Level', 'Belastung', 'Erholung', 'Runden / Block'], rows: [
      ['Anfänger', '20 s', '40 s', '3'],
      ['Mittel', '40 s', '20 s', '4'],
      ['Fortgeschritten', '45 s', '15 s', '4 bis 5'],
    ] },
    { type: 'h2', text: 'Timer-Regel' },
    { type: 'list', items: [
      `Stelle einen Intervall-Timer mit deinem Verhältnis (z. B. 40 s / 20 s).`,
      `Pause zwischen den Übungsblöcken: 60 s (Anfänger), 45 s (Mittel), 30 s (Fortgeschritten).`,
      `Steige ein Level auf, wenn eine Einheit „bequem" wird.`,
    ] },

    { type: 'h1', text: 'Aufwärmen (5 Min.)' },
    { type: 'p', text: `Unverzichtbar vor jeder HIIT-Einheit, besonders bei explosiven Bewegungen.` },
    { type: 'table', headers: ['Bewegung', 'Dauer'], rows: [
      ['Gehen / Laufen auf der Stelle', '60 s'],
      ['High Knees', '45 s'],
      ['Arm- & Hüftkreisen', '45 s'],
      ['Langsame Kniebeugen', '45 s'],
      ['Dynamische Ausfallschritte + Anfersen', '60 s'],
    ] },

    { type: 'chapter', title: 'Die 24 Einheiten', src: 'hiit-cover.jpg', intro: `Hier sind deine 24 Einheiten (4 pro Woche). Wende DEIN Belastungs-/Erholungsverhältnis an (Level-Kapitel). Jede Zeile = ein Block, der für die Rundenzahl deines Levels wiederholt wird. Wärme dich vorher auf, dehne dich danach.` },
    { type: 'h2', text: 'Woche 1 - Anpassung' },
    { type: 'table', headers: ['Einheit', 'Blöcke', 'Dauer'], rows: [
      ['E1 · Ganzkörper', 'Kniebeugen · Knie-Liegestütze · Mountain Climbers · Plank', '20 Min.'],
      ['E2 · Cardio', 'Hampelmänner · High Knees · Anfersen · Ausfallschritte', '20 Min.'],
      ['E3 · Unten + Core', 'Kniebeugen · Ausfallschritte · Hüftheben · Side-Plank', '20 Min.'],
      ['E4 · Oben + Core', 'Liegestütze · Stuhl-Dips · Pike-Liegestütze · Plank', '20 Min.'],
    ] },
    { type: 'h2', text: 'Woche 2 - Volumen' },
    { type: 'table', headers: ['Einheit', 'Blöcke', 'Dauer'], rows: [
      ['E5 · Ganzkörper', 'Sprungkniebeugen · Liegestütze · Mountain Climbers · Burpees', '22 Min.'],
      ['E6 · Cardio', 'Hampelmänner · High Knees · Skaters · Anfersen', '22 Min.'],
      ['E7 · Unten + Core', 'Sprung-Ausfallschritte · Kniebeugen · Hüftheben · Beinheben', '22 Min.'],
      ['E8 · Oben + Core', 'Liegestütze · Dips · Diamant-Liegestütze · Plank Up-Downs', '22 Min.'],
    ] },
    { type: 'h2', text: 'Woche 3 - Intensität' },
    { type: 'table', headers: ['Einheit', 'Blöcke', 'Dauer'], rows: [
      ['E9 · Ganzkörper', 'Burpees · Sprungkniebeugen · Mountain Climbers · Liegestütze', '25 Min.'],
      ['E10 · Cardio', 'High Knees · Skaters · Hampelmänner · Sprint auf der Stelle', '25 Min.'],
      ['E11 · Unten + Core', 'Sprung-Ausfallschritte · Kniebeugen · Einbeiniges Hüftheben · Plank', '25 Min.'],
      ['E12 · Oben + Core', 'Decline-Liegestütze · Dips · Pike-Liegestütze · Mountain Climbers', '25 Min.'],
    ] },
    { type: 'h2', text: 'Woche 4 - Zirkel' },
    { type: 'table', headers: ['Einheit', 'Blöcke', 'Dauer'], rows: [
      ['E13 · Ganzkörper', 'Burpees · Sprung-Ausfallschritte · Liegestütze · Plank Up-Downs', '25 Min.'],
      ['E14 · Cardio', 'Sprint auf der Stelle · Skaters · Hampelmänner · High Knees', '25 Min.'],
      ['E15 · Unten + Core', 'Sprungkniebeugen · Ausfallschritte · Hüftheben · Beinheben', '25 Min.'],
      ['E16 · Oben + Core', 'Liegestütze · Diamant-Liegestütze · Dips · Side-Plank', '25 Min.'],
    ] },
    { type: 'h2', text: 'Woche 5 - Spitze' },
    { type: 'table', headers: ['Einheit', 'Blöcke', 'Dauer'], rows: [
      ['E17 · Ganzkörper', 'Burpees · Sprungkniebeugen · Liegestütze · Mountain Climbers', '28 Min.'],
      ['E18 · Cardio', 'Sprint auf der Stelle · High Knees · Skaters · Hampelmänner', '28 Min.'],
      ['E19 · Unten + Core', 'Sprung-Ausfallschritte · Kniebeugen · Einbeiniges Hüftheben · Plank', '28 Min.'],
      ['E20 · Oben + Core', 'Decline-Liegestütze · Diamant-Liegestütze · Dips · Plank Up-Downs', '28 Min.'],
    ] },
    { type: 'h2', text: 'Woche 6 - Finish' },
    { type: 'table', headers: ['Einheit', 'Blöcke', 'Dauer'], rows: [
      ['E21 · Ganzkörper', 'Burpees · Sprungkniebeugen · Liegestütze · Plank Up-Downs', '30 Min.'],
      ['E22 · Cardio max', 'Sprint auf der Stelle · Skaters · High Knees · Hampelmänner', '30 Min.'],
      ['E23 · Unten + Core', 'Sprung-Ausfallschritte · Sprungkniebeugen · Hüftheben · Beinheben', '30 Min.'],
      ['E24 · Finale', 'Burpees · Mountain Climbers · Liegestütze · Sprungkniebeugen · Plank', '30 Min.'],
    ] },
    { type: 'note', text: `Verfolge deinen Fortschritt: zähle deine Wiederholungen in einem festen Block (z. B. Burpees in 40 s) in E1, E3 und E6. Du wirst den Unterschied sehen.` },

    { type: 'h1', text: 'Anatomie einer typischen Einheit' },
    { type: 'p', text: `Jede Einheit folgt derselben Struktur. Detailliertes Beispiel einer „Ganzkörper"-Einheit auf mittlerem Level (40 s Belastung / 20 s Erholung, 4 Runden):` },
    { type: 'table', headers: ['Phase', 'Inhalt', 'Dauer'], rows: [
      ['Aufwärmen', 'Leichtes Cardio + Mobilität + Aktivierung', '5 Min.'],
      ['Block 1', 'Burpees - 40 s / 20 s × 4', '4 Min.'],
      ['Block 2', 'Sprungkniebeugen - 40 s / 20 s × 4', '4 Min.'],
      ['Block 3', 'Liegestütze - 40 s / 20 s × 4', '4 Min.'],
      ['Block 4', 'Mountain Climbers - 40 s / 20 s × 4', '4 Min.'],
      ['Cool-down', 'Gehen + Dehnen', '5 Min.'],
    ] },
    { type: 'p', text: `Pause zwischen den Blöcken: 45 s (Mittel). Gesamt ≈ 26 Min. Passe Verhältnisse und Runden an DEIN Level an (Kapitel „Wähle dein Level").` },
    { type: 'note', text: `Videos: jede Übung der untenstehenden Bibliothek hat einen QR-Code, der ihr HD-Demovideo öffnet. Bei Unsicherheit über die Ausführung scanne ihn, bevor du deinen Timer startest.` },

    { type: 'h1', text: 'Übungsbibliothek' },
    { type: 'p', text: `Beherrsche diese Bewegungen. Scanne den QR-Code für das Demovideo.` },
    { type: 'exercise', name: 'Burpee', muscles: 'Ganzer Körper, Cardio', level: 'Fortgeschritten', technique: `Stehen → Hände auf den Boden → Füße nach hinten springen (Plank) → Liegestütz (optional) → Füße heranziehen → Strecksprung mit gestreckten Armen. Flüssig aneinanderreihen.`, mistakes: `Runder Rücken, Landung mit gestreckten Beinen. Landung abfedern, gleichmäßiger Rhythmus statt schnell und schlampig.` },
    { type: 'exercise', name: 'Sprungkniebeugen', muscles: 'Beine, Gesäß, Cardio', level: 'Mittel', technique: `Kniebeuge, dann explosiver Sprung, weiche Landung in der Kniebeugenposition, wiederholen. Anfängerversion: Kniebeuge ohne Sprung.`, mistakes: `Landung mit steifen Knien, vorgebeugter Oberkörper, zu kurzer Bewegungsumfang.` },
    { type: 'exercise', name: 'Mountain Climbers', muscles: 'Bauch, Schultern, Cardio', level: 'Mittel', technique: `Im hohen Plank abwechselnd ein Knie zur Brust ziehen, immer schneller, Hüften tief, Core fest.`, mistakes: `Hüften hoch, durchhängender Rücken, unsauberer Rhythmus.` },
    { type: 'exercise', name: 'Hampelmänner', muscles: 'Cardio, Schultern, Beine', level: 'Anfänger', technique: `Springe und spreize Beine und Arme, dann zurück. Weiche Landung, gleichmäßiger Rhythmus.`, mistakes: `Steife Landung, unvollständige Armbewegung.` },
    { type: 'exercise', name: 'High Knees', muscles: 'Cardio, Hüftbeuger, Bauch', level: 'Anfänger', technique: `Auf der Stelle laufen und die Knie auf Hüfthöhe heben, schneller Rhythmus, fester Core, Arme schwingen mit.`, mistakes: `Oberkörper nach hinten geneigt, Knie zu tief, schwerer Schritt.` },
    { type: 'exercise', name: 'Skaters', muscles: 'Beine, Gesäß, Cardio, Gleichgewicht', level: 'Mittel', technique: `Seitlicher Sprung von einem Fuß auf den anderen, freies Bein nach hinten, wie ein Eisschnellläufer. Weiche Landung, fester Core.`, mistakes: `Steife Landung, zu wenig seitlicher Umfang, einknickender Oberkörper.` },
    { type: 'exercise', name: 'Liegestütze', muscles: 'Brust, Trizeps, Schultern, Core', level: 'Anfänger - Mittel', technique: `Körper fest, Brust zum Boden senken, Ellbogen ~45°, drücken. Varianten: Knie (leicht) → Boden → Decline (schwer).`, mistakes: `Hüften sacken ab, Ellbogen zu weit abgespreizt, kurzer Umfang.` },
    { type: 'exercise', name: 'Diamant-Liegestütze', muscles: 'Trizeps, Brust', level: 'Fortgeschritten', technique: `Hände nah beieinander bilden eine Raute unter der Brust, absenken, dann drücken. Belastet stark den Trizeps.`, mistakes: `Ellbogen spreizen, unvollständiger Umfang, Hohlkreuz.` },
    { type: 'exercise', name: 'Stuhl-Dips', muscles: 'Trizeps, Schultern', level: 'Anfänger - Mittel', technique: `Hände auf der Stuhlkante, Beine vorn, durch Beugen der Ellbogen nach hinten absenken, hochdrücken. Gestreckte Beine = schwerer.`, mistakes: `Schultern hochgezogen, kurzes Absenken, instabiler Stuhl.` },
    { type: 'exercise', name: 'Sprung-Ausfallschritte', muscles: 'Beine, Gesäß, Cardio', level: 'Fortgeschritten', technique: `Aus einem Ausfallschritt springen und in der Luft das Bein wechseln, weiche Landung im Ausfallschritt. Anfängerversion: abwechselnde Ausfallschritte ohne Sprung.`, mistakes: `Vorderes Knie schiebt zu weit nach vorn, vorgebeugter Oberkörper, steife Landung.` },
    { type: 'exercise', name: 'Plank Up-Downs', muscles: 'Bauch, Schultern, Core', level: 'Mittel', technique: `Im Plank abwechselnd von den Unterarmen auf gestreckte Hände und zurück wechseln, dabei die Hüften stabil halten.`, mistakes: `Hüften schwingen, durchhängender Rücken, zu schneller Rhythmus.` },
    { type: 'exercise', name: 'Beinheben', muscles: 'Unterer Bauch, Core', level: 'Anfänger', technique: `Liegend, Hände unter dem Gesäß, Beine zur Senkrechten heben, langsam absenken, ohne den Boden zu berühren. Unterer Rücken angedrückt.`, mistakes: `Hohlkreuz, zu schnelles Absenken, Schwung.` },
    { type: 'exercise', name: 'Sprint auf der Stelle', muscles: 'Cardio, Beine', level: 'Mittel', technique: `So schnell wie möglich auf der Stelle laufen, schneller Schritt auf dem Vorfuß, aktive Arme, fester Core. Maximale Intensität.`, mistakes: `Schwerer Schritt, steifer Oberkörper, zu geringe Intensität.` },
    { type: 'exercise', name: 'Anfersen', muscles: 'Cardio, Beinbeuger', level: 'Anfänger', technique: `Auf der Stelle laufen und die Fersen zum Gesäß bringen, schneller Rhythmus, aktiver Core.`, mistakes: `Vorgebeugter Oberkörper, zu kurzer Umfang, träger Rhythmus.` },
    { type: 'exercise', name: 'Pike-Liegestütze', muscles: 'Schultern, Trizeps', level: 'Mittel', technique: `Im umgekehrten „V" (Hüften hoch), den Scheitel zum Boden senken, indem du die Ellbogen beugst, dann drücken. Trainiert die Schultern.`, mistakes: `Runder Rücken, kurzer Umfang, Ellbogen zu weit abgespreizt.` },
    { type: 'exercise', name: 'Hüftheben', muscles: 'Gesäß, Beinbeuger', level: 'Anfänger', technique: `Auf dem Rücken, Knie gebeugt, durch die Fersen drücken, um die Hüften zu heben, oben das Gesäß anspannen, ohne abzusetzen senken.`, mistakes: `Hohlkreuz, zu hoch heben, Füße zu weit weg.` },
    { type: 'exercise', name: 'Decline-Liegestütze', muscles: 'Obere Brust, Schultern, Trizeps', level: 'Fortgeschritten', technique: `Füße erhöht (Stuhl/Sofa), Körper fest, Brust zum Boden senken, dann drücken. Je höher die Füße, desto schwerer.`, mistakes: `Hüften sacken ab, kurzer Umfang, Ellbogen zu weit abgespreizt.` },
    { type: 'exercise', name: 'Side-Plank', muscles: 'Schräge Bauchmuskeln, Core', level: 'Anfänger', technique: `Auf der Seite, auf einem Unterarm gestützt, Körper in einer Linie, Hüften angehoben. Halten, dann die Seite wechseln.`, mistakes: `Hüften sacken ab, Körper kippt nach vorn.` },

    { type: 'h1', text: 'Nach Level anpassen' },
    { type: 'p', text: `Jede Bewegung hat eine leichtere und eine schwerere Version: du kannst alle 24 Einheiten auf jedem Level machen.` },
    { type: 'table', headers: ['Übung', 'Leichter', 'Schwerer'], rows: [
      ['Burpee', 'Ohne Liegestütz / ohne Sprung', 'Mit Liegestütz + Tuck Jump'],
      ['Sprungkniebeuge', 'Körpergewichts-Kniebeuge', 'Sprungkniebeuge + 180°'],
      ['Liegestütz', 'Auf Knien / schräg', 'Decline / Diamant'],
      ['Sprung-Ausfallschritt', 'Abwechselnder Ausfallschritt', 'Sprung-Ausfallschritt + Tempo'],
      ['Mountain Climber', 'Langsamer', 'Schnell Cross-Body'],
    ] },

    { type: 'chapter', title: 'Ernährung zum Verbrennen', src: 'nutrition.jpg', intro: `HIIT beschleunigt den Fettabbau, aber der Teller bleibt König. Keine komplizierte Diät nötig: wende diese Richtwerte an und die Definition zeigt sich schneller.` },
    { type: 'meta', items: [
      { label: 'Defizit', value: '300 bis 500 kcal / Tag' },
      { label: 'Eiweiß', value: '1,8 bis 2 g pro kg' },
      { label: 'Trinken', value: '2 bis 3 L pro Tag' },
      { label: 'Schlaf', value: '7 bis 8 h' },
    ] },
    { type: 'list', items: [
      `Eine Eiweißquelle bei jeder Mahlzeit (bewahrt den Muskel).`,
      `Viel Gemüse für Volumen und Sättigung.`,
      `Kohlenhydrate rund um die HIIT-Einheit für Energie.`,
      `Flüssigen Zucker und Alkohol streichen - der schnellste Sieg.`,
      `Trinke: HIIT lässt dich stark schwitzen.`,
    ] },
    { type: 'h2', text: '4 Express-Fettverbrennungsrezepte' },
    { type: 'h2', text: 'Skyr-Obst-Bowl nach HIIT' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 300 kcal' }, { label: 'Eiweiß', value: '30 g' }] },
    { type: 'list', items: [`200 g Skyr`, `Beeren`, `30 g Haferflocken`] },
    { type: 'p', text: `Mischen. Füllt das Eiweiß nach der Einheit wieder auf.` },
    { type: 'h2', text: 'Gemüse-Omelett' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 320 kcal' }, { label: 'Eiweiß', value: '28 g' }] },
    { type: 'list', items: [`3 Eier`, `Spinat, Paprika`, `Grüner Salat`] },
    { type: 'p', text: `Gemüse anschwitzen, Eier angießen, mit einem Salat servieren.` },
    { type: 'h2', text: 'Hähnchen-Reis-Gemüse-Bowl' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 470 kcal' }, { label: 'Eiweiß', value: '40 g' }] },
    { type: 'list', items: [`130 g Hähnchen`, `100 g Reis (roh)`, `Gemüse`, `Sojasoße`] },
    { type: 'p', text: `Reis kochen, Hähnchen und Gemüse anbraten, zusammenstellen.` },
    { type: 'h2', text: 'Eiweiß-Shake' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 200 kcal' }, { label: 'Eiweiß', value: '25 g' }] },
    { type: 'list', items: [`1 Portion Whey`, `250 ml Wasser oder Magermilch`, `Eiswürfel`] },
    { type: 'p', text: `Schütteln. Praktisch direkt nach dem Training.` },

    { type: 'h1', text: 'Gehen & NEAT' },
    { type: 'p', text: `Über die HIIT-Einheiten hinaus macht deine Alltagsaktivität (NEAT) einen großen Unterschied beim Verbrauch - ohne zu ermüden oder deine Erholung zu beeinträchtigen.` },
    { type: 'list', items: [
      `Ziele auf 8 000 bis 10 000 Schritte/Tag: Treppen, Wege zu Fuß, ein Spaziergang nach den Mahlzeiten.`,
      `An Tagen ohne HIIT mach 30 Min. zügiges Gehen.`,
      `Stückle es: 3 × 10 Min. Gehen sind so viel wert wie ein 30-Min.-Block.`,
      `Gehen hilft dir, dich vom HIIT zu erholen (Durchblutung, Stressmanagement).`,
    ] },

    { type: 'h1', text: 'Erholung' },
    { type: 'list', items: [
      `HIIT ist fordernd: lass mindestens 1 Ruhetag zwischen 2 harten Einheiten.`,
      `Schlafe 7 bis 8 h: die Erholung bestimmt deine Leistung und den Fettabbau.`,
      `Dehne dich und nutze Foam Rolling, falls vorhanden.`,
      `Ein Spaziergang an freien Tagen erhält den Verbrauch ohne zu ermüden.`,
    ] },

    { type: 'h1', text: 'Zu vermeidende Fehler' },
    { type: 'list', items: [
      `Das Aufwärmen auslassen: hohes Verletzungsrisiko bei explosiven Bewegungen.`,
      `Die Technik vernachlässigen, um schneller zu sein: Qualität vor Tempo.`,
      `Jeden Tag HIIT machen: 4 Einheiten/Woche reichen, Ruhe gehört zum Plan.`,
      `Den Teller vernachlässigen: HIIT gleicht keinen Kalorienüberschuss aus.`,
      `Steife Landungen bei Sprüngen: federe immer ab, um Knie und Sprunggelenke zu schützen.`,
    ] },
    { type: 'h2', text: 'Problem → Lösung' },
    { type: 'table', headers: ['Du erlebst…', 'Die Lösung'], rows: [
      ['Zu schwer, die Belastung zu halten', 'Ein Level runter (Verhältnis mit mehr Erholung)'],
      ['Knieschmerzen (Sprünge)', 'Versionen ohne Impact (Kniebeuge, High Knees)'],
      ['Kein Fettabbau', 'Den Teller prüfen: er entscheidet'],
      ['Zu leicht', 'Ein Level rauf, eine Runde mehr'],
    ] },

    { type: 'h1', text: 'Motiviert bleiben' },
    { type: 'list', items: [
      `Setze dir eine messbare Herausforderung (z. B. „+5 Burpees in 40 s in 6 Wochen").`,
      `Mach alle 2 Wochen ein Foto und nimm deine Maße.`,
      `Leg eine energiegeladene Playlist auf: der Beat steigert die Intensität.`,
      `20 Minuten sind kurz: denk daran, du bist fertig, bevor du Zeit zum Aufgeben hast.`,
    ] },

    { type: 'h1', text: 'Häufige Fragen' },
    { type: 'h2', text: 'Ich bin Anfänger, ist es zu schwer?' },
    { type: 'p', text: `Nein: das Anfängerlevel (20 s Belastung / 40 s Erholung) ist machbar, und jede Übung hat eine vereinfachte Version. Starte dort, steige auf, wenn du dich bereit fühlst.` },
    { type: 'h2', text: 'Wie oft pro Woche?' },
    { type: 'p', text: `4 Einheiten pro Woche, mit mindestens einem Ruhetag zwischen harten Einheiten. Mehr ist unnötig: Erholung gehört zum Ergebnis.` },
    { type: 'h2', text: 'Reicht HIIT, um Fett zu verlieren?' },
    { type: 'p', text: `HIIT beschleunigt den Verbrauch stark, aber der Fettabbau entscheidet sich zu 70 % auf dem Teller. Kombiniere HIIT + ein leichtes Ernährungsdefizit.` },
    { type: 'h2', text: 'Ich wohne in einer Wohnung, die Sprünge stören die Nachbarn.' },
    { type: 'p', text: `Ersetze alle Sprungbewegungen durch ihre Versionen ohne Impact (Kniebeugen, High Knees statt Hampelmänner). Die Intensität bleibt hoch.` },
    { type: 'h2', text: 'Brauche ich Ausrüstung?' },
    { type: 'p', text: `Keine. Nur ein stabiler Stuhl für die Dips (optional) und ein Intervall-Timer (dein Handy reicht).` },

    { type: 'h1', text: 'Cool-down & Dehnen' },
    { type: 'p', text: `5 Minuten nach jeder Einheit, um das Herz herunterzubringen und Muskelkater zu begrenzen. Halte jede Dehnung 20-30 s.` },
    { type: 'table', headers: ['Dehnung', 'Bereich', 'Dauer'], rows: [
      ['Langsames Gehen', 'Herz', '1-2 Min.'],
      ['Quadrizeps stehend', 'Oberschenkelvorderseite', '30 s / Seite'],
      ['Beinbeuger gestrecktes Bein', 'Oberschenkelrückseite', '30 s / Seite'],
      ['Waden an der Wand', 'Waden', '30 s / Seite'],
      ['Brust & Schultern', 'Oberkörper', '30 s / Seite'],
      ['Tiefe Atmung', 'Erholung', '1 Min.'],
    ] },

    { type: 'h1', text: 'Sicherheit & Impact' },
    { type: 'list', items: [
      `Wärme dich immer vor explosiven Bewegungen auf (Burpees, Sprünge).`,
      `Weiche Landung auf dem Vorfuß, Knie gebeugt, bei jedem Sprung.`,
      `Harter Boden oder Wohnung: ersetze Sprünge durch Versionen ohne Impact.`,
      `Halte den Rücken bei Liegestützen, Ausfallschritten und Plank fest und neutral.`,
      `Scharfer Gelenkschmerz = Stopp. Wähle eine sanftere Variante oder ruhe dich aus.`,
    ] },

    { type: 'h1', text: 'Und nach deinen 6 Wochen?' },
    { type: 'list', items: [
      `Mach den Referenztest erneut (Wdh. in 40 s): vergleiche mit Woche 1.`,
      `Starte einen neuen Zyklus auf dem nächsthöheren Level (anspruchsvolleres Verhältnis, mehr Runden).`,
      `Kombiniere mit Krafttraining (Heim-Fitness / Kraft), um dich zu straffen.`,
      `Behalte 2 HIIT-Einheiten/Woche zum Erhalt, sobald dein Ziel erreicht ist.`,
    ] },

    { type: 'h1', text: 'Intensität verstehen' },
    { type: 'p', text: `HIIT funktioniert nur, wenn der Effort WIRKLICH intensiv ist. Um dich ohne Pulsmesser zu orientieren, nutze den „Sprechtest": deine Sprechfähigkeit zeigt deine Intensität an.` },
    { type: 'table', headers: ['Zone', 'Gefühl', 'Sprechtest', 'Einsatz'], rows: [
      ['Niedrig', 'Sehr leicht', 'Du kannst singen', 'Aufwärmen, Gehen'],
      ['Moderat', 'Anhaltend', 'Kurze Sätze', 'Aktive Erholung'],
      ['Hoch', 'Hart, außer Atem', 'Wenige Worte', 'HIIT-Belastungsphasen'],
      ['Maximal', 'Sehr hart', 'Sprechen unmöglich', 'Sprints, Finisher'],
    ] },
    { type: 'list', items: [
      `In der Belastung: ziele auf „hoch bis maximal" - du solltest nicht plaudern können.`,
      `In der Erholung: komm runter auf „moderat", atme tief.`,
      `Wenn du während der Belastung eine Unterhaltung führen kannst, gibst du nicht genug.`,
    ] },

    { type: 'h1', text: 'Deine typische Woche' },
    { type: 'p', text: `Verteile deine 4 Einheiten mit mindestens einem Ruhetag zwischen den härtesten. Beispielwoche:` },
    { type: 'table', headers: ['Tag', 'Programm'], rows: [
      ['Montag', 'HIIT-Einheit (Ganzkörper)'],
      ['Dienstag', 'Gehen 30 Min. / Pause'],
      ['Mittwoch', 'HIIT-Einheit (Cardio)'],
      ['Donnerstag', 'Aktive Pause'],
      ['Freitag', 'HIIT-Einheit (Unten + Core)'],
      ['Samstag', 'HIIT-Einheit (Oben + Core)'],
      ['Sonntag', 'Pause + Tracking'],
    ] },

    { type: 'h1', text: 'Fettverbrennungs-Finisher (Bonus)' },
    { type: 'p', text: `An Tagen, an denen du 5 Minuten mehr hast, füge am Ende der Einheit einen Finisher für einen Verbrauchsschub hinzu. Tabata-Format: 20 s maximaler Effort / 10 s Pause, 8 Runden.` },
    { type: 'table', headers: ['Finisher', 'Format', 'Ziel'], rows: [
      ['Tabata Burpees', '20 s / 10 s × 8', 'Ganzer Körper'],
      ['Tabata Sprungkniebeugen', '20 s / 10 s × 8', 'Beine'],
      ['Tabata Mountain Climbers', '20 s / 10 s × 8', 'Bauch, Cardio'],
      ['Tabata Sprint auf der Stelle', '20 s / 10 s × 8', 'Cardio max'],
    ] },
    { type: 'note', text: `Ein Tabata-Finisher dauert nur 4 Minuten, haut dich aber um: perfekt, um stark abzuschließen, ohne die Einheit zu verlängern.` },

    { type: 'h1', text: 'Tracking deines Fortschritts' },
    { type: 'p', text: `Notiere deine Leistungen und Maße jede Woche.` },
    { type: 'h2', text: 'Gewicht & Energie' },
    { type: 'tracker', columns: ['Datum', 'Gewicht (kg)', 'Taille (cm)', 'Energie /10'], rows: 7 },
    { type: 'h2', text: 'Referenztest (Wdh. in 40 s)' },
    { type: 'tracker', columns: ['Übung', 'W1', 'W3', 'W6'], rows: 5 },

    { type: 'h1', text: 'Wöchentliche Checkliste' },
    { type: 'p', text: `Hake jedes Kästchen am Ende der Woche ab. Ziel: mindestens 5 von 7.` },
    { type: 'checklist', items: [
      `Ich habe meine 4 Einheiten diese Woche gemacht.`,
      `Ich habe mich vor jeder Einheit aufgewärmt.`,
      `Ich habe maximale Intensität in den Belastungen gegeben.`,
      `Ich habe bei jeder Mahlzeit Eiweiß gegessen.`,
      `Ich habe ein leichtes Kaloriendefizit eingehalten.`,
      `Ich habe 2 L+ Wasser pro Tag getrunken.`,
      `Ich habe meine Leistungen notiert.`,
    ] },

    { type: 'h1', text: 'Persönliche Notizen' },
    { type: 'tracker', columns: ['Meine Einheiten, Empfindungen und Rekorde der Woche'], rows: 16 },

    { type: 'note', text: `6 Wochen geschafft? Mach den Referenztest erneut, um deinen Fortschritt zu messen, dann starte einen neuen Zyklus auf höherem Level oder mach mit dem Programm Cardio-Ausdauer / Heim-Fitness weiter. Erstelle dein Konto auf xenotif.com.` },
  ],
}
