import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Fortgeschrittenes Krafttraining-Programm (DE-Mirror von musculation-avance.ts). Premium-Vorlage XENOTIF® (≈30 Seiten).
export const musculationAvanceDe: Guide = {
  id: 'musculation-avance',
  title: 'Fortgeschrittenes Krafttraining-Programm',
  subtitle: '12 Wochen mit hoher Intensität, um dein Plateau zu durchbrechen und den Muskelaufbau zu maximieren',
  author: 'XENOTIF Coach - Athletiktraining zertifiziert',
  level: 'Fortgeschritten',
  duration: '12 Wochen · 5 bis 6 Einheiten/Woche',
  coverImage: 'cover.jpg',
  blocks: [
    { type: 'h1', text: 'Durchbrich dein Plateau' },
    { type: 'p', text: `Du trainierst seit Jahren und der Fortschritt verlangsamt sich? Dieses fortgeschrittene Programm kombiniert hohes Volumen, kontrollierte Intensität, Periodisierung und Intensivierungstechniken, um das Muskelwachstum neu anzukurbeln und Plateaus zu durchbrechen. Es ist anspruchsvoll: Es richtet sich an erfahrene Athleten, die ein hohes Arbeitspensum und die dazugehörige Erholung managen können.` },
    { type: 'p', text: `Jede Übung hat einen QR-Code zu ihrem Video auf XENOTIF®. Auf deinem Niveau steckt der Teufel im Detail: Ausführung, Tempo, Erholung, Selbststeuerung.` },
    { type: 'meta', items: [
      { label: 'Ziel', value: 'Hypertrophie & Maximalkraft' },
      { label: 'Niveau', value: 'Fortgeschritten (2+ Jahre)' },
      { label: 'Dauer', value: '12 Wochen (periodisiert)' },
      { label: 'Häufigkeit', value: '5 bis 6 Einheiten/Woche' },
      { label: 'Ausrüstung', value: 'Komplettes Fitnessstudio' },
      { label: 'Split', value: 'PPL (Push/Pull/Legs ×2)' },
    ] },
    { type: 'h2', text: 'Ziele des Programms' },
    { type: 'list', items: [
      `Die Hypertrophie nach einer Stagnationsphase neu ankurbeln.`,
      `Die Kraft bei den Hauptbewegungen steigern (mit konkreten Zielwerten).`,
      `Periodisierung und Selbststeuerung (RPE/RIR) beherrschen.`,
      `Schwachstellen durch gezielte Spezialisierung verbessern.`,
    ] },
    { type: 'h2', text: 'Bist du wirklich auf fortgeschrittenem Niveau?' },
    { type: 'list', items: [
      `Du trainierst seit 2 Jahren oder länger ernsthaft.`,
      `Du beherrschst die Technik der Grundübungen perfekt.`,
      `Du kannst 5 bis 6 Mal pro Woche trainieren und dich gut erholen.`,
      `Du weißt, was RPE/RIR bedeutet, und führst ein Trainingstagebuch.`,
      `Falls nicht, ist das Programm Krafttraining Mittelstufe besser geeignet.`,
    ] },
    { type: 'note', text: `Goldene Regel für Fortgeschrittene: Du machst keine Fortschritte mehr „von allein". Fortschritt entsteht durch Präzision - im Umgang mit Volumen, Intensität, Ermüdung und Schwachstellen.` },

    { type: 'h1', text: 'So funktioniert\'s' },
    { type: 'list', items: [
      `PPL-Split, 2× wiederholt: jeder Muskel wird 2× pro Woche trainiert.`,
      `Hohes Volumen: 16 bis 22 Sätze pro Muskelgruppe und Woche.`,
      `RIR (Reps in Reserve): 2-3 RIR zu Blockbeginn, 0-1 am Blockende.`,
      `Kontrolliertes Tempo: exzentrisch 2-3 s, optionale Pause, kontrollierte konzentrische Phase.`,
      `Pausen: 2-3 Min. (Grundübungen), 60-90 s (Isolationsübungen).`,
      `Selbststeuerung: Passe Last und Volumen an deine Tagesform an (RPE).`,
    ] },
    { type: 'h2', text: 'Intensivierungstechniken' },
    { type: 'p', text: `Setze sie gezielt ein: maximal 2 bis 3 pro Einheit, vor allem bei Isolationsübungen und im letzten Satz der Grundübungen.` },
    { type: 'table', headers: ['Technik', 'Prinzip', 'Anwendung'], rows: [
      ['Dropset', 'Gewicht bei Muskelversagen reduzieren, weitermachen', 'Letzter Satz Isolationsübung'],
      ['Rest-Pause', 'Mini-Pausen von 10-20 s für mehr Wdh.', 'Finish'],
      ['Myo-Reps', 'Aktivierungssatz + Mini-Sätze', 'Isolation, Zeitersparnis'],
      ['Tempo / langsame Exzentrik', 'Absenken über 4-5 s', 'Mind-Muscle-Connection, Schwachstellen'],
      ['Partial Reps', 'Teilwiederholungen am Satzende', 'Maximale Pumpe'],
    ] },

    { type: 'h1', text: 'Aufwärmen & Vorbereitung' },
    { type: 'p', text: `Bei hoher Intensität ist das Aufwärmen kein Kann, sondern ein Muss. Füge bei jeder schweren Grundübung ansteigende Aufwärmsätze hinzu.` },
    { type: 'table', headers: ['Schritt', 'Detail', 'Dauer'], rows: [
      ['Cardio', 'Fahrrad / Rudergerät', '5 Min.'],
      ['Gezielte Mobilität', 'Gelenke des Tages', '3-4 Min.'],
      ['Aktivierung', 'Bänder, Core', '2 Min.'],
      ['Aufwärmsätze', '40/55/70/85 % der 1. Grundübung', '4 Sätze'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Hohes Volumen: Die Ernährung muss präzise stimmen.' },
    { type: 'h1', text: 'Ernährung' },
    { type: 'p', text: `Bei diesem Trainingsvolumen zählt Präzision. Berechne deine Makros, passe sie je nach Fortschritt an und achte auf das Timing rund ums Training.` },
    { type: 'meta', items: [
      { label: 'Kalorien', value: 'Überschuss +200/+350 (oder Recomp)' },
      { label: 'Eiweiß', value: '2 bis 2,4 g pro kg' },
      { label: 'Kohlenhydrate', value: '5 bis 7 g/kg an Trainingstagen' },
      { label: 'Trinken', value: '3 bis 4 L pro Tag' },
    ] },
    { type: 'h2', text: 'Strategie' },
    { type: 'list', items: [
      `Eiweiß auf 4-6 Mahlzeiten verteilen (~0,4 g/kg/Mahlzeit), um die Synthese zu maximieren.`,
      `Optionales Kohlenhydrat-Cycling: mehr Kohlenhydrate an schweren Tagen (Beine, Rücken).`,
      `Mahlzeiten rund ums Training: Kohlenhydrate + Eiweiß vor UND nach den großen Einheiten.`,
      `Passe alle 2 Wochen basierend auf deinem wöchentlichen Gewichtsdurchschnitt an.`,
    ] },
    { type: 'h2', text: 'Deine Makros verstehen' },
    { type: 'table', headers: ['Makro', 'Rolle', 'Zielwert'], rows: [
      ['Eiweiß', 'Aufbau & Erhalt', '2-2,4 g/kg'],
      ['Kohlenhydrate', 'Leistung & Volumen', '5-7 g/kg (Trainingstage)'],
      ['Fette', 'Hormone', '0,8-1 g/kg'],
    ] },
    { type: 'note', text: `Der Überschuss bleibt auch bei Fortgeschrittenen moderat: Du baust in diesem Stadium nur langsam Muskeln auf, unnötiges Fett brauchst du nicht. +0,2 kg/Woche ist ein guter Richtwert.` },

    { type: 'h1', text: 'Rezepte' },
    { type: 'h2', text: 'Intra-/Peri-Training-Shake' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 450 kcal' }, { label: 'Eiweiß', value: '40 g' }] },
    { type: 'list', items: [`1,5 Portionen Whey`, `1 Banane`, `40 g Haferflocken`, `300 ml Milch/Wasser`] },
    { type: 'p', text: `Zubereitung: mixen. Rund um die großen Einheiten trinken, um Energie und Erholung zu unterstützen.` },
    { type: 'h2', text: 'Der kräftige Teller' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 750 kcal' }, { label: 'Eiweiß', value: '55 g' }] },
    { type: 'list', items: [`180 g mageres Fleisch/Fisch`, `140 g Reis (roh)`, `Gemüse`, `Olivenöl`] },
    { type: 'p', text: `Zubereitung: alles kochen, zusammenstellen. Die Hauptmahlzeit an Trainingstagen.` },
    { type: 'h2', text: 'Eiweißreicher Snack' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 400 kcal' }, { label: 'Eiweiß', value: '35 g' }] },
    { type: 'list', items: [`250 g Skyr`, `1 Portion Whey`, `Obst + 30 g Haferflocken`, `Erdnussbutter`] },
    { type: 'p', text: `Zubereitung: mischen. Ideal zwischen zwei Mahlzeiten, um deine Kalorienziele zu erreichen.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Bei hoher Intensität ist Erholung Priorität Nr. 1.' },
    { type: 'h1', text: 'Erholung & Ermüdungsmanagement' },
    { type: 'list', items: [
      `Schlafe 8 bis 9 h: Das ist der wichtigste Erholungsfaktor bei deinem Volumen.`,
      `Deload alle 4-5 Wochen (Volumen −50 %, Intensität beibehalten).`,
      `Behalte Ermüdungsmarker im Blick: Schlaf, Kraft, Motivation, Ruhepuls.`,
      `Trenne große Einheiten (Beine) durch mindestens 48 h.`,
      `Kontrolliere deinen Stress: Er zehrt an derselben Erholungsreserve wie das Training.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: 'PPL ×2: Häufigkeit und Volumen im Dienst des Muskelwachstums.' },
    { type: 'h1', text: '12-Wochen-Plan (periodisiert)' },
    { type: 'p', text: `Drei Blöcke: Akkumulation (Volumen), Intensivierung (Lasten), Realisierung (Kraft/Spitze), dann Deload.` },
    { type: 'table', headers: ['Block', 'Wochen', 'Fokus', 'RIR'], rows: [
      ['Akkumulation', 'W1-W4', 'Maximal tolerierbares Volumen', '2-3 RIR'],
      ['Intensivierung', 'W5-W8', 'Schwerere Lasten', '1-2 RIR'],
      ['Realisierung', 'W9-W11', 'Kraft & Intensität', '0-1 RIR'],
      ['Deload + Tests', 'W12', 'Erholung, dann Tests', 'Leicht'],
    ] },
    { type: 'h2', text: 'Typische Woche (6 Tage, PPL ×2)' },
    { type: 'table', headers: ['Tag', 'Einheit'], rows: [
      ['Montag', 'Push A (Kraft)'],
      ['Dienstag', 'Pull A (Kraft)'],
      ['Mittwoch', 'Legs A (Kraft)'],
      ['Donnerstag', 'Push B (Volumen)'],
      ['Freitag', 'Pull B (Volumen)'],
      ['Samstag', 'Legs B (Volumen)'],
      ['Sonntag', 'Pause + Tracking'],
    ] },

    { type: 'h1', text: 'Deine Einheiten im Detail' },
    { type: 'h2', text: 'Push A (Kraft)' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Bankdrücken', '5', '4 bis 6', '180 s'],
      ['Schulterdrücken', '4', '6 bis 8', '150 s'],
      ['Schrägbankdrücken Kurzhantel', '3', '8 bis 10', '120 s'],
      ['Seitheben', '4', '12 bis 15', '60 s'],
      ['Trizepsstrecken (+ Dropset)', '4', '10 bis 12', '75 s'],
    ] },
    { type: 'h2', text: 'Pull A (Kraft)' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Kreuzheben', '4', '3 bis 5', '210 s'],
      ['Klimmzüge mit Zusatzgewicht', '4', '6 bis 8', '150 s'],
      ['Langhantelrudern', '4', '8 bis 10', '120 s'],
      ['Face Pull', '3', '15', '60 s'],
      ['Bizepscurls (+ Rest-Pause)', '4', '10 bis 12', '60 s'],
    ] },
    { type: 'h2', text: 'Legs A (Kraft)' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Kniebeuge', '5', '4 bis 6', '210 s'],
      ['Beinpresse', '4', '10 bis 12', '150 s'],
      ['Rumänisches Kreuzheben', '3', '8 bis 10', '120 s'],
      ['Beinbeuger + Beinstrecker (Superset)', '3', '12 bis 15', '90 s'],
      ['Wadenheben (+ Partial Reps)', '4', '12 bis 20', '45 s'],
    ] },
    { type: 'p', text: `Die B-Einheiten (Volumen) greifen dieselben Schemata leichter auf: 10-15 Wiederholungen, kürzere Pausen, mehr Intensivierungstechniken (Dropsets, Myo-Reps). Ziel: Volumen und Pump.` },
    { type: 'h2', text: 'Push B (Volumen)' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Schrägbankdrücken Kurzhantel', '4', '10 bis 12', '90 s'],
      ['Bankdrücken Kurzhantel', '3', '12', '90 s'],
      ['Schulterdrücken Maschine', '4', '12 bis 15', '75 s'],
      ['Seitheben (+ Dropset)', '4', '15 bis 20', '45 s'],
      ['Trizepsdrücken am Kabel (+ Myo-Reps)', '4', '12 bis 15', '60 s'],
    ] },
    { type: 'h2', text: 'Pull B (Volumen)' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Latzug', '4', '10 bis 12', '90 s'],
      ['Rudern Maschine / horizontal', '4', '12', '90 s'],
      ['Pullover am Kabel', '3', '12 bis 15', '75 s'],
      ['Face Pull (+ Band Pull-Apart)', '4', '15 bis 20', '45 s'],
      ['Schrägbankcurls (+ Dropset)', '4', '12 bis 15', '60 s'],
    ] },
    { type: 'h2', text: 'Legs B (Volumen)' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Kniebeuge / Hackenschmidt-Kniebeuge', '4', '10 bis 12', '120 s'],
      ['Ausfallschritte im Gehen / Split Squat', '3', '12 / Bein', '90 s'],
      ['Beinstrecker (+ Partial Reps)', '4', '15', '60 s'],
      ['Beinbeuger (+ Myo-Reps)', '4', '15', '60 s'],
      ['Wadenheben (+ Dropset)', '5', '15 bis 20', '45 s'],
    ] },

    { type: 'h1', text: 'Übungsbibliothek' },
    { type: 'p', text: `Die wichtigsten Bewegungen. Scanne den QR-Code für das Demovideo.` },
    { type: 'exercise', name: 'Kniebeuge', muscles: 'Quadrizeps, Gesäß, Beinbeuger, Core', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Hohe oder tiefe Stangenposition je nach Stil, senke dich unter die Parallele ab, Rücken fest, Knie in der Achse, explosives, kontrolliertes Hochdrücken. Sicherheitsablagen bei schweren Sätzen Pflicht.`, mistakes: `Good Morning (Becken kommt zu schnell hoch), Knie fallen nach innen, Verlust der Körperspannung unten.` },
    { type: 'exercise', name: 'Bankdrücken', muscles: 'Brust, Trizeps, Schultern', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Füße fest verankert, Brustkorb gewölbt, Schulterblätter zusammengezogen und tief. Berühre den unteren Brustbereich, Ellbogen ~45-70°, explosives Hochdrücken. Spotter bei schweren Gewichten empfohlen.`, mistakes: `Abprallen von der Brust, Ellbogen zu weit gespreizt, Gesäß hebt ab, instabile Stangenführung.` },
    { type: 'exercise', name: 'Kreuzheben', muscles: 'Komplette hintere Kette', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Stange über der Fußmitte, kräftig anspannen (kontrollierte Valsalva-Atmung), gegen den Boden drücken, Stange nah am Körper führen, ohne Hyperextension aufrichten.`, mistakes: `Runder Rücken, Hüfte am Start zu tief, Stange entfernt sich vom Körper.` },
    { type: 'exercise', name: 'Schulterdrücken', muscles: 'Schultern, Trizeps, Core', level: 'Mittel', video: `${D}/musculation`, technique: `Im Stehen, Gesäß und Bauch angespannt, senkrecht nach oben drücken, Kopf am Ende der Bewegung leicht nach vorn schieben, ausstrecken.`, mistakes: `Hohlkreuz, Drücken nach vorn, unvollständige Streckung.` },
    { type: 'exercise', name: 'Klimmzüge mit Zusatzgewicht', muscles: 'Latissimus, Bizeps', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Gewichtsgurt anlegen, aus tiefer Schulterposition starten, Ellbogen nach unten/hinten ziehen, Kinn über die Stange, vollständig kontrolliert absenken.`, mistakes: `Unvollständiger Bewegungsumfang, ungewolltes Schwingen (Kipping), zu schweres Gewicht, das die Technik zerstört.` },
    { type: 'exercise', name: 'Langhantelrudern', muscles: 'Rücken, Bizeps, hintere Schulter', level: 'Mittel', video: `${D}/musculation`, technique: `Oberkörper 30-45° geneigt, Rücken gerade, zum unteren Bauch ziehen, Schulterblätter zusammenziehen, exzentrische Phase kontrollieren.`, mistakes: `Oberkörper richtet sich auf, runder Rücken, zu hoch ziehen.` },
    { type: 'exercise', name: 'Beinpresse', muscles: 'Quadrizeps, Gesäß', level: 'Anfänger', video: `${D}/musculation`, technique: `Fußposition passend zum Trainingsziel wählen, absenken, ohne den unteren Rücken abzuheben, vollständiger Bewegungsumfang, drücken ohne die Knie hart durchzustrecken.`, mistakes: `Unterer Rücken hebt ab, zu kurzer Bewegungsumfang, hartes Durchstrecken.` },
    { type: 'exercise', name: 'Rumänisches Kreuzheben', muscles: 'Beinbeuger, Gesäß, Rücken', level: 'Mittel', video: `${D}/musculation`, technique: `Hüfte nach hinten schieben, Rücken gerade, Beinbeuger dehnen, durch Anspannen des Gesäßes zurückkommen. Langsame Exzentrik für mehr Muskelaufbau.`, mistakes: `Runder Rücken, Knie beugen sich zu stark, Stange entfernt sich vom Körper.` },
    { type: 'exercise', name: 'Seitheben', muscles: 'Seitliche Schulter (Deltoideus)', level: 'Anfänger', video: `${D}/musculation`, technique: `Leichtes Gewicht wählen, bis zur Horizontalen heben, Ellbogen leicht gebeugt, langsam absenken. Ideal für Dropsets und Myo-Reps.`, mistakes: `Zu schweres Gewicht, Schwungholen, zu hoch heben.` },
    { type: 'exercise', name: 'Face Pull', muscles: 'Hintere Schulter, Rotatorenmanschette', level: 'Anfänger', video: `${D}/musculation`, technique: `Hohe Kabelposition, Seil zum Gesicht ziehen, Ellbogen hoch, am Ende der Bewegung nach außen rotieren. Gut für die Schultergesundheit.`, mistakes: `Zu schweres Gewicht, Ellbogen sinken ab, mit den Armen statt dem Rücken ziehen.` },
    { type: 'exercise', name: 'Bizepscurls', muscles: 'Bizeps', level: 'Anfänger', video: `${D}/musculation`, technique: `Ellbogen fixiert, oben fest anspannen, langsame Exzentrik. Ideal für Rest-Pause zum Abschluss.`, mistakes: `Schwungholen, Ellbogen wandern nach vorn, unvollständiger Bewegungsumfang.` },
    { type: 'exercise', name: 'Trizepsdrücken am Kabel', muscles: 'Trizeps', level: 'Anfänger', video: `${D}/musculation`, technique: `Ellbogen eng am Körper, vollständig strecken, kontrollierte Rückführung. Spannung durchgehend halten.`, mistakes: `Ellbogen spreizen sich ab, Oberkörper hilft mit, zu kurzer Bewegungsumfang.` },
    { type: 'exercise', name: 'Schrägbankdrücken Kurzhantel', muscles: 'Obere Brust, Schultern', level: 'Mittel', video: `${D}/musculation`, technique: `Bank auf ~30°, absenken bis zur Dehnung, hochdrücken und die Hanteln dabei leicht aneinander annähern. Hervorragend für die oft unterentwickelte obere Brust.`, mistakes: `Bank zu steil, zu kurzer Bewegungsumfang, Ellbogen komplett durchgestreckt.` },
    { type: 'exercise', name: 'Bulgarian Split Squat', muscles: 'Quadrizeps, Gesäß, Gleichgewicht', level: 'Mittel', video: `${D}/musculation`, technique: `Hinterer Fuß erhöht auf einer Bank, Becken senkrecht absenken, vorderes Knie in der Achse, dann über die vordere Ferse hochdrücken. Einseitige Übung, ideal zum Ausgleichen von Dysbalancen.`, mistakes: `Oberkörper zu weit nach vorn geneigt, Knie kippt nach innen, Abstützen auf dem hinteren Bein.` },
    { type: 'exercise', name: 'Pullover am Kabel', muscles: 'Latissimus, Brust', level: 'Mittel', video: `${D}/musculation`, technique: `Arme fast gestreckt, Stange/Seil von den Hüften nach oben führen und dabei die Spannung auf dem Rücken halten, dann kontrolliert zurückführen. Dehnt und isoliert den Latissimus.`, mistakes: `Ellbogen beugen (wird zur Trizepsübung), zu kurzer Bewegungsumfang, ruckartige Bewegungen.` },
    { type: 'exercise', name: 'Hip Thrust mit Zusatzgewicht', muscles: 'Gesäß, Beinbeuger', level: 'Mittel', video: `${D}/musculation`, technique: `Oberer Rücken auf einer Bank, Stange auf den Hüften, durch die Fersen drücken bis zur vollen Ausrichtung, oben das Gesäß fest anspannen, kontrolliert absenken.`, mistakes: `Überstreckung im unteren Rücken, unvollständiger Bewegungsumfang, falsche Fußposition.` },

    { type: 'h1', text: 'Spezialisierung auf Schwachstellen' },
    { type: 'p', text: `Auf deinem Niveau kannst du einen Block einer zurückgebliebenen Muskelgruppe widmen. Erhöhe ihre Häufigkeit und ihr Volumen, reduziere den Rest leicht, um die Ermüdung nicht explodieren zu lassen.` },
    { type: 'list', items: [
      `Wähle nur 1 Schwachstelle pro Block (z. B. Schultern, Rücken, Waden).`,
      `Füge 4 bis 8 zusätzliche Sätze pro Woche für diese Gruppe hinzu, als 3. Trainingseinheit für diese Gruppe.`,
      `Setze bei Isolationsübungen auf perfekte Ausführung und Mind-Muscle-Connection.`,
      `Reduziere im Ausgleich eine „starke" Muskelgruppe um 2-4 Sätze.`,
    ] },

    { type: 'h1', text: 'Die 12 Wochen im Detail' },
    { type: 'table', headers: ['Woche', 'Ziel-RIR', 'Hinweis'], rows: [
      ['W1-W2', '3 RIR', 'Hohes Volumen, perfekte Technik'],
      ['W3-W4', '2-3 RIR', '+ Last, Bilanz in W4'],
      ['W5-W6', '2 RIR', 'Intensivierung, Dropsets'],
      ['W7-W8', '1-2 RIR', '+ Last, RPE 8-9'],
      ['W9-W10', '1 RIR', 'Kraft, lange Pausen'],
      ['W11', '0-1 RIR', 'Intensitätsspitze'],
      ['W12', 'Deload', 'Erholung + Krafttests, Bilanz'],
    ] },

    { type: 'h1', text: 'Ein Plateau durchbrechen' },
    { type: 'list', items: [
      `Prüfe zuerst Schlaf, Stress und Kalorien: 80 % der Plateaus kommen daher.`,
      `Mach einen echten Deload: Oft verdeckt Ermüdung den tatsächlichen Fortschritt.`,
      `Erhöhe das Volumen der stagnierenden Muskelgruppe für 3-4 Wochen um 20-30 %.`,
      `Ändere Winkel oder Übungsvariante für einen neuen Reiz.`,
      `Arbeite an der Ausführungsqualität, bevor du mehr Gewicht auflegst.`,
    ] },

    { type: 'h1', text: 'Zu vermeidende Fehler' },
    { type: 'list', items: [
      `Intensivierungstechniken stapeln: Du erzeugst Ermüdung, keinen Muskel.`,
      `Deloads ignorieren: Übertraining wirft dich zurück.`,
      `Schwachstellen oder Rotatorenmanschette/Schultern vernachlässigen (Verletzungsgefahr).`,
      `Ernährung und Schlaf bei hohem Volumen unterschätzen.`,
      `Das Programm wechseln, bevor du dem Protokoll 12 Wochen gegeben hast.`,
    ] },
    { type: 'h2', text: 'Problem → Lösung' },
    { type: 'table', headers: ['Du erlebst…', 'Die Lösung'], rows: [
      ['Stagnation trotz Anstrengung', 'Deload, dann +gezieltes Volumen für 3-4 Wochen'],
      ['Schmerzende Gelenke', 'Lasten reduzieren, + Face Pull/Mobilität'],
      ['Chronische Ermüdung', 'Volumen −30 %, +1 Ruhetag, mehr schlafen'],
      ['Kraft nimmt ab', 'Zeichen von Übertraining: sofortiger Deload'],
    ] },

    { type: 'h1', text: 'Motiviert bleiben' },
    { type: 'list', items: [
      `Setze dir konkrete Kraftziele und visuelle Ziele (Schwachstelle).`,
      `Filme deine schweren Sätze: Deine Technik zu analysieren ist motivierend und hilfreich.`,
      `Fotos & Maße alle 4 Wochen.`,
      `Denk daran: Auf deinem Niveau sind Fortschritte langsam, aber real. Geduld ist eine Fähigkeit.`,
    ] },

    { type: 'h1', text: 'Häufige Fragen' },
    { type: 'h2', text: 'Wie viel Volumen ist optimal?' },
    { type: 'p', text: `Für die meisten Fortgeschrittenen 16 bis 22 Sätze pro Muskelgruppe und Woche. Starte am unteren Ende der Spanne und erhöhe, wenn du dich gut erholst. Mehr ist nicht immer besser: Es zählt das Volumen, von dem du dich auch erholst.` },
    { type: 'h2', text: 'RIR oder RPE?' },
    { type: 'p', text: `Zwei Seiten derselben Medaille. RIR = Reps in Reserve; RPE = 10 − RIR. RIR 2 = RPE 8. Nutze das Konzept, das dir mehr sagt, um dich selbst zu steuern.` },
    { type: 'h2', text: 'Muss ich bis zum Muskelversagen trainieren?' },
    { type: 'p', text: `Selten bei schweren Grundübungen (Risiko/Ermüdung). Eher bei Isolationsübungen am Ende der Einheit. Der Realisierungsblock (W9-W11) nähert sich dem Muskelversagen an; der Rest behält RIR bei.` },
    { type: 'h2', text: 'Welche Supplements auf diesem Niveau?' },
    { type: 'p', text: `Kreatin (3-5 g/Tag), Whey, Koffein vor dem Training. Eventuell Citrullin (Pump) und Elektrolyte bei großen Einheiten. Der Rest hat nur marginale Effekte.` },
    { type: 'h2', text: 'Wie gehe ich mit Zeitmangel um?' },
    { type: 'p', text: `Wechsle zu PPL an 3 Tagen oder Oberkörper/Unterkörper an 4 Tagen und behalte die Intensität bei. Lieber 4 produktive Einheiten als 6 schlampige aus Erholungsmangel.` },

    { type: 'h1', text: 'Cardio & Konditionierung' },
    { type: 'p', text: `Richtig dosiertes Cardio unterstützt deine Erholung (bessere Durchblutung, Arbeitskapazität) und begrenzt die Fettzunahme in Überschussphasen - ohne deine Gains zu kannibalisieren, solange du diese Richtwerte einhältst.` },
    { type: 'list', items: [
      `Tägliches Gehen (8.000-12.000 Schritte): die Basis, ohne jeden Einfluss auf die Erholung.`,
      `2 bis 3 Einheiten moderates Cardio (Zone 2, 25-35 Min.) pro Woche, mit Abstand zum Beintraining.`,
      `Vermeide intensives Cardio am Vortag oder am Tag schwerer Bein-/Rückeneinheiten.`,
      `In einer Definitionsphase: erhöhe das Cardio schrittweise, statt die Kalorien weiter zu kürzen.`,
    ] },
    { type: 'table', headers: ['Typ', 'Dauer', 'Häufigkeit', 'Ziel'], rows: [
      ['Gehen (NEAT)', 'Täglich', 'Jeden Tag', 'Verbrauch, Erholung'],
      ['Cardio Zone 2', '25-35 Min.', '2-3×/Woche', 'Kapazität, Gesundheit'],
      ['Leichtes Intervall', '10-15 Min.', '1×/Woche', 'Konditionierung'],
    ] },

    { type: 'h1', text: 'Mobilität & Gelenkgesundheit' },
    { type: 'p', text: `Je schwerer du trainierst, desto wichtiger sind Mobilität und Gelenkgesundheit. Baue sie fest in deine Routine ein.` },
    { type: 'table', headers: ['Übung', 'Zielbereich', 'Dosis'], rows: [
      ['Face Pull / Band Pull-Apart', 'Schultern (Prävention)', '2-3×/Woche, 2-3 Sätze'],
      ['Mobilität Hüfte/Sprunggelenke', 'Kniebeuge & Kreuzheben', 'Vor dem Beintraining'],
      ['Brustdehnung', 'Schultern', '30 s / Seite'],
      ['Hängen an der Stange', 'Dekompression des Rückens', '30-45 s'],
    ] },

    { type: 'h1', text: 'Sicherheit' },
    { type: 'list', items: [
      `Nutze Sicherheitsablagen und/oder einen Spotter bei Kniebeuge und Bankdrücken.`,
      `Wärme dich mit ansteigenden Aufwärmsätzen bei jeder Grundübung auf.`,
      `Lerne die Valsalva-Atemtechnik, um dich bei schweren Sätzen zu stabilisieren (ohne Übertreibung).`,
      `Opfere niemals die Technik für mehr Gewicht: Das ist die Definition von Ego-Lifting.`,
    ] },

    { type: 'h1', text: 'Und nach deinen 12 Wochen?' },
    { type: 'p', text: `Auf deinem Niveau liegt der Schlüssel zum langfristigen Erfolg in intelligenter Variation und Ermüdungsmanagement über das ganze Jahr.` },
    { type: 'list', items: [
      `Mach einen echten Deload (1 Woche), bevor du einen neuen Block startest.`,
      `Ändere Übungsvarianten und Reihenfolge für einen neuen Reiz.`,
      `Wechsle über das Jahr zwischen hypertrophie- und kraftorientierten Blöcken.`,
      `Widme den nächsten Block einer Schwachstelle, die du in diesen 12 Wochen identifiziert hast.`,
      `Je nach Ziel: Schließe eine Definitionsphase (Gewichtsverlust) oder eine echte Aufbauphase an.`,
    ] },
    { type: 'note', text: `Denke in „Jahren", nicht in „12 Wochen". Die besten Physiques entstehen über Jahre hinweg durch die Aneinanderreihung gut geführter Blöcke und respektierter Erholung.` },

    { type: 'h1', text: 'Dein Trainingstagebuch richtig führen' },
    { type: 'p', text: `Als Fortgeschrittener ist dein Tagebuch dein wichtigstes Fortschrittswerkzeug: Es verwandelt dein Training in steuerbare Daten. Ohne es navigierst du blind.` },
    { type: 'list', items: [
      `Notiere für jede Übung: Gewicht × Wiederholungen × Sätze sowie das RIR des letzten Satzes.`,
      `Notiere deine Tagesform (Energie /10, Schlaf): Das erklärt deine guten und schlechten Einheiten.`,
      `Schau dir vor jedem Arbeitssatz deine letzte Leistung an: Dein Ziel ist es, sie zu schlagen.`,
      `Lies dein Tagebuch jede Woche durch: erkenne stagnierende Übungen, um zu reagieren.`,
      `Halte deine Deloads und Rekorde fest: motivierend und aufschlussreich auf lange Sicht.`,
    ] },
    { type: 'note', text: `„Was gemessen wird, verbessert sich." Zwei Athleten mit demselben Potenzial werden in einem Jahr nicht denselben Körper haben: Wer notiert und anpasst, wird die Nase vorn haben.` },

    { type: 'h1', text: 'Tracking deines Fortschritts' },
    { type: 'p', text: `Notiere alles: Gewichte, Sätze, RIR, Empfindungen. Auf deinem Niveau ist dein Tagebuch dein bester Coach.` },
    { type: 'h2', text: 'Gewicht & Maße' },
    { type: 'tracker', columns: ['Datum', 'Gewicht', 'Arm', 'Oberschenkel', 'Brust', 'Taille'], rows: 7 },
    { type: 'h2', text: 'Maximalkraft (kg) bei den Grundübungen' },
    { type: 'tracker', columns: ['Übung', 'W1', 'W4', 'W8', 'W12'], rows: 5 },

    { type: 'h1', text: 'Wöchentliche Checkliste' },
    { type: 'checklist', items: [
      `Ich habe alle meine Einheiten absolviert und mein Zielvolumen erreicht.`,
      `Ich habe meine Ziel-RIR pro Block eingehalten.`,
      `Ich habe bei mindestens einer Schlüsselübung Fortschritte gemacht.`,
      `Ich habe meine Eiweiß- und Kohlenhydratziele erreicht.`,
      `Ich habe die meisten Nächte 8 bis 9 h geschlafen.`,
      `Ich habe meine Ermüdung im Griff gehabt (kein ungewöhnlicher Kraftabfall).`,
      `Ich habe an meiner Schwachstelle / meiner Mobilität gearbeitet.`,
      `Ich habe alles in meinem Tagebuch notiert.`,
    ] },

    { type: 'h1', text: 'Persönliche Notizen' },
    { type: 'tracker', columns: ['Meine Notizen, Gewichte, RIR und Empfindungen der Woche'], rows: 16 },

    { type: 'h1', text: 'Glossar' },
    { type: 'list', items: [
      `RIR: Reps in Reserve (RIR 2 = es blieben noch 2 Wdh. übrig).`,
      `Periodisierung: das Training in Blöcke gliedern (Volumen, Intensität, Spitze).`,
      `Akkumulation / Intensivierung / Realisierung: die 3 Phasen eines periodisierten Blocks.`,
      `Dropset, Rest-Pause, Myo-Reps: Intensivierungstechniken.`,
      `Valsalva: Atemtechnik zur Stabilisierung bei schweren Lasten.`,
      `Selbststeuerung: Last/Volumen über RPE/RIR an die Tagesform anpassen.`,
      `Deload: Entlastungswoche, um Ermüdung abzubauen.`,
    ] },

    { type: 'note', text: `12 Wochen geschafft? Kompletter Deload, teste deine Maximalwerte, nimm deine Maße, dann starte einen neuen Block mit variierten Übungen oder schließe eine Definitions-/Aufbauphase je nach deinem Ziel an. Erstelle dein Konto auf xenotif.com.` },
  ],
}
