import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Krafttraining-Programm für Anfänger (DE-Mirror von musculation-debutant.ts). Premium-Vorlage XENOTIF® (≈30 Seiten).
export const musculationDebutantDe: Guide = {
  id: 'musculation-debutant',
  title: 'Krafttraining-Programm für Anfänger',
  subtitle: '8 Wochen für ein solides Fundament in Kraft und Muskelaufbau',
  author: 'XENOTIF Coach - Kraft- und Fitnesstraining zertifiziert',
  level: 'Anfänger',
  duration: '8 Wochen · 3 Einheiten/Woche',
  coverImage: 'musculation-debutant-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Willkommen - du startest mit dem Krafttraining' },
    { type: 'p', text: `Dieses Programm ist für echte Anfänger gemacht: keine Erfahrung nötig. In 8 Wochen lernst du die grundlegenden Bewegungsmuster, wirst stärker, baust Muskeln auf und etablierst eine Routine, die du langfristig durchhältst. Technik und Regelmäßigkeit stehen vor dem Gewicht - so machst du schnelle und verletzungsfreie Fortschritte.` },
    { type: 'p', text: `Behalte diesen Leitfaden auf deinem Handy: Jede Übung hat einen QR-Code, der ihr Demovideo auf XENOTIF® öffnet. Bei Unsicherheit über eine Bewegung, scanne ihn einfach.` },
    { type: 'meta', items: [
      { label: 'Ziel', value: 'Kraft, Muskelaufbau & technische Grundlagen' },
      { label: 'Niveau', value: 'Anfänger (keine Erfahrung nötig)' },
      { label: 'Dauer', value: '8 Wochen' },
      { label: 'Häufigkeit', value: '3 Einheiten pro Woche' },
      { label: 'Ausrüstung', value: 'Fitnessstudio oder Kurzhanteln + Langhantel' },
      { label: 'Format', value: 'Ganzkörper an 3 Tagen' },
    ] },
    { type: 'h2', text: 'Ziele des Programms' },
    { type: 'list', items: [
      `Die 6 grundlegenden Bewegungsmuster beherrschen (Kniebeuge, Hüftbeugung, Drücken, Ziehen, Ausfallschritt, Rumpfstabilisation).`,
      `Schnell an Kraft gewinnen (die Fortschritte als Anfänger sind die beeindruckendsten).`,
      `Muskeln aufbauen und den ganzen Körper straffen.`,
      `Eine Trainingsroutine aufbauen, die du langfristig beibehältst.`,
    ] },
    { type: 'h2', text: 'So nutzt du diesen Leitfaden' },
    { type: 'list', items: [
      `Lies den Leitfaden komplett durch und folge dann dem 8-Wochen-Kalender.`,
      `Starte leicht: beherrsche die Bewegung, bevor du Gewicht hinzufügst.`,
      `Wärme dich vor jeder Einheit 5-8 Min. auf (eigene Seite dazu).`,
      `Scanne den QR-Code einer Übung, um die Technik im Video zu sehen.`,
      `Notiere deine Gewichte bei jeder Einheit und ziehe sonntags Bilanz.`,
    ] },
    { type: 'note', text: `Goldene Regel für Anfänger: Technik vor Gewicht. Eine saubere Wiederholung ist mehr wert als zehn schlampige. Muskeln entstehen durch die Qualität der Bewegung, nicht durch Ego.` },

    { type: 'h1', text: 'So funktioniert’s' },
    { type: 'list', items: [
      `Ganzkörper: Du trainierst bei jeder Einheit den ganzen Körper, 3-mal pro Woche.`,
      `Mindestens 1 Ruhetag zwischen den Einheiten (z. B. Montag / Mittwoch / Freitag).`,
      `Sätze × Wiederholungen: „3 × 10" = 3 Sätze mit je 10 Wiederholungen.`,
      `Kontrolliertes Tempo: 2 s beim Absenken, 1 s beim Hochdrücken. Niemals ruckartig.`,
      `Pause: 90 s bei den großen Grundübungen, 60 s bei den restlichen.`,
      `RPE 7 bis 8: behalte 2-3 Wiederholungen in Reserve. Als Anfänger gehst du nicht bis zum Muskelversagen.`,
    ] },
    { type: 'h2', text: 'Die 6 grundlegenden Bewegungsmuster' },
    { type: 'p', text: `Alles basiert auf 6 Bewegungsmustern. Wenn du sie beherrschst, kannst du deinen ganzen Körper überall trainieren.` },
    { type: 'table', headers: ['Muster', 'Beispiel', 'Hauptmuskeln'], rows: [
      ['Kniebeuge (Beugung)', 'Kniebeuge, Beinpresse', 'Quadrizeps, Gesäß'],
      ['Hüftbeugung (Hinge)', 'Rumänisches Kreuzheben', 'Beinbeuger, Gesäß, Rücken'],
      ['Drücken', 'Bankdrücken, Liegestütze', 'Brust, Schultern, Trizeps'],
      ['Ziehen', 'Rudern, Latzug', 'Rücken, Bizeps'],
      ['Ausfallschritt', 'Ausfallschritt, Split-Kniebeuge', 'Beine, Gleichgewicht'],
      ['Rumpfstabilisation', 'Plank, Side-Plank', 'Bauch, unterer Rücken'],
    ] },

    { type: 'h1', text: 'Aufwärmen' },
    { type: 'p', text: `Überspringe niemals das Aufwärmen: es bereitet den Körper vor und verbessert deine Leistung. Mach es vor jeder Einheit.` },
    { type: 'table', headers: ['Schritt', 'Detail', 'Dauer'], rows: [
      ['Leichtes Cardio', 'Rad / Springseil / zügiges Gehen', '3 Min.'],
      ['Mobilität', 'Schultern, Hüften, Sprunggelenke', '2 Min.'],
      ['Aktivierung', 'Rumpfstabilisation + Kniebeugen mit Körpergewicht', '2 Min.'],
      ['Aufwärmsätze', '1-2 leichte Sätze der 1. Übung', '1 Min.'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Gute Ernährung beschleunigt deine Fortschritte als Anfänger.' },
    { type: 'h1', text: 'Ernährung' },
    { type: 'p', text: `Gute Nachricht: Als Anfänger kannst du gleichzeitig Muskeln aufbauen UND etwas Fett verlieren („Rekomposition"). Iss auf Erhaltungsniveau oder mit leichtem Überschuss, mit ausreichend Eiweiß.` },
    { type: 'meta', items: [
      { label: 'Kalorien', value: 'Erhaltung bis leichter Überschuss' },
      { label: 'Eiweiß', value: '1,6 bis 2 g pro kg Körpergewicht' },
      { label: 'Trinken', value: '2 bis 3 L pro Tag' },
      { label: 'Schlaf', value: '7 bis 9 h' },
    ] },
    { type: 'h2', text: 'Die einfachen Regeln' },
    { type: 'list', items: [
      `Eine Eiweißquelle bei jeder Mahlzeit (Eier, Hähnchen, Fisch, Skyr, Hülsenfrüchte).`,
      `Kohlenhydrate rund um das Training (Reis, Nudeln, Haferflocken, Obst) für Energie.`,
      `Gemüse zu jeder Hauptmahlzeit.`,
      `Trink regelmäßig Wasser, besonders während des Trainings.`,
    ] },
    { type: 'h2', text: 'Deine Makros verstehen' },
    { type: 'table', headers: ['Makro', 'Rolle', 'Pro g', 'Priorität'], rows: [
      ['Eiweiß', 'Baut Muskeln auf', '4 kcal', 'HOCH - 1,6-2 g/kg'],
      ['Kohlenhydrate', 'Energie fürs Training', '4 kcal', 'Rund um die Einheiten'],
      ['Fette', 'Hormone, Gesundheit', '9 kcal', 'Moderat, auf Qualität achten'],
    ] },
    { type: 'note', text: `Du musst nicht alles abwiegen. Stell jeden Teller einfach so zusammen: 1 Eiweißquelle + 1 Kohlenhydratquelle + Gemüse + etwas gutes Fett.` },

    { type: 'h1', text: 'Einfache Rezepte' },
    { type: 'h2', text: 'Eiweiß-Bowl nach dem Training' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 500 kcal' }, { label: 'Eiweiß', value: '40 g' }] },
    { type: 'list', items: [`130 g Hähnchen`, `100 g Reis (roh)`, `Gemüse`, `Sojasoße, Gewürze`] },
    { type: 'p', text: `Zubereitung: Reis kochen, Hähnchen und Gemüse anbraten, alles zusammenstellen. Ideal nach dem Training.` },
    { type: 'h2', text: 'Eiweiß-Frühstück' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 420 kcal' }, { label: 'Eiweiß', value: '35 g' }] },
    { type: 'list', items: [`200 g Skyr`, `50 g Haferflocken`, `1 Banane`, `1 TL Honig`] },
    { type: 'p', text: `Zubereitung: Skyr und Haferflocken mischen, Banane und Honig hinzufügen. Schnell und sättigend.` },
    { type: 'h2', text: 'Komplettes Omelett' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 400 kcal' }, { label: 'Eiweiß', value: '30 g' }] },
    { type: 'list', items: [`3 Eier`, `50 g Käse`, `Spinat, Tomate`, `1 Scheibe Vollkornbrot`] },
    { type: 'p', text: `Zubereitung: Eier verquirlen, Gemüse und Käse hinzufügen, bei niedriger Hitze braten. Mit Brot servieren. Als schnelles Frühstück oder Abendessen.` },
    { type: 'h2', text: 'Nudeln mit Thunfisch und Tomate' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 520 kcal' }, { label: 'Eiweiß', value: '35 g' }] },
    { type: 'list', items: [`100 g Vollkornnudeln (roh)`, `1 Dose Thunfisch`, `Tomatensoße, Knoblauch`, `Ein Schuss Olivenöl`] },
    { type: 'p', text: `Zubereitung: Nudeln kochen, Thunfisch mit Knoblauch-Tomatensoße mischen. Schnell, günstig, eiweißreich.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Muskeln wachsen in der Ruhephase.' },
    { type: 'h1', text: 'Erholung' },
    { type: 'list', items: [
      `Schlafe 7 bis 9 h: die Muskelerholung findet vor allem nachts statt.`,
      `Lass mindestens 1 Ruhetag zwischen den Ganzkörper-Einheiten.`,
      `Muskelkater in den ersten Wochen ist normal: er wird nachlassen.`,
      `Dehne dich 5-10 Min. nach jeder Einheit.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: '3 Einheiten pro Woche, ganzer Körper.' },
    { type: 'h1', text: '8-Wochen-Kalender' },
    { type: 'p', text: `Wechsle innerhalb der Woche zwischen 3 Ganzkörper-Einheiten (A, B, C) ab. Steigere Gewicht oder Wiederholungen, sobald es leicht fällt.` },
    { type: 'table', headers: ['Wochen', 'Fokus', 'Wiederholungen', 'Hinweis'], rows: [
      ['W1-W2', 'Technik lernen', '3 × 10-12', 'Leichte Gewichte, saubere Bewegung'],
      ['W3-W4', 'Aufbau', '3 × 10', '+ progressive Steigerung'],
      ['W5-W6', 'Kräftigung', '4 × 8-10', 'Du beherrschst die Technik, jetzt steigern'],
      ['W7-W8', 'Festigung', '4 × 8', 'Schlage deine Leistung von W1, Bilanz ziehen'],
    ] },
    { type: 'h2', text: 'Typische Woche' },
    { type: 'table', headers: ['Tag', 'Einheit', 'Dauer'], rows: [
      ['Montag', 'Ganzkörper A', '45 Min.'],
      ['Dienstag', 'Ruhe / Gehen', '-'],
      ['Mittwoch', 'Ganzkörper B', '45 Min.'],
      ['Donnerstag', 'Ruhe / Gehen', '-'],
      ['Freitag', 'Ganzkörper C', '45 Min.'],
      ['Wochenende', 'Ruhe + Tracking', '-'],
    ] },

    { type: 'h1', text: 'Deine Einheiten im Detail' },
    { type: 'h2', text: 'Ganzkörper A' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Kniebeuge (oder Beinpresse)', '3', '10', '90 s'],
      ['Bankdrücken (oder Liegestütze)', '3', '10', '90 s'],
      ['Rudern / Latzug', '3', '12', '75 s'],
      ['Plank', '3', '30 s', '45 s'],
    ] },
    { type: 'h2', text: 'Ganzkörper B' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Rumänisches Kreuzheben', '3', '10', '90 s'],
      ['Schulterdrücken', '3', '10', '90 s'],
      ['Latzug', '3', '12', '75 s'],
      ['Ausfallschritte', '3', '10 / Bein', '60 s'],
    ] },
    { type: 'h2', text: 'Ganzkörper C' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Ausfallschritte (oder Split-Kniebeuge)', '3', '10 / Bein', '75 s'],
      ['Liegestütze (oder Drücken)', '3', 'Max. sauber', '75 s'],
      ['Kurzhantel-Rudern', '3', '12', '75 s'],
      ['Bizeps-Curls + Trizeps-Extensionen', '3', '12', '60 s'],
      ['Side-Plank', '3', '20 s / Seite', '45 s'],
    ] },

    { type: 'h1', text: 'Übungsbibliothek' },
    { type: 'p', text: `Beherrsche diese Grundbewegungen. Scanne den QR-Code für das Demovideo.` },
    { type: 'exercise', name: 'Kniebeuge', muscles: 'Quadrizeps, Gesäß, Beinbeuger', level: 'Anfänger', video: `${D}/musculation`, technique: `Füße schulterbreit, senke dich ab, indem du das Gesäß nach hinten schiebst, Rücken fest, bis die Oberschenkel parallel zum Boden sind, dann drücke dich über die Fersen wieder hoch. Starte mit dem eigenen Körpergewicht, bevor du eine Langhantel hinzufügst.`, mistakes: `Knie, die nach innen kippen, Fersen, die abheben, runder Rücken. Blick nach vorn, Brust offen halten.` },
    { type: 'exercise', name: 'Rumänisches Kreuzheben', muscles: 'Beinbeuger, Gesäß, Rücken', level: 'Anfänger', video: `${D}/musculation`, technique: `Gewicht vor den Oberschenkeln, Rücken gerade. Schiebe die Hüfte nach hinten, während du das Gewicht an den Beinen entlang absenkst, Knie leicht gebeugt, dann komm hoch, indem du das Gesäß anspannst.`, mistakes: `Runder Rücken, Gewicht entfernt sich vom Körper, Knie wie bei einer Kniebeuge beugen.` },
    { type: 'exercise', name: 'Liegestütze', muscles: 'Brust, Trizeps, Schultern', level: 'Anfänger', video: `${D}/musculation`, technique: `Körper in gerader Linie fest angespannt, Hände etwas breiter als schulterbreit. Senke die Brust Richtung Boden, Ellbogen bei ~45°, dann drücke dich hoch. Bei Bedarf auf den Knien oder schräg (erhöht) ausführen.`, mistakes: `Becken sackt durch, Ellbogen zu weit abgespreizt, zu kurzer Bewegungsumfang.` },
    { type: 'exercise', name: 'Bankdrücken', muscles: 'Brust, Trizeps, Schultern', level: 'Anfänger - Mittel', video: `${D}/musculation`, technique: `Schulterblätter zusammengezogen, senke die Stange zum unteren Brustbereich, Ellbogen bei ~45°, dann drücke hoch. Füße fest am Boden. Starte leicht, bitte bei schweren Gewichten um Hilfestellung.`, mistakes: `Ellbogen zu weit abgespreizt, Abprallen auf der Brust, Gesäß hebt von der Bank ab.` },
    { type: 'exercise', name: 'Kurzhantel-Rudern', muscles: 'Rücken, Bizeps', level: 'Anfänger', video: `${D}/musculation`, technique: `Ein Knie und eine Hand auf einer Bank abgestützt, Rücken gerade. Ziehe die Kurzhantel zur Hüfte, indem du das Schulterblatt zusammenziehst, dann senke sie langsam wieder ab. Die Bewegung kommt aus dem Rücken.`, mistakes: `Runder Rücken, Rotation des Oberkörpers, nur mit dem Arm ziehen.` },
    { type: 'exercise', name: 'Schulterdrücken', muscles: 'Schultern, Trizeps', level: 'Anfänger - Mittel', video: `${D}/musculation`, technique: `Im Stehen, Rumpf fest angespannt, drücke das Gewicht über den Kopf, ohne den unteren Rücken durchzudrücken, dann senke es kontrolliert bis zu den Schultern ab.`, mistakes: `Hohlkreuz, nach vorn drücken, unvollständiger Bewegungsumfang.` },
    { type: 'exercise', name: 'Latzug', muscles: 'Rücken, Bizeps', level: 'Anfänger', video: `${D}/musculation`, technique: `Im Sitzen, weiter Griff. Ziehe die Stange zum oberen Brustbereich, indem du die Schultern nach unten ziehst und den Rücken anspannst, dann lass sie kontrolliert wieder hoch.`, mistakes: `Schwung holen, hinter den Nacken ziehen, oben die Spannung verlieren.` },
    { type: 'exercise', name: 'Ausfallschritte', muscles: 'Quadrizeps, Gesäß, Gleichgewicht', level: 'Anfänger', video: `${D}/musculation`, technique: `Großer Schritt nach vorn, hinteres Knie Richtung Boden, Oberkörper aufrecht. Das vordere Knie bleibt über dem Sprunggelenk. Drücke dich über die vordere Ferse zurück.`, mistakes: `Zu kurzer Schritt, nach vorn gebeugter Oberkörper, Gleichgewichtsverlust.` },
    { type: 'exercise', name: 'Bizeps-Curl', muscles: 'Bizeps', level: 'Anfänger', video: `${D}/musculation`, technique: `Ellbogen eng am Körper, hebe die Kurzhanteln unter Anspannung, senke sie langsam wieder ab. Kein Schwung aus dem Oberkörper.`, mistakes: `Schwung holen, Ellbogen wandern nach vorn, zu schnelles Absenken.` },
    { type: 'exercise', name: 'Plank', muscles: 'Bauchmuskulatur', level: 'Anfänger', video: `${D}/musculation`, technique: `Auf Unterarmen und Fußspitzen abgestützt, Körper in einer Linie, Bauch und Gesäß angespannt. Ruhig atmen und die Position halten.`, mistakes: `Becken sackt durch, Gesäß zu hoch, Kopf im Nacken.` },
    { type: 'exercise', name: 'Bankdips', muscles: 'Trizeps, Schultern, Brust', level: 'Anfänger - Mittel', video: `${D}/musculation`, technique: `Hände auf der Kante einer Bank, Beine nach vorn ausgestreckt. Senke das Becken ab, indem du die Ellbogen nach hinten beugst, dann drücke dich wieder hoch. Je gestreckter die Beine, desto schwerer.`, mistakes: `Schultern ziehen sich zu den Ohren hoch, zu kurzes Absenken, instabile Bank.` },
    { type: 'exercise', name: 'Side-Plank', muscles: 'Schräge Bauchmuskeln, Rumpf', level: 'Anfänger', video: `${D}/musculation`, technique: `Auf der Seite liegend, auf einem Unterarm abgestützt, Körper in einer Linie. Hebe die Hüfte an und halte die Position, ohne dass das Becken absinkt. Danach die Seite wechseln.`, mistakes: `Hüfte sinkt ab, Schulter nicht über dem Ellbogen ausgerichtet, Körper kippt.` },
    { type: 'exercise', name: 'Hip Thrust (Hüftheben mit Gewicht)', muscles: 'Gesäß, Beinbeuger', level: 'Anfänger', video: `${D}/musculation`, technique: `Oberer Rücken auf einer Bank abgestützt, Gewicht auf der Hüfte. Drücke dich über die Fersen hoch, bis Schultern, Hüfte und Knie eine Linie bilden, spanne das Gesäß oben 1 s lang an, dann senke die Hüfte wieder ab.`, mistakes: `Unteren Rücken durchdrücken, zu hoch hochkommen, Füße falsch positioniert.` },
    { type: 'exercise', name: 'Seitheben', muscles: 'Schultern (Deltamuskel)', level: 'Anfänger', video: `${D}/musculation`, technique: `Im Stehen, leichte Kurzhanteln seitlich am Körper. Hebe die Arme seitlich bis zur Waagrechten, Ellbogen leicht gebeugt, dann senke sie langsam wieder ab. Hier gilt: leicht ist besser.`, mistakes: `Zu schwer wählen, über Schulterhöhe heben, mit dem Körper schwingen.` },
    { type: 'exercise', name: 'Wadenheben im Stehen', muscles: 'Waden', level: 'Anfänger', video: `${D}/musculation`, technique: `Im Stehen so hoch wie möglich auf die Zehenspitzen kommen, kurz halten, dann langsam wieder absenken und dabei dehnen. Auf einer Stufe für mehr Bewegungsumfang.`, mistakes: `Zu kurzer Bewegungsumfang, Abprallen, zu schnelles Absenken.` },

    { type: 'h1', text: 'Einen perfekten Satz ausführen' },
    { type: 'p', text: `Die Ausführungsqualität ist es, was einen Anfänger, der Fortschritte macht, von einem unterscheidet, der sich verletzt. Hier sind die 5 Prinzipien für jeden Satz.` },
    { type: 'list', items: [
      `Voller Bewegungsumfang: senke und hebe über die gesamte Bewegungsstrecke.`,
      `Kontrolliertes Tempo: 2 s beim Absenken, 1 s beim Hochdrücken. Niemals ruckartig oder mit Schwung.`,
      `Atmung: ausatmen bei der Anstrengung (hoch), einatmen beim Absenken.`,
      `Rumpfspannung: Bauch bei jeder Wiederholung angespannt, um den unteren Rücken zu schützen.`,
      `Muskel-Gehirn-Verbindung: konzentriere dich auf den arbeitenden Muskel, nicht auf das Gewicht.`,
    ] },
    { type: 'note', text: `Wenn du nicht alle Wiederholungen mit sauberer Technik schaffst, ist das Gewicht zu schwer. Reduziere es: der Muskel reagiert auf Qualität, nicht auf Ego.` },

    { type: 'h1', text: 'Cardio für Anfänger' },
    { type: 'p', text: `Cardio ist für Fortschritte im Krafttraining nicht zwingend nötig, verbessert aber deine Gesundheit, deine Erholung und hilft dir, definiert zu bleiben. Halte es moderat, damit es deine Krafteinheiten nicht beeinträchtigt.` },
    { type: 'list', items: [
      `2 bis 3 zügige Spaziergänge von 30 Min. pro Woche an den Ruhetagen.`,
      `Optional: 10-15 Min. Rad oder Rudergerät am Ende der Einheit.`,
      `Ziele auf 8.000 Schritte/Tag im Alltag: Treppen, Wege zu Fuß usw.`,
      `Vermeide lange, intensive Cardio-Einheiten, die deine Beine vor dem Krafttraining ermüden.`,
    ] },

    { type: 'h1', text: 'Variante zu Hause ohne Ausrüstung' },
    { type: 'p', text: `Kein Studio, keine Hanteln? Dieser Ganzkörper-Zirkel mit dem eigenen Körpergewicht ersetzt eine Einheit. Mach 3 bis 4 Runden, 45 s Belastung / 15 s Übergang, 1 Min. Pause zwischen den Runden.` },
    { type: 'table', headers: ['Übung', 'Ziel', 'Wiederholungen / Zeit'], rows: [
      ['Kniebeugen mit Körpergewicht', 'Beine', '15 bis 20'],
      ['Liegestütze (bei Bedarf auf den Knien)', 'Oberkörper', 'Max. sauber'],
      ['Wechselnde Ausfallschritte', 'Beine', '10 / Bein'],
      ['Rudern mit beschwertem Rucksack', 'Rücken', '12'],
      ['Stuhl-Dips', 'Trizeps', '10'],
      ['Plank', 'Bauch', '30 bis 45 s'],
    ] },

    { type: 'h1', text: 'Bauchmuskeln stärken' },
    { type: 'p', text: `Füge am Ende der Einheit 5 Minuten Bauchtraining hinzu, 2 bis 3 Mal pro Woche. Ein starker Rumpf schützt deinen Rücken und verbessert alle anderen Übungen.` },
    { type: 'exercise', name: 'Crunch', muscles: 'Gerader Bauchmuskel', level: 'Anfänger', video: `${D}/musculation`, technique: `Auf dem Rücken liegend, Knie gebeugt, Hände auf der Brust oder an den Schläfen. Hebe die Schultern vom Boden ab, indem du den Oberkörper einrollst, atme aus, dann senke ihn langsam wieder ab. Der untere Rücken bleibt am Boden.`, mistakes: `Am Nacken ziehen, den ganzen Rücken abheben, die Luft anhalten.` },
    { type: 'exercise', name: 'Beinheben', muscles: 'Unterer Bauch, Rumpf', level: 'Anfänger - Mittel', video: `${D}/musculation`, technique: `Auf dem Rücken liegend, Hände unter dem Gesäß. Hebe die gestreckten Beine (oder mit gebeugten Knien) bis zur Senkrechten, dann senke sie langsam ab, ohne den Boden zu berühren. Unterer Rücken bleibt am Boden.`, mistakes: `Unteren Rücken durchdrücken, zu schnell absenken, Schwung aus den Beinen.` },
    { type: 'list', items: [
      `Express-Bauch-Zirkel: 15 Crunches + 12 Beinheben + 40 s Plank, 3 Runden.`,
      `Qualität vor Quantität: langsame, kontrollierte Bewegungen.`,
      `Ein sichtbarer Sixpack kommt vor allem durch eine kontrollierte Ernährung, nicht nur durch Übungen.`,
    ] },

    { type: 'h1', text: 'Die 8 Wochen im Detail' },
    { type: 'p', text: `Hier ist die Entwicklung Woche für Woche. Behalte die 3 Ganzkörper-Einheiten bei, passe Gewichte und Wiederholungen an.` },
    { type: 'table', headers: ['Woche', 'Sätze × Wdh.', 'Wochenziel'], rows: [
      ['Woche 1', '3 × 12', 'Bewegungen erlernen, sehr leichte Gewichte'],
      ['Woche 2', '3 × 12', 'Technik festigen, leichte Steigerung'],
      ['Woche 3', '3 × 10', 'Gewicht steigern, 90 s Pause'],
      ['Woche 4', '3 × 10', 'Zwischenbilanz, Foto & Maße'],
      ['Woche 5', '4 × 10', 'Einen Satz hinzufügen, mehr Volumen'],
      ['Woche 6', '4 × 8', 'Schwerere Gewichte'],
      ['Woche 7', '4 × 8', 'Sauberer Intensitätshöhepunkt'],
      ['Woche 8', '4 × 8 + Bilanz', 'Leistung von Woche 1 schlagen, finale Maße'],
    ] },

    { type: 'h1', text: 'Empfohlene Progression' },
    { type: 'p', text: `Anfänger machen schnell Fortschritte: nutze das mit einer einfachen progressiven Steigerung.` },
    { type: 'list', items: [
      `Wenn du alle Sätze am oberen Ende der Wiederholungsspanne schaffst, füge Gewicht hinzu (die kleinstmögliche Steigerung).`,
      `Andernfalls füge jede Woche 1 Wiederholung pro Satz hinzu.`,
      `Notiere jede Einheit: Gewicht × Wiederholungen. Schlage diese Zahl beim nächsten Mal.`,
      `Keine Panik, wenn eine Woche stagniert: Schlaf und Ernährung zählen genauso viel wie das Training.`,
    ] },

    { type: 'h1', text: 'Anfängerfehler, die du vermeiden solltest' },
    { type: 'list', items: [
      `Zu schnell steigern: die Technik verschlechtert sich und das Verletzungsrisiko steigt stark.`,
      `Ständig das Programm wechseln: gib dem Programm 8 Wochen Zeit, um zu wirken.`,
      `Beine und Rücken zugunsten von Armen/Brust vernachlässigen.`,
      `Das Aufwärmen oder die Ruhetage auslassen.`,
      `Sich mit anderen vergleichen: vergleiche dich stattdessen mit dir selbst von letzter Woche.`,
    ] },
    { type: 'h2', text: 'Problem → Lösung' },
    { type: 'table', headers: ['Du erlebst…', 'Die Lösung'], rows: [
      ['Du weißt nicht, welches Gewicht du nehmen sollst', 'Wähle ein Gewicht, bei dem die letzte Wdh. hart, aber sauber ist'],
      ['Du hast Gelenkschmerzen', 'Reduziere das Gewicht, überprüfe die Technik (Video scannen)'],
      ['Du machst keine Fortschritte mehr', 'Überprüfe Schlaf und Eiweiß, füge mehr Ruhe hinzu'],
      ['Starker Muskelkater', 'Am Anfang normal; trink genug, dehne dich, es geht vorbei'],
    ] },

    { type: 'h1', text: 'Motiviert bleiben' },
    { type: 'list', items: [
      `Setze dir ein einfaches Kraftziel (z. B. „10 saubere Liegestütze", „Kniebeuge ohne Gewicht beherrschen, dann steigern").`,
      `Mach alle 4 Wochen ein Foto und nimm deine Maße.`,
      `Blocke deine 3 Termine in deinem Kalender wie feste Verabredungen.`,
      `Feiere jeden kleinen Erfolg: ein regelmäßiger Anfänger schlägt einen unregelmäßigen Fortgeschrittenen.`,
    ] },
    { type: 'h2', text: 'Baue die Gewohnheit auf' },
    { type: 'list', items: [
      `Packe deine Tasche schon am Vorabend: null Reibung am Trainingstag.`,
      `2-Minuten-Regel: starte einfach mit dem Aufwärmen, der Rest folgt von allein.`,
      `Lass niemals 2 Einheiten hintereinander ausfallen.`,
    ] },

    { type: 'h1', text: 'Häufige Fragen' },
    { type: 'h2', text: 'Werde ich „zu muskulös"?' },
    { type: 'p', text: `Nein. Muskelaufbau ist langsam und erfordert jahrelange Anstrengung. Krafttraining macht dich straffer, stärker und gesünder - nicht aus Versehen „riesig".` },
    { type: 'h2', text: 'Cardio oder Krafttraining zum Fettabbau?' },
    { type: 'p', text: `Beides, aber Krafttraining ist essenziell: es erhält bzw. baut Muskeln auf, die deinen Grundumsatz erhöhen. Kombiniere Krafttraining + etwas Gehen/Cardio + kontrollierte Ernährung.` },
    { type: 'h2', text: 'Kann ich es zu Hause machen?' },
    { type: 'p', text: `Ja, mit einem Paar Kurzhanteln. Andernfalls nutze die Varianten mit Körpergewicht (Liegestütze, Ausfallschritte, Kniebeugen, Plank, Rudern mit beschwertem Rucksack).` },
    { type: 'h2', text: 'Wie lange dauert es, bis ich Ergebnisse sehe?' },
    { type: 'p', text: `Kraft: schon nach 2-3 Wochen. Optisch: 6 bis 8 Wochen bei passender Ernährung. Die ersten Monate als Anfänger sind die lohnendsten.` },
    { type: 'h2', text: 'Braucht man Nahrungsergänzungsmittel?' },
    { type: 'p', text: `Nein, nicht zum Einstieg. Wenn du möchtest: Whey (um dein Eiweißziel zu erreichen) und Kreatin (3-5 g/Tag). Der Rest ist zweitrangig.` },
    { type: 'h2', text: 'Wie viele Ruhetage?' },
    { type: 'p', text: `Mindestens 1 Tag zwischen jeder Ganzkörper-Einheit, also das Format mit 3 Einheiten/Woche (z. B. Montag/Mittwoch/Freitag). Ruhe ist keine verlorene Zeit: genau dann baut sich der Muskel wieder auf.` },
    { type: 'h2', text: 'Was tun, wenn eine Übung schmerzt?' },
    { type: 'p', text: `Unterscheide zwischen Muskelgefühl (normal) und Gelenk- oder akutem Schmerz (nicht normal). Bei Schmerzen: Übung abbrechen, Gewicht reduzieren, Technik überprüfen (Video scannen) oder durch eine Variante ersetzen. Bei anhaltenden Beschwerden einen Arzt aufsuchen.` },

    { type: 'h1', text: 'Und nach deinen 8 Wochen?' },
    { type: 'p', text: `Du hast die Grundlagen gelernt und an Kraft gewonnen: jetzt geht es darum, weiter Fortschritte zu machen. Hier sind deine Optionen.` },
    { type: 'list', items: [
      `Steige auf das Programm Krafttraining Fortgeschritten (Mittelstufe) um, für mehr Volumen und einen fortgeschritteneren Trainingssplit.`,
      `Wenn dein Ziel Muskelaufbau ist: mach weiter mit Masseaufbau (leichter Überschuss).`,
      `Wenn dein Ziel Definition ist: mach weiter mit Gewichtsverlust (leichtes Defizit) - die aufgebaute Kraft hilft dir, deine Muskeln zu erhalten.`,
      `In jedem Fall: hör nicht auf. Regelmäßigkeit über Monate hinweg macht den ganzen Unterschied.`,
    ] },
    { type: 'note', text: `Nimm nach diesen 8 Wochen erneut deine Maße und ein Foto auf und vergleiche sie mit deinem Ausgangspunkt. Das ist deine wahre Belohnung - und deine beste Motivation, weiterzumachen.` },

    { type: 'h1', text: 'Dehnen & Mobilität' },
    { type: 'p', text: `5-10 Min. nach jeder Einheit. Halte jede Position 20-30 s, ohne zu wippen.` },
    { type: 'table', headers: ['Dehnung', 'Bereich', 'Dauer'], rows: [
      ['Quadrizeps stehend', 'Oberschenkelvorderseite', '30 s / Seite'],
      ['Beinbeuger gestrecktes Bein', 'Oberschenkelrückseite', '30 s / Seite'],
      ['Brust an der Wand', 'Brust, Schultern', '30 s / Seite'],
      ['Hängen an der Stange', 'Rücken, Schultern', '30 s'],
      ['Katze-Kuh', 'Wirbelsäule', '45 s'],
    ] },

    { type: 'h1', text: 'Sicherheit & Verletzungsprävention' },
    { type: 'p', text: `Krafttraining ist sehr sicher, wenn es richtig ausgeführt wird. Fast alle Anfängerverletzungen entstehen aus drei vermeidbaren Ursachen: Ego, Technik und fehlendes Aufwärmen.` },
    { type: 'list', items: [
      `Wärme dich immer auf, besonders vor schweren Bewegungen.`,
      `Steigere Gewichte schrittweise (in kleinen Schritten), niemals sprunghaft.`,
      `Halte den Rücken bei Kniebeuge, Kreuzheben und Schulterdrücken fest und neutral.`,
      `Brich einen Satz ab, wenn die Technik nachlässt: lieber 8 saubere Wiederholungen als 12 schlampige.`,
      `Scharfer Gelenkschmerz = Stopp. „Durchbeißen" bei echtem Schmerz gilt niemals.`,
      `Trink genug und schlafe ausreichend: ein müder Körper verletzt sich leichter.`,
    ] },
    { type: 'note', text: `Bei Unsicherheit über eine Bewegung, scanne ihren QR-Code, um die Technik im Video anzusehen, bevor du Gewicht auflegst.` },

    { type: 'h1', text: 'Tracking deines Fortschritts' },
    { type: 'p', text: `Notiere deine Gewichte bei jeder Einheit und deine Maße jede Woche. Was gemessen wird, kann gesteuert werden.` },
    { type: 'h2', text: 'Gewicht & Maße' },
    { type: 'tracker', columns: ['Datum', 'Gewicht (kg)', 'Arm (cm)', 'Oberschenkel (cm)', 'Taillenumfang (cm)'], rows: 7 },
    { type: 'h2', text: 'Gewichte (kg) auf den Grundübungen' },
    { type: 'tracker', columns: ['Übung', 'W1', 'W3', 'W5', 'W8'], rows: 6 },

    { type: 'h1', text: 'Wöchentliche Checkliste' },
    { type: 'p', text: `Hake jedes Kästchen am Ende der Woche ab. Ziel: mindestens 5 von 7.` },
    { type: 'checklist', items: [
      `Ich habe meine 3 Einheiten diese Woche gemacht.`,
      `Ich habe bei allen Übungen eine saubere Technik beibehalten.`,
      `Ich habe mein Eiweißziel erreicht.`,
      `Ich habe ein Gewicht oder eine Wiederholung gesteigert.`,
      `Ich habe die meisten Nächte 7 bis 9 h geschlafen.`,
      `Ich habe mich vor jeder Einheit aufgewärmt.`,
      `Ich habe meine Gewichte und mein Befinden notiert.`,
    ] },

    { type: 'h1', text: 'Persönliche Notizen' },
    { type: 'tracker', columns: ['Meine Notizen, Gewichte und Empfindungen der Woche'], rows: 16 },

    { type: 'h1', text: 'Glossar' },
    { type: 'list', items: [
      `Ganzkörper: Einheit, die den gesamten Körper trainiert.`,
      `RPE: gefühlte Intensität /10 (RPE 8 = 2 Wdh. in Reserve).`,
      `Progressive Steigerung: Gewicht/Wiederholungen im Laufe der Wochen erhöhen.`,
      `Tempo: Ausführungsgeschwindigkeit (z. B. 2 s Absenken, 1 s Hochdrücken).`,
      `Hüftbeugung (Hinge): Kippbewegung der Hüfte (Kreuzheben).`,
      `Rekomposition: gleichzeitig Muskeln aufbauen und Fett verlieren (bei Anfängern möglich).`,
    ] },

    { type: 'note', text: `8 Wochen geschafft? Du hast ein solides Fundament gelegt. Mach weiter mit dem Programm Krafttraining Fortgeschritten oder Masseaufbau, um weiter Fortschritte zu machen. Erstelle dein Konto auf xenotif.com.` },
  ],
}
