import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Muskelaufbau-Programm für Fortgeschrittene - 12 Wochen (DE-Mirror von musculation-intermediaire.ts).
// Gleiche Struktur; nur die Texte sind übersetzt. ≈ 30 Seiten.
export const musculationIntermediaireDe: Guide = {
  id: 'musculation-intermediaire',
  title: 'Muskelaufbau-Programm für Fortgeschrittene',
  subtitle: 'In 12 Wochen den nächsten Schritt gehen: mehr Volumen, mehr Muskeln, mehr Kraft',
  author: 'XENOTIF Coach - Zertifizierter Kraft- & Konditionstrainer',
  level: 'Fortgeschritten',
  duration: '12 Wochen · 4-5 Einheiten/Woche',
  coverImage: 'musculation-intermediaire-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Erreiche das nächste Level' },
    { type: 'p', text: `Du beherrschst die Grundlagen und willst schneller vorankommen? Dieses 12-wöchige Programm für Fortgeschrittene erhöht das Trainingsvolumen, führt einen strukturierten Split ein (Push/Pull/Legs oder Oberkörper/Unterkörper) und arbeitet mit Intensivierungstechniken. Das Ziel: mehr Muskeln, mehr Kraft, eine dichtere Silhouette - ohne zu stagnieren.` },
    { type: 'p', text: `Jede Übung hat einen QR-Code zu ihrem Demovideo auf XENOTIF®. Notiere deine Gewichte: Auf deinem Niveau macht die präzise progressive Überlastung den Unterschied.` },
    { type: 'meta', items: [
      { label: 'Ziel', value: 'Hypertrophie & Kraft' },
      { label: 'Niveau', value: 'Fortgeschritten (6+ Monate Erfahrung)' },
      { label: 'Dauer', value: '12 Wochen (3 Blöcke)' },
      { label: 'Häufigkeit', value: '4-5 Einheiten/Woche' },
      { label: 'Ausrüstung', value: 'Vollständiges Fitnessstudio empfohlen' },
      { label: 'Split', value: 'Push / Pull / Legs' },
    ] },
    { type: 'h2', text: 'Ziele des Programms' },
    { type: 'list', items: [
      `In 12 Wochen 2 bis 4 kg Muskelmasse aufbauen.`,
      `Deine Kraft bei den Schlüsselübungen steigern (Kniebeuge, Bankdrücken, Kreuzheben, Klimmzüge).`,
      `Die Muskel-Gehirn-Verbindung und die Ausführungsqualität verbessern.`,
      `Lernen, dein Training zu periodisieren, um langfristig Fortschritte zu machen.`,
    ] },
    { type: 'h2', text: 'Bist du bereit für dieses Niveau?' },
    { type: 'list', items: [
      `Du trainierst seit mindestens 6 Monaten regelmäßig.`,
      `Du beherrschst die Technik der Grundübungen.`,
      `Du kannst 4 bis 5 Mal pro Woche trainieren.`,
      `Falls nicht, starte mit dem Muskelaufbau-Programm für Anfänger.`,
    ] },
    { type: 'note', text: `Die goldene Regel für Fortgeschrittene: Fortschritt passiert nicht mehr von selbst. Du musst ihn erzwingen - progressive Überlastung, ausreichend Volumen, Erholung und Ernährung müssen stimmen.` },

    { type: 'h1', text: 'So funktioniert\'s' },
    { type: 'list', items: [
      `Push/Pull/Legs-Split: Drücken, Ziehen, Beine - 1,5- bis 2-mal pro Woche wiederholt.`,
      `Volumen: 12 bis 20 Sätze pro Muskelgruppe und Woche.`,
      `Sätze × Wiederholungen: „4 × 8" = 4 Sätze à 8 Wiederholungen.`,
      `Tempo: 2-3 s exzentrisch (Absenken), kontrolliert-explosiv konzentrisch (Hochdrücken).`,
      `Pause: 2-3 Min. bei den großen Grundübungen, 60-90 s bei Isolationsübungen.`,
      `RPE 8-9: 1 bis 2 Wiederholungen in Reserve, der letzte Satz nah am Muskelversagen.`,
    ] },
    { type: 'h2', text: 'Intensivierungstechniken' },
    { type: 'p', text: `Um auf deinem Niveau weiter Fortschritte zu machen, setze diese Techniken sparsam ein (1 bis 2 pro Einheit, bei Isolationsübungen).` },
    { type: 'table', headers: ['Technik', 'Prinzip', 'Wann'], rows: [
      ['Superset', '2 Übungen ohne Pause hintereinander', 'Zeit sparen, Pump'],
      ['Dropset', 'Gewicht bei Muskelversagen reduzieren und weitermachen', 'Letzter Satz Isolationsübung'],
      ['Rest-Pause', 'Mini-Pausen von 10-15 s für mehr Wdh.', 'Zum Abschluss einer Übung'],
      ['Langsames Tempo', 'Exzentrische Phase von 3-4 s', 'Verbindung & Kontrolle'],
    ] },

    { type: 'h1', text: 'Aufwärmen' },
    { type: 'p', text: `Vollständiges Aufwärmen vor jeder Einheit, plus Aufwärmsätze bei der ersten schweren Übung.` },
    { type: 'table', headers: ['Schritt', 'Detail', 'Dauer'], rows: [
      ['Cardio', 'Fahrrad / Rudergerät', '3-5 Min.'],
      ['Gezielte Mobilität', 'Gelenke des Tages (Schultern / Hüften)', '3 Min.'],
      ['Aktivierung', 'Widerstandsband, Core', '2 Min.'],
      ['Aufwärmsätze', '40 %, 60 %, 80 % der 1. Übung', '3-4 Sätze'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Ein hohes Trainingsvolumen braucht Treibstoff auf gleichem Niveau.' },
    { type: 'h1', text: 'Ernährung' },
    { type: 'p', text: `Bei diesem Trainingsvolumen muss deine Ernährung mitziehen. Ein leichter Kalorienüberschuss zum Aufbauen, hohe Proteinzufuhr, großzügige Kohlenhydrate rund um die Einheiten.` },
    { type: 'meta', items: [
      { label: 'Kalorien', value: 'Erhaltungsbedarf +200/+400 kcal' },
      { label: 'Eiweiß', value: '1,8 bis 2,2 g pro kg' },
      { label: 'Kohlenhydrate', value: '4 bis 6 g/kg (Energie)' },
      { label: 'Flüssigkeit', value: '3 L pro Tag' },
    ] },
    { type: 'h2', text: 'Die Regeln' },
    { type: 'list', items: [
      `Eiweiß über 4-5 Mahlzeiten am Tag verteilen (~0,4 g/kg pro Mahlzeit).`,
      `Kohlenhydrate vor und nach dem Training für Leistung und Erholung.`,
      `Hochwertige Fette (0,8-1 g/kg) für den Hormonhaushalt.`,
      `Mahlzeit rund ums Training: Eiweiß + Kohlenhydrate innerhalb von 1-2 Std. um die Einheit herum.`,
    ] },
    { type: 'h2', text: 'Deine Makros verstehen' },
    { type: 'table', headers: ['Makro', 'Rolle', 'Zielwert'], rows: [
      ['Eiweiß', 'Muskelaufbau', '1,8-2,2 g/kg'],
      ['Kohlenhydrate', 'Energie & Volumen (Glykogen)', '4-6 g/kg'],
      ['Fette', 'Hormone, Gesundheit', '0,8-1 g/kg'],
    ] },
    { type: 'note', text: `Wiege dich 2-3× pro Woche und bilde den Wochendurchschnitt. Ziel: +0,25 bis +0,4 kg/Woche. Darüber hinaus: reduziere den Überschuss, um den Fettaufbau zu begrenzen.` },

    { type: 'h1', text: 'Rezepte' },
    { type: 'h2', text: 'Shake rund ums Training' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 500 kcal' }, { label: 'Eiweiß', value: '40 g' }] },
    { type: 'list', items: [`1 Portion Whey`, `60 g Haferflocken`, `1 Banane`, `300 ml Milch`] },
    { type: 'p', text: `Zubereitung: alles mixen. Perfekt direkt nach dem Training, um die Erholung anzukurbeln.` },
    { type: 'h2', text: 'Rind-Reis-Gemüse-Bowl' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 700 kcal' }, { label: 'Eiweiß', value: '50 g' }] },
    { type: 'list', items: [`160 g Rinderhack 5%`, `120 g Reis (roh)`, `Gemüse`, `Sojasoße, Gewürze`] },
    { type: 'p', text: `Zubereitung: Rind scharf anbraten, Gemüse dazugeben, auf dem Reis servieren. Die kräftige Mahlzeit des Tages.` },
    { type: 'h2', text: 'Eiweiß-Skyr' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 350 kcal' }, { label: 'Eiweiß', value: '35 g' }] },
    { type: 'list', items: [`250 g Skyr`, `1 Portion Whey`, `Beeren`, `Mandeln`] },
    { type: 'p', text: `Zubereitung: Skyr und Whey mischen, Beeren und Mandeln hinzufügen. Der ideale proteinreiche Snack.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Mehr Volumen = mehr Aufmerksamkeit für die Erholung.' },
    { type: 'h1', text: 'Erholung' },
    { type: 'list', items: [
      `Schlafe 7 bis 9 Std.: bei diesem Trainingsvolumen nicht verhandelbar.`,
      `Gib einer Muskelgruppe 48-72 Std., bevor du sie erneut trainierst.`,
      `Deload alle 4-6 Wochen (Volumen −40 %), um Übertraining zu vermeiden.`,
      `Achte auf Anzeichen von Übermüdung: schlechterer Schlaf, Kraftverlust, Reizbarkeit.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: 'Push / Pull / Legs: ein Klassiker, der funktioniert.' },
    { type: 'h1', text: 'Der 12-Wochen-Plan (3 Blöcke)' },
    { type: 'p', text: `Drei aufeinander aufbauende Blöcke: Volumen, Intensität, Kraft. Behalte denselben Split bei und passe Wiederholungen und Gewichte an.` },
    { type: 'table', headers: ['Block', 'Wochen', 'Fokus', 'Wiederholungen'], rows: [
      ['Block 1', 'W1-W4', 'Volumen & Technik', '10 bis 12'],
      ['Block 2', 'W5-W8', 'Hypertrophie', '8 bis 10'],
      ['Block 3', 'W9-W12', 'Kraft & Dichte', '5 bis 8'],
    ] },
    { type: 'h2', text: 'Typische Woche (5 Tage)' },
    { type: 'table', headers: ['Tag', 'Einheit'], rows: [
      ['Montag', 'Push (Brust, Schultern, Trizeps)'],
      ['Dienstag', 'Pull (Rücken, Bizeps)'],
      ['Mittwoch', 'Legs (Beine, Gesäß)'],
      ['Donnerstag', 'Ruhetag / leichtes Cardio'],
      ['Freitag', 'Upper (Oberkörper)'],
      ['Samstag', 'Lower (Unterkörper) + Bauch'],
      ['Sonntag', 'Ruhetag + Tracking'],
    ] },

    { type: 'h1', text: 'Deine Einheiten im Detail' },
    { type: 'h2', text: 'Push - Brust / Schultern / Trizeps' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Bankdrücken', '4', '6 bis 8', '150 s'],
      ['Schrägbankdrücken Kurzhantel', '4', '8 bis 10', '120 s'],
      ['Schulterdrücken', '3', '8 bis 10', '120 s'],
      ['Seitheben', '4', '12 bis 15', '60 s'],
      ['Dips / Trizepsstrecken', '3', '10 bis 12', '75 s'],
    ] },
    { type: 'h2', text: 'Pull - Rücken / Bizeps' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Klimmzüge (oder Latzug)', '4', '6 bis 10', '150 s'],
      ['Langhantelrudern', '4', '8 bis 10', '120 s'],
      ['Sitzendes Kabelrudern', '3', '10 bis 12', '90 s'],
      ['Face Pull', '3', '15', '60 s'],
      ['Bizepscurl + Hammercurl', '4', '10 bis 12', '60 s'],
    ] },
    { type: 'h2', text: 'Legs - Beine / Gesäß' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Kniebeuge', '4', '6 bis 8', '180 s'],
      ['Rumänisches Kreuzheben', '4', '8 bis 10', '150 s'],
      ['Beinpresse', '3', '12', '120 s'],
      ['Beincurl', '3', '12 bis 15', '75 s'],
      ['Waden', '4', '15 bis 20', '45 s'],
    ] },

    { type: 'h1', text: '4-Tage-Variante (Oberkörper / Unterkörper)' },
    { type: 'p', text: `Du kannst nur 4-mal pro Woche trainieren? Ersetze den PPL-Split durch diesen Oberkörper/Unterkörper-Split (Montag/Dienstag/Donnerstag/Freitag). Jede Körperhälfte wird 2× pro Woche trainiert - hervorragend für Trainingsfrequenz und Erholung.` },
    { type: 'h2', text: 'Oberkörper (A & B)' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Bankdrücken / Schrägbankdrücken', '4', '6 bis 10', '150 s'],
      ['Klimmzüge / Latzug', '4', '8 bis 10', '120 s'],
      ['Schulterdrücken', '3', '8 bis 10', '120 s'],
      ['Langhantelrudern / Kabelrudern', '3', '10', '90 s'],
      ['Seitheben + Bizepscurl + Trizeps', '3', '12', '60 s'],
    ] },
    { type: 'h2', text: 'Unterkörper (A & B)' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wiederholungen', 'Pause'], rows: [
      ['Kniebeuge / Beinpresse', '4', '6 bis 10', '180 s'],
      ['Rumänisches Kreuzheben', '4', '8 bis 10', '150 s'],
      ['Ausfallschritte / Beinstrecker', '3', '12', '90 s'],
      ['Beincurl', '3', '12 bis 15', '75 s'],
      ['Waden + Bauch', '4', '15', '45 s'],
    ] },

    { type: 'h1', text: 'Übungsbibliothek' },
    { type: 'p', text: `Die Schlüsselübungen des Programms. Scanne den QR-Code für das Demovideo.` },
    { type: 'exercise', name: 'Bankdrücken', muscles: 'Brust, Trizeps, Schultern', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Schulterblätter zusammengezogen, leichtes Hohlkreuz, Füße fest verankert. Senke die Hantel zur unteren Brust ab, Ellbogen ~45°, dann drücke hoch. Kontrolliere die exzentrische Phase.`, mistakes: `Ellbogen zu weit abgespreizt, Abprallen auf der Brust, Gesäß hebt ab, unvollständiger Bewegungsumfang.` },
    { type: 'exercise', name: 'Kniebeuge', muscles: 'Quadrizeps, Gesäß, Beinbeuger', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Hantel auf dem oberen Rücken, senke dich unter die Parallele ab, wenn deine Mobilität es zulässt, Rücken angespannt, Knie in Linie mit den Füßen, dann explosiv hoch.`, mistakes: `Knie kippen nach innen, Rücken rundet sich unten, Fersen heben ab.` },
    { type: 'exercise', name: 'Kreuzheben', muscles: 'Hintere Kette, Rücken, Gesäß', level: 'Experte', video: `${D}/musculation`, technique: `Hantel über der Fußmitte, flacher Rücken, Core angespannt, drücke dich mit den Beinen vom Boden ab und halte die Hantel körpernah, verriegle oben Hüfte und Knie.`, mistakes: `Runder Rücken, Hantel entfernt sich vom Körper, mit dem unteren Rücken ziehen, Überstreckung oben.` },
    { type: 'exercise', name: 'Klimmzüge', muscles: 'Latissimus, Bizeps', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Obergriff, starte mit tiefen Schultern, ziehe die Ellbogen nach unten, um das Kinn über die Stange zu bringen, dann kontrolliert ablassen.`, mistakes: `Schwingen (ungewolltes Kipping), unvollständiger Bewegungsumfang, hochgezogene Schultern.` },
    { type: 'exercise', name: 'Langhantelrudern', muscles: 'Rücken, Bizeps, hintere Schulter', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Oberkörper ~45° vorgebeugt, flacher Rücken, ziehe die Hantel zum Unterbauch, indem du die Schulterblätter zusammenziehst, lass langsam wieder ab.`, mistakes: `Runder Rücken, Oberkörper richtet sich auf, zu hoch ziehen.` },
    { type: 'exercise', name: 'Schulterdrücken', muscles: 'Schultern, Trizeps', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Stehend, Core fest angespannt, drücke die Hantel senkrecht nach oben, ohne den unteren Rücken zu überstrecken, verriegle oben.`, mistakes: `Hohlkreuz, nach vorne statt senkrecht drücken, unvollständiger Bewegungsumfang.` },
    { type: 'exercise', name: 'Rumänisches Kreuzheben', muscles: 'Beinbeuger, Gesäß, Rücken', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Schiebe die Hüften nach hinten, flacher Rücken, senke die Hantel an den Beinen entlang ab, bis du die Dehnung der Beinbeuger spürst, dann komm zurück, indem du das Gesäß anspannst.`, mistakes: `Runder Rücken, Knie beugen wie bei einer Kniebeuge, Hantel entfernt sich vom Körper.` },
    { type: 'exercise', name: 'Beinpresse', muscles: 'Quadrizeps, Gesäß', level: 'Anfänger', video: `${D}/musculation`, technique: `Füße schulterbreit auf der Plattform, senke ab bis ~90° in den Knien, ohne den unteren Rücken abzuheben, dann drücke hoch, ohne die Knie abrupt durchzustrecken.`, mistakes: `Rücken hebt ab, Knie kippen nach innen, zu kurzer Bewegungsumfang.` },
    { type: 'exercise', name: 'Seitheben', muscles: 'Seitliche Schultermuskulatur', level: 'Anfänger', video: `${D}/musculation`, technique: `Leichte Kurzhanteln, hebe die Arme seitlich bis zur Horizontalen, Ellbogen leicht gebeugt, langsames Ablassen. Leicht und sauber ausführen.`, mistakes: `Zu schweres Gewicht, Schwungholen, über Schulterhöhe heben.` },
    { type: 'exercise', name: 'Face Pull', muscles: 'Hintere Schulter, Trapezmuskel', level: 'Anfänger', video: `${D}/musculation`, technique: `Am oberen Kabelzug, ziehe das Seil zum Gesicht, während du die Hände auseinanderführst, Ellbogen hoch, Schulterblätter zusammenziehen. Hervorragend für gesunde Schultern.`, mistakes: `Zu schweres Gewicht, mit den Armen ziehen, absinkende Ellbogen.` },
    { type: 'exercise', name: 'Bizepscurl', muscles: 'Bizeps', level: 'Anfänger', video: `${D}/musculation`, technique: `Ellbogen fest am Körper, hebe unter Anspannung an, senke langsam ab (2-3 s). Kein Schwung.`, mistakes: `Schwingen, Ellbogen wandern nach vorne, zu schnelles Ablassen.` },
    { type: 'exercise', name: 'Beincurl', muscles: 'Beinbeuger', level: 'Anfänger', video: `${D}/musculation`, technique: `Liegend oder sitzend je nach Maschine, beuge die Knie, um die Ferse zum Gesäß zu führen, spanne an, dann kontrolliert zurück.`, mistakes: `Becken hebt ab, ruckartige Bewegungen, unvollständiger Bewegungsumfang.` },
    { type: 'exercise', name: 'Schrägbankdrücken Kurzhantel', muscles: 'Obere Brust, Schultern', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `Bank auf ~30°, Kurzhanteln auf Brusthöhe, drücke nach oben, während du die Hanteln leicht annäherst, kontrolliertes Absenken bis zur Dehnung.`, mistakes: `Bank zu steil (wird zur Schulterübung), zu kurzes Absenken, durchgestreckte Ellbogen oben.` },
    { type: 'exercise', name: 'Sitzendes Kabelrudern', muscles: 'Rücken (Mitte), Bizeps', level: 'Anfänger', video: `${D}/musculation`, technique: `Sitzend, gerader Rücken, ziehe den Griff zum Nabel, während du die Schulterblätter zusammenziehst, ohne den Oberkörper nach hinten zu lehnen, dann zurück unter Spannung.`, mistakes: `Mit dem Oberkörper schwingen, Rücken runden, zu hoch ziehen.` },
    { type: 'exercise', name: 'Dips', muscles: 'Untere Brust, Trizeps', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `An den Dip-Barren, Körper angespannt, senke dich ab, indem du die Ellbogen bis ~90° beugst, leichte Vorlage für die Brust, dann hochdrücken.`, mistakes: `Zu tiefes Absenken (belastet die Schultern), ruckartige Bewegungen, hochgezogene Schultern.` },
    { type: 'exercise', name: 'Hammercurl', muscles: 'Bizeps, Armbeuger, Unterarme', level: 'Anfänger', video: `${D}/musculation`, technique: `Kurzhanteln im neutralen Griff (Daumen nach oben), hebe unter Anspannung an, langsames Ablassen. Ellbogen fixiert.`, mistakes: `Schwingen, Ellbogen wandern nach vorne, Griff dreht sich.` },

    { type: 'h1', text: 'Bauch & Core' },
    { type: 'p', text: `Trainiere die Rumpfmuskulatur 2-3×/Woche am Ende der Einheit. Ein starker Core verbessert deine Leistung bei allen großen Grundübungen und schützt deinen Rücken.` },
    { type: 'exercise', name: 'Plank', muscles: 'Bauchmuskulatur, unterer Rücken', level: 'Anfänger', video: `${D}/musculation`, technique: `Unterarme am Boden, Körper in einer Linie, Bauch und Gesäß angespannt. Halte die Position bei ruhiger Atmung. Steigere dich, indem du die Dauer verlängerst oder Zusatzgewicht hinzufügst.`, mistakes: `Becken sackt ab, Gesäß zu hoch, Kopf angehoben.` },
    { type: 'exercise', name: 'Hängendes Beinheben', muscles: 'Unterer Bauch, Rumpfstabilität', level: 'Fortgeschritten', video: `${D}/musculation`, technique: `An der Stange hängend, ziehe die Knie (oder gestreckten Beine) zur Brust, indem du das Becken einrollst, dann kontrolliert ablassen, ohne zu schwingen.`, mistakes: `Schwingen, nur die Beine heben ohne das Becken einzurollen, zu schnelles Ablassen.` },
    { type: 'list', items: [
      `Core-Zirkel: Plank 45 s + Beinheben 12 Wdh. + Seitstütz 30 s/Seite, 3 Runden.`,
      `Füge Zusatzgewicht hinzu, sobald das eigene Körpergewicht zu leicht wird.`,
    ] },

    { type: 'h1', text: 'Die 12 Wochen im Detail' },
    { type: 'p', text: `Behalte den Split bei und passe Wiederholungen und Gewichte je nach Block an.` },
    { type: 'table', headers: ['Woche', 'Sätze × Wdh.', 'Hinweis'], rows: [
      ['W1-W2', '4 × 10-12', 'Volumen, Technik, RPE 7-8'],
      ['W3-W4', '4 × 10', '+ Gewicht, Bilanz in W4'],
      ['W5-W6', '4 × 8-10', 'Hypertrophie, 1 Intensivierungstechnik/Einheit'],
      ['W7-W8', '4 × 8', '+ Gewicht, RPE 8-9'],
      ['W9-W10', '5 × 6-8', 'Kraft, lange Pausen'],
      ['W11', '5 × 5-6', 'Intensitätsspitze'],
      ['W12', 'Deload + Tests', 'Deload, dann Krafttests, Bilanz'],
    ] },

    { type: 'h1', text: 'Progression & Periodisierung' },
    { type: 'p', text: `Auf deinem Niveau reicht lineare Progression nicht mehr aus: Du musst periodisieren (zwischen Volumen und Intensität wechseln) und die Ermüdung steuern.` },
    { type: 'list', items: [
      `Progressive Überlastung: +2,5 kg oder +1 Wdh., sobald du bei allen Sätzen die obere Grenze der Spanne erreichst.`,
      `Autoregulation: Fühlst du dich fit, gib Vollgas; bist du müde, behalte eine Wiederholung mehr in Reserve.`,
      `Deload verpflichtend alle 4-6 Wochen: eine Woche mit −40 % Volumen.`,
      `Führe ein Trainingstagebuch: Gewicht × Wiederholungen × Sätze. Das ist dein Kompass.`,
    ] },

    { type: 'h1', text: 'Zu vermeidende Fehler' },
    { type: 'list', items: [
      `Zu viel Volumen auf einmal: steigere schrittweise, sonst summiert sich die Ermüdung.`,
      `Intensivierungstechniken übertreiben: 1-2 pro Einheit reichen aus.`,
      `Beintraining oder Rudern auslassen (führt zu Dysbalancen und Verletzungen).`,
      `Den Deload vernachlässigen: Übertraining bringt dich zurück, nicht voran.`,
      `Schlechtes Schlaf-/Ernährungsmanagement: du sabotierst dein Trainingsvolumen.`,
    ] },
    { type: 'h2', text: 'Problem → Lösung' },
    { type: 'table', headers: ['Du erlebst…', 'Die Lösung'], rows: [
      ['Kraftstagnation', '1 Woche Deload, Schlaf & Kalorien prüfen'],
      ['Anhaltende Müdigkeit', 'Volumen reduzieren, einen Ruhetag hinzufügen'],
      ['Schulterschmerzen', 'Mehr Face Pulls, Ellbogenwinkel überprüfen'],
      ['Zu schneller Fettaufbau', 'Überschuss reduzieren, Eiweiß hoch halten'],
    ] },

    { type: 'h1', text: 'Motiviert bleiben' },
    { type: 'list', items: [
      `Setze dir konkrete Kraftziele (z. B. Kniebeuge mit dem 1,5-fachen Körpergewicht).`,
      `Fotos & Maße alle 4 Wochen.`,
      `Wechsle die Musik, trainiere mit einem Partner an Tagen ohne Motivation.`,
      `Denk daran: 12 Wochen Konstanz sind mehr wert als 3 perfekte Monate gefolgt vom Aufgeben.`,
    ] },
    { type: 'h2', text: 'Baue die Gewohnheit auf' },
    { type: 'list', items: [
      `Blocke deine 4-5 Trainingszeiten wie unverhandelbare Termine.`,
      `Bereite Tasche und Mahlzeiten am Vorabend vor.`,
      `Lass die Kette nie 2 Einheiten in Folge reißen.`,
    ] },

    { type: 'h1', text: 'Häufige Fragen' },
    { type: 'h2', text: 'PPL oder Oberkörper/Unterkörper?' },
    { type: 'p', text: `Beide funktionieren. PPL eignet sich, wenn du 5-6×/Woche trainieren kannst; Oberkörper/Unterkörper, wenn du 4×/Woche anstrebst. Dieses Programm kombiniert beide Ansätze für 5 Tage. Pass es an deinen Zeitplan an.` },
    { type: 'h2', text: 'Wie viele Sätze pro Muskel?' },
    { type: 'p', text: `12 bis 20 Sätze pro Woche und Muskelgruppe für die meisten Fortgeschrittenen. Starte bei 12-14 und steigere schrittweise, wenn du gut regenerierst.` },
    { type: 'h2', text: 'Muss man bis zum Muskelversagen trainieren?' },
    { type: 'p', text: `Behalte bei den meisten Sätzen 1-2 Wiederholungen in Reserve. Reserviere das Muskelversagen dem letzten Satz von Isolationsübungen, nicht den schweren Grundübungen (Kniebeuge, Kreuzheben).` },
    { type: 'h2', text: 'Welche Nahrungsergänzungsmittel auf diesem Niveau?' },
    { type: 'p', text: `Kreatin-Monohydrat (3-5 g/Tag) und Whey bleiben am nützlichsten. Koffein vor dem Training für die Leistung. Der Rest ist Nebensache.` },
    { type: 'h2', text: 'Cardio, ohne Muskeln zu verlieren?' },
    { type: 'p', text: `Ja: 2-3 moderate Cardio-Einheiten (20-30 Min.) pro Woche, wenn möglich getrennt von den Beintagen. Vermeide zu viel intensives Cardio, das die Erholung beeinträchtigt.` },

    { type: 'h1', text: 'Konditionierung & Cardio' },
    { type: 'p', text: `Etwas Cardio verbessert deine Erholung zwischen den Sätzen, deine Arbeitskapazität und hält das Fett während des Überschusses in Schach - ohne deine Fortschritte zu beeinträchtigen, wenn du es richtig dosierst.` },
    { type: 'list', items: [
      `2 bis 3 moderate Cardio-Einheiten (20-30 Min.) pro Woche, idealerweise an Tagen ohne Beintraining.`,
      `Tägliches Gehen (8.000-10.000 Schritte): die Basis, ohne Auswirkung auf die Erholung.`,
      `Finisher-Option: 5-8 Min. intensives Cardio am Ende der Oberkörper-Einheit.`,
      `Vermeide lange, intensive Cardio-Einheiten am Tag vor dem Beintraining.`,
    ] },
    { type: 'table', headers: ['Art', 'Dauer', 'Häufigkeit', 'Effekt'], rows: [
      ['Gehen', '30-45 Min.', 'Täglich', 'Verbrauch, Erholung'],
      ['Moderates Cardio (Rad/Rudern)', '20-30 Min.', '2-3×/Woche', 'Gesundheit, Kapazität'],
      ['HIIT-Finisher', '5-8 Min.', '1-2×/Woche', 'Konditionierung'],
    ] },

    { type: 'h1', text: 'Dehnen & Mobilität' },
    { type: 'p', text: `Trainiere die Mobilität 2-3×/Woche, um vollen Bewegungsumfang unter Last zu unterstützen.` },
    { type: 'table', headers: ['Übung', 'Bereich', 'Dauer'], rows: [
      ['Schultermobilität (Stange/Band)', 'Schultern', '1 Min.'],
      ['Hüftmobilität (tiefer Ausfallschritt)', 'Hüften', '30 s / Seite'],
      ['Sprunggelenk-Mobilität', 'Sprunggelenke', '30 s / Seite'],
      ['Brustdehnung', 'Brust', '30 s / Seite'],
      ['Hang an der Stange', 'Rücken, Schultern', '30 s'],
      ['Brustwirbelsäulen-Rotation', 'Wirbelsäule', '45 s'],
    ] },

    { type: 'h1', text: 'Sicherheit & Prävention' },
    { type: 'list', items: [
      `Wärme dich mit Aufwärmsätzen vor jeder schweren Übung auf.`,
      `Nutze einen Spotter oder Sicherheitsablagen bei Kniebeuge und Bankdrücken.`,
      `Behalte eine perfekte Technik bei, wenn du das Gewicht steigerst: Verletzungen kommen vom Ego.`,
      `Halte dich an Deloads und ausreichend Schlaf: Erholung verhindert 90 % der Probleme.`,
    ] },

    { type: 'h1', text: 'Und nach deinen 12 Wochen?' },
    { type: 'p', text: `Du hast an Muskeln und Kraft gewonnen. Um weiter Fortschritte zu machen, ändere den Trainingsreiz und setze dir ein neues Ziel.` },
    { type: 'list', items: [
      `Steige um auf das Muskelaufbau-Programm für Experten (anspruchsvollere Techniken und mehr Volumen).`,
      `Ziel Muskelaufbau: starte direkt eine echte Masseaufbau-Phase.`,
      `Ziel Definition: wechsle in eine Abnehmphase, um die aufgebauten Muskeln sichtbar zu machen.`,
      `Wiederhole deine Maße, Fotos und Krafttests, um deinen Fortschritt zu messen.`,
    ] },
    { type: 'note', text: `Tipp: Wiederhole nicht exakt dasselbe Programm. Variiere Übungen, Winkel und Wiederholungsbereiche, um neue Fortschritte anzustoßen.` },

    { type: 'h1', text: 'Nahrungsergänzungsmittel' },
    { type: 'p', text: `Keines ist zwingend notwendig, aber einige haben auf deinem Trainingsniveau einen nachweislichen Nutzen.` },
    { type: 'table', headers: ['Nahrungsergänzung', 'Nutzen', 'Dosis'], rows: [
      ['Kreatin-Monohydrat', 'Kraft & Volumen, am besten erforscht', '3 bis 5 g/Tag'],
      ['Whey', 'Eiweißbedarf einfach erreichen', '1 bis 2 Portionen/Tag'],
      ['Koffein', 'Leistung & Energie vor dem Training', '3 mg/kg, 30-45 Min. vorher'],
      ['Omega-3 / Vitamin D', 'Erholung, Gelenke, Gesundheit', 'Nach Bedarf'],
    ] },
    { type: 'note', text: `Die Basis bleiben Ernährung und Training. Nahrungsergänzungsmittel sind nur ein kleines Plus - verlasse dich nie darauf, ein schlechtes Programm oder schlechten Schlaf auszugleichen.` },

    { type: 'h1', text: 'Tracking deines Fortschritts' },
    { type: 'p', text: `Notiere deine Gewichte bei jeder Einheit und deine Maße jede Woche.` },
    { type: 'h2', text: 'Gewicht & Maße' },
    { type: 'tracker', columns: ['Datum', 'Gewicht (kg)', 'Arm', 'Oberschenkel', 'Brust', 'Taille'], rows: 7 },
    { type: 'h2', text: 'Kraft bei den Schlüsselübungen (kg × Wdh.)' },
    { type: 'tracker', columns: ['Übung', 'W1', 'W4', 'W8', 'W12'], rows: 6 },

    { type: 'h1', text: 'Wöchentliche Checkliste' },
    { type: 'p', text: `Hake jedes Kästchen am Ende der Woche ab. Ziel: mindestens 6 von 8.` },
    { type: 'checklist', items: [
      `Ich habe alle meine Einheiten diese Woche absolviert.`,
      `Ich habe mein Zielvolumen pro Muskelgruppe erreicht.`,
      `Ich habe bei mindestens einer Schlüsselübung Fortschritte gemacht.`,
      `Ich habe jeden Tag meine Proteinzufuhr erreicht.`,
      `Ich habe in einem leichten, kontrollierten Überschuss gegessen.`,
      `Ich habe die meisten Nächte 7 bis 9 Std. geschlafen.`,
      `Ich habe meine Pausenzeiten eingehalten.`,
      `Ich habe alle meine Gewichte notiert.`,
    ] },

    { type: 'h1', text: 'Persönliche Notizen' },
    { type: 'tracker', columns: ['Meine Notizen, Gewichte und Empfindungen der Woche'], rows: 16 },

    { type: 'h1', text: 'Glossar' },
    { type: 'list', items: [
      `PPL: Push / Pull / Legs (Drücken / Ziehen / Beine).`,
      `Volumen: Gesamtzahl der Sätze pro Muskel und Woche.`,
      `Periodisierung: das Training in Blöcken organisieren (Volumen, Intensität, Kraft).`,
      `Superset: zwei Übungen ohne Pause hintereinander.`,
      `Dropset: das Gewicht bei Muskelversagen reduzieren, um den Satz fortzusetzen.`,
      `Deload: eine leichtere Woche zur Erholung.`,
      `Autoregulation: die Anstrengung an deine Tagesform anpassen (RPE).`,
    ] },

    { type: 'note', text: `12 Wochen geschafft? Mach einen Deload, teste deine Kraft, nimm deine Maße, und starte dann das Muskelaufbau-Programm für Experten oder eine Masseaufbau-/Abnehmphase, je nach deinem Ziel. Erstelle dein Konto auf xenotif.com.` },
  ],
}
