import type { Guide } from '@/lib/boutique/guides'

// d2 - Ernährungsplan Definitionsphase 8 Wochen (DE-Mirror von nutrition-seche.ts).
// ERNÄHRUNGSprogramm: 56 Tage Menüs, 40+ Rezepte, Einkaufslisten, persönliche Makros, vegane Version.
export const nutritionSecheDe: Guide = {
  id: 'd2',
  title: 'Ernährungsplan Definitionsphase - 8 Wochen',
  subtitle: '56 Tage Menüs, 40+ Rezepte, Einkaufslisten, persönliche Makros, vegane Version',
  author: 'XENOTIF Coach - Zertifizierte Sporternährung',
  level: 'Alle Niveaus',
  duration: '8 Wochen · 56 Tage Menüs',
  coverImage: 'seche-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Willkommen zu deiner Definitionsphase' },
    { type: 'p', text: `Dieser 8-Wochen-Plan hilft dir, deine Muskeldefinition durch Fettabbau zu zeigen - ohne den hart erarbeiteten Muskel zu opfern, ohne extreme Diät oder absurden Verzicht. Eine progressive, haltbare und wissenschaftlich fundierte Methode. Du findest darin die Berechnung deines Bedarfs, 56 Tage detaillierte Menüs, 40+ Rezepte, deine Einkaufslisten und eine vollständige vegane Version.` },
    { type: 'p', text: `Dieses Dokument ist dein Ernährungsplan für die Hosentasche: folge den Menüs Tag für Tag, kaufe mit den bereitgestellten Listen ein und lass die Definition Woche für Woche erscheinen.` },
    { type: 'meta', items: [
      { label: 'Ziel', value: 'Fett verlieren, Muskel halten' },
      { label: 'Niveau', value: 'Alle Niveaus' },
      { label: 'Dauer', value: '8 Wochen (56 Tage)' },
      { label: 'Defizit', value: '300 bis 500 kcal / Tag' },
      { label: 'Eiweiß', value: '2 bis 2,4 g pro kg' },
      { label: 'Enthalten', value: 'Menüs + Rezepte + Einkauf' },
    ] },
    { type: 'h2', text: 'Was du bekommst' },
    { type: 'list', items: [
      `Stetigen Fettabbau (0,5 bis 0,8 % deines Gewichts pro Woche).`,
      `Den Erhalt deiner Muskelmasse durch hohes Eiweiß.`,
      `56 Tage gebrauchsfertige Menüs, ausgewogen und schmackhaft.`,
      `Ess-Automatismen, die du nach der Definitionsphase behältst.`,
    ] },
    { type: 'h2', text: 'So nutzt du diesen Plan' },
    { type: 'list', items: [
      `Berechne deinen Bedarf (Kapitel „Deine persönlichen Makros").`,
      `Folge den Menüs Woche für Woche oder wähle aus den 40+ Rezepten.`,
      `Kaufe mit den bereitgestellten Wochenlisten ein.`,
      `Wiege dich 1× pro Woche, nüchtern, und passe bei Bedarf an.`,
    ] },
    { type: 'note', text: `Eine Definitionsphase ist ein Marathon, kein Sprint. Ein stetiger Verlust von 0,5 bis 0,8 % deines Gewichts pro Woche bewahrt den Muskel. Schneller = Muskel schmelzen und den Stoffwechsel ruinieren.` },

    { type: 'h1', text: 'Das Prinzip der Definitionsphase' },
    { type: 'p', text: `Definieren heißt Fettmasse verlieren und dabei den Muskel bewahren. Das erfordert drei Dinge gleichzeitig.` },
    { type: 'list', items: [
      `Ein moderates Kaloriendefizit: 15 bis 20 % unter deinem Erhalt, nicht mehr.`,
      `Hohes Eiweiß: 2 bis 2,4 g pro kg, um die Magermasse zu schützen.`,
      `Beibehaltung des Krafttrainings: das ist das Signal, das dem Körper sagt, den Muskel zu halten.`,
    ] },
    { type: 'p', text: `Kohlenhydrate und Fette füllen den Rest deiner Kalorien: sie geben dir Energie zum Trainieren und stützen deine Hormone. Man streicht sie nicht, man passt sie an.` },

    { type: 'chapter', title: 'Deine persönlichen Makros', src: 'seche-1.jpg' },
    { type: 'p', text: `So berechnest du deinen Bedarf in 3 Schritten. Keine Feinwaage nötig: diese Richtwerte reichen für die große Mehrheit der Fälle.` },
    { type: 'h2', text: 'Schritt 1 - Dein Erhalt' },
    { type: 'p', text: `Schnellschätzung: Gewicht (kg) × 30 bis 33 (je nach Aktivität). Beispiel für 75 kg, mäßig aktiv: 75 × 31 ≈ 2 325 kcal/Tag Erhalt.` },
    { type: 'h2', text: 'Schritt 2 - Dein Defizit' },
    { type: 'p', text: `Ziehe 15 bis 20 % ab: 2 325 − 18 % ≈ 1 900 kcal/Tag. Das ist dein Kalorienziel in der Definitionsphase.` },
    { type: 'h2', text: 'Schritt 3 - In Makros aufteilen' },
    { type: 'table', headers: ['Makro', 'Berechnung', 'Beispiel (75 kg, 1 900 kcal)'], rows: [
      ['Eiweiß', '2,2 g/kg', '165 g (660 kcal)'],
      ['Fette', '0,8 g/kg', '60 g (540 kcal)'],
      ['Kohlenhydrate', 'der Rest', '175 g (700 kcal)'],
    ] },
    { type: 'h2', text: 'Kalorien-Richtwerte nach Gewicht' },
    { type: 'table', headers: ['Gewicht', 'Erhalt ≈', 'Definition ≈', 'Eiweiß'], rows: [
      ['60 kg', '1 860 kcal', '1 500 kcal', '130 g'],
      ['70 kg', '2 170 kcal', '1 750 kcal', '155 g'],
      ['80 kg', '2 480 kcal', '2 000 kcal', '175 g'],
      ['90 kg', '2 790 kcal', '2 250 kcal', '200 g'],
    ] },
    { type: 'note', text: `Passe nach 2 Wochen an: kein Verlust → 100-150 kcal abziehen (Kohlenhydrate am Abend). Zu schneller Verlust (> 1 %/Woche) oder Kraftverlust → 100-150 kcal hinzufügen.` },

    { type: 'h1', text: 'Die goldenen Regeln der Definitionsphase' },
    { type: 'list', items: [
      `Eine Eiweißquelle bei JEDER Mahlzeit (0,4 g/kg pro Portion).`,
      `Die Hälfte des Tellers Gemüse: Volumen, Sättigung, Mikronährstoffe.`,
      `Kohlenhydrate vor allem rund ums Training (Energie + Erholung).`,
      `2 bis 2,5 L Wasser/Tag: ein großes Glas vor jeder Mahlzeit (Sättigungseffekt).`,
      `Begrenze flüssigen Zucker und Alkohol (leere Kalorien, die das Defizit sabotieren).`,
      `1 Genuss-Mahlzeit pro Woche, um langfristig durchzuhalten, ohne einzubrechen.`,
    ] },

    { type: 'chapter', title: 'Mahlzeitenplan - 56 Tage', src: 'seche-2.jpg', intro: `Hier sind 8 Wochen gebrauchsfertige Menüs (≈1 800-1 900 kcal, passe die Portionen an DEINE Makros an). Jede Woche wechselt die Mahlzeiten, um Langeweile zu vermeiden. Alle Rezepte sind später detailliert. Vegane Version: siehe eigenes Kapitel.` },
    { type: 'h2', text: 'Woche 1' },
    { type: 'table', headers: ['Tag', 'Frühstück', 'Mittag', 'Abend'], rows: [
      ['Mo', 'Skyr-Haferflocken-Obst', 'Hähnchen-Reis-Brokkoli', 'Lachs-Süßkartoffel-Salat'],
      ['Di', 'Omelett 3 Eier + Brot', 'Mageres Rind-Quinoa-Gemüse', 'Gebratener Tofu-Reis-Zucchini'],
      ['Mi', 'Skyr-Haferflocken-Obst', 'Hähnchen-Wrap-Rohkost', 'Kabeljau-Kartoffeln-Bohnen'],
      ['Do', 'Rührei + Avocado', 'Pute-Vollkornreis-Paprika', 'Gemüse-Omelett + Salat'],
      ['Fr', 'Eiweiß-Porridge', 'Kichererbsen-Thunfisch-Salat', 'Hähnchen-Süßkartoffel-Spinat'],
      ['Sa', 'Eiweiß-Pancakes', 'Genuss-Mahlzeit (vernünftig)', 'Suppe + harte Eier + Brot'],
      ['So', 'Skyr-Obst-Mandeln', 'Hähnchen-Reis-Gemüse-Bowl', 'Weißfisch-Quinoa-Salat'],
    ] },
    { type: 'h2', text: 'Woche 2' },
    { type: 'table', headers: ['Tag', 'Frühstück', 'Mittag', 'Abend'], rows: [
      ['Mo', 'Omelett + Haferflocken', 'Rind-Reis-Brokkoli', 'Tofu-Quinoa-grünes Gemüse'],
      ['Di', 'Skyr-Haferflocken-Obst', 'Hähnchen-Süßkartoffel-Salat', 'Kabeljau-Reis-Zucchini'],
      ['Mi', 'Avocado-Ei-Toast', 'Pute-Wrap-Rohkost', 'Lachs-Kartoffeln-Bohnen'],
      ['Do', 'Eiweiß-Porridge', 'Quinoa-Hähnchen-Salat', 'Gemüse-Omelett + Vollkornbrot'],
      ['Fr', 'Eiweiß-Pancakes', 'Fisch-Vollkornreis-Spinat', 'Hähnchen-Zucchini-Feta'],
      ['Sa', 'Skyr-Obst-Mandeln', 'Genuss-Mahlzeit (vernünftig)', 'Suppe + Thunfisch + Brot'],
      ['So', 'Rührei + Avocado', 'Rind-Reis-Gemüse-Bowl', 'Weißfisch-Süßkartoffel-Salat'],
    ] },
    { type: 'h2', text: 'Woche 3' },
    { type: 'table', headers: ['Tag', 'Frühstück', 'Mittag', 'Abend'], rows: [
      ['Mo', 'Eiweiß-Porridge', 'Hähnchen-Quinoa-Zucchini', 'Kabeljau-Süßkartoffel-Bohnen'],
      ['Di', 'Skyr-Haferflocken-Obst', 'Mageres Rind-Reis-Brokkoli', 'Gebratener Tofu-Reis-Paprika'],
      ['Mi', 'Omelett + Brot', 'Hähnchen-Feta-Tomaten-Salat', 'Lachs-Kartoffeln-Spinat'],
      ['Do', 'Eiweiß-Pancakes', 'Pute-Wrap-Rohkost', 'Gemüse-Omelett + Salat'],
      ['Fr', 'Avocado-Ei-Toast', 'Thunfisch-weiße Bohnen-Tomate', 'Hähnchen-Zucchini-Quinoa'],
      ['Sa', 'Skyr-Obst-Mandeln', 'Genuss-Mahlzeit (vernünftig)', 'Gemüsesuppe + harte Eier'],
      ['So', 'Rührei + Avocado', 'Hähnchen-Reis-Gemüse-Bowl', 'Weißfisch-Süßkartoffel-Salat'],
    ] },
    { type: 'h2', text: 'Woche 4' },
    { type: 'table', headers: ['Tag', 'Frühstück', 'Mittag', 'Abend'], rows: [
      ['Mo', 'Skyr-Haferflocken-Obst', 'Pute-Vollkornreis-Paprika', 'Gebratene Garnelen-Reis-Zucchini'],
      ['Di', 'Omelett 3 Eier', 'Hähnchen-Süßkartoffel-Brokkoli', 'Tofu-Quinoa-grünes Gemüse'],
      ['Mi', 'Eiweiß-Porridge', 'Kichererbsen-Thunfisch-Salat', 'Kabeljau-Kartoffeln-Bohnen'],
      ['Do', 'Spinat-Whey-Bananen-Smoothie', 'Mageres Rind-Quinoa-Gemüse', 'Gemüse-Omelett + Brot'],
      ['Fr', 'Eiweiß-Pancakes', 'Hähnchen-Wrap-Rohkost', 'Lachs-Süßkartoffel-Salat'],
      ['Sa', 'Skyr-Obst-Mandeln', 'Genuss-Mahlzeit (vernünftig)', 'Linsen-Gemüse-Suppe'],
      ['So', 'Avocado-Ei-Toast', 'Rind-Reis-Gemüse-Bowl', 'Weißfisch-Quinoa-Spinat'],
    ] },
    { type: 'h2', text: 'Woche 5' },
    { type: 'table', headers: ['Tag', 'Frühstück', 'Mittag', 'Abend'], rows: [
      ['Mo', 'Eiweiß-Porridge', 'Hähnchen-Reis-Brokkoli', 'Gebratener Tofu-Reis-Zucchini'],
      ['Di', 'Skyr-Haferflocken-Obst', 'Mageres Rind-Süßkartoffel-Salat', 'Kabeljau-Quinoa-Bohnen'],
      ['Mi', 'Omelett + Brot', 'Quinoa-Edamame-Tofu-Salat', 'Lachs-Kartoffeln-Spinat'],
      ['Do', 'Eiweiß-Pancakes', 'Pute-Vollkornreis-Paprika', 'Gemüse-Omelett + Salat'],
      ['Fr', 'Avocado-Ei-Toast', 'Hähnchen-Wrap-Rohkost', 'Hähnchen-Zucchini-Feta'],
      ['Sa', 'Skyr-Obst-Mandeln', 'Genuss-Mahlzeit (vernünftig)', 'Suppe + Thunfisch + Brot'],
      ['So', 'Rührei + Avocado', 'Hähnchen-Reis-Gemüse-Bowl', 'Weißfisch-Süßkartoffel-Salat'],
    ] },
    { type: 'h2', text: 'Woche 6' },
    { type: 'table', headers: ['Tag', 'Frühstück', 'Mittag', 'Abend'], rows: [
      ['Mo', 'Skyr-Haferflocken-Obst', 'Mageres Rind-Reis-Brokkoli', 'Garnelen-Reis-Zucchini'],
      ['Di', 'Omelett 3 Eier', 'Hähnchen-Quinoa-Gemüse', 'Tofu-Quinoa-Paprika'],
      ['Mi', 'Eiweiß-Porridge', 'Hähnchen-Feta-Tomaten-Salat', 'Kabeljau-Kartoffeln-Bohnen'],
      ['Do', 'Eiweiß-Pancakes', 'Thunfisch-weiße Bohnen-Tomate', 'Gemüse-Omelett + Brot'],
      ['Fr', 'Avocado-Ei-Toast', 'Pute-Süßkartoffel-Spinat', 'Lachs-Quinoa-Salat'],
      ['Sa', 'Skyr-Obst-Mandeln', 'Genuss-Mahlzeit (vernünftig)', 'Gemüsesuppe + harte Eier'],
      ['So', 'Rührei + Avocado', 'Rind-Reis-Gemüse-Bowl', 'Weißfisch-Süßkartoffel-Salat'],
    ] },
    { type: 'h2', text: 'Woche 7' },
    { type: 'table', headers: ['Tag', 'Frühstück', 'Mittag', 'Abend'], rows: [
      ['Mo', 'Eiweiß-Porridge', 'Hähnchen-Reis-Brokkoli', 'Gebratener Tofu-Reis-Zucchini'],
      ['Di', 'Skyr-Haferflocken-Obst', 'Mageres Rind-Quinoa-Gemüse', 'Kabeljau-Süßkartoffel-Bohnen'],
      ['Mi', 'Omelett + Brot', 'Pute-Wrap-Rohkost', 'Lachs-Kartoffeln-Spinat'],
      ['Do', 'Spinat-Whey-Bananen-Smoothie', 'Kichererbsen-Thunfisch-Salat', 'Gemüse-Omelett + Salat'],
      ['Fr', 'Eiweiß-Pancakes', 'Hähnchen-Süßkartoffel-Paprika', 'Garnelen-Quinoa-Zucchini'],
      ['Sa', 'Skyr-Obst-Mandeln', 'Genuss-Mahlzeit (vernünftig)', 'Linsen-Gemüse-Suppe'],
      ['So', 'Avocado-Ei-Toast', 'Hähnchen-Reis-Gemüse-Bowl', 'Weißfisch-Quinoa-Salat'],
    ] },
    { type: 'h2', text: 'Woche 8 (Finish)' },
    { type: 'table', headers: ['Tag', 'Frühstück', 'Mittag', 'Abend'], rows: [
      ['Mo', 'Skyr-Haferflocken-Obst', 'Hähnchen-Reis-Brokkoli', 'Kabeljau-Süßkartoffel-Bohnen'],
      ['Di', 'Omelett 3 Eier', 'Mageres Rind-Quinoa-Gemüse', 'Tofu-Quinoa-Paprika'],
      ['Mi', 'Eiweiß-Porridge', 'Hähnchen-Feta-Tomaten-Salat', 'Lachs-Kartoffeln-Spinat'],
      ['Do', 'Eiweiß-Pancakes', 'Pute-Vollkornreis-Gemüse', 'Gemüse-Omelett + Salat'],
      ['Fr', 'Avocado-Ei-Toast', 'Thunfisch-weiße Bohnen-Tomate', 'Hähnchen-Zucchini-Quinoa'],
      ['Sa', 'Skyr-Obst-Mandeln', 'Leichte Genuss-Mahlzeit', 'Suppe + harte Eier'],
      ['So', 'Rührei + Avocado', 'Hähnchen-Reis-Gemüse-Bowl', 'Weißfisch-Süßkartoffel-Salat'],
    ] },
    { type: 'note', text: `Tipp: du kannst dasselbe Frühstück 2-3 Tage hintereinander behalten, um es einfach zu halten - die Vielfalt zählt über die Woche. Passe die PORTIONEN immer an DEINE Makros an (vorheriges Kapitel).` },

    { type: 'chapter', title: 'Deine Einkaufslisten', src: 'seche-1.jpg', intro: `Kaufe 1 bis 2 Mal pro Woche mit diesen Listen ein. Die richtigen Lebensmittel kaufen = ohne Nachdenken richtig essen.` },
    { type: 'h2', text: 'Eiweiß' },
    { type: 'list', items: [`Hähnchen, Pute, mageres Rind 5%`, `Weißfisch, Lachs, Thunfisch`, `Eier, Skyr, Magerquark 0%`, `Tofu, Tempeh, Hülsenfrüchte`, `Whey (Option)`] },
    { type: 'h2', text: 'Kohlenhydrate & Beilagen' },
    { type: 'list', items: [`Reis, Quinoa, Vollkornnudeln`, `Süßkartoffel, Kartoffeln`, `Haferflocken, Vollkornbrot`, `Obst (Banane, Apfel, Beeren)`] },
    { type: 'h2', text: 'Gemüse & Fette' },
    { type: 'list', items: [`Brokkoli, Zucchini, Spinat, grüne Bohnen, Paprika, Salat, Tomate`, `Olivenöl, Avocado, Mandeln, Walnüsse`, `Zitrone, Knoblauch, Kräuter, Gewürze (nach Belieben)`] },

    { type: 'chapter', title: 'Rezepte - Frühstück', src: 'seche-2.jpg' },
    { type: 'h2', text: '1. Skyr-Haferflocken-Beeren' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 350 kcal' }, { label: 'Eiweiß', value: '30 g' }] },
    { type: 'list', items: [`200 g Skyr`, `40 g Haferflocken`, `1 Handvoll Beeren`] },
    { type: 'p', text: `Skyr und Haferflocken mischen, 5 Min. ziehen lassen, Obst zugeben.` },
    { type: 'h2', text: '2. Eiweiß-Omelett' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 320 kcal' }, { label: 'Eiweiß', value: '28 g' }] },
    { type: 'list', items: [`3 Eier`, `Spinat, Tomate`, `1 Scheibe Vollkornbrot`] },
    { type: 'p', text: `Eier verquirlen, mit dem Gemüse bei niedriger Hitze garen, mit dem Brot servieren.` },
    { type: 'h2', text: '3. Eiweiß-Porridge' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 380 kcal' }, { label: 'Eiweiß', value: '32 g' }] },
    { type: 'list', items: [`50 g Haferflocken`, `250 ml Milch`, `1 Portion Whey`, `Zimt`] },
    { type: 'p', text: `Haferflocken 3 Min. in der Milch erhitzen, vom Herd Whey und Zimt unterrühren.` },
    { type: 'h2', text: '4. Eiweiß-Pancakes' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 360 kcal' }, { label: 'Eiweiß', value: '30 g' }] },
    { type: 'list', items: [`1 Banane`, `2 Eier`, `40 g Haferflocken`, `1/2 Portion Whey`] },
    { type: 'p', text: `Alles mixen, kleine Pancakes in der Pfanne backen. Mit Obst belegen.` },
    { type: 'h2', text: '5. Avocado-Ei-Toast' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 380 kcal' }, { label: 'Eiweiß', value: '22 g' }] },
    { type: 'list', items: [`2 Scheiben Vollkornbrot`, `1/2 Avocado`, `2 Eier`, `Zitrone, Pfeffer`] },
    { type: 'p', text: `Avocado auf das Brot zerdrücken, Eier zugeben (Spiegel- oder pochiert).` },

    { type: 'h1', text: 'Rezepte - Mittag' },
    { type: 'h2', text: '6. Hähnchen-Reis-Gemüse-Bowl' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 480 kcal' }, { label: 'Eiweiß', value: '42 g' }] },
    { type: 'list', items: [`130 g Hähnchen`, `100 g Reis (roh)`, `Gemüse`, `Sojasoße`] },
    { type: 'p', text: `Reis kochen, Hähnchen und Gemüse anbraten, zusammenstellen.` },
    { type: 'h2', text: '7. Hähnchen-Wrap-Rohkost' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 450 kcal' }, { label: 'Eiweiß', value: '38 g' }] },
    { type: 'list', items: [`1 Vollkorn-Wrap`, `120 g Hähnchen`, `Rohkost`, `Magerquark + Senf`] },
    { type: 'p', text: `Bestreichen, füllen, fest aufrollen.` },
    { type: 'h2', text: '8. Kichererbsen-Thunfisch-Salat' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 450 kcal' }, { label: 'Eiweiß', value: '35 g' }] },
    { type: 'list', items: [`1 Dose Kichererbsen`, `1 Dose Thunfisch`, `Tomaten, Zwiebel`, `Zitrone, Olivenöl`] },
    { type: 'p', text: `Alles mischen. Schnell, ohne Kochen.` },
    { type: 'h2', text: '9. Mageres Rind-Quinoa' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 520 kcal' }, { label: 'Eiweiß', value: '45 g' }] },
    { type: 'list', items: [`140 g Rind 5%`, `80 g Quinoa (roh)`, `Grünes Gemüse`, `Gewürze`] },
    { type: 'p', text: `Rind anbraten, über dem Quinoa mit dem Gemüse servieren.` },

    { type: 'h1', text: 'Rezepte - Abend' },
    { type: 'h2', text: '10. Lachs-Süßkartoffel-Salat' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 500 kcal' }, { label: 'Eiweiß', value: '38 g' }] },
    { type: 'list', items: [`130 g Lachs`, `200 g Süßkartoffel`, `Grüner Salat`, `Olivenöl, Zitrone`] },
    { type: 'p', text: `Lachs und Süßkartoffel im Ofen garen, mit dem Salat servieren.` },
    { type: 'h2', text: '11. Kabeljau-Kartoffeln-Bohnen' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 430 kcal' }, { label: 'Eiweiß', value: '40 g' }] },
    { type: 'list', items: [`160 g Kabeljau`, `200 g Kartoffeln`, `Grüne Bohnen`, `Kräuter`] },
    { type: 'p', text: `Alles dämpfen oder im Ofen garen, würzen.` },
    { type: 'h2', text: '12. Gebratener Tofu-Reis-Zucchini' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 450 kcal' }, { label: 'Eiweiß', value: '28 g' }] },
    { type: 'list', items: [`150 g fester Tofu`, `80 g Reis (roh)`, `Zucchini`, `Sojasoße, Ingwer`] },
    { type: 'p', text: `Tofu anbraten, Zucchini zugeben, über dem Reis servieren.` },
    { type: 'h2', text: '13. Gemüse-Omelett am Abend' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 320 kcal' }, { label: 'Eiweiß', value: '28 g' }] },
    { type: 'list', items: [`3 Eier`, `Spinat, Paprika`, `Grüner Salat`] },
    { type: 'p', text: `Gemüse anschwitzen, Eier angießen, mit einem Salat servieren.` },

    { type: 'h1', text: 'Rezepte - Snacks' },
    { type: 'h2', text: '14. Eiweiß-Skyr' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 220 kcal' }, { label: 'Eiweiß', value: '28 g' }] },
    { type: 'list', items: [`250 g Skyr`, `Beeren`, `Zimt`] },
    { type: 'p', text: `Mischen. Perfekt zwischen den Mahlzeiten oder nach dem Training.` },
    { type: 'h2', text: '15. Eiweiß-Shake' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 200 kcal' }, { label: 'Eiweiß', value: '25 g' }] },
    { type: 'list', items: [`1 Portion Whey`, `250 ml Wasser oder Magermilch`, `Eiswürfel`] },
    { type: 'p', text: `Mixen oder schütteln. Praktisch im Büro.` },
    { type: 'h2', text: '16. Harte Eier + Rohkost' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 180 kcal' }, { label: 'Eiweiß', value: '16 g' }] },
    { type: 'list', items: [`2 harte Eier`, `Karotten-/Gurkensticks`, `Salz, Pfeffer`] },
    { type: 'p', text: `Eier 9 Min. kochen, mit der Rohkost servieren.` },
    { type: 'h2', text: '17. Hüttenkäse-Ananas' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 200 kcal' }, { label: 'Eiweiß', value: '24 g' }] },
    { type: 'list', items: [`200 g Hüttenkäse`, `100 g Ananas`, `Zimt`] },
    { type: 'p', text: `Mischen. Ein süß-salziger Snack, sehr eiweißreich und kalorienarm.` },
    { type: 'h2', text: '18. Gebratene Garnelen-Reis-Zucchini' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 430 kcal' }, { label: 'Eiweiß', value: '38 g' }] },
    { type: 'list', items: [`150 g Garnelen`, `80 g Reis (roh)`, `Zucchini, Knoblauch`, `Sojasoße`] },
    { type: 'p', text: `Garnelen mit Knoblauch anbraten, Zucchini zugeben, über dem Reis servieren.` },
    { type: 'h2', text: '19. Linsen-Gemüse-Suppe' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 350 kcal' }, { label: 'Eiweiß', value: '22 g' }] },
    { type: 'list', items: [`100 g Linsen (roh)`, `Karotte, Zwiebel, Tomate`, `Kreuzkümmel, Brühe`] },
    { type: 'p', text: `25 Min. köcheln lassen. Sättigend, ballaststoffreich, perfekt am Abend.` },
    { type: 'h2', text: '24 Express-Bonusrezepte' },
    { type: 'p', text: `Wähle auch aus diesen schnellen Ideen (baue sie um deine Makros) - damit dir nie die Optionen ausgehen:` },
    { type: 'table', headers: ['Rezept', 'Typ', 'Eiweiß'], rows: [
      ['Hähnchen-Avocado-Wrap', 'Mittag', '35 g'],
      ['Gegrillte Pute-Zucchini', 'Abend', '40 g'],
      ['Quinoa-Edamame-Tofu-Bowl', 'Mittag', '30 g'],
      ['Griechischer Joghurt-Walnüsse-Honig', 'Snack', '18 g'],
      ['Haferflocken-Eiweiß-Pancake', 'Frühstück', '24 g'],
      ['Gebackene Eier-Spinat', 'Frühstück', '20 g'],
      ['Thunfisch-grüne Bohnen-Ei-Salat', 'Mittag', '36 g'],
      ['Pute-Paprika-Reis-Pfanne', 'Mittag', '40 g'],
      ['Kabeljau in Folie-Gemüse', 'Abend', '38 g'],
      ['Chili sin Carne (Tofu/Bohnen)', 'Abend', '28 g'],
      ['Magerquark-Beeren-Samen', 'Snack', '22 g'],
      ['Räucherlachs-Frischkäse-Wrap', 'Mittag', '30 g'],
      ['Buddha-Bowl Gemüse-Kichererbsen', 'Mittag', '24 g'],
      ['Rinderhack-Patty 5%-grüne Bohnen', 'Abend', '40 g'],
      ['Ei-Kartoffel-Tortilla', 'Frühstück', '26 g'],
      ['Beeren-Eiweiß-Smoothie', 'Snack', '28 g'],
      ['Teriyaki-Hähnchen-Brokkoli-Reis', 'Mittag', '42 g'],
      ['Linsen-Feta-Tomaten-Salat', 'Mittag', '24 g'],
      ['Kichererbsen-Spinat-Curry', 'Abend', '22 g'],
      ['Putenbrust-Rohkost', 'Snack', '25 g'],
      ['Gebratener Reis Ei-Gemüse-Edamame', 'Mittag', '26 g'],
      ['Kabeljau-Süßkartoffelpüree', 'Abend', '38 g'],
      ['Skyr-hausgemachtes Granola-Obst', 'Frühstück', '28 g'],
      ['Miso-Tofu-Gemüse-Suppe', 'Abend', '20 g'],
    ] },
    { type: 'note', text: `Insgesamt mehr als 40 Rezepte: kombiniere sie frei mit den Menüs für 8 Wochen ohne je Langeweile.` },

    { type: 'chapter', title: 'Batch Cooking & Organisation', src: 'seche-2.jpg', intro: `Das Geheimnis einer gelungenen Definitionsphase: nie unvorbereitet sein. Koche zweimal pro Woche in großen Mengen - du isst besser und greifst nicht zur erstbesten schnellen Option.` },
    { type: 'list', items: [
      `Sonntag & Mittwoch: koche 1 kg Eiweiß (Hähnchen, Rind, Tofu) + 500 g Beilagen (Reis, Quinoa).`,
      `Schneide und wasche dein Gemüse im Voraus, lagere es in Boxen.`,
      `Bereite 4-5 identische Portionen vor, variiere nur die Würzung (Sojasoße, Zitrone, Gewürze).`,
      `Halte immer harte Eier und Skyr im Kühlschrank gegen Heißhunger bereit.`,
      `Investiere in 4-5 luftdichte Boxen: das Werkzeug Nr. 1 der Definitionsphase.`,
    ] },

    { type: 'chapter', title: 'Vegane Version', src: 'seche-1.jpg', intro: `Die Definitionsphase funktioniert perfekt vegan: ziele einfach auf vielfältige, vollständige pflanzliche Proteine. Ersetze tierische Proteine einfach durch ihre Äquivalente.` },
    { type: 'table', headers: ['Statt…', 'Nutze…', 'Eiweiß'], rows: [
      ['Hähnchen / Rind', 'Fester Tofu, Tempeh, Seitan', '15-25 g/100 g'],
      ['Eier', 'Rührtofu, Kichererbsen', '8-19 g'],
      ['Skyr / Magerquark', 'Natur-Sojajoghurt', '6-10 g'],
      ['Whey', 'Erbsen- / Reisprotein', '20-25 g/Portion'],
      ['Thunfisch / Fisch', 'Kichererbsen, Linsen, Edamame', '9-20 g'],
    ] },
    { type: 'list', items: [
      `Ziele auf Vielfalt: kombiniere Getreide + Hülsenfrüchte für vollständige Proteine.`,
      `Ergänze B12 (vegan unverzichtbar) und achte auf dein Eisen.`,
      `Hülsenfrüchte liefern auch sättigende Ballaststoffe - ideal in der Definitionsphase.`,
    ] },

    { type: 'h1', text: 'Tipps für den Erfolg' },
    { type: 'list', items: [
      `Bereite deine Mahlzeiten im Voraus vor (Batch Cooking) 2× pro Woche.`,
      `Trinke ein großes Glas Wasser bei Heißhunger: man verwechselt oft Durst mit Hunger.`,
      `Halte Eiweißsnacks griffbereit (Skyr, hartes Ei, Putenbrust).`,
      `Schlafe 7-8 h: Schlafmangel steigert den Hunger und bremst den Fettabbau.`,
      `Mach mit dem Krafttraining weiter: es bewahrt deinen Muskel im Defizit.`,
    ] },

    { type: 'h1', text: 'Zu vermeidende Fehler' },
    { type: 'list', items: [
      `Zu aggressives Defizit: du verlierst Muskel, deine Energie bricht ein, du brichst ein.`,
      `Eiweiß auslassen: Priorität Nr. 1 in der Definitionsphase.`,
      `Kohlenhydrate völlig streichen: du verlierst Energie und Leistung.`,
      `Dich täglich wiegen: das Gewicht schwankt, schau auf den 2-Wochen-Trend.`,
      `Alkohol und Soßen vergessen: versteckte Kalorien, die das Defizit blockieren.`,
    ] },
    { type: 'h2', text: 'Problem → Lösung' },
    { type: 'table', headers: ['Du erlebst…', 'Die Lösung'], rows: [
      ['Die Waage stagniert 2 Wochen', '100-150 kcal abziehen (Kohlenhydrate abends)'],
      ['Ständiger Hunger', 'Mehr Eiweiß + Gemüse + Wasser'],
      ['Energiemangel', 'Kohlenhydrate rund ums Training behalten'],
      ['Süßlust am Abend', 'Skyr + Beeren oder geplante Genuss-Mahlzeit'],
    ] },

    { type: 'h1', text: 'Häufige Fragen' },
    { type: 'h2', text: 'Wie lange bis zu Ergebnissen?' },
    { type: 'p', text: `Ab 2-3 Wochen für die ersten Veränderungen (davon ein Teil Wasser in der 1. Woche). Sichtbare Definition zeigt sich zwischen 4 und 8 Wochen je nach Ausgangslage.` },
    { type: 'h2', text: 'Muss ich Kalorien zählen?' },
    { type: 'p', text: `Am Anfang ist es nützlich zum Kalibrieren. Danach reichen die Menüs und Portionsrichtwerte. Wichtig ist die Konstanz des Defizits über die Woche.` },
    { type: 'h2', text: 'Kann ich diesen Plan ohne Training befolgen?' },
    { type: 'p', text: `Du wirst Gewicht verlieren, aber ein Teil davon ist Muskel. Für eine echte Definition (Fett verlieren und fit bleiben) behalte mindestens 2-3 Krafteinheiten pro Woche.` },
    { type: 'h2', text: 'Verdirbt die Genuss-Mahlzeit alles?' },
    { type: 'p', text: `Nein: 1 Mahlzeit von 21 lässt ein wöchentliches Defizit bestehen. Sie bewahrt deine Motivation und dein Sozialleben - die echten Abbruchgründe.` },
    { type: 'h2', text: 'Und nach den 8 Wochen?' },
    { type: 'p', text: `Erhöhe deine Kalorien schrittweise zurück zum Erhalt (+100 kcal/Woche), um den Jo-Jo-Effekt zu vermeiden, dann stabilisiere oder gehe in eine Masseaufbauphase.` },

    { type: 'h1', text: 'Auswärts essen & Unerwartetes meistern' },
    { type: 'p', text: `Eine Definitionsphase soll dich nicht vom Leben abhalten. Mit ein paar Reflexen bleibst du auf Kurs, auch im Restaurant oder unterwegs.` },
    { type: 'list', items: [
      `Im Restaurant: wähle ein mageres Eiweiß (gegrilltes Fleisch, Fisch) + Gemüse, Soße separat.`,
      `Vermeide den flüssigen Aperitif (Alkohol, Limos): ersetze durch Sprudelwasser mit Zitrone.`,
      `Fast Food: nimm gegrillte Optionen, Salat, und lass Pommes/süße Soßen weg.`,
      `Unterwegs: halte Eiweißriegel, Skyr oder harte Eier bei dir.`,
      `Ein „außerplanmäßiger" Tag bricht nichts: mach einfach bei der nächsten Mahlzeit weiter.`,
    ] },
    { type: 'table', headers: ['Situation', 'Guter Reflex'], rows: [
      ['Restaurant', 'Gegrilltes Eiweiß + Gemüse, Soße separat'],
      ['Pizza/Burger', 'Einfache Version, kein XL-Menü, Wasser'],
      ['Aperitif', 'Rohkost, Sprudelwasser, max. 1 Glas'],
      ['Brunch', 'Eier, Magerquark, Obst, Vollkornbrot'],
    ] },

    { type: 'h1', text: 'Nützliche Ergänzungen in der Definitionsphase' },
    { type: 'p', text: `Keine ist Pflicht - die Ernährung kommt zuerst. Aber einige helfen, das Defizit zu halten und den Muskel zu bewahren.` },
    { type: 'table', headers: ['Ergänzung', 'Nutzen in der Definition', 'Dosis'], rows: [
      ['Whey / Iso', 'Eiweiß mit wenig Kalorien erreichen', '1 bis 2 Portionen/Tag'],
      ['Kreatin', 'Krafterhalt im Defizit', '3 bis 5 g/Tag'],
      ['Kaffee / Koffein', 'Appetitzügler und Energie', 'In Maßen'],
      ['Flohsamen / Ballaststoffe', 'Sättigung und Verdauung', 'Nach Bedarf'],
      ['Multivitamine', 'Eventuelle Defizite ausgleichen', '1/Tag (Option)'],
    ] },
    { type: 'note', text: `Vorsicht bei Wunder-„Fatburnern": keiner ersetzt das Kaloriendefizit. Spar dein Geld für gutes Essen.` },

    { type: 'h1', text: 'Tracking deiner Definitionsphase' },
    { type: 'p', text: `Miss dich jede Woche, nüchtern, unter gleichen Bedingungen. Foto und Taillenumfang sind oft aussagekräftiger als die Waage.` },
    { type: 'h2', text: 'Gewicht & Maße' },
    { type: 'tracker', columns: ['Datum', 'Gewicht (kg)', 'Taille (cm)', 'Energie /10'], rows: 9 },
    { type: 'h2', text: 'Zufuhr (optional)' },
    { type: 'tracker', columns: ['Datum', 'Kalorien', 'Eiweiß (g)', 'Wasser (L)'], rows: 7 },

    { type: 'h1', text: 'Wöchentliche Checkliste' },
    { type: 'p', text: `Hake jedes Kästchen am Ende der Woche ab. Ziel: mindestens 6 von 8.` },
    { type: 'checklist', items: [
      `Ich habe mein Kaloriendefizit an den meisten Tagen eingehalten.`,
      `Ich habe mein Eiweiß jeden Tag erreicht.`,
      `Ich habe bei jeder Hauptmahlzeit Gemüse gegessen.`,
      `Ich habe 2 L Wasser pro Tag getrunken.`,
      `Ich habe flüssigen Zucker und Alkohol begrenzt.`,
      `Ich habe meine Krafteinheiten beibehalten.`,
      `Ich habe mich 1× gewogen, unter gleichen Bedingungen.`,
      `Ich habe meine Mahlzeiten im Voraus vorbereitet.`,
    ] },

    { type: 'h1', text: 'Persönliche Notizen' },
    { type: 'tracker', columns: ['Meine Lieblingsgerichte, Empfindungen und Anpassungen der Woche'], rows: 16 },

    { type: 'note', text: `8 Wochen Definitionsphase geschafft? Erhöhe deine Kalorien sanft, behalte deine guten Gewohnheiten, dann gehe in einen sauberen Masseaufbau oder in den Erhalt. Erstelle dein Konto auf xenotif.com für dein Tracking und deinen KI-Coach.` },
  ],
}
