import type { Guide } from '@/lib/boutique/guides'

// Masseaufbau-Programm - 12 Wochen (DE-Mirror von prise-de-masse-12s.ts).
// Gleiche Struktur; nur die Texte sind übersetzt. ≈ 30 Seiten.
export const priseDeMasse12sDe: Guide = {
  id: 'd1',
  title: 'Masseaufbau-Programm - 12 Wochen',
  subtitle: '4-Tage-Split, geführte Lastprogression, Ernährungsplan + Makros',
  author: 'XENOTIF Coach - Zertifiziertes Kraft- & Ernährungscoaching',
  level: 'Anfänger - Fortgeschrittene',
  duration: '12 Wochen · 4 Einheiten/Woche · 84 Einheiten',
  coverImage: 'masse-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Willkommen zu deinem Masseaufbau' },
    { type: 'p', text: `12 Wochen, um deinen Körper umzubauen: mehr Muskeln, mehr Kraft, eine dichtere Silhouette. Kein „schmutziger" Masseaufbau, der dich nur aufschwemmt - hier baust du Qualitätsmuskeln über drei Hebel auf: einen leichten Kalorienüberschuss, progressive Überlastung im Training und sorgfältige Erholung.` },
    { type: 'p', text: `Behalte diesen Leitfaden auf deinem Handy: Jede Übung hat einen QR-Code, der ihr Demovideo öffnet. Folge dem Plan, notiere deine Lasten, iss genug - und der Muskel folgt.` },
    { type: 'meta', items: [
      { label: 'Ziel', value: '2 bis 5 kg Muskeln aufbauen' },
      { label: 'Niveau', value: 'Anfänger bis Fortgeschrittene' },
      { label: 'Dauer', value: '12 Wochen (3 Phasen)' },
      { label: 'Häufigkeit', value: '4 Einheiten pro Woche' },
      { label: 'Ausrüstung', value: 'Studio oder Kurzhanteln + Langhantel' },
      { label: 'Split', value: 'Oberkörper / Unterkörper (4 Tage)' },
    ] },
    { type: 'h2', text: 'Ziele des Programms' },
    { type: 'list', items: [
      `2 bis 5 kg Muskeln in 12 Wochen aufbauen (je nach Ausgangslage).`,
      `Deutlich an Kraft bei den Grundübungen gewinnen.`,
      `Deine Haltung verbessern und deine Silhouette verdichten.`,
      `Eine Trainings- und Ernährungsmethode lernen, die du fürs Leben behältst.`,
    ] },
    { type: 'h2', text: 'So nutzt du diesen Leitfaden' },
    { type: 'list', items: [
      `Lies den Leitfaden ganz durch, bevor du startest, folge dann dem 12-Wochen-Kalender.`,
      `Notiere deine Lasten in jeder Einheit: Fortschritt wird gesteuert, nicht improvisiert.`,
      `Wärme dich 5-10 Min. vor jeder Einheit auf (eigene Seite).`,
      `Scanne den QR-Code einer Übung, um die Technik im Video zu sehen.`,
      `Wiege dich 1× pro Woche und fülle sonntags dein Tracking aus.`,
    ] },
    { type: 'note', text: `Goldene Regel: kein Muskel ohne Kalorienüberschuss UND progressive Überlastung. Mehr essen ohne hartes Training = Fett. Hart trainieren ohne genug zu essen = kein Fortschritt. Beides zusammen = Muskeln.` },

    { type: 'h1', text: 'So funktioniert es' },
    { type: 'list', items: [
      `Moderater Kalorienüberschuss: iss 200 bis 400 kcal über deinem Erhalt.`,
      `Progressive Überlastung: steigere fast jede Woche Last oder Wiederholungen.`,
      `Sätze × Wiederholungen: „4 × 8" = 4 Sätze à 8 Wiederholungen.`,
      `Tempo: 2 s in der Abwärtsphase (exzentrisch), 1 s in der Aufwärtsphase.`,
      `Pause: 90 bis 120 s bei den großen Übungen, 60 s bei Isolation.`,
      `RPE 8: behalte ~2 Wiederholungen in Reserve, sofern nicht anders angegeben.`,
    ] },
    { type: 'h2', text: 'Progressive Überlastung, erklärt' },
    { type: 'p', text: `Ein Muskel wächst, wenn man mehr von ihm verlangt, als er gewohnt ist. Konkret: Ziele jede Woche auf +1 bis 2 Wiederholungen pro Satz oder +2,5 kg, sobald du das obere Ende des Wiederholungsbereichs erreichst. Führe ein Logbuch: nur so schlägst du die Werte der Vorwoche.` },

    { type: 'h1', text: 'Aufwärmen & Mobilität' },
    { type: 'p', text: `Ein gutes Aufwärmen steigert deine Leistung und schützt deine Gelenke unter Last. Lass es nie aus, besonders vor schweren Übungen.` },
    { type: 'h2', text: 'Typisches Aufwärmen (8 Minuten)' },
    { type: 'table', headers: ['Schritt', 'Detail', 'Dauer'], rows: [
      ['Leichtes Cardio', 'Rad / Seil / zügiges Gehen', '3 Min.'],
      ['Mobilität', 'Schultern, Hüften, Sprunggelenke', '2 Min.'],
      ['Aktivierung', 'Core + Band (Rücken/Schultern)', '2 Min.'],
      ['Aufbausätze', '2 leichte Sätze der 1. Übung', '1 Min.'],
    ] },

    { type: 'chapter', title: 'Ernährungsplan Masseaufbau', src: 'seche-1.jpg' },
    { type: 'p', text: `Muskeln werden mit einem moderaten Kalorienüberschuss und viel Eiweiß aufgebaut. Das Ziel: Muskeln aufbauen und dabei Fett begrenzen. Besser +0,25 kg/Woche sauber als +1 kg schmutzig.` },
    { type: 'meta', items: [
      { label: 'Zielüberschuss', value: '200 bis 400 kcal / Tag' },
      { label: 'Eiweiß', value: '1,8 bis 2,2 g pro kg' },
      { label: 'Kohlenhydrate', value: 'Hoch (Energie & Volumen)' },
      { label: 'Gewichtszunahme', value: '0,2 bis 0,4 kg / Woche' },
    ] },
    { type: 'h2', text: 'Die 5 goldenen Regeln' },
    { type: 'list', items: [
      `Eiweiß bei jeder Mahlzeit (1,8-2,2 g/kg/Tag): der Baustein des Muskels.`,
      `Großzügig Kohlenhydrate rund ums Training (Reis, Nudeln, Süßkartoffel, Haferflocken).`,
      `3 bis 5 Mahlzeiten pro Tag, um deine Kalorien ohne Völlerei zu erreichen.`,
      `Bevorzuge energiedichte Lebensmittel, wenn du schwer genug isst (Nüsse, Erdnussmus, Haferflocken, Olivenöl).`,
      `Beobachte Spiegel und Waage: steigt das Fett zu schnell, reduziere den Überschuss.`,
    ] },
    { type: 'h2', text: 'Wie viel essen?' },
    { type: 'p', text: `Schnellschätzung deines Erhalts: Gewicht (kg) × ca. 33 (wenn du aktiv bist). Beispiel für 70 kg: ≈ 2 300 kcal. Ziele dann auf 2 500 bis 2 700 kcal/Tag. Passe nach 2 Wochen an: keine Zunahme → +150 kcal; zu schnelle Zunahme (> 0,5 kg/Woche) → −150 kcal.` },
    { type: 'h2', text: 'Beispieltag (≈ 2 600 kcal)' },
    { type: 'table', headers: ['Mahlzeit', 'Beispiel', 'Eiweiß'], rows: [
      ['Frühstück', 'Haferflocken + Milch + Banane + Erdnussmus + Whey', '45 g'],
      ['Mittag', 'Mageres Rind + Reis + Gemüse + Olivenöl', '45 g'],
      ['Snack', 'Skyr + Obst + Mandeln', '25 g'],
      ['Nach dem Training', 'Hähnchen + Nudeln + Tomatensoße', '45 g'],
      ['Gesamt', '≈ 2 600 kcal · moderater Überschuss', '≈ 160 g'],
    ] },
    { type: 'h2', text: 'Einkaufsliste' },
    { type: 'list', items: [
      `Eiweiß: mageres Rind, Hähnchen, Pute, Eier, Fisch, Skyr, Whey.`,
      `Kohlenhydrate: Reis, Vollkornnudeln, Süßkartoffel, Haferflocken, Vollkornbrot.`,
      `Fette: Olivenöl, Avocado, Mandeln, Erdnussmus.`,
      `Gemüse & Obst: Brokkoli, Spinat, Paprika, Banane, Beeren.`,
    ] },
    { type: 'note', text: `Schaffst du es nicht, genug zu essen? Trink deine Kalorien: ein Shake aus Haferflocken + Milch + Banane + Whey + Erdnussmus = locker 600-700 kcal zwischen zwei Mahlzeiten.` },
    { type: 'h2', text: 'Deine Makros verstehen' },
    { type: 'p', text: `Du musst nicht alles abwiegen, aber die Rolle jedes Makronährstoffs zu verstehen hilft dir, bessere Masseaufbau-Teller zusammenzustellen.` },
    { type: 'table', headers: ['Makro', 'Rolle', 'Pro g', 'Priorität bei Masse'], rows: [
      ['Eiweiß', 'Baut Muskeln auf', '4 kcal', 'HOCH - 1,8-2,2 g/kg'],
      ['Kohlenhydrate', 'Energie & Muskelvolumen', '4 kcal', 'HOCH - rund ums Training'],
      ['Fette', 'Hormone (Testosteron)', '9 kcal', 'Moderat - 0,8-1 g/kg'],
    ] },
    { type: 'list', items: [
      `Eiweiß: der Baustein. Ohne ihn kein Aufbau, egal was sonst.`,
      `Kohlenhydrate: dein Trainingsbrennstoff und das „Volumen" des Muskels (Glykogen).`,
      `Fette: geh nie zu niedrig, sie stützen deine anabolen Hormone.`,
    ] },

    { type: 'h1', text: 'Rezepte für den Masseaufbau' },
    { type: 'h2', text: 'Hausgemachter Masseaufbau-Shake' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 650 kcal' }, { label: 'Eiweiß', value: '45 g' }] },
    { type: 'list', items: [`300 ml Milch`, `60 g Haferflocken`, `1 Banane`, `1 Portion Whey`, `1 EL Erdnussmus`] },
    { type: 'p', text: `Zubereitung: alles 30 Sekunden mixen. Ideal zum Frühstück oder nach dem Training.` },
    { type: 'h2', text: 'Rind-Reis-Bowl nach dem Training' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 700 kcal' }, { label: 'Eiweiß', value: '50 g' }] },
    { type: 'list', items: [`150 g Rinderhack 5%`, `120 g Reis (roh)`, `Gemüse nach Wahl`, `Sojasoße, Gewürze`] },
    { type: 'p', text: `Zubereitung: Rind anbraten, Gemüse zugeben, über dem Reis servieren. Reichhaltig, einfach, perfekt nach der Einheit.` },
    { type: 'h2', text: 'Eiweiß-Porridge am Morgen' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 550 kcal' }, { label: 'Eiweiß', value: '38 g' }] },
    { type: 'list', items: [`80 g Haferflocken`, `300 ml Milch`, `1 Portion Vanille-Whey`, `1 EL Honig + Beeren`] },
    { type: 'p', text: `Zubereitung: Haferflocken 3 Min. in der Milch erhitzen, vom Herd nehmen, Whey, Honig und Obst unterrühren. Champions-Frühstück.` },
    { type: 'h2', text: 'Kräftiges Omelett + Süßkartoffel' },
    { type: 'meta', items: [{ label: 'Kalorien', value: '≈ 600 kcal' }, { label: 'Eiweiß', value: '42 g' }] },
    { type: 'list', items: [`4 Eier + 2 Eiweiß`, `200 g Süßkartoffel`, `Spinat, Käse`, `Olivenöl`] },
    { type: 'p', text: `Zubereitung: Süßkartoffel im Ofen/in der Mikrowelle garen, Omelett mit Spinat und Käse zubereiten. Vollständige, sättigende Mahlzeit.` },

    { type: 'chapter', title: 'Erholung', src: 'recovery.jpg' },
    { type: 'list', items: [
      `Schlafe 7 bis 9 h: im Schlaf ist die Muskelproteinsynthese am höchsten.`,
      `Lass einem Muskel 48 h, bevor du ihn erneut belastest (daher der Oberkörper/Unterkörper-Split).`,
      `Trinke (3 L/Tag): Muskel besteht zu ~75 % aus Wasser.`,
      `Eine „Deload"-Woche (Lasten −40 %) alle 6 Wochen beugt Stagnation vor.`,
    ] },

    { type: 'chapter', title: '12-Wochen-Plan (3 Phasen)', src: 'masse-1.jpg' },
    { type: 'p', text: `Das Programm schreitet in 3 Phasen voran. Halte die Reihenfolge ein: erst Volumen, dann Intensität.` },
    { type: 'table', headers: ['Phase', 'Wochen', 'Fokus', 'Wdh.'], rows: [
      ['Phase 1', 'W1 bis W4', 'Anpassung & Volumen', '12 bis 15'],
      ['Phase 2', 'W5 bis W8', 'Hypertrophie', '8 bis 12'],
      ['Phase 3', 'W9 bis W12', 'Kraft & Dichte', '6 bis 8'],
    ] },
    { type: 'h2', text: 'Beispielwoche (Oberkörper / Unterkörper-Split)' },
    { type: 'table', headers: ['Tag', 'Einheit', 'Fokus'], rows: [
      ['Montag', 'Oberkörper A', 'Brust, Rücken, Schultern, Arme'],
      ['Dienstag', 'Unterkörper A', 'Quadrizeps, Gesäß, Waden'],
      ['Mittwoch', 'Pause / leichtes Cardio', 'Erholung'],
      ['Donnerstag', 'Oberkörper B', 'Rücken, Brust, Arme'],
      ['Freitag', 'Unterkörper B', 'Beinbeuger, Gesäß, Core'],
      ['Wochenende', 'Pause + Tracking', 'Erholung'],
    ] },

    { type: 'h1', text: 'Deine Einheiten im Detail' },
    { type: 'h2', text: 'Oberkörper A' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wdh.', 'Pause'], rows: [
      ['Bankdrücken (oder Liegestütze mit Last)', '4', '8 bis 10', '120 s'],
      ['Rudern horizontal', '4', '10', '90 s'],
      ['Schulterdrücken', '3', '10', '90 s'],
      ['Latzug', '3', '12', '75 s'],
      ['Bizepscurl', '3', '12', '60 s'],
      ['Trizepsstrecken', '3', '12', '60 s'],
    ] },
    { type: 'h2', text: 'Unterkörper A' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wdh.', 'Pause'], rows: [
      ['Kniebeuge', '4', '8 bis 10', '120 s'],
      ['Beinpresse (oder Ausfallschritte)', '4', '12', '90 s'],
      ['Rumänisches Kreuzheben', '3', '10', '90 s'],
      ['Beinbeuger (oder Hüftheben mit Last)', '3', '12', '75 s'],
      ['Wadenheben stehend', '4', '15', '45 s'],
    ] },
    { type: 'h2', text: 'Oberkörper B' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wdh.', 'Pause'], rows: [
      ['Klimmzüge (oder Latzug)', '4', '8 bis 10', '120 s'],
      ['Schrägbankdrücken Kurzhantel', '4', '10', '90 s'],
      ['Einarmiges Kurzhantelrudern', '3', '12', '75 s'],
      ['Seitheben', '3', '15', '60 s'],
      ['Hammercurl', '3', '12', '60 s'],
      ['Dips (oder Trizepsstrecken)', '3', '10', '60 s'],
    ] },
    { type: 'h2', text: 'Unterkörper B' },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wdh.', 'Pause'], rows: [
      ['Kreuzheben (oder Hip Thrust)', '4', '6 bis 8', '120 s'],
      ['Gehende Ausfallschritte Kurzhantel', '3', '12 / Bein', '90 s'],
      ['Beinstrecker (oder Bulgarische Kniebeuge)', '3', '15', '75 s'],
      ['Hüftheben mit Last', '3', '12', '75 s'],
      ['Plank + Side-Plank', '3', '40 s', '45 s'],
    ] },

    { type: 'h1', text: '12-Wochen-Kalender' },
    { type: 'p', text: `Drei progressive Phasen. Behalte jede Woche denselben Oberkörper/Unterkörper-Split, aber entwickle Wiederholungen und Lasten je nach Phase.` },
    { type: 'h2', text: 'Phase 1 - Anpassung & Volumen (W1 bis W4)' },
    { type: 'table', headers: ['Woche', 'Wdh.', 'Intensität', 'Hinweis'], rows: [
      ['W1', '12 bis 15', 'RPE 7', 'Technik zuerst'],
      ['W2', '12 bis 15', 'RPE 7-8', '+1 Wdh. / Satz'],
      ['W3', '12 bis 15', 'RPE 8', '+ leichte Last'],
      ['W4', '12 bis 15', 'RPE 8', 'Schlag deine W1-Werte'],
    ] },
    { type: 'h2', text: 'Phase 2 - Hypertrophie (W5 bis W8)' },
    { type: 'table', headers: ['Woche', 'Wdh.', 'Intensität', 'Hinweis'], rows: [
      ['W5', '8 bis 12', 'RPE 8', 'Lasten erhöhen'],
      ['W6', '8 bis 12', 'RPE 8', 'Leichter Deload am Wochenende'],
      ['W7', '8 bis 12', 'RPE 8-9', '+ Last'],
      ['W8', '8 bis 12', 'RPE 9', 'Sätze nah am Versagen'],
    ] },
    { type: 'h2', text: 'Phase 3 - Kraft & Dichte (W9 bis W12)' },
    { type: 'table', headers: ['Woche', 'Wdh.', 'Intensität', 'Hinweis'], rows: [
      ['W9', '6 bis 8', 'RPE 8', 'Schwere Lasten, lange Pausen'],
      ['W10', '6 bis 8', 'RPE 8-9', '+ Last'],
      ['W11', '6 bis 8', 'RPE 9', 'Intensitätsspitze'],
      ['W12', '6 bis 8 dann Deload', 'Variabel', 'Bilanz + Fotos + Maße'],
    ] },

    { type: 'h1', text: 'Variante: Ganzkörper 3 Tage' },
    { type: 'p', text: `Du kannst nicht 4× pro Woche trainieren? Ersetze den Oberkörper/Unterkörper-Split durch dieses Ganzkörperschema an 3 Tagen (Mo / Mi / Fr). Jede Einheit trainiert den ganzen Körper: sehr effektiv für Anfänger und volle Terminkalender.` },
    { type: 'table', headers: ['Übung', 'Sätze', 'Wdh.', 'Pause'], rows: [
      ['Kniebeuge', '4', '8 bis 10', '120 s'],
      ['Bankdrücken (oder Liegestütze)', '4', '8 bis 10', '120 s'],
      ['Rudern / Latzug', '4', '10', '90 s'],
      ['Schulterdrücken', '3', '10', '90 s'],
      ['Rumänisches Kreuzheben', '3', '10', '90 s'],
      ['Core + Curl/Strecken', '3', '12', '60 s'],
    ] },
    { type: 'note', text: `Beim Ganzkörper variiere die Übungen leicht über die 3 Einheiten (z. B. Kniebeuge Montag, Ausfallschritte Mittwoch, Beinpresse Freitag), um die Reize zu variieren.` },

    { type: 'h1', text: 'Übungsbibliothek' },
    { type: 'p', text: `Beherrsche diese Grundbewegungen: sie bauen den Großteil deiner Masse auf. Scanne den QR-Code für das Demovideo.` },
    { type: 'exercise', name: 'Kniebeuge', muscles: 'Quadrizeps, Gesäß, Beinbeuger, Core', level: 'Fortgeschritten', technique: `Hantel auf dem oberen Rücken, Füße schulterbreit. Senke dich, indem du das Gesäß nach hinten schiebst, Core fest, bis die Oberschenkel parallel sind, dann drücke über die Fersen hoch.`, mistakes: `Knie kippen nach innen, Fersen heben ab, Rücken rundet. Halte die Brust stolz und das Gewicht in den Fersen.` },
    { type: 'exercise', name: 'Bankdrücken', muscles: 'Brust, Trizeps, Schultern', level: 'Fortgeschritten', technique: `Auf der Bank liegend, Schulterblätter zusammen, leichtes Hohlkreuz. Senke die Hantel zur unteren Brust, Ellbogen ~45°, dann drücke und halte die Füße verankert.`, mistakes: `Ellbogen zu weit abgespreizt, Abprallen an der Brust, Gesäß hebt ab. Kontrolliere das Absenken.` },
    { type: 'exercise', name: 'Rumänisches Kreuzheben', muscles: 'Beinbeuger, Gesäß, Rücken', level: 'Fortgeschritten', technique: `Hantel vor den Oberschenkeln, flacher Rücken. Senke die Hantel entlang der Beine, indem du die Hüften nach hinten schiebst, leichte Kniebeugung, bis du die Dehnung der Beinbeuger spürst, dann zurück durch Anspannen des Gesäßes.`, mistakes: `Runder Rücken, Hantel entfernt sich vom Körper, zu starke Kniebeugung (es wird zur Kniebeuge).` },
    { type: 'exercise', name: 'Langhantelrudern', muscles: 'Rücken, Bizeps, hintere Schulter', level: 'Fortgeschritten', technique: `Oberkörper ~45° vorgebeugt, flacher Rücken. Ziehe die Hantel zum Unterbauch, indem du die Schulterblätter zusammenziehst, dann langsam ablassen. Die Bewegung kommt aus dem Rücken, nicht aus den Armen.`, mistakes: `Runder Rücken, Oberkörper richtet sich bei jeder Wiederholung auf, zu hoch zur Brust ziehen.` },
    { type: 'exercise', name: 'Schulterdrücken', muscles: 'Schultern, Trizeps, Core', level: 'Fortgeschritten', technique: `Stehend, Hantel auf Schlüsselbeinhöhe, Core fest. Drücke die Hantel über den Kopf, ohne den unteren Rücken zu überstrecken, dann kontrolliert ablassen.`, mistakes: `Übermäßiges Hohlkreuz, nach vorne statt senkrecht drücken, unvollständiger Endpunkt.` },
    { type: 'exercise', name: 'Latzug', muscles: 'Latissimus, Bizeps', level: 'Anfänger', technique: `Sitzend, weiter Griff. Ziehe die Stange zur oberen Brust, indem du die Schultern senkst und den Rücken anspannst, dann kontrolliert zurück mit Spannung.`, mistakes: `Nach hinten schwingen, hinter den Nacken ziehen, oben loslassen.` },
    { type: 'exercise', name: 'Ausfallschritte Kurzhantel', muscles: 'Quadrizeps, Gesäß, Gleichgewicht', level: 'Anfänger', technique: `Kurzhanteln in der Hand, großer Schritt nach vorne, hinteres Knie zum Boden, Oberkörper aufrecht. Drücke über die vordere Ferse zurück. Beine abwechseln.`, mistakes: `Zu kurzer Schritt, vorgebeugter Oberkörper, Knie kippt nach innen.` },
    { type: 'exercise', name: 'Bizepscurl', muscles: 'Bizeps', level: 'Anfänger', technique: `Ellbogen am Körper, hebe die Kurzhanteln durch Anspannen des Bizeps, dann langsam ablassen (2 s). Kein Schwung.`, mistakes: `Mit dem Körper schwingen, Ellbogen wandern nach vorne, zu schnelles Ablassen.` },
    { type: 'exercise', name: 'Trizepsstrecken', muscles: 'Trizeps', level: 'Anfänger', technique: `Am Kabel oder mit Kurzhantel, Ellbogen fixiert, strecke den Unterarm vollständig und kehre kontrolliert zurück. Nur der Unterarm bewegt sich.`, mistakes: `Ellbogen spreizen, unvollständiger Bewegungsumfang, Schwung aus dem Oberkörper.` },
    { type: 'exercise', name: 'Plank', muscles: 'Bauchmuskulatur, unterer Rücken', level: 'Anfänger', technique: `Auf Unterarmen und Fußspitzen, Körper in einer Linie, Bauch und Gesäß angespannt. Halte die Position bei ruhiger Atmung.`, mistakes: `Hüften sacken ab, Gesäß zu hoch, Kopf angehoben.` },

    { type: 'h1', text: 'Empfohlene Progression' },
    { type: 'p', text: `Progressive Überlastung ist der Motor des Masseaufbaus. So gehst du voran, ohne dich zu verletzen.` },
    { type: 'table', headers: ['Phase', 'Ziel', 'Wie fortschreiten'], rows: [
      ['W1-W4', 'Lernen & Volumen vertragen', '+1-2 Wdh./Woche'],
      ['W5-W8', 'Hypertrophie maximieren', '+2,5 kg am oberen Ende'],
      ['W9-W12', 'Kraft aufbauen', 'Schwerere Lasten, weniger Wdh.'],
    ] },
    { type: 'list', items: [
      `Erreichst du das obere Ende des Wiederholungsbereichs in allen Sätzen, füge Gewicht hinzu.`,
      `Notiere jede Einheit: Last × Wiederholungen. Schlage diese Zahl beim nächsten Mal.`,
      `Deload alle 6 Wochen: Volumen −40 % für eine Woche, dann stärker zurück.`,
    ] },

    { type: 'h1', text: 'Zu vermeidende Fehler' },
    { type: 'list', items: [
      `Zu viel essen („Dirty Bulk"): du gewinnst vor allem Fett, das du wieder verlieren musst.`,
      `Alle 2 Wochen das Programm wechseln: Muskel braucht Konstanz.`,
      `Beine vernachlässigen: ein Körper wird auch (vor allem) von unten aufgebaut.`,
      `Ego-Lifting: zu schwer, Technik verschlechtert sich → garantierte Verletzung.`,
      `Eiweiß oder Schlaf auslassen: kein Aufbau ohne Material und Ruhe.`,
    ] },
    { type: 'h2', text: 'Problem → Lösung' },
    { type: 'table', headers: ['Du erlebst…', 'Die Lösung'], rows: [
      ['Du nimmst nicht zu', '+150-200 kcal/Tag, Shake ergänzen'],
      ['Du nimmst zu viel Fett zu', 'Überschuss senken, Eiweiß hoch halten'],
      ['Du stagnierst bei der Kraft', 'Deload 1 Woche, Schlaf & Kalorien prüfen'],
      ['Gelenkschmerzen', 'Last reduzieren, Technik prüfen (Video scannen)'],
    ] },

    { type: 'h1', text: 'Motiviert bleiben' },
    { type: 'list', items: [
      `Fotografiere dich alle 4 Wochen: Masse sieht man besser, als man sie fühlt.`,
      `Setze dir Kraftziele (z. B. „Kniebeuge mit 1× Körpergewicht").`,
      `Umgib dich: ein Trainingspartner steigert Intensität und Verbindlichkeit.`,
      `Sei geduldig: 2 bis 5 kg Muskeln in 12 Wochen sind ein ausgezeichnetes Ergebnis.`,
    ] },
    { type: 'h2', text: 'Baue die Gewohnheit auf' },
    { type: 'list', items: [
      `Blockiere deine 4 Trainingstermine im Kalender wie Verabredungen.`,
      `Bereite Tasche und Mahlzeiten am Vorabend vor: null Reibung am Tag X.`,
      `Brich die Kette nie zwei Einheiten hintereinander.`,
    ] },

    { type: 'h1', text: 'Häufige Fragen' },
    { type: 'h2', text: 'Ich bin Anfänger, ist dieses Programm für mich?' },
    { type: 'p', text: `Ja. Beginne leicht, um die Technik zu beherrschen (nutze bei Bedarf die Körpergewichtsvarianten), dann steigere die Last allmählich. Anfänger machen in den ersten Monaten sehr schnell Fortschritte.` },
    { type: 'h2', text: 'Werde ich Fett zunehmen?' },
    { type: 'p', text: `Etwas - das ist normal und nötig, um Muskeln aufzubauen. Mit moderatem Überschuss (200-400 kcal) und viel Eiweiß bleibt die Zunahme überwiegend muskulär.` },
    { type: 'h2', text: 'Kann ich es zu Hause machen?' },
    { type: 'p', text: `Ja, mit verstellbaren Kurzhanteln und einer Langhantel. Sonst ersetze durch die Körpergewichtsvarianten (Liegestütze mit Last, Ausfallschritte, Klimmzüge, Dips) und ziele auf sauberes Versagen.` },
    { type: 'h2', text: 'Brauche ich Nahrungsergänzung?' },
    { type: 'p', text: `Keine ist Pflicht. Die nützlichsten: Whey (um dein Eiweiß zu erreichen), Kreatin-Monohydrat (3-5 g/Tag, das am besten untersuchte Mittel für Kraft und Volumen).` },
    { type: 'h2', text: 'Wie viel Cardio?' },
    { type: 'p', text: `Etwas (2 × 20 Min. leicht/Woche) für die Gesundheit und um Fett fernzuhalten, ohne Übermaß, damit du deine Aufbau-Kalorien nicht verbrennst.` },
    { type: 'h2', text: 'Muss ich bis zum Versagen gehen?' },
    { type: 'p', text: `Nicht in jedem Satz: behalte in den meisten Sätzen 1 bis 2 Wiederholungen in Reserve (RPE 8). Hebe das Versagen für den letzten Satz einer Isolationsübung auf. Ständig bis zum Versagen zu gehen ermüdet das Nervensystem und bremst die Erholung.` },
    { type: 'h2', text: 'Was, wenn ich eine Einheit verpasse?' },
    { type: 'p', text: `Mach einfach bei der nächsten geplanten Einheit weiter, versuche nicht, alles nachzuholen. Über 12 Wochen ändert eine verpasste Einheit nichts - das Aufgeben schon.` },
    { type: 'h2', text: 'Ich bin „Hardgainer", ich nehme nicht zu. Was tun?' },
    { type: 'p', text: `In 95 % der Fälle isst du weniger, als du denkst. Erhöhe die Portionen, ergänze einen flüssigen Shake zwischen den Mahlzeiten und wiege dich: bewegt sich die Waage über 2 Wochen nicht, füge 200 kcal hinzu.` },

    { type: 'h1', text: 'Schlaf, Stress & Hormone' },
    { type: 'p', text: `Muskelaufbau entscheidet sich nicht nur im Studio: deine Hormone (Testosteron, Wachstumshormon) und deine Erholung hängen stark von Schlaf und Stressmanagement ab.` },
    { type: 'list', items: [
      `Ziele auf 7 bis 9 h Schlaf: der Großteil der Muskelerholung findet nachts statt.`,
      `Geh zu regelmäßigen Zeiten ins Bett; schalte Bildschirme 30 Min. vorher aus.`,
      `Chronischer Stress hebt das Cortisol, das den Muskelaufbau bremst - lerne abzuschalten.`,
      `Vermeide übermäßigen Alkohol: er stört Schlaf und Proteinsynthese.`,
      `Hol dir morgens Tageslicht, um deine innere Uhr zu stellen.`,
    ] },

    { type: 'h1', text: 'Dehnen & Mobilität' },
    { type: 'p', text: `Widme nach jeder Einheit 5 bis 10 Minuten dem Dehnen, um deine Mobilität unter Last zu erhalten und Muskelkater zu begrenzen. Halte jede Position 20 bis 30 s.` },
    { type: 'table', headers: ['Dehnung', 'Bereich', 'Dauer'], rows: [
      ['Brustdehnung an der Wand', 'Brust, Schultern', '30 s / Seite'],
      ['Hängen an der Stange', 'Rücken, Schultern', '30 s'],
      ['Quadrizepsdehnung stehend', 'Oberschenkelvorderseite', '30 s / Seite'],
      ['Beinbeugerdehnung sitzend', 'Oberschenkelrückseite', '30 s / Seite'],
      ['Taube (Gesäß)', 'Gesäß, Hüften', '30 s / Seite'],
      ['Brustwirbelrotation am Boden', 'Wirbelsäule', '45 s'],
    ] },

    { type: 'h1', text: 'Jede Übung anpassen' },
    { type: 'p', text: `Keine Ausrüstung oder eine Bewegung zu schwer? Hier eine Alternative für jede Grundübung, ohne Effektivität zu verlieren.` },
    { type: 'table', headers: ['Übung', 'Ohne Ausrüstung / leichter', 'Schwerer'], rows: [
      ['Langhantel-Kniebeuge', 'Goblet- / Körpergewichts-Kniebeuge', 'Bulgarische Kniebeuge mit Last'],
      ['Bankdrücken', 'Liegestütze (Füße erhöht)', 'Schweres Schrägbankdrücken'],
      ['Klimmzüge', 'Bandunterstützter Latzug / Rudern', 'Klimmzüge mit Last'],
      ['Kreuzheben', 'Hip Thrust / Hüftheben', 'Schweres Kreuzheben'],
      ['Schulterdrücken', 'Pike-Liegestütze', 'Schweres Drücken im Stehen'],
    ] },

    { type: 'h1', text: 'Nahrungsergänzung' },
    { type: 'p', text: `Keine ist Pflicht - die Ernährung kommt zuerst. Aber einige Mittel haben echten, wissenschaftlich belegten Wert.` },
    { type: 'table', headers: ['Ergänzung', 'Nutzen', 'Dosis'], rows: [
      ['Kreatin-Monohydrat', 'Kraft, Volumen, am besten untersucht', '3 bis 5 g / Tag'],
      ['Whey', 'Eiweiß leicht erreichen', '1 bis 2 Portionen / Tag'],
      ['Vitamin D', 'Bei wenig Sonne', 'Nach ärztlichem Rat'],
      ['Omega-3', 'Erholung, Gelenke', '1 bis 2 g / Tag'],
    ] },
    { type: 'note', text: `Vorsicht bei zuckrigen „Gainern" und Wundermitteln: sie kosten viel für wenig Wirkung. Kreatin und Whey reichen in 99 % der Fälle.` },

    { type: 'h1', text: 'Und nach deinen 12 Wochen?' },
    { type: 'p', text: `Du hast Muskeln aufgebaut: jetzt geht es darum, sie zu erhalten und weiter Fortschritte zu machen. Zwei Optionen je nach Ziel.` },
    { type: 'h2', text: 'Option 1 - Den Muskel zeigen (Definition)' },
    { type: 'list', items: [
      `Wechsle in ein leichtes Defizit (−300 bis −500 kcal), um das in der Masse aufgebaute Fett zu schmelzen.`,
      `Halte Eiweiß hoch und das Krafttraining, um den Muskel zu bewahren.`,
      `Mach mit dem Abnehm-Programm weiter, um deine Definition zu zeigen.`,
    ] },
    { type: 'h2', text: 'Option 2 - Weiter aufbauen' },
    { type: 'list', items: [
      `Mach eine Deload-Woche, dann starte einen neuen Zyklus mit schwereren Lasten.`,
      `Wechsle einige Übungen, um die Reize zu variieren und Routine zu vermeiden.`,
      `Ziele auf neue Kraftrekorde als roten Faden.`,
    ] },
    { type: 'note', text: `Was auch immer du wählst: lass nicht alles auf einmal schleifen. Muskel geht schnell verloren, wenn du komplett aufhörst zu trainieren und genug Eiweiß zu essen.` },

    { type: 'h1', text: 'Tracking deines Fortschritts' },
    { type: 'p', text: `Notiere deine Lasten und dein Gewicht jede Woche: das ist dein Cockpit. Was gemessen wird, wird gesteuert.` },
    { type: 'h2', text: 'Gewicht & Maße' },
    { type: 'tracker', columns: ['Datum', 'Gewicht (kg)', 'Arm (cm)', 'Oberschenkel (cm)', 'Brust (cm)'], rows: 7 },
    { type: 'h2', text: 'Lasten bei den Grundübungen (kg)' },
    { type: 'tracker', columns: ['Übung', 'W1', 'W4', 'W8', 'W12'], rows: 6 },

    { type: 'h1', text: 'Wöchentliche Checkliste' },
    { type: 'p', text: `Hake jedes Kästchen am Ende der Woche ab. Ziel: mindestens 6 von 8.` },
    { type: 'checklist', items: [
      `Ich habe meine 4 Einheiten diese Woche gemacht.`,
      `Ich habe mein Eiweißziel jeden Tag erreicht.`,
      `Ich habe in leichtem Überschuss gegessen (Gewicht stabil oder +).`,
      `Ich habe eine Last oder Wiederholungen erhöht.`,
      `Ich habe die meisten Nächte 7 bis 9 h geschlafen.`,
      `Ich habe getrunken (≈ 3 L/Tag).`,
      `Ich habe meine Lasten und Leistungen notiert.`,
      `Ich habe mich 1× gewogen, unter gleichen Bedingungen.`,
    ] },

    { type: 'h1', text: 'Persönliche Notizen' },
    { type: 'tracker', columns: ['Meine Notizen, Lasten und Empfindungen der Woche'], rows: 18 },

    { type: 'h1', text: 'Glossar' },
    { type: 'p', text: `Die Begriffe, die in diesem Leitfaden vorkommen, einfach erklärt.` },
    { type: 'list', items: [
      `Hypertrophie: Wachstum der Größe der Muskelfasern (das „Volumen").`,
      `Progressive Überlastung: Last oder Wiederholungen regelmäßig erhöhen, um Anpassung zu erzwingen.`,
      `RPE: gefühlte Intensität von 10. RPE 8 = du hattest ~2 Wiederholungen in Reserve.`,
      `Tempo: Ausführungsgeschwindigkeit (z. B. 2 s abwärts, 1 s aufwärts).`,
      `Exzentrisch: die Phase, in der sich der Muskel unter Spannung verlängert (das Absenken).`,
      `Deload: eine leichtere Woche, um zu erholen und stärker zurückzukommen.`,
      `Erhalt: die Kalorienzahl, die dein Gewicht stabil hält.`,
      `Split: wie du die Muskelgruppen über die Woche verteilst (hier Oberkörper/Unterkörper).`,
    ] },

    { type: 'note', text: `12 Wochen geschafft? Mach eine Deload-Woche, nimm deine Maße und Fotos erneut, dann starte einen neuen Zyklus oder eine Definitionsphase (Abnehmen), um den aufgebauten Muskel zu zeigen. Erstelle dein Konto auf xenotif.com.` },
  ],
}
