import type { Guide } from '@/lib/boutique/guides'

// d4 - Lauf-Guide: vom 5K zum Marathon (DE-Mirror von running-guide.ts).
// 5K/10K/Halb/Marathon-Pläne, Lauf-Ernährung, Verletzungsprävention, Wettkampf-Mentalität.
export const runningGuideDe: Guide = {
  id: 'd4',
  title: 'Lauf-Guide - Vom 5K zum Marathon',
  subtitle: '5K / 10K / Halb / Marathon-Pläne, Lauf-Ernährung, Verletzungsprävention, Mentalität',
  author: 'XENOTIF Coach - Zertifizierter Lauftrainer',
  level: 'Anfänger → Erfahren',
  duration: '4 Pläne · 5K bis Marathon',
  coverImage: 'run-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Willkommen, Läufer' },
    { type: 'p', text: `Ob du deine ersten 5 km laufen oder einen Marathon bezwingen willst - dieser Leitfaden begleitet dich den ganzen Weg. Er vereint 4 vollständige Trainingspläne (5K, 10K, Halbmarathon, Marathon), die Wissenschaft der Tempos, die Lauf-Ernährung, die Verletzungsprävention, das Krafttraining des Läufers und die Wettkampf-Mentalität.` },
    { type: 'p', text: `Lies zuerst die Kapitel über Tempos und Technik: sie machen den Unterschied bei deinem Fortschritt und deiner Verletzungsprävention. Jede Kraftübung hat einen QR-Code zu ihrem Demovideo.` },
    { type: 'meta', items: [
      { label: 'Ziel', value: '5K bis Marathon laufen' },
      { label: 'Niveau', value: 'Anfänger bis erfahren' },
      { label: 'Pläne', value: '5K · 10K · Halb · Marathon' },
      { label: 'Einheiten', value: '3 bis 4 pro Woche' },
      { label: 'Ausrüstung', value: 'Ein gutes Paar Schuhe' },
      { label: 'Enthalten', value: 'Pläne + Ernährung + Mentalität' },
    ] },
    { type: 'h2', text: 'So nutzt du diesen Leitfaden' },
    { type: 'list', items: [
      `Wähle deinen Plan je nach Ziel (5K, 10K, Halb oder Marathon).`,
      `Lies die Kapitel „Tempos" und „Prävention", bevor du startest.`,
      `Halte die Ruhetage ein: Fortschritt entsteht in der Erholung.`,
      `Mach das Krafttraining 1-2×/Woche (eigenes Kapitel, mit Video-QR-Codes).`,
      `Notiere deine Läufe und Empfindungen im Tracking.`,
    ] },
    { type: 'note', text: `Die 80/20-Regel: 80 % deiner Kilometer in Grundlagenausdauer (langsam, du kannst reden), 20 % in der Intensität. Das ist die Basis jedes dauerhaften Fortschritts beim Laufen.` },

    { type: 'h1', text: 'Die Wissenschaft der Tempos' },
    { type: 'p', text: `„Ständig schnell" zu laufen ist der Fehler Nr. 1 des Anfängers: das führt zu Übertraining und Verletzungen. Fortschritt kommt aus der VIELFALT der Tempos.` },
    { type: 'table', headers: ['Tempo', 'Intensität', 'Gefühl', 'Einsatz'], rows: [
      ['Grundlagenausdauer', 'Niedrig', 'Du kannst dich unterhalten', '80 % des Volumens'],
      ['Marathon-Tempo', 'Moderat', 'Angenehm hart', 'Lange Läufe'],
      ['Halb/10K-Tempo', 'Anhaltend', 'Kurze Sätze', 'Tempo / Schwelle'],
      ['5K-Tempo / VO2', 'Hoch', 'Wenige Worte', 'Intervalle'],
      ['Sprint', 'Maximal', 'Sprechen unmöglich', 'Steigerungen'],
    ] },
    { type: 'list', items: [
      `Grundlagenausdauer (GA): die Basis. Lauf langsam, wirklich langsam.`,
      `Intervalle (VO2): schnelle Wiederholungen mit Erholung (z. B. 8 × 400 m).`,
      `Tempo / Schwelle: ein anhaltendes Tempo, 15-30 Min. gehalten, um deine Schwelle zu verschieben.`,
      `Langer Lauf: progressiv in der Dauer, im lockeren Tempo, Schlüssel für Halb und Marathon.`,
    ] },

    { type: 'h1', text: 'Berechne deine Trainingstempos' },
    { type: 'p', text: `Um effektiv zu trainieren, hat jeder Einheitstyp sein eigenes Tempo. Finde deine Zielzeit in der Tabelle und lies die entsprechenden Tempos (in Min./km). Das sind deine Richtwerte für den ganzen Leitfaden.` },
    { type: 'table', headers: ['Ziel', 'GA', 'Schwellentempo', 'VO2/5K-Tempo'], rows: [
      ['5K in 30 Min.', '7:00 - 7:30', '5:40', '5:20'],
      ['5K in 25 Min.', '6:15 - 6:45', '4:45', '4:30'],
      ['10K in 55 Min.', '6:30 - 7:00', '5:10', '4:55'],
      ['10K in 50 Min.', '6:00 - 6:30', '4:40', '4:25'],
      ['Halb in 2 h', '6:30 - 7:00', '5:25', '5:05'],
      ['Halb in 1 h 45', '5:45 - 6:15', '4:45', '4:25'],
      ['Marathon in 4 h 30', '7:00 - 7:30', '5:55', '5:30'],
      ['Marathon in 4 h', '6:15 - 6:45', '5:15', '4:55'],
    ] },
    { type: 'note', text: `Du kennst dein Niveau nicht? Lauf 5 km voll aus, einmal aufgewärmt: deine Zeit ordnet dich in die Tabelle ein. Mach diesen Test alle 4-6 Wochen erneut, um deine Tempos mit dem Fortschritt anzupassen.` },

    { type: 'chapter', title: 'Der perfekte Laufstil', src: 'run-2.jpg', intro: `Gute Lauftechnik bedeutet weniger Ermüdung, mehr Tempo und deutlich weniger Verletzungen. Ein paar einfache Prinzipien, die du schrittweise integrierst.` },
    { type: 'list', items: [
      `Schrittfrequenz: ziele auf etwa 170-180 Schritte pro Minute. Eine hohe Frequenz verkürzt den Schritt und reduziert den Impact.`,
      `Fußaufsatz: setze den Fuß unter deiner Hüfte auf, nicht weit vor dir (vermeide den Fersenaufsatz mit gestrecktem Bein).`,
      `Haltung: aufrechter Oberkörper, leichte Körperspannung, Blick zum Horizont, entspannte Schultern.`,
      `Arme: in ~90° gebeugt, Bewegung vor und zurück (kein Kreuzen vor dem Oberkörper), entspannte Hände.`,
      `Atmung: bauchbetont und regelmäßig, an deinen Schritt gekoppelt (z. B. 3 Schritte einatmen / 2 Schritte ausatmen in GA).`,
    ] },
    { type: 'h2', text: 'Der Frequenztest' },
    { type: 'p', text: `Zähle die Aufsätze eines einzigen Fußes über 30 Sekunden, dann multipliziere mit 4. Weniger als 80? Arbeite daran, deinen Schritt zu verkürzen und zu beschleunigen, besonders mit dem Lauf-ABC aus dem Kraftkapitel.` },

    { type: 'h1', text: 'Aufwärmen & Cool-down' },
    { type: 'p', text: `Lass das Aufwärmen nie vor einer Qualitätseinheit aus (Intervalle, Schwelle, Wettkampf). Das Cool-down beschleunigt die Erholung.` },
    { type: 'h2', text: 'Typisches Aufwärmen (15 Min.)' },
    { type: 'table', headers: ['Schritt', 'Dauer', 'Inhalt'], rows: [
      ['Lockeres Einlaufen', '10 Min.', 'Schrittweises Anlaufen des Körpers'],
      ['Mobilität', '2 Min.', 'Hüftkreisen, Sprunggelenke, Beinpendeln'],
      ['Lauf-ABC', '2 Min.', 'High Knees, Anfersen, Seitschritte'],
      ['Steigerungen', '1 Min.', '3 bis 4 progressive Beschleunigungen'],
    ] },
    { type: 'h2', text: 'Cool-down (10 Min.)' },
    { type: 'list', items: [
      `5 Min. sehr lockeres Auslaufen, um das Herz herunterzubringen.`,
      `5 Min. sanftes Dehnen der wichtigsten Muskelgruppen (siehe Dehnkapitel).`,
      `Rehydriere und nimm einen Kohlenhydrat- + Eiweiß-Snack innerhalb der Stunde.`,
    ] },
    { type: 'h2', text: 'Mobilität vor dem Laufen (5 Min.)' },
    { type: 'p', text: `Für lockere Läufe reicht ein kürzeres Aufwärmen, aber einige dynamische Bewegungen bereiten die Gelenke vor und senken das Verletzungsrisiko.` },
    { type: 'table', headers: ['Bewegung', 'Wdh.', 'Ziel'], rows: [
      ['Beinpendeln (vor-zurück)', '10 / Bein', 'Hüften, Beinbeuger'],
      ['Seitliches Pendeln', '10 / Bein', 'Adduktoren, Hüften'],
      ['Sprunggelenkkreisen', '10 / Richtung', 'Sprunggelenke'],
      ['Gehende Ausfallschritte', '8 / Bein', 'Quadrizeps, Gesäß'],
      ['Anfersen auf der Stelle', '20 s', 'Beinbeuger, Anlaufen'],
    ] },
    { type: 'note', text: `Vermeide lange statische Dehnungen VOR dem Laufen: sie senken vorübergehend die Muskelkraft. Heb sie für das Cool-down auf. Vor dem Effort: bevorzuge Bewegung (dynamisch).` },

    { type: 'h1', text: 'Blutiger Anfänger: das Geh-Lauf-Programm' },
    { type: 'p', text: `Du startest bei null oder kommst nach langer Pause zurück? Beginne hier vor dem 5K-Plan. Das Ziel: in 6 Wochen 30 Minuten am Stück laufen, ohne dich zu verletzen.` },
    { type: 'table', headers: ['Woche', 'Einheit (×3/Woche)', 'Gesamt'], rows: [
      ['W1', '6 × (1 Min. Lauf / 1,5 Min. Gehen)', '~20 Min.'],
      ['W2', '6 × (2 Min. Lauf / 1 Min. Gehen)', '~22 Min.'],
      ['W3', '5 × (3 Min. Lauf / 1 Min. Gehen)', '~25 Min.'],
      ['W4', '4 × (5 Min. Lauf / 1 Min. Gehen)', '~28 Min.'],
      ['W5', '3 × (8 Min. Lauf / 1 Min. Gehen)', '~30 Min.'],
      ['W6', '2 × (14 Min. Lauf / 1 Min. Gehen)', '~30 Min.'],
    ] },
    { type: 'note', text: `Lauf immer langsam (du solltest reden können). Ist eine Woche zu schwer, wiederhole sie: es ist keine Schande, im eigenen Tempo voranzukommen. Hast du die 30 Min. am Stück, geh zum 5K-Plan über.` },

    { type: 'chapter', title: '5K-Plan (8 Wochen)', src: 'run-1.jpg', intro: `Ideal zum Starten oder um deine ersten 5 km laufend anzupeilen. 3 Läufe pro Woche. Wechsle anfangs bei Bedarf Laufen und Gehen ab.` },
    { type: 'table', headers: ['Woche', 'Lauf 1', 'Lauf 2', 'Lauf 3 (lang)'], rows: [
      ['W1', '20 Min. Lauf/Gehen', 'Pause / Gehen', '25 Min. Lauf/Gehen'],
      ['W2', '25 Min. GA', 'Pause', '30 Min. GA'],
      ['W3', '25 Min. GA', '6 × 1 Min. schnell / 1 Min. langsam', '35 Min. GA'],
      ['W4', '30 Min. GA', '8 × 1 Min. schnell / 1 Min. langsam', '35 Min. GA'],
      ['W5', '30 Min. GA', '2 × 6 Min. Tempo', '40 Min. GA'],
      ['W6', '30 Min. GA', '10 × 1 Min. schnell / 1 Min. langsam', '40 Min. GA'],
      ['W7', '30 Min. GA', '3 × 6 Min. Tempo', '35 Min. GA'],
      ['W8', '20 Min. GA', '2 × 4 Min. im 5K-Tempo', '5K-RENNEN'],
    ] },

    { type: 'h1', text: '10K-Plan (8 Wochen)' },
    { type: 'p', text: `Für alle, die bereits 5 km laufen und die 10 anpeilen. 3 bis 4 Läufe pro Woche.` },
    { type: 'table', headers: ['Woche', 'Lauf 1', 'Lauf 2', 'Lauf 3 (lang)'], rows: [
      ['W1', '35 Min. GA', '8 × 400 m im 5K-Tempo', '45 Min. GA'],
      ['W2', '35 Min. GA', '2 × 8 Min. Tempo', '50 Min. GA'],
      ['W3', '40 Min. GA', '10 × 400 m', '55 Min. GA'],
      ['W4', '40 Min. GA', '3 × 8 Min. Tempo', '60 Min. GA'],
      ['W5', '40 Min. GA', '6 × 800 m im 10K-Tempo', '65 Min. GA'],
      ['W6', '45 Min. GA', '2 × 12 Min. Tempo', '70 Min. GA'],
      ['W7', '40 Min. GA', '5 × 1000 m im 10K-Tempo', '50 Min. GA'],
      ['W8', '30 Min. GA', '2 × 5 Min. im 10K-Tempo', '10K-RENNEN'],
    ] },
    { type: 'h2', text: 'Deinen 10K meistern' },
    { type: 'list', items: [
      `GA = Grundlagenausdauer (langsam). Das sind 80 % des Plans: lauf sie nie zu schnell.`,
      `Die „Tempo"-Einheiten läufst du im Schwellentempo (siehe Tempokapitel), anhaltend aber kontrolliert.`,
      `Plane einen Ruhetag nach jeder Qualitätseinheit (Intervalle, Tempo).`,
      `In der Wettkampfwoche (W8) reduziere: du sollst frisch ankommen, nicht müde.`,
      `Ziele auf einen Negativ-Split: starte vorsichtig, beschleunige in der zweiten Hälfte.`,
    ] },

    { type: 'chapter', title: 'Halbmarathon-Plan (10 Wochen)', src: 'run-2.jpg', intro: `21,1 km. Der lange Lauf wird zu deiner Königseinheit. 3 bis 4 Läufe pro Woche, darunter ein langer am Wochenende.` },
    { type: 'table', headers: ['Woche', 'Tempo / Schwelle', 'Intervalle', 'Langer Lauf'], rows: [
      ['W1', '2 × 10 Min.', '8 × 400 m', '1 h 10'],
      ['W2', '2 × 12 Min.', '6 × 800 m', '1 h 20'],
      ['W3', '3 × 10 Min.', '10 × 400 m', '1 h 30'],
      ['W4', '20 Min. Schwelle', '5 × 1000 m', '1 h 40'],
      ['W5', '2 × 15 Min.', '6 × 1000 m', '1 h 30 (locker)'],
      ['W6', '25 Min. Schwelle', '4 × 1500 m', '1 h 50'],
      ['W7', '2 × 15 Min. im Halb-Tempo', '8 × 800 m', '2 h 00'],
      ['W8', '30 Min. im Halb-Tempo', '6 × 1000 m', '1 h 45'],
      ['W9', '20 Min. im Halb-Tempo', '4 × 800 m', '1 h 10 (Tapering)'],
      ['W10', '15 Min. Einlaufen', '3 × 3 Min.', 'HALBMARATHON'],
    ] },

    { type: 'h1', text: 'Marathon-Plan (12 Wochen)' },
    { type: 'p', text: `42,195 km: der anspruchsvollste Plan. Voraussetzung: bereits ~1 h bequem laufen. Konstanz und lange Läufe machen alles aus.` },
    { type: 'table', headers: ['Woche', 'Qualitätseinheit', 'Langer Lauf'], rows: [
      ['W1', '2 × 12 Min. Schwelle', '1 h 30'],
      ['W2', '6 × 1000 m', '1 h 45'],
      ['W3', '3 × 12 Min. Schwelle', '2 h 00'],
      ['W4', '8 × 800 m', '1 h 45 (locker)'],
      ['W5', '25 Min. im Marathon-Tempo', '2 h 15'],
      ['W6', '2 × 15 Min. Schwelle', '2 h 30'],
      ['W7', '30 Min. im Marathon-Tempo', '2 h 00 (locker)'],
      ['W8', '5 × 2000 m', '2 h 45'],
      ['W9', '40 Min. im Marathon-Tempo', '3 h 00 (die Königin)'],
      ['W10', '2 × 20 Min. Schwelle', '2 h 15 (Tapering)'],
      ['W11', '20 Min. im Marathon-Tempo', '1 h 30 (Tapering)'],
      ['W12', '15 Min. lockeres Einlaufen', 'MARATHON'],
    ] },
    { type: 'note', text: `Tapering (letzte 2 Wochen): reduziere das Volumen um 40-50 % und behalte etwas Intensität. Du kommst frisch und spritzig am Renntag an. Mach NIE einen großen langen Lauf in der letzten Woche.` },

    { type: 'h1', text: 'Renntag-Strategie' },
    { type: 'p', text: `Ein Rennen wird gesteuert. Der „Negativ-Split" (zweite Hälfte schneller als die erste) ist die beste Strategie auf allen Distanzen. Zu schnell zu starten ist Fehler Nr. 1.` },
    { type: 'table', headers: ['Distanz', 'Erstes Drittel', 'Mitte', 'Finish'], rows: [
      ['5K', 'Kontrolliert, nie voll', 'Zieltempo', 'Auf dem letzten km alles geben'],
      ['10K', 'Leicht unter dem Zieltempo', 'Stabiles Zieltempo', 'Auf den letzten 2 km beschleunigen'],
      ['Halb', 'Sehr kontrolliert', 'Stabiles Zieltempo', 'Kräfte für die letzten 5 km behalten'],
      ['Marathon', 'Langsam, ökonomisch (die Anfangsfalle)', 'Stabiles Marathon-Tempo', 'Die Wand meistern, möglichst stark finishen'],
    ] },
    { type: 'list', items: [
      `Orientiere dich an deinen Tempos (Kapitel „Berechne deine Tempos"), nicht an anderen Läufern.`,
      `Trinke und iss bei Halb/Marathon von Anfang an, bevor du Hunger oder Durst hast.`,
      `Teile das Rennen mental auf (siehe Mentalkapitel): ein Segment nach dem anderen.`,
      `Bereite Ausrüstung und Frühstück am Vorabend vor: null Improvisation am Morgen.`,
    ] },
    { type: 'note', text: `Goldene Regel: „starte langsam, dann werde langsamer" ist ein Läuferwitz… aber er stimmt. Fast alle Minderleistungen kommen von einem zu schnellen Start. Die Disziplin der ersten Kilometer macht die schönen Finishs.` },

    { type: 'chapter', title: 'Ernährung des Läufers', src: 'run-1.jpg', intro: `Gut essen und gut trinken heißt Minuten gewinnen und die Wand vermeiden. Hier die Richtwerte vor, während und nach dem Effort.` },
    { type: 'h2', text: 'Im Alltag' },
    { type: 'list', items: [
      `Genug Kohlenhydrate: sie sind dein Hauptbrennstoff beim Laufen.`,
      `Eiweiß bei jeder Mahlzeit für die Muskelerholung (1,4-1,8 g/kg).`,
      `Konstante Hydrierung: 2 bis 3 L/Tag, mehr je nach Hitze und Volumen.`,
    ] },
    { type: 'h2', text: 'Vorher / währenddessen / danach' },
    { type: 'table', headers: ['Wann', 'Was', 'Warum'], rows: [
      ['Vorher (2-3 h)', 'Kohlenhydratreiche Mahlzeit, arm an Ballast/Fett', 'Auftanken ohne Schwere'],
      ['Währenddessen (> 1 h)', 'Wasser + Kohlenhydrate (Gels, Getränk, Trockenobst) alle 30-45 Min.', 'Den Einbruch (die „Wand") vermeiden'],
      ['Danach (0-1 h)', 'Kohlenhydrate + Eiweiß + Wasser', 'Erholung & Auffüllung'],
    ] },
    { type: 'note', text: `Die Marathon-„Wand" (um den 30. km) = Erschöpfung der Glykogenspeicher. Man vermeidet sie, indem man AB dem Rennstart isst (nicht erst bei Hunger) und im Training lange Läufe gemacht hat.` },

    { type: 'h2', text: 'Hydrierung & Verpflegung je nach Effort' },
    { type: 'p', text: `Passe deine Verpflegung an die Dauer des Laufs an. Jenseits einer Stunde wird die Kohlenhydratzufuhr entscheidend.` },
    { type: 'table', headers: ['Dauer', 'Getränk', 'Kohlenhydrate'], rows: [
      ['< 45 Min.', 'Nicht unbedingt nötig', 'Keine'],
      ['45 Min. - 1 h', 'Wasser bei Hitze', 'Optional'],
      ['1 h - 2 h', '~500 ml/h', '30-40 g/h (Gel, Getränk)'],
      ['> 2 h (Marathon)', 'Wasser + Elektrolyte', '60-90 g/h, ab dem Start'],
    ] },
    { type: 'list', items: [
      `Teste ALLES im Training (Gels, Getränke, Marken): nie etwas Neues am Renntag.`,
      `Bei großer Hitze füge Elektrolyte (Natrium) hinzu, um Krämpfe und Hyponatriämie zu vermeiden.`,
      `Warnsignal für Dehydrierung: dunkler Urin, trockener Mund, sinkende Leistung, Schwindel.`,
      `Wiege dich nach dem Effort: trinke ~1,5 L pro verlorenem Kilo, um gut zu rehydrieren.`,
    ] },
    { type: 'h2', text: 'Verpflegung: selbstgemacht oder gekauft?' },
    { type: 'p', text: `Gekaufte Gels sind im Rennen praktisch, aber im Training kann man sich gut „selbstgemacht" verpflegen, günstiger und verträglicher.` },
    { type: 'table', headers: ['Option', 'Kohlenhydrate', 'Wann'], rows: [
      ['Energie-Gel', '~25 g', 'Rennen, hohe Intensität'],
      ['Fruchtgummi', '~20 g', 'Lange Läufe'],
      ['Banane', '~25 g', 'Lockerer langer Lauf'],
      ['Trockenobst (Datteln, Aprikosen)', '~15-20 g', 'Lange Läufe'],
      ['Selbstgemachtes Sportgetränk', '~30-40 g/500 ml', 'Jeder Lauf > 1 h'],
    ] },
    { type: 'note', text: `Rezept selbstgemachtes Getränk (500 ml): Wasser + 30 g Zucker (oder Sirup) + eine Prise Salz + ein Spritzer Zitrone. Einfach, wirksam und viel günstiger als gekaufte Getränke.` },

    { type: 'chapter', title: 'Verletzungsprävention', src: 'run-2.jpg', intro: `Laufen belastet den Körper stark. 80 % der Läuferverletzungen kommen von vermeidbaren Fehlern: zu viel, zu schnell, schlechte Erholung.` },
    { type: 'list', items: [
      `Die 10-%-Regel: steigere dein Wochenvolumen nicht um mehr als 10 % pro Woche.`,
      `Wärme dich vor Qualitätseinheiten auf (Einlaufen + Lauf-ABC).`,
      `Kräftige dich 1-2×/Woche (nächstes Kapitel): ein starker Läufer verletzt sich weniger.`,
      `Gute Schuhe passend zu deinem Laufstil, alle ~800-1000 km ersetzt.`,
      `Höre auf Schmerzen: ein anhaltendes Gelenkproblem = Pause + ärztlicher Rat.`,
      `Wechsle die Untergründe (Straße, Weg) und vernachlässige nie die Ruhetage.`,
    ] },
    { type: 'h2', text: 'Problem → Lösung' },
    { type: 'table', headers: ['Symptom', 'Häufige Ursache', 'Lösung'], rows: [
      ['Schienbeinkantensyndrom', 'Volumen zu schnell gesteigert', 'Reduzieren, kühlen, weiche Untergründe'],
      ['Läuferknie', 'Schwache Gesäß-/Quadrizepsmuskeln', 'Krafttraining + Tempo senken'],
      ['Achillessehne', 'Zu viel Intensität', 'Pause, Wadendehnungen'],
      ['Blasen', 'Schuhe/Socken', 'Gute Ausrüstung, Anti-Reibung'],
    ] },

    { type: 'chapter', title: 'Die Erholung des Läufers', src: 'run-1.jpg', intro: `Du machst keine Fortschritte während des Efforts, sondern während der Erholung. Sie zu vernachlässigen heißt stagnieren und sich verletzen. So erholst du dich gut.` },
    { type: 'list', items: [
      `Schlaf: 7 bis 9 h pro Nacht. Das ist das Erholungswerkzeug Nr. 1, weit vor allem anderen.`,
      `Ruhetage: nicht verhandelbar. Mindestens 1-2 lauffreie Tage pro Woche je nach Plan.`,
      `Aktive Erholung: Gehen, lockeres Radfahren oder Schwimmen an freien Tagen fördern die Durchblutung.`,
      `Ernährung: Kohlenhydrate + Eiweiß + Hydrierung innerhalb der Stunde nach großen Einheiten.`,
      `Selbstmassage: Rolle und Massageball auf Waden, Quadrizeps und Gesäß.`,
      `Achte auf Übertrainingssignale: anhaltende Müdigkeit, schlechter Schlaf, hoher Ruhepuls, sinkende Motivation.`,
    ] },
    { type: 'h2', text: 'Die Entlastungswoche' },
    { type: 'p', text: `Alle 3-4 Wochen reduziere dein Volumen um ~30 %. Diese „lockeren" Wochen lassen deinen Körper die Arbeit verarbeiten und stärker zurückkommen. Sie gehören zum Fortschritt, sind keine verlorene Zeit.` },

    { type: 'chapter', title: 'Die richtigen Schuhe wählen', src: 'run-2.jpg', intro: `Es ist deine einzige wirklich essenzielle Ausrüstung. Gute Schuhe passend zu deinem Laufstil verhindern die meisten Verletzungen.` },
    { type: 'table', headers: ['Typ', 'Für wen', 'Einsatz'], rows: [
      ['Gedämpft / Max-Cushion', 'Anfänger, schwerere Läufer', 'GA, lange Läufe, Straße'],
      ['Vielseitig', 'Die meisten Läufer', 'Tägliches Training'],
      ['Leicht / dynamisch', 'Regelmäßige Läufer', 'Schnelle Einheiten, Rennen'],
      ['Carbonplatte', 'Erfahrene (Wettkampf)', 'Rennen (5K bis Marathon)'],
      ['Trail', 'Gelände', 'Wege, Berge, Schlamm'],
    ] },
    { type: 'list', items: [
      `Lass dich im Fachgeschäft beraten (Laufstilanalyse).`,
      `Kauf eine halbe Nummer größer als deine Alltagsgröße (die Füße schwellen).`,
      `Ersetze deine Schuhe alle ~800-1000 km (die Dämpfung verschleißt auch ohne sichtbare Löcher).`,
      `Halte bei großem Volumen 2 Paare im Wechsel: sie halten länger und variieren die Belastung.`,
    ] },

    { type: 'h1', text: 'Bei jedem Wetter laufen' },
    { type: 'p', text: `Es gibt kein schlechtes Wetter, nur schlechte Ausrüstung. Pass dich an, um das ganze Jahr sicher zu laufen.` },
    { type: 'table', headers: ['Wetter', 'Tipps'], rows: [
      ['Große Hitze', 'Früh morgens/abends, Hydrierung + Elektrolyte, reduziertes Tempo, Kappe'],
      ['Große Kälte', 'Mehrere atmungsaktive Schichten, Handschuhe/Mütze, längeres Aufwärmen'],
      ['Regen', 'Schirmmütze, technische Kleidung, Anti-Reibung, Wechselsocken'],
      ['Nacht', 'Reflektierende Kleidung, Stirnlampe, bekannte und beleuchtete Strecke'],
      ['Wind', 'Starte gegen den Wind, kehre mit Rückenwind zurück; sei am Straßenrand vorsichtig'],
    ] },
    { type: 'h2', text: 'Sicherheitsregeln' },
    { type: 'list', items: [
      `Sag einer nahestehenden Person bei langen Läufen deine Strecke und Rückkehrzeit.`,
      `Lauf dem Verkehr entgegen, wenn es keinen Gehweg gibt, und bleib sichtbar.`,
      `Halte die Lautstärke niedrig (oder nur einen Ohrhörer), um deine Umgebung zu hören.`,
      `Nimm Handy und Ausweis auf langen Distanzen mit.`,
      `Bei Hitzewelle oder Glätte zögere nicht zu verschieben: keine Einheit ist eine Verletzung wert.`,
    ] },

    { type: 'h1', text: 'Krafttraining des Läufers' },
    { type: 'p', text: `Ein starker Körper läuft schneller und verletzt sich weniger. Mach diesen Zirkel 1 bis 2 Mal pro Woche (außer an Tagen großer Einheiten). Scanne den QR-Code für das Demovideo.` },
    { type: 'exercise', name: 'Plank', muscles: 'Core, Laufhaltung', level: 'Anfänger', technique: `Unterarme auf dem Boden, Körper in einer Linie, Bauch und Gesäß angespannt. Halte 30-60 s. Ein stabiler Rumpf stabilisiert deinen Schritt und spart Energie.`, mistakes: `Hüften sacken ab, Gesäß hoch, Kopf angehoben.` },
    { type: 'exercise', name: 'Kniebeugen', muscles: 'Quadrizeps, Gesäß', level: 'Anfänger', technique: `Füße schulterbreit, Gesäß nach hinten setzen mit geradem Rücken bis die Oberschenkel parallel sind, hochkommen. Stärkt den Abdruck und schützt die Knie.`, mistakes: `Knie kippen nach innen, Fersen heben ab, runder Rücken.` },
    { type: 'exercise', name: 'Ausfallschritte', muscles: 'Gesäß, Quadrizeps, Gleichgewicht', level: 'Anfänger', technique: `Großer Schritt nach vorne, hinteres Knie zum Boden, aufrechter Oberkörper, drücke zurück. Stärkt jedes Bein und korrigiert Ungleichgewichte.`, mistakes: `Zu kurzer Schritt, vorgebeugter Oberkörper, Gleichgewichtsverlust.` },
    { type: 'exercise', name: 'Hüftheben', muscles: 'Gesäß, Beinbeuger', level: 'Anfänger', technique: `Auf dem Rücken, Knie gebeugt, durch die Fersen drücken, um die Hüften zu heben, das Gesäß anspannen. Starke Gesäßmuskeln schützen Knie und Hüften.`, mistakes: `Hohlkreuz, zu hoch heben.` },
    { type: 'exercise', name: 'Wadenheben stehend', muscles: 'Waden, Achillessehne', level: 'Anfänger', technique: `Steig so hoch wie möglich auf die Fußspitzen, halte kurz, senke langsam. Auf einer Stufe für mehr Umfang.`, mistakes: `Kurzer Umfang, Wippen, schnelles Absenken.` },
    { type: 'exercise', name: 'Side-Plank', muscles: 'Schräge Bauchmuskeln, Beckenstabilität', level: 'Anfänger - Mittel', technique: `Auf der Seite, auf dem Unterarm gestützt, Körper in einer Linie, Hüften angehoben. Stabilisiert das Becken für einen effizienten Schritt.`, mistakes: `Hüften sacken ab, Körper kippt.` },
    { type: 'exercise', name: 'Step-Ups', muscles: 'Quadrizeps, Gesäß, Gleichgewicht', level: 'Anfänger', technique: `Steig auf eine Stufe/Bank, indem du über das vordere Bein drückst, kontrolliere das Absenken. Trainiert die einbeinige Kraft, die fürs Laufen spezifisch ist.`, mistakes: `Mit dem hinteren Bein helfen, unkontrolliertes Absenken.` },
    { type: 'exercise', name: 'Lauf-ABC: High Knees', muscles: 'Lauftechnik, Hüftbeuger', level: 'Anfänger', technique: `Über 20 m das Knieheben auf Hüfthöhe übertreiben, schneller Rhythmus, aktiver Core. Verbessert Technik und Schrittfrequenz.`, mistakes: `Oberkörper nach hinten, Knie zu tief, schwerer Schritt.` },
    { type: 'exercise', name: 'Lauf-ABC: Anfersen', muscles: 'Lauftechnik, Beinbeuger', level: 'Anfänger', technique: `Über 20 m die Fersen zum Gesäß bringen, schneller Rhythmus. Aktiviert die Beinbeuger und macht den Schritt geschmeidiger.`, mistakes: `Vorgebeugter Oberkörper, kurzer Umfang.` },
    { type: 'exercise', name: 'Sprunglauf', muscles: 'Kraft, Vortrieb', level: 'Mittel', technique: `Über 20-30 m die Abdruck- und Flugphase übertreiben, wie Sprünge nach vorn. Entwickelt Kraft und Laufökonomie.`, mistakes: `Steife Landung, fehlender Umfang, passive Arme.` },
    { type: 'h2', text: 'Der komplette Zirkel (2×/Woche)' },
    { type: 'p', text: `Reihe diese Übungen als Zirkel aneinander, 2 bis 3 Runden, außer an Tagen großer Einheiten. 15-20 Minuten reichen für einen stärkeren, widerstandsfähigeren Läufer.` },
    { type: 'table', headers: ['Übung', 'Sätze × Wdh.', 'Pause'], rows: [
      ['Plank', '3 × 30-45 s', '30 s'],
      ['Side-Plank', '3 × 30 s / Seite', '30 s'],
      ['Kniebeugen', '3 × 15', '45 s'],
      ['Ausfallschritte', '3 × 12 / Bein', '45 s'],
      ['Hüftheben', '3 × 15', '30 s'],
      ['Wadenheben stehend', '3 × 20', '30 s'],
      ['Step-Ups', '3 × 12 / Bein', '45 s'],
    ] },
    { type: 'note', text: `Das Lauf-ABC (High Knees, Anfersen, Sprunglauf) macht man besser im Aufwärmen der Qualitätseinheiten, über 20-30 m, 2 bis 3 Durchgänge je.` },

    { type: 'h1', text: 'Dehnen & Mobilität' },
    { type: 'p', text: `Nach jedem Lauf 5-10 Min. gezieltes Dehnen. Halte jede Position 20-30 s, ohne Ruckeln.` },
    { type: 'table', headers: ['Dehnung', 'Bereich', 'Dauer'], rows: [
      ['Waden an der Wand', 'Waden, Achilles', '30 s / Seite'],
      ['Quadrizeps stehend', 'Oberschenkelvorderseite', '30 s / Seite'],
      ['Beinbeuger gestrecktes Bein', 'Oberschenkelrückseite', '30 s / Seite'],
      ['Tiefer Ausfallschritt (Psoas)', 'Hüftbeuger', '30 s / Seite'],
      ['Gesäßdehnung (Figur 4)', 'Gesäß', '30 s / Seite'],
      ['Iliotibialband', 'Oberschenkelaußenseite', '30 s / Seite'],
    ] },
    { type: 'h2', text: 'Selbstmassage mit der Rolle' },
    { type: 'p', text: `1 bis 2 Mal pro Woche rolle 30-60 s über jeden Bereich (Waden, Quadrizeps, Gesäß, Iliotibialband). Geh langsam und verweile auf empfindlichen Punkten, ohne direkt über die Gelenke zu rollen. Das verbessert die Beweglichkeit und beschleunigt die Erholung.` },
    { type: 'note', text: `Wann dehnen? Eher kalt am Ende des Tages oder nach dem Cool-down, nie mit Kraft auf einem unaufgewärmten Muskel. Dehnen „verhindert" nicht alle Verletzungen, erhält aber deine Beweglichkeit und deinen Schritt-Komfort.` },

    { type: 'h1', text: 'Die Wettkampf-Mentalität' },
    { type: 'p', text: `Auf langen Distanzen macht der Kopf so viel aus wie die Beine. Die gute Nachricht: das ist trainierbar, genau wie die Ausdauer. So formst du deinen Läuferkopf.` },
    { type: 'h2', text: 'Die Säulen der Mentalität' },
    { type: 'list', items: [
      `Teile das Rennen in Segmente: denk nicht „42 km", sondern „die nächste Verpflegungsstelle".`,
      `Bereite Mantras vor („ich bin stark", „ein Schritt nach dem anderen") für die harten Momente.`,
      `Visualisiere dein Rennen und deine Ziellinie in den Tagen davor.`,
      `Starte vorsichtig: die meisten Minderleistungen kommen von einem zu schnellen Start.`,
      `Akzeptiere das Unbehagen: beim Marathon gehört das Harte zum Plan, es geht immer vorbei.`,
    ] },
    { type: 'h2', text: 'Vor dem Rennen: Stress bewältigen' },
    { type: 'list', items: [
      `Lampenfieber ist normal und sogar nützlich: es macht dich wach und konzentriert.`,
      `Bereite alles am Vorabend vor (Startnummer, Outfit, Frühstück), um den Kopf frei zu haben.`,
      `Atme langsam (4 s einatmen, 6 s ausatmen), um die Anspannung zu senken.`,
      `Setze dir 3 Ziele: ein ehrgeiziges, ein realistisches, ein „akzeptables Minimum".`,
    ] },
    { type: 'h2', text: 'Während des Rennens: durchhalten, wenn es weh tut' },
    { type: 'table', headers: ['Schwerer Moment', 'Mentale Technik'], rows: [
      ['Start zu leicht', 'Dich bremsen: „Geduld, das Rennen beginnt zur Hälfte"'],
      ['Durchhänger', 'Mantra + Fokus auf Schritt und Atmung'],
      ['Die Wand (Marathon)', 'Segmentieren: „nur bis zum nächsten km", lächeln, lockerlassen'],
      ['Lust aufzugeben', 'Erinnere dich an dein „Warum" und die investierten Trainingsstunden'],
      ['Letzter Kilometer', 'Alles geben: „jetzt ernte ich"'],
    ] },
    { type: 'note', text: `Trainiere deinen Kopf im Training: lange Läufe und das Ende von Intervallen sind der ideale Ort, um deine Mantras und das Segmentieren zu üben. Am Renntag ist es nur eine Gewohnheit mehr.` },

    { type: 'h1', text: 'Essenzielle Ausrüstung' },
    { type: 'p', text: `Gute Nachricht: Laufen ist günstig. Abgesehen von den Schuhen (eigenes Kapitel) hier die nützliche Ausrüstung, nach Priorität sortiert - investiere nicht alles auf einmal.` },
    { type: 'table', headers: ['Ausrüstung', 'Priorität', 'Wozu'], rows: [
      ['Passende Schuhe', 'Unverzichtbar', 'Komfort und Verletzungsprävention'],
      ['Technische Socken', 'Unverzichtbar', 'Schweiß ableiten, Blasen vermeiden'],
      ['Atmungsaktive Kleidung', 'Empfohlen', 'Trocken bleiben, Temperatur regulieren'],
      ['Stütz-Sport-BH', 'Unverzichtbar (Frauen)', 'Komfort und Schutz'],
      ['GPS-Uhr / App', 'Empfohlen', 'Tempo, Distanz, Herzfrequenz verfolgen'],
      ['Gürtel / Soft Flask', 'Nützlich (lange Läufe)', 'Wasser und Verpflegung tragen'],
      ['Anti-Reibung', 'Nützlich', 'Empfindliche Stellen schützen (Schenkel, Achseln)'],
      ['Stirnlampe + Reflektoren', 'Je nach Einsatz', 'Sicherheit beim Laufen in der Nacht'],
    ] },
    { type: 'h2', text: 'GPS-Uhr oder Smartphone?' },
    { type: 'p', text: `Eine kostenlose App auf deinem Handy (Strava, Nike Run Club…) reicht zum Starten: sie misst Distanz, Tempo und Strecke. Die GPS-Uhr wird zum echten Plus, sobald du deine Tempos und deine Herzfrequenz täglich trainierst: sofortige Ablesung am Handgelenk, ohne das Handy herauszuholen.` },
    { type: 'note', text: `Die Anfängerfalle: alles auf einmal kaufen. Beginne mit guten Schuhen und atmungsaktiver Kleidung. Den Rest fügst du mit deinem Fortschritt und deinen Zielen hinzu.` },

    { type: 'h1', text: 'Häufige Fragen' },
    { type: 'h2', text: 'Ich halte keine 5 Min. laufend durch, kann ich starten?' },
    { type: 'p', text: `Ja: der 5K-Plan wechselt anfangs Laufen und Gehen ab. Steigere schrittweise den Laufanteil. In 8 Wochen läufst du deine 5K.` },
    { type: 'h2', text: 'Wie schnell soll ich meine Läufe laufen?' },
    { type: 'p', text: `In der Grundlagenausdauer solltest du dich unterhalten können. Bist du außer Atem, läufst du zu schnell. 80 % deiner Läufe sollten in diesem Tempo sein.` },
    { type: 'h2', text: 'Wie lange vor einem Marathon?' },
    { type: 'p', text: `Wenn du bereits ~1 h bequem läufst, reichen 12 Wochen. Sonst mach erst die 10K- und Halb-Pläne, bevor du den Marathon angehst.` },
    { type: 'h2', text: 'Was tun bei Schmerzen?' },
    { type: 'p', text: `Ein vorübergehendes Muskelproblem: anpassen. Ein Gelenkschmerz oder einer, der anhält: ruhe dich aus und lass dich beraten. „Drück" nie durch echten Schmerz - das ist der garantierte Stopp.` },
    { type: 'h2', text: 'Muss ich Krafttraining machen?' },
    { type: 'p', text: `Ja, 1-2×/Woche. Das macht dich schneller UND widerstandsfähiger gegen Verletzungen. Krafttraining ist für dauerhaften Fortschritt nicht optional.` },
    { type: 'h2', text: 'Laufband oder draußen?' },
    { type: 'p', text: `Beides funktioniert. Das Laufband dämpft und erlaubt Tempokontrolle (stell 1 % Steigung ein, um draußen zu imitieren). Draußen trainiert Gleichgewicht, Gelände und den Kopf. Idealerweise wechsle ab.` },
    { type: 'h2', text: 'Wie vermeide ich Seitenstechen?' },
    { type: 'p', text: `Iss nicht zu kurz vor dem Lauf, wärme dich schrittweise auf und arbeite an deiner Bauchatmung. Bei Seitenstechen werde langsamer und atme tief aus, während du leicht auf die Stelle drückst.` },
    { type: 'h2', text: 'Ich stagniere, was tun?' },
    { type: 'p', text: `Prüfe zuerst deine Erholung und deinen Schlaf. Füge Vielfalt hinzu (Intervalle, Schwelle), halte das 80/20 ein und mach Entlastungswochen. Fortschritt ist nie linear: Geduld zahlt sich aus.` },
    { type: 'h2', text: 'Wie oft pro Woche laufen?' },
    { type: 'p', text: `3 Läufe reichen für 5K und 10K, 3-4 für Halb und Marathon. Besser 3 regelmäßige, gute Läufe als 5 hingeschluderte. Konstanz schlägt punktuelle Intensität.` },

    { type: 'h1', text: 'Tracking deiner Läufe' },
    { type: 'p', text: `Notiere jeden Lauf: Distanz, Dauer, Tempo, Empfindungen. Das ist dein Fortschrittsjournal.` },
    { type: 'tracker', columns: ['Datum', 'Distanz (km)', 'Dauer', 'Tempo', 'Empfindungen /10'], rows: 13 },
    { type: 'h2', text: 'Persönliche Rekorde' },
    { type: 'tracker', columns: ['Distanz', 'Ziel', 'Erreicht', 'Datum'], rows: 6 },

    { type: 'h1', text: 'Wöchentliche Checkliste' },
    { type: 'p', text: `Hake jedes Kästchen am Ende der Woche ab.` },
    { type: 'checklist', items: [
      `Ich habe meine geplanten Läufe diese Woche gemacht.`,
      `80 % meines Volumens waren Grundlagenausdauer.`,
      `Ich habe mein Volumen nicht um mehr als 10 % gesteigert.`,
      `Ich habe mich vor meinen Qualitätseinheiten aufgewärmt.`,
      `Ich habe 1-2 Krafteinheiten gemacht.`,
      `Ich habe mein Lauf-ABC gemacht und an meiner Frequenz gearbeitet.`,
      `Ich habe mich nach den Läufen gedehnt.`,
      `Ich habe 7 bis 9 h pro Nacht geschlafen.`,
      `Ich habe gut getrunken und gegessen.`,
      `Ich habe meine Ruhetage eingehalten.`,
      `Ich habe meine Läufe und Empfindungen notiert.`,
      `Ich hatte diese Woche Freude am Laufen.`,
    ] },

    { type: 'h1', text: 'Motivation & Konstanz' },
    { type: 'p', text: `Das Schwerste ist nicht, schnell zu laufen, sondern REGELMÄSSIG zu laufen. So hältst du auf Dauer durch.` },
    { type: 'list', items: [
      `Melde dich für ein Rennen an: eine Startnummer ist der beste Antrieb.`,
      `Bereite deine Sachen am Vorabend vor: weniger Reibung = weniger Ausreden.`,
      `Lauf zu einer festen Zeit, um es zur automatischen Gewohnheit zu machen.`,
      `Find einen Partner oder einen Verein: zu zweit steht man leichter auf.`,
      `Feiere jeden Fortschritt (erste 5K ohne Gehen, neuer Rekord): Motivation nährt sich von Siegen.`,
      `An Tagen ohne Lust setz dir nur „10 Minuten". Meist beendest du deinen Lauf.`,
    ] },
    { type: 'note', text: `Konstanz schlägt Talent. Ein durchschnittlicher Läufer, der ein Jahr lang 3×/Woche trainiert, macht mehr Fortschritte als ein begabter, der eine Woche von drei trainiert. Sei dieser konstante Läufer.` },

    { type: 'h1', text: 'Das Läufer-Glossar' },
    { type: 'p', text: `Das essenzielle Vokabular, um die Pläne und Gespräche zwischen Läufern zu entschlüsseln.` },
    { type: 'table', headers: ['Begriff', 'Definition'], rows: [
      ['GA', 'Grundlagenausdauer: langsames Tempo, in dem man reden kann'],
      ['VO2', 'Das Tempo, bei dem man seinen maximalen Sauerstoffverbrauch erreicht'],
      ['Schwelle', 'Anhaltendes Tempo, ~1 h haltbar; verbessert die Ausdauer bei hoher Intensität'],
      ['Intervalle', 'Schnelle Wiederholungen, unterbrochen von Erholungen (z. B. 8 × 400 m)'],
      ['Fahrtspiel', 'Freies Tempospiel: man beschleunigt und verlangsamt nach Gefühl'],
      ['Tempo', 'Kontinuierlicher Effort in anhaltendem Tempo (nahe der Schwelle)'],
      ['Negativ-Split', 'Die 2. Hälfte schneller laufen als die 1.'],
      ['Tapering', 'Volumenreduktion vor einem Rennen, um frisch anzukommen'],
      ['Die Wand', 'Plötzliche Glykogenerschöpfung (oft um den 30. km des Marathons)'],
      ['Drop', 'Höhenunterschied Ferse/Vorfuß eines Schuhs'],
      ['Schrittfrequenz', 'Anzahl der Schritte pro Minute'],
      ['Tempo (Pace)', 'Zeit für 1 km (Min./km)'],
    ] },

    { type: 'h1', text: 'Persönliche Notizen' },
    { type: 'tracker', columns: ['Meine Läufe, Empfindungen und Ziele der Woche'], rows: 20 },

    { type: 'h1', text: 'Und nach deinem Rennen?' },
    { type: 'p', text: `Du hast die Ziellinie überquert: bravo! Aber das Abenteuer endet nicht hier. So verwandelst du diesen Erfolg in dauerhaften Fortschritt.` },
    { type: 'list', items: [
      `Erhole dich richtig: 1 sehr lockere Woche nach einem 5K/10K, 2 bis 3 Wochen nach einem Marathon.`,
      `Setze dir eine neue Herausforderung: die nächste Distanz oder dieselbe Zeit… schneller.`,
      `Halte das ganze Jahr eine Grundlagenausdauer-Basis: das macht Wiedereinstiege leicht.`,
      `Mach mit Krafttraining und Lauf-ABC weiter: ein gepflegter Läufer ist ein Läufer, der durchhält.`,
      `Tritt einer Gemeinschaft oder einem Verein bei: mit anderen laufen erhält die Motivation langfristig.`,
    ] },
    { type: 'h2', text: 'Wähle dein nächstes Ziel' },
    { type: 'table', headers: ['Du bist gerade gelaufen', 'Logisches nächstes Ziel'], rows: [
      ['Deine ersten 5K', 'Deine Zeit verbessern, dann 10K anpeilen'],
      ['Einen 10K', 'Den Halbmarathon'],
      ['Einen Halbmarathon', 'Den Marathon oder einen schnelleren Halb'],
      ['Einen Marathon', 'Einen neuen Marathon mit Zeitziel oder Trailrunning'],
    ] },
    { type: 'note', text: `Glückwunsch! Gönn dir eine echte Erholung, dann brich zu einem neuen Ziel auf. Erstelle dein Konto auf xenotif.com, um deine Läufe zu verfolgen, deine Tempos zu planen und mit deinem KI-Coach zu sprechen. Wir sehen uns an der Startlinie!` },
  ],
}
