import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Home Fitness Program (EN mirror of fitness-maison.ts). Premium XENOTIF® template (≈30 pages).
export const fitnessMaisonEn: Guide = {
  id: 'fitness-maison',
  title: 'Home Fitness Program',
  subtitle: '8 weeks, 100% bodyweight, zero equipment - wherever you are',
  author: 'XENOTIF Coach - Certified Strength & Conditioning',
  level: 'Beginner - Intermediate',
  duration: '8 weeks · 4 sessions/week',
  coverImage: 'fitness-maison-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Your home is your gym' },
    { type: 'p', text: `No gym, no equipment, no excuses. This 8-week program is done entirely with bodyweight training, in just 2 m² of space, at home or on the road. You'll tone your body, build functional strength, burn fat, and build an unbreakable routine - with your own body as the only equipment you need.` },
    { type: 'p', text: `Every exercise has a QR code linking to its demo video on XENOTIF®. If you're ever unsure, scan it.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Tone, burn, strengthen' },
      { label: 'Level', value: 'Beginner to intermediate' },
      { label: 'Duration', value: '8 weeks' },
      { label: 'Frequency', value: '4 sessions per week' },
      { label: 'Equipment', value: 'None (mat optional)' },
      { label: 'Location', value: 'Home, travel, anywhere' },
    ] },
    { type: 'h2', text: 'Program goals' },
    { type: 'list', items: [
      `Tone and strengthen your entire body with no equipment.`,
      `Burn fat with short, intense circuits.`,
      `Improve your functional strength, mobility, and cardio.`,
      `Build a routine you can stick to anywhere, with zero constraints.`,
    ] },
    { type: 'h2', text: 'How to use this guide' },
    { type: 'list', items: [
      `Read the whole guide, then follow the 8-week schedule.`,
      `Warm up for 5 min before every session (dedicated page).`,
      `Scan an exercise's QR code to watch the technique on video.`,
      `Progress by moving to the harder variations listed.`,
      `Review your week every Sunday (tracker + checklist).`,
    ] },
    { type: 'note', text: `Golden rule of bodyweight training: without added weight, you progress through variation difficulty, tempo, rep count, and density (less rest). Progression is real - you just have to create it.` },

    { type: 'h1', text: 'How it works' },
    { type: 'list', items: [
      `4 sessions/week: 2 full-body strength sessions + 2 cardio/HIIT circuits.`,
      `Circuit format: move from one exercise to the next with little rest to keep the intensity high.`,
      `Reps or time: "3 × 12" = 3 sets of 12; "40 s" = 40 seconds of effort.`,
      `Controlled tempo: 2 s on the way down, 1 s on the way up. Slowing down increases the difficulty.`,
      `Rest: 30 to 60 s between sets/exercises depending on your level.`,
      `Intensity (RPE /10): aim for 7-8; push to 9 on the HIIT circuits.`,
    ] },
    { type: 'h2', text: 'Progressing without weights' },
    { type: 'p', text: `This is THE question everyone asks about home training. Here are the 5 levers to keep progressing without ever touching a dumbbell.` },
    { type: 'table', headers: ['Lever', 'How', 'Example'], rows: [
      ['Harder variation', 'Choose a more demanding version', 'Push-up → decline push-up'],
      ['More reps', 'Add reps every week', '10 → 12 → 15'],
      ['Slow tempo', 'Slow down the eccentric', '4-second squat descent'],
      ['Density', 'Reduce rest', '60 s → 30 s'],
      ['Single-leg/arm work', 'Train one side at a time', 'Squat → Bulgarian split squat'],
    ] },

    { type: 'h1', text: 'Warm-up' },
    { type: 'p', text: `5 minutes before every session to prep your body and boost your performance.` },
    { type: 'table', headers: ['Movement', 'Duration'], rows: [
      ['Walk / jog in place', '60 s'],
      ['High knees', '45 s'],
      ['Arm & hip circles', '45 s'],
      ['Slow squats', '45 s'],
      ['Dynamic lunges', '45 s'],
      ['20 s plank + slow push-ups', '40 s'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Results are built at the table too.' },
    { type: 'h1', text: 'Nutrition' },
    { type: 'p', text: `Whatever your goal (toning, cutting, getting stronger), the basics are the same: enough protein, simple foods, and a calorie intake matched to your target.` },
    { type: 'meta', items: [
      { label: 'For cutting', value: 'Slight deficit (−300/−500 kcal)' },
      { label: 'For getting stronger', value: 'Maintenance to slight surplus' },
      { label: 'Protein', value: '1.6 to 2 g per kg' },
      { label: 'Hydration', value: '2 to 3 L per day' },
    ] },
    { type: 'list', items: [
      `A protein source at every meal (eggs, chicken, fish, skyr, legumes).`,
      `Vegetables with every meal, carbs around your sessions.`,
      `Cut back on liquid sugar (soda, juice, alcohol).`,
      `Drink water regularly, especially during the circuits.`,
    ] },
    { type: 'h2', text: 'Understanding your macros' },
    { type: 'table', headers: ['Macro', 'Role', 'Per g', 'Priority'], rows: [
      ['Protein', 'Muscle & satiety', '4 kcal', 'HIGH - 1.6-2 g/kg'],
      ['Carbs', 'Energy', '4 kcal', 'Around sessions'],
      ['Fats', 'Hormones, health', '9 kcal', 'Moderate, quality'],
    ] },
    { type: 'note', text: `No equipment needed… and no complicated cooking either. Build every plate: 1 protein + 1 carb + vegetables + a bit of healthy fat.` },

    { type: 'h1', text: 'Quick recipes' },
    { type: 'h2', text: 'Scrambled eggs + oats' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 400 kcal' }, { label: 'Protein', value: '28 g' }] },
    { type: 'list', items: [`3 eggs`, `40 g rolled oats`, `1 piece of fruit`, `Spices`] },
    { type: 'p', text: `Prep: scramble the eggs, prepare the oats separately. A complete breakfast in 5 min.` },
    { type: 'h2', text: 'Chickpea & tuna salad' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protein', value: '35 g' }] },
    { type: 'list', items: [`1 can chickpeas`, `1 can tuna`, `Tomatoes, onion, parsley`, `Lemon, olive oil`] },
    { type: 'p', text: `Prep: mix everything together. No cooking required, ultra-quick and filling.` },
    { type: 'h2', text: 'Protein skyr bowl' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 350 kcal' }, { label: 'Protein', value: '32 g' }] },
    { type: 'list', items: [`250 g skyr`, `Berries`, `30 g oats`, `Almonds`] },
    { type: 'p', text: `Prep: mix together. Perfect as a snack or post-workout.` },
    { type: 'h2', text: 'Chicken & veggie stir-fry' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 470 kcal' }, { label: 'Protein', value: '40 g' }] },
    { type: 'list', items: [`140 g chicken`, `200 g vegetables (fresh or frozen)`, `100 g cooked rice`, `Spices, soy sauce`] },
    { type: 'p', text: `Prep: sear the chicken, add the vegetables, serve over rice. One pan, 12 min.` },
    { type: 'h2', text: 'Avocado-egg toast' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 380 kcal' }, { label: 'Protein', value: '22 g' }] },
    { type: 'list', items: [`2 slices wholegrain bread`, `1/2 avocado`, `2 eggs`, `Lemon, salt, pepper`] },
    { type: 'p', text: `Prep: mash the avocado onto the bread, top with the eggs (fried or poached). A filling breakfast or snack.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Recover well to progress session after session.' },
    { type: 'h1', text: 'Recovery' },
    { type: 'list', items: [
      `Sleep 7 to 9 h: that's when your body rebuilds.`,
      `Keep at least 1 full rest day per week.`,
      `Soreness in the first few weeks is completely normal.`,
      `Stretch for 5-10 min after every session.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: '4 sessions a week, wherever you are.' },
    { type: 'h1', text: '8-week schedule' },
    { type: 'p', text: `Alternate strength work and circuits. Add reps, slow the tempo, or move to harder variations as soon as it gets easy.` },
    { type: 'table', headers: ['Weeks', 'Focus', 'Volume', 'Note'], rows: [
      ['W1-W2', 'Adaptation', '3 rounds', 'Learn the movements'],
      ['W3-W4', 'Volume', '4 rounds', '+ reps'],
      ['W5-W6', 'Intensity', '4 rounds', 'Harder variations, shorter rest'],
      ['W7-W8', 'Peak', '5 rounds', 'Beat your PRs, review'],
    ] },
    { type: 'h2', text: 'Typical week' },
    { type: 'table', headers: ['Day', 'Session', 'Duration'], rows: [
      ['Monday', 'Strength A (lower body + core)', '35 min'],
      ['Tuesday', 'HIIT circuit', '25 min'],
      ['Wednesday', 'Rest / walk', '-'],
      ['Thursday', 'Strength B (upper body + core)', '35 min'],
      ['Friday', 'Full-body cardio circuit', '30 min'],
      ['Weekend', 'Active rest + tracking', '-'],
    ] },

    { type: 'h2', text: 'Day-by-day breakdown (weeks 1 to 4)' },
    { type: 'p', text: `Weeks 5 to 8 follow the same pattern with more rounds, harder variations, and less rest (see "8-week progression").` },
    { type: 'table', headers: ['Day', 'W1-W2', 'W3-W4'], rows: [
      ['Monday', 'Strength A', 'Strength A (+ reps)'],
      ['Tuesday', 'HIIT circuit', 'HIIT circuit'],
      ['Wednesday', 'Rest / walk', 'Rest / walk'],
      ['Thursday', 'Strength B', 'Strength B (+ reps)'],
      ['Friday', 'Cardio circuit', 'Cardio circuit (4 rounds)'],
      ['Saturday', 'Active rest', 'Active rest'],
      ['Sunday', 'Rest + tracking', 'Rest + tracking'],
    ] },

    { type: 'h1', text: 'Your sessions in detail' },
    { type: 'h2', text: 'Strength A - Lower body & core' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Squats', '4', '15 to 20', '45 s'],
      ['Alternating lunges', '3', '12 / leg', '45 s'],
      ['Glute bridge', '3', '20', '40 s'],
      ['Wall sit', '3', '40 s', '40 s'],
      ['Plank', '3', '40 s', '40 s'],
    ] },
    { type: 'h2', text: 'Strength B - Upper body & core' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Push-ups (adapted variation)', '4', 'Clean max', '45 s'],
      ['Chair dips', '3', '12', '45 s'],
      ['Weighted-bag row (or superman)', '3', '12', '45 s'],
      ['Pike push-ups (shoulders)', '3', '10', '45 s'],
      ['Side plank', '3', '25 s / side', '30 s'],
    ] },
    { type: 'h2', text: 'HIIT circuit (25 min)' },
    { type: 'table', headers: ['Block', 'Work', 'Rest', 'Rounds'], rows: [
      ['Burpees (or jump squats)', '40 s', '20 s', '4'],
      ['Mountain climbers', '40 s', '20 s', '4'],
      ['Jump lunges (or lunges)', '40 s', '20 s', '4'],
      ['Jumping jacks', '40 s', '20 s', '4'],
      ['Dynamic plank', '40 s', '20 s', '4'],
    ] },

    { type: 'h1', text: 'Exercise library' },
    { type: 'p', text: `Master these bodyweight movements. Scan the QR for the demo video.` },
    { type: 'exercise', name: 'Bodyweight squat', muscles: 'Quads, glutes, hamstrings', level: 'Beginner', video: `${D}/musculation`, technique: `Feet shoulder-width apart, lower by pushing your hips back, back straight, heels on the floor, down to thighs parallel, then push back up.`, mistakes: `Knees caving in, heels lifting, rounded back.` },
    { type: 'exercise', name: 'Alternating lunges', muscles: 'Glutes, quads, balance', level: 'Beginner', video: `${D}/musculation`, technique: `Big step forward, back knee toward the floor, torso upright, front knee over the ankle, push back to return.`, mistakes: `Step too short, leaning torso, losing balance.` },
    { type: 'exercise', name: 'Push-ups', muscles: 'Chest, triceps, shoulders, core', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Body braced in a straight line, lower the chest toward the floor, elbows ~45°, then push. Variations: incline (easy) → floor → decline (hard).`, mistakes: `Hips sagging, elbows too flared, short range.` },
    { type: 'exercise', name: 'Glute bridge', muscles: 'Glutes, hamstrings', level: 'Beginner', video: `${D}/musculation`, technique: `On your back, knees bent, push through the heels to lift the hips, squeeze the glutes at the top, lower without resting. Variation: single-leg.`, mistakes: `Arching the back, lifting too high, feet too far out.` },
    { type: 'exercise', name: 'Wall sit', muscles: 'Quads, core', level: 'Beginner', video: `${D}/musculation`, technique: `Back against the wall, slide down until thighs are parallel, knees at 90°, hold the position, core engaged.`, mistakes: `Knees passing the ankles, back lifting off the wall, holding your breath.` },
    { type: 'exercise', name: 'Chair dips', muscles: 'Triceps, shoulders, chest', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Hands on the edge of a stable chair, legs out in front, lower by bending the elbows back, then push back up. Straight legs = harder.`, mistakes: `Shoulders shrugging up, short descent, unstable chair.` },
    { type: 'exercise', name: 'Pike push-ups', muscles: 'Shoulders, triceps', level: 'Intermediate', video: `${D}/musculation`, technique: `In an inverted "V" (hips high), lower the crown of your head toward the floor by bending the elbows, then push. Builds toward the handstand push-up.`, mistakes: `Rounded back, short range, elbows too flared.` },
    { type: 'exercise', name: 'Superman', muscles: 'Lower back, glutes, back', level: 'Beginner', video: `${D}/musculation`, technique: `Lying face down, lift the arms and legs at the same time by contracting the back and glutes, hold 1-2 s, lower with control.`, mistakes: `Jerky movement, neck hyperextended, insufficient contraction.` },
    { type: 'exercise', name: 'Plank', muscles: 'Core', level: 'Beginner', video: `${D}/musculation`, technique: `Forearms and toes on the floor, body aligned, abs and glutes braced, breathe and hold.`, mistakes: `Hips sagging, hips too high, head lifted up.` },
    { type: 'exercise', name: 'Side plank', muscles: 'Obliques, core', level: 'Beginner', video: `${D}/musculation`, technique: `On your side, supported on one forearm, body aligned, hips lifted. Hold, then switch sides.`, mistakes: `Hips dropping, body tipping forward.` },
    { type: 'exercise', name: 'Mountain climbers', muscles: 'Abs, shoulders, cardio', level: 'Intermediate', video: `${D}/hiit`, technique: `In a high plank, alternately drive one knee toward the chest, faster and faster, hips low, core braced.`, mistakes: `Hips too high, sagging back, messy rhythm.` },
    { type: 'exercise', name: 'Burpee', muscles: 'Whole body, cardio', level: 'Advanced', video: `${D}/hiit`, technique: `Standing → hands on the floor → jump feet back (plank) → push-up (optional) → bring the feet in → vertical jump. Chain it smoothly.`, mistakes: `Rounded back, landing with stiff legs. Cushion the landing, keep a steady rhythm.` },
    { type: 'exercise', name: 'Jump squats', muscles: 'Legs, glutes, cardio', level: 'Intermediate', video: `${D}/hiit`, technique: `Squat then jump explosively upward, land soft and controlled back in the squat position, repeat.`, mistakes: `Landing with stiff knees, leaning torso, insufficient squat depth.` },
    { type: 'exercise', name: 'Jumping jacks', muscles: 'Cardio, shoulders, legs', level: 'Beginner', video: `${D}/hiit`, technique: `Jump while spreading the legs and arms, then return. Soft landing, steady rhythm.`, mistakes: `Stiff landing, incomplete arm range.` },
    { type: 'exercise', name: 'Crunch', muscles: 'Rectus abdominis (abs)', level: 'Beginner', video: `${D}/musculation`, technique: `On your back, knees bent, lift the shoulders by curling the torso up, exhale, lower slowly. The lower back stays on the floor.`, mistakes: `Pulling on the neck, lifting the whole back off the floor, holding your breath.` },
    { type: 'exercise', name: 'Leg raises', muscles: 'Lower abs, core', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Lying down, hands under the glutes, raise the legs (straight or bent) toward vertical, lower slowly without touching the floor. Lower back pressed down.`, mistakes: `Arching the back, lowering too fast, using momentum.` },
    { type: 'exercise', name: 'Single-leg glute bridge', muscles: 'Glutes, hamstrings, core', level: 'Intermediate', video: `${D}/musculation`, technique: `Classic glute bridge but with one leg extended in the air. Push through the grounded heel, lift the hips level, squeeze the glute. Switch legs.`, mistakes: `Hips twisting, lower-back hyperextension, short range.` },

    { type: 'h1', text: 'Cardio, walking & NEAT' },
    { type: 'p', text: `Beyond your sessions, your daily activity (NEAT) makes a huge difference to energy expenditure and fat loss - without causing fatigue or requiring any equipment.` },
    { type: 'list', items: [
      `Aim for 8,000 to 10,000 steps a day: walking, stairs, trips on foot.`,
      `2 to 3 brisk 30-min walks a week, ideally on rest days.`,
      `Break it up: 3 × 10 min of walking is worth a 30-min block.`,
      `First thing in the morning, fasted, with music or a podcast - the best time to make it stick.`,
    ] },
    { type: 'table', headers: ['Activity', 'Duration', 'Frequency', 'Effect'], rows: [
      ['Walking (NEAT)', 'Throughout the day', 'Daily', 'Expenditure, recovery'],
      ['Brisk walk', '30 min', '2-3×/week', 'Gentle cardio, fat loss'],
      ['HIIT circuit', '20-25 min', '2×/week', 'Fat burn, EPOC'],
    ] },

    { type: 'h1', text: '8-week progression' },
    { type: 'table', headers: ['Week', 'Volume / format', 'Goal'], rows: [
      ['W1', '3 rounds, 60 s rest', 'Learn the movements'],
      ['W2', '3 rounds, +2 reps', 'Lock in the technique'],
      ['W3', '4 rounds', 'Increase volume'],
      ['W4', '4 rounds, 45 s rest', 'Midpoint review'],
      ['W5', '4 rounds, harder variations', 'Step up the difficulty'],
      ['W6', '4 rounds, slow tempo', 'Build control'],
      ['W7', '5 rounds', 'Peak volume'],
      ['W8', '5 rounds, 30 s rest', 'Peak, final measurements'],
    ] },

    { type: 'h1', text: 'Adapt every exercise to your level' },
    { type: 'p', text: `In bodyweight training, progression comes through variation. Choose the version that lets you hit the target reps with good technique, then step up the difficulty.` },
    { type: 'table', headers: ['Exercise', 'Easier', 'Standard', 'Harder'], rows: [
      ['Push-up', 'Incline (hands elevated)', 'Floor', 'Decline / weighted'],
      ['Squat', 'Chair-assisted', 'Bodyweight', 'Jump / Bulgarian split'],
      ['Lunge', 'Static, supported', 'Alternating', 'Jumping'],
      ['Plank', 'On the knees', 'Full plank', 'Dynamic / 3-point'],
      ['Dips', 'Feet close in', 'Legs half-extended', 'Legs fully extended'],
      ['Glute bridge', 'Two legs', 'Paused at the top', 'Single-leg'],
    ] },

    { type: 'h1', text: 'Plan B: 10-minute express session' },
    { type: 'p', text: `No time? A short session always beats no session - it keeps the habit alive. Run this circuit twice, 40 s work / 20 s transition, 1 min rest between rounds.` },
    { type: 'table', headers: ['Exercise', 'Duration', 'Rest'], rows: [
      ['Squats', '40 s', '20 s'],
      ['Push-ups', '40 s', '20 s'],
      ['Mountain climbers', '40 s', '20 s'],
      ['Alternating lunges', '40 s', '20 s'],
      ['Plank', '40 s', '20 s'],
    ] },

    { type: 'h1', text: 'HIIT at home' },
    { type: 'p', text: `HIIT is your best ally for burning fat with no equipment and barely any space. The principle: short, intense efforts broken up by recovery periods.` },
    { type: 'list', items: [
      `Classic format: 40 s work / 20 s rest, 4 to 5 exercises, 3 to 5 rounds.`,
      `During the work phase, you should be unable to hold a conversation.`,
      `2 HIIT sessions a week are enough; more risks hurting your recovery.`,
      `Adapt the impact: swap jumps for grounded versions if your joints are sensitive.`,
    ] },

    { type: 'h1', text: 'Mistakes to avoid' },
    { type: 'list', items: [
      `Believing you can't progress without equipment: false - use the 5 progression levers.`,
      `Rushing technique to go faster: quality comes first, especially in bodyweight training.`,
      `Doing cardio only: keep 2 strength sessions a week.`,
      `Skipping the warm-up, especially before jump-based circuits.`,
      `Ignoring nutrition: a workout doesn't make up for a poor diet.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: [`You're facing…`, 'The solution'], rows: [
      ['Push-ups are too hard', 'Start with incline push-ups (hands elevated)'],
      [`It's gotten too easy`, 'Harder variation, slower tempo, −15 s rest'],
      ['Knee pain (jumps)', 'Swap for no-impact versions'],
      ['Lacking motivation', 'A short 15-min session beats nothing'],
    ] },

    { type: 'h1', text: 'Staying motivated' },
    { type: 'list', items: [
      `Set a fixed time slot: at home, routine is everything.`,
      `Lay out your workout clothes and mat the night before.`,
      `Photos & measurements every 4 weeks: the transformation shows.`,
      `Keep a 15-min "Plan B" session for days when time is tight.`,
    ] },
    { type: 'h2', text: 'Build the habit' },
    { type: 'list', items: [
      `Anchor your session to a specific moment (right after waking up, before dinner).`,
      `The 2-minute rule: just start the warm-up.`,
      `Never skip 2 sessions in a row.`,
    ] },

    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: 'Can you really build muscle without weights?' },
    { type: 'p', text: `Yes, especially as a beginner or intermediate. By increasing variation difficulty, reps, and tempo, and reducing rest, you create enough tension to build muscle.` },
    { type: 'h2', text: 'How much space do you need?' },
    { type: 'p', text: `2 m² is enough: room to lie down and do a lunge. No equipment required; a mat adds comfort on the floor.` },
    { type: 'h2', text: `What if I don't have a chair for dips?` },
    { type: 'p', text: `Use a couch, a low bed, or steps. Otherwise swap in close-grip push-ups (hands close together), which also target the triceps.` },
    { type: 'h2', text: 'I live in an apartment and the jumps disturb the neighbors. What can I do?' },
    { type: 'p', text: `Replace every jumping movement with its no-impact version (squat instead of jump squat, high knees instead of jumping jacks). It stays just as effective.` },
    { type: 'h2', text: 'Cardio or strength training for fat loss?' },
    { type: 'p', text: `Both. Strength training preserves muscle, while HIIT and walking increase expenditure. And above all: nutrition. The program already combines everything.` },

    { type: 'h1', text: 'Safety & impact' },
    { type: 'p', text: `Home training is very safe. Here are a few guidelines to train hard without getting hurt, even on a hard floor or in an apartment.` },
    { type: 'list', items: [
      `Always warm up, especially before jumping movements.`,
      `Soft landing on the balls of the feet, knees bent, on every jump.`,
      `Hard floor or downstairs neighbors: replace jumps with no-impact versions.`,
      `Keep the back braced and neutral during push-ups, lunges, and planks.`,
      `Joint pain = stop. Choose a gentler variation.`,
    ] },

    { type: 'h1', text: 'Stretching & mobility' },
    { type: 'p', text: `5-10 min after every session, hold each position for 20-30 s.` },
    { type: 'table', headers: ['Stretch', 'Area', 'Duration'], rows: [
      ['Standing quad', 'Front of thigh', '30 s / side'],
      ['Straight-leg hamstring', 'Back of thigh', '30 s / side'],
      ['Low lunge', 'Hips', '30 s / side'],
      ['Chest at the wall', 'Chest, shoulders', '30 s / side'],
      ['Cat-cow', 'Spine', '45 s'],
    ] },

    { type: 'h1', text: 'Morning mobility routine (5 min)' },
    { type: 'p', text: `Do this right after waking up or on rest days: 5 minutes to wake up the body, improve your posture, and prep your joints. No equipment, flow through it smoothly.` },
    { type: 'table', headers: ['Movement', 'Target', 'Duration'], rows: [
      ['Cat-cow', 'Spine', '45 s'],
      ['Shoulder & hip circles', 'Joints', '45 s'],
      ['Low lunge + rotation', 'Hips, back', '30 s / side'],
      ['Deep squat hold', 'Hips, ankles', '45 s'],
      ['Standing pelvic tilt', 'Lower back', '45 s'],
      ['Neck stretch', 'Neck', '30 s'],
    ] },

    { type: 'h1', text: 'Measuring your progress (beyond the scale)' },
    { type: 'p', text: `The scale only tells part of the story. In bodyweight training, your best indicators are performance and the mirror.` },
    { type: 'list', items: [
      `Performance: more reps, harder variations, longer plank holds, less rest.`,
      `Photos: same lighting, same angle, same time of day, every 4 weeks.`,
      `Measurements: waist, hips, thighs, arms - often more telling than weight.`,
      `How you feel: energy, sleep, looser clothes, improved posture.`,
      `Weigh yourself only once a week, fasted, on the same day: weight fluctuates daily.`,
    ] },

    { type: 'h1', text: 'Tracking your progress' },
    { type: 'p', text: `Fill in these tables every week, under the same conditions.` },
    { type: 'h2', text: 'Weight & measurements' },
    { type: 'tracker', columns: ['Date', 'Weight (kg)', 'Waist', 'Energy /10'], rows: 8 },
    { type: 'h2', text: 'Performance (reps or time)' },
    { type: 'tracker', columns: ['Exercise', 'W1', 'W3', 'W5', 'W8'], rows: 6 },

    { type: 'h1', text: 'Weekly checklist' },
    { type: 'p', text: `Tick each box at the end of the week. Goal: at least 5 out of 7.` },
    { type: 'checklist', items: [
      `I did my 4 sessions this week.`,
      `I kept clean technique.`,
      `I progressed (reps, variation, or shorter rest).`,
      `I ate protein at every meal.`,
      `I drank 2 L of water a day.`,
      `I slept 7 to 9 h most nights.`,
      `I logged my performances.`,
    ] },

    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My notes, feelings, and wins for the week'], rows: 16 },

    { type: 'h1', text: 'And after your 8 weeks?' },
    { type: 'list', items: [
      `Run another cycle with the hardest variations and 5 rounds throughout.`,
      `Got access to equipment? Move on to the Beginner Strength Training program.`,
      `Fat-loss goal: follow up with the Weight Loss program.`,
      `Always keep your home "Plan B" routine for days without a gym.`,
    ] },

    { type: 'note', text: `8 weeks with zero excuses is already a win. Retake your measurements and photo, compare them to your starting point, and keep the momentum going. Create your account at xenotif.com.` },
  ],
}
