import type { Guide } from '@/lib/boutique/guides'

// d3 — Fat-Burning HIIT Program 6 weeks (EN mirror of hiit-6s.ts).
// 24 sessions of 20-30 min, 100% bodyweight, no equipment, 3 levels, timers, video QR.
export const hiit6sEn: Guide = {
  id: 'd3',
  title: 'Fat-Burning HIIT Program — 6 Weeks',
  subtitle: '24 sessions of 20-30 min, 100% bodyweight, no equipment at all',
  author: 'XENOTIF Coach — CrossFit & strength-conditioning certified',
  level: 'Beginner → Advanced',
  duration: '6 weeks · 24 sessions · 20-30 min',
  coverImage: 'hiit-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Burn the most in the least time' },
    { type: 'p', text: `In 6 weeks, this program will transform your fitness and melt fat — no gym, no equipment, wherever you are, in short but intense 20- to 30-minute sessions. Inside you'll find the 24 detailed sessions with their timers, the technique of every movement, and three levels to progress from beginner to advanced.` },
    { type: 'p', text: `Every exercise has a QR code to its demo video. Keep the guide on your phone and start your timer: let's go.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Burn fat, build cardio' },
      { label: 'Level', value: 'Beginner to advanced' },
      { label: 'Duration', value: '6 weeks · 24 sessions' },
      { label: 'Session', value: '20 to 30 minutes' },
      { label: 'Equipment', value: 'None (bodyweight)' },
      { label: 'Frequency', value: '4 sessions per week' },
    ] },
    { type: 'h2', text: `What you'll get` },
    { type: 'list', items: [
      `Visible fat loss (HIIT burns during AND after the effort).`,
      `Markedly improved cardio and stamina.`,
      `A more toned, more athletic body.`,
      `An express routine you can keep even on busy days.`,
    ] },
    { type: 'h2', text: 'How to use this guide' },
    { type: 'list', items: [
      `Choose your level (beginner / intermediate / advanced) — see the dedicated chapter.`,
      `Follow the 24 sessions in order (4 per week).`,
      `Run an interval timer (work / rest) for each session.`,
      `Scan an exercise's QR code to review the technique.`,
      `Warm up 5 min before, stretch 5 min after.`,
    ] },
    { type: 'note', text: `Intensity = key. During the work phases, you should be unable to hold a conversation. During recovery, catch your breath actively (march in place, deep breathing).` },

    { type: 'h1', text: 'Why HIIT works' },
    { type: 'p', text: `HIIT (High Intensity Interval Training) alternates intense efforts with short recoveries. Result: you burn calories during the effort AND for up to 24 h after, thanks to the EPOC effect (excess post-exercise oxygen consumption).` },
    { type: 'list', items: [
      `A 20-min session can burn as much as a 45-min jog.`,
      `The body keeps burning calories after the session (afterburn).`,
      `HIIT preserves muscle better than long, monotonous cardio.`,
      `No equipment: you can train anywhere, anytime.`,
    ] },

    { type: 'chapter', title: 'Choose your level & your timer', src: 'hiit-1.jpg', intro: `Every session follows an interval format. Choose the work/rest ratio that fits your level, then set your timer (or the XENOTIF app). You can level up over the weeks.` },
    { type: 'table', headers: ['Level', 'Work', 'Rest', 'Rounds / block'], rows: [
      ['Beginner', '20 s', '40 s', '3'],
      ['Intermediate', '40 s', '20 s', '4'],
      ['Advanced', '45 s', '15 s', '4 to 5'],
    ] },
    { type: 'h2', text: 'Timer rule' },
    { type: 'list', items: [
      `Set an interval timer with your ratio (e.g. 40 s / 20 s).`,
      `Rest between exercise blocks: 60 s (beginner), 45 s (interm.), 30 s (advanced).`,
      `Level up when a session feels "comfortable".`,
    ] },

    { type: 'h1', text: 'Warm-up (5 min)' },
    { type: 'p', text: `Essential before every HIIT session, especially with explosive movements.` },
    { type: 'table', headers: ['Movement', 'Duration'], rows: [
      ['Walk / jog in place', '60 s'],
      ['High knees', '45 s'],
      ['Arm & hip circles', '45 s'],
      ['Slow squats', '45 s'],
      ['Dynamic lunges + butt kicks', '60 s'],
    ] },

    { type: 'chapter', title: 'The 24 sessions', src: 'hiit-cover.jpg', intro: `Here are your 24 sessions (4 per week). Apply YOUR work/rest ratio (level chapter). Each line = one block to repeat for the number of rounds of your level. Warm up before, stretch after.` },
    { type: 'h2', text: 'Week 1 — Adaptation' },
    { type: 'table', headers: ['Session', 'Blocks', 'Duration'], rows: [
      ['S1 · Full body', 'Squats · Knee push-ups · Mountain climbers · Plank', '20 min'],
      ['S2 · Cardio', 'Jumping jacks · High knees · Butt kicks · Lunges', '20 min'],
      ['S3 · Lower + core', 'Squats · Lunges · Glute bridge · Side plank', '20 min'],
      ['S4 · Upper + core', 'Push-ups · Chair dips · Pike push-ups · Plank', '20 min'],
    ] },
    { type: 'h2', text: 'Week 2 — Volume' },
    { type: 'table', headers: ['Session', 'Blocks', 'Duration'], rows: [
      ['S5 · Full body', 'Jump squats · Push-ups · Mountain climbers · Burpees', '22 min'],
      ['S6 · Cardio', 'Jumping jacks · High knees · Skaters · Butt kicks', '22 min'],
      ['S7 · Lower + core', 'Jump lunges · Squats · Glute bridge · Leg raises', '22 min'],
      ['S8 · Upper + core', 'Push-ups · Dips · Diamond push-ups · Plank up-downs', '22 min'],
    ] },
    { type: 'h2', text: 'Week 3 — Intensity' },
    { type: 'table', headers: ['Session', 'Blocks', 'Duration'], rows: [
      ['S9 · Full body', 'Burpees · Jump squats · Mountain climbers · Push-ups', '25 min'],
      ['S10 · Cardio', 'High knees · Skaters · Jumping jacks · Sprint in place', '25 min'],
      ['S11 · Lower + core', 'Jump lunges · Squats · Single-leg glute bridge · Plank', '25 min'],
      ['S12 · Upper + core', 'Decline push-ups · Dips · Pike push-ups · Mountain climbers', '25 min'],
    ] },
    { type: 'h2', text: 'Week 4 — Circuits' },
    { type: 'table', headers: ['Session', 'Blocks', 'Duration'], rows: [
      ['S13 · Full body', 'Burpees · Jump lunges · Push-ups · Plank up-downs', '25 min'],
      ['S14 · Cardio', 'Sprint in place · Skaters · Jumping jacks · High knees', '25 min'],
      ['S15 · Lower + core', 'Jump squats · Lunges · Glute bridge · Leg raises', '25 min'],
      ['S16 · Upper + core', 'Push-ups · Diamond push-ups · Dips · Side plank', '25 min'],
    ] },
    { type: 'h2', text: 'Week 5 — Peak' },
    { type: 'table', headers: ['Session', 'Blocks', 'Duration'], rows: [
      ['S17 · Full body', 'Burpees · Jump squats · Push-ups · Mountain climbers', '28 min'],
      ['S18 · Cardio', 'Sprint in place · High knees · Skaters · Jumping jacks', '28 min'],
      ['S19 · Lower + core', 'Jump lunges · Squats · Single-leg glute bridge · Plank', '28 min'],
      ['S20 · Upper + core', 'Decline push-ups · Diamond push-ups · Dips · Plank up-downs', '28 min'],
    ] },
    { type: 'h2', text: 'Week 6 — Finish' },
    { type: 'table', headers: ['Session', 'Blocks', 'Duration'], rows: [
      ['S21 · Full body', 'Burpees · Jump squats · Push-ups · Plank up-downs', '30 min'],
      ['S22 · Cardio max', 'Sprint in place · Skaters · High knees · Jumping jacks', '30 min'],
      ['S23 · Lower + core', 'Jump lunges · Jump squats · Glute bridge · Leg raises', '30 min'],
      ['S24 · Final challenge', 'Burpees · Mountain climbers · Push-ups · Jump squats · Plank', '30 min'],
    ] },
    { type: 'note', text: `Track your progress: count your reps on a fixed block (e.g. burpees in 40 s) in S1, S3 and S6. You'll see the difference.` },

    { type: 'h1', text: 'Anatomy of a typical session' },
    { type: 'p', text: `Every session follows the same structure. Detailed example of an intermediate "Full body" session (40 s work / 20 s rest, 4 rounds):` },
    { type: 'table', headers: ['Phase', 'Content', 'Duration'], rows: [
      ['Warm-up', 'Light cardio + mobility + activation', '5 min'],
      ['Block 1', 'Burpees — 40 s / 20 s × 4', '4 min'],
      ['Block 2', 'Jump squats — 40 s / 20 s × 4', '4 min'],
      ['Block 3', 'Push-ups — 40 s / 20 s × 4', '4 min'],
      ['Block 4', 'Mountain climbers — 40 s / 20 s × 4', '4 min'],
      ['Cool-down', 'Walk + stretching', '5 min'],
    ] },
    { type: 'p', text: `Rest between blocks: 45 s (interm.). Total ≈ 26 min. Adapt ratios and rounds to YOUR level (chapter "Choose your level").` },
    { type: 'note', text: `Videos: every exercise in the library below has a QR code that opens its HD demo video. If you're unsure about the execution, scan it before starting your timer.` },

    { type: 'h1', text: 'Exercise library' },
    { type: 'p', text: `Master these movements. Scan the QR for the demo video.` },
    { type: 'exercise', name: 'Burpee', muscles: 'Whole body, cardio', level: 'Advanced', technique: `Standing → hands on the floor → jump feet back (plank) → push-up (optional) → bring the feet in → vertical jump, arms extended. Chain it smoothly.`, mistakes: `Rounded back, landing with stiff legs. Cushion the landing, steady rhythm rather than fast and sloppy.` },
    { type: 'exercise', name: 'Jump squats', muscles: 'Legs, glutes, cardio', level: 'Intermediate', technique: `Squat then explosive jump, soft landing in the squat position, repeat. Beginner version: squat without the jump.`, mistakes: `Landing with stiff knees, leaning torso, range too short.` },
    { type: 'exercise', name: 'Mountain climbers', muscles: 'Abs, shoulders, cardio', level: 'Intermediate', technique: `In a high plank, alternately drive one knee toward the chest, faster and faster, hips low, core braced.`, mistakes: `Hips high, sagging back, messy rhythm.` },
    { type: 'exercise', name: 'Jumping jacks', muscles: 'Cardio, shoulders, legs', level: 'Beginner', technique: `Jump spreading legs and arms, then return. Soft landing, steady rhythm.`, mistakes: `Stiff landing, incomplete arm range.` },
    { type: 'exercise', name: 'High knees', muscles: 'Cardio, hip flexors, abs', level: 'Beginner', technique: `Run in place driving the knees to hip height, fast rhythm, braced core, arms swinging along.`, mistakes: `Torso leaning back, knees too low, heavy stride.` },
    { type: 'exercise', name: 'Skaters', muscles: 'Legs, glutes, cardio, balance', level: 'Intermediate', technique: `Lateral bound from one foot to the other, free leg behind, like a speed skater. Soft landing, braced core.`, mistakes: `Stiff landing, lacking lateral range, torso collapsing.` },
    { type: 'exercise', name: 'Push-ups', muscles: 'Chest, triceps, shoulders, core', level: 'Beginner - Intermediate', technique: `Body braced, lower the chest toward the floor, elbows ~45°, push. Variations: knees (easy) → floor → decline (hard).`, mistakes: `Hips sagging, elbows too flared, short range.` },
    { type: 'exercise', name: 'Diamond push-ups', muscles: 'Triceps, chest', level: 'Advanced', technique: `Hands close together forming a diamond under the chest, lower then push. Strongly targets the triceps.`, mistakes: `Elbows flaring out, partial range, arching back.` },
    { type: 'exercise', name: 'Chair dips', muscles: 'Triceps, shoulders', level: 'Beginner - Intermediate', technique: `Hands on the edge of a chair, legs in front, lower by bending the elbows back, push back up. Straight legs = harder.`, mistakes: `Shoulders shrugging up, short descent, unstable chair.` },
    { type: 'exercise', name: 'Jump lunges', muscles: 'Legs, glutes, cardio', level: 'Advanced', technique: `From a lunge, jump and switch legs in the air, soft landing in a lunge. Beginner version: alternating lunges without the jump.`, mistakes: `Front knee passing too far forward, leaning torso, stiff landing.` },
    { type: 'exercise', name: 'Plank up-downs', muscles: 'Abs, shoulders, core', level: 'Intermediate', technique: `In a plank, alternately move from forearms to extended hands and back, keeping the hips stable.`, mistakes: `Hips swaying, sagging back, rushing the rhythm.` },
    { type: 'exercise', name: 'Leg raises', muscles: 'Lower abs, core', level: 'Beginner', technique: `Lying down, hands under the glutes, raise the legs toward vertical, lower slowly without touching the floor. Lower back pressed down.`, mistakes: `Arching the back, lowering too fast, swinging.` },
    { type: 'exercise', name: 'Sprint in place', muscles: 'Cardio, legs', level: 'Intermediate', technique: `Run in place as fast as possible, quick stride on the balls of the feet, active arms, braced core. Maximum intensity.`, mistakes: `Heavy stride, stiff torso, insufficient intensity.` },
    { type: 'exercise', name: 'Butt kicks', muscles: 'Cardio, hamstrings', level: 'Beginner', technique: `Run in place bringing the heels toward the glutes, fast rhythm, active core.`, mistakes: `Leaning torso, range too short, sluggish rhythm.` },
    { type: 'exercise', name: 'Pike push-ups', muscles: 'Shoulders, triceps', level: 'Intermediate', technique: `In an inverted "V" (hips high), lower the crown of your head toward the floor by bending the elbows, then push. Works the shoulders.`, mistakes: `Rounded back, short range, elbows too flared.` },
    { type: 'exercise', name: 'Glute bridge', muscles: 'Glutes, hamstrings', level: 'Beginner', technique: `On your back, knees bent, push through the heels to lift the hips, squeeze the glutes at the top, lower without resting.`, mistakes: `Arching the back, lifting too high, feet too far out.` },
    { type: 'exercise', name: 'Decline push-ups', muscles: 'Upper chest, shoulders, triceps', level: 'Advanced', technique: `Feet elevated (chair/couch), body braced, lower the chest toward the floor then push. The higher the feet, the harder.`, mistakes: `Hips sagging, short range, elbows too flared.` },
    { type: 'exercise', name: 'Side plank', muscles: 'Obliques, core', level: 'Beginner', technique: `On your side, supported on one forearm, body aligned, hips lifted. Hold, then switch sides.`, mistakes: `Hips dropping, body tipping forward.` },

    { type: 'h1', text: 'Adapting by level' },
    { type: 'p', text: `Every movement has an easier and a harder version: you can follow all 24 sessions whatever your level.` },
    { type: 'table', headers: ['Exercise', 'Easier', 'Harder'], rows: [
      ['Burpee', 'No push-up / no jump', 'With push-up + tuck jump'],
      ['Jump squat', 'Bodyweight squat', 'Jump squat + 180°'],
      ['Push-up', 'On knees / incline', 'Decline / diamond'],
      ['Jump lunge', 'Alternating lunge', 'Jump lunge + tempo'],
      ['Mountain climber', 'Slower', 'Fast cross-body'],
    ] },

    { type: 'chapter', title: 'Nutrition to burn', src: 'nutrition.jpg', intro: `HIIT speeds up fat loss, but the plate still rules. No complicated diet needed: apply these benchmarks and the definition will show up faster.` },
    { type: 'meta', items: [
      { label: 'Deficit', value: '300 to 500 kcal / day' },
      { label: 'Protein', value: '1.8 to 2 g per kg' },
      { label: 'Hydration', value: '2 to 3 L per day' },
      { label: 'Sleep', value: '7 to 8 h' },
    ] },
    { type: 'list', items: [
      `A protein source at every meal (preserves muscle).`,
      `Plenty of vegetables for volume and satiety.`,
      `Carbs around the HIIT session for energy.`,
      `Cut liquid sugar and alcohol — the fastest win.`,
      `Hydrate: HIIT makes you sweat a lot.`,
    ] },
    { type: 'h2', text: '4 express fat-burning recipes' },
    { type: 'h2', text: 'Post-HIIT skyr-fruit bowl' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 300 kcal' }, { label: 'Protein', value: '30 g' }] },
    { type: 'list', items: [`200 g skyr`, `Berries`, `30 g oats`] },
    { type: 'p', text: `Mix. Refills protein after the session.` },
    { type: 'h2', text: 'Veg omelette' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 320 kcal' }, { label: 'Protein', value: '28 g' }] },
    { type: 'list', items: [`3 eggs`, `Spinach, bell pepper`, `Green salad`] },
    { type: 'p', text: `Sauté the vegetables, pour in the eggs, serve with a salad.` },
    { type: 'h2', text: 'Chicken-rice-veg bowl' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 470 kcal' }, { label: 'Protein', value: '40 g' }] },
    { type: 'list', items: [`130 g chicken`, `100 g rice (dry)`, `Vegetables`, `Soy sauce`] },
    { type: 'p', text: `Cook the rice, sear the chicken and vegetables, assemble.` },
    { type: 'h2', text: 'Protein shake' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 200 kcal' }, { label: 'Protein', value: '25 g' }] },
    { type: 'list', items: [`1 scoop whey`, `250 ml water or skim milk`, `Ice`] },
    { type: 'p', text: `Shake. Handy right after training.` },

    { type: 'h1', text: 'Walking & NEAT' },
    { type: 'p', text: `Beyond the HIIT sessions, your daily activity (NEAT) makes a big difference to energy expenditure — without fatigue or harming your recovery.` },
    { type: 'list', items: [
      `Aim for 8,000 to 10,000 steps/day: stairs, walking commutes, a walk after meals.`,
      `On non-HIIT days, do 30 min of brisk walking.`,
      `Break it up: 3 × 10 min of walking is worth a 30-min block.`,
      `Walking helps you recover from HIIT (circulation, stress management).`,
    ] },

    { type: 'h1', text: 'Recovery' },
    { type: 'list', items: [
      `HIIT is demanding: keep at least 1 rest day between 2 hard sessions.`,
      `Sleep 7 to 8 h: recovery drives your performance and fat loss.`,
      `Stretch and foam-roll if you have one.`,
      `A walk on off days maintains expenditure without fatigue.`,
    ] },

    { type: 'h1', text: 'Mistakes to avoid' },
    { type: 'list', items: [
      `Skipping the warm-up: high injury risk on explosive movements.`,
      `Rushing technique to go faster: quality before speed.`,
      `Doing HIIT every day: 4 sessions/week is enough, rest is part of the plan.`,
      `Neglecting the plate: HIIT doesn't offset a caloric surplus.`,
      `Stiff landings on jumps: always cushion to protect knees and ankles.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: ['You run into…', 'The solution'], rows: [
      ['Too hard to hold the effort', 'Drop a level (ratio with more rest)'],
      ['Knee pain (jumps)', 'No-impact versions (squat, high knees)'],
      ['No fat loss', 'Check the plate: it decides'],
      ['Too easy', 'Level up, add a round'],
    ] },

    { type: 'h1', text: 'Staying motivated' },
    { type: 'list', items: [
      `Set a numeric challenge (e.g. "+5 burpees in 40 s in 6 weeks").`,
      `Take a photo and your measurements every 2 weeks.`,
      `Put on an energetic playlist: the beat boosts intensity.`,
      `20 minutes is short: remember you'll be done before you have time to quit.`,
    ] },

    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: "I'm a beginner, is it too hard?" },
    { type: 'p', text: `No: the beginner level (20 s work / 40 s rest) is accessible, and every exercise has a regressed version. Start there, level up when you feel ready.` },
    { type: 'h2', text: 'How many times a week?' },
    { type: 'p', text: `4 sessions a week, with at least one rest day between hard sessions. No need to do more: recovery is part of the results.` },
    { type: 'h2', text: 'Is HIIT enough to lose fat?' },
    { type: 'p', text: `HIIT greatly accelerates expenditure, but fat loss is 70% decided on the plate. Combine HIIT + a slight dietary deficit.` },
    { type: 'h2', text: 'I live in an apartment, the jumps disturb the neighbors.' },
    { type: 'p', text: `Replace all jumping movements with their no-impact versions (squats, high knees instead of jumping jacks). The intensity stays high.` },
    { type: 'h2', text: 'Do I need equipment?' },
    { type: 'p', text: `None. Just a stable chair for the dips (optional) and an interval timer (your phone is enough).` },

    { type: 'h1', text: 'Cool-down & stretching' },
    { type: 'p', text: `5 minutes after every session to bring the heart down and limit soreness. Hold each stretch 20-30 s.` },
    { type: 'table', headers: ['Stretch', 'Area', 'Duration'], rows: [
      ['Slow walk', 'Heart', '1-2 min'],
      ['Standing quad', 'Front of thigh', '30 s / side'],
      ['Straight-leg hamstring', 'Back of thigh', '30 s / side'],
      ['Calves at the wall', 'Calves', '30 s / side'],
      ['Chest & shoulders', 'Upper body', '30 s / side'],
      ['Deep breathing', 'Recovery', '1 min'],
    ] },

    { type: 'h1', text: 'Safety & impact' },
    { type: 'list', items: [
      `Always warm up before explosive movements (burpees, jumps).`,
      `Soft landing on the balls of the feet, knees bent, on every jump.`,
      `Hard floor or apartment: replace jumps with no-impact versions.`,
      `Keep the back braced and neutral on push-ups, lunges and planks.`,
      `Sharp joint pain = stop. Choose a gentler variation or rest.`,
    ] },

    { type: 'h1', text: 'And after your 6 weeks?' },
    { type: 'list', items: [
      `Redo the benchmark test (reps in 40 s): compare to week 1.`,
      `Start a new cycle at the next level (tougher ratio, more rounds).`,
      `Combine with strength work (Home Fitness / Strength) to tone up.`,
      `Keep 2 HIIT sessions/week for maintenance once your goal is reached.`,
    ] },

    { type: 'h1', text: 'Understanding intensity' },
    { type: 'p', text: `HIIT only works if the effort is REALLY intense. To gauge it without a heart-rate monitor, use the "talk test": your ability to speak indicates your intensity.` },
    { type: 'table', headers: ['Zone', 'Feel', 'Talk test', 'Use'], rows: [
      ['Low', 'Very easy', 'You can sing', 'Warm-up, walking'],
      ['Moderate', 'Sustained', 'Short sentences', 'Active recovery'],
      ['High', 'Hard, breathless', 'A few words', 'HIIT work phases'],
      ['Maximal', 'Very hard', 'Cannot speak', 'Sprints, finishers'],
    ] },
    { type: 'list', items: [
      `On the effort: aim for "high to maximal" — you shouldn't be able to chat.`,
      `On recovery: come back down to "moderate", breathe deeply.`,
      `If you can hold a conversation during the effort, you're not pushing hard enough.`,
    ] },

    { type: 'h1', text: 'Your typical week' },
    { type: 'p', text: `Spread your 4 sessions with at least one rest day between the hardest ones. Example week:` },
    { type: 'table', headers: ['Day', 'On the program'], rows: [
      ['Monday', 'HIIT session (Full body)'],
      ['Tuesday', 'Walk 30 min / rest'],
      ['Wednesday', 'HIIT session (Cardio)'],
      ['Thursday', 'Active rest'],
      ['Friday', 'HIIT session (Lower + core)'],
      ['Saturday', 'HIIT session (Upper + core)'],
      ['Sunday', 'Rest + tracking'],
    ] },

    { type: 'h1', text: 'Fat-burning finishers (bonus)' },
    { type: 'p', text: `On days when you have 5 extra minutes, add a finisher at the end of the session for a spike in expenditure. Tabata format: 20 s max effort / 10 s rest, 8 rounds.` },
    { type: 'table', headers: ['Finisher', 'Format', 'Target'], rows: [
      ['Tabata burpees', '20 s / 10 s × 8', 'Whole body'],
      ['Tabata jump squats', '20 s / 10 s × 8', 'Legs'],
      ['Tabata mountain climbers', '20 s / 10 s × 8', 'Abs, cardio'],
      ['Tabata sprint in place', '20 s / 10 s × 8', 'Cardio max'],
    ] },
    { type: 'note', text: `A Tabata finisher lasts only 4 minutes but wipes you out: perfect to finish strong without lengthening the session.` },

    { type: 'h1', text: 'Tracking your progress' },
    { type: 'p', text: `Log your performances and measurements every week.` },
    { type: 'h2', text: 'Weight & energy' },
    { type: 'tracker', columns: ['Date', 'Weight (kg)', 'Waist (cm)', 'Energy /10'], rows: 7 },
    { type: 'h2', text: 'Benchmark test (reps in 40 s)' },
    { type: 'tracker', columns: ['Exercise', 'W1', 'W3', 'W6'], rows: 5 },

    { type: 'h1', text: 'Weekly checklist' },
    { type: 'p', text: `Tick each box at the end of the week. Goal: at least 5 out of 7.` },
    { type: 'checklist', items: [
      `I did my 4 sessions this week.`,
      `I warmed up before every session.`,
      `I gave maximum intensity on the efforts.`,
      `I ate protein at every meal.`,
      `I kept a slight caloric deficit.`,
      `I drank 2 L+ of water per day.`,
      `I logged my performances.`,
    ] },

    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My sessions, sensations and records for the week'], rows: 16 },

    { type: 'note', text: `6 weeks done? Redo the benchmark test to measure your progress, then start a new cycle at the next level, or move on to the Cardio Endurance / Home Fitness program. Create your account at xenotif.com.` },
  ],
}
