import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Intermediate Strength Training Program (EN mirror of musculation-intermediaire.ts). Premium XENOTIF® template (~30 pages).
export const musculationIntermediaireEn: Guide = {
  id: 'musculation-intermediaire',
  title: 'Intermediate Strength Training Program',
  subtitle: '12 weeks to break through a plateau: more volume, more muscle, more strength',
  author: 'XENOTIF Coach - Certified strength & conditioning',
  level: 'Intermediate',
  duration: '12 weeks · 4 to 5 sessions/week',
  coverImage: 'cover.jpg',
  blocks: [
    { type: 'h1', text: 'Level up' },
    { type: 'p', text: `You've got the basics down and want to progress faster? This 12-week intermediate program increases your training volume, introduces a structured split (Push / Pull / Legs or Upper/Lower) and intensity techniques. The goal: more muscle, more strength, a denser physique - without plateauing.` },
    { type: 'p', text: `Every exercise comes with a QR code linking to its demo video on XENOTIF®. Log your loads: at your level, precise progressive overload is what makes the difference.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Hypertrophy & strength' },
      { label: 'Level', value: 'Intermediate (6+ months)' },
      { label: 'Duration', value: '12 weeks (3 blocks)' },
      { label: 'Frequency', value: '4 to 5 sessions/week' },
      { label: 'Equipment', value: 'Full gym recommended' },
      { label: 'Split', value: 'Push / Pull / Legs' },
    ] },
    { type: 'h2', text: 'Program goals' },
    { type: 'list', items: [
      `Gain 2 to 4 kg of muscle over 12 weeks.`,
      `Increase your strength on the key lifts (squat, bench press, deadlift, pull-ups).`,
      `Improve your mind-muscle connection and execution quality.`,
      `Learn to periodize your training for long-term progress.`,
    ] },
    { type: 'h2', text: 'Are you ready for this level?' },
    { type: 'list', items: [
      `You've been training consistently for at least 6 months.`,
      `You have solid technique on the basic lifts.`,
      `You can train 4 to 5 times a week.`,
      `If not, start with the Beginner Strength Training program.`,
    ] },
    { type: 'note', text: `Golden rule at the intermediate level: progress is no longer automatic. You have to force it - progressive overload, sufficient volume, and recovery and nutrition dialed in.` },

    { type: 'h1', text: 'How it works' },
    { type: 'list', items: [
      `Push / Pull / Legs split: push, pull, legs - repeated 1.5 to 2 times a week.`,
      `Volume: 12 to 20 sets per muscle group per week.`,
      `Sets × reps: "4 × 8" = 4 sets of 8 reps.`,
      `Tempo: 2-3 s on the eccentric (lowering), explosive but controlled on the concentric (lifting).`,
      `Rest: 2-3 min on the big lifts, 60-90 s on isolation work.`,
      `RPE 8-9: 1 to 2 reps in reserve, with the last set close to failure.`,
    ] },
    { type: 'h2', text: 'Intensity techniques' },
    { type: 'p', text: `To keep progressing at your level, use these techniques sparingly (1 to 2 per session, on isolation exercises).` },
    { type: 'table', headers: ['Technique', 'Principle', 'When'], rows: [
      ['Superset', '2 exercises back-to-back, no rest', 'Save time, boost the pump'],
      ['Drop set', 'Lower the weight at failure and keep going', 'Last set of isolation work'],
      ['Rest-pause', 'Mini 10-15 s pauses for extra reps', 'Finishing an exercise'],
      ['Slow tempo', '3-4 s eccentric', 'Connection & control'],
    ] },

    { type: 'h1', text: 'Warm-up' },
    { type: 'p', text: `A full warm-up before every session, plus warm-up sets on the first heavy exercise.` },
    { type: 'table', headers: ['Step', 'Detail', 'Duration'], rows: [
      ['Cardio', 'Bike / rower', '3-5 min'],
      ['Targeted mobility', 'Joint focus of the day (shoulders / hips)', '3 min'],
      ['Activation', 'Band work, core bracing', '2 min'],
      ['Warm-up sets', '40%, 60%, 80% of the 1st exercise', '3-4 sets'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'This training volume demands fuel to match.' },
    { type: 'h1', text: 'Nutrition' },
    { type: 'p', text: `At this training volume, your nutrition has to keep up. A slight surplus to build, high protein, and generous carbs around your sessions.` },
    { type: 'meta', items: [
      { label: 'Calories', value: 'Maintenance +200/+400 kcal' },
      { label: 'Protein', value: '1.8 to 2.2 g per kg' },
      { label: 'Carbs', value: '4 to 6 g/kg (energy)' },
      { label: 'Hydration', value: '3 L per day' },
    ] },
    { type: 'h2', text: 'The rules' },
    { type: 'list', items: [
      `Spread protein across 4-5 meals a day (~0.4 g/kg per meal).`,
      `Carbs before and after training for performance and recovery.`,
      `Quality fats (0.8-1 g/kg) for hormone health.`,
      `Peri-workout meal: protein + carbs within 1-2 h around your session.`,
    ] },
    { type: 'h2', text: 'Understanding your macros' },
    { type: 'table', headers: ['Macro', 'Role', 'Target'], rows: [
      ['Protein', 'Muscle building', '1.8-2.2 g/kg'],
      ['Carbs', 'Energy & volume (glycogen)', '4-6 g/kg'],
      ['Fats', 'Hormones, health', '0.8-1 g/kg'],
    ] },
    { type: 'note', text: `Weigh yourself 2-3× a week and take the weekly average. Aim for +0.25 to +0.4 kg/week. Beyond that, cut back on the surplus to limit fat gain.` },

    { type: 'h1', text: 'Recipes' },
    { type: 'h2', text: 'Peri-workout shake' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 500 kcal' }, { label: 'Protein', value: '40 g' }] },
    { type: 'list', items: [`1 scoop of whey`, `60 g rolled oats`, `1 banana`, `300 ml milk`] },
    { type: 'p', text: `Prep: blend everything together. Perfect right after your session to kick-start recovery.` },
    { type: 'h2', text: 'Beef, rice & vegetables' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 700 kcal' }, { label: 'Protein', value: '50 g' }] },
    { type: 'list', items: [`160 g of 5% fat beef`, `120 g rice (dry)`, `Vegetables`, `Soy sauce, spices`] },
    { type: 'p', text: `Prep: sear the beef, add the vegetables, serve over the rice. Your heavy-hitter meal of the day.` },
    { type: 'h2', text: 'Protein skyr' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 350 kcal' }, { label: 'Protein', value: '35 g' }] },
    { type: 'list', items: [`250 g skyr`, `1 scoop of whey`, `Berries`, `Almonds`] },
    { type: 'p', text: `Prep: mix the skyr and whey, add the berries and almonds. The ideal protein snack.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'More volume means more attention to recovery.' },
    { type: 'h1', text: 'Recovery' },
    { type: 'list', items: [
      `Sleep 7 to 9 h: non-negotiable at this training volume.`,
      `Give a muscle group 48-72 h before training it again.`,
      `Deload every 4-6 weeks (-40% volume) to avoid overtraining.`,
      `Watch for signs of excessive fatigue: poor sleep, strength loss, irritability.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: 'Push / Pull / Legs: a classic that works.' },
    { type: 'h1', text: '12-week plan (3 blocks)' },
    { type: 'p', text: `Three progressive blocks: volume, intensity, strength. Keep the same split, and progress your reps and loads.` },
    { type: 'table', headers: ['Block', 'Weeks', 'Focus', 'Reps'], rows: [
      ['Block 1', 'W1-W4', 'Volume & technique', '10 to 12'],
      ['Block 2', 'W5-W8', 'Hypertrophy', '8 to 10'],
      ['Block 3', 'W9-W12', 'Strength & density', '5 to 8'],
    ] },
    { type: 'h2', text: 'Typical week (5 days)' },
    { type: 'table', headers: ['Day', 'Session'], rows: [
      ['Monday', 'Push (chest, shoulders, triceps)'],
      ['Tuesday', 'Pull (back, biceps)'],
      ['Wednesday', 'Legs (legs, glutes)'],
      ['Thursday', 'Rest / light cardio'],
      ['Friday', 'Upper (upper body)'],
      ['Saturday', 'Lower (lower body) + abs'],
      ['Sunday', 'Rest + tracking'],
    ] },

    { type: 'h1', text: 'Your sessions in detail' },
    { type: 'h2', text: 'Push - Chest / Shoulders / Triceps' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Barbell bench press', '4', '6 to 8', '150 s'],
      ['Incline dumbbell press', '4', '8 to 10', '120 s'],
      ['Overhead press', '3', '8 to 10', '120 s'],
      ['Lateral raises', '4', '12 to 15', '60 s'],
      ['Dips / triceps extension', '3', '10 to 12', '75 s'],
    ] },
    { type: 'h2', text: 'Pull - Back / Biceps' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Pull-ups (or lat pulldown)', '4', '6 to 10', '150 s'],
      ['Barbell row', '4', '8 to 10', '120 s'],
      ['Seated cable row', '3', '10 to 12', '90 s'],
      ['Face pull', '3', '15', '60 s'],
      ['Biceps curl + hammer curl', '4', '10 to 12', '60 s'],
    ] },
    { type: 'h2', text: 'Legs - Legs / Glutes' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Squat', '4', '6 to 8', '180 s'],
      ['Romanian deadlift', '4', '8 to 10', '150 s'],
      ['Leg press', '3', '12', '120 s'],
      ['Leg curl', '3', '12 to 15', '75 s'],
      ['Calf raises', '4', '15 to 20', '45 s'],
    ] },

    { type: 'h1', text: '4-day variant (Upper / Lower)' },
    { type: 'p', text: `Can only train 4 times a week? Swap the PPL for this Upper/Lower split (Monday/Tuesday/Thursday/Friday). Each half of the body gets trained 2× a week - great for frequency and recovery.` },
    { type: 'h2', text: 'Upper body (A & B)' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Bench press / incline press', '4', '6 to 10', '150 s'],
      ['Pull-ups / lat pulldown', '4', '8 to 10', '120 s'],
      ['Overhead press', '3', '8 to 10', '120 s'],
      ['Barbell row / seated row', '3', '10', '90 s'],
      ['Lateral raises + curls + triceps', '3', '12', '60 s'],
    ] },
    { type: 'h2', text: 'Lower body (A & B)' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Squat / leg press', '4', '6 to 10', '180 s'],
      ['Romanian deadlift', '4', '8 to 10', '150 s'],
      ['Lunges / leg extension', '3', '12', '90 s'],
      ['Leg curl', '3', '12 to 15', '75 s'],
      ['Calves + abs', '4', '15', '45 s'],
    ] },

    { type: 'h1', text: 'Exercise library' },
    { type: 'p', text: `The program's key movements. Scan the QR for the demo video.` },
    { type: 'exercise', name: 'Barbell bench press', muscles: 'Chest, triceps, shoulders', level: 'Intermediate', video: `${D}/musculation`, technique: `Shoulder blades pinched together, slight arch, feet planted. Lower the bar to the bottom of your chest, elbows at ~45°, then press up. Control the eccentric.`, mistakes: `Elbows flared too wide, bouncing off the chest, hips lifting off the bench, partial range of motion.` },
    { type: 'exercise', name: 'Squat', muscles: 'Quads, glutes, hamstrings', level: 'Intermediate', video: `${D}/musculation`, technique: `Bar on your upper back, descend below parallel if your mobility allows, core braced, knees tracking over your feet, then drive up explosively.`, mistakes: `Knees caving in, rounded lower back at the bottom, heels lifting off the floor.` },
    { type: 'exercise', name: 'Deadlift', muscles: 'Posterior chain, back, glutes', level: 'Advanced', video: `${D}/musculation`, technique: `Bar over the middle of your foot, flat back, core braced, drive the floor away with your legs while keeping the bar close to your body, lock out hips and knees at the top.`, mistakes: `Rounded back, bar drifting away from the body, pulling with the lower back, hyperextending at the top.` },
    { type: 'exercise', name: 'Pull-ups', muscles: 'Lats, biceps', level: 'Intermediate', video: `${D}/musculation`, technique: `Overhand grip, start with shoulders packed down, drive your elbows down to bring your chin above the bar, then lower with control.`, mistakes: `Swinging (unintentional kipping), partial range of motion, shoulders shrugging up.` },
    { type: 'exercise', name: 'Barbell row', muscles: 'Back, biceps, rear delts', level: 'Intermediate', video: `${D}/musculation`, technique: `Torso at ~45°, flat back, pull the bar to your lower belly while squeezing your shoulder blades, lower slowly.`, mistakes: `Rounded back, torso rising up, pulling too high.` },
    { type: 'exercise', name: 'Overhead press', muscles: 'Shoulders, triceps', level: 'Intermediate', video: `${D}/musculation`, technique: `Standing, core braced tight, press the bar straight up without arching your lower back, lock out at the top.`, mistakes: `Lower-back arching, pressing forward, incomplete range of motion.` },
    { type: 'exercise', name: 'Romanian deadlift', muscles: 'Hamstrings, glutes, back', level: 'Intermediate', video: `${D}/musculation`, technique: `Push your hips back, flat back, lower the bar along your legs until you feel your hamstrings stretch, then return by squeezing your glutes.`, mistakes: `Rounded back, bending the knees like a squat, bar drifting away from the legs.` },
    { type: 'exercise', name: 'Leg press', muscles: 'Quads, glutes', level: 'Beginner', video: `${D}/musculation`, technique: `Feet shoulder-width apart on the platform, lower until your knees hit ~90° without your lower back lifting off, then press up without slamming your knees straight.`, mistakes: `Lower back lifting off, knees caving in, range of motion too short.` },
    { type: 'exercise', name: 'Lateral raises', muscles: 'Side delts', level: 'Beginner', video: `${D}/musculation`, technique: `Light dumbbells, raise your arms out to the sides up to shoulder height, elbows slightly bent, lower slowly. Light and clean.`, mistakes: `Too heavy, swinging the weight, raising above shoulder height.` },
    { type: 'exercise', name: 'Face pull', muscles: 'Rear delts, traps', level: 'Beginner', video: `${D}/musculation`, technique: `On the high cable, pull the rope toward your face while spreading your hands apart, elbows high, squeeze your shoulder blades. Excellent for shoulder health.`, mistakes: `Too heavy, pulling with the arms, elbows dropping.` },
    { type: 'exercise', name: 'Biceps curl', muscles: 'Biceps', level: 'Beginner', video: `${D}/musculation`, technique: `Elbows locked at your sides, curl up while squeezing, lower slowly (2-3 s). No swinging.`, mistakes: `Swinging the body, elbows drifting forward, lowering too fast.` },
    { type: 'exercise', name: 'Leg curl', muscles: 'Hamstrings', level: 'Beginner', video: `${D}/musculation`, technique: `Lying or seated depending on the machine, bend your knees to bring your heels toward your glutes, squeeze, then return with control.`, mistakes: `Hips lifting off, jerky reps, partial range of motion.` },
    { type: 'exercise', name: 'Incline dumbbell press', muscles: 'Upper chest, shoulders', level: 'Intermediate', video: `${D}/musculation`, technique: `Bench set at ~30°, dumbbells at chest height, press up while bringing the dumbbells slightly together, lower with control until you feel the stretch.`, mistakes: `Bench angled too steep (turns into a shoulder press), range too short, locking the elbows out at the top.` },
    { type: 'exercise', name: 'Seated cable row', muscles: 'Mid-back, biceps', level: 'Beginner', video: `${D}/musculation`, technique: `Seated, back straight, pull the handle toward your belly button while squeezing your shoulder blades, without leaning your torso back, then return while keeping tension.`, mistakes: `Rocking the torso, rounding the back, pulling too high.` },
    { type: 'exercise', name: 'Dips', muscles: 'Lower chest, triceps', level: 'Intermediate', video: `${D}/musculation`, technique: `On parallel bars, core braced, lower by bending your elbows to ~90°, lean slightly forward to target the chest, then press back up.`, mistakes: `Descending too deep (stresses the shoulders), jerky reps, shoulders shrugging up.` },
    { type: 'exercise', name: 'Hammer curl', muscles: 'Biceps, brachialis, forearms', level: 'Beginner', video: `${D}/musculation`, technique: `Dumbbells in a neutral grip (thumbs up), curl up while squeezing, lower slowly. Elbows locked in place.`, mistakes: `Swinging the body, elbows drifting forward, grip rotating.` },

    { type: 'h1', text: 'Abs & core' },
    { type: 'p', text: `Train your core 2-3×/week at the end of your sessions. A strong core improves your performance on every big lift and protects your back.` },
    { type: 'exercise', name: 'Plank', muscles: 'Abs, lower back', level: 'Beginner', video: `${D}/musculation`, technique: `Forearms on the floor, body aligned, abs and glutes braced. Hold while breathing steadily. Progress by holding longer or adding weight.`, mistakes: `Hips sagging, glutes too high, head lifted up.` },
    { type: 'exercise', name: 'Hanging leg raise', muscles: 'Lower abs, core', level: 'Intermediate', video: `${D}/musculation`, technique: `Hanging from the bar, raise your knees (or straight legs) toward your chest by rolling your pelvis, then lower with control without swinging.`, mistakes: `Swinging, raising only the legs without rolling the pelvis, lowering too fast.` },
    { type: 'list', items: [
      `Core circuit: plank 45 s + leg raises 12 + side plank 30 s/side, 3 rounds.`,
      `Add weight once bodyweight becomes easy.`,
    ] },

    { type: 'h1', text: '12-week breakdown' },
    { type: 'p', text: `Keep the same split, and progress your reps and loads according to the block.` },
    { type: 'table', headers: ['Week', 'Sets × Reps', 'Note'], rows: [
      ['W1-W2', '4 × 10-12', 'Volume, technique, RPE 7-8'],
      ['W3-W4', '4 × 10', '+ load, check-in at W4'],
      ['W5-W6', '4 × 8-10', 'Hypertrophy, 1 intensity technique/session'],
      ['W7-W8', '4 × 8', '+ load, RPE 8-9'],
      ['W9-W10', '5 × 6-8', 'Strength, longer rest'],
      ['W11', '5 × 5-6', 'Peak intensity'],
      ['W12', 'Deload + tests', 'Deload then strength tests, review'],
    ] },

    { type: 'h1', text: 'Progression & periodization' },
    { type: 'p', text: `At your level, linear progression is no longer enough: you need to periodize (alternate volume and intensity) and manage fatigue.` },
    { type: 'list', items: [
      `Progressive overload: add +2.5 kg or +1 rep once you hit the top of the rep range on every set.`,
      `Autoregulation: push harder when you're feeling good; keep an extra rep in reserve when you're fatigued.`,
      `Mandatory deload every 4-6 weeks: cut volume by 40% for a week.`,
      `Keep a training log: load × reps × sets. It's your compass.`,
    ] },

    { type: 'h1', text: 'Mistakes to avoid' },
    { type: 'list', items: [
      `Adding too much volume too fast: ramp up gradually or you'll accumulate fatigue.`,
      `Overusing intensity techniques: 1-2 per session is enough.`,
      `Skipping legs or horizontal rowing (leads to imbalances and injuries).`,
      `Neglecting the deload: overtraining sets you back instead of moving you forward.`,
      `Poor sleep/nutrition management: it sabotages your training volume.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: ['You run into…', 'The solution'], rows: [
      ['Strength plateau', 'Deload for 1 week, check sleep & calories'],
      ['Persistent fatigue', 'Reduce volume, add a rest day'],
      ['Shoulder pain', 'Add more face pulls, review your elbow angle'],
      ['Gaining fat too fast', 'Reduce the surplus, keep protein high'],
    ] },

    { type: 'h1', text: 'Staying motivated' },
    { type: 'list', items: [
      `Set numeric strength goals (e.g. squat 1.5× your bodyweight).`,
      `Photos & measurements every 4 weeks.`,
      `Switch up your music, train with a partner on the days you don't feel like it.`,
      `Keep in mind: 12 weeks of consistency beats 3 perfect months followed by quitting.`,
    ] },
    { type: 'h2', text: 'Build the habit' },
    { type: 'list', items: [
      `Block your 4-5 time slots like non-negotiable appointments.`,
      `Prep your bag and meals the night before.`,
      `Never break the chain for 2 sessions in a row.`,
    ] },

    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: 'PPL or Upper/Lower?' },
    { type: 'p', text: `Both work. PPL suits you if you can train 5-6×/week; Upper/Lower if you're aiming for 4×/week. This program combines both for a 5-day setup. Adapt it to your schedule.` },
    { type: 'h2', text: 'How many sets per muscle group?' },
    { type: 'p', text: `12 to 20 weekly sets per muscle group works for most intermediate lifters. Start at 12-14 and increase gradually if you're recovering well.` },
    { type: 'h2', text: 'Should I train to failure?' },
    { type: 'p', text: `Keep 1-2 reps in reserve on most sets. Save failure for the last set of isolation exercises, not for the heavy lifts (squat, deadlift).` },
    { type: 'h2', text: 'What supplements at this level?' },
    { type: 'p', text: `Creatine monohydrate (3-5 g/day) and whey remain the most useful. Caffeine pre-workout for performance. Everything else is secondary.` },
    { type: 'h2', text: 'Cardio without losing muscle?' },
    { type: 'p', text: `Yes: 2-3 sessions of moderate cardio (20-30 min) a week, kept separate from leg days if possible. Avoid excessive intense cardio, which hurts recovery.` },

    { type: 'h1', text: 'Conditioning & cardio' },
    { type: 'p', text: `A bit of cardio improves your recovery between sets, boosts your work capacity, and keeps fat gain in check during the surplus - without hurting your gains if you dose it well.` },
    { type: 'list', items: [
      `2 to 3 sessions of moderate cardio (20-30 min) a week, ideally on non-leg days.`,
      `Daily walking (8,000-10,000 steps): the foundation, with no impact on recovery.`,
      `Optional finisher: 5-8 min of intense cardio at the end of an upper-body session.`,
      `Avoid long, intense cardio sessions the day before leg day.`,
    ] },
    { type: 'table', headers: ['Type', 'Duration', 'Frequency', 'Effect'], rows: [
      ['Walking', '30-45 min', 'Daily', 'Expenditure, recovery'],
      ['Moderate cardio (bike/rower)', '20-30 min', '2-3×/week', 'Health, capacity'],
      ['HIIT finisher', '5-8 min', '1-2×/week', 'Conditioning'],
    ] },

    { type: 'h1', text: 'Stretching & mobility' },
    { type: 'p', text: `Work on mobility 2-3×/week to support full range of motion under load.` },
    { type: 'table', headers: ['Movement', 'Area', 'Duration'], rows: [
      ['Shoulder mobility (bar/band)', 'Shoulders', '1 min'],
      ['Hip mobility (deep lunge)', 'Hips', '30 s / side'],
      ['Ankle mobility', 'Ankles', '30 s / side'],
      ['Chest stretch', 'Chest', '30 s / side'],
      ['Dead hang', 'Back, shoulders', '30 s'],
      ['Thoracic rotation', 'Spine', '45 s'],
    ] },

    { type: 'h1', text: 'Safety & injury prevention' },
    { type: 'list', items: [
      `Warm up with ramp-up sets before every heavy lift.`,
      `Use a spotter or safety bars for squats and bench press.`,
      `Keep your technique perfect as you add weight: ego is what causes injury.`,
      `Respect your deloads and your sleep: recovery prevents 90% of injuries.`,
    ] },

    { type: 'h1', text: 'What comes after your 12 weeks?' },
    { type: 'p', text: `You've gained muscle and strength. To keep progressing, change up your stimulus and set yourself a new target.` },
    { type: 'list', items: [
      `Move on to the Advanced Strength Training program (more advanced techniques and higher volume).`,
      `Muscle goal: move into a proper Bulking phase.`,
      `Definition goal: switch to Weight Loss to reveal the muscle you've built.`,
      `Redo your measurements, photos, and strength tests to see how far you've come.`,
    ] },
    { type: 'note', text: `Tip: don't repeat the exact same program again. Vary the exercises, angles, and rep ranges to kick-start progress again.` },

    { type: 'h1', text: 'Supplements' },
    { type: 'p', text: `None are mandatory, but a few have real, proven value at your training level.` },
    { type: 'table', headers: ['Supplement', 'Benefit', 'Dose'], rows: [
      ['Creatine monohydrate', 'Strength & volume, the most studied', '3 to 5 g/day'],
      ['Whey', 'Hit your protein target easily', '1 to 2 scoops/day'],
      ['Caffeine', 'Performance & pre-workout energy', '3 mg/kg, 30-45 min before'],
      ['Omega-3 / Vitamin D', 'Recovery, joints, health', 'As needed'],
    ] },
    { type: 'note', text: `The foundation is still nutrition and training. Supplements are just a small bonus - never rely on them to make up for a poor program or bad sleep.` },

    { type: 'h1', text: 'Tracking your progress' },
    { type: 'p', text: `Log your loads every session and your measurements every week.` },
    { type: 'h2', text: 'Weight & measurements' },
    { type: 'tracker', columns: ['Date', 'Weight (kg)', 'Arm', 'Thigh', 'Chest', 'Waist'], rows: 7 },
    { type: 'h2', text: 'Strength on key lifts (kg × reps)' },
    { type: 'tracker', columns: ['Exercise', 'W1', 'W4', 'W8', 'W12'], rows: 6 },

    { type: 'h1', text: 'Weekly checklist' },
    { type: 'p', text: `Tick each box at the end of the week. Goal: at least 6 out of 8.` },
    { type: 'checklist', items: [
      `I did all my sessions this week.`,
      `I hit my target volume per muscle group.`,
      `I made progress on at least one key exercise.`,
      `I hit my protein target every day.`,
      `I ate in a slight, controlled surplus.`,
      `I slept 7 to 9 h most nights.`,
      `I respected my rest times.`,
      `I logged all my loads.`,
    ] },

    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My notes, loads and how I felt this week'], rows: 16 },

    { type: 'h1', text: 'Glossary' },
    { type: 'list', items: [
      `PPL: Push / Pull / Legs.`,
      `Volume: total number of sets per muscle per week.`,
      `Periodization: organizing training into blocks (volume, intensity, strength).`,
      `Superset: two exercises performed back-to-back with no rest.`,
      `Drop set: lowering the weight at failure to keep the set going.`,
      `Deload: a lighter week to recover.`,
      `Autoregulation: adjusting your effort based on how you feel that day (RPE).`,
    ] },

    { type: 'note', text: `Finished your 12 weeks? Deload, test your strength, take your measurements, then move on to the Advanced Strength Training program or a Bulking / Weight Loss phase based on your goal. Create your account at xenotif.com.` },
  ],
}
