import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Advanced Muscle-Building Program (EN mirror of musculation-avance.ts). Premium XENOTIF® template (~30 pages).
export const musculationAvanceEn: Guide = {
  id: 'musculation-avance',
  title: 'Advanced Muscle-Building Program',
  subtitle: '12 weeks of high intensity to break through a plateau and maximize muscle',
  author: 'XENOTIF Coach - Certified strength & conditioning coach',
  level: 'Advanced',
  duration: '12 weeks · 5 to 6 sessions/week',
  coverImage: 'musculation-avance-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Break through your plateau' },
    { type: 'p', text: `Training for years now and your progress is slowing down? This advanced program combines high volume, controlled intensity, periodization, and intensity techniques to reignite muscle growth and break through plateaus. It's demanding: built for seasoned lifters who can handle a serious training load and manage their recovery.` },
    { type: 'p', text: `Every exercise has a QR code linking to its video on XENOTIF®. At your level, the devil is in the details: execution, tempo, recovery, autoregulation.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Hypertrophy & max strength' },
      { label: 'Level', value: 'Advanced (2+ years)' },
      { label: 'Duration', value: '12 weeks (periodized)' },
      { label: 'Frequency', value: '5 to 6 sessions/week' },
      { label: 'Equipment', value: 'Full gym' },
      { label: 'Split', value: 'PPL (Push/Pull/Legs ×2)' },
    ] },
    { type: 'h2', text: 'Program goals' },
    { type: 'list', items: [
      `Reignite hypertrophy after a period of stagnation.`,
      `Increase strength on the main lifts (numeric targets).`,
      `Master periodization and autoregulation (RPE/RIR).`,
      `Improve weak points through specialization.`,
    ] },
    { type: 'h2', text: 'Are you really at an advanced level?' },
    { type: 'list', items: [
      `You've been training seriously for 2 years or more.`,
      `You have flawless technique on compound lifts.`,
      `You can train 5 to 6 times a week and recover well.`,
      `You know what RPE/RIR means and you keep a training log.`,
      `If not, the Intermediate Muscle-Building program is a better fit.`,
    ] },
    { type: 'note', text: `Golden rule for advanced lifters: progress no longer happens "on its own." Gains now come from precision - managing volume, intensity, fatigue, and weak points.` },

    { type: 'h1', text: 'How it works' },
    { type: 'list', items: [
      `PPL split repeated 2×: every muscle trained twice a week.`,
      `High volume: 16 to 22 sets per muscle group per week.`,
      `RIR (reps in reserve): 2-3 RIR at the start of a block, 0-1 by the end.`,
      `Controlled tempo: 2-3 s eccentric, optional pause, controlled concentric.`,
      `Rest: 2-3 min (compounds), 60-90 s (isolation).`,
      `Autoregulation: adjust load and volume to how you feel that day (RPE).`,
    ] },
    { type: 'h2', text: 'Intensity techniques' },
    { type: 'p', text: `Use them with precision: 2 to 3 per session max, mainly on isolation work and the last set of compound lifts.` },
    { type: 'table', headers: ['Technique', 'Principle', 'Application'], rows: [
      ['Drop set', 'Lower the load at failure, keep going', 'Last isolation set'],
      ['Rest-pause', '10-20 s micro-pauses for extra reps', 'Finisher'],
      ['Myo-reps', 'Activation set + mini-sets', 'Isolation, saves time'],
      ['Tempo / slow eccentric', '4-5 s descent', 'Mind-muscle connection, weak points'],
      ['Partials', 'Partial reps at the end of a set', 'Maximum pump'],
    ] },

    { type: 'h1', text: 'Warm-up & preparation' },
    { type: 'p', text: `At high intensity, warming up isn't optional. Add ascending warm-up sets before every heavy compound lift.` },
    { type: 'table', headers: ['Step', 'Detail', 'Duration'], rows: [
      ['Cardio', 'Bike / rower', '5 min'],
      ['Targeted mobility', `Today's joints`, '3-4 min'],
      ['Activation', 'Bands, core bracing', '2 min'],
      ['Warm-up sets', '40/55/70/85% of the first compound lift', '4 sets'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'High volume means nutrition has to be precise.' },
    { type: 'h1', text: 'Nutrition' },
    { type: 'p', text: `At this training volume, precision matters. Calculate your macros, adjust them as you progress, and dial in your timing around training.` },
    { type: 'meta', items: [
      { label: 'Calories', value: 'Surplus +200/+350 (or recomp)' },
      { label: 'Protein', value: '2 to 2.4 g per kg' },
      { label: 'Carbs', value: '5 to 7 g/kg on training days' },
      { label: 'Hydration', value: '3 to 4 L per day' },
    ] },
    { type: 'h2', text: 'Strategy' },
    { type: 'list', items: [
      `Spread protein across 4-6 meals (~0.4 g/kg/meal) to maximize synthesis.`,
      `Optional carb cycling: more carbs on heavy days (legs, back).`,
      `Peri-workout meals: carbs + protein before AND after the big sessions.`,
      `Adjust every 2 weeks based on your weekly average weight.`,
    ] },
    { type: 'h2', text: 'Understanding your macros' },
    { type: 'table', headers: ['Macro', 'Role', 'Target'], rows: [
      ['Protein', 'Building & maintenance', '2-2.4 g/kg'],
      ['Carbs', 'Performance & volume', '5-7 g/kg (ON days)'],
      ['Fats', 'Hormones', '0.8-1 g/kg'],
    ] },
    { type: 'note', text: `Keep the surplus moderate even at the advanced stage: muscle gain is slow now, so there's no need to pile on excess fat. +0.2 kg/week is a good benchmark.` },

    { type: 'h1', text: 'Recipes' },
    { type: 'h2', text: 'Intra/peri-workout shake' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protein', value: '40 g' }] },
    { type: 'list', items: [`1.5 scoop whey`, `1 banana`, `40 g oats`, `300 ml milk/water`] },
    { type: 'p', text: `Prep: blend. Sip around your big sessions to support energy and recovery.` },
    { type: 'h2', text: 'Hearty plate' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 750 kcal' }, { label: 'Protein', value: '55 g' }] },
    { type: 'list', items: [`180 g lean meat/fish`, `140 g rice (dry)`, `Vegetables`, `Olive oil`] },
    { type: 'p', text: `Prep: cook everything, assemble. The main meal on training days.` },
    { type: 'h2', text: 'Dense protein snack' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 400 kcal' }, { label: 'Protein', value: '35 g' }] },
    { type: 'list', items: [`250 g skyr`, `1 scoop whey`, `Fruit + 30 g oats`, `Peanut butter`] },
    { type: 'p', text: `Prep: mix together. Ideal between meals to hit your calorie target.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'At high intensity, recovery is priority number one.' },
    { type: 'h1', text: 'Recovery & fatigue management' },
    { type: 'list', items: [
      `Sleep 8 to 9 h: it's the #1 recovery factor at your training volume.`,
      `Deload every 4-5 weeks (volume −50%, intensity maintained).`,
      `Monitor fatigue markers: sleep, strength, motivation, resting heart rate.`,
      `Space big sessions (legs) at least 48 h apart.`,
      `Manage stress: it draws from the same recovery reserve as training.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: 'PPL ×2: frequency and volume working for your muscle.' },
    { type: 'h1', text: '12-week plan (periodized)' },
    { type: 'p', text: `Three blocks: accumulation (volume), intensification (loads), realization (strength/peak), then deload.` },
    { type: 'table', headers: ['Block', 'Weeks', 'Focus', 'RIR'], rows: [
      ['Accumulation', 'W1-W4', 'Max tolerable volume', '2-3 RIR'],
      ['Intensification', 'W5-W8', 'Heavier loads', '1-2 RIR'],
      ['Realization', 'W9-W11', 'Strength & intensity', '0-1 RIR'],
      ['Deload + tests', 'W12', 'Recover, then test', 'Light'],
    ] },
    { type: 'h2', text: 'Typical week (6 days, PPL ×2)' },
    { type: 'table', headers: ['Day', 'Session'], rows: [
      ['Monday', 'Push A (strength)'],
      ['Tuesday', 'Pull A (strength)'],
      ['Wednesday', 'Legs A (strength)'],
      ['Thursday', 'Push B (volume)'],
      ['Friday', 'Pull B (volume)'],
      ['Saturday', 'Legs B (volume)'],
      ['Sunday', 'Rest + tracking'],
    ] },

    { type: 'h1', text: 'Your sessions in detail' },
    { type: 'h2', text: 'Push A (strength)' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Barbell bench press', '5', '4 to 6', '180 s'],
      ['Overhead press', '4', '6 to 8', '150 s'],
      ['Incline dumbbell press', '3', '8 to 10', '120 s'],
      ['Lateral raises', '4', '12 to 15', '60 s'],
      ['Triceps extension (+ drop set)', '4', '10 to 12', '75 s'],
    ] },
    { type: 'h2', text: 'Pull A (strength)' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Deadlift', '4', '3 to 5', '210 s'],
      ['Weighted pull-ups', '4', '6 to 8', '150 s'],
      ['Barbell row', '4', '8 to 10', '120 s'],
      ['Face pull', '3', '15', '60 s'],
      ['Biceps curl (+ rest-pause)', '4', '10 to 12', '60 s'],
    ] },
    { type: 'h2', text: 'Legs A (strength)' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Squat', '5', '4 to 6', '210 s'],
      ['Leg press', '4', '10 to 12', '150 s'],
      ['Romanian deadlift', '3', '8 to 10', '120 s'],
      ['Leg curl + leg extension (superset)', '3', '12 to 15', '90 s'],
      ['Calf raises (+ partials)', '4', '12 to 20', '45 s'],
    ] },
    { type: 'p', text: `The B sessions (volume) repeat the same patterns but lighter: 10-15 reps, shorter rest, more intensity techniques (drop sets, myo-reps). Goal: volume and pump.` },
    { type: 'h2', text: 'Push B (volume)' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Incline dumbbell press', '4', '10 to 12', '90 s'],
      ['Dumbbell bench press', '3', '12', '90 s'],
      ['Machine shoulder press', '4', '12 to 15', '75 s'],
      ['Lateral raises (+ drop set)', '4', '15 to 20', '45 s'],
      ['Cable triceps pushdown (+ myo-reps)', '4', '12 to 15', '60 s'],
    ] },
    { type: 'h2', text: 'Pull B (volume)' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Lat pulldown', '4', '10 to 12', '90 s'],
      ['Machine / seated row', '4', '12', '90 s'],
      ['Cable pullover', '3', '12 to 15', '75 s'],
      ['Face pull (+ band pull-apart)', '4', '15 to 20', '45 s'],
      ['Incline curl (+ drop set)', '4', '12 to 15', '60 s'],
    ] },
    { type: 'h2', text: 'Legs B (volume)' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Squat / hack squat', '4', '10 to 12', '120 s'],
      ['Walking lunges / split squat', '3', '12 / leg', '90 s'],
      ['Leg extension (+ partials)', '4', '15', '60 s'],
      ['Leg curl (+ myo-reps)', '4', '15', '60 s'],
      ['Calf raises (+ drop set)', '5', '15 to 20', '45 s'],
    ] },

    { type: 'h1', text: 'Exercise library' },
    { type: 'p', text: `The key movements. Scan the QR code for the demo video.` },
    { type: 'exercise', name: 'Squat', muscles: 'Quads, glutes, hamstrings, core', level: 'Advanced', video: `${D}/musculation`, technique: `High-bar or low-bar depending on your style, descend below parallel, braced back, knees tracking in line, controlled explosive drive up. Safety bars mandatory when going heavy.`, mistakes: `Good-morning effect (hips shooting up first), knees caving in, losing core brace at the bottom.` },
    { type: 'exercise', name: 'Bench press', muscles: 'Chest, triceps, shoulders', level: 'Advanced', video: `${D}/musculation`, technique: `Feet planted, thoracic arch, shoulder blades pulled together and down. Touch the lower chest, elbows at ~45-70°, explosive drive. Spotter recommended when heavy.`, mistakes: `Bouncing off the chest, excessive elbow flare, glutes lifting off the bench, unstable bar path.` },
    { type: 'exercise', name: 'Deadlift', muscles: 'Entire posterior chain', level: 'Advanced', video: `${D}/musculation`, technique: `Bar over the middle of the foot, brace hard (controlled Valsalva), push the floor away, keep the bar close to the body, lock out without hyperextending.`, mistakes: `Rounded back, hips starting too low, bar drifting away from the body.` },
    { type: 'exercise', name: 'Overhead press', muscles: 'Shoulders, triceps, core', level: 'Intermediate', video: `${D}/musculation`, technique: `Standing, glutes and abs braced, press straight up, head moves slightly forward at the top, lock out.`, mistakes: `Lower-back arching, pressing forward instead of up, incomplete lockout.` },
    { type: 'exercise', name: 'Weighted pull-ups', muscles: 'Lats, biceps', level: 'Advanced', video: `${D}/musculation`, technique: `Weight belt on, start from a dead hang with shoulders down, pull the elbows down and back, chin above the bar, full controlled descent.`, mistakes: `Partial range, unintentional kipping, too much added weight breaking down technique.` },
    { type: 'exercise', name: 'Barbell row', muscles: 'Back, biceps, rear delts', level: 'Intermediate', video: `${D}/musculation`, technique: `Torso at 30-45°, flat back, pull toward the lower abdomen, squeeze the shoulder blades, control the eccentric.`, mistakes: `Torso standing up during the pull, rounded back, pulling too high.` },
    { type: 'exercise', name: 'Leg press', muscles: 'Quads, glutes', level: 'Beginner', video: `${D}/musculation`, technique: `Feet positioned for your target, lower without your lower back lifting off, full range, push without slamming the knees into lockout.`, mistakes: `Lower back lifting off the pad, short range, hard lockout.` },
    { type: 'exercise', name: 'Romanian deadlift', muscles: 'Hamstrings, glutes, back', level: 'Intermediate', video: `${D}/musculation`, technique: `Hips push back, flat back, stretch the hamstrings, return by squeezing the glutes. Slow eccentric for extra gains.`, mistakes: `Rounded back, bending the knees too much, bar drifting away from the legs.` },
    { type: 'exercise', name: 'Lateral raises', muscles: 'Side delts', level: 'Beginner', video: `${D}/musculation`, technique: `Keep it light, raise to shoulder height, elbows slightly bent, slow descent. Ideal for drop sets and myo-reps.`, mistakes: `Too heavy, using momentum, raising too high.` },
    { type: 'exercise', name: 'Face pull', muscles: 'Rear delts, rotator cuff', level: 'Beginner', video: `${D}/musculation`, technique: `High cable, pull the rope toward your face, elbows high, external rotation at the end of the movement. Great for shoulder health.`, mistakes: `Too heavy, elbows dropping, pulling with the arms instead of the back.` },
    { type: 'exercise', name: 'Biceps curl', muscles: 'Biceps', level: 'Beginner', video: `${D}/musculation`, technique: `Elbows fixed, strong contraction at the top, slow eccentric. Ideal for a rest-pause finisher.`, mistakes: `Using momentum, elbows drifting forward, partial range.` },
    { type: 'exercise', name: 'Cable triceps extension', muscles: 'Triceps', level: 'Beginner', video: `${D}/musculation`, technique: `Elbows pinned to your sides, extend fully, control the return. Keep constant tension.`, mistakes: `Elbows flaring out, torso helping the movement, short range.` },
    { type: 'exercise', name: 'Incline dumbbell press', muscles: 'Upper chest, shoulders', level: 'Intermediate', video: `${D}/musculation`, technique: `Bench at ~30°, lower until you feel the stretch, press while slightly bringing the dumbbells together. Excellent for an upper chest that's often lagging.`, mistakes: `Bench angle too steep, short range, elbows locking out.` },
    { type: 'exercise', name: 'Bulgarian split squat', muscles: 'Quads, glutes, balance', level: 'Intermediate', video: `${D}/musculation`, technique: `Rear foot elevated on a bench, lower the hips straight down, front knee tracking in line, then drive up through the front heel. Unilateral - ideal for fixing imbalances.`, mistakes: `Torso leaning too far forward, knee caving inward, pushing off the back leg.` },
    { type: 'exercise', name: 'Cable pullover', muscles: 'Lats, chest', level: 'Intermediate', video: `${D}/musculation`, technique: `Arms nearly straight, bring the bar/rope from the hips upward while keeping tension on the back, then return under control. Stretches and isolates the lats.`, mistakes: `Bending the elbows (turns it into a triceps move), short range, jerky reps.` },
    { type: 'exercise', name: 'Weighted hip thrust', muscles: 'Glutes, hamstrings', level: 'Intermediate', video: `${D}/musculation`, technique: `Upper back on a bench, barbell across the hips, drive through the heels until fully aligned, squeeze the glutes hard at the top, controlled descent.`, mistakes: `Lower-back hyperextension, incomplete range, feet poorly positioned.` },

    { type: 'h1', text: 'Weak-point specialization' },
    { type: 'p', text: `At your level, you can dedicate a whole block to a lagging muscle group. Increase its frequency and volume, and slightly trim everything else to keep fatigue in check.` },
    { type: 'list', items: [
      `Pick just 1 weak point per block (e.g. shoulders, back, calves).`,
      `Add 4 to 8 extra weekly sets on that group, as a 3rd weekly session for it.`,
      `Prioritize flawless execution and mind-muscle connection on isolation work.`,
      `Trim 2-4 sets from a "strong" muscle group to compensate.`,
    ] },

    { type: 'h1', text: 'Week-by-week breakdown (12 weeks)' },
    { type: 'table', headers: ['Week', 'Target RIR', 'Note'], rows: [
      ['W1-W2', '3 RIR', 'High volume, flawless technique'],
      ['W3-W4', '2-3 RIR', 'Add load, W4 check-in'],
      ['W5-W6', '2 RIR', 'Intensification, drop sets'],
      ['W7-W8', '1-2 RIR', 'Add load, RPE 8-9'],
      ['W9-W10', '1 RIR', 'Strength, long rest periods'],
      ['W11', '0-1 RIR', 'Intensity peak'],
      ['W12', 'Deload', 'Recover + strength tests, review'],
    ] },

    { type: 'h1', text: 'Breaking through a plateau' },
    { type: 'list', items: [
      `Check sleep, stress, and calories first: 80% of plateaus come from there.`,
      `Take a real deload: fatigue often masks the progress you've made.`,
      `Increase the stalled muscle group's volume by 20-30% for 3-4 weeks.`,
      `Change the angle or exercise variation for a fresh stimulus.`,
      `Work on execution quality before adding more load.`,
    ] },

    { type: 'h1', text: 'Mistakes to avoid' },
    { type: 'list', items: [
      `Stacking too many intensity techniques: you generate fatigue, not muscle.`,
      `Skipping deloads: overtraining sets you back.`,
      `Neglecting weak points or the rotator cuff/shoulders (injury risk).`,
      `Underestimating nutrition and sleep at high training volume.`,
      `Switching programs before giving the protocol a full 12 weeks.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: [`You're dealing with…`, 'The solution'], rows: [
      ['Stagnation despite the effort', 'Deload, then targeted +volume for 3-4 wks.'],
      ['Joint pain', 'Reduce loads, add face pulls/mobility'],
      ['Chronic fatigue', 'Volume −30%, +1 rest day, sleep more'],
      ['Strength dropping', 'Sign of overreaching: deload immediately'],
    ] },

    { type: 'h1', text: 'Staying motivated' },
    { type: 'list', items: [
      `Set numeric strength targets and visual goals (weak point).`,
      `Film your heavy sets: analyzing your technique is both motivating and useful.`,
      `Photos & measurements every 4 weeks.`,
      `Remember: at your level, progress is slow but real. Patience is a skill.`,
    ] },

    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: 'How much volume is optimal?' },
    { type: 'p', text: `16 to 22 sets per muscle group per week for most advanced lifters. Start at the low end of the range and increase it if you're recovering well. More isn't always better - what counts is the volume you can actually recover from.` },
    { type: 'h2', text: 'RIR or RPE?' },
    { type: 'p', text: `Two sides of the same coin. RIR = reps in reserve; RPE = 10 − RIR. RIR 2 = RPE 8. Use whichever one clicks better for you to autoregulate.` },
    { type: 'h2', text: 'Should I train to failure?' },
    { type: 'p', text: `Rarely on heavy compound lifts (risk/fatigue). More often on isolation work at the end of a session. The realization block (W9-W11) gets closer to failure; the rest of the program keeps some RIR in the tank.` },
    { type: 'h2', text: 'What supplements at this level?' },
    { type: 'p', text: `Creatine (3-5 g/day), whey, pre-workout caffeine. Optionally citrulline (pump) and electrolytes for big sessions. Everything else has a marginal effect.` },
    { type: 'h2', text: 'How do I handle a lack of time?' },
    { type: 'p', text: `Switch to a 3-day PPL or a 4-day upper/lower split while keeping the intensity high. 4 productive sessions beat 6 rushed ones with poor recovery.` },

    { type: 'h1', text: 'Cardio & conditioning' },
    { type: 'p', text: `Well-dosed cardio supports your recovery (better circulation, work capacity) and limits fat gain during surplus blocks - without cannibalizing your gains if you stick to these benchmarks.` },
    { type: 'list', items: [
      `Daily walking (8,000-12,000 steps): the foundation, zero impact on recovery.`,
      `2 to 3 moderate cardio sessions (zone 2, 25-35 min) per week, spaced away from leg day.`,
      `Avoid intense cardio the day before or on the day of heavy leg/back sessions.`,
      `During a cutting block: gradually increase cardio rather than cutting calories further.`,
    ] },
    { type: 'table', headers: ['Type', 'Duration', 'Frequency', 'Purpose'], rows: [
      ['Walking (NEAT)', 'Daily', 'Every day', 'Expenditure, recovery'],
      ['Zone 2 cardio', '25-35 min', '2-3×/wk', 'Capacity, health'],
      ['Light intervals', '10-15 min', '1×/wk', 'Conditioning'],
    ] },

    { type: 'h1', text: 'Mobility & joint health' },
    { type: 'p', text: `The heavier you load, the more mobility and joint health matter. Build them into your routine.` },
    { type: 'table', headers: ['Movement', 'Target', 'Dose'], rows: [
      ['Face pull / band pull-apart', 'Shoulders (prevention)', '2-3×/wk, 2-3 sets'],
      ['Hip/ankle mobility', 'Squat & deadlift', 'Before leg day'],
      ['Chest stretch', 'Shoulders', '30 s / side'],
      ['Dead hang', 'Spinal decompression', '30-45 s'],
    ] },

    { type: 'h1', text: 'Safety' },
    { type: 'list', items: [
      `Use safety bars and/or a spotter on squats and bench press.`,
      `Warm up with ascending sets before every compound lift.`,
      `Learn the Valsalva maneuver to brace on heavy sets (without overdoing it).`,
      `Never sacrifice technique for load: that's the very definition of ego lifting.`,
    ] },

    { type: 'h1', text: 'And after your 12 weeks?' },
    { type: 'p', text: `At your level, the key to long-term progress is smart variation and managing fatigue across the year.` },
    { type: 'list', items: [
      `Take a real deload (1 week) before starting a new block.`,
      `Change up exercise variations and order for a fresh stimulus.`,
      `Alternate hypertrophy-focused and strength-focused blocks throughout the year.`,
      `Dedicate your next block to a weak point you identified during these 12 weeks.`,
      `Depending on your goal: follow up with a cut (Weight Loss program) or a true bulking phase.`,
    ] },
    { type: 'note', text: `Think in years, not in 12-week blocks. The best physiques are built by stacking well-run blocks and honoring recovery, year after year.` },

    { type: 'h1', text: 'Keeping a proper training log' },
    { type: 'p', text: `At the advanced stage, your log is your #1 progress tool: it turns training into data you can actually act on. Without it, you're flying blind.` },
    { type: 'list', items: [
      `Log for every exercise: load × reps × sets, plus the RIR of the last set.`,
      `Note how you feel that day (energy /10, sleep): it explains your good and bad sessions.`,
      `Before every working set, check your previous performance: your goal is to beat it.`,
      `Review your log every week: spot the exercises that are stalling so you can act on them.`,
      `Keep a record of your deloads and PRs: motivating and instructive over the long run.`,
    ] },
    { type: 'note', text: `"What gets measured gets improved." Two lifters with the same potential won't have the same physique a year from now: the one who logs and adjusts will pull ahead.` },

    { type: 'h1', text: 'Tracking your progress' },
    { type: 'p', text: `Log everything: loads, sets, RIR, how you feel. At your level, your training log is your best coach.` },
    { type: 'h2', text: 'Weight & measurements' },
    { type: 'tracker', columns: ['Date', 'Weight', 'Arms', 'Thigh', 'Chest', 'Waist'], rows: 7 },
    { type: 'h2', text: 'Max strength (kg) on the compounds' },
    { type: 'tracker', columns: ['Exercise', 'W1', 'W4', 'W8', 'W12'], rows: 5 },

    { type: 'h1', text: 'Weekly checklist' },
    { type: 'checklist', items: [
      `I completed all my sessions and hit my target volume.`,
      `I stuck to my target RIR for this block.`,
      `I made progress on at least one key lift.`,
      `I hit my protein and carb targets.`,
      `I slept 8 to 9 h most nights.`,
      `I managed my fatigue (no abnormal strength drop).`,
      `I worked on my weak point / my mobility.`,
      `I logged everything in my training log.`,
    ] },

    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My notes, loads, RIR and sensations for the week'], rows: 16 },

    { type: 'h1', text: 'Glossary' },
    { type: 'list', items: [
      `RIR: reps in reserve (RIR 2 = 2 reps left in the tank).`,
      `Periodization: organizing training into blocks (volume, intensity, peak).`,
      `Accumulation / intensification / realization: the 3 phases of a periodized block.`,
      `Drop set, rest-pause, myo-reps: intensity techniques.`,
      `Valsalva: a breath-bracing technique for heavy loads.`,
      `Autoregulation: adjusting load/volume to how you feel that day via RPE/RIR.`,
      `Deload: a reduced-load week to dissipate fatigue.`,
    ] },

    { type: 'note', text: `Wrapped up your 12 weeks? Take a full deload, test your maxes, take your measurements, then start a new block with varied exercises, or move into a cutting/bulking phase depending on your goal. Create your account at xenotif.com.` },
  ],
}
