import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// EN mirror of musculation-debutant.ts - Beginner Strength Training Program. Premium XENOTIF® template (≈30 pages).
export const musculationDebutantEn: Guide = {
  id: 'musculation-debutant',
  title: 'Beginner Strength Training Program',
  subtitle: '8 weeks to build solid foundations in strength and muscle',
  author: 'XENOTIF Coach - Certified strength & conditioning coach',
  level: 'Beginner',
  duration: '8 weeks · 3 sessions/week',
  coverImage: 'musculation-debutant-cover.jpg',
  blocks: [
    { type: 'h1', text: "Welcome - you're starting strength training" },
    { type: 'p', text: `This program is designed for true beginners: no experience required. In 8 weeks, you'll learn the fundamental movements, build strength, gain muscle, and create a routine that lasts. We prioritize technique and consistency over load - that's how you progress fast without getting hurt.` },
    { type: 'p', text: `Keep this guide on your phone: every exercise has a QR code that opens its demo video on XENOTIF®. If you're ever unsure about a movement, scan it.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Strength, muscle & foundational technique' },
      { label: 'Level', value: 'Beginner (zero experience OK)' },
      { label: 'Duration', value: '8 weeks' },
      { label: 'Frequency', value: '3 sessions per week' },
      { label: 'Equipment', value: 'Gym, or dumbbells + barbell' },
      { label: 'Format', value: 'Full body, 3 days' },
    ] },
    { type: 'h2', text: 'Program goals' },
    { type: 'list', items: [
      `Master the 6 fundamental movement patterns (squat, hinge, push, pull, lunge, core bracing).`,
      `Build strength fast (beginner gains are the most dramatic you'll ever see).`,
      `Build muscle and tone your whole body.`,
      `Establish a training routine you'll keep for the long run.`,
    ] },
    { type: 'h2', text: 'How to use this guide' },
    { type: 'list', items: [
      `Read the whole guide, then follow the 8-week calendar.`,
      `Start light: master the movement before adding weight.`,
      `Warm up for 5-8 min before every session (dedicated page).`,
      `Scan an exercise's QR code to see the technique on video.`,
      `Log your loads every session and review your progress on Sunday.`,
    ] },
    { type: 'note', text: `Golden rule for beginners: technique before load. One clean rep is worth ten sloppy ones. Muscle comes from quality movement, not ego.` },

    { type: 'h1', text: 'How it works' },
    { type: 'list', items: [
      `Full body: you train your whole body every session, 3 times a week.`,
      `At least 1 rest day between sessions (e.g. Monday / Wednesday / Friday).`,
      `Sets × reps: "3 × 10" = 3 sets of 10 reps.`,
      `Controlled tempo: 2 s on the way down, 1 s on the way up. Never jerky reps.`,
      `Rest: 90 s on the big lifts, 60 s on the rest.`,
      `RPE 7 to 8: keep 2-3 reps in reserve. As a beginner, you don't train to failure.`,
    ] },
    { type: 'h2', text: 'The 6 fundamental movements' },
    { type: 'p', text: `Everything is built on 6 movement patterns. Master them and you can train your whole body anywhere.` },
    { type: 'table', headers: ['Pattern', 'Example', 'Main muscles'], rows: [
      ['Squat (knee-dominant)', 'Squat, leg press', 'Quads, glutes'],
      ['Hinge', 'Romanian deadlift', 'Hamstrings, glutes, back'],
      ['Push', 'Bench press, push-ups', 'Chest, shoulders, triceps'],
      ['Pull', 'Row, lat pulldown', 'Back, biceps'],
      ['Lunge', 'Lunge, split squat', 'Legs, balance'],
      ['Core bracing', 'Plank, side plank', 'Abs, lower back'],
    ] },

    { type: 'h1', text: 'Warm-up' },
    { type: 'p', text: `Never skip the warm-up: it primes your body and boosts performance. Do it before every session.` },
    { type: 'table', headers: ['Step', 'Detail', 'Duration'], rows: [
      ['Light cardio', 'Bike / jump rope / brisk walk', '3 min'],
      ['Mobility', 'Shoulders, hips, ankles', '2 min'],
      ['Activation', 'Core bracing + bodyweight squats', '2 min'],
      ['Warm-up sets', '1-2 light sets of the 1st exercise', '1 min'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Eating well speeds up your beginner gains.' },
    { type: 'h1', text: 'Nutrition' },
    { type: 'p', text: `Good news: as a beginner, you can build muscle AND lose a bit of fat at the same time ("recomposition"). Eat at maintenance or in a slight surplus, with enough protein.` },
    { type: 'meta', items: [
      { label: 'Calories', value: 'Maintenance to slight surplus' },
      { label: 'Protein', value: '1.6 to 2 g per kg of bodyweight' },
      { label: 'Hydration', value: '2 to 3 L per day' },
      { label: 'Sleep', value: '7 to 9 h' },
    ] },
    { type: 'h2', text: 'The simple rules' },
    { type: 'list', items: [
      `A protein source at every meal (eggs, chicken, fish, skyr, legumes).`,
      `Carbs around training (rice, pasta, oats, fruit) for energy.`,
      `Vegetables at every main meal.`,
      `Drink water regularly, especially during your session.`,
    ] },
    { type: 'h2', text: 'Understanding your macros' },
    { type: 'table', headers: ['Macro', 'Role', 'Per g', 'Priority'], rows: [
      ['Protein', 'Builds muscle', '4 kcal', 'HIGH - 1.6-2 g/kg'],
      ['Carbs', 'Training energy', '4 kcal', 'Around sessions'],
      ['Fat', 'Hormones, health', '9 kcal', 'Moderate, quality sources'],
    ] },
    { type: 'note', text: `No need to weigh everything. Just build each plate this way: 1 protein source + 1 carb source + vegetables + a bit of healthy fat.` },

    { type: 'h1', text: 'Simple recipes' },
    { type: 'h2', text: 'Post-workout protein bowl' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 500 kcal' }, { label: 'Protein', value: '40 g' }] },
    { type: 'list', items: [`130 g chicken`, `100 g rice (dry)`, `Vegetables`, `Soy sauce, spices`] },
    { type: 'p', text: `Preparation: cook the rice, sear the chicken and vegetables, assemble. Perfect after training.` },
    { type: 'h2', text: 'Protein breakfast' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 420 kcal' }, { label: 'Protein', value: '35 g' }] },
    { type: 'list', items: [`200 g skyr`, `50 g rolled oats`, `1 banana`, `1 tsp honey`] },
    { type: 'p', text: `Preparation: mix the skyr and oats, add the banana and honey. Quick and filling.` },
    { type: 'h2', text: 'Loaded omelette' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 400 kcal' }, { label: 'Protein', value: '30 g' }] },
    { type: 'list', items: [`3 eggs`, `50 g cheese`, `Spinach, tomato`, `1 slice whole-grain bread`] },
    { type: 'p', text: `Preparation: beat the eggs, add the vegetables and cheese, cook over low heat. Serve with the bread. Great for breakfast or a quick dinner.` },
    { type: 'h2', text: 'Tuna-tomato pasta' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 520 kcal' }, { label: 'Protein', value: '35 g' }] },
    { type: 'list', items: [`100 g whole-grain pasta (dry)`, `1 can of tuna`, `Tomato sauce, garlic`, `A drizzle of olive oil`] },
    { type: 'p', text: `Preparation: cook the pasta, mix in the tuna and garlic tomato sauce. Quick, cheap, and high in protein.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Muscle is built during rest.' },
    { type: 'h1', text: 'Recovery' },
    { type: 'list', items: [
      `Sleep 7 to 9 h: most muscle recovery happens at night.`,
      `Leave at least 1 rest day between full-body sessions.`,
      `Soreness in the first few weeks is normal - it will fade.`,
      `Stretch for 5-10 min after every session.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: '3 sessions a week, full body.' },
    { type: 'h1', text: 'The 8-week calendar' },
    { type: 'p', text: `Alternate 3 full-body sessions (A, B, C) throughout the week. Increase load or reps as soon as it feels easy.` },
    { type: 'table', headers: ['Weeks', 'Focus', 'Reps', 'Note'], rows: [
      ['W1-W2', 'Learning technique', '3 × 10-12', 'Light loads, clean movement'],
      ['W3-W4', 'Building the base', '3 × 10', '+ progressive load'],
      ['W5-W6', 'Strengthening', '4 × 8-10', "You've got the technique, now load up"],
      ['W7-W8', 'Consolidation', '4 × 8', 'Beat your W1 numbers, review'],
    ] },
    { type: 'h2', text: 'Typical week' },
    { type: 'table', headers: ['Day', 'Session', 'Duration'], rows: [
      ['Monday', 'Full body A', '45 min'],
      ['Tuesday', 'Rest / walk', '-'],
      ['Wednesday', 'Full body B', '45 min'],
      ['Thursday', 'Rest / walk', '-'],
      ['Friday', 'Full body C', '45 min'],
      ['Weekend', 'Rest + tracking', '-'],
    ] },

    { type: 'h1', text: 'Your sessions in detail' },
    { type: 'h2', text: 'Full body A' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Squat (or leg press)', '3', '10', '90 s'],
      ['Bench press (or push-ups)', '3', '10', '90 s'],
      ['Row / pulldown', '3', '12', '75 s'],
      ['Plank', '3', '30 s', '45 s'],
    ] },
    { type: 'h2', text: 'Full body B' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Romanian deadlift', '3', '10', '90 s'],
      ['Overhead press', '3', '10', '90 s'],
      ['Lat pulldown', '3', '12', '75 s'],
      ['Lunges', '3', '10 / leg', '60 s'],
    ] },
    { type: 'h2', text: 'Full body C' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Lunges (or split squat)', '3', '10 / leg', '75 s'],
      ['Push-ups (or bench press)', '3', 'Max clean reps', '75 s'],
      ['Dumbbell row', '3', '12', '75 s'],
      ['Curl + triceps extension', '3', '12', '60 s'],
      ['Side plank', '3', '20 s / side', '45 s'],
    ] },

    { type: 'h1', text: 'Exercise library' },
    { type: 'p', text: `Master these basic movements. Scan the QR code for the demo video.` },
    { type: 'exercise', name: 'Squat', muscles: 'Quads, glutes, hamstrings', level: 'Beginner', video: `${D}/musculation`, technique: `Feet shoulder-width apart, push your hips back as you lower, back braced, until your thighs are parallel to the ground, then drive up through your heels. Start with bodyweight before adding a barbell.`, mistakes: `Knees caving in, heels lifting, rounded back. Keep your eyes forward and chest open.` },
    { type: 'exercise', name: 'Romanian Deadlift', muscles: 'Hamstrings, glutes, back', level: 'Beginner', video: `${D}/musculation`, technique: `Bar in front of your thighs, flat back. Push your hips back as you lower the weight along your legs, knees slightly bent, then return by squeezing your glutes.`, mistakes: `Rounded back, the weight drifting away from your body, bending the knees like a squat.` },
    { type: 'exercise', name: 'Push-ups', muscles: 'Chest, triceps, shoulders', level: 'Beginner', video: `${D}/musculation`, technique: `Body braced in a straight line, hands slightly wider than your shoulders. Lower your chest toward the floor, elbows at ~45°, then push back up. On your knees or against an incline if needed.`, mistakes: `Hips sagging, elbows too flared, range too short.` },
    { type: 'exercise', name: 'Bench Press', muscles: 'Chest, triceps, shoulders', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Shoulder blades pinned together, lower the bar to the bottom of your chest, elbows at ~45°, then press up. Feet planted on the floor. Start light, ask for a spotter if going heavy.`, mistakes: `Elbows too flared, bouncing the bar off your chest, hips lifting off the bench.` },
    { type: 'exercise', name: 'Dumbbell Row', muscles: 'Back, biceps', level: 'Beginner', video: `${D}/musculation`, technique: `One knee and one hand on a bench, flat back. Pull the dumbbell toward your hip while squeezing your shoulder blade, then lower slowly. The movement comes from your back.`, mistakes: `Rounded back, twisting the torso, pulling with the arm alone.` },
    { type: 'exercise', name: 'Overhead Press', muscles: 'Shoulders, triceps', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Standing, core braced, press the weight overhead without arching your lower back, then lower under control back to your shoulders.`, mistakes: `Arching the lower back, pressing forward instead of up, incomplete range of motion.` },
    { type: 'exercise', name: 'Lat Pulldown', muscles: 'Back, biceps', level: 'Beginner', video: `${D}/musculation`, technique: `Seated, wide grip. Pull the bar toward the top of your chest by depressing your shoulders and squeezing your back, then return under control.`, mistakes: `Swinging the body, pulling behind the neck, releasing tension at the top.` },
    { type: 'exercise', name: 'Lunges', muscles: 'Quads, glutes, balance', level: 'Beginner', video: `${D}/musculation`, technique: `Take a big step forward, back knee toward the floor, torso upright. The front knee stays above the ankle. Push through the front heel to return.`, mistakes: `Step too short, leaning torso, losing your balance.` },
    { type: 'exercise', name: 'Biceps Curl', muscles: 'Biceps', level: 'Beginner', video: `${D}/musculation`, technique: `Elbows pinned to your sides, curl the dumbbells up while contracting the biceps, lower slowly. No swinging from the torso.`, mistakes: `Swinging the body, elbows drifting forward, lowering too fast.` },
    { type: 'exercise', name: 'Plank', muscles: 'Core', level: 'Beginner', video: `${D}/musculation`, technique: `Support on your forearms and toes, body aligned, abs and glutes braced. Breathe calmly and hold the position.`, mistakes: `Hips sagging, glutes too high, head lifted up.` },
    { type: 'exercise', name: 'Bench Dips', muscles: 'Triceps, shoulders, chest', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Hands on the edge of a bench, legs out in front. Lower your hips by bending your elbows back, then push back up. The straighter your legs, the harder it gets.`, mistakes: `Shoulders creeping up toward the ears, shallow descent, unstable bench.` },
    { type: 'exercise', name: 'Side Plank', muscles: 'Obliques, core', level: 'Beginner', video: `${D}/musculation`, technique: `On your side, supported on one forearm, body aligned. Lift your hips and hold without letting them drop. Switch sides.`, mistakes: `Hips dropping, shoulder misaligned with the elbow, body tipping forward.` },
    { type: 'exercise', name: 'Hip Thrust', muscles: 'Glutes, hamstrings', level: 'Beginner', video: `${D}/musculation`, technique: `Upper back against a bench, weight resting on your hips. Push through your heels to raise your hips until your shoulders, hips, and knees align, squeeze your glutes for 1 s at the top, then lower.`, mistakes: `Arching the lower back, raising the hips too high, feet poorly positioned.` },
    { type: 'exercise', name: 'Lateral Raises', muscles: 'Shoulders (delts)', level: 'Beginner', video: `${D}/musculation`, technique: `Standing, light dumbbells at your sides. Raise your arms out to the sides up to shoulder height, elbows slightly bent, then lower slowly. Light weight works best here.`, mistakes: `Going too heavy, raising above shoulder height, swinging the body.` },
    { type: 'exercise', name: 'Standing Calf Raise', muscles: 'Calves', level: 'Beginner', video: `${D}/musculation`, technique: `Standing, rise up onto your toes as high as possible, pause briefly, then lower slowly with a full stretch. Use a step for a greater range of motion.`, mistakes: `Range too short, bouncing, lowering too fast.` },

    { type: 'h1', text: 'Executing the perfect set' },
    { type: 'p', text: `Execution quality is what separates a beginner who progresses from one who gets hurt. Here are the 5 principles to apply on every set.` },
    { type: 'list', items: [
      `Full range of motion: lower and rise through the entire movement.`,
      `Controlled tempo: 2 s down, 1 s up. Never jerky or using momentum.`,
      `Breathing: exhale on the effort (the lift), inhale on the release (the lowering).`,
      `Bracing: keep your abs tight to protect your lower back on every rep.`,
      `Mind-muscle connection: focus on the muscle working, not on the weight.`,
    ] },
    { type: 'note', text: `If you can't complete all your reps with clean form, the load is too heavy. Drop it: muscle responds to quality, not ego.` },

    { type: 'h1', text: 'Cardio for beginners' },
    { type: 'p', text: `Cardio isn't mandatory for progressing in strength training, but it improves your health, your recovery, and helps you stay lean. Keep it light so it doesn't interfere with your strength sessions.` },
    { type: 'list', items: [
      `2 to 3 brisk 30-min walks a week, on your rest days.`,
      `Optional: 10-15 min of bike or rower at the end of a session.`,
      `Aim for 8,000 steps a day: stairs, walking commutes, etc.`,
      `Avoid long, intense cardio sessions that tire your legs out before lifting.`,
    ] },

    { type: 'h1', text: 'No-equipment home variant' },
    { type: 'p', text: `No gym or dumbbells? This bodyweight full-body circuit replaces a session. Do 3 to 4 rounds, 45 s of work / 15 s transition, 1 min rest between rounds.` },
    { type: 'table', headers: ['Exercise', 'Target', 'Reps / time'], rows: [
      ['Bodyweight squats', 'Legs', '15 to 20'],
      ['Push-ups (knees if needed)', 'Upper body', 'Max clean reps'],
      ['Alternating lunges', 'Legs', '10 / leg'],
      ['Row with a weighted bag', 'Back', '12'],
      ['Chair dips', 'Triceps', '10'],
      ['Plank', 'Abs', '30 to 45 s'],
    ] },

    { type: 'h1', text: 'Strengthening your abs' },
    { type: 'p', text: `Add 5 minutes of ab work at the end of a session, 2 to 3 times a week. A strong core protects your back and improves every other exercise you do.` },
    { type: 'exercise', name: 'Crunch', muscles: 'Rectus abdominis (abs)', level: 'Beginner', video: `${D}/musculation`, technique: `Lying down, knees bent, hands on your chest or temples. Lift your shoulders off the floor by curling your torso, exhale, then lower slowly. Keep your lower back on the floor.`, mistakes: `Pulling on your neck, lifting your whole back off the floor, holding your breath.` },
    { type: 'exercise', name: 'Leg Raise', muscles: 'Lower abs, core', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Lying down, hands under your glutes. Raise your straight legs (or bent knees) up to vertical, then lower slowly without touching the floor. Keep your lower back pressed down.`, mistakes: `Arching the lower back, lowering too fast, swinging the legs.` },
    { type: 'list', items: [
      `Express ab circuit: 15 crunches + 12 leg raises + 40 s plank, 3 rounds.`,
      `Quality over quantity: slow, controlled movements.`,
      `Visible abs mainly come from controlled nutrition, not exercise alone.`,
    ] },

    { type: 'h1', text: 'Week-by-week breakdown' },
    { type: 'p', text: `Here's how it evolves week by week. Keep the 3 full-body sessions, and progress your loads and reps.` },
    { type: 'table', headers: ['Week', 'Sets × Reps', 'Weekly goal'], rows: [
      ['Week 1', '3 × 12', 'Learn the movements, very light loads'],
      ['Week 2', '3 × 12', 'Confirm your technique, slight increase'],
      ['Week 3', '3 × 10', 'Add weight, 90 s rest'],
      ['Week 4', '3 × 10', 'Midpoint check-in, photo & measurements'],
      ['Week 5', '4 × 10', 'Add a set, more volume'],
      ['Week 6', '4 × 8', 'Heavier loads'],
      ['Week 7', '4 × 8', 'Peak intensity, clean form'],
      ['Week 8', '4 × 8 + review', 'Beat your Week 1 numbers, final measurements'],
    ] },

    { type: 'h1', text: 'Recommended progression' },
    { type: 'p', text: `Beginners progress fast: take advantage of it with simple progressive overload.` },
    { type: 'list', items: [
      `When you hit the top of the rep range on every set, add weight (the smallest increment available).`,
      `Otherwise, add 1 rep per set each week.`,
      `Log every session: load × reps. Beat that number next time.`,
      `Don't panic if a week stalls: sleep and nutrition matter as much as the session itself.`,
    ] },

    { type: 'h1', text: 'Beginner mistakes to avoid' },
    { type: 'list', items: [
      `Adding weight too fast: technique breaks down and injury risk skyrockets.`,
      `Constantly switching programs: give this program 8 weeks to work.`,
      `Neglecting legs and back in favor of arms/chest.`,
      `Skipping the warm-up or your rest days.`,
      `Comparing yourself to others: compare yourself to last week's you.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: ["You're facing…", 'The solution'], rows: [
      ["You don't know what weight to use", 'Pick a weight where the last rep is hard but clean'],
      ['Your joints hurt', 'Lighten the load, review your technique (scan the video)'],
      ["You're not progressing anymore", 'Check your sleep, protein intake, and add rest'],
      ['Intense soreness', "Normal early on; hydrate, stretch, it'll pass"],
    ] },

    { type: 'h1', text: 'Staying motivated' },
    { type: 'list', items: [
      `Set a simple strength goal (e.g. "10 clean push-ups," "master the bodyweight squat, then add load").`,
      `Take a photo and your measurements every 4 weeks.`,
      `Block your 3 time slots in your calendar like appointments.`,
      `Celebrate every small win: a consistent beginner beats an inconsistent advanced lifter.`,
    ] },
    { type: 'h2', text: 'Build the habit' },
    { type: 'list', items: [
      `Pack your bag the night before: zero friction on the day.`,
      `The 2-minute rule: just start the warm-up, the rest follows.`,
      `Never skip 2 sessions in a row.`,
    ] },

    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: 'Will I get "too bulky"?' },
    { type: 'p', text: `No. Building muscle is slow and takes years of effort. Strength training will make you more toned, stronger, and healthier - not accidentally "huge."` },
    { type: 'h2', text: 'Cardio or strength training to lose fat?' },
    { type: 'p', text: `Both, but strength training is essential: it preserves/builds muscle, which raises your resting energy expenditure. Combine strength training + some walking/cardio + controlled nutrition.` },
    { type: 'h2', text: 'Can I do this at home?' },
    { type: 'p', text: `Yes, with a pair of dumbbells. Otherwise, use the bodyweight variations (push-ups, lunges, squats, planks, rows with a weighted bag).` },
    { type: 'h2', text: 'How long before I see results?' },
    { type: 'p', text: `Strength: as early as 2-3 weeks. Visible changes: 6 to 8 weeks with solid nutrition. Your first few months as a beginner are the most rewarding.` },
    { type: 'h2', text: 'Do I need supplements?' },
    { type: 'p', text: `No, not to get started. If you want them: whey (to hit your protein target) and creatine (3-5 g/day). Everything else is secondary.` },
    { type: 'h2', text: 'How many rest days?' },
    { type: 'p', text: `At least 1 day between each full-body session, which fits the 3-sessions-a-week format (e.g. Monday/Wednesday/Friday). Rest isn't wasted time - it's when your muscle actually rebuilds.` },
    { type: 'h2', text: 'What if an exercise hurts?' },
    { type: 'p', text: `Tell the difference between normal muscular sensation and abnormal joint or sharp pain. If it hurts, stop the exercise, lighten the load, review your technique (scan the video), or swap it for a variation. See a professional if it persists.` },

    { type: 'h1', text: 'What comes after your 8 weeks?' },
    { type: 'p', text: `You've learned the fundamentals and built strength: now it's about continuing to progress. Here are your options.` },
    { type: 'list', items: [
      `Move on to the Intermediate Strength Training program for more volume and a more advanced split.`,
      `If your goal is muscle: follow up with Muscle Gain (slight surplus).`,
      `If your goal is leaning out: follow up with Weight Loss (slight deficit) - the strength you've built will help you keep your muscle.`,
      `Either way: don't stop. Consistency over months makes all the difference.`,
    ] },
    { type: 'note', text: `Retake your measurements and a photo after these 8 weeks, and compare them to where you started. That's your real reward - and your best motivation to keep going.` },

    { type: 'h1', text: 'Stretching & mobility' },
    { type: 'p', text: `5-10 min after every session. Hold each position 20-30 s, no bouncing.` },
    { type: 'table', headers: ['Stretch', 'Area', 'Duration'], rows: [
      ['Standing quad', 'Front of thigh', '30 s / side'],
      ['Straight-leg hamstring', 'Back of thigh', '30 s / side'],
      ['Chest at the wall', 'Chest, shoulders', '30 s / side'],
      ['Bar hang', 'Back, shoulders', '30 s'],
      ['Cat-cow', 'Spine', '45 s'],
    ] },

    { type: 'h1', text: 'Safety & injury prevention' },
    { type: 'p', text: `Strength training is very safe when done properly. Almost all beginner injuries come from three avoidable causes: ego, technique, and skipping the warm-up.` },
    { type: 'list', items: [
      `Always warm up, especially before heavy movements.`,
      `Increase your loads progressively (small increments), never all at once.`,
      `Keep your back braced and neutral on squats, deadlifts, and overhead presses.`,
      `Stop a set if your technique breaks down: 8 clean reps beat 12 sloppy ones.`,
      `Sharp joint pain = stop. Never "push through" real pain.`,
      `Stay hydrated and get enough sleep: a tired body gets injured more easily.`,
    ] },
    { type: 'note', text: `If you're ever unsure about a movement, scan its QR code to review the technique on video before adding load.` },

    { type: 'h1', text: 'Tracking your progress' },
    { type: 'p', text: `Log your loads every session and your measurements every week. What gets measured gets managed.` },
    { type: 'h2', text: 'Weight & measurements' },
    { type: 'tracker', columns: ['Date', 'Weight (kg)', 'Arm (cm)', 'Thigh (cm)', 'Waist (cm)'], rows: 7 },
    { type: 'h2', text: 'Loads (kg) on the basics' },
    { type: 'tracker', columns: ['Exercise', 'W1', 'W3', 'W5', 'W8'], rows: 6 },

    { type: 'h1', text: 'Weekly checklist' },
    { type: 'p', text: `Tick each box at the end of the week. Goal: at least 5 out of 7.` },
    { type: 'checklist', items: [
      `I did my 3 sessions this week.`,
      `I kept clean technique on every exercise.`,
      `I hit my protein target.`,
      `I increased a load or a rep.`,
      `I slept 7 to 9 h most nights.`,
      `I warmed up before every session.`,
      `I logged my loads and how I felt.`,
    ] },

    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My notes, loads, and sensations for the week'], rows: 16 },

    { type: 'h1', text: 'Glossary' },
    { type: 'list', items: [
      `Full body: a session that trains your entire body.`,
      `RPE: rate of perceived exertion out of 10 (RPE 8 = 2 reps in reserve).`,
      `Progressive overload: increasing load/reps over the weeks.`,
      `Tempo: the speed of execution (e.g. 2 s down, 1 s up).`,
      `Hinge: a hip-tilting movement pattern (deadlift).`,
      `Recomposition: gaining muscle and losing fat at the same time (possible for beginners).`,
    ] },

    { type: 'note', text: `Finished your 8 weeks? You've built a solid foundation. Move on to the Intermediate Strength Training or Muscle Gain program to keep progressing. Create your account at xenotif.com.` },
  ],
}
