import type { Guide } from '@/lib/boutique/guides'

// d2 - Cutting Nutrition Plan 8 weeks (EN mirror of nutrition-seche.ts).
// NUTRITION program: 56 days of menus, 40+ recipes, shopping lists, custom macros, vegan version.
export const nutritionSecheEn: Guide = {
  id: 'd2',
  title: 'Cutting Nutrition Plan - 8 Weeks',
  subtitle: '56 days of menus, 40+ recipes, shopping lists, custom macros, vegan version',
  author: 'XENOTIF Coach - Certified sports nutrition',
  level: 'All levels',
  duration: '8 weeks · 56 days of menus',
  coverImage: 'seche-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Welcome to your cut' },
    { type: 'p', text: `This 8-week plan will help you reveal your muscle definition by losing fat - without sacrificing the muscle you worked hard for, with no extreme diet or absurd deprivation. A progressive, sustainable, science-based method. Inside you'll find how to calculate your needs, 56 days of detailed menus, 40+ recipes, your shopping lists and a complete vegan version.` },
    { type: 'p', text: `This document is your pocket meal plan: follow the menus day by day, prep your groceries with the lists provided, and let the definition appear week after week.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Lose fat, keep muscle' },
      { label: 'Level', value: 'All levels' },
      { label: 'Duration', value: '8 weeks (56 days)' },
      { label: 'Deficit', value: '300 to 500 kcal / day' },
      { label: 'Protein', value: '2 to 2.4 g per kg' },
      { label: 'Included', value: 'Menus + recipes + shopping' },
    ] },
    { type: 'h2', text: `What you'll get` },
    { type: 'list', items: [
      `Steady fat loss (0.5 to 0.8% of your bodyweight per week).`,
      `Maintenance of your muscle mass thanks to high protein.`,
      `56 days of ready-to-follow menus, balanced and tasty.`,
      `Eating habits you'll keep after the cut.`,
    ] },
    { type: 'h2', text: 'How to use this plan' },
    { type: 'list', items: [
      `Calculate your needs (chapter "Your custom macros").`,
      `Follow the menus week by week, or pick from the 40+ recipes.`,
      `Do your shopping with the weekly lists provided.`,
      `Weigh yourself once a week, fasted, and adjust if needed.`,
    ] },
    { type: 'note', text: `A cut is a marathon, not a sprint. A steady loss of 0.5 to 0.8% of your bodyweight per week preserves muscle. Going faster = melting muscle and breaking your metabolism.` },

    { type: 'h1', text: 'The principle of cutting' },
    { type: 'p', text: `Cutting means losing fat mass while preserving muscle. It requires three things at once.` },
    { type: 'list', items: [
      `A moderate caloric deficit: 15 to 20% below your maintenance, no more.`,
      `High protein: 2 to 2.4 g per kg to protect lean mass.`,
      `Keeping up strength training: it's the signal that tells the body to hold onto muscle.`,
    ] },
    { type: 'p', text: `Carbs and fats fill the rest of your calories: they give you the energy to train and support your hormones. You don't cut them out - you adjust them.` },

    { type: 'chapter', title: 'Your custom macros', src: 'seche-1.jpg' },
    { type: 'p', text: `Here's how to calculate your needs in 3 steps. No precision scale needed: these benchmarks are enough for the vast majority of cases.` },
    { type: 'h2', text: 'Step 1 - Your maintenance' },
    { type: 'p', text: `Quick estimate: bodyweight (kg) × 30 to 33 (depending on your activity). Example for 75 kg, moderately active: 75 × 31 ≈ 2,325 kcal/day maintenance.` },
    { type: 'h2', text: 'Step 2 - Your deficit' },
    { type: 'p', text: `Subtract 15 to 20%: 2,325 − 18% ≈ 1,900 kcal/day. That's your cutting calorie target.` },
    { type: 'h2', text: 'Step 3 - Split into macros' },
    { type: 'table', headers: ['Macro', 'Calculation', 'Example (75 kg, 1,900 kcal)'], rows: [
      ['Protein', '2.2 g/kg', '165 g (660 kcal)'],
      ['Fats', '0.8 g/kg', '60 g (540 kcal)'],
      ['Carbs', 'the rest', '175 g (700 kcal)'],
    ] },
    { type: 'h2', text: 'Calorie benchmarks by bodyweight' },
    { type: 'table', headers: ['Weight', 'Maintenance ≈', 'Cut ≈', 'Protein'], rows: [
      ['60 kg', '1,860 kcal', '1,500 kcal', '130 g'],
      ['70 kg', '2,170 kcal', '1,750 kcal', '155 g'],
      ['80 kg', '2,480 kcal', '2,000 kcal', '175 g'],
      ['90 kg', '2,790 kcal', '2,250 kcal', '200 g'],
    ] },
    { type: 'note', text: `Adjust after 2 weeks: no loss → cut 100-150 kcal (evening carbs). Losing too fast (> 1%/week) or losing strength → add 100-150 kcal.` },

    { type: 'h1', text: 'The golden rules of cutting' },
    { type: 'list', items: [
      `A protein source at EVERY meal (0.4 g/kg per serving).`,
      `Half the plate vegetables: volume, satiety, micronutrients.`,
      `Carbs mostly around training (energy + recovery).`,
      `2 to 2.5 L of water/day: a big glass before each meal (satiety effect).`,
      `Limit liquid sugar and alcohol (empty calories that sabotage the deficit).`,
      `1 treat meal per week to last the distance without cracking.`,
    ] },

    { type: 'chapter', title: 'Meal plan - 56 days', src: 'seche-2.jpg', intro: `Here are 8 weeks of ready-to-follow menus (≈1,800-1,900 kcal, adjust portions to YOUR macros). Each week rotates meals to avoid boredom. All recipes are detailed later. Vegan version: see the dedicated chapter.` },
    { type: 'h2', text: 'Week 1' },
    { type: 'table', headers: ['Day', 'Breakfast', 'Lunch', 'Dinner'], rows: [
      ['Mon', 'Skyr-oats-fruit', 'Chicken-rice-broccoli', 'Salmon-sweet potato-salad'],
      ['Tue', '3-egg omelette + bread', 'Lean beef-quinoa-veg', 'Stir-fried tofu-rice-zucchini'],
      ['Wed', 'Skyr-oats-fruit', 'Chicken wrap-raw veg', 'Cod-potatoes-green beans'],
      ['Thu', 'Scrambled eggs + avocado', 'Turkey-brown rice-peppers', 'Veg omelette + salad'],
      ['Fri', 'Protein porridge', 'Chickpea-tuna salad', 'Chicken-sweet potato-spinach'],
      ['Sat', 'Protein pancakes', 'Treat meal (reasonable)', 'Soup + boiled eggs + bread'],
      ['Sun', 'Skyr-fruit-almonds', 'Chicken-rice-veg bowl', 'White fish-quinoa-salad'],
    ] },
    { type: 'h2', text: 'Week 2' },
    { type: 'table', headers: ['Day', 'Breakfast', 'Lunch', 'Dinner'], rows: [
      ['Mon', 'Omelette + oats', 'Beef-rice-broccoli', 'Tofu-quinoa-greens'],
      ['Tue', 'Skyr-oats-fruit', 'Chicken-sweet potato-salad', 'Cod-rice-zucchini'],
      ['Wed', 'Avocado-egg toast', 'Turkey wrap-raw veg', 'Salmon-potatoes-green beans'],
      ['Thu', 'Protein porridge', 'Quinoa-chicken salad', 'Veg omelette + wholegrain bread'],
      ['Fri', 'Protein pancakes', 'Fish-brown rice-spinach', 'Chicken-zucchini-feta'],
      ['Sat', 'Skyr-fruit-almonds', 'Treat meal (reasonable)', 'Soup + tuna + bread'],
      ['Sun', 'Scrambled eggs + avocado', 'Beef-rice-veg bowl', 'White fish-sweet potato-salad'],
    ] },
    { type: 'h2', text: 'Week 3' },
    { type: 'table', headers: ['Day', 'Breakfast', 'Lunch', 'Dinner'], rows: [
      ['Mon', 'Protein porridge', 'Chicken-quinoa-zucchini', 'Cod-sweet potato-green beans'],
      ['Tue', 'Skyr-oats-fruit', 'Lean beef-rice-broccoli', 'Stir-fried tofu-rice-pepper'],
      ['Wed', 'Omelette + bread', 'Chicken-feta-tomato salad', 'Salmon-potatoes-spinach'],
      ['Thu', 'Protein pancakes', 'Turkey wrap-raw veg', 'Veg omelette + salad'],
      ['Fri', 'Avocado-egg toast', 'Tuna-white beans-tomato', 'Chicken-zucchini-quinoa'],
      ['Sat', 'Skyr-fruit-almonds', 'Treat meal (reasonable)', 'Veg soup + boiled eggs'],
      ['Sun', 'Scrambled eggs + avocado', 'Chicken-rice-veg bowl', 'White fish-sweet potato-salad'],
    ] },
    { type: 'h2', text: 'Week 4' },
    { type: 'table', headers: ['Day', 'Breakfast', 'Lunch', 'Dinner'], rows: [
      ['Mon', 'Skyr-oats-fruit', 'Turkey-brown rice-peppers', 'Stir-fried shrimp-rice-zucchini'],
      ['Tue', '3-egg omelette', 'Chicken-sweet potato-broccoli', 'Tofu-quinoa-greens'],
      ['Wed', 'Protein porridge', 'Chickpea-tuna salad', 'Cod-potatoes-green beans'],
      ['Thu', 'Spinach-whey-banana smoothie', 'Lean beef-quinoa-veg', 'Veg omelette + bread'],
      ['Fri', 'Protein pancakes', 'Chicken wrap-raw veg', 'Salmon-sweet potato-salad'],
      ['Sat', 'Skyr-fruit-almonds', 'Treat meal (reasonable)', 'Lentil-veg soup'],
      ['Sun', 'Avocado-egg toast', 'Beef-rice-veg bowl', 'White fish-quinoa-spinach'],
    ] },
    { type: 'h2', text: 'Week 5' },
    { type: 'table', headers: ['Day', 'Breakfast', 'Lunch', 'Dinner'], rows: [
      ['Mon', 'Protein porridge', 'Chicken-rice-broccoli', 'Stir-fried tofu-rice-zucchini'],
      ['Tue', 'Skyr-oats-fruit', 'Lean beef-sweet potato-salad', 'Cod-quinoa-green beans'],
      ['Wed', 'Omelette + bread', 'Quinoa-edamame-tofu salad', 'Salmon-potatoes-spinach'],
      ['Thu', 'Protein pancakes', 'Turkey-brown rice-peppers', 'Veg omelette + salad'],
      ['Fri', 'Avocado-egg toast', 'Chicken wrap-raw veg', 'Chicken-zucchini-feta'],
      ['Sat', 'Skyr-fruit-almonds', 'Treat meal (reasonable)', 'Soup + tuna + bread'],
      ['Sun', 'Scrambled eggs + avocado', 'Chicken-rice-veg bowl', 'White fish-sweet potato-salad'],
    ] },
    { type: 'h2', text: 'Week 6' },
    { type: 'table', headers: ['Day', 'Breakfast', 'Lunch', 'Dinner'], rows: [
      ['Mon', 'Skyr-oats-fruit', 'Lean beef-rice-broccoli', 'Shrimp-rice-zucchini'],
      ['Tue', '3-egg omelette', 'Chicken-quinoa-veg', 'Tofu-quinoa-pepper'],
      ['Wed', 'Protein porridge', 'Chicken-feta-tomato salad', 'Cod-potatoes-green beans'],
      ['Thu', 'Protein pancakes', 'Tuna-white beans-tomato', 'Veg omelette + bread'],
      ['Fri', 'Avocado-egg toast', 'Turkey-sweet potato-spinach', 'Salmon-quinoa-salad'],
      ['Sat', 'Skyr-fruit-almonds', 'Treat meal (reasonable)', 'Veg soup + boiled eggs'],
      ['Sun', 'Scrambled eggs + avocado', 'Beef-rice-veg bowl', 'White fish-sweet potato-salad'],
    ] },
    { type: 'h2', text: 'Week 7' },
    { type: 'table', headers: ['Day', 'Breakfast', 'Lunch', 'Dinner'], rows: [
      ['Mon', 'Protein porridge', 'Chicken-rice-broccoli', 'Stir-fried tofu-rice-zucchini'],
      ['Tue', 'Skyr-oats-fruit', 'Lean beef-quinoa-veg', 'Cod-sweet potato-green beans'],
      ['Wed', 'Omelette + bread', 'Turkey wrap-raw veg', 'Salmon-potatoes-spinach'],
      ['Thu', 'Spinach-whey-banana smoothie', 'Chickpea-tuna salad', 'Veg omelette + salad'],
      ['Fri', 'Protein pancakes', 'Chicken-sweet potato-peppers', 'Shrimp-quinoa-zucchini'],
      ['Sat', 'Skyr-fruit-almonds', 'Treat meal (reasonable)', 'Lentil-veg soup'],
      ['Sun', 'Avocado-egg toast', 'Chicken-rice-veg bowl', 'White fish-quinoa-salad'],
    ] },
    { type: 'h2', text: 'Week 8 (finish)' },
    { type: 'table', headers: ['Day', 'Breakfast', 'Lunch', 'Dinner'], rows: [
      ['Mon', 'Skyr-oats-fruit', 'Chicken-rice-broccoli', 'Cod-sweet potato-green beans'],
      ['Tue', '3-egg omelette', 'Lean beef-quinoa-veg', 'Tofu-quinoa-pepper'],
      ['Wed', 'Protein porridge', 'Chicken-feta-tomato salad', 'Salmon-potatoes-spinach'],
      ['Thu', 'Protein pancakes', 'Turkey-brown rice-veg', 'Veg omelette + salad'],
      ['Fri', 'Avocado-egg toast', 'Tuna-white beans-tomato', 'Chicken-zucchini-quinoa'],
      ['Sat', 'Skyr-fruit-almonds', 'Light treat meal', 'Soup + boiled eggs'],
      ['Sun', 'Scrambled eggs + avocado', 'Chicken-rice-veg bowl', 'White fish-sweet potato-salad'],
    ] },
    { type: 'note', text: `Tip: you can keep the same breakfast 2-3 days in a row to simplify - variety matters across the week. Always adjust the PORTIONS to YOUR macros (previous chapter).` },

    { type: 'chapter', title: 'Your shopping lists', src: 'seche-1.jpg', intro: `Shop 1 to 2 times a week with these lists. Buying the right foods = eating well without thinking.` },
    { type: 'h2', text: 'Protein' },
    { type: 'list', items: [`Chicken, turkey, lean (5%) beef`, `White fish, salmon, tuna`, `Eggs, skyr, 0% fromage blanc`, `Tofu, tempeh, legumes`, `Whey (option)`] },
    { type: 'h2', text: 'Carbs & starches' },
    { type: 'list', items: [`Rice, quinoa, wholegrain pasta`, `Sweet potato, potatoes`, `Oats, wholegrain bread`, `Fruit (banana, apple, berries)`] },
    { type: 'h2', text: 'Vegetables & fats' },
    { type: 'list', items: [`Broccoli, zucchini, spinach, green beans, bell pepper, salad, tomato`, `Olive oil, avocado, almonds, walnuts`, `Lemon, garlic, herbs, spices (unlimited)`] },

    { type: 'chapter', title: 'Recipes - Breakfasts', src: 'seche-2.jpg' },
    { type: 'h2', text: '1. Skyr-oats-berries' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 350 kcal' }, { label: 'Protein', value: '30 g' }] },
    { type: 'list', items: [`200 g skyr`, `40 g oats`, `1 handful of berries`] },
    { type: 'p', text: `Mix skyr and oats, let sit 5 min, add the fruit.` },
    { type: 'h2', text: '2. Protein omelette' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 320 kcal' }, { label: 'Protein', value: '28 g' }] },
    { type: 'list', items: [`3 eggs`, `Spinach, tomato`, `1 slice of wholegrain bread`] },
    { type: 'p', text: `Beat the eggs, cook with the vegetables on low heat, serve with the bread.` },
    { type: 'h2', text: '3. Protein porridge' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 380 kcal' }, { label: 'Protein', value: '32 g' }] },
    { type: 'list', items: [`50 g oats`, `250 ml milk`, `1 scoop whey`, `Cinnamon`] },
    { type: 'p', text: `Heat the oats in the milk for 3 min, off the heat stir in the whey and cinnamon.` },
    { type: 'h2', text: '4. Protein pancakes' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 360 kcal' }, { label: 'Protein', value: '30 g' }] },
    { type: 'list', items: [`1 banana`, `2 eggs`, `40 g oats`, `1/2 scoop whey`] },
    { type: 'p', text: `Blend everything, cook small pancakes in a pan. Top with fruit.` },
    { type: 'h2', text: '5. Avocado-egg toast' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 380 kcal' }, { label: 'Protein', value: '22 g' }] },
    { type: 'list', items: [`2 slices of wholegrain bread`, `1/2 avocado`, `2 eggs`, `Lemon, pepper`] },
    { type: 'p', text: `Mash the avocado on the bread, add the eggs (fried or poached).` },

    { type: 'h1', text: 'Recipes - Lunches' },
    { type: 'h2', text: '6. Chicken-rice-veg bowl' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 480 kcal' }, { label: 'Protein', value: '42 g' }] },
    { type: 'list', items: [`130 g chicken`, `100 g rice (dry)`, `Vegetables`, `Soy sauce`] },
    { type: 'p', text: `Cook the rice, sear the chicken and vegetables, assemble.` },
    { type: 'h2', text: '7. Chicken wrap-raw veg' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protein', value: '38 g' }] },
    { type: 'list', items: [`1 wholegrain wrap`, `120 g chicken`, `Raw veg`, `Fromage blanc + mustard`] },
    { type: 'p', text: `Spread, fill, roll tight.` },
    { type: 'h2', text: '8. Chickpea-tuna salad' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protein', value: '35 g' }] },
    { type: 'list', items: [`1 can of chickpeas`, `1 can of tuna`, `Tomatoes, onion`, `Lemon, olive oil`] },
    { type: 'p', text: `Mix everything. Quick, no cooking.` },
    { type: 'h2', text: '9. Lean beef-quinoa' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 520 kcal' }, { label: 'Protein', value: '45 g' }] },
    { type: 'list', items: [`140 g 5% beef`, `80 g quinoa (dry)`, `Green vegetables`, `Spices`] },
    { type: 'p', text: `Sear the beef, serve over the quinoa with the vegetables.` },

    { type: 'h1', text: 'Recipes - Dinners' },
    { type: 'h2', text: '10. Salmon-sweet potato-salad' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 500 kcal' }, { label: 'Protein', value: '38 g' }] },
    { type: 'list', items: [`130 g salmon`, `200 g sweet potato`, `Green salad`, `Olive oil, lemon`] },
    { type: 'p', text: `Cook the salmon and sweet potato in the oven, serve with the salad.` },
    { type: 'h2', text: '11. Cod-potatoes-green beans' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 430 kcal' }, { label: 'Protein', value: '40 g' }] },
    { type: 'list', items: [`160 g cod`, `200 g potatoes`, `Green beans`, `Herbs`] },
    { type: 'p', text: `Steam or roast everything, season.` },
    { type: 'h2', text: '12. Stir-fried tofu-rice-zucchini' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protein', value: '28 g' }] },
    { type: 'list', items: [`150 g firm tofu`, `80 g rice (dry)`, `Zucchini`, `Soy sauce, ginger`] },
    { type: 'p', text: `Sear the tofu, add the zucchini, serve over the rice.` },
    { type: 'h2', text: '13. Evening veg omelette' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 320 kcal' }, { label: 'Protein', value: '28 g' }] },
    { type: 'list', items: [`3 eggs`, `Spinach, bell pepper`, `Green salad`] },
    { type: 'p', text: `Sauté the vegetables, pour in the eggs, serve with a salad.` },

    { type: 'h1', text: 'Recipes - Snacks' },
    { type: 'h2', text: '14. Protein skyr' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 220 kcal' }, { label: 'Protein', value: '28 g' }] },
    { type: 'list', items: [`250 g skyr`, `Berries`, `Cinnamon`] },
    { type: 'p', text: `Mix. Perfect between meals or after training.` },
    { type: 'h2', text: '15. Protein shake' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 200 kcal' }, { label: 'Protein', value: '25 g' }] },
    { type: 'list', items: [`1 scoop whey`, `250 ml water or skim milk`, `Ice`] },
    { type: 'p', text: `Blend or shake. Handy at the office.` },
    { type: 'h2', text: '16. Boiled eggs + raw veg' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 180 kcal' }, { label: 'Protein', value: '16 g' }] },
    { type: 'list', items: [`2 boiled eggs`, `Carrot/cucumber sticks`, `Salt, pepper`] },
    { type: 'p', text: `Boil the eggs 9 min, serve with the raw veg.` },
    { type: 'h2', text: '17. Cottage cheese-pineapple' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 200 kcal' }, { label: 'Protein', value: '24 g' }] },
    { type: 'list', items: [`200 g cottage cheese`, `100 g pineapple`, `Cinnamon`] },
    { type: 'p', text: `Mix. A sweet-savory snack, very high in protein and low in calories.` },
    { type: 'h2', text: '18. Stir-fried shrimp-rice-zucchini' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 430 kcal' }, { label: 'Protein', value: '38 g' }] },
    { type: 'list', items: [`150 g shrimp`, `80 g rice (dry)`, `Zucchini, garlic`, `Soy sauce`] },
    { type: 'p', text: `Sear the shrimp with garlic, add the zucchini, serve over the rice.` },
    { type: 'h2', text: '19. Lentil-veg soup' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 350 kcal' }, { label: 'Protein', value: '22 g' }] },
    { type: 'list', items: [`100 g lentils (dry)`, `Carrot, onion, tomato`, `Cumin, stock`] },
    { type: 'p', text: `Simmer for 25 min. Filling, high in fiber, perfect in the evening.` },
    { type: 'h2', text: '24 bonus express recipes' },
    { type: 'p', text: `Also pick from these quick ideas (build them around your macros) - so you never run out of options:` },
    { type: 'table', headers: ['Recipe', 'Type', 'Protein'], rows: [
      ['Chicken-avocado wrap', 'Lunch', '35 g'],
      ['Grilled turkey-zucchini', 'Dinner', '40 g'],
      ['Quinoa-edamame-tofu bowl', 'Lunch', '30 g'],
      ['Greek yogurt-walnuts-honey', 'Snack', '18 g'],
      ['Oat-egg-white pancake', 'Breakfast', '24 g'],
      ['Baked eggs-spinach', 'Breakfast', '20 g'],
      ['Tuna-green bean-egg salad', 'Lunch', '36 g'],
      ['Turkey-pepper-rice stir-fry', 'Lunch', '40 g'],
      ['Cod en papillote-veg', 'Dinner', '38 g'],
      ['Chili sin carne (tofu/beans)', 'Dinner', '28 g'],
      ['Fromage blanc-berries-seeds', 'Snack', '22 g'],
      ['Smoked salmon-cream cheese wrap', 'Lunch', '30 g'],
      ['Buddha bowl veg-chickpeas', 'Lunch', '24 g'],
      ['5% beef patty-green beans', 'Dinner', '40 g'],
      ['Egg-potato tortilla', 'Breakfast', '26 g'],
      ['Berry protein smoothie', 'Snack', '28 g'],
      ['Teriyaki chicken-broccoli-rice', 'Lunch', '42 g'],
      ['Lentil-feta-tomato salad', 'Lunch', '24 g'],
      ['Chickpea-spinach curry', 'Dinner', '22 g'],
      ['Turkey breast-raw veg', 'Snack', '25 g'],
      ['Egg fried rice-veg-edamame', 'Lunch', '26 g'],
      ['Cod-sweet potato mash', 'Dinner', '38 g'],
      ['Skyr-homemade granola-fruit', 'Breakfast', '28 g'],
      ['Miso-tofu-veg soup', 'Dinner', '20 g'],
    ] },
    { type: 'note', text: `In total, more than 40 recipes: combine them freely with the menus for 8 weeks without ever getting bored.` },

    { type: 'chapter', title: 'Batch cooking & organization', src: 'seche-2.jpg', intro: `The secret to a successful cut: never be caught off guard. Cook twice a week in big batches - you eat better and don't cave to the first fast option.` },
    { type: 'list', items: [
      `Sunday & Wednesday: cook 1 kg of protein (chicken, beef, tofu) + 500 g of starches (rice, quinoa).`,
      `Cut and wash your vegetables in advance, store in containers.`,
      `Prepare 4-5 identical portions, just vary the seasoning (soy sauce, lemon, spices).`,
      `Always keep boiled eggs and skyr in the fridge for cravings.`,
      `Invest in 4-5 airtight containers: the #1 tool of a cut.`,
    ] },

    { type: 'chapter', title: 'Vegan version', src: 'seche-1.jpg', intro: `Cutting works perfectly on a vegan diet: just aim for varied, complete plant proteins. Simply swap animal proteins for their equivalents.` },
    { type: 'table', headers: ['Instead of…', 'Use…', 'Protein'], rows: [
      ['Chicken / beef', 'Firm tofu, tempeh, seitan', '15-25 g/100 g'],
      ['Eggs', 'Scrambled tofu, chickpeas', '8-19 g'],
      ['Skyr / fromage blanc', 'Plain soy yogurt', '6-10 g'],
      ['Whey', 'Pea / rice protein', '20-25 g/scoop'],
      ['Tuna / fish', 'Chickpeas, lentils, edamame', '9-20 g'],
    ] },
    { type: 'list', items: [
      `Aim for variety: combine grains + legumes for complete proteins.`,
      `Supplement B12 (essential when vegan) and watch your iron.`,
      `Legumes also bring filling fiber - ideal on a cut.`,
    ] },

    { type: 'h1', text: 'Tips to succeed' },
    { type: 'list', items: [
      `Prep your meals ahead (batch cooking) twice a week.`,
      `Drink a big glass of water at the first craving: we often confuse thirst with hunger.`,
      `Keep protein snacks on hand (skyr, boiled egg, turkey breast).`,
      `Sleep 7-8 h: lack of sleep increases hunger and slows fat loss.`,
      `Keep lifting: it's what preserves your muscle during the deficit.`,
    ] },

    { type: 'h1', text: 'Mistakes to avoid' },
    { type: 'list', items: [
      `Too aggressive a deficit: you lose muscle, your energy crashes, you crack.`,
      `Skipping protein: the #1 priority on a cut.`,
      `Cutting out carbs entirely: you lose energy and performance.`,
      `Weighing yourself every day: weight fluctuates, watch the 2-week trend.`,
      `Forgetting alcohol and sauces: hidden calories that block the deficit.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: ['You run into…', 'The solution'], rows: [
      ['The scale stalls for 2 weeks', 'Cut 100-150 kcal (evening carbs)'],
      ['Constant hunger', 'More protein + vegetables + water'],
      ['Lack of energy', 'Keep carbs around training'],
      ['Sugar cravings at night', 'Skyr + berries, or a planned treat meal'],
    ] },

    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: 'How long to see results?' },
    { type: 'p', text: `From 2-3 weeks for the first changes (some of which is water in week 1). Visible definition shows between 4 and 8 weeks depending on your starting point.` },
    { type: 'h2', text: 'Do I have to count calories?' },
    { type: 'p', text: `At the start it's useful to calibrate. After that, the menus and portion benchmarks are enough. What matters is the consistency of the deficit over the week.` },
    { type: 'h2', text: 'Can I follow this plan without training?' },
    { type: 'p', text: `You'll lose weight, but some of it will be muscle. For a real cut (losing fat while staying fit), keep at least 2-3 strength sessions per week.` },
    { type: 'h2', text: 'Will the treat meal ruin everything?' },
    { type: 'p', text: `No: 1 meal out of 21 still leaves a weekly deficit. It preserves your motivation and social life - the real drivers of quitting.` },
    { type: 'h2', text: 'And after the 8 weeks?' },
    { type: 'p', text: `Raise your calories gradually back toward maintenance (+100 kcal/week) to avoid the yo-yo effect, then stabilize or move into a mass-gain phase.` },

    { type: 'h1', text: 'Eating out & handling the unexpected' },
    { type: 'p', text: `A cut shouldn't stop you from living. With a few reflexes, you stay on target even at a restaurant or on the move.` },
    { type: 'list', items: [
      `At a restaurant: choose a lean protein (grilled meat, fish) + vegetables, sauce on the side.`,
      `Avoid the liquid aperitif (alcohol, sodas): swap for sparkling water with lemon.`,
      `Fast food: go for grilled options, salad, and skip the fries/sugary sauces.`,
      `On the move: keep protein bars, skyr or boiled eggs with you.`,
      `One "off-plan" day breaks nothing: just pick up at the next meal.`,
    ] },
    { type: 'table', headers: ['Situation', 'Smart move'], rows: [
      ['Restaurant', 'Grilled protein + vegetables, sauce on the side'],
      ['Pizza/burger', 'Simple version, no XL menu, water'],
      ['Drinks', 'Raw veg, sparkling water, 1 glass max'],
      ['Brunch', 'Eggs, fromage blanc, fruit, wholegrain bread'],
    ] },

    { type: 'h1', text: 'Useful supplements on a cut' },
    { type: 'p', text: `None are mandatory - food comes first. But some help you hold the deficit and preserve muscle.` },
    { type: 'table', headers: ['Supplement', 'Benefit on a cut', 'Dose'], rows: [
      ['Whey / iso', 'Hit your protein with few calories', '1 to 2 scoops/day'],
      ['Creatine', 'Maintain strength during the deficit', '3 to 5 g/day'],
      ['Coffee / caffeine', 'Appetite suppressant and energy', 'In moderation'],
      ['Psyllium / fiber', 'Satiety and digestion', 'As needed'],
      ['Multivitamins', 'Cover any deficiencies', '1/day (option)'],
    ] },
    { type: 'note', text: `Beware miracle "fat burners": none replace the caloric deficit. Save your money for good food.` },

    { type: 'h1', text: 'Tracking your cut' },
    { type: 'p', text: `Measure yourself every week, fasted, under the same conditions. The photo and waist circumference are often more telling than the scale.` },
    { type: 'h2', text: 'Weight & measurements' },
    { type: 'tracker', columns: ['Date', 'Weight (kg)', 'Waist (cm)', 'Energy /10'], rows: 9 },
    { type: 'h2', text: 'Intake (optional)' },
    { type: 'tracker', columns: ['Date', 'Calories', 'Protein (g)', 'Water (L)'], rows: 7 },

    { type: 'h1', text: 'Weekly checklist' },
    { type: 'p', text: `Tick each box at the end of the week. Goal: at least 6 out of 8.` },
    { type: 'checklist', items: [
      `I respected my caloric deficit most days.`,
      `I hit my protein every day.`,
      `I ate vegetables at every main meal.`,
      `I drank 2 L of water per day.`,
      `I limited liquid sugar and alcohol.`,
      `I kept up my strength sessions.`,
      `I weighed myself once, under the same conditions.`,
      `I prepped my meals in advance.`,
    ] },

    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My favorite meals, feelings and adjustments for the week'], rows: 16 },

    { type: 'note', text: `8 weeks of cutting done? Raise your calories gently, keep your good habits, then move into a clean mass-gain or maintenance phase. Create your account at xenotif.com for your tracking and AI coach.` },
  ],
}
