import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines' // base URL for exercise demo video QR codes

export const perteDePoids30jEn: Guide = {
  id: 'perte-de-poids-30j',
  title: 'Weight Loss Program',
  subtitle: '30 days to kick-start lasting fat loss, without extreme dieting',
  author: 'XENOTIF Coach - Certified strength & nutrition coaching',
  level: 'Beginner - Intermediate',
  duration: '30 days · 5 sessions/week',
  coverImage: 'perte-de-poids-cover.jpg',
  blocks: [
    // ── INTRO ──────────────────────────────────────────────
    { type: 'h1', text: 'Welcome to your 30-day challenge' },
    { type: 'p', text: `Over the next 30 days, you're going to kick-start real, lasting fat loss - no extreme dieting, no endless workouts. The method rests on three simple, proven levers: a slight calorie deficit, short but effective sessions, and consistency. Follow the day-by-day plan, tick your checklist every week, fill in your tracker, and let the results build.` },
    { type: 'p', text: `This document is your pocket coach: keep it on your phone, print it, annotate it. Every exercise has a QR code that opens a demo video on XENOTIF® - scan it whenever you're unsure about the technique.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Lose 2 to 4 kg of fat' },
      { label: 'Level', value: 'Beginner to intermediate' },
      { label: 'Duration', value: '30 days (4 weeks)' },
      { label: 'Frequency', value: '5 sessions per week' },
      { label: 'Equipment', value: 'Mat + 1 pair of dumbbells (optional)' },
      { label: 'Location', value: 'Home or gym' },
    ] },
    { type: 'h2', text: 'Program goals' },
    { type: 'list', items: [
      `Lose 2 to 4 kg of body fat (depending on your starting point).`,
      `Refine your shape: flatter stomach, better definition.`,
      `Gain energy, stamina, and better sleep quality.`,
      `Build healthy eating habits that last well beyond the 30 days.`,
    ] },
    { type: 'h2', text: 'How to use this guide' },
    { type: 'list', items: [
      `Read through the whole guide once before you start.`,
      `Follow the 30-day calendar: each day tells you exactly what to do.`,
      `Before every session, do the 5-minute warm-up (dedicated page).`,
      `Scan an exercise's QR code if you want to review the technique on video.`,
      `Every Sunday: fill in your tracker and tick your weekly checklist.`,
    ] },
    { type: 'h2', text: 'Required level' },
    { type: 'p', text: `No prerequisites: the program starts from zero and ramps up gradually. If you're already active, use the advanced variations indicated and shorten rest times. If you're in pain, pregnant, or have a medical condition, check with a doctor before starting.` },
    { type: 'note', text: `Golden rule: fat loss is 70% decided in the kitchen. Training speeds up the result, but dietary consistency is what makes the real difference.` },

    // ── METHOD ────────────────────────────────────────────
    { type: 'h1', text: 'How it works' },
    { type: 'list', items: [
      `Moderate calorie deficit: eat 300 to 500 kcal below your maintenance, never more.`,
      `Move more daily (NEAT): aim for 8,000 to 10,000 steps a day.`,
      `Sets × reps: "3 × 12" = 3 sets of 12 reps.`,
      `Rest: 30 to 60 seconds between sets to keep intensity and heart rate up.`,
      `RPE (perceived effort out of 10): aim for 7 to 8. You should have about 2 reps "left in the tank".`,
      `Warm up 5 minutes before every session and stretch 5 minutes after.`,
    ] },
    { type: 'h2', text: 'The calorie deficit, explained simply' },
    { type: 'p', text: `Your body burns a certain number of calories every day (your "maintenance"). If you eat a bit less than that, it draws on your fat reserves to make up the difference: that's the deficit. Too light and you won't lose; too aggressive and you'll lose muscle, your energy will crash, and you'll give in to cravings. The ideal zone: 300 to 500 kcal below maintenance. Enough to lose 0.5 to 0.8 kg of fat per week, without suffering.` },
    { type: 'h2', text: 'Why train while losing fat?' },
    { type: 'p', text: `Muscle is metabolically active: the more you have, the more calories you burn at rest. Above all, doing strength work during a deficit tells your body to keep the muscle and draw from fat instead. Result: you don't end up "skinny-fat", but lean and toned.` },

    // ── WARM-UP ───────────────────────────────────────────
    { type: 'h1', text: 'Warm-up & cool-down' },
    { type: 'p', text: `Never skip the warm-up: it preps your joints, boosts performance, and markedly cuts injury risk. The cool-down speeds up recovery and limits soreness.` },
    { type: 'h2', text: 'Typical warm-up (5 minutes)' },
    { type: 'table', headers: ['Movement', 'Duration'], rows: [
      ['Brisk walk or jog in place', '60 s'],
      ['High knees', '45 s'],
      ['Arm & hip circles', '45 s'],
      ['Slow squats (growing range)', '45 s'],
      ['Dynamic lunges', '45 s'],
      ['Butt kicks', '40 s'],
    ] },
    { type: 'h2', text: 'Cool-down (5 minutes)' },
    { type: 'list', items: [
      `Slow walk 1 to 2 min to bring the heart rate down.`,
      `Stretch quads, hamstrings, glutes, calves: 20 to 30 s each.`,
      `Stretch chest, back, and shoulders: 20 to 30 s.`,
      `3 to 5 deep breaths to close out the session.`,
    ] },

    // ── NUTRITION ──────────────────────────────────────────
    { type: 'photo', src: 'nutrition.jpg', caption: '70% of the result is decided on the plate.' },
    { type: 'h1', text: 'Nutrition plan' },
    { type: 'p', text: `No need to weigh every gram of every food. Apply these simple benchmarks, and the scale will move in the right direction week after week.` },
    { type: 'meta', items: [
      { label: 'Target deficit', value: '300 to 500 kcal / day' },
      { label: 'Protein', value: '1.8 to 2.2 g per kg of bodyweight' },
      { label: 'Hydration', value: '2 to 2.5 L of water per day' },
      { label: 'Sleep', value: '7 to 8 h (key to fat loss)' },
    ] },
    { type: 'h2', text: 'The 5 golden rules' },
    { type: 'list', items: [
      `A protein source at every meal (eggs, chicken, fish, tofu, legumes, skyr).`,
      `Half the plate in vegetables at every main meal.`,
      `Carbs mainly around your training (rice, sweet potato, oats, fruit).`,
      `Cut liquid sugar (soda, juice, alcohol) - the fastest, most rewarding win.`,
      `Keep 1 treat meal a week: total deprivation leads to bingeing.`,
    ] },
    { type: 'h2', text: 'How much should you eat?' },
    { type: 'p', text: `Quick estimate of your maintenance: bodyweight (kg) × roughly 30. Example for 70 kg: ≈ 2,100 kcal. Aim then for 1,600 to 1,800 kcal/day. Adjust after 2 weeks based on your weight trend: no loss → cut 100-150 kcal; losing too fast (> 1 kg/week) → add 100-150 kcal.` },
    { type: 'h2', text: 'Typical day (≈ 1,800 kcal)' },
    { type: 'table', headers: ['Meal', 'Example', 'Protein'], rows: [
      ['Breakfast', 'Skyr + oats + berries', '30 g'],
      ['Lunch', 'Chicken + rice + green vegetables + olive oil', '40 g'],
      ['Snack', '1 piece of fruit + a handful of almonds', '8 g'],
      ['Dinner', 'Salmon (or tofu) + sweet potato + salad', '35 g'],
      ['Total', '≈ 1,800 kcal · moderate deficit', '≈ 113 g'],
    ] },
    { type: 'h2', text: 'Basic shopping list' },
    { type: 'list', items: [
      `Protein: eggs, chicken, turkey, white fish, salmon, tofu, skyr, lentils.`,
      `Carbs: rice, sweet potato, oats, whole-grain bread, fruit.`,
      `Vegetables: broccoli, zucchini, spinach, bell pepper, tomatoes, salad greens.`,
      `Healthy fats: olive oil, avocado, almonds, walnuts.`,
      `Extras: coffee/tea, spices, lemon, balsamic vinegar.`,
    ] },
    { type: 'h2', text: 'Hydration & supplements' },
    { type: 'list', items: [
      `Water: 2 to 2.5 L/day. Drink a large glass before every meal (satiety effect).`,
      `Sugar-free coffee/tea: fine, and a natural appetite suppressant before training.`,
      `Useful supplements (optional): whey if you're short on protein, vitamin D in winter, omega-3.`,
      `Useless: miracle "fat burners". None of them replace the deficit.`,
    ] },
    { type: 'note', text: `Batch-cooking tip: cook twice a week in bulk (protein + carbs + vegetables). When it's already prepped, you eat better and don't give in to the first quick meal on hand.` },
    { type: 'h2', text: 'Understanding your macros (in 2 minutes)' },
    { type: 'p', text: `Calories come from three macronutrients. You don't need to track everything, but understanding their role helps you build better plates.` },
    { type: 'table', headers: ['Macro', 'Role', 'Per g', 'Priority when cutting'], rows: [
      ['Protein', 'Preserves muscle, fills you up', '4 kcal', 'HIGH - 1.8-2.2 g/kg'],
      ['Carbs', 'Energy, performance', '4 kcal', 'Around training'],
      ['Fat', 'Hormones, satiety', '9 kcal', 'Moderate, quality'],
    ] },
    { type: 'list', items: [
      `Always prioritize protein: it's macro #1 for fat loss.`,
      `Carbs don't "make you fat": it's total calorie surplus that counts.`,
      `Keep some healthy fats (olive oil, avocado, nuts) for hormones and satiety.`,
    ] },

    // ── RECIPES ───────────────────────────────────────────
    { type: 'h1', text: 'Express recipes (under 15 min)' },
    { type: 'p', text: `Four simple, protein-rich, filling recipes so you're never caught off guard.` },
    { type: 'h2', text: 'Protein breakfast bowl' },
    { type: 'meta', items: [
      { label: 'Calories', value: '≈ 380 kcal' },
      { label: 'Protein', value: '32 g' },
    ] },
    { type: 'list', items: [`200 g plain skyr`, `40 g oats`, `1 handful of berries`, `1 tsp honey (optional)`] },
    { type: 'p', text: `Prep: mix the skyr and oats, let sit 5 min (or overnight in the fridge). Add the berries and honey. Ready.` },
    { type: 'h2', text: 'Chicken & veggie wrap' },
    { type: 'meta', items: [
      { label: 'Calories', value: '≈ 450 kcal' },
      { label: 'Protein', value: '38 g' },
    ] },
    { type: 'list', items: [`1 whole-wheat wrap`, `120 g grilled chicken`, `Lettuce, tomato, cucumber`, `1 tbsp cottage cheese + mustard`] },
    { type: 'p', text: `Prep: spread the cottage cheese-mustard mix on the wrap, top with chicken and vegetables, roll tightly. Cut in half.` },
    { type: 'h2', text: 'Express tofu/chicken & veggie stir-fry' },
    { type: 'meta', items: [
      { label: 'Calories', value: '≈ 480 kcal' },
      { label: 'Protein', value: '40 g' },
    ] },
    { type: 'list', items: [`150 g firm tofu or chicken`, `200 g frozen vegetables`, `100 g cooked rice`, `Soy sauce, garlic, ginger`] },
    { type: 'p', text: `Prep: sear the tofu/chicken on high heat, add the vegetables, deglaze with soy sauce, garlic, and ginger. Serve over rice.` },
    { type: 'h2', text: 'Evening veggie omelette' },
    { type: 'meta', items: [
      { label: 'Calories', value: '≈ 320 kcal' },
      { label: 'Protein', value: '28 g' },
    ] },
    { type: 'list', items: [`3 eggs`, `1 handful of spinach`, `1/2 bell pepper`, `Herbs, salt, pepper`] },
    { type: 'p', text: `Prep: sauté the vegetables for 3 min, pour in the beaten eggs, cook on low heat. Serve with a green salad.` },

    // ── RECOVERY ───────────────────────────────────────────
    { type: 'photo', src: 'recovery.jpg', caption: 'The body transforms during rest.' },
    { type: 'h1', text: 'Recovery' },
    { type: 'list', items: [
      `Sleep 7 to 8 h: lack of sleep raises hunger (ghrelin) and slows fat loss.`,
      `Mild soreness is normal; joint pain isn't - adapt or rest.`,
      `Keep at least 1 true rest day per week (gentle walking allowed).`,
      `Stretch 5 to 10 min after every session to limit stiffness.`,
    ] },
    { type: 'h2', text: 'Sleeping better' },
    { type: 'list', items: [
      `Go to bed at a regular time, even on weekends.`,
      `Cut screens 30 min before sleep; dim the lights.`,
      `No coffee after 4 p.m.; keep the room cool and dark.`,
    ] },
    { type: 'h2', text: 'Managing cravings' },
    { type: 'list', items: [
      `Drink a large glass of water: thirst and hunger are often confused.`,
      `Keep protein snacks on hand (skyr, hard-boiled egg, turkey breast).`,
      `A craving lasts ~15 min: distract yourself, it passes.`,
    ] },

    // ── SCHEDULE ───────────────────────────────────────────
    { type: 'photo', src: 'training.jpg', caption: 'A clear plan, week after week.' },
    { type: 'h1', text: 'Your 4-week schedule' },
    { type: 'p', text: `Intensity ramps up gradually each week. Don't skip a stage: progression is exactly what makes the program effective and safe.` },
    { type: 'table', headers: ['Week', 'Focus', 'Sessions', 'Cardio'], rows: [
      ['Week 1', 'Adaptation & technique', '5 × 25 min', '2 brisk walks'],
      ['Week 2', 'Volume - full body', '5 × 30 min', '2 light HIIT'],
      ['Week 3', 'Intensity - circuits', '5 × 35 min', '3 HIIT'],
      ['Week 4', 'Peak & finish', '5 × 35 min', '3 HIIT + 1 long outing'],
    ] },
    { type: 'h2', text: 'Typical week (overview)' },
    { type: 'table', headers: ['Day', 'Session', 'Duration', 'Intensity'], rows: [
      ['Monday', 'Session A - Lower body', '30 min', 'Moderate'],
      ['Tuesday', 'Fat-burning HIIT', '20 min', 'High'],
      ['Wednesday', 'Session B - Upper body', '30 min', 'Moderate'],
      ['Thursday', 'Brisk walk / active rest', '30 min', 'Low'],
      ['Friday', 'Full-body circuit', '35 min', 'High'],
      ['Saturday', 'Cardio + core', '25 min', 'Moderate'],
      ['Sunday', 'Rest + tracking', '-', 'Recovery'],
    ] },

    // ── 30-DAY CALENDAR ────────────────────────────────
    { type: 'h1', text: 'Your 30-day calendar' },
    { type: 'p', text: `Every day tells you exactly what to do. Tick it off as you go. "Active rest" days aren't optional: walking is part of the program.` },
    { type: 'h2', text: 'Week 1 - Adaptation' },
    { type: 'table', headers: ['Day', 'On the program', 'Duration'], rows: [
      ['D1', 'Session A - Lower body', '25 min'],
      ['D2', 'Light HIIT + core', '20 min'],
      ['D3', 'Session B - Upper body', '25 min'],
      ['D4', 'Brisk walk', '30 min'],
      ['D5', 'Full-body circuit', '25 min'],
      ['D6', 'Cardio + core', '25 min'],
      ['D7', 'Rest + weekly tracking', '-'],
    ] },
    { type: 'h2', text: 'Week 2 - Volume' },
    { type: 'table', headers: ['Day', 'On the program', 'Duration'], rows: [
      ['D8', 'Session A - Lower body', '30 min'],
      ['D9', 'HIIT 15 min + walk', '30 min'],
      ['D10', 'Session B - Upper body', '30 min'],
      ['D11', 'Brisk walk', '35 min'],
      ['D12', 'Full-body circuit', '30 min'],
      ['D13', 'Cardio + core', '25 min'],
      ['D14', 'Rest + weekly tracking', '-'],
    ] },
    { type: 'h2', text: 'Week 3 - Intensity' },
    { type: 'table', headers: ['Day', 'On the program', 'Duration'], rows: [
      ['D15', 'Session A (rest −10 s)', '35 min'],
      ['D16', 'HIIT 20 min', '20 min'],
      ['D17', 'Session B (rest −10 s)', '35 min'],
      ['D18', 'Brisk walk', '40 min'],
      ['D19', 'Intense full-body circuit', '35 min'],
      ['D20', 'HIIT + core', '25 min'],
      ['D21', 'Rest + weekly tracking', '-'],
    ] },
    { type: 'h2', text: 'Week 4 - Peak & finish' },
    { type: 'table', headers: ['Day', 'On the program', 'Duration'], rows: [
      ['D22', 'Session A - clean max effort', '35 min'],
      ['D23', 'HIIT 20 min', '20 min'],
      ['D24', 'Session B - clean max effort', '35 min'],
      ['D25', 'Long outing (walk/bike)', '50 min'],
      ['D26', 'Full-body circuit', '35 min'],
      ['D27', 'HIIT + core', '25 min'],
      ['D28', 'Rest + weekly tracking', '-'],
    ] },
    { type: 'note', text: `Days 29 & 30: redo your favorite session, retake your measurements and an "after" photo. Compare to your "before": that's your real reward.` },

    // ── DETAILED SESSIONS ─────────────────────────────────
    { type: 'h1', text: 'Your sessions in detail' },
    { type: 'h2', text: 'Session A - Lower body' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Bodyweight squat', '4', '15', '45 s'],
      ['Alternating lunges', '3', '12 / leg', '45 s'],
      ['Glute bridge', '3', '20', '40 s'],
      ['Wall sit', '3', '30 s', '40 s'],
      ['Standing calf raises', '3', '20', '30 s'],
    ] },
    { type: 'h2', text: 'Session B - Upper body & core' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Push-ups (knees or feet)', '4', '8 to 12', '45 s'],
      ['Dumbbell / bottle rows', '4', '12', '45 s'],
      ['Chair dips', '3', '10', '40 s'],
      ['Plank', '3', '30 to 45 s', '40 s'],
      ['Side plank', '3', '20 s / side', '30 s'],
    ] },
    { type: 'h2', text: 'Fat-burning HIIT circuit (20 min)' },
    { type: 'table', headers: ['Block', 'Effort', 'Rest', 'Rounds'], rows: [
      ['Mountain climbers', '30 s', '20 s', '4'],
      ['Jump squats (or squats)', '30 s', '20 s', '4'],
      ['Jumping jacks', '30 s', '20 s', '4'],
      ['Dynamic plank', '30 s', '20 s', '4'],
    ] },

    // ── EXERCISE LIBRARY ───────────────────────────
    { type: 'h1', text: 'Exercise library' },
    { type: 'p', text: `Master these movements: they make up the core of your sessions. Good technique first, load and speed later. Scan the QR on each card to see the demo video on XENOTIF®.` },
    { type: 'exercise', name: 'Bodyweight squat', muscles: 'Quads, glutes, hamstrings', level: 'Beginner', video: `${D}/musculation`, technique: `Feet shoulder-width apart, lower by pushing your hips back as if sitting down, back straight, heels on the ground. Lower until your thighs are parallel to the floor, then push through your heels to stand.`, mistakes: `Knees caving inward, heels lifting, rounded back. Keep your chest open and eyes forward.` },
    { type: 'exercise', name: 'Alternating lunges', muscles: 'Glutes, quads, balance', level: 'Beginner', video: `${D}/musculation`, technique: `Take a big step forward, lower the back knee toward the floor while keeping your torso upright. The front knee stays above the ankle. Push through the front heel to return, then switch legs.`, mistakes: `Step too short (knee past the toes), torso leaning forward, losing balance. Brace your core to stay stable.` },
    { type: 'exercise', name: 'Glute bridge', muscles: 'Glutes, hamstrings, core', level: 'Beginner', video: `${D}/musculation`, technique: `Lying on your back, knees bent, feet flat. Push through your heels to lift your hips until you form a straight line from shoulders to knees. Squeeze the glutes for 1 second at the top, then lower without fully resting.`, mistakes: `Arching the lower back instead of squeezing the glutes, lifting too high, feet too far from the hips.` },
    { type: 'exercise', name: 'Wall sit', muscles: 'Quads, core', level: 'Beginner', video: `${D}/musculation`, technique: `Back flat against the wall, slide down until your thighs are parallel to the floor, knees at 90°. Hold the position, breathe calmly, core engaged.`, mistakes: `Knees past the ankles, back lifting off the wall, holding your breath. Keep the weight in your heels.` },
    { type: 'exercise', name: 'Push-ups (knees or feet)', muscles: 'Chest, triceps, shoulders, core', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Hands slightly wider than shoulders, body braced in a straight line. Lower your chest toward the floor, elbows at ~45°, then push back up. Use the knees version if needed to keep clean form.`, mistakes: `Hips sagging or piking up, elbows flaring out, range too short.` },
    { type: 'exercise', name: 'Dumbbell rows (or bottles)', muscles: 'Back, biceps, rear delts', level: 'Beginner', video: `${D}/musculation`, technique: `Torso leaning forward (flat back), arms extended toward the floor. Pull the elbows back, squeezing the shoulder blades together, then lower slowly. Keep the back braced.`, mistakes: `Rounded back, swinging the torso, pulling with the arms instead of the back.` },
    { type: 'exercise', name: 'Chair dips', muscles: 'Triceps, shoulders, chest', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `Hands on the edge of a stable chair, legs in front. Lower your hips by bending the elbows back, then push back up. The straighter the legs, the harder it gets.`, mistakes: `Shoulders shrugging up toward the ears, descent too short, unstable chair.` },
    { type: 'exercise', name: 'Plank', muscles: 'Core, lower back', level: 'Beginner', video: `${D}/musculation`, technique: `Resting on your forearms and the balls of your feet, body in a straight line. Brace your abs and glutes, breathe calmly, hold the position.`, mistakes: `Hips sagging, glutes too high, head lifted. Imagine a rigid plank of wood.` },
    { type: 'exercise', name: 'Side plank', muscles: 'Obliques, core', level: 'Beginner - Intermediate', video: `${D}/musculation`, technique: `On your side, resting on one forearm, body aligned. Lift your hips and hold, without letting them drop. Switch sides.`, mistakes: `Hips dropping, shoulder not aligned with the elbow, body tipping forward.` },
    { type: 'exercise', name: 'Mountain climbers', muscles: 'Abs, shoulders, cardio', level: 'Intermediate', video: `${D}/hiit`, technique: `In a high plank, alternately drive one knee toward your chest, faster and faster. Keep the hips low and the core braced.`, mistakes: `Hips rising too high, sagging back, messy rhythm.` },
    { type: 'exercise', name: 'Jumping jacks', muscles: 'Cardio, shoulders, legs', level: 'Beginner', video: `${D}/hiit`, technique: `Standing, jump while spreading your legs and arms at the same time, then return. Soft landing on the balls of the feet, steady rhythm.`, mistakes: `Landing with stiff knees, arched back, incomplete arm range. Cushion the landing and keep the cadence.` },
    { type: 'exercise', name: 'Burpee (advanced option)', muscles: 'Whole body, cardio', level: 'Advanced', video: `${D}/hiit`, technique: `From standing, hands on the floor, jump your feet back into a plank, do a push-up (optional), bring the feet back in and jump up with arms extended. Chain it smoothly.`, mistakes: `Rounded back on the way down, landing with stiff legs. Cushion the landing, favor a steady rhythm over fast and sloppy.` },

    // ── CARDIO ─────────────────────────────────────────────
    { type: 'photo', src: 'cardio.jpg', caption: 'Cardio speeds up expenditure - and your mindset.' },
    { type: 'h1', text: 'Cardio & HIIT' },
    { type: 'p', text: `HIIT alternates intense efforts with short recoveries: you burn calories during AND after the session (EPOC effect). Brisk walking, meanwhile, boosts your daily expenditure without causing fatigue - it's your secret weapon on "off" days.` },
    { type: 'list', items: [
      `HIIT: 30 s of effort / 20 s of recovery, 4 rounds per exercise. During the effort, you should be unable to hold a conversation.`,
      `Brisk walk: 30 to 45 min, sustained pace, 2 to 3 times a week.`,
      `Week 4: add a long outing (45-60 min of walking/biking) on the weekend.`,
      `Daily habits: take the stairs, get off one stop early, walk while on the phone.`,
    ] },
    { type: 'h2', text: 'Your effort zones' },
    { type: 'p', text: `To gauge intensity without a heart-rate monitor, use the "talk test": your ability to speak indicates your effort level.` },
    { type: 'table', headers: ['Zone', 'Feel', 'Talk test', 'Use'], rows: [
      ['Low', 'Very easy', 'You can sing', 'Warm-up, walking'],
      ['Moderate', 'Sustained but manageable', 'Short sentences', 'Strength work, cardio'],
      ['High', 'Hard, breathless', 'A few words', 'HIIT, finishers'],
      ['Max', 'Very hard', 'Cannot speak', '20-30 s spikes'],
    ] },
    { type: 'h2', text: 'Walking: your secret weapon' },
    { type: 'list', items: [
      `Burns calories without fatigue or spiking appetite - ideal in a deficit.`,
      `Aim for 8,000 to 10,000 steps/day. Break it up: 3 × 10 min counts just as much as one block.`,
      `Morning fasted walks, with music or a podcast, are the best time to lock in the habit.`,
    ] },

    // ── PROGRESSION ────────────────────────────────────────
    { type: 'h1', text: 'Recommended progression' },
    { type: 'p', text: `The body adapts fast: if you never increase the difficulty, it stalls. Here's how to progress every week.` },
    { type: 'table', headers: ['Week', 'Reps', 'Rest', 'Cardio'], rows: [
      ['Week 1', 'Baseline (learn the technique)', '60 s', '2 × 30 min walk'],
      ['Week 2', '+1 to 2 reps / set', '50 s', '2 HIIT 15 min'],
      ['Week 3', '+2 reps or harder variation', '40 s', '3 HIIT 20 min'],
      ['Week 4', 'Clean max per set', '30 s', '3 HIIT + long outing'],
    ] },
    { type: 'list', items: [
      `When an exercise becomes easy (RPE < 6), move to the harder variation.`,
      `Log your performances: beating last week is the best motivation.`,
    ] },
    { type: 'h2', text: `Signs you're progressing (beyond the scale)` },
    { type: 'list', items: [
      `Your clothes fit looser, especially at the waist.`,
      `You do more reps or hold the plank longer.`,
      `You recover faster between sets and climb stairs without getting winded.`,
      `You sleep better, have more energy, and a better mood.`,
    ] },
    { type: 'note', text: `Hit a plateau after 3 weeks? Do a lighter "deload" week (volume −30%), then come back stronger. Rest is part of progression.` },

    // ── STRETCHING & MOBILITY ──────────────────────────────
    { type: 'h1', text: 'Stretching & mobility' },
    { type: 'p', text: `5 to 10 minutes of stretching after every session (or on rest days) improves flexibility, reduces soreness, and limits injury. Hold each position 20 to 30 seconds, smoothly, breathing steadily.` },
    { type: 'table', headers: ['Stretch', 'Area', 'Duration'], rows: [
      ['Low lunge (hip flexor)', 'Hips, psoas', '30 s / side'],
      ['Straight-leg hamstring stretch', 'Back of thigh', '30 s / side'],
      ['Standing quad stretch', 'Front of thigh', '30 s / side'],
      ['Figure-4 glute stretch', 'Glutes', '30 s / side'],
      ['Cat-cow', 'Spine, back', '45 s'],
      ['Chest opener at the wall', 'Chest, shoulders', '30 s / side'],
    ] },

    // ── EXPRESS SESSION ─────────────────────────────────
    { type: 'h1', text: 'Plan B: 10-minute express session' },
    { type: 'p', text: `No time? A short session is ALWAYS better than none: it keeps the habit alive (the real key to success). Do this circuit twice, no rest between exercises, 30 seconds off between the two rounds.` },
    { type: 'table', headers: ['Exercise', 'Duration', 'Rest'], rows: [
      ['Squats', '40 s', '20 s'],
      ['Push-ups (knees or feet)', '40 s', '20 s'],
      ['Mountain climbers', '40 s', '20 s'],
      ['Alternating lunges', '40 s', '20 s'],
      ['Plank', '40 s', '20 s'],
    ] },
    { type: 'note', text: `Keep this "plan B" session in mind: on your busiest days, it's the one that saves your consistency.` },

    // ── SUBSTITUTIONS ──────────────────────────────────────
    { type: 'h1', text: 'Adapting every exercise to your level' },
    { type: 'p', text: `Too easy or too hard? Every movement has an easier (regressed) and a harder (progressed) version. Choose the one that lets you keep clean technique across all your reps.` },
    { type: 'table', headers: ['Exercise', 'Easier', 'Harder'], rows: [
      ['Squat', 'Chair squat', 'Jump squat / loaded'],
      ['Push-up', 'On knees / incline', 'Feet elevated / decline'],
      ['Lunge', 'Static, wall-supported', 'Jump lunge'],
      ['Plank', 'On the knees', 'Dynamic plank / 3-point plank'],
      ['Dips', 'Feet close', 'Legs straight / loaded'],
      ['Mountain climber', 'Slower', 'Fast cross-body'],
    ] },
    { type: 'note', text: `Simple rule: if you can't do the planned number of reps with good form, regress. If it's too easy (RPE < 6), progress.` },

    // ── MISTAKES ────────────────────────────────────────────
    { type: 'h1', text: 'Mistakes to avoid' },
    { type: 'list', items: [
      `Wanting to go too fast: too aggressive a deficit causes muscle loss and kills motivation.`,
      `Skipping protein: without it, you lose muscle instead of fat.`,
      `Weighing yourself every day: weigh in once a week, fasted, on the same day.`,
      `Neglecting recovery: the body changes during rest.`,
      `Skipping the warm-up: the surest way to get injured and stop altogether.`,
      `Comparing your week 1 to someone else's transformation. Compare yourself to yesterday's you.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: ['You run into…', 'The solution'], rows: [
      [`The scale isn't moving`, `Look over 2 weeks; if not, cut −100 kcal at dinner`],
      [`You're hungry all the time`, 'More protein + vegetables + water at meals'],
      [`You're low on energy`, 'Carbs around training + 8 h of sleep'],
      ['Heavy soreness', 'Cut volume 2-3 days, stretch, hydrate'],
      [`You missed a session`, `Pick up the next one, don't "make up" for it all`],
    ] },

    // ── MOTIVATION ─────────────────────────────────────────
    { type: 'h1', text: 'Staying motivated' },
    { type: 'list', items: [
      `Set a specific goal and a date (e.g. "-3 kg in 30 days").`,
      `Take a "before" photo and your measurements: the scale can lie, the mirror doesn't.`,
      `Lay out your workout gear the night before: less friction means more sessions kept.`,
      `Find a partner or share your progress: public commitment doubles your consistency.`,
      `Celebrate every completed week. Consistency beats perfection.`,
    ] },
    { type: 'h2', text: 'Build the habit (not just the motivation)' },
    { type: 'p', text: `Motivation is a spark: some days it's there, some days it isn't. What will make you succeed is habit. And a habit is built by cutting friction and anchoring it to a ritual.` },
    { type: 'list', items: [
      `Tie your session to a fixed moment (e.g. right after waking up, or before dinner).`,
      `The 2-minute rule: start with just the warm-up. Once you're moving, you finish.`,
      `Never break the chain twice in a row. One off day happens - two turns into quitting.`,
      `Make it visible: check off your calendar, it's oddly satisfying and effective.`,
    ] },

    // ── FAQ ────────────────────────────────────────────────
    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: "I don't have dumbbells, is that a problem?" },
    { type: 'p', text: `No. The whole program can be done with bodyweight. Water bottles or a weighted backpack work perfectly instead of dumbbells for rows and lunges.` },
    { type: 'h2', text: 'Can I train fasted in the morning?' },
    { type: 'p', text: `Yes, if it feels good to you. Fasted or not, what matters over 30 days is your total calorie deficit and consistency - not the exact timing of the session.` },
    { type: 'h2', text: "The scale isn't moving, what do I do?" },
    { type: 'p', text: `Be patient: weight fluctuates (water, digestion). Look at the trend over 2 weeks and your measurements. If nothing budges after 2 weeks, slightly reduce your evening carbs.` },
    { type: 'h2', text: 'How much weight will I lose?' },
    { type: 'p', text: `On average 0.5 to 0.8 kg of fat per week, i.e. 2 to 4 kg over 30 days. The further you're starting from, the faster the initial loss (partly water in the first week).` },
    { type: 'h2', text: 'Can I do this program at the gym?' },
    { type: 'p', text: `Absolutely. Swap the bodyweight exercises for their machine versions (leg press, cable row, leg curl) if you prefer, keeping the same number of sets/reps.` },
    { type: 'h2', text: 'Something hurts, should I keep going?' },
    { type: 'p', text: `Muscle soreness: yes, while adapting. Joint or sharp pain: no, rest the area and see a doctor if it persists. Never push through real pain.` },
    { type: 'h2', text: "Won't the 'treat meal' ruin everything?" },
    { type: 'p', text: `No, quite the opposite. One treat meal out of 21 meals a week still leaves a weekly deficit. It preserves your motivation and social life - the real factors behind quitting.` },
    { type: 'h2', text: 'And after the 30 days?' },
    { type: 'p', text: `Either redo a cycle (with more intensity), or move on to a PRO program (Muscle Gain, Strength Training, 90-Day Transformation) to keep progressing.` },

    // ── TRACKING ──────────────────────────────────────────
    { type: 'h1', text: 'Tracking your progress' },
    { type: 'p', text: `Fill in these tables every week. Measure yourself fasted, in the morning, under the same conditions. This is your dashboard: what gets measured gets managed.` },
    { type: 'h2', text: 'Weight & energy' },
    { type: 'tracker', columns: ['Date', 'Weight (kg)', 'Waist (cm)', 'Energy /10'], rows: 8 },
    { type: 'h2', text: 'Measurements (cm)' },
    { type: 'tracker', columns: ['Date', 'Waist', 'Hips', 'Thigh', 'Arm'], rows: 5 },
    { type: 'h2', text: 'Performance (reps or time)' },
    { type: 'tracker', columns: ['Exercise', 'Wk 1', 'Wk 2', 'Wk 3', 'Wk 4'], rows: 6 },

    // ── CHECKLIST ──────────────────────────────────────────
    { type: 'h1', text: 'Weekly checklist' },
    { type: 'p', text: `Tick each box at the end of the week. Goal: at least 6 out of 8.` },
    { type: 'checklist', items: [
      `I did my 5 sessions this week.`,
      `I ate protein at every meal.`,
      `I hit 8,000+ steps most days.`,
      `I drank 2 L of water per day.`,
      `I slept 7 to 8 h most nights.`,
      `I limited liquid sugar and alcohol.`,
      `I weighed myself once, under the same conditions.`,
      `I logged my performances and how I felt.`,
    ] },
    { type: 'h2', text: 'End-of-program review (day 30)' },
    { type: 'checklist', items: [
      `I retook my weight and measurements.`,
      `I took my "after" photo and compared it to the "before".`,
      `I beat at least one rep record vs. week 1.`,
      `I identified 2 habits to keep going forward.`,
      `I chose my next program to keep the momentum.`,
    ] },

    // ── AFTER THE PROGRAM ─────────────────────────────────
    { type: 'h1', text: 'And after your 30 days?' },
    { type: 'p', text: `The classic trap is the yo-yo effect: slipping back into old habits and regaining the fat you lost. To lock in your results, the transition matters as much as the program itself.` },
    { type: 'h2', text: 'Maintaining your results' },
    { type: 'list', items: [
      `Bring your calories back up toward maintenance gradually (+100 kcal/week), rather than letting go all at once.`,
      `Keep the 2-3 habits that helped you most (protein, walking, sleep).`,
      `Keep training 3 to 5 times a week: maintained muscle keeps your metabolism up.`,
      `Weigh yourself once a week: if you regain 1-2 kg, react right away, not in 6 months.`,
    ] },
    { type: 'h2', text: 'Your next goal' },
    { type: 'list', items: [
      `Still fat to lose? Redo a 30-day cycle, with more intensity.`,
      `Want to tone up and get more defined? Move to the Strength Training or Home Fitness program.`,
      `Ready for a real challenge? Start the 90-Day Physical Transformation.`,
    ] },

    // ── NOTES ──────────────────────────────────────────────
    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My notes, feelings, and wins for the week'], rows: 18 },

    { type: 'note', text: `Finished your 30 days? Move on to a PRO program (Muscle Gain, 90-Day Transformation, Strength Training) to keep the momentum going. Create your account at xenotif.com and keep it up.` },
  ],
}
