import type { Guide } from '@/lib/boutique/guides'

// Mass Gain Program — 12 weeks (EN mirror of prise-de-masse-12s.ts).
// Same structure; only the text is translated. ≈ 30 pages.
export const priseDeMasse12sEn: Guide = {
  id: 'd1',
  title: 'Mass Gain Program — 12 Weeks',
  subtitle: '4-day split, guided load progression, nutrition plan + macros',
  author: 'XENOTIF Coach — Certified strength & conditioning and nutrition',
  level: 'Beginner - Intermediate',
  duration: '12 weeks · 4 sessions/week · 84 sessions',
  coverImage: 'masse-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Welcome to your mass-gain plan' },
    { type: 'p', text: `12 weeks to transform your physique: more muscle, more strength, a denser silhouette. No "dirty" bulk that just makes you fat — here you build quality muscle through three levers: a slight caloric surplus, progressive overload in training, and careful recovery.` },
    { type: 'p', text: `Keep this guide on your phone: every exercise has a QR code that opens its demo video. Follow the plan, log your loads, eat enough — and the muscle will follow.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Gain 2 to 5 kg of muscle' },
      { label: 'Level', value: 'Beginner to intermediate' },
      { label: 'Duration', value: '12 weeks (3 phases)' },
      { label: 'Frequency', value: '4 sessions per week' },
      { label: 'Equipment', value: 'Gym or dumbbells + barbell' },
      { label: 'Split', value: 'Upper / Lower (4 days)' },
    ] },
    { type: 'h2', text: 'Program goals' },
    { type: 'list', items: [
      `Build 2 to 5 kg of muscle over 12 weeks (depending on your starting point).`,
      `Gain clear strength on the basic compound lifts.`,
      `Improve your posture and add density to your frame.`,
      `Learn a training and nutrition method you'll keep for life.`,
    ] },
    { type: 'h2', text: 'How to use this guide' },
    { type: 'list', items: [
      `Read the whole guide before starting, then follow the 12-week calendar.`,
      `Log your loads every session: progress is steered, not improvised.`,
      `Warm up 5-10 min before each session (dedicated page).`,
      `Scan an exercise's QR code to review the technique on video.`,
      `Weigh yourself once a week and fill in your tracker on Sunday.`,
    ] },
    { type: 'note', text: `Golden rule: no muscle without a caloric surplus AND progressive overload. Eating more without training hard = fat. Training hard without eating enough = no progress. Both together = muscle.` },

    { type: 'h1', text: 'How it works' },
    { type: 'list', items: [
      `Moderate caloric surplus: eat 200 to 400 kcal above your maintenance.`,
      `Progressive overload: add load or reps almost every week.`,
      `Sets × reps: "4 × 8" = 4 sets of 8 reps.`,
      `Tempo: 2 s on the way down (eccentric), 1 s on the way up.`,
      `Rest: 90 to 120 s on the big lifts, 60 s on isolation.`,
      `RPE 8: keep ~2 reps in reserve, unless stated otherwise.`,
    ] },
    { type: 'h2', text: 'Progressive overload, explained' },
    { type: 'p', text: `A muscle grows when you ask of it more than it's used to. In practice: each week, aim for +1 to 2 reps per set, or +2.5 kg once you hit the top of the rep range. Keep a log: it's the only way to beat last week's numbers.` },

    { type: 'h1', text: 'Warm-up & mobility' },
    { type: 'p', text: `A good warm-up boosts performance and protects your joints under load. Never skip it, especially before heavy lifts.` },
    { type: 'h2', text: 'Typical warm-up (8 minutes)' },
    { type: 'table', headers: ['Step', 'Detail', 'Duration'], rows: [
      ['Light cardio', 'Bike / rope / brisk walk', '3 min'],
      ['Mobility', 'Shoulders, hips, ankles', '2 min'],
      ['Activation', 'Core + band (back/shoulders)', '2 min'],
      ['Ramp-up sets', '2 light sets of the first exercise', '1 min'],
    ] },

    { type: 'chapter', title: 'Mass-gain nutrition plan', src: 'seche-1.jpg' },
    { type: 'p', text: `Muscle is built with a moderate caloric surplus and plenty of protein. The goal: gain muscle while limiting fat. Better +0.25 kg/week clean than +1 kg dirty.` },
    { type: 'meta', items: [
      { label: 'Target surplus', value: '200 to 400 kcal / day' },
      { label: 'Protein', value: '1.8 to 2.2 g per kg' },
      { label: 'Carbs', value: 'High (energy & muscle volume)' },
      { label: 'Weight gain', value: '0.2 to 0.4 kg / week' },
    ] },
    { type: 'h2', text: 'The 5 golden rules' },
    { type: 'list', items: [
      `Protein at every meal (1.8-2.2 g/kg/day): it's the building block of muscle.`,
      `Generous carbs around training (rice, pasta, sweet potato, oats).`,
      `3 to 5 meals a day to hit your calories without stuffing yourself at once.`,
      `Favor calorie-dense foods if you struggle to eat enough (nuts, peanut butter, oats, olive oil).`,
      `Watch the mirror and the scale: if fat climbs too fast, cut the surplus.`,
    ] },
    { type: 'h2', text: 'How much to eat?' },
    { type: 'p', text: `Quick maintenance estimate: bodyweight (kg) × about 33 (if you're active). Example for 70 kg: ≈ 2,300 kcal. Then aim for 2,500 to 2,700 kcal/day. Adjust after 2 weeks: no weight gain → +150 kcal; gaining too fast (> 0.5 kg/week) → −150 kcal.` },
    { type: 'h2', text: 'Sample day (≈ 2,600 kcal)' },
    { type: 'table', headers: ['Meal', 'Example', 'Protein'], rows: [
      ['Breakfast', 'Oats + milk + banana + peanut butter + whey', '45 g'],
      ['Lunch', 'Lean beef + rice + vegetables + olive oil', '45 g'],
      ['Snack', 'Skyr + fruit + almonds', '25 g'],
      ['Post-workout', 'Chicken + pasta + tomato sauce', '45 g'],
      ['Total', '≈ 2,600 kcal · moderate surplus', '≈ 160 g'],
    ] },
    { type: 'h2', text: 'Shopping list' },
    { type: 'list', items: [
      `Protein: lean beef, chicken, turkey, eggs, fish, skyr, whey.`,
      `Carbs: rice, wholegrain pasta, sweet potato, oats, wholegrain bread.`,
      `Fats: olive oil, avocado, almonds, peanut butter.`,
      `Vegetables & fruit: broccoli, spinach, bell pepper, banana, berries.`,
    ] },
    { type: 'note', text: `Can't eat enough? Drink your calories: a shake with oats + milk + banana + whey + peanut butter = an easy 600-700 kcal between meals.` },
    { type: 'h2', text: 'Understanding your macros' },
    { type: 'p', text: `You don't need to weigh everything, but understanding the role of each macronutrient helps you build better mass-gain plates.` },
    { type: 'table', headers: ['Macro', 'Role', 'Per g', 'Priority for mass'], rows: [
      ['Protein', 'Builds muscle', '4 kcal', 'HIGH — 1.8-2.2 g/kg'],
      ['Carbs', 'Energy & muscle volume', '4 kcal', 'HIGH — around sessions'],
      ['Fats', 'Hormones (testosterone)', '9 kcal', 'Moderate — 0.8-1 g/kg'],
    ] },
    { type: 'list', items: [
      `Protein: the building block. Without it, no construction, whatever else you do.`,
      `Carbs: your training fuel and the muscle's "volume" (glycogen).`,
      `Fats: never go too low — they support your anabolic hormones.`,
    ] },

    { type: 'h1', text: 'Mass-gain recipes' },
    { type: 'h2', text: 'Homemade mass-gain shake' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 650 kcal' }, { label: 'Protein', value: '45 g' }] },
    { type: 'list', items: [`300 ml milk`, `60 g oats`, `1 banana`, `1 scoop whey`, `1 tbsp peanut butter`] },
    { type: 'p', text: `Method: blend everything for 30 seconds. Ideal at breakfast or after training.` },
    { type: 'h2', text: 'Post-workout beef & rice bowl' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 700 kcal' }, { label: 'Protein', value: '50 g' }] },
    { type: 'list', items: [`150 g lean (5%) ground beef`, `120 g rice (dry weight)`, `Vegetables of choice`, `Soy sauce, spices`] },
    { type: 'p', text: `Method: sear the beef, add the vegetables, serve over rice. Rich, simple, perfect after a session.` },
    { type: 'h2', text: 'Morning protein porridge' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 550 kcal' }, { label: 'Protein', value: '38 g' }] },
    { type: 'list', items: [`80 g oats`, `300 ml milk`, `1 scoop vanilla whey`, `1 tbsp honey + berries`] },
    { type: 'p', text: `Method: heat the oats in the milk for 3 min, take off the heat and stir in the whey, honey and fruit. A champion's breakfast.` },
    { type: 'h2', text: 'Hearty omelette + sweet potato' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 600 kcal' }, { label: 'Protein', value: '42 g' }] },
    { type: 'list', items: [`4 eggs + 2 whites`, `200 g sweet potato`, `Spinach, cheese`, `Olive oil`] },
    { type: 'p', text: `Method: cook the sweet potato in the oven/microwave, make the omelette with spinach and cheese. A complete, filling meal.` },

    { type: 'chapter', title: 'Recovery', src: 'recovery.jpg' },
    { type: 'list', items: [
      `Sleep 7 to 9 h: muscle protein synthesis peaks during sleep.`,
      `Leave 48 h before training a muscle again (hence the Upper/Lower split).`,
      `Hydrate (3 L/day): muscle is ~75% water.`,
      `A "deload" week (loads −40%) every 6 weeks prevents plateaus.`,
    ] },

    { type: 'chapter', title: '12-week plan (3 phases)', src: 'masse-1.jpg' },
    { type: 'p', text: `The program progresses in 3 phases. Respect the order: volume first, intensity later.` },
    { type: 'table', headers: ['Phase', 'Weeks', 'Focus', 'Reps'], rows: [
      ['Phase 1', 'W1 to W4', 'Adaptation & volume', '12 to 15'],
      ['Phase 2', 'W5 to W8', 'Hypertrophy', '8 to 12'],
      ['Phase 3', 'W9 to W12', 'Strength & density', '6 to 8'],
    ] },
    { type: 'h2', text: 'Sample week (Upper / Lower split)' },
    { type: 'table', headers: ['Day', 'Session', 'Focus'], rows: [
      ['Monday', 'Upper body A', 'Chest, back, shoulders, arms'],
      ['Tuesday', 'Lower body A', 'Quads, glutes, calves'],
      ['Wednesday', 'Rest / light cardio', 'Recovery'],
      ['Thursday', 'Upper body B', 'Back, chest, arms'],
      ['Friday', 'Lower body B', 'Hamstrings, glutes, core'],
      ['Weekend', 'Rest + tracking', 'Recovery'],
    ] },

    { type: 'h1', text: 'Your sessions in detail' },
    { type: 'h2', text: 'Upper body A' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Bench press (or weighted push-ups)', '4', '8 to 10', '120 s'],
      ['Horizontal row', '4', '10', '90 s'],
      ['Overhead press', '3', '10', '90 s'],
      ['Lat pulldown', '3', '12', '75 s'],
      ['Biceps curl', '3', '12', '60 s'],
      ['Triceps extension', '3', '12', '60 s'],
    ] },
    { type: 'h2', text: 'Lower body A' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Squat', '4', '8 to 10', '120 s'],
      ['Leg press (or lunges)', '4', '12', '90 s'],
      ['Romanian deadlift', '3', '10', '90 s'],
      ['Leg curl (or weighted glute bridge)', '3', '12', '75 s'],
      ['Standing calf raise', '4', '15', '45 s'],
    ] },
    { type: 'h2', text: 'Upper body B' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Pull-ups (or lat pulldown)', '4', '8 to 10', '120 s'],
      ['Incline dumbbell press', '4', '10', '90 s'],
      ['One-arm dumbbell row', '3', '12', '75 s'],
      ['Lateral raises', '3', '15', '60 s'],
      ['Hammer curl', '3', '12', '60 s'],
      ['Dips (or triceps extension)', '3', '10', '60 s'],
    ] },
    { type: 'h2', text: 'Lower body B' },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Deadlift (or hip thrust)', '4', '6 to 8', '120 s'],
      ['Walking dumbbell lunges', '3', '12 / leg', '90 s'],
      ['Leg extension (or Bulgarian split squat)', '3', '15', '75 s'],
      ['Weighted glute bridge', '3', '12', '75 s'],
      ['Plank + side plank', '3', '40 s', '45 s'],
    ] },

    { type: 'h1', text: '12-week calendar' },
    { type: 'p', text: `Three progressive phases. Keep the same Upper/Lower split each week, but evolve reps and loads according to the phase.` },
    { type: 'h2', text: 'Phase 1 — Adaptation & volume (W1 to W4)' },
    { type: 'table', headers: ['Week', 'Reps', 'Intensity', 'Note'], rows: [
      ['W1', '12 to 15', 'RPE 7', 'Technique first'],
      ['W2', '12 to 15', 'RPE 7-8', '+1 rep / set'],
      ['W3', '12 to 15', 'RPE 8', '+ light load'],
      ['W4', '12 to 15', 'RPE 8', 'Beat your W1 numbers'],
    ] },
    { type: 'h2', text: 'Phase 2 — Hypertrophy (W5 to W8)' },
    { type: 'table', headers: ['Week', 'Reps', 'Intensity', 'Note'], rows: [
      ['W5', '8 to 12', 'RPE 8', 'Increase the loads'],
      ['W6', '8 to 12', 'RPE 8', 'Light deload end of week'],
      ['W7', '8 to 12', 'RPE 8-9', '+ load'],
      ['W8', '8 to 12', 'RPE 9', 'Sets close to failure'],
    ] },
    { type: 'h2', text: 'Phase 3 — Strength & density (W9 to W12)' },
    { type: 'table', headers: ['Week', 'Reps', 'Intensity', 'Note'], rows: [
      ['W9', '6 to 8', 'RPE 8', 'Heavy loads, long rests'],
      ['W10', '6 to 8', 'RPE 8-9', '+ load'],
      ['W11', '6 to 8', 'RPE 9', 'Intensity peak'],
      ['W12', '6 to 8 then deload', 'Variable', 'Review + photos + measurements'],
    ] },

    { type: 'h1', text: 'Variation: 3-day full body' },
    { type: 'p', text: `Can't train 4 times a week? Replace the Upper/Lower split with this 3-day full-body scheme (Mon / Wed / Fri). Each session works the whole body: very effective for beginners and busy schedules.` },
    { type: 'table', headers: ['Exercise', 'Sets', 'Reps', 'Rest'], rows: [
      ['Squat', '4', '8 to 10', '120 s'],
      ['Bench press (or push-ups)', '4', '8 to 10', '120 s'],
      ['Row / pulldown', '4', '10', '90 s'],
      ['Overhead press', '3', '10', '90 s'],
      ['Romanian deadlift', '3', '10', '90 s'],
      ['Core + curl/extension', '3', '12', '60 s'],
    ] },
    { type: 'note', text: `On full body, slightly rotate the exercises across the 3 sessions (e.g. squat Monday, lunges Wednesday, leg press Friday) to vary the stimulus.` },

    { type: 'h1', text: 'Exercise library' },
    { type: 'p', text: `Master these basic movements: they build most of your mass. Scan the QR for the demo video.` },
    { type: 'exercise', name: 'Squat', muscles: 'Quads, glutes, hamstrings, core', level: 'Intermediate', technique: `Bar on the upper back, feet shoulder-width. Descend by pushing the hips back, core braced, until thighs are parallel, then drive back up through the heels.`, mistakes: `Knees caving in, heels lifting, back rounding. Keep your chest proud and the weight in your heels.` },
    { type: 'exercise', name: 'Bench press', muscles: 'Chest, triceps, shoulders', level: 'Intermediate', technique: `Lying on the bench, shoulder blades retracted, slight arch. Lower the bar to the lower chest, elbows at ~45°, then press while keeping your feet anchored.`, mistakes: `Elbows too flared, bouncing off the chest, glutes lifting. Control the descent.` },
    { type: 'exercise', name: 'Romanian deadlift', muscles: 'Hamstrings, glutes, back', level: 'Intermediate', technique: `Bar in front of the thighs, flat back. Lower the bar along the legs by pushing the hips back, slight knee bend, until you feel the hamstring stretch, then return by squeezing the glutes.`, mistakes: `Rounded back, bar drifting away from the body, excessive knee bend (it becomes a squat).` },
    { type: 'exercise', name: 'Barbell row', muscles: 'Back, biceps, rear delts', level: 'Intermediate', technique: `Torso bent ~45°, flat back. Pull the bar to the lower abdomen by squeezing the shoulder blades, then lower slowly. The movement comes from the back, not the arms.`, mistakes: `Rounded back, torso rising every rep, pulling too high toward the chest.` },
    { type: 'exercise', name: 'Overhead press', muscles: 'Shoulders, triceps, core', level: 'Intermediate', technique: `Standing, bar at collarbone level, core braced. Press the bar overhead without arching the lower back, then lower under control.`, mistakes: `Excessive lumbar arch, pressing forward instead of vertical, incomplete lockout.` },
    { type: 'exercise', name: 'Lat pulldown', muscles: 'Lats, biceps', level: 'Beginner', technique: `Seated, wide grip. Pull the bar to the upper chest by depressing the shoulders and squeezing the back, then return under control keeping tension.`, mistakes: `Swinging back, pulling behind the neck, letting go at the top.` },
    { type: 'exercise', name: 'Dumbbell lunges', muscles: 'Quads, glutes, balance', level: 'Beginner', technique: `Dumbbells in hand, big step forward, rear knee toward the floor, torso upright. Push through the front heel to return. Alternate legs.`, mistakes: `Step too short, torso leaning, knee caving inward.` },
    { type: 'exercise', name: 'Biceps curl', muscles: 'Biceps', level: 'Beginner', technique: `Elbows pinned to the body, raise the dumbbells by contracting the biceps, then lower slowly (2 s). No swinging.`, mistakes: `Swinging the body, elbows drifting forward, lowering too fast.` },
    { type: 'exercise', name: 'Triceps extension', muscles: 'Triceps', level: 'Beginner', technique: `On a cable or with a dumbbell, elbows fixed, extend the forearm fully then return under control. Only the forearm moves.`, mistakes: `Elbows flaring out, partial range, torso swinging.` },
    { type: 'exercise', name: 'Plank', muscles: 'Core, lower back', level: 'Beginner', technique: `Forearms and toes on the floor, body aligned, abs and glutes braced. Hold the position while breathing calmly.`, mistakes: `Hips sagging, glutes too high, head lifted.` },

    { type: 'h1', text: 'Recommended progression' },
    { type: 'p', text: `Progressive overload is the engine of mass gain. Here's how to advance without injury.` },
    { type: 'table', headers: ['Phase', 'Goal', 'How to progress'], rows: [
      ['W1-W4', 'Learn & absorb volume', '+1-2 reps/week'],
      ['W5-W8', 'Maximize hypertrophy', '+2.5 kg at top of range'],
      ['W9-W12', 'Build strength', 'Heavier loads, lower reps'],
    ] },
    { type: 'list', items: [
      `When you hit the top of the rep range on all sets, add weight.`,
      `Log every session: load × reps. Beat that number next time.`,
      `Deload every 6 weeks: volume −40% for one week, then come back stronger.`,
    ] },

    { type: 'h1', text: 'Mistakes to avoid' },
    { type: 'list', items: [
      `Eating too much ("dirty bulk"): you mostly gain fat you'll have to lose again.`,
      `Switching programs every 2 weeks: muscle needs consistency.`,
      `Neglecting legs: a physique is also (mostly) built from the bottom up.`,
      `Ego-lifting: too heavy, form breaks down → guaranteed injury.`,
      `Skipping protein or sleep: no construction without materials or rest.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: ['You run into…', 'The solution'], rows: [
      ['Not gaining weight', '+150-200 kcal/day, add a shake'],
      ['Gaining too much fat', 'Cut the surplus, keep protein high'],
      ['Strength plateau', 'Deload 1 week, check sleep & calories'],
      ['Joint pain', 'Lighten up, review technique (scan the video)'],
    ] },

    { type: 'h1', text: 'Staying motivated' },
    { type: 'list', items: [
      `Photograph yourself every 4 weeks: muscle shows up better than it feels.`,
      `Set strength goals (e.g. "squat 1× my bodyweight").`,
      `Surround yourself: a training partner boosts intensity and consistency.`,
      `Be patient: 2 to 5 kg of muscle in 12 weeks is an excellent result.`,
    ] },
    { type: 'h2', text: 'Build the habit' },
    { type: 'list', items: [
      `Block your 4 training slots in your calendar like appointments.`,
      `Prep your bag and meals the night before: zero friction on the day.`,
      `Never break the chain two sessions in a row.`,
    ] },

    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: "I'm a beginner, is this program for me?" },
    { type: 'p', text: `Yes. Start light to master the technique (use the bodyweight variations if needed), then add load progressively. Beginners progress very fast in the first months.` },
    { type: 'h2', text: 'Will I gain fat?' },
    { type: 'p', text: `A little — that's normal and necessary to build muscle. With a moderate surplus (200-400 kcal) and plenty of protein, the gain stays mostly muscular.` },
    { type: 'h2', text: 'Can I do it at home?' },
    { type: 'p', text: `Yes, with adjustable dumbbells and a barbell. Otherwise, swap in the bodyweight variations (weighted push-ups, lunges, pull-ups, dips) aiming for clean failure.` },
    { type: 'h2', text: 'Do I need supplements?' },
    { type: 'p', text: `None are mandatory. The most useful: whey (to hit your protein), creatine monohydrate (3-5 g/day, the most studied supplement for strength and volume).` },
    { type: 'h2', text: 'How much cardio?' },
    { type: 'p', text: `A little (2 × 20 min light/week) for health and to keep fat at bay, without excess so you don't burn your building calories.` },
    { type: 'h2', text: 'Should I train to failure?' },
    { type: 'p', text: `Not on every set: keep 1 to 2 reps in reserve on most sets (RPE 8). Save failure for the last set of an isolation exercise. Always going to failure fatigues the nervous system and slows recovery.` },
    { type: 'h2', text: 'What if I miss a session?' },
    { type: 'p', text: `Just pick up at the next scheduled session, don't try to make everything up. Over 12 weeks, one missed session changes nothing — quitting does.` },
    { type: 'h2', text: "I'm a 'hardgainer', I don't gain. What do I do?" },
    { type: 'p', text: `In 95% of cases, you eat less than you think. Increase portions, add a liquid shake between meals, and weigh yourself: if the scale doesn't move over 2 weeks, add 200 kcal.` },

    { type: 'h1', text: 'Sleep, stress & hormones' },
    { type: 'p', text: `Muscle building doesn't happen only at the gym: your hormones (testosterone, growth hormone) and your recovery depend largely on your sleep and stress management.` },
    { type: 'list', items: [
      `Aim for 7 to 9 h of sleep: most muscle recovery happens at night.`,
      `Go to bed at a regular time; cut screens 30 min before.`,
      `Chronic stress raises cortisol, which hampers muscle gain — learn to unwind.`,
      `Avoid excess alcohol: it disrupts sleep and protein synthesis.`,
      `Get morning daylight to set your internal clock.`,
    ] },

    { type: 'h1', text: 'Stretching & mobility' },
    { type: 'p', text: `After each session, spend 5 to 10 minutes stretching to preserve your mobility under load and limit soreness. Hold each position 20 to 30 s.` },
    { type: 'table', headers: ['Stretch', 'Area', 'Duration'], rows: [
      ['Chest stretch at the wall', 'Chest, shoulders', '30 s / side'],
      ['Bar hang', 'Back, shoulders', '30 s'],
      ['Standing quad stretch', 'Front of thigh', '30 s / side'],
      ['Seated hamstring stretch', 'Back of thigh', '30 s / side'],
      ['Pigeon (glutes)', 'Glutes, hips', '30 s / side'],
      ['Floor thoracic rotation', 'Spine', '45 s'],
    ] },

    { type: 'h1', text: 'Adapting each exercise' },
    { type: 'p', text: `No equipment or a movement too hard? Here's an alternative for each basic exercise, without losing effectiveness.` },
    { type: 'table', headers: ['Exercise', 'No equipment / easier', 'Harder'], rows: [
      ['Barbell squat', 'Goblet / bodyweight squat', 'Weighted Bulgarian split squat'],
      ['Bench press', 'Push-ups (feet elevated)', 'Heavy incline press'],
      ['Pull-ups', 'Band-assisted pulldown / row', 'Weighted pull-ups'],
      ['Deadlift', 'Hip thrust / glute bridge', 'Heavy deadlift'],
      ['Overhead press', 'Pike push-ups', 'Heavy standing press'],
    ] },

    { type: 'h1', text: 'Supplements' },
    { type: 'p', text: `None are mandatory — food comes first. But a few supplements have real, science-backed value.` },
    { type: 'table', headers: ['Supplement', 'Benefit', 'Dose'], rows: [
      ['Creatine monohydrate', 'Strength, volume, the most studied', '3 to 5 g / day'],
      ['Whey', 'Hit your protein easily', '1 to 2 scoops / day'],
      ['Vitamin D', 'If little sun exposure', 'Per medical advice'],
      ['Omega-3', 'Recovery, joints', '1 to 2 g / day'],
    ] },
    { type: 'note', text: `Beware sugary "gainers" and miracle products: they cost a lot for little effect. Creatine and whey are enough in 99% of cases.` },

    { type: 'h1', text: 'And after your 12 weeks?' },
    { type: 'p', text: `You've built muscle: now it's about keeping it and continuing to progress. Two options depending on your goal.` },
    { type: 'h2', text: 'Option 1 — Reveal the muscle (cut)' },
    { type: 'list', items: [
      `Move into a slight deficit (−300 to −500 kcal) to melt the fat gained during the bulk.`,
      `Keep protein high and strength training to preserve the muscle.`,
      `Follow up with the Weight Loss program to reveal your definition.`,
    ] },
    { type: 'h2', text: 'Option 2 — Keep building' },
    { type: 'list', items: [
      `Take a deload week, then start a new cycle with heavier loads.`,
      `Change a few exercises to vary the stimulus and avoid routine.`,
      `Chase new strength records as your guiding thread.`,
    ] },
    { type: 'note', text: `Whatever you choose: don't drop everything at once. Muscle is lost fast if you completely stop training and eating enough protein.` },

    { type: 'h1', text: 'Tracking your progress' },
    { type: 'p', text: `Log your loads and weight every week: it's your dashboard. What gets measured gets managed.` },
    { type: 'h2', text: 'Weight & measurements' },
    { type: 'tracker', columns: ['Date', 'Weight (kg)', 'Arm (cm)', 'Thigh (cm)', 'Chest (cm)'], rows: 7 },
    { type: 'h2', text: 'Loads on the basic lifts (kg)' },
    { type: 'tracker', columns: ['Exercise', 'W1', 'W4', 'W8', 'W12'], rows: 6 },

    { type: 'h1', text: 'Weekly checklist' },
    { type: 'p', text: `Tick each box at the end of the week. Goal: at least 6 boxes out of 8.` },
    { type: 'checklist', items: [
      `I did my 4 sessions this week.`,
      `I hit my protein target every day.`,
      `I ate in a slight surplus (weight stable or up).`,
      `I increased a load or reps.`,
      `I slept 7 to 9 h most nights.`,
      `I stayed hydrated (≈ 3 L/day).`,
      `I logged my loads and performances.`,
      `I weighed myself once, under the same conditions.`,
    ] },

    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My notes, loads and sensations for the week'], rows: 18 },

    { type: 'h1', text: 'Glossary' },
    { type: 'p', text: `The terms that come up in this guide, explained simply.` },
    { type: 'list', items: [
      `Hypertrophy: growth in the size of muscle fibers (the "volume").`,
      `Progressive overload: regularly increasing load or reps to force adaptation.`,
      `RPE: perceived intensity out of 10. RPE 8 = you had ~2 reps in reserve.`,
      `Tempo: execution speed (e.g. 2 s down, 1 s up).`,
      `Eccentric: the phase where the muscle lengthens under tension (the descent).`,
      `Deload: a lighter week to recover and come back stronger.`,
      `Maintenance: the number of calories that keeps your weight stable.`,
      `Split: how you distribute muscle groups across the week (here Upper/Lower).`,
    ] },

    { type: 'note', text: `12 weeks done? Take a deload week, retake your measurements and photos, then start a new cycle or a cutting phase (Weight Loss) to reveal the muscle you built. Create your account at xenotif.com.` },
  ],
}
