import type { Guide } from '@/lib/boutique/guides'

// d4 - Running Guide: from 5K to Marathon (EN mirror of running-guide.ts).
// 5K/10K/half/marathon plans, run nutrition, injury prevention, competitor mindset.
export const runningGuideEn: Guide = {
  id: 'd4',
  title: 'Running Guide - From 5K to Marathon',
  subtitle: '5K / 10K / half / marathon plans, run nutrition, injury prevention, mindset',
  author: 'XENOTIF Coach - Certified athletics coach',
  level: 'Beginner → Experienced',
  duration: '4 plans · 5K to marathon',
  coverImage: 'run-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Welcome, runner' },
    { type: 'p', text: `Whether you want to run your first 5 km or conquer a marathon, this guide walks the whole road with you. It brings together 4 complete training plans (5K, 10K, half marathon, marathon), the science of pacing, run nutrition, injury prevention, runner's strength work and the competitor's mindset.` },
    { type: 'p', text: `Read the chapters on pacing and technique first: they're what make the difference to your progress and your injury prevention. Every strength exercise has a QR code to its demo video.` },
    { type: 'meta', items: [
      { label: 'Goal', value: 'Run 5K to marathon' },
      { label: 'Level', value: 'Beginner to experienced' },
      { label: 'Plans', value: '5K · 10K · half · marathon' },
      { label: 'Sessions', value: '3 to 4 per week' },
      { label: 'Equipment', value: 'A good pair of shoes' },
      { label: 'Included', value: 'Plans + nutrition + mindset' },
    ] },
    { type: 'h2', text: 'How to use this guide' },
    { type: 'list', items: [
      `Choose your plan based on your goal (5K, 10K, half or marathon).`,
      `Read the "pacing" and "prevention" chapters before starting.`,
      `Respect rest days: progress happens during recovery.`,
      `Do the strength work 1-2×/week (dedicated chapter, with video QR codes).`,
      `Log your runs and how you felt in the tracker.`,
    ] },
    { type: 'note', text: `The 80/20 rule: 80% of your kilometers in easy aerobic running (slow, you can talk), 20% at intensity. It's the foundation of all lasting progress in running.` },

    { type: 'h1', text: 'The science of pacing' },
    { type: 'p', text: `Running "fast all the time" is the beginner's #1 mistake: it leads to overtraining and injuries. Progress comes from the VARIETY of paces.` },
    { type: 'table', headers: ['Pace', 'Intensity', 'Feel', 'Use'], rows: [
      ['Easy aerobic', 'Low', 'You can hold a conversation', '80% of volume'],
      ['Marathon pace', 'Moderate', 'Comfortably hard', 'Long runs'],
      ['Half/10K pace', 'Sustained', 'Short sentences', 'Tempo / threshold'],
      ['5K pace / VO2', 'High', 'A few words', 'Intervals'],
      ['Sprint', 'Maximal', 'Cannot speak', 'Strides'],
    ] },
    { type: 'list', items: [
      `Easy aerobic (EA): the base. Run slowly, really slowly.`,
      `Intervals (VO2): fast repetitions with recovery (e.g. 8 × 400 m).`,
      `Tempo / threshold: a sustained pace held 15-30 min, to push back your threshold.`,
      `Long run: progressive in duration, at an easy pace, key for the half and the marathon.`,
    ] },

    { type: 'h1', text: 'Calculate your training paces' },
    { type: 'p', text: `To train effectively, each type of session has its own pace. Find your goal time in the table and read the corresponding paces (in min/km). These are your benchmarks for the whole guide.` },
    { type: 'table', headers: ['Goal', 'Easy (EA)', 'Threshold pace', 'VO2/5K pace'], rows: [
      ['5K in 30 min', '7:00 - 7:30', '5:40', '5:20'],
      ['5K in 25 min', '6:15 - 6:45', '4:45', '4:30'],
      ['10K in 55 min', '6:30 - 7:00', '5:10', '4:55'],
      ['10K in 50 min', '6:00 - 6:30', '4:40', '4:25'],
      ['Half in 2 h', '6:30 - 7:00', '5:25', '5:05'],
      ['Half in 1 h 45', '5:45 - 6:15', '4:45', '4:25'],
      ['Marathon in 4 h 30', '7:00 - 7:30', '5:55', '5:30'],
      ['Marathon in 4 h', '6:15 - 6:45', '5:15', '4:55'],
    ] },
    { type: 'note', text: `Don't know your level? Run 5 km all-out once warmed up: your time places you in the table. Redo this test every 4-6 weeks to adjust your paces as you progress.` },

    { type: 'chapter', title: 'The perfect stride', src: 'run-2.jpg', intro: `Good running technique means less fatigue, more speed and far fewer injuries. A few simple principles to integrate gradually.` },
    { type: 'list', items: [
      `Cadence: aim for about 170-180 steps per minute. A high cadence shortens the stride and reduces impact.`,
      `Footstrike: land the foot under your hips, not far in front of you (avoid heel-striking with a straight leg).`,
      `Posture: upright torso, light core engagement, eyes on the horizon, relaxed shoulders.`,
      `Arms: bent at ~90°, moving front to back (no crossing in front of the torso), relaxed hands.`,
      `Breathing: belly-based and regular, synced to your stride (e.g. 3 steps inhale / 2 steps exhale in EA).`,
    ] },
    { type: 'h2', text: 'The cadence test' },
    { type: 'p', text: `Count the footstrikes of a single foot over 30 seconds, then multiply by 4. Less than 80? Work on shortening and quickening your stride, especially with the running drills from the strength chapter.` },

    { type: 'h1', text: 'Warm-up & cool-down' },
    { type: 'p', text: `Never skip the warm-up before a quality session (intervals, threshold, race). The cool-down speeds up recovery.` },
    { type: 'h2', text: 'Typical warm-up (15 min)' },
    { type: 'table', headers: ['Step', 'Duration', 'Content'], rows: [
      ['Easy jog', '10 min', 'Gradual ramp-up of the body'],
      ['Mobility', '2 min', 'Hip circles, ankles, leg swings'],
      ['Drills', '2 min', 'High knees, butt kicks, side shuffles'],
      ['Strides', '1 min', '3 to 4 progressive accelerations'],
    ] },
    { type: 'h2', text: 'Cool-down (10 min)' },
    { type: 'list', items: [
      `5 min of very easy jogging to bring the heart down.`,
      `5 min of gentle stretching of the main muscle groups (see stretching chapter).`,
      `Rehydrate and have a carb + protein snack within the hour.`,
    ] },
    { type: 'h2', text: 'Mobility before running (5 min)' },
    { type: 'p', text: `For easy runs, a shorter warm-up is enough, but a few dynamic movements prepare the joints and reduce injury risk.` },
    { type: 'table', headers: ['Movement', 'Reps', 'Target'], rows: [
      ['Leg swings (front-back)', '10 / leg', 'Hips, hamstrings'],
      ['Lateral swings', '10 / leg', 'Adductors, hips'],
      ['Ankle circles', '10 / direction', 'Ankles'],
      ['Walking lunges', '8 / leg', 'Quads, glutes'],
      ['Butt kicks in place', '20 s', 'Hamstrings, ramp-up'],
    ] },
    { type: 'note', text: `Avoid long static stretches BEFORE running: they temporarily reduce muscular power. Save them for the cool-down. Before the effort, favor movement (dynamic).` },

    { type: 'h1', text: 'Complete beginner: the run-walk program' },
    { type: 'p', text: `Starting from zero or coming back after a long break? Begin here before the 5K plan. The goal: run 30 minutes continuously in 6 weeks, without getting injured.` },
    { type: 'table', headers: ['Week', 'Session (×3/week)', 'Total'], rows: [
      ['W1', '6 × (1 min run / 1.5 min walk)', '~20 min'],
      ['W2', '6 × (2 min run / 1 min walk)', '~22 min'],
      ['W3', '5 × (3 min run / 1 min walk)', '~25 min'],
      ['W4', '4 × (5 min run / 1 min walk)', '~28 min'],
      ['W5', '3 × (8 min run / 1 min walk)', '~30 min'],
      ['W6', '2 × (14 min run / 1 min walk)', '~30 min'],
    ] },
    { type: 'note', text: `Always run slowly (you should be able to talk). If a week is too hard, repeat it: there's no shame in progressing at your own pace. Once you've got 30 continuous min, move on to the 5K plan.` },

    { type: 'chapter', title: '5K plan (8 weeks)', src: 'run-1.jpg', intro: `Ideal to start or to aim for your first 5 km running. 3 runs per week. Alternate running and walking at the beginning if needed.` },
    { type: 'table', headers: ['Week', 'Run 1', 'Run 2', 'Run 3 (long)'], rows: [
      ['W1', '20 min run/walk', 'Rest / walk', '25 min run/walk'],
      ['W2', '25 min EA', 'Rest', '30 min EA'],
      ['W3', '25 min EA', '6 × 1 min fast / 1 min slow', '35 min EA'],
      ['W4', '30 min EA', '8 × 1 min fast / 1 min slow', '35 min EA'],
      ['W5', '30 min EA', '2 × 6 min tempo', '40 min EA'],
      ['W6', '30 min EA', '10 × 1 min fast / 1 min slow', '40 min EA'],
      ['W7', '30 min EA', '3 × 6 min tempo', '35 min EA'],
      ['W8', '20 min EA', '2 × 4 min at 5K pace', '5K RACE'],
    ] },

    { type: 'h1', text: '10K plan (8 weeks)' },
    { type: 'p', text: `For those who already run 5 km and are aiming for 10. 3 to 4 runs per week.` },
    { type: 'table', headers: ['Week', 'Run 1', 'Run 2', 'Run 3 (long)'], rows: [
      ['W1', '35 min EA', '8 × 400 m at 5K pace', '45 min EA'],
      ['W2', '35 min EA', '2 × 8 min tempo', '50 min EA'],
      ['W3', '40 min EA', '10 × 400 m', '55 min EA'],
      ['W4', '40 min EA', '3 × 8 min tempo', '60 min EA'],
      ['W5', '40 min EA', '6 × 800 m at 10K pace', '65 min EA'],
      ['W6', '45 min EA', '2 × 12 min tempo', '70 min EA'],
      ['W7', '40 min EA', '5 × 1000 m at 10K pace', '50 min EA'],
      ['W8', '30 min EA', '2 × 5 min at 10K pace', '10K RACE'],
    ] },
    { type: 'h2', text: 'Nailing your 10K' },
    { type: 'list', items: [
      `EA = easy aerobic (slow). It's 80% of the plan: never run it too fast.`,
      `The "tempo" sessions are run at threshold pace (see pacing chapter), sustained but controlled.`,
      `Place a rest day after each quality session (intervals, tempo).`,
      `Race week (W8), ease off: you should arrive fresh, not tired.`,
      `Aim for a negative split: start cautiously, accelerate on the second half.`,
    ] },

    { type: 'chapter', title: 'Half-marathon plan (10 weeks)', src: 'run-2.jpg', intro: `21.1 km. The long run becomes your key session. 3 to 4 runs per week, including one long run on the weekend.` },
    { type: 'table', headers: ['Week', 'Tempo / threshold', 'Intervals', 'Long run'], rows: [
      ['W1', '2 × 10 min', '8 × 400 m', '1 h 10'],
      ['W2', '2 × 12 min', '6 × 800 m', '1 h 20'],
      ['W3', '3 × 10 min', '10 × 400 m', '1 h 30'],
      ['W4', '20 min threshold', '5 × 1000 m', '1 h 40'],
      ['W5', '2 × 15 min', '6 × 1000 m', '1 h 30 (easy)'],
      ['W6', '25 min threshold', '4 × 1500 m', '1 h 50'],
      ['W7', '2 × 15 min at half pace', '8 × 800 m', '2 h 00'],
      ['W8', '30 min at half pace', '6 × 1000 m', '1 h 45'],
      ['W9', '20 min at half pace', '4 × 800 m', '1 h 10 (taper)'],
      ['W10', '15 min jog', '3 × 3 min', 'HALF MARATHON'],
    ] },

    { type: 'h1', text: 'Marathon plan (12 weeks)' },
    { type: 'p', text: `42.195 km: the most demanding plan. Prerequisite: already running ~1 h comfortably. Consistency and long runs are everything.` },
    { type: 'table', headers: ['Week', 'Quality session', 'Long run'], rows: [
      ['W1', '2 × 12 min threshold', '1 h 30'],
      ['W2', '6 × 1000 m', '1 h 45'],
      ['W3', '3 × 12 min threshold', '2 h 00'],
      ['W4', '8 × 800 m', '1 h 45 (easy)'],
      ['W5', '25 min at marathon pace', '2 h 15'],
      ['W6', '2 × 15 min threshold', '2 h 30'],
      ['W7', '30 min at marathon pace', '2 h 00 (easy)'],
      ['W8', '5 × 2000 m', '2 h 45'],
      ['W9', '40 min at marathon pace', '3 h 00 (the key one)'],
      ['W10', '2 × 20 min threshold', '2 h 15 (taper)'],
      ['W11', '20 min at marathon pace', '1 h 30 (taper)'],
      ['W12', '15 min easy jog', 'MARATHON'],
    ] },
    { type: 'note', text: `Taper (last 2 weeks): reduce volume by 40-50% while keeping a little intensity. You'll arrive fresh and sharp on race day. NEVER do a big long run in the final week.` },

    { type: 'h1', text: 'Race-day strategy' },
    { type: 'p', text: `A race is managed. The "negative split" (second half faster than the first) is the best strategy at all distances. Starting too fast is mistake #1.` },
    { type: 'table', headers: ['Distance', 'First third', 'Middle', 'Finish'], rows: [
      ['5K', 'Controlled, never all-out', 'Target pace', 'Empty the tank on the last km'],
      ['10K', 'Slightly under target pace', 'Steady target pace', 'Accelerate over the last 2 km'],
      ['Half', 'Very controlled', 'Steady target pace', 'Keep strength for the last 5 km'],
      ['Marathon', 'Slow, economical (the early trap)', 'Steady marathon pace', 'Manage the wall, finish strong if you can'],
    ] },
    { type: 'list', items: [
      `Go by your paces (chapter "calculate your paces"), not by other runners.`,
      `Drink and eat from the start on half/marathon, before you're hungry or thirsty.`,
      `Break the race up mentally (see mindset chapter): one segment at a time.`,
      `Prep your gear and breakfast the night before: zero improvising in the morning.`,
    ] },
    { type: 'note', text: `Golden rule: "start slow, then slow down" is a runner's joke… but it rings true. Almost all underperformances come from starting too fast. The discipline of the early kilometers makes for great finishes.` },

    { type: 'chapter', title: 'Runner nutrition', src: 'run-1.jpg', intro: `Eating and hydrating well means gaining minutes and avoiding the wall. Here are the benchmarks before, during and after the effort.` },
    { type: 'h2', text: 'Day to day' },
    { type: 'list', items: [
      `Enough carbs: they're your main fuel when running.`,
      `Protein at every meal for muscle recovery (1.4-1.8 g/kg).`,
      `Constant hydration: 2 to 3 L/day, more depending on heat and volume.`,
    ] },
    { type: 'h2', text: 'Before / during / after' },
    { type: 'table', headers: ['When', 'What', 'Why'], rows: [
      ['Before (2-3 h)', 'Carb-rich meal, low in fiber/fat', 'Fuel up without feeling heavy'],
      ['During (> 1 h)', 'Water + carbs (gels, drink, dried fruit) every 30-45 min', 'Avoid bonking (the "wall")'],
      ['After (0-1 h)', 'Carbs + protein + water', 'Recovery & replenishment'],
    ] },
    { type: 'note', text: `The marathon "wall" (around the 30th km) = depletion of glycogen stores. You avoid it by fueling FROM the start of the race (not when you're hungry), and by having done long runs in training.` },

    { type: 'h2', text: 'Hydration & fueling by effort' },
    { type: 'p', text: `Adapt your fueling to the duration of the run. Beyond an hour, carb intake becomes decisive.` },
    { type: 'table', headers: ['Duration', 'Drink', 'Carbs'], rows: [
      ['< 45 min', 'Not essential', 'None'],
      ['45 min - 1 h', 'Water if hot', 'Optional'],
      ['1 h - 2 h', '~500 ml/h', '30-40 g/h (gel, drink)'],
      ['> 2 h (marathon)', 'Water + electrolytes', '60-90 g/h, from the start'],
    ] },
    { type: 'list', items: [
      `Test EVERYTHING in training (gels, drinks, brands): never anything new on race day.`,
      `In high heat, add electrolytes (sodium) to avoid cramps and hyponatremia.`,
      `Dehydration warning signs: dark urine, dry mouth, dropping performance, dizziness.`,
      `After the effort, weigh yourself: drink ~1.5 L per kilo lost to rehydrate well.`,
    ] },
    { type: 'h2', text: 'Fueling: homemade or store-bought?' },
    { type: 'p', text: `Store-bought gels are convenient in a race, but you can easily fuel "homemade" in training, for less money and more digestible.` },
    { type: 'table', headers: ['Option', 'Carbs', 'When'], rows: [
      ['Energy gel', '~25 g', 'Race, high intensity'],
      ['Fruit jelly', '~20 g', 'Long runs'],
      ['Banana', '~25 g', 'Easy long run'],
      ['Dried fruit (dates, apricots)', '~15-20 g', 'Long runs'],
      ['Homemade sports drink', '~30-40 g/500 ml', 'Any run > 1 h'],
    ] },
    { type: 'note', text: `Homemade drink recipe (500 ml): water + 30 g of sugar (or syrup) + a pinch of salt + a squeeze of lemon. Simple, effective and far cheaper than store-bought drinks.` },

    { type: 'chapter', title: 'Injury prevention', src: 'run-2.jpg', intro: `Running is hard on the body. 80% of runner injuries come from avoidable mistakes: too much, too fast, poor recovery.` },
    { type: 'list', items: [
      `The 10% rule: don't increase your weekly volume by more than 10% per week.`,
      `Warm up before quality sessions (jog + drills).`,
      `Strengthen 1-2×/week (next chapter): a strong runner gets injured less.`,
      `Good shoes suited to your stride, replaced every ~800-1000 km.`,
      `Listen to pain: a joint ache that persists = rest + medical advice.`,
      `Alternate surfaces (road, trail) and never neglect rest days.`,
    ] },
    { type: 'h2', text: 'Problem → solution' },
    { type: 'table', headers: ['Symptom', 'Common cause', 'Solution'], rows: [
      ['Shin splints', 'Volume increased too fast', 'Reduce, ice, softer surfaces'],
      ["Runner's knee", 'Weak glutes/quads', 'Strength work + reduce the pace'],
      ['Achilles tendon', 'Too much intensity', 'Rest, calf stretches'],
      ['Blisters', 'Shoes/socks', 'Good gear, anti-chafe'],
    ] },

    { type: 'chapter', title: `The runner's recovery`, src: 'run-1.jpg', intro: `You don't progress during the effort, but during recovery. Neglecting it means stalling and getting injured. Here's how to recover well.` },
    { type: 'list', items: [
      `Sleep: 7 to 9 h per night. It's the #1 recovery tool, far ahead of everything else.`,
      `Rest days: non-negotiable. At least 1-2 run-free days per week depending on your plan.`,
      `Active recovery: walking, easy cycling or swimming on off days boosts circulation.`,
      `Nutrition: carbs + protein + hydration within the hour after big sessions.`,
      `Self-massage: roller and massage ball on calves, quads and glutes.`,
      `Watch for overtraining signs: persistent fatigue, poor sleep, high resting HR, dropping motivation.`,
    ] },
    { type: 'h2', text: 'The down week' },
    { type: 'p', text: `Every 3-4 weeks, cut your volume by ~30%. These "light" weeks let your body absorb the work and come back stronger. They're part of progress, not wasted time.` },

    { type: 'chapter', title: 'Choosing the right shoes', src: 'run-2.jpg', intro: `It's your only truly essential piece of gear. Good shoes suited to your stride prevent most injuries.` },
    { type: 'table', headers: ['Type', 'For whom', 'Use'], rows: [
      ['Cushioned / max-cushion', 'Beginners, heavier runners', 'EA, long runs, road'],
      ['Versatile', 'Most runners', 'Daily training'],
      ['Light / dynamic', 'Regular runners', 'Fast sessions, races'],
      ['Carbon plate', 'Experienced (racing)', 'Races (5K to marathon)'],
      ['Trail', 'Off-road', 'Trails, mountain, mud'],
    ] },
    { type: 'list', items: [
      `Get advice at a specialist store (gait analysis).`,
      `Buy a half size larger than your street size (feet swell).`,
      `Replace your shoes every ~800-1000 km (cushioning wears out even without visible holes).`,
      `Keep 2 pairs in rotation on high volume: they last longer and vary the stress.`,
    ] },

    { type: 'h1', text: 'Running in all weather' },
    { type: 'p', text: `There's no bad weather, only bad gear. Adapt to run safely all year round.` },
    { type: 'table', headers: ['Weather', 'Tips'], rows: [
      ['High heat', 'Early morning/evening, hydration + electrolytes, reduced pace, cap'],
      ['Cold', 'Several breathable layers, gloves/hat, longer warm-up'],
      ['Rain', 'Peaked cap, technical clothing, anti-chafe, spare socks'],
      ['Night', 'Reflective clothing, head torch, known and lit route'],
      ['Wind', 'Start into the wind, return with it at your back; stay careful by the road'],
    ] },
    { type: 'h2', text: 'Safety rules' },
    { type: 'list', items: [
      `Tell someone your route and return time on long runs.`,
      `Run facing traffic when there's no sidewalk, and stay visible.`,
      `Keep the volume low (or one earbud) so you can hear your surroundings.`,
      `Carry your phone and ID on long distances.`,
      `In a heatwave or on ice, don't hesitate to postpone: no session is worth an injury.`,
    ] },

    { type: 'h1', text: "Runner's strength work" },
    { type: 'p', text: `A strong body runs faster and gets injured less. Do this circuit 1 to 2 times per week (off big-session days). Scan the QR for the demo video.` },
    { type: 'exercise', name: 'Plank', muscles: 'Core, running posture', level: 'Beginner', technique: `Forearms on the floor, body aligned, abs and glutes braced. Hold 30-60 s. A solid trunk stabilizes your stride and saves energy.`, mistakes: `Hips sagging, glutes high, head lifted.` },
    { type: 'exercise', name: 'Squats', muscles: 'Quads, glutes', level: 'Beginner', technique: `Feet shoulder-width, sit the hips back with a straight back until thighs are parallel, stand back up. Builds drive and protects the knees.`, mistakes: `Knees caving in, heels lifting, rounded back.` },
    { type: 'exercise', name: 'Lunges', muscles: 'Glutes, quads, balance', level: 'Beginner', technique: `Big step forward, rear knee toward the floor, upright torso, push to return. Strengthens each leg and corrects imbalances.`, mistakes: `Step too short, leaning torso, loss of balance.` },
    { type: 'exercise', name: 'Glute bridge', muscles: 'Glutes, hamstrings', level: 'Beginner', technique: `On your back, knees bent, push through the heels to lift the hips, squeeze the glutes. Strong glutes protect knees and hips.`, mistakes: `Arching the back, lifting too high.` },
    { type: 'exercise', name: 'Standing calf raises', muscles: 'Calves, Achilles tendon', level: 'Beginner', technique: `Rise onto the balls of your feet as high as possible, pause, lower slowly. On a step for more range.`, mistakes: `Short range, bouncing, fast descent.` },
    { type: 'exercise', name: 'Side plank', muscles: 'Obliques, pelvis stability', level: 'Beginner - Intermediate', technique: `On your side, supported on the forearm, body aligned, hips lifted. Stabilizes the pelvis for an efficient stride.`, mistakes: `Hips dropping, body tipping.` },
    { type: 'exercise', name: 'Step-ups', muscles: 'Quads, glutes, balance', level: 'Beginner', technique: `Step up onto a step/bench by pushing through the front leg, control the descent. Works the single-leg power specific to running.`, mistakes: `Using the rear leg to help, uncontrolled descent.` },
    { type: 'exercise', name: 'Drill: high knees', muscles: 'Running technique, hip flexors', level: 'Beginner', technique: `Over 20 m, exaggerate the knee lift to hip height, fast rhythm, active core. Improves technique and stride frequency.`, mistakes: `Torso leaning back, knees too low, heavy stride.` },
    { type: 'exercise', name: 'Drill: butt kicks', muscles: 'Running technique, hamstrings', level: 'Beginner', technique: `Over 20 m, bring the heels toward the glutes, fast rhythm. Activates the hamstrings and smooths the stride.`, mistakes: `Leaning torso, short range.` },
    { type: 'exercise', name: 'Bounding strides', muscles: 'Power, propulsion', level: 'Intermediate', technique: `Over 20-30 m, exaggerate the push-off and flight phase, like bounds forward. Develops power and running economy.`, mistakes: `Stiff landing, lack of range, passive arms.` },
    { type: 'h2', text: 'The full circuit (2×/week)' },
    { type: 'p', text: `Run these exercises as a circuit, 2 to 3 rounds, off big-session days. 15-20 minutes is enough for a stronger, more resilient runner.` },
    { type: 'table', headers: ['Exercise', 'Sets × reps', 'Rest'], rows: [
      ['Plank', '3 × 30-45 s', '30 s'],
      ['Side plank', '3 × 30 s / side', '30 s'],
      ['Squats', '3 × 15', '45 s'],
      ['Lunges', '3 × 12 / leg', '45 s'],
      ['Glute bridge', '3 × 15', '30 s'],
      ['Standing calf raises', '3 × 20', '30 s'],
      ['Step-ups', '3 × 12 / leg', '45 s'],
    ] },
    { type: 'note', text: `The drills (high knees, butt kicks, bounding strides) are better done in the warm-up of quality sessions, over 20-30 m, 2 to 3 passes each.` },

    { type: 'h1', text: 'Stretching & mobility' },
    { type: 'p', text: `After each run, 5-10 min of targeted stretching. Hold each position 20-30 s, no jerking.` },
    { type: 'table', headers: ['Stretch', 'Area', 'Duration'], rows: [
      ['Calves at the wall', 'Calves, Achilles', '30 s / side'],
      ['Standing quad', 'Front of thigh', '30 s / side'],
      ['Straight-leg hamstring', 'Back of thigh', '30 s / side'],
      ['Low lunge (psoas)', 'Hip flexors', '30 s / side'],
      ['Glute stretch (figure 4)', 'Glutes', '30 s / side'],
      ['IT band', 'Outer thigh', '30 s / side'],
    ] },
    { type: 'h2', text: 'Foam rolling' },
    { type: 'p', text: `1 to 2 times a week, run a foam roller 30-60 s over each area (calves, quads, glutes, IT band). Go slowly and dwell on the tender spots, without rolling directly over the joints. It improves flexibility and speeds recovery.` },
    { type: 'note', text: `When to stretch? Rather when cold at the end of the day or after the cool-down, never forcefully on an unwarmed muscle. Stretching doesn't "prevent" all injuries, but it maintains your mobility and your stride comfort.` },

    { type: 'h1', text: "The competitor's mindset" },
    { type: 'p', text: `On long distances, the mind does as much as the legs. The good news: it's trainable, exactly like endurance. Here's how to forge your runner's head.` },
    { type: 'h2', text: 'The pillars of the mind' },
    { type: 'list', items: [
      `Break the race into segments: don't think "42 km" but "the next aid station".`,
      `Prepare mantras ("I'm strong", "one step at a time") for the hard moments.`,
      `Visualize your race and your finish line in the days before.`,
      `Start cautiously: most underperformances come from starting too fast.`,
      `Accept the discomfort: in the marathon, the hard part is part of the plan, it always passes.`,
    ] },
    { type: 'h2', text: 'Before the race: managing stress' },
    { type: 'list', items: [
      `Pre-race nerves are normal and even useful: they make you alert and focused.`,
      `Prepare everything the night before (bib, kit, breakfast) to free your mind.`,
      `Breathe slowly (inhale 4 s, exhale 6 s) to lower the tension.`,
      `Set 3 goals: an ambitious one, a realistic one, an "acceptable minimum".`,
    ] },
    { type: 'h2', text: 'During the race: holding on when it hurts' },
    { type: 'table', headers: ['Tough moment', 'Mental technique'], rows: [
      ['Start too easy', 'Hold yourself back: "patience, the race starts at halfway"'],
      ['A low patch', 'Mantra + focus on the stride and breathing'],
      ['The wall (marathon)', 'Segment: "just to the next km", smile, relax'],
      ['Urge to quit', 'Recall your "why" and the training hours invested'],
      ['Final kilometer', 'Empty the tank: "this is where I cash in"'],
    ] },
    { type: 'note', text: `Train your mind in training: long runs and the end of intervals are the ideal place to practice your mantras and segmentation. On race day, it'll just be one more habit.` },

    { type: 'h1', text: 'Essential equipment' },
    { type: 'p', text: `Good news: running is cheap. Beyond the shoes (dedicated chapter), here's the useful gear, ranked by priority - don't buy it all at once.` },
    { type: 'table', headers: ['Equipment', 'Priority', `What it's for`], rows: [
      ['Suitable shoes', 'Essential', 'Comfort and injury prevention'],
      ['Technical socks', 'Essential', 'Wick sweat, avoid blisters'],
      ['Breathable kit', 'Recommended', 'Stay dry, regulate temperature'],
      ['Support sports bra', 'Essential (women)', 'Comfort and protection'],
      ['GPS watch / app', 'Recommended', 'Track pace, distance, heart rate'],
      ['Belt / soft flask', 'Useful (long runs)', 'Carry water and fuel'],
      ['Anti-chafe', 'Useful', 'Protect sensitive areas (thighs, underarms)'],
      ['Head torch + reflective', 'As needed', 'Safety for running at night'],
    ] },
    { type: 'h2', text: 'GPS watch or smartphone?' },
    { type: 'p', text: `A free app on your phone (Strava, Nike Run Club…) is enough to start: it measures distance, pace and route. The GPS watch becomes a real plus once you work on your paces and heart rate day to day: instant reading at the wrist, without taking out the phone.` },
    { type: 'note', text: `The beginner's trap: buying everything at once. Start with good shoes and breathable kit. The rest, you'll add as you progress and as your goals evolve.` },

    { type: 'h1', text: 'Frequently asked questions' },
    { type: 'h2', text: "I can't run 5 min straight, can I start?" },
    { type: 'p', text: `Yes: the 5K plan alternates running and walking at the start. Gradually increase the running portion. In 8 weeks, you'll run your 5K.` },
    { type: 'h2', text: 'How fast should I run my easy runs?' },
    { type: 'p', text: `At easy aerobic pace, you should be able to hold a conversation. If you're out of breath, you're running too fast. 80% of your runs should be at this pace.` },
    { type: 'h2', text: 'How long before a marathon?' },
    { type: 'p', text: `If you already run ~1 h comfortably, 12 weeks is enough. Otherwise, do the 10K then half plans first before tackling a marathon.` },
    { type: 'h2', text: `What to do if I'm in pain?` },
    { type: 'p', text: `A passing muscular ache: adapt. A joint pain or one that persists: rest and see a professional. Never "push" through real pain - it's a guaranteed stop.` },
    { type: 'h2', text: 'Do I need to strength train?' },
    { type: 'p', text: `Yes, 1-2×/week. It's what makes you faster AND more injury-resistant. Strength work isn't optional for lasting progress.` },
    { type: 'h2', text: 'Treadmill or outdoors?' },
    { type: 'p', text: `Both work. The treadmill cushions and lets you control the pace (set 1% incline to mimic outdoors). Outdoors works balance, terrain and the mind. Ideally, alternate.` },
    { type: 'h2', text: 'How do I avoid a side stitch?' },
    { type: 'p', text: `Avoid eating too close to the run, warm up gradually and work on belly breathing. If you get a stitch, slow down and exhale fully while pressing lightly on the area.` },
    { type: 'h2', text: "I'm plateauing, what should I do?" },
    { type: 'p', text: `First check your recovery and sleep. Add variety (intervals, threshold), respect the 80/20, and do down weeks. Progress is never linear: patience pays.` },
    { type: 'h2', text: 'How many times a week should I run?' },
    { type: 'p', text: `3 runs are enough for the 5K and 10K, 3-4 for the half and marathon. Better 3 regular, quality runs than 5 rushed ones. Consistency beats one-off intensity.` },

    { type: 'h1', text: 'Tracking your runs' },
    { type: 'p', text: `Log every run: distance, duration, pace, sensations. It's your progress journal.` },
    { type: 'tracker', columns: ['Date', 'Distance (km)', 'Duration', 'Pace', 'Sensations /10'], rows: 13 },
    { type: 'h2', text: 'Personal records' },
    { type: 'tracker', columns: ['Distance', 'Goal', 'Achieved', 'Date'], rows: 6 },

    { type: 'h1', text: 'Weekly checklist' },
    { type: 'p', text: `Tick each box at the end of the week.` },
    { type: 'checklist', items: [
      `I did my planned runs this week.`,
      `80% of my volume was easy aerobic.`,
      `I didn't increase my volume by more than 10%.`,
      `I warmed up before my quality sessions.`,
      `I did 1-2 strength sessions.`,
      `I did my drills and worked on my cadence.`,
      `I stretched after my runs.`,
      `I slept 7 to 9 h per night.`,
      `I hydrated and ate well.`,
      `I respected my rest days.`,
      `I logged my runs and sensations.`,
      `I enjoyed running this week.`,
    ] },

    { type: 'h1', text: 'Motivation & consistency' },
    { type: 'p', text: `The hardest part isn't running fast, it's running CONSISTENTLY. Here's how to last over time.` },
    { type: 'list', items: [
      `Sign up for a race: a bib is the best of motivators.`,
      `Prep your gear the night before: less friction = fewer excuses.`,
      `Run at a fixed time to make it an automatic habit.`,
      `Find a partner or a club: it's easier to get up when there are two of you.`,
      `Celebrate every gain (first 5K without walking, new record): motivation feeds on wins.`,
      `On days you don't feel like it, set just "10 minutes". Most often, you'll finish your run.`,
    ] },
    { type: 'note', text: `Consistency beats talent. An average runner who trains 3×/week for a year progresses more than a gifted runner who trains one week in three. Be that consistent runner.` },

    { type: 'h1', text: "The runner's glossary" },
    { type: 'p', text: `The essential vocabulary to decode the plans and conversations between runners.` },
    { type: 'table', headers: ['Term', 'Definition'], rows: [
      ['EA', 'Easy aerobic: slow pace where you can talk'],
      ['VO2', 'The pace at which you reach your max oxygen consumption'],
      ['Threshold', 'Sustained pace holdable ~1 h; improves endurance at high intensity'],
      ['Intervals', 'Fast repetitions broken up by recoveries (e.g. 8 × 400 m)'],
      ['Fartlek', 'Free pace play: you speed up and slow down by feel'],
      ['Tempo', 'Continuous effort at a sustained pace (near threshold)'],
      ['Negative split', 'Running the 2nd half faster than the 1st'],
      ['Taper', 'Reducing volume before a race to arrive fresh'],
      ['The wall', 'Sudden glycogen depletion (often around the 30th km of a marathon)'],
      ['Drop', 'Heel/forefoot height difference of a shoe'],
      ['Cadence', 'Number of steps per minute'],
      ['Pace', 'Time to cover 1 km (min/km)'],
    ] },

    { type: 'h1', text: 'Personal notes' },
    { type: 'tracker', columns: ['My runs, sensations and goals for the week'], rows: 20 },

    { type: 'h1', text: 'And after your race?' },
    { type: 'p', text: `You crossed the finish line: bravo! But the adventure doesn't stop there. Here's how to turn this success into lasting progress.` },
    { type: 'list', items: [
      `Recover properly: 1 very easy week after a 5K/10K, 2 to 3 weeks after a marathon.`,
      `Set a new challenge: the next distance up, or the same time… faster.`,
      `Keep an easy-aerobic base all year: it's what makes comebacks easy.`,
      `Keep up the strength work and drills: a maintained runner is a runner who lasts.`,
      `Join a community or a club: running with others sustains motivation over the long term.`,
    ] },
    { type: 'h2', text: 'Choose your next target' },
    { type: 'table', headers: ['You just ran', 'Logical next goal'], rows: [
      ['Your first 5K', 'Improve your time, then aim for the 10K'],
      ['A 10K', 'The half marathon'],
      ['A half marathon', 'The marathon, or a faster half'],
      ['A marathon', 'A new marathon targeting time, or trail running'],
    ] },
    { type: 'note', text: `Congratulations! Take a proper recovery, then set off toward a new goal. Create your account at xenotif.com to track your runs, plan your paces and chat with your AI coach. See you on the start line!` },
  ],
}
