import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Programme Fitness Maison Sans Matériel (FR). Gabarit premium XENOTIF® (≈30 pages).
export const fitnessMaison: Guide = {
  id: 'fitness-maison',
  title: 'Programme Fitness Maison',
  subtitle: '8 semaines, 100 % au poids du corps, zéro matériel - où que tu sois',
  author: 'XENOTIF Coach - Préparation physique certifiée',
  level: 'Débutant - Intermédiaire',
  duration: '8 semaines · 4 séances/sem',
  coverImage: 'fitness-maison-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Ta salle de sport, c’est chez toi' },
    { type: 'p', text: `Pas de salle, pas de matériel, pas d’excuse. Ce programme de 8 semaines se fait entièrement au poids du corps, dans 2 m², à la maison ou en voyage. Tu vas tonifier ton corps, gagner en force fonctionnelle, brûler du gras et créer une routine indestructible - avec pour seul équipement ton propre corps.` },
    { type: 'p', text: `Chaque exercice possède un QR code vers sa vidéo de démonstration sur XENOTIF®. En cas de doute, scanne-le.` },
    { type: 'meta', items: [
      { label: 'Objectif', value: 'Tonifier, brûler, renforcer' },
      { label: 'Niveau', value: 'Débutant à intermédiaire' },
      { label: 'Durée', value: '8 semaines' },
      { label: 'Fréquence', value: '4 séances par semaine' },
      { label: 'Matériel', value: 'Aucun (tapis en option)' },
      { label: 'Lieu', value: 'Maison, voyage, n’importe où' },
    ] },
    { type: 'h2', text: 'Objectifs du programme' },
    { type: 'list', items: [
      `Tonifier et renforcer l’ensemble du corps sans matériel.`,
      `Brûler du gras grâce à des circuits intenses et courts.`,
      `Améliorer ta force fonctionnelle, ta mobilité et ton cardio.`,
      `Installer une routine que tu peux tenir partout, sans contrainte.`,
    ] },
    { type: 'h2', text: 'Comment utiliser ce guide' },
    { type: 'list', items: [
      `Lis le guide en entier, puis suis le calendrier des 8 semaines.`,
      `Échauffe-toi 5 min avant chaque séance (page dédiée).`,
      `Scanne le QR d’un exercice pour voir la technique en vidéo.`,
      `Progresse en passant aux variantes plus difficiles indiquées.`,
      `Fais ton bilan chaque dimanche (suivi + checklist).`,
    ] },
    { type: 'note', text: `Règle d’or du poids du corps : sans charges, tu progresses par la difficulté des variantes, le tempo, le nombre de répétitions et la densité (moins de repos). La progression existe bel et bien - il suffit de la provoquer.` },

    { type: 'h1', text: 'Comment ça marche' },
    { type: 'list', items: [
      `4 séances/semaine : 2 renforcement full body + 2 circuits cardio/HIIT.`,
      `Format circuit : enchaîne les exercices avec peu de repos pour garder l’intensité.`,
      `Répétitions ou temps : « 3 × 12 » = 3 séries de 12 ; « 40 s » = 40 secondes d’effort.`,
      `Tempo contrôlé : 2 s en descente, 1 s en montée. La lenteur augmente la difficulté.`,
      `Repos : 30 à 60 s entre les séries/exercices selon ton niveau.`,
      `Intensité (RPE /10) : vise 7-8 ; sur les circuits HIIT, monte à 9.`,
    ] },
    { type: 'h2', text: 'Progresser sans poids' },
    { type: 'p', text: `C’est LA question du training maison. Voici les 5 leviers pour continuer à progresser sans jamais toucher un haltère.` },
    { type: 'table', headers: ['Levier', 'Comment', 'Exemple'], rows: [
      ['Variante + dure', 'Choisir une version plus exigeante', 'Pompe → pompe déclinée'],
      ['Plus de répétitions', 'Ajouter des reps chaque semaine', '10 → 12 → 15'],
      ['Tempo lent', 'Ralentir l’excentrique', 'Descente de squat en 4 s'],
      ['Densité', 'Réduire le repos', '60 s → 30 s'],
      ['Unilatéral', 'Travailler un côté à la fois', 'Squat → squat bulgare'],
    ] },

    { type: 'h1', text: 'Échauffement' },
    { type: 'p', text: `5 minutes avant chaque séance pour préparer le corps et booster tes performances.` },
    { type: 'table', headers: ['Mouvement', 'Durée'], rows: [
      ['Marche / course sur place', '60 s'],
      ['Montées de genoux', '45 s'],
      ['Rotations bras & hanches', '45 s'],
      ['Squats lents', '45 s'],
      ['Fentes dynamiques', '45 s'],
      ['Gainage 20 s + pompes lentes', '40 s'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Le résultat se construit aussi dans l’assiette.' },
    { type: 'h1', text: 'Nutrition' },
    { type: 'p', text: `Quel que soit ton objectif (tonifier, sécher, se renforcer), les bases sont les mêmes : assez de protéines, des aliments simples, et un apport calorique adapté à ton but.` },
    { type: 'meta', items: [
      { label: 'Pour sécher', value: 'Léger déficit (−300/−500 kcal)' },
      { label: 'Pour se renforcer', value: 'Maintenance à léger surplus' },
      { label: 'Protéines', value: '1,6 à 2 g par kg' },
      { label: 'Hydratation', value: '2 à 3 L par jour' },
    ] },
    { type: 'list', items: [
      `Une source de protéines à chaque repas (œufs, poulet, poisson, skyr, légumineuses).`,
      `Des légumes à volonté, des glucides autour des séances.`,
      `Réduis le sucre liquide (sodas, jus, alcool).`,
      `Bois de l’eau régulièrement, surtout pendant les circuits.`,
    ] },
    { type: 'h2', text: 'Comprendre tes macros' },
    { type: 'table', headers: ['Macro', 'Rôle', 'Par g', 'Priorité'], rows: [
      ['Protéines', 'Muscle & satiété', '4 kcal', 'HAUTE - 1,6-2 g/kg'],
      ['Glucides', 'Énergie', '4 kcal', 'Autour des séances'],
      ['Lipides', 'Hormones, santé', '9 kcal', 'Modérée, qualité'],
    ] },
    { type: 'note', text: `Pas besoin de matériel… ni de cuisine compliquée. Compose chaque assiette : 1 protéine + 1 glucide + des légumes + un peu de bon gras.` },

    { type: 'h1', text: 'Recettes express' },
    { type: 'h2', text: 'Œufs brouillés + avoine' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 400 kcal' }, { label: 'Protéines', value: '28 g' }] },
    { type: 'list', items: [`3 œufs`, `40 g de flocons d’avoine`, `1 fruit`, `Épices`] },
    { type: 'p', text: `Préparation : brouille les œufs, prépare l’avoine à part. Petit-déj complet en 5 min.` },
    { type: 'h2', text: 'Salade de pois chiches au thon' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protéines', value: '35 g' }] },
    { type: 'list', items: [`1 boîte de pois chiches`, `1 boîte de thon`, `Tomates, oignon, persil`, `Citron, huile d’olive`] },
    { type: 'p', text: `Préparation : mélange le tout. Aucun ustensile de cuisson, ultra-rapide et rassasiant.` },
    { type: 'h2', text: 'Skyr protéiné' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 350 kcal' }, { label: 'Protéines', value: '32 g' }] },
    { type: 'list', items: [`250 g de skyr`, `Fruits rouges`, `30 g d’avoine`, `Amandes`] },
    { type: 'p', text: `Préparation : mélange. Parfait en collation ou après la séance.` },
    { type: 'h2', text: 'Poêlée poulet-légumes' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 470 kcal' }, { label: 'Protéines', value: '40 g' }] },
    { type: 'list', items: [`140 g de poulet`, `200 g de légumes (frais ou surgelés)`, `100 g de riz cuit`, `Épices, sauce soja`] },
    { type: 'p', text: `Préparation : saisis le poulet, ajoute les légumes, sers sur le riz. Une seule poêle, 12 min.` },
    { type: 'h2', text: 'Toast avocat-œuf' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 380 kcal' }, { label: 'Protéines', value: '22 g' }] },
    { type: 'list', items: [`2 tranches de pain complet`, `1/2 avocat`, `2 œufs`, `Citron, sel, poivre`] },
    { type: 'p', text: `Préparation : écrase l’avocat sur le pain, ajoute les œufs (au plat ou pochés). Petit-déj ou en-cas rassasiant.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Récupère bien pour progresser séance après séance.' },
    { type: 'h1', text: 'Récupération' },
    { type: 'list', items: [
      `Dors 7 à 9 h : c’est là que le corps se reconstruit.`,
      `Garde au moins 1 jour de repos complet par semaine.`,
      `Des courbatures les premières semaines, c’est normal.`,
      `Étire-toi 5-10 min après chaque séance.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: '4 séances par semaine, où que tu sois.' },
    { type: 'h1', text: 'Calendrier des 8 semaines' },
    { type: 'p', text: `Alterne renforcement et circuits. Augmente reps, ralentis le tempo ou passe aux variantes plus dures dès que c’est facile.` },
    { type: 'table', headers: ['Semaines', 'Focus', 'Volume', 'Note'], rows: [
      ['S1-S2', 'Adaptation', '3 tours', 'Apprendre les mouvements'],
      ['S3-S4', 'Volume', '4 tours', '+ répétitions'],
      ['S5-S6', 'Intensité', '4 tours', 'Variantes + dures, repos courts'],
      ['S7-S8', 'Pic', '5 tours', 'Bats tes perfs, bilan'],
    ] },
    { type: 'h2', text: 'Semaine type' },
    { type: 'table', headers: ['Jour', 'Séance', 'Durée'], rows: [
      ['Lundi', 'Renforcement A (bas + core)', '35 min'],
      ['Mardi', 'Circuit HIIT', '25 min'],
      ['Mercredi', 'Repos / marche', '-'],
      ['Jeudi', 'Renforcement B (haut + core)', '35 min'],
      ['Vendredi', 'Circuit cardio full body', '30 min'],
      ['Week-end', 'Repos actif + suivi', '-'],
    ] },

    { type: 'h2', text: 'Détail jour par jour (semaines 1 à 4)' },
    { type: 'p', text: `Les semaines 5 à 8 reprennent le même schéma avec plus de tours, des variantes plus dures et moins de repos (voir « Progression sur 8 semaines »).` },
    { type: 'table', headers: ['Jour', 'S1-S2', 'S3-S4'], rows: [
      ['Lundi', 'Renforcement A', 'Renforcement A (+ reps)'],
      ['Mardi', 'Circuit HIIT', 'Circuit HIIT'],
      ['Mercredi', 'Repos / marche', 'Repos / marche'],
      ['Jeudi', 'Renforcement B', 'Renforcement B (+ reps)'],
      ['Vendredi', 'Circuit cardio', 'Circuit cardio (4 tours)'],
      ['Samedi', 'Repos actif', 'Repos actif'],
      ['Dimanche', 'Repos + suivi', 'Repos + suivi'],
    ] },

    { type: 'h1', text: 'Tes séances en détail' },
    { type: 'h2', text: 'Renforcement A - Bas du corps & core' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Squats', '4', '15 à 20', '45 s'],
      ['Fentes alternées', '3', '12 / jambe', '45 s'],
      ['Pont fessier', '3', '20', '40 s'],
      ['Chaise contre le mur', '3', '40 s', '40 s'],
      ['Gainage planche', '3', '40 s', '40 s'],
    ] },
    { type: 'h2', text: 'Renforcement B - Haut du corps & core' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Pompes (variante adaptée)', '4', 'Max propre', '45 s'],
      ['Dips sur chaise', '3', '12', '45 s'],
      ['Rowing avec sac lesté (ou superman)', '3', '12', '45 s'],
      ['Pompes piké (épaules)', '3', '10', '45 s'],
      ['Gainage latéral', '3', '25 s / côté', '30 s'],
    ] },
    { type: 'h2', text: 'Circuit HIIT (25 min)' },
    { type: 'table', headers: ['Bloc', 'Effort', 'Récup.', 'Tours'], rows: [
      ['Burpees (ou squats sautés)', '40 s', '20 s', '4'],
      ['Mountain climbers', '40 s', '20 s', '4'],
      ['Fentes sautées (ou fentes)', '40 s', '20 s', '4'],
      ['Jumping jacks', '40 s', '20 s', '4'],
      ['Gainage dynamique', '40 s', '20 s', '4'],
    ] },

    { type: 'h1', text: 'Bibliothèque d’exercices' },
    { type: 'p', text: `Maîtrise ces mouvements au poids du corps. Scanne le QR pour la vidéo de démonstration.` },
    { type: 'exercise', name: 'Squat au poids du corps', muscles: 'Quadriceps, fessiers, ischios', level: 'Débutant', video: `${D}/musculation`, technique: `Pieds largeur d’épaules, descends en poussant les fesses vers l’arrière, dos droit, talons au sol, jusqu’à cuisses parallèles, puis remonte.`, mistakes: `Genoux qui rentrent, talons qui décollent, dos arrondi.` },
    { type: 'exercise', name: 'Fentes alternées', muscles: 'Fessiers, quadriceps, équilibre', level: 'Débutant', video: `${D}/musculation`, technique: `Grand pas en avant, genou arrière vers le sol, buste droit, genou avant au-dessus de la cheville, pousse pour revenir.`, mistakes: `Pas trop court, buste penché, perte d’équilibre.` },
    { type: 'exercise', name: 'Pompes', muscles: 'Pectoraux, triceps, épaules, gainage', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Corps gainé en ligne droite, descends la poitrine vers le sol, coudes ~45°, puis pousse. Variantes : inclinées (facile) → au sol → déclinées (dur).`, mistakes: `Bassin qui s’affaisse, coudes trop écartés, amplitude courte.` },
    { type: 'exercise', name: 'Pont fessier', muscles: 'Fessiers, ischios', level: 'Débutant', video: `${D}/musculation`, technique: `Sur le dos, genoux fléchis, pousse dans les talons pour monter le bassin, serre les fessiers en haut, redescends sans poser. Variante : sur une jambe.`, mistakes: `Cambrer le dos, monter trop haut, pieds trop loin.` },
    { type: 'exercise', name: 'Chaise contre le mur', muscles: 'Quadriceps, gainage', level: 'Débutant', video: `${D}/musculation`, technique: `Dos au mur, glisse jusqu’à cuisses parallèles, genoux à 90°, tiens la position, abdos engagés.`, mistakes: `Genoux qui dépassent les chevilles, dos décollé, apnée.` },
    { type: 'exercise', name: 'Dips sur chaise', muscles: 'Triceps, épaules, pectoraux', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Mains sur le bord d’une chaise stable, jambes devant, descends en pliant les coudes vers l’arrière, puis remonte. Jambes tendues = plus dur.`, mistakes: `Épaules qui montent, descente courte, chaise instable.` },
    { type: 'exercise', name: 'Pompes piké', muscles: 'Épaules, triceps', level: 'Intermédiaire', video: `${D}/musculation`, technique: `En « V » inversé (fessiers hauts), descends le sommet de la tête vers le sol en pliant les coudes, puis pousse. Prépare au handstand push-up.`, mistakes: `Dos rond, amplitude courte, coudes trop écartés.` },
    { type: 'exercise', name: 'Superman', muscles: 'Lombaires, fessiers, dos', level: 'Débutant', video: `${D}/musculation`, technique: `À plat ventre, décolle simultanément bras et jambes en contractant le dos et les fessiers, tiens 1-2 s, redescends contrôlé.`, mistakes: `Mouvement saccadé, cou en hyperextension, manque de contraction.` },
    { type: 'exercise', name: 'Gainage planche', muscles: 'Sangle abdominale', level: 'Débutant', video: `${D}/musculation`, technique: `Avant-bras et pointes de pieds, corps aligné, abdos et fessiers serrés, respire et tiens.`, mistakes: `Bassin qui s’affaisse, fesses hautes, tête relevée.` },
    { type: 'exercise', name: 'Gainage latéral', muscles: 'Obliques, gainage', level: 'Débutant', video: `${D}/musculation`, technique: `Sur le côté, appui sur un avant-bras, corps aligné, hanches décollées. Tiens et change de côté.`, mistakes: `Hanches qui descendent, corps qui bascule.` },
    { type: 'exercise', name: 'Mountain climbers', muscles: 'Abdos, épaules, cardio', level: 'Intermédiaire', video: `${D}/hiit`, technique: `En planche bras tendus, ramène alternativement un genou vers la poitrine de plus en plus vite, hanches basses, gainage actif.`, mistakes: `Fesses hautes, dos creusé, rythme désordonné.` },
    { type: 'exercise', name: 'Burpee', muscles: 'Corps entier, cardio', level: 'Avancé', video: `${D}/hiit`, technique: `Debout → mains au sol → pieds en arrière (planche) → pompe (option) → ramène les pieds → saut vertical. Enchaîne fluidement.`, mistakes: `Dos arrondi, réception jambes tendues. Amortis, rythme régulier.` },
    { type: 'exercise', name: 'Squats sautés', muscles: 'Jambes, fessiers, cardio', level: 'Intermédiaire', video: `${D}/hiit`, technique: `Squat puis saut explosif vers le haut, réception souple et contrôlée en position de squat, enchaîne.`, mistakes: `Réception genoux raides, dos penché, manque d’amplitude au squat.` },
    { type: 'exercise', name: 'Jumping jacks', muscles: 'Cardio, épaules, jambes', level: 'Débutant', video: `${D}/hiit`, technique: `Saute en écartant jambes et bras, puis reviens. Réception souple, rythme régulier.`, mistakes: `Réception raide, mouvement de bras incomplet.` },
    { type: 'exercise', name: 'Crunch', muscles: 'Grand droit (abdos)', level: 'Débutant', video: `${D}/musculation`, technique: `Sur le dos, genoux fléchis, décolle les épaules en enroulant le buste, expire, redescends lentement. Le bas du dos reste au sol.`, mistakes: `Tirer sur la nuque, décoller tout le dos, retenir sa respiration.` },
    { type: 'exercise', name: 'Relevé de jambes', muscles: 'Bas des abdos, gainage', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Allongé, mains sous les fessiers, monte les jambes (tendues ou fléchies) vers la verticale, redescends lentement sans toucher le sol. Bas du dos plaqué.`, mistakes: `Cambrer le dos, descente trop rapide, élan.` },
    { type: 'exercise', name: 'Pont fessier une jambe', muscles: 'Fessiers, ischios, gainage', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Pont fessier classique mais une jambe tendue en l’air. Pousse dans le talon au sol, monte le bassin bien à l’horizontale, serre le fessier. Change de jambe.`, mistakes: `Bassin qui se tord, hyperextension lombaire, amplitude courte.` },

    { type: 'h1', text: 'Cardio, marche & NEAT' },
    { type: 'p', text: `Au-delà des séances, ton activité quotidienne (NEAT) fait une énorme différence sur la dépense d’énergie et la perte de gras - sans fatiguer ni nécessiter de matériel.` },
    { type: 'list', items: [
      `Vise 8 000 à 10 000 pas par jour : marche, escaliers, trajets à pied.`,
      `2 à 3 marches rapides de 30 min/semaine, idéalement les jours de repos.`,
      `Fractionne : 3 × 10 min de marche valent un bloc de 30 min.`,
      `Le matin à jeun, en musique ou podcast : le meilleur moment pour tenir l’habitude.`,
    ] },
    { type: 'table', headers: ['Activité', 'Durée', 'Fréquence', 'Effet'], rows: [
      ['Marche (NEAT)', 'Tout au long du jour', 'Quotidien', 'Dépense, récupération'],
      ['Marche rapide', '30 min', '2-3×/sem', 'Cardio doux, gras'],
      ['Circuit HIIT', '20-25 min', '2×/sem', 'Brûle-graisses, EPOC'],
    ] },

    { type: 'h1', text: 'Progression sur 8 semaines' },
    { type: 'table', headers: ['Semaine', 'Volume / format', 'Objectif'], rows: [
      ['S1', '3 tours, repos 60 s', 'Apprendre les mouvements'],
      ['S2', '3 tours, +2 reps', 'Confirmer la technique'],
      ['S3', '4 tours', 'Augmenter le volume'],
      ['S4', '4 tours, repos 45 s', 'Bilan mi-parcours'],
      ['S5', '4 tours, variantes + dures', 'Monter en difficulté'],
      ['S6', '4 tours, tempo lent', 'Renforcer le contrôle'],
      ['S7', '5 tours', 'Pic de volume'],
      ['S8', '5 tours, repos 30 s', 'Pic, mesures finales'],
    ] },

    { type: 'h1', text: 'Adapte chaque exercice à ton niveau' },
    { type: 'p', text: `Au poids du corps, la progression passe par la variante. Choisis la version qui te permet de tenir le nombre de répétitions avec une bonne technique, puis monte en difficulté.` },
    { type: 'table', headers: ['Exercice', 'Plus facile', 'Standard', 'Plus dur'], rows: [
      ['Pompe', 'Inclinée (mains hautes)', 'Au sol', 'Déclinée / lestée'],
      ['Squat', 'Sur chaise', 'Au poids du corps', 'Sauté / bulgare'],
      ['Fente', 'Statique, appui', 'Alternée', 'Sautée'],
      ['Gainage', 'Sur les genoux', 'Planche complète', 'Dynamique / 3 appuis'],
      ['Dips', 'Pieds proches', 'Jambes mi-tendues', 'Jambes tendues'],
      ['Pont fessier', 'Deux jambes', 'Marqué en haut', 'Sur une jambe'],
    ] },

    { type: 'h1', text: 'Plan B : séance express 10 minutes' },
    { type: 'p', text: `Pas le temps ? Une séance courte vaut toujours mieux que rien : elle entretient l’habitude. Fais ce circuit 2 fois, 40 s d’effort / 20 s de transition, 1 min de repos entre les tours.` },
    { type: 'table', headers: ['Exercice', 'Durée', 'Récup.'], rows: [
      ['Squats', '40 s', '20 s'],
      ['Pompes', '40 s', '20 s'],
      ['Mountain climbers', '40 s', '20 s'],
      ['Fentes alternées', '40 s', '20 s'],
      ['Gainage planche', '40 s', '20 s'],
    ] },

    { type: 'h1', text: 'HIIT à la maison' },
    { type: 'p', text: `Le HIIT est ton meilleur allié pour brûler du gras sans matériel ni espace. Le principe : efforts courts et intenses entrecoupés de récupérations.` },
    { type: 'list', items: [
      `Format classique : 40 s d’effort / 20 s de repos, 4 à 5 exercices, 3 à 5 tours.`,
      `Sur l’effort, tu dois être incapable de tenir une conversation.`,
      `2 séances HIIT/semaine suffisent ; plus risque de nuire à la récupération.`,
      `Adapte l’impact : remplace les sauts par des versions au sol si articulations sensibles.`,
    ] },

    { type: 'h1', text: 'Erreurs à éviter' },
    { type: 'list', items: [
      `Croire qu’on ne progresse pas sans matériel : faux, utilise les 5 leviers de progression.`,
      `Bâcler la technique pour aller vite : la qualité prime, surtout au poids du corps.`,
      `Ne faire que du cardio : garde 2 séances de renforcement par semaine.`,
      `Sauter l’échauffement, surtout avant les circuits sautés.`,
      `Ignorer la nutrition : la séance ne compense pas une mauvaise alimentation.`,
    ] },
    { type: 'h2', text: 'Problème → solution' },
    { type: 'table', headers: ['Tu rencontres…', 'La solution'], rows: [
      ['Les pompes sont trop dures', 'Commence inclinées (mains surélevées)'],
      ['C’est devenu trop facile', 'Variante + dure, tempo lent, repos −15 s'],
      ['Douleur aux genoux (sauts)', 'Remplace par versions sans impact'],
      ['Manque de motivation', 'Séance courte de 15 min plutôt que rien'],
    ] },

    { type: 'h1', text: 'Rester motivé(e)' },
    { type: 'list', items: [
      `Fixe un créneau fixe : à la maison, c’est la routine qui fait tout.`,
      `Prépare ta tenue et ton tapis la veille.`,
      `Photos & mesures toutes les 4 semaines : la transformation se voit.`,
      `Garde une séance « plan B » de 15 min pour les jours sans temps.`,
    ] },
    { type: 'h2', text: 'Construis l’habitude' },
    { type: 'list', items: [
      `Associe ta séance à un moment précis (au réveil, avant le dîner).`,
      `Règle des 2 minutes : commence juste l’échauffement.`,
      `Ne saute jamais 2 séances de suite.`,
    ] },

    { type: 'h1', text: 'Questions fréquentes' },
    { type: 'h2', text: 'Peut-on vraiment se muscler sans poids ?' },
    { type: 'p', text: `Oui, surtout en débutant/intermédiaire. En augmentant la difficulté des variantes, les répétitions, le tempo et en réduisant le repos, tu crées une tension suffisante pour développer du muscle.` },
    { type: 'h2', text: 'Combien d’espace faut-il ?' },
    { type: 'p', text: `2 m² suffisent : de quoi t’allonger et faire une fente. Aucun matériel requis ; un tapis améliore le confort au sol.` },
    { type: 'h2', text: 'Et si je n’ai pas de chaise pour les dips ?' },
    { type: 'p', text: `Utilise un canapé, un lit bas ou des marches. Sinon remplace par des pompes serrées (mains rapprochées) qui ciblent aussi les triceps.` },
    { type: 'h2', text: 'Je vis en appartement, les sauts dérangent. Que faire ?' },
    { type: 'p', text: `Remplace tous les mouvements sautés par leurs versions sans impact (squat au lieu de squat sauté, montées de genoux au lieu de jumping jacks). L’efficacité reste excellente.` },
    { type: 'h2', text: 'Cardio ou renforcement pour perdre du gras ?' },
    { type: 'p', text: `Les deux. Le renforcement préserve le muscle, le HIIT et la marche augmentent la dépense. Et surtout : l’alimentation. Le programme combine déjà tout.` },

    { type: 'h1', text: 'Sécurité & impact' },
    { type: 'p', text: `Le training maison est très sûr. Quelques repères pour t’entraîner intensément sans te blesser, même sur sol dur ou en appartement.` },
    { type: 'list', items: [
      `Échauffe-toi toujours, surtout avant les mouvements sautés.`,
      `Réception souple sur la pointe des pieds, genoux fléchis, à chaque saut.`,
      `Sol dur ou voisins du dessous : remplace les sauts par des versions sans impact.`,
      `Garde le dos gainé et neutre sur les pompes, fentes et le gainage.`,
      `Douleur articulaire = stop. Choisis une variante plus douce.`,
    ] },

    { type: 'h1', text: 'Étirements & mobilité' },
    { type: 'p', text: `5-10 min après chaque séance, tiens chaque position 20-30 s.` },
    { type: 'table', headers: ['Étirement', 'Zone', 'Durée'], rows: [
      ['Quadriceps debout', 'Avant de cuisse', '30 s / côté'],
      ['Ischios jambe tendue', 'Arrière de cuisse', '30 s / côté'],
      ['Fente basse', 'Hanches', '30 s / côté'],
      ['Pectoraux au mur', 'Poitrine, épaules', '30 s / côté'],
      ['Chat-vache', 'Colonne', '45 s'],
    ] },

    { type: 'h1', text: 'Routine mobilité matinale (5 min)' },
    { type: 'p', text: `À faire au réveil ou les jours de repos : 5 minutes pour réveiller le corps, améliorer ta posture et préparer tes articulations. Aucun matériel, enchaîne fluidement.` },
    { type: 'table', headers: ['Mouvement', 'Cible', 'Durée'], rows: [
      ['Chat-vache', 'Colonne', '45 s'],
      ['Cercles d’épaules & de hanches', 'Articulations', '45 s'],
      ['Fente basse + rotation', 'Hanches, dos', '30 s / côté'],
      ['Squat profond tenu', 'Hanches, chevilles', '45 s'],
      ['Bascule du bassin debout', 'Lombaires', '45 s'],
      ['Étirement du cou & nuque', 'Cervicales', '30 s'],
    ] },

    { type: 'h1', text: 'Mesurer tes progrès (au-delà de la balance)' },
    { type: 'p', text: `La balance ne raconte qu’une partie de l’histoire. Au poids du corps, tes meilleurs indicateurs sont la performance et le miroir.` },
    { type: 'list', items: [
      `Performance : plus de répétitions, variantes plus dures, gainage plus long, moins de repos.`,
      `Photos : même lumière, même angle, même heure, toutes les 4 semaines.`,
      `Mensurations : tour de taille, hanches, cuisses, bras - souvent plus parlantes que le poids.`,
      `Sensations : énergie, sommeil, vêtements plus amples, posture améliorée.`,
      `Ne te pèse qu’une fois par semaine, à jeun, le même jour : le poids fluctue au quotidien.`,
    ] },

    { type: 'h1', text: 'Suivi de ta progression' },
    { type: 'p', text: `Remplis ces tableaux chaque semaine, dans les mêmes conditions.` },
    { type: 'h2', text: 'Poids & mensurations' },
    { type: 'tracker', columns: ['Date', 'Poids (kg)', 'Tour de taille', 'Énergie /10'], rows: 8 },
    { type: 'h2', text: 'Performances (reps ou temps)' },
    { type: 'tracker', columns: ['Exercice', 'S1', 'S3', 'S5', 'S8'], rows: 6 },

    { type: 'h1', text: 'Checklist hebdomadaire' },
    { type: 'p', text: `Coche chaque case en fin de semaine. Objectif : au moins 5 sur 7.` },
    { type: 'checklist', items: [
      `J’ai fait mes 4 séances cette semaine.`,
      `J’ai gardé une technique propre.`,
      `J’ai progressé (reps, variante ou repos plus court).`,
      `J’ai mangé des protéines à chaque repas.`,
      `J’ai bu 2 L d’eau par jour.`,
      `J’ai dormi 7 à 9 h la plupart des nuits.`,
      `J’ai noté mes performances.`,
    ] },

    { type: 'h1', text: 'Notes personnelles' },
    { type: 'tracker', columns: ['Mes notes, sensations et victoires de la semaine'], rows: 16 },

    { type: 'h1', text: 'Et après tes 8 semaines ?' },
    { type: 'list', items: [
      `Refais un cycle avec les variantes les plus dures et 5 tours partout.`,
      `Tu as accès à du matériel ? Passe au programme Musculation Débutant.`,
      `Objectif perte de gras : enchaîne le programme Perte de Poids.`,
      `Garde toujours ta routine maison « plan B » pour les jours sans salle.`,
    ] },

    { type: 'note', text: `8 semaines sans aucune excuse, c’est déjà une victoire. Refais tes mesures et ta photo, compare à ton point de départ, et continue sur ta lancée. Crée ton compte sur xenotif.com.` },
  ],
}
