import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// d3 - Programme HIIT Brûle-Graisses 6 Semaines (FR). 24 séances 20-30 min,
// 100% poids du corps, sans matériel, 3 niveaux, timers, QR vidéo. ≈30 pages.
export const hiit6s: Guide = {
  id: 'd3',
  title: 'Programme HIIT Brûle-Graisses - 6 Semaines',
  subtitle: '24 séances de 20-30 min, 100 % au poids du corps, sans aucun matériel',
  author: 'XENOTIF Coach - Certifié CrossFit & préparation physique',
  level: 'Débutant → Avancé',
  duration: '6 semaines · 24 séances · 20-30 min',
  coverImage: 'hiit-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Brûle un maximum en un minimum de temps' },
    { type: 'p', text: `En 6 semaines, ce programme va transformer ta condition physique et faire fondre la graisse - sans salle, sans matériel, où que tu sois, en séances courtes mais intenses de 20 à 30 minutes. Tu y trouveras les 24 séances détaillées avec leurs minuteurs, la technique de chaque mouvement, et trois niveaux pour progresser de débutant à avancé.` },
    { type: 'p', text: `Chaque exercice a un QR code vers sa vidéo de démonstration sur XENOTIF®. Garde le guide sur ton téléphone et lance ton minuteur : c’est parti.` },
    { type: 'meta', items: [
      { label: 'Objectif', value: 'Brûler du gras, gagner du souffle' },
      { label: 'Niveau', value: 'Débutant à avancé' },
      { label: 'Durée', value: '6 semaines · 24 séances' },
      { label: 'Séance', value: '20 à 30 minutes' },
      { label: 'Matériel', value: 'Aucun (poids du corps)' },
      { label: 'Fréquence', value: '4 séances par semaine' },
    ] },
    { type: 'h2', text: 'Ce que tu vas obtenir' },
    { type: 'list', items: [
      `Une perte de gras visible (le HIIT brûle pendant ET après l’effort).`,
      `Un cardio et un souffle nettement améliorés.`,
      `Un corps plus tonique et plus athlétique.`,
      `Une routine express tenable même les jours chargés.`,
    ] },
    { type: 'h2', text: 'Comment utiliser ce guide' },
    { type: 'list', items: [
      `Choisis ton niveau (débutant / intermédiaire / avancé) - voir le chapitre dédié.`,
      `Suis les 24 séances dans l’ordre (4 par semaine).`,
      `Lance un minuteur d’intervalles (effort / récup) pour chaque séance.`,
      `Scanne le QR d’un exercice pour revoir la technique.`,
      `Échauffe-toi 5 min avant, étire-toi 5 min après.`,
    ] },
    { type: 'note', text: `Intensité = clé. Sur les phases d’effort, tu dois être incapable de tenir une conversation. Sur la récupération, tu reprends ton souffle activement (marche sur place, respiration profonde).` },

    { type: 'h1', text: 'Pourquoi le HIIT fonctionne' },
    { type: 'p', text: `Le HIIT (High Intensity Interval Training) alterne efforts intenses et récupérations courtes. Résultat : tu brûles des calories pendant l’effort ET jusqu’à 24 h après, grâce à l’effet EPOC (surconsommation d’oxygène post-effort).` },
    { type: 'list', items: [
      `Une séance de 20 min peut brûler autant qu’un footing de 45 min.`,
      `Le corps continue de brûler des calories après la séance (afterburn).`,
      `Le HIIT préserve le muscle mieux que le cardio long et monotone.`,
      `Aucun matériel : tu peux t’entraîner partout, n’importe quand.`,
    ] },

    { type: 'chapter', title: 'Choisis ton niveau & ton minuteur', src: 'hiit-1.jpg', intro: `Toutes les séances suivent un format d’intervalles. Choisis le ratio effort/récupération adapté à ton niveau, puis programme ton minuteur (ou l’app XENOTIF). Tu pourras monter de niveau au fil des semaines.` },
    { type: 'table', headers: ['Niveau', 'Effort', 'Récup.', 'Tours / bloc'], rows: [
      ['Débutant', '20 s', '40 s', '3'],
      ['Intermédiaire', '40 s', '20 s', '4'],
      ['Avancé', '45 s', '15 s', '4 à 5'],
    ] },
    { type: 'h2', text: 'Règle du minuteur' },
    { type: 'list', items: [
      `Programme un minuteur d’intervalles avec ton ratio (ex. 40 s / 20 s).`,
      `Repos entre les blocs d’exercices : 60 s (débutant), 45 s (interm.), 30 s (avancé).`,
      `Monte d’un niveau quand une séance devient « confortable ».`,
    ] },

    { type: 'h1', text: 'Échauffement (5 min)' },
    { type: 'p', text: `Indispensable avant chaque séance HIIT, surtout avec des mouvements explosifs.` },
    { type: 'table', headers: ['Mouvement', 'Durée'], rows: [
      ['Marche / course sur place', '60 s'],
      ['Montées de genoux', '45 s'],
      ['Rotations bras & hanches', '45 s'],
      ['Squats lents', '45 s'],
      ['Fentes dynamiques + talons-fesses', '60 s'],
    ] },

    { type: 'chapter', title: 'Les 24 séances', src: 'hiit-cover.jpg', intro: `Voici tes 24 séances (4 par semaine). Applique TON ratio effort/récup (chapitre niveau). Chaque ligne = un bloc à répéter selon le nombre de tours de ton niveau. Échauffe-toi avant, étire-toi après.` },
    { type: 'h2', text: 'Semaine 1 - Adaptation' },
    { type: 'table', headers: ['Séance', 'Blocs', 'Durée'], rows: [
      ['S1 · Full body', 'Squats · Pompes genoux · Mountain climbers · Gainage', '20 min'],
      ['S2 · Cardio', 'Jumping jacks · Montées de genoux · Talons-fesses · Fentes', '20 min'],
      ['S3 · Bas + core', 'Squats · Fentes · Pont fessier · Gainage latéral', '20 min'],
      ['S4 · Haut + core', 'Pompes · Dips chaise · Pompes piké · Gainage', '20 min'],
    ] },
    { type: 'h2', text: 'Semaine 2 - Volume' },
    { type: 'table', headers: ['Séance', 'Blocs', 'Durée'], rows: [
      ['S5 · Full body', 'Squats sautés · Pompes · Mountain climbers · Burpees', '22 min'],
      ['S6 · Cardio', 'Jumping jacks · High knees · Skaters · Talons-fesses', '22 min'],
      ['S7 · Bas + core', 'Fentes sautées · Squats · Pont fessier · Relevés de jambes', '22 min'],
      ['S8 · Haut + core', 'Pompes · Dips · Pompes diamant · Gainage dynamique', '22 min'],
    ] },
    { type: 'h2', text: 'Semaine 3 - Intensité' },
    { type: 'table', headers: ['Séance', 'Blocs', 'Durée'], rows: [
      ['S9 · Full body', 'Burpees · Squats sautés · Mountain climbers · Pompes', '25 min'],
      ['S10 · Cardio', 'High knees · Skaters · Jumping jacks · Sprint sur place', '25 min'],
      ['S11 · Bas + core', 'Fentes sautées · Squats · Pont fessier 1 jambe · Gainage', '25 min'],
      ['S12 · Haut + core', 'Pompes déclinées · Dips · Pompes piké · Mountain climbers', '25 min'],
    ] },
    { type: 'h2', text: 'Semaine 4 - Circuits' },
    { type: 'table', headers: ['Séance', 'Blocs', 'Durée'], rows: [
      ['S13 · Full body', 'Burpees · Fentes sautées · Pompes · Gainage dynamique', '25 min'],
      ['S14 · Cardio', 'Sprint sur place · Skaters · Jumping jacks · High knees', '25 min'],
      ['S15 · Bas + core', 'Squats sautés · Fentes · Pont fessier · Relevés de jambes', '25 min'],
      ['S16 · Haut + core', 'Pompes · Pompes diamant · Dips · Gainage latéral', '25 min'],
    ] },
    { type: 'h2', text: 'Semaine 5 - Pic' },
    { type: 'table', headers: ['Séance', 'Blocs', 'Durée'], rows: [
      ['S17 · Full body', 'Burpees · Squats sautés · Pompes · Mountain climbers', '28 min'],
      ['S18 · Cardio', 'Sprint sur place · High knees · Skaters · Jumping jacks', '28 min'],
      ['S19 · Bas + core', 'Fentes sautées · Squats · Pont fessier 1 jambe · Gainage', '28 min'],
      ['S20 · Haut + core', 'Pompes déclinées · Pompes diamant · Dips · Gainage dynamique', '28 min'],
    ] },
    { type: 'h2', text: 'Semaine 6 - Finition' },
    { type: 'table', headers: ['Séance', 'Blocs', 'Durée'], rows: [
      ['S21 · Full body', 'Burpees · Squats sautés · Pompes · Gainage dynamique', '30 min'],
      ['S22 · Cardio max', 'Sprint sur place · Skaters · High knees · Jumping jacks', '30 min'],
      ['S23 · Bas + core', 'Fentes sautées · Squats sautés · Pont fessier · Relevés de jambes', '30 min'],
      ['S24 · Défi final', 'Burpees · Mountain climbers · Pompes · Squats sautés · Gainage', '30 min'],
    ] },
    { type: 'note', text: `Repère ta progression : compte tes répétitions sur un bloc fixe (ex. burpees en 40 s) en S1, S3 et S6. Tu verras la différence.` },

    { type: 'h1', text: 'Anatomie d’une séance type' },
    { type: 'p', text: `Chaque séance suit la même structure. Exemple détaillé d’une séance « Full body » niveau intermédiaire (40 s effort / 20 s récup, 4 tours) :` },
    { type: 'table', headers: ['Phase', 'Contenu', 'Durée'], rows: [
      ['Échauffement', 'Cardio léger + mobilité + activation', '5 min'],
      ['Bloc 1', 'Burpees - 40 s / 20 s × 4', '4 min'],
      ['Bloc 2', 'Squats sautés - 40 s / 20 s × 4', '4 min'],
      ['Bloc 3', 'Pompes - 40 s / 20 s × 4', '4 min'],
      ['Bloc 4', 'Mountain climbers - 40 s / 20 s × 4', '4 min'],
      ['Retour au calme', 'Marche + étirements', '5 min'],
    ] },
    { type: 'p', text: `Repos entre les blocs : 45 s (interm.). Total ≈ 26 min. Adapte les ratios et tours à TON niveau (chapitre « Choisis ton niveau »).` },
    { type: 'note', text: `🎥 Vidéos : chaque exercice de la bibliothèque ci-dessous possède un QR code qui ouvre sa vidéo de démonstration HD sur XENOTIF®. En cas de doute sur l’exécution, scanne-le avant de lancer ton minuteur.` },

    { type: 'h1', text: 'Bibliothèque d’exercices' },
    { type: 'p', text: `Maîtrise ces mouvements. Scanne le QR pour la vidéo de démonstration.` },
    { type: 'exercise', name: 'Burpee', muscles: 'Corps entier, cardio', level: 'Avancé', video: `${D}/hiit`, technique: `Debout → mains au sol → saut des pieds en arrière (planche) → pompe (option) → ramène les pieds → saut vertical bras tendus. Enchaîne de façon fluide.`, mistakes: `Dos arrondi, réception jambes tendues. Amortis, rythme régulier plutôt que rapide et brouillon.` },
    { type: 'exercise', name: 'Squats sautés', muscles: 'Jambes, fessiers, cardio', level: 'Intermédiaire', video: `${D}/hiit`, technique: `Squat puis saut explosif, réception souple en position de squat, enchaîne. Version débutant : squat sans saut.`, mistakes: `Réception genoux raides, dos penché, amplitude trop courte.` },
    { type: 'exercise', name: 'Mountain climbers', muscles: 'Abdos, épaules, cardio', level: 'Intermédiaire', video: `${D}/hiit`, technique: `En planche bras tendus, ramène alternativement un genou vers la poitrine, de plus en plus vite, hanches basses, gainage actif.`, mistakes: `Fesses hautes, dos creusé, rythme désordonné.` },
    { type: 'exercise', name: 'Jumping jacks', muscles: 'Cardio, épaules, jambes', level: 'Débutant', video: `${D}/hiit`, technique: `Saute en écartant jambes et bras, puis reviens. Réception souple, rythme régulier.`, mistakes: `Réception raide, bras incomplets.` },
    { type: 'exercise', name: 'High knees (montées de genoux)', muscles: 'Cardio, fléchisseurs de hanche, abdos', level: 'Débutant', video: `${D}/hiit`, technique: `Course sur place en montant les genoux à hauteur de hanche, rythme rapide, gainage serré, bras qui accompagnent.`, mistakes: `Buste penché en arrière, genoux trop bas, foulée lourde.` },
    { type: 'exercise', name: 'Skaters (patineur)', muscles: 'Jambes, fessiers, cardio, équilibre', level: 'Intermédiaire', video: `${D}/hiit`, technique: `Bond latéral d’un pied sur l’autre, jambe libre derrière, comme un patineur. Réception souple, gainage actif.`, mistakes: `Réception raide, manque d’amplitude latérale, buste qui s’effondre.` },
    { type: 'exercise', name: 'Pompes', muscles: 'Pectoraux, triceps, épaules, gainage', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Corps gainé, descends la poitrine vers le sol, coudes ~45°, pousse. Variantes : genoux (facile) → au sol → déclinées (dur).`, mistakes: `Bassin qui s’affaisse, coudes trop écartés, amplitude courte.` },
    { type: 'exercise', name: 'Pompes diamant', muscles: 'Triceps, pectoraux', level: 'Avancé', video: `${D}/musculation`, technique: `Mains rapprochées formant un losange sous la poitrine, descends puis pousse. Cible fortement les triceps.`, mistakes: `Coudes qui partent vers l’extérieur, amplitude partielle, dos qui cambre.` },
    { type: 'exercise', name: 'Dips sur chaise', muscles: 'Triceps, épaules', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Mains sur le bord d’une chaise, jambes devant, descends en pliant les coudes vers l’arrière, remonte. Jambes tendues = plus dur.`, mistakes: `Épaules qui montent, descente courte, chaise instable.` },
    { type: 'exercise', name: 'Fentes sautées', muscles: 'Jambes, fessiers, cardio', level: 'Avancé', video: `${D}/hiit`, technique: `Depuis une fente, saute et change de jambe en l’air, réception souple en fente. Version débutant : fentes alternées sans saut.`, mistakes: `Genou avant qui dépasse trop, buste penché, réception raide.` },
    { type: 'exercise', name: 'Gainage dynamique', muscles: 'Abdos, épaules, gainage', level: 'Intermédiaire', video: `${D}/musculation`, technique: `En planche, passe alternativement des avant-bras aux mains tendues et inversement, en gardant le bassin stable.`, mistakes: `Hanches qui se balancent, dos creusé, rythme trop rapide.` },
    { type: 'exercise', name: 'Relevés de jambes', muscles: 'Bas des abdos, gainage', level: 'Débutant', video: `${D}/musculation`, technique: `Allongé, mains sous les fessiers, monte les jambes vers la verticale, redescends lentement sans toucher le sol. Bas du dos plaqué.`, mistakes: `Cambrer le dos, descente rapide, élan.` },
    { type: 'exercise', name: 'Sprint sur place', muscles: 'Cardio, jambes', level: 'Intermédiaire', video: `${D}/hiit`, technique: `Cours sur place le plus vite possible, foulée rapide sur l’avant du pied, bras actifs, gainage serré. Intensité maximale.`, mistakes: `Foulée lourde, buste raide, intensité insuffisante.` },
    { type: 'exercise', name: 'Talons-fesses', muscles: 'Cardio, ischios', level: 'Débutant', video: `${D}/hiit`, technique: `Course sur place en ramenant les talons vers les fessiers, rythme rapide, gainage actif.`, mistakes: `Pencher le buste, amplitude trop courte, rythme mou.` },
    { type: 'exercise', name: 'Pompes piké', muscles: 'Épaules, triceps', level: 'Intermédiaire', video: `${D}/musculation`, technique: `En « V » inversé (fessiers hauts), descends le sommet de la tête vers le sol en pliant les coudes, puis pousse. Travaille les épaules.`, mistakes: `Dos rond, amplitude courte, coudes trop écartés.` },
    { type: 'exercise', name: 'Pont fessier', muscles: 'Fessiers, ischios', level: 'Débutant', video: `${D}/musculation`, technique: `Sur le dos, genoux fléchis, pousse dans les talons pour monter le bassin, serre les fessiers en haut, redescends sans poser.`, mistakes: `Cambrer le dos, monter trop haut, pieds trop loin.` },
    { type: 'exercise', name: 'Pompes déclinées', muscles: 'Haut des pectoraux, épaules, triceps', level: 'Avancé', video: `${D}/musculation`, technique: `Pieds surélevés (chaise/canapé), corps gainé, descends la poitrine vers le sol puis pousse. Plus les pieds sont hauts, plus c’est dur.`, mistakes: `Bassin qui s’affaisse, amplitude courte, coudes trop écartés.` },
    { type: 'exercise', name: 'Gainage latéral', muscles: 'Obliques, gainage', level: 'Débutant', video: `${D}/musculation`, technique: `Sur le côté, appui sur un avant-bras, corps aligné, hanches décollées. Tiens, puis change de côté.`, mistakes: `Hanches qui descendent, corps qui bascule vers l’avant.` },

    { type: 'h1', text: 'Adapter par niveau' },
    { type: 'p', text: `Chaque mouvement a une version plus facile et plus dure : tu peux suivre les 24 séances quel que soit ton niveau.` },
    { type: 'table', headers: ['Exercice', 'Plus facile', 'Plus dur'], rows: [
      ['Burpee', 'Sans pompe / sans saut', 'Avec pompe + saut groupé'],
      ['Squat sauté', 'Squat au poids du corps', 'Squat sauté + 180°'],
      ['Pompe', 'Sur les genoux / inclinée', 'Déclinée / diamant'],
      ['Fente sautée', 'Fente alternée', 'Fente sautée + tempo'],
      ['Mountain climber', 'Plus lent', 'Cross-body rapide'],
    ] },

    { type: 'chapter', title: 'Nutrition pour brûler', src: 'nutrition.jpg', intro: `Le HIIT accélère la perte de gras, mais l’assiette reste reine. Pas besoin de régime compliqué : applique ces repères et la définition apparaîtra plus vite.` },
    { type: 'meta', items: [
      { label: 'Déficit', value: '300 à 500 kcal / jour' },
      { label: 'Protéines', value: '1,8 à 2 g par kg' },
      { label: 'Hydratation', value: '2 à 3 L par jour' },
      { label: 'Sommeil', value: '7 à 8 h' },
    ] },
    { type: 'list', items: [
      `Une source de protéines à chaque repas (préserve le muscle).`,
      `Beaucoup de légumes pour le volume et la satiété.`,
      `Des glucides autour de la séance HIIT pour l’énergie.`,
      `Réduis le sucre liquide et l’alcool - la victoire la plus rapide.`,
      `Hydrate-toi : le HIIT fait beaucoup transpirer.`,
    ] },
    { type: 'h2', text: '4 recettes express brûle-graisses' },
    { type: 'h2', text: 'Bol skyr-fruits post-HIIT' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 300 kcal' }, { label: 'Protéines', value: '30 g' }] },
    { type: 'list', items: [`200 g de skyr`, `Fruits rouges`, `30 g d’avoine`] },
    { type: 'p', text: `Mélange. Refait le plein de protéines après la séance.` },
    { type: 'h2', text: 'Omelette légumes' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 320 kcal' }, { label: 'Protéines', value: '28 g' }] },
    { type: 'list', items: [`3 œufs`, `Épinards, poivron`, `Salade verte`] },
    { type: 'p', text: `Fais revenir les légumes, verse les œufs, accompagne d’une salade.` },
    { type: 'h2', text: 'Bowl poulet-riz-légumes' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 470 kcal' }, { label: 'Protéines', value: '40 g' }] },
    { type: 'list', items: [`130 g de poulet`, `100 g de riz (cru)`, `Légumes`, `Sauce soja`] },
    { type: 'p', text: `Cuis le riz, saisis le poulet et les légumes, assemble.` },
    { type: 'h2', text: 'Shake protéiné' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 200 kcal' }, { label: 'Protéines', value: '25 g' }] },
    { type: 'list', items: [`1 dose de whey`, `250 ml d’eau ou lait écrémé`, `Glaçons`] },
    { type: 'p', text: `Secoue. Pratique juste après l’entraînement.` },

    { type: 'h1', text: 'Marche & NEAT' },
    { type: 'p', text: `Au-delà des séances HIIT, ton activité quotidienne (NEAT) fait une grosse différence sur la dépense - sans fatiguer ni nuire à ta récupération.` },
    { type: 'list', items: [
      `Vise 8 000 à 10 000 pas/jour : escaliers, trajets à pied, marche après les repas.`,
      `Les jours sans HIIT, fais 30 min de marche rapide.`,
      `Fractionne : 3 × 10 min de marche valent un bloc de 30 min.`,
      `La marche aide à récupérer du HIIT (circulation, gestion du stress).`,
    ] },

    { type: 'h1', text: 'Récupération' },
    { type: 'list', items: [
      `Le HIIT est exigeant : garde au moins 1 jour de repos entre 2 séances dures.`,
      `Dors 7 à 8 h : la récupération conditionne tes performances et la perte de gras.`,
      `Étire-toi et fais du foam rolling si tu en as.`,
      `Une marche les jours off entretient la dépense sans fatiguer.`,
    ] },

    { type: 'h1', text: 'Erreurs à éviter' },
    { type: 'list', items: [
      `Sauter l’échauffement : risque de blessure élevé sur les mouvements explosifs.`,
      `Bâcler la technique pour aller plus vite : qualité avant vitesse.`,
      `Faire du HIIT tous les jours : 4 séances/semaine suffisent, le repos fait partie du plan.`,
      `Négliger l’assiette : le HIIT ne compense pas un surplus calorique.`,
      `Réception raide sur les sauts : amortis toujours pour protéger genoux et chevilles.`,
    ] },
    { type: 'h2', text: 'Problème → solution' },
    { type: 'table', headers: ['Tu rencontres…', 'La solution'], rows: [
      ['Trop dur de tenir l’effort', 'Descends d’un niveau (ratio + de récup)'],
      ['Douleur aux genoux (sauts)', 'Versions sans impact (squat, montées de genoux)'],
      ['Pas de perte de gras', 'Vérifie l’assiette : c’est elle qui décide'],
      ['Trop facile', 'Monte d’un niveau, ajoute un tour'],
    ] },

    { type: 'h1', text: 'Rester motivé(e)' },
    { type: 'list', items: [
      `Fixe-toi un défi chiffré (ex. « +5 burpees en 40 s en 6 semaines »).`,
      `Prends une photo et tes mesures toutes les 2 semaines.`,
      `Mets une playlist énergique : le rythme booste l’intensité.`,
      `20 minutes, c’est court : rappelle-toi que tu auras fini avant d’avoir eu le temps d’abandonner.`,
    ] },

    { type: 'h1', text: 'Questions fréquentes' },
    { type: 'h2', text: 'Je suis débutant, c’est trop dur ?' },
    { type: 'p', text: `Non : le niveau débutant (20 s d’effort / 40 s de récup) est accessible, et chaque exercice a une version régressée. Commence là, monte de niveau quand tu te sens prêt.` },
    { type: 'h2', text: 'Combien de fois par semaine ?' },
    { type: 'p', text: `4 séances par semaine, avec au moins un jour de repos entre les séances dures. Inutile d’en faire plus : la récupération fait partie des résultats.` },
    { type: 'h2', text: 'Le HIIT suffit-il pour perdre du gras ?' },
    { type: 'p', text: `Le HIIT accélère fortement la dépense, mais la perte de gras se décide à 70 % dans l’assiette. Combine HIIT + léger déficit alimentaire.` },
    { type: 'h2', text: 'J’habite en appartement, les sauts dérangent.' },
    { type: 'p', text: `Remplace tous les mouvements sautés par leurs versions sans impact (squats, montées de genoux au lieu de jumping jacks). L’intensité reste élevée.` },
    { type: 'h2', text: 'Faut-il du matériel ?' },
    { type: 'p', text: `Aucun. Juste une chaise stable pour les dips (optionnel) et un minuteur d’intervalles (ton téléphone suffit).` },

    { type: 'h1', text: 'Retour au calme & étirements' },
    { type: 'p', text: `5 minutes après chaque séance pour faire redescendre le cœur et limiter les courbatures. Tiens chaque étirement 20-30 s.` },
    { type: 'table', headers: ['Étirement', 'Zone', 'Durée'], rows: [
      ['Marche lente', 'Cœur', '1-2 min'],
      ['Quadriceps debout', 'Avant de cuisse', '30 s / côté'],
      ['Ischios jambe tendue', 'Arrière de cuisse', '30 s / côté'],
      ['Mollets au mur', 'Mollets', '30 s / côté'],
      ['Pectoraux & épaules', 'Haut du corps', '30 s / côté'],
      ['Respiration profonde', 'Récupération', '1 min'],
    ] },

    { type: 'h1', text: 'Sécurité & impact' },
    { type: 'list', items: [
      `Échauffe-toi toujours avant les mouvements explosifs (burpees, sauts).`,
      `Réception souple sur la pointe des pieds, genoux fléchis, à chaque saut.`,
      `Sol dur ou appartement : remplace les sauts par les versions sans impact.`,
      `Garde le dos gainé et neutre sur les pompes, fentes et le gainage.`,
      `Douleur articulaire vive = stop. Choisis une variante plus douce ou repose-toi.`,
    ] },

    { type: 'h1', text: 'Et après tes 6 semaines ?' },
    { type: 'list', items: [
      `Refais le test de référence (reps en 40 s) : compare à la semaine 1.`,
      `Recommence un cycle au niveau supérieur (ratio plus exigeant, plus de tours).`,
      `Combine avec de la musculation (Fitness Maison / Musculation) pour te tonifier.`,
      `Garde 2 séances HIIT/semaine en entretien une fois ton objectif atteint.`,
    ] },

    { type: 'h1', text: 'Comprendre l’intensité' },
    { type: 'p', text: `Le HIIT ne marche que si l’effort est VRAIMENT intense. Pour te repérer sans cardiofréquencemètre, utilise le « test de la parole » : ta capacité à parler indique ton intensité.` },
    { type: 'table', headers: ['Zone', 'Ressenti', 'Test de la parole', 'Usage'], rows: [
      ['Faible', 'Très facile', 'Tu chantes', 'Échauffement, marche'],
      ['Modérée', 'Soutenu', 'Phrases courtes', 'Récupération active'],
      ['Élevée', 'Dur, essoufflé', 'Quelques mots', 'Phases d’effort HIIT'],
      ['Maximale', 'Très dur', 'Impossible de parler', 'Sprints, finishers'],
    ] },
    { type: 'list', items: [
      `Sur l’effort : vise « élevée à maximale » - tu ne dois pas pouvoir discuter.`,
      `Sur la récup : redescends en « modérée », respire profondément.`,
      `Si tu tiens une conversation pendant l’effort, c’est que tu ne pousses pas assez.`,
    ] },

    { type: 'h1', text: 'Ta semaine type' },
    { type: 'p', text: `Répartis tes 4 séances avec au moins un jour de repos entre les plus dures. Exemple de semaine :` },
    { type: 'table', headers: ['Jour', 'Au programme'], rows: [
      ['Lundi', 'Séance HIIT (Full body)'],
      ['Mardi', 'Marche 30 min / repos'],
      ['Mercredi', 'Séance HIIT (Cardio)'],
      ['Jeudi', 'Repos actif'],
      ['Vendredi', 'Séance HIIT (Bas + core)'],
      ['Samedi', 'Séance HIIT (Haut + core)'],
      ['Dimanche', 'Repos + suivi'],
    ] },

    { type: 'h1', text: 'Finishers brûle-graisses (bonus)' },
    { type: 'p', text: `Les jours où tu as 5 minutes de plus, ajoute un finisher en fin de séance pour un pic de dépense. Format Tabata : 20 s d’effort max / 10 s de repos, 8 tours.` },
    { type: 'table', headers: ['Finisher', 'Format', 'Cible'], rows: [
      ['Tabata burpees', '20 s / 10 s × 8', 'Corps entier'],
      ['Tabata squats sautés', '20 s / 10 s × 8', 'Jambes'],
      ['Tabata mountain climbers', '20 s / 10 s × 8', 'Abdos, cardio'],
      ['Tabata sprint sur place', '20 s / 10 s × 8', 'Cardio max'],
    ] },
    { type: 'note', text: `Un finisher Tabata ne dure que 4 minutes mais te met K.O. : parfait pour finir en beauté sans rallonger la séance.` },

    { type: 'h1', text: 'Suivi de ta progression' },
    { type: 'p', text: `Note tes performances et tes mesures chaque semaine.` },
    { type: 'h2', text: 'Poids & énergie' },
    { type: 'tracker', columns: ['Date', 'Poids (kg)', 'Tour de taille (cm)', 'Énergie /10'], rows: 7 },
    { type: 'h2', text: 'Test de référence (reps en 40 s)' },
    { type: 'tracker', columns: ['Exercice', 'S1', 'S3', 'S6'], rows: 5 },

    { type: 'h1', text: 'Checklist hebdomadaire' },
    { type: 'p', text: `Coche chaque case en fin de semaine. Objectif : au moins 5 sur 7.` },
    { type: 'checklist', items: [
      `J’ai fait mes 4 séances cette semaine.`,
      `Je me suis échauffé(e) avant chaque séance.`,
      `J’ai donné l’intensité maximale sur les efforts.`,
      `J’ai mangé des protéines à chaque repas.`,
      `J’ai respecté un léger déficit calorique.`,
      `J’ai bu 2 L+ d’eau par jour.`,
      `J’ai noté mes performances.`,
    ] },

    { type: 'h1', text: 'Notes personnelles' },
    { type: 'tracker', columns: ['Mes séances, sensations et records de la semaine'], rows: 16 },

    { type: 'note', text: `6 semaines bouclées ? Refais le test de référence pour mesurer tes progrès, puis recommence un cycle au niveau supérieur, ou enchaîne le programme Cardio Endurance / Fitness Maison. Crée ton compte sur xenotif.com.` },
  ],
}
