import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Programme Musculation Débutant (FR). Gabarit premium XENOTIF® (≈30 pages).
export const musculationDebutant: Guide = {
  id: 'musculation-debutant',
  title: 'Programme Musculation Débutant',
  subtitle: '8 semaines pour poser des bases solides en force et en muscle',
  author: 'XENOTIF Coach — Préparation physique certifiée',
  level: 'Débutant',
  duration: '8 semaines · 3 séances/sem',
  coverImage: 'cover.jpg',
  blocks: [
    { type: 'h1', text: 'Bienvenue — tu débutes la musculation' },
    { type: 'p', text: `Ce programme est conçu pour les vrais débutants : aucune expérience requise. En 8 semaines, tu vas apprendre les mouvements fondamentaux, gagner en force, prendre du muscle et créer une routine durable. On privilégie la technique et la régularité plutôt que la charge : c’est ainsi qu’on progresse vite et sans se blesser.` },
    { type: 'p', text: `Garde ce guide sur ton téléphone : chaque exercice possède un QR code qui ouvre sa vidéo de démonstration sur XENOTIF®. En cas de doute sur un mouvement, scanne-le.` },
    { type: 'meta', items: [
      { label: 'Objectif', value: 'Force, muscle & bases techniques' },
      { label: 'Niveau', value: 'Débutant (zéro expérience OK)' },
      { label: 'Durée', value: '8 semaines' },
      { label: 'Fréquence', value: '3 séances par semaine' },
      { label: 'Matériel', value: 'Salle, ou haltères + barre' },
      { label: 'Format', value: 'Full body 3 jours' },
    ] },
    { type: 'h2', text: 'Objectifs du programme' },
    { type: 'list', items: [
      `Maîtriser les 6 mouvements fondamentaux (squat, charnière, poussée, tirage, fente, gainage).`,
      `Gagner en force rapidement (les progrès du débutant sont les plus spectaculaires).`,
      `Prendre du muscle et tonifier l’ensemble du corps.`,
      `Installer une routine d’entraînement que tu garderas sur le long terme.`,
    ] },
    { type: 'h2', text: 'Comment utiliser ce guide' },
    { type: 'list', items: [
      `Lis le guide en entier, puis suis le calendrier des 8 semaines.`,
      `Commence léger : maîtrise le mouvement avant d’ajouter du poids.`,
      `Échauffe-toi 5-8 min avant chaque séance (page dédiée).`,
      `Scanne le QR d’un exercice pour voir la technique en vidéo.`,
      `Note tes charges à chaque séance et fais ton bilan le dimanche.`,
    ] },
    { type: 'note', text: `Règle d’or du débutant : la technique avant la charge. Une répétition propre vaut dix répétitions bâclées. Le muscle vient de la qualité du mouvement, pas de l’ego.` },

    { type: 'h1', text: 'Comment ça marche' },
    { type: 'list', items: [
      `Full body : tu travailles tout le corps à chaque séance, 3 fois par semaine.`,
      `Repos d’au moins 1 jour entre les séances (ex. lundi / mercredi / vendredi).`,
      `Séries × répétitions : « 3 × 10 » = 3 séries de 10 répétitions.`,
      `Tempo contrôlé : 2 s pour descendre, 1 s pour monter. Jamais de à-coups.`,
      `Repos : 90 s sur les gros mouvements, 60 s sur le reste.`,
      `RPE 7 à 8 : garde 2-3 répétitions en réserve. Tu ne vas pas à l’échec en tant que débutant.`,
    ] },
    { type: 'h2', text: 'Les 6 mouvements fondamentaux' },
    { type: 'p', text: `Tout repose sur 6 schémas moteurs. Si tu les maîtrises, tu peux entraîner tout ton corps n’importe où.` },
    { type: 'table', headers: ['Schéma', 'Exemple', 'Muscles principaux'], rows: [
      ['Squat (flexion)', 'Squat, presse', 'Quadriceps, fessiers'],
      ['Charnière (hinge)', 'Soulevé de terre roumain', 'Ischios, fessiers, dos'],
      ['Poussée', 'Développé couché, pompes', 'Pecs, épaules, triceps'],
      ['Tirage', 'Rowing, tirage vertical', 'Dos, biceps'],
      ['Fente', 'Fente, split squat', 'Jambes, équilibre'],
      ['Gainage', 'Planche, gainage latéral', 'Abdos, lombaires'],
    ] },

    { type: 'h1', text: 'Échauffement' },
    { type: 'p', text: `Ne saute jamais l’échauffement : il prépare le corps et améliore tes performances. Fais-le avant chaque séance.` },
    { type: 'table', headers: ['Étape', 'Détail', 'Durée'], rows: [
      ['Cardio léger', 'Vélo / corde / marche rapide', '3 min'],
      ['Mobilité', 'Épaules, hanches, chevilles', '2 min'],
      ['Activation', 'Gainage + squats au poids du corps', '2 min'],
      ['Séries d’approche', '1-2 séries légères du 1er exercice', '1 min'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Bien manger accélère tes progrès de débutant.' },
    { type: 'h1', text: 'Nutrition' },
    { type: 'p', text: `Bonne nouvelle : en tant que débutant, tu peux prendre du muscle ET perdre un peu de gras en même temps (« recomposition »). Mange à ta maintenance ou en léger surplus, avec assez de protéines.` },
    { type: 'meta', items: [
      { label: 'Calories', value: 'Maintenance à léger surplus' },
      { label: 'Protéines', value: '1,6 à 2 g par kg de poids' },
      { label: 'Hydratation', value: '2 à 3 L par jour' },
      { label: 'Sommeil', value: '7 à 9 h' },
    ] },
    { type: 'h2', text: 'Les règles simples' },
    { type: 'list', items: [
      `Une source de protéines à chaque repas (œufs, poulet, poisson, skyr, légumineuses).`,
      `Des glucides autour de l’entraînement (riz, pâtes, avoine, fruits) pour l’énergie.`,
      `Des légumes à chaque repas principal.`,
      `Bois de l’eau régulièrement, surtout pendant la séance.`,
    ] },
    { type: 'h2', text: 'Comprendre tes macros' },
    { type: 'table', headers: ['Macro', 'Rôle', 'Par g', 'Priorité'], rows: [
      ['Protéines', 'Construisent le muscle', '4 kcal', 'HAUTE — 1,6-2 g/kg'],
      ['Glucides', 'Énergie à l’entraînement', '4 kcal', 'Autour des séances'],
      ['Lipides', 'Hormones, santé', '9 kcal', 'Modérée, qualité'],
    ] },
    { type: 'note', text: `Pas besoin de tout peser. Compose simplement chaque assiette ainsi : 1 source de protéines + 1 source de glucides + des légumes + un peu de bon gras.` },

    { type: 'h1', text: 'Recettes simples' },
    { type: 'h2', text: 'Bol protéiné post-séance' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 500 kcal' }, { label: 'Protéines', value: '40 g' }] },
    { type: 'list', items: [`130 g de poulet`, `100 g de riz (cru)`, `Légumes`, `Sauce soja, épices`] },
    { type: 'p', text: `Préparation : cuis le riz, saisis le poulet et les légumes, assemble. Idéal après l’entraînement.` },
    { type: 'h2', text: 'Petit-déj protéiné' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 420 kcal' }, { label: 'Protéines', value: '35 g' }] },
    { type: 'list', items: [`200 g de skyr`, `50 g de flocons d’avoine`, `1 banane`, `1 c. à café de miel`] },
    { type: 'p', text: `Préparation : mélange skyr et flocons, ajoute la banane et le miel. Rapide et rassasiant.` },
    { type: 'h2', text: 'Omelette complète' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 400 kcal' }, { label: 'Protéines', value: '30 g' }] },
    { type: 'list', items: [`3 œufs`, `50 g de fromage`, `Épinards, tomate`, `1 tranche de pain complet`] },
    { type: 'p', text: `Préparation : bats les œufs, ajoute légumes et fromage, cuis à feu doux. Sers avec le pain. Petit-déj ou dîner express.` },
    { type: 'h2', text: 'Pâtes thon-tomate' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 520 kcal' }, { label: 'Protéines', value: '35 g' }] },
    { type: 'list', items: [`100 g de pâtes complètes (cru)`, `1 boîte de thon`, `Sauce tomate, ail`, `Un filet d’huile d’olive`] },
    { type: 'p', text: `Préparation : cuis les pâtes, mélange thon et sauce tomate à l’ail. Rapide, économique, riche en protéines.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Le muscle se construit pendant le repos.' },
    { type: 'h1', text: 'Récupération' },
    { type: 'list', items: [
      `Dors 7 à 9 h : la récupération musculaire a lieu surtout la nuit.`,
      `Laisse au moins 1 jour de repos entre les séances full body.`,
      `Des courbatures les premières semaines, c’est normal : elles diminueront.`,
      `Étire-toi 5-10 min après chaque séance.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: '3 séances par semaine, tout le corps.' },
    { type: 'h1', text: 'Calendrier des 8 semaines' },
    { type: 'p', text: `Alterne 3 séances full body (A, B, C) sur la semaine. Augmente charges ou répétitions dès que c’est facile.` },
    { type: 'table', headers: ['Semaines', 'Focus', 'Répétitions', 'Note'], rows: [
      ['S1-S2', 'Apprentissage technique', '3 × 10-12', 'Charges légères, mouvement propre'],
      ['S3-S4', 'Mise en place', '3 × 10', '+ charge progressive'],
      ['S5-S6', 'Renforcement', '4 × 8-10', 'Tu maîtrises, tu charges'],
      ['S7-S8', 'Consolidation', '4 × 8', 'Bats tes perfs de S1, bilan'],
    ] },
    { type: 'h2', text: 'Semaine type' },
    { type: 'table', headers: ['Jour', 'Séance', 'Durée'], rows: [
      ['Lundi', 'Full body A', '45 min'],
      ['Mardi', 'Repos / marche', '—'],
      ['Mercredi', 'Full body B', '45 min'],
      ['Jeudi', 'Repos / marche', '—'],
      ['Vendredi', 'Full body C', '45 min'],
      ['Week-end', 'Repos + suivi', '—'],
    ] },

    { type: 'h1', text: 'Tes séances en détail' },
    { type: 'h2', text: 'Full body A' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Squat (ou presse)', '3', '10', '90 s'],
      ['Développé couché (ou pompes)', '3', '10', '90 s'],
      ['Rowing / tirage', '3', '12', '75 s'],
      ['Gainage planche', '3', '30 s', '45 s'],
    ] },
    { type: 'h2', text: 'Full body B' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Soulevé de terre roumain', '3', '10', '90 s'],
      ['Développé militaire', '3', '10', '90 s'],
      ['Tirage vertical', '3', '12', '75 s'],
      ['Fentes', '3', '10 / jambe', '60 s'],
    ] },
    { type: 'h2', text: 'Full body C' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Fentes (ou split squat)', '3', '10 / jambe', '75 s'],
      ['Pompes (ou développé)', '3', 'Max propre', '75 s'],
      ['Rowing haltère', '3', '12', '75 s'],
      ['Curl + extension triceps', '3', '12', '60 s'],
      ['Gainage latéral', '3', '20 s / côté', '45 s'],
    ] },

    { type: 'h1', text: 'Bibliothèque d’exercices' },
    { type: 'p', text: `Maîtrise ces mouvements de base. Scanne le QR pour la vidéo de démonstration.` },
    { type: 'exercise', name: 'Squat', muscles: 'Quadriceps, fessiers, ischios', level: 'Débutant', video: `${D}/musculation`, technique: `Pieds largeur d’épaules, descends en poussant les fesses vers l’arrière, dos gainé, jusqu’à cuisses parallèles, puis remonte dans les talons. Commence au poids du corps avant d’ajouter une barre.`, mistakes: `Genoux qui rentrent, talons qui décollent, dos arrondi. Regard devant, poitrine ouverte.` },
    { type: 'exercise', name: 'Soulevé de terre roumain', muscles: 'Ischios, fessiers, dos', level: 'Débutant', video: `${D}/musculation`, technique: `Charge devant les cuisses, dos plat. Pousse les hanches vers l’arrière en descendant la charge le long des jambes, légère flexion des genoux, puis reviens en serrant les fessiers.`, mistakes: `Dos arrondi, charge qui s’éloigne du corps, plier les genoux comme un squat.` },
    { type: 'exercise', name: 'Pompes', muscles: 'Pectoraux, triceps, épaules', level: 'Débutant', video: `${D}/musculation`, technique: `Corps gainé en ligne droite, mains un peu plus larges que les épaules. Descends la poitrine vers le sol, coudes à ~45°, puis pousse. Sur les genoux ou inclinées si besoin.`, mistakes: `Bassin qui s’affaisse, coudes trop écartés, amplitude trop courte.` },
    { type: 'exercise', name: 'Développé couché', muscles: 'Pectoraux, triceps, épaules', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Omoplates serrées, descends la barre vers le bas des pectoraux, coudes ~45°, puis pousse. Pieds ancrés au sol. Commence léger, demande une parade si lourd.`, mistakes: `Coudes trop écartés, rebond sur la poitrine, fesses qui décollent.` },
    { type: 'exercise', name: 'Rowing haltère', muscles: 'Dos, biceps', level: 'Débutant', video: `${D}/musculation`, technique: `Un genou et une main sur un banc, dos plat. Tire l’haltère vers la hanche en serrant l’omoplate, puis redescends lentement. Le mouvement vient du dos.`, mistakes: `Dos rond, rotation du buste, tirer avec le bras seul.` },
    { type: 'exercise', name: 'Développé militaire', muscles: 'Épaules, triceps', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Debout, gainage serré, pousse la charge au-dessus de la tête sans cambrer le bas du dos, puis redescends contrôlé jusqu’aux épaules.`, mistakes: `Cambrure lombaire, pousser vers l’avant, amplitude incomplète.` },
    { type: 'exercise', name: 'Tirage vertical', muscles: 'Dos, biceps', level: 'Débutant', video: `${D}/musculation`, technique: `Assis, prise large. Tire la barre vers le haut de la poitrine en abaissant les épaules et serrant le dos, puis remonte contrôlé.`, mistakes: `Se balancer, tirer derrière la nuque, relâcher en haut.` },
    { type: 'exercise', name: 'Fentes', muscles: 'Quadriceps, fessiers, équilibre', level: 'Débutant', video: `${D}/musculation`, technique: `Grand pas en avant, genou arrière vers le sol, buste droit. Le genou avant reste au-dessus de la cheville. Pousse dans le talon avant pour revenir.`, mistakes: `Pas trop court, buste penché, perte d’équilibre.` },
    { type: 'exercise', name: 'Curl biceps', muscles: 'Biceps', level: 'Débutant', video: `${D}/musculation`, technique: `Coudes collés au corps, monte les haltères en contractant, redescends lentement. Pas d’élan du buste.`, mistakes: `Se balancer, coudes qui avancent, descente trop rapide.` },
    { type: 'exercise', name: 'Gainage planche', muscles: 'Sangle abdominale', level: 'Débutant', video: `${D}/musculation`, technique: `Appui avant-bras et pointes de pieds, corps aligné, abdos et fessiers serrés. Respire calmement et tiens la position.`, mistakes: `Bassin qui s’affaisse, fesses trop hautes, tête relevée.` },
    { type: 'exercise', name: 'Dips sur banc', muscles: 'Triceps, épaules, pectoraux', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Mains sur le bord d’un banc, jambes devant. Descends le bassin en pliant les coudes vers l’arrière, puis remonte en poussant. Plus les jambes sont tendues, plus c’est dur.`, mistakes: `Épaules qui montent vers les oreilles, descente trop courte, banc instable.` },
    { type: 'exercise', name: 'Gainage latéral', muscles: 'Obliques, gainage', level: 'Débutant', video: `${D}/musculation`, technique: `Sur le côté, appui sur un avant-bras, corps aligné. Décolle les hanches et tiens sans laisser le bassin tomber. Change de côté.`, mistakes: `Hanches qui descendent, épaule mal alignée avec le coude, corps qui bascule.` },
    { type: 'exercise', name: 'Hip thrust (pont fessier lesté)', muscles: 'Fessiers, ischios', level: 'Débutant', video: `${D}/musculation`, technique: `Haut du dos sur un banc, charge sur les hanches. Pousse dans les talons pour monter le bassin jusqu’à l’alignement épaules-genoux, serre les fessiers 1 s en haut, puis redescends.`, mistakes: `Cambrer le bas du dos, monter trop haut, pieds mal placés.` },
    { type: 'exercise', name: 'Élévations latérales', muscles: 'Épaules (deltoïdes)', level: 'Débutant', video: `${D}/musculation`, technique: `Debout, haltères légers le long du corps. Monte les bras sur les côtés jusqu’à l’horizontale, coudes légèrement fléchis, puis redescends lentement. Léger = mieux ici.`, mistakes: `Charger trop lourd, monter au-dessus des épaules, balancer le corps.` },
    { type: 'exercise', name: 'Mollets debout', muscles: 'Mollets', level: 'Débutant', video: `${D}/musculation`, technique: `Debout, monte sur la pointe des pieds le plus haut possible, marque un temps d’arrêt, puis redescends lentement en étirant. Sur une marche pour plus d’amplitude.`, mistakes: `Amplitude trop courte, rebond, descente trop rapide.` },

    { type: 'h1', text: 'Exécuter une série parfaite' },
    { type: 'p', text: `La qualité d’exécution est ce qui sépare un débutant qui progresse d’un débutant qui se blesse. Voici les 5 principes à appliquer sur chaque série.` },
    { type: 'list', items: [
      `Amplitude complète : descends et monte sur toute la course du mouvement.`,
      `Tempo contrôlé : 2 s en descente, 1 s en montée. Jamais d’à-coups ni d’élan.`,
      `Respiration : expire à l’effort (montée), inspire au relâchement (descente).`,
      `Gainage : abdos serrés pour protéger le bas du dos sur chaque répétition.`,
      `Connexion muscle-cerveau : concentre-toi sur le muscle qui travaille, pas sur le poids.`,
    ] },
    { type: 'note', text: `Si tu ne peux pas faire toutes tes répétitions avec une forme propre, c’est que la charge est trop lourde. Réduis : le muscle répond à la qualité, pas à l’ego.` },

    { type: 'h1', text: 'Cardio pour débutant' },
    { type: 'p', text: `Le cardio n’est pas obligatoire pour progresser en muscu, mais il améliore ta santé, ta récupération et t’aide à rester sec. Garde-le léger pour ne pas nuire à tes séances de force.` },
    { type: 'list', items: [
      `2 à 3 marches rapides de 30 min par semaine, les jours de repos.`,
      `Option : 10-15 min de vélo ou rameur en fin de séance.`,
      `Vise 8 000 pas/jour au quotidien : escaliers, trajets à pied, etc.`,
      `Évite les longues sorties cardio intenses qui fatiguent tes jambes avant la muscu.`,
    ] },

    { type: 'h1', text: 'Variante maison sans matériel' },
    { type: 'p', text: `Pas de salle ni d’haltères ? Ce circuit full body au poids du corps remplace une séance. Fais 3 à 4 tours, 45 s d’effort / 15 s de transition, 1 min de repos entre les tours.` },
    { type: 'table', headers: ['Exercice', 'Cible', 'Répétitions / temps'], rows: [
      ['Squats au poids du corps', 'Jambes', '15 à 20'],
      ['Pompes (genoux si besoin)', 'Haut du corps', 'Max propre'],
      ['Fentes alternées', 'Jambes', '10 / jambe'],
      ['Rowing avec sac lesté', 'Dos', '12'],
      ['Dips sur chaise', 'Triceps', '10'],
      ['Gainage planche', 'Abdos', '30 à 45 s'],
    ] },

    { type: 'h1', text: 'Renforcer les abdominaux' },
    { type: 'p', text: `Ajoute 5 minutes d’abdos en fin de séance, 2 à 3 fois par semaine. Un tronc fort protège ton dos et améliore tous tes autres exercices.` },
    { type: 'exercise', name: 'Crunch', muscles: 'Grand droit (abdos)', level: 'Débutant', video: `${D}/musculation`, technique: `Allongé, genoux fléchis, mains sur la poitrine ou les tempes. Décolle les épaules du sol en enroulant le buste, expire, puis redescends lentement. Le bas du dos reste au sol.`, mistakes: `Tirer sur la nuque, décoller tout le dos, retenir sa respiration.` },
    { type: 'exercise', name: 'Relevé de jambes', muscles: 'Bas des abdos, gainage', level: 'Débutant - Intermédiaire', video: `${D}/musculation`, technique: `Allongé, mains sous les fessiers. Monte les jambes tendues (ou genoux fléchis) jusqu’à la verticale, puis redescends lentement sans toucher le sol. Bas du dos plaqué.`, mistakes: `Cambrer le bas du dos, descendre trop vite, élan des jambes.` },
    { type: 'list', items: [
      `Circuit abdos express : crunch 15 + relevé de jambes 12 + gainage 40 s, 3 tours.`,
      `Qualité avant quantité : mouvements lents et contrôlés.`,
      `Les abdos se voient surtout grâce à une alimentation maîtrisée, pas seulement aux exercices.`,
    ] },

    { type: 'h1', text: 'Détail des 8 semaines' },
    { type: 'p', text: `Voici l’évolution semaine par semaine. Garde les 3 séances full body, fais évoluer charges et répétitions.` },
    { type: 'table', headers: ['Semaine', 'Séries × Reps', 'Objectif de la semaine'], rows: [
      ['Semaine 1', '3 × 12', 'Apprendre les mouvements, charges très légères'],
      ['Semaine 2', '3 × 12', 'Confirmer la technique, légère hausse'],
      ['Semaine 3', '3 × 10', 'Ajouter du poids, repos 90 s'],
      ['Semaine 4', '3 × 10', 'Bilan mi-parcours, photo & mesures'],
      ['Semaine 5', '4 × 10', 'Ajouter une série, plus de volume'],
      ['Semaine 6', '4 × 8', 'Charges plus lourdes'],
      ['Semaine 7', '4 × 8', 'Pic d’intensité propre'],
      ['Semaine 8', '4 × 8 + bilan', 'Battre ses perfs de S1, mesures finales'],
    ] },

    { type: 'h1', text: 'Progression recommandée' },
    { type: 'p', text: `Les débutants progressent vite : profite-en avec une surcharge progressive simple.` },
    { type: 'list', items: [
      `Quand tu fais toutes tes séries au haut de la fourchette de répétitions, ajoute du poids (le plus petit incrément).`,
      `Sinon, ajoute 1 répétition par série chaque semaine.`,
      `Note chaque séance : charge × répétitions. Bats ce chiffre la fois suivante.`,
      `Pas de panique si une semaine stagne : le sommeil et l’alimentation comptent autant que la séance.`,
    ] },

    { type: 'h1', text: 'Erreurs de débutant à éviter' },
    { type: 'list', items: [
      `Charger trop vite : la technique se dégrade et le risque de blessure explose.`,
      `Changer de programme sans arrêt : laisse 8 semaines au programme pour agir.`,
      `Négliger les jambes et le dos au profit des bras/pecs.`,
      `Sauter l’échauffement ou les jours de repos.`,
      `Se comparer aux autres : compare-toi à toi-même la semaine dernière.`,
    ] },
    { type: 'h2', text: 'Problème → solution' },
    { type: 'table', headers: ['Tu rencontres…', 'La solution'], rows: [
      ['Tu ne sais pas quelle charge prendre', 'Choisis un poids où la dernière rép. est dure mais propre'],
      ['Tu as mal aux articulations', 'Allège, revois la technique (scanne la vidéo)'],
      ['Tu ne progresses plus', 'Vérifie sommeil, protéines, et ajoute du repos'],
      ['Courbatures intenses', 'Normal en début ; hydrate-toi, étire-toi, ça passe'],
    ] },

    { type: 'h1', text: 'Rester motivé(e)' },
    { type: 'list', items: [
      `Fixe-toi un objectif de force simple (ex. « 10 pompes propres », « squat à vide maîtrisé puis chargé »).`,
      `Prends une photo et tes mensurations toutes les 4 semaines.`,
      `Bloque tes 3 créneaux dans ton agenda comme des rendez-vous.`,
      `Célèbre chaque petite victoire : un débutant régulier bat un avancé irrégulier.`,
    ] },
    { type: 'h2', text: 'Construis l’habitude' },
    { type: 'list', items: [
      `Prépare ton sac la veille : zéro friction le jour J.`,
      `Règle des 2 minutes : commence juste l’échauffement, le reste suit.`,
      `Ne saute jamais 2 séances de suite.`,
    ] },

    { type: 'h1', text: 'Questions fréquentes' },
    { type: 'h2', text: 'Vais-je devenir « trop musclé(e) » ?' },
    { type: 'p', text: `Non. Construire du muscle est lent et demande des années d’efforts. La musculation te rendra plus tonique, plus fort(e) et en meilleure santé — pas « énorme » par accident.` },
    { type: 'h2', text: 'Cardio ou muscu pour perdre du gras ?' },
    { type: 'p', text: `Les deux, mais la muscu est essentielle : elle préserve/construit le muscle, qui augmente ta dépense au repos. Combine muscu + un peu de marche/cardio + alimentation maîtrisée.` },
    { type: 'h2', text: 'Je peux le faire à la maison ?' },
    { type: 'p', text: `Oui avec une paire d’haltères. Sinon, utilise les variantes au poids du corps (pompes, fentes, squats, gainage, rowing avec sac lesté).` },
    { type: 'h2', text: 'Combien de temps avant de voir des résultats ?' },
    { type: 'p', text: `Force : dès 2-3 semaines. Visuel : 6 à 8 semaines avec une alimentation correcte. Les premiers mois de débutant sont les plus gratifiants.` },
    { type: 'h2', text: 'Faut-il des compléments ?' },
    { type: 'p', text: `Non, pas pour débuter. Si tu veux : whey (atteindre tes protéines) et créatine (3-5 g/jour). Le reste est secondaire.` },
    { type: 'h2', text: 'Combien de jours de repos ?' },
    { type: 'p', text: `Au moins 1 jour entre chaque séance full body, soit le format 3 séances/semaine (ex. lundi/mercredi/vendredi). Le repos n’est pas une perte de temps : c’est là que le muscle se reconstruit.` },
    { type: 'h2', text: 'Que faire si un exercice me fait mal ?' },
    { type: 'p', text: `Distingue la sensation musculaire (normale) de la douleur articulaire ou aiguë (anormale). En cas de douleur, arrête l’exercice, allège, revois la technique (scanne la vidéo) ou remplace-le par une variante. Consulte si ça persiste.` },

    { type: 'h1', text: 'Et après tes 8 semaines ?' },
    { type: 'p', text: `Tu as appris les fondamentaux et gagné en force : il s’agit maintenant de continuer à progresser. Voici tes options.` },
    { type: 'list', items: [
      `Passe au programme Musculation Intermédiaire pour plus de volume et un split plus avancé.`,
      `Si ton objectif est le muscle : enchaîne avec Prise de Masse (léger surplus).`,
      `Si ton objectif est de t’affiner : enchaîne avec Perte de Poids (léger déficit), la muscu acquise t’aidera à garder ton muscle.`,
      `Dans tous les cas : ne t’arrête pas. La régularité sur des mois fait toute la différence.`,
    ] },
    { type: 'note', text: `Refais tes mesures et une photo après ces 8 semaines, et compare à ton point de départ. C’est ta vraie récompense — et ta meilleure motivation pour continuer.` },

    { type: 'h1', text: 'Étirements & mobilité' },
    { type: 'p', text: `5-10 min après chaque séance. Tiens chaque position 20-30 s, sans à-coups.` },
    { type: 'table', headers: ['Étirement', 'Zone', 'Durée'], rows: [
      ['Quadriceps debout', 'Avant de cuisse', '30 s / côté'],
      ['Ischios jambe tendue', 'Arrière de cuisse', '30 s / côté'],
      ['Pectoraux au mur', 'Poitrine, épaules', '30 s / côté'],
      ['Suspension à la barre', 'Dos, épaules', '30 s'],
      ['Chat-vache', 'Colonne', '45 s'],
    ] },

    { type: 'h1', text: 'Sécurité & prévention des blessures' },
    { type: 'p', text: `La musculation est très sûre quand elle est bien faite. La quasi-totalité des blessures de débutant vient de trois causes évitables : ego, technique, et manque d’échauffement.` },
    { type: 'list', items: [
      `Échauffe-toi systématiquement, surtout avant les mouvements lourds.`,
      `Augmente les charges progressivement (petit incrément), jamais d’un coup.`,
      `Garde le dos gainé et neutre sur squat, soulevé de terre et développé militaire.`,
      `Arrête une série si la technique se dégrade : mieux vaut 8 reps propres que 12 bâclées.`,
      `Douleur articulaire vive = stop. Ne « pousse » jamais à travers une vraie douleur.`,
      `Hydrate-toi et dors suffisamment : un corps fatigué se blesse plus facilement.`,
    ] },
    { type: 'note', text: `En cas de doute sur un mouvement, scanne son QR code pour revoir la technique en vidéo avant de charger.` },

    { type: 'h1', text: 'Suivi de ta progression' },
    { type: 'p', text: `Note tes charges chaque séance et tes mesures chaque semaine. Ce qui se mesure se pilote.` },
    { type: 'h2', text: 'Poids & mensurations' },
    { type: 'tracker', columns: ['Date', 'Poids (kg)', 'Bras (cm)', 'Cuisse (cm)', 'Tour de taille (cm)'], rows: 7 },
    { type: 'h2', text: 'Charges (kg) sur les bases' },
    { type: 'tracker', columns: ['Exercice', 'S1', 'S3', 'S5', 'S8'], rows: 6 },

    { type: 'h1', text: 'Checklist hebdomadaire' },
    { type: 'p', text: `Coche chaque case en fin de semaine. Objectif : au moins 5 cases sur 7.` },
    { type: 'checklist', items: [
      `J’ai fait mes 3 séances cette semaine.`,
      `J’ai gardé une technique propre sur tous les exercices.`,
      `J’ai atteint mon objectif de protéines.`,
      `J’ai augmenté une charge ou une répétition.`,
      `J’ai dormi 7 à 9 h la plupart des nuits.`,
      `Je me suis échauffé(e) avant chaque séance.`,
      `J’ai noté mes charges et mes ressentis.`,
    ] },

    { type: 'h1', text: 'Notes personnelles' },
    { type: 'tracker', columns: ['Mes notes, charges et sensations de la semaine'], rows: 16 },

    { type: 'h1', text: 'Glossaire' },
    { type: 'list', items: [
      `Full body : séance qui travaille tout le corps.`,
      `RPE : intensité ressentie /10 (RPE 8 = 2 reps en réserve).`,
      `Surcharge progressive : augmenter charge/reps au fil des semaines.`,
      `Tempo : vitesse d’exécution (ex. 2 s descente, 1 s montée).`,
      `Charnière (hinge) : mouvement de bascule des hanches (soulevé de terre).`,
      `Recomposition : prendre du muscle et perdre du gras en même temps (possible chez le débutant).`,
    ] },

    { type: 'note', text: `8 semaines terminées ? Tu as posé des bases solides. Enchaîne avec le programme Musculation Intermédiaire ou Prise de Masse pour continuer à progresser. Crée ton compte sur xenotif.com.` },
  ],
}
