import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Programme Musculation Avancé (FR). Gabarit premium XENOTIF® (≈30 pages).
export const musculationAvance: Guide = {
  id: 'musculation-avance',
  title: 'Programme Musculation Avancé',
  subtitle: '12 semaines de haute intensité pour franchir un plateau et maximiser le muscle',
  author: 'XENOTIF Coach - Préparation physique certifiée',
  level: 'Avancé',
  duration: '12 semaines · 5 à 6 séances/sem',
  coverImage: 'cover.jpg',
  blocks: [
    { type: 'h1', text: 'Franchis ton plateau' },
    { type: 'p', text: `Tu t’entraînes depuis des années et la progression ralentit ? Ce programme avancé combine volume élevé, intensité maîtrisée, périodisation et techniques d’intensification pour relancer la croissance musculaire et casser les plateaux. C’est exigeant : il s’adresse aux pratiquants confirmés capables de gérer une charge de travail conséquente et leur récupération.` },
    { type: 'p', text: `Chaque exercice possède un QR code vers sa vidéo sur XENOTIF®. À ton niveau, le diable est dans les détails : exécution, tempo, récupération, autorégulation.` },
    { type: 'meta', items: [
      { label: 'Objectif', value: 'Hypertrophie & force max' },
      { label: 'Niveau', value: 'Avancé (2+ ans)' },
      { label: 'Durée', value: '12 semaines (périodisé)' },
      { label: 'Fréquence', value: '5 à 6 séances/sem' },
      { label: 'Matériel', value: 'Salle complète' },
      { label: 'Split', value: 'PPL (Push/Pull/Legs ×2)' },
    ] },
    { type: 'h2', text: 'Objectifs du programme' },
    { type: 'list', items: [
      `Relancer l’hypertrophie après une période de stagnation.`,
      `Augmenter la force sur les mouvements principaux (objectifs chiffrés).`,
      `Maîtriser la périodisation et l’autorégulation (RPE/RIR).`,
      `Améliorer les points faibles via la spécialisation.`,
    ] },
    { type: 'h2', text: 'Es-tu vraiment au niveau avancé ?' },
    { type: 'list', items: [
      `Tu t’entraînes sérieusement depuis 2 ans ou plus.`,
      `Tu maîtrises parfaitement la technique des mouvements composés.`,
      `Tu peux t’entraîner 5 à 6 fois par semaine et bien récupérer.`,
      `Tu sais ce qu’est le RPE/RIR et tu tiens un carnet d’entraînement.`,
      `Sinon, le programme Musculation Intermédiaire est plus adapté.`,
    ] },
    { type: 'note', text: `Règle d’or de l’avancé : tu ne progresses plus « tout seul ». La progression vient de la précision - gestion du volume, de l’intensité, de la fatigue et des points faibles.` },

    { type: 'h1', text: 'Comment ça marche' },
    { type: 'list', items: [
      `Split PPL répété 2× : chaque muscle travaillé 2 fois par semaine.`,
      `Volume élevé : 16 à 22 séries par groupe musculaire et par semaine.`,
      `RIR (répétitions en réserve) : 2-3 RIR en début de bloc, 0-1 en fin de bloc.`,
      `Tempo maîtrisé : excentrique 2-3 s, pause optionnelle, concentrique contrôlé.`,
      `Repos : 2-3 min (composés), 60-90 s (isolation).`,
      `Autorégulation : adapte charge et volume à ta forme du jour (RPE).`,
    ] },
    { type: 'h2', text: 'Techniques d’intensification' },
    { type: 'p', text: `Utilise-les avec précision : 2 à 3 par séance maximum, surtout sur l’isolation et la dernière série des composés.` },
    { type: 'table', headers: ['Technique', 'Principe', 'Application'], rows: [
      ['Drop set', 'Baisser la charge à l’échec, continuer', 'Dernière série d’isolation'],
      ['Rest-pause', 'Mini-pauses 10-20 s pour + de reps', 'Finition'],
      ['Myo-reps', 'Série d’activation + mini-séries', 'Isolation, gain de temps'],
      ['Tempo / excentrique lent', 'Descente 4-5 s', 'Connexion, points faibles'],
      ['Partielles', 'Reps partielles en fin de série', 'Congestion maximale'],
    ] },

    { type: 'h1', text: 'Échauffement & préparation' },
    { type: 'p', text: `À haute intensité, l’échauffement n’est pas optionnel. Ajoute des séries d’approche montantes sur chaque exercice composé lourd.` },
    { type: 'table', headers: ['Étape', 'Détail', 'Durée'], rows: [
      ['Cardio', 'Vélo / rameur', '5 min'],
      ['Mobilité ciblée', 'Articulations du jour', '3-4 min'],
      ['Activation', 'Élastiques, gainage', '2 min'],
      ['Séries d’approche', '40/55/70/85 % du 1er composé', '4 séries'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Volume élevé : la nutrition doit être précise.' },
    { type: 'h1', text: 'Nutrition' },
    { type: 'p', text: `À ce niveau de volume, la précision compte. Calcule tes macros, ajuste-les selon ta progression, et soigne le timing autour de l’entraînement.` },
    { type: 'meta', items: [
      { label: 'Calories', value: 'Surplus +200/+350 (ou recomp)' },
      { label: 'Protéines', value: '2 à 2,4 g par kg' },
      { label: 'Glucides', value: '5 à 7 g/kg les jours d’entraînement' },
      { label: 'Hydratation', value: '3 à 4 L par jour' },
    ] },
    { type: 'h2', text: 'Stratégie' },
    { type: 'list', items: [
      `Protéines réparties sur 4-6 prises (~0,4 g/kg/repas) pour maximiser la synthèse.`,
      `Cyclage glucidique optionnel : plus de glucides les jours lourds (jambes, dos).`,
      `Repas péri-training : glucides + protéines avant ET après les grosses séances.`,
      `Ajuste toutes les 2 semaines selon la moyenne de poids hebdomadaire.`,
    ] },
    { type: 'h2', text: 'Comprendre tes macros' },
    { type: 'table', headers: ['Macro', 'Rôle', 'Cible'], rows: [
      ['Protéines', 'Construction & maintien', '2-2,4 g/kg'],
      ['Glucides', 'Performance & volume', '5-7 g/kg (jours ON)'],
      ['Lipides', 'Hormones', '0,8-1 g/kg'],
    ] },
    { type: 'note', text: `Le surplus reste modéré même chez l’avancé : tu construis du muscle lentement à ce stade, inutile de prendre du gras en excès. +0,2 kg/semaine est un bon repère.` },

    { type: 'h1', text: 'Recettes' },
    { type: 'h2', text: 'Shake intra/péri-training' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protéines', value: '40 g' }] },
    { type: 'list', items: [`1,5 dose de whey`, `1 banane`, `40 g d’avoine`, `300 ml de lait/eau`] },
    { type: 'p', text: `Préparation : mixe. À siroter autour des grosses séances pour soutenir énergie et récupération.` },
    { type: 'h2', text: 'Assiette costaud' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 750 kcal' }, { label: 'Protéines', value: '55 g' }] },
    { type: 'list', items: [`180 g de viande maigre/poisson`, `140 g de riz (cru)`, `Légumes`, `Huile d’olive`] },
    { type: 'p', text: `Préparation : cuis le tout, assemble. Le repas principal des jours d’entraînement.` },
    { type: 'h2', text: 'Collation protéinée dense' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 400 kcal' }, { label: 'Protéines', value: '35 g' }] },
    { type: 'list', items: [`250 g de skyr`, `1 dose de whey`, `Fruits + 30 g d’avoine`, `Beurre de cacahuète`] },
    { type: 'p', text: `Préparation : mélange. Idéal entre deux repas pour atteindre tes calories.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'À haute intensité, la récupération est la priorité n°1.' },
    { type: 'h1', text: 'Récupération & gestion de la fatigue' },
    { type: 'list', items: [
      `Dors 8 à 9 h : c’est le facteur n°1 de récupération à ton volume.`,
      `Deload toutes les 4-5 semaines (volume −50 %, intensité maintenue).`,
      `Surveille les marqueurs de fatigue : sommeil, force, motivation, fréquence cardiaque au repos.`,
      `Sépare les grosses séances (jambes) d’au moins 48 h.`,
      `Gère le stress : il puise dans la même réserve de récupération que l’entraînement.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: 'PPL ×2 : fréquence et volume au service du muscle.' },
    { type: 'h1', text: 'Plan sur 12 semaines (périodisé)' },
    { type: 'p', text: `Trois blocs : accumulation (volume), intensification (charges), réalisation (force/pic), puis deload.` },
    { type: 'table', headers: ['Bloc', 'Semaines', 'Focus', 'RIR'], rows: [
      ['Accumulation', 'S1-S4', 'Volume max tolérable', '2-3 RIR'],
      ['Intensification', 'S5-S8', 'Charges + lourdes', '1-2 RIR'],
      ['Réalisation', 'S9-S11', 'Force & intensité', '0-1 RIR'],
      ['Deload + tests', 'S12', 'Récup. puis tests', 'Léger'],
    ] },
    { type: 'h2', text: 'Semaine type (6 jours, PPL ×2)' },
    { type: 'table', headers: ['Jour', 'Séance'], rows: [
      ['Lundi', 'Push A (force)'],
      ['Mardi', 'Pull A (force)'],
      ['Mercredi', 'Legs A (force)'],
      ['Jeudi', 'Push B (volume)'],
      ['Vendredi', 'Pull B (volume)'],
      ['Samedi', 'Legs B (volume)'],
      ['Dimanche', 'Repos + suivi'],
    ] },

    { type: 'h1', text: 'Tes séances en détail' },
    { type: 'h2', text: 'Push A (force)' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Développé couché', '5', '4 à 6', '180 s'],
      ['Développé militaire', '4', '6 à 8', '150 s'],
      ['Développé incliné haltères', '3', '8 à 10', '120 s'],
      ['Élévations latérales', '4', '12 à 15', '60 s'],
      ['Extension triceps (+ drop set)', '4', '10 à 12', '75 s'],
    ] },
    { type: 'h2', text: 'Pull A (force)' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Soulevé de terre', '4', '3 à 5', '210 s'],
      ['Tractions lestées', '4', '6 à 8', '150 s'],
      ['Rowing barre', '4', '8 à 10', '120 s'],
      ['Face pull', '3', '15', '60 s'],
      ['Curl biceps (+ rest-pause)', '4', '10 à 12', '60 s'],
    ] },
    { type: 'h2', text: 'Legs A (force)' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Squat', '5', '4 à 6', '210 s'],
      ['Presse à cuisses', '4', '10 à 12', '150 s'],
      ['Soulevé de terre roumain', '3', '8 à 10', '120 s'],
      ['Leg curl + leg extension (superset)', '3', '12 à 15', '90 s'],
      ['Mollets (+ partielles)', '4', '12 à 20', '45 s'],
    ] },
    { type: 'p', text: `Les séances B (volume) reprennent les schémas en plus léger : répétitions 10-15, repos plus courts, plus de techniques d’intensification (drop sets, myo-reps). Objectif : volume et congestion.` },
    { type: 'h2', text: 'Push B (volume)' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Développé incliné haltères', '4', '10 à 12', '90 s'],
      ['Développé couché aux haltères', '3', '12', '90 s'],
      ['Développé épaules machine', '4', '12 à 15', '75 s'],
      ['Élévations latérales (+ drop set)', '4', '15 à 20', '45 s'],
      ['Triceps poulie (+ myo-reps)', '4', '12 à 15', '60 s'],
    ] },
    { type: 'h2', text: 'Pull B (volume)' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Tirage vertical', '4', '10 à 12', '90 s'],
      ['Rowing machine / horizontal', '4', '12', '90 s'],
      ['Pull-over poulie', '3', '12 à 15', '75 s'],
      ['Face pull (+ band pull-apart)', '4', '15 à 20', '45 s'],
      ['Curl incliné (+ drop set)', '4', '12 à 15', '60 s'],
    ] },
    { type: 'h2', text: 'Legs B (volume)' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Squat / hack squat', '4', '10 à 12', '120 s'],
      ['Fentes marchées / split squat', '3', '12 / jambe', '90 s'],
      ['Leg extension (+ partielles)', '4', '15', '60 s'],
      ['Leg curl (+ myo-reps)', '4', '15', '60 s'],
      ['Mollets (+ drop set)', '5', '15 à 20', '45 s'],
    ] },

    { type: 'h1', text: 'Bibliothèque d’exercices' },
    { type: 'p', text: `Les mouvements clés. Scanne le QR pour la vidéo de démonstration.` },
    { type: 'exercise', name: 'Squat', muscles: 'Quadriceps, fessiers, ischios, gainage', level: 'Avancé', video: `${D}/musculation`, technique: `Barre haute ou basse selon ton style, descends sous parallèle, dos gainé, genoux dans l’axe, remontée explosive contrôlée. Sécurité (barres) obligatoire en lourd.`, mistakes: `Good morning (bassin qui monte trop vite), genoux qui rentrent, perte de gainage en bas.` },
    { type: 'exercise', name: 'Développé couché', muscles: 'Pectoraux, triceps, épaules', level: 'Avancé', video: `${D}/musculation`, technique: `Pieds ancrés, arche thoracique, omoplates serrées et basses. Touche le bas des pecs, coudes ~45-70°, drive explosif. Parade conseillée en lourd.`, mistakes: `Rebond, coudes flare excessif, fesses qui décollent, trajectoire instable.` },
    { type: 'exercise', name: 'Soulevé de terre', muscles: 'Chaîne postérieure complète', level: 'Avancé', video: `${D}/musculation`, technique: `Barre au-dessus du milieu du pied, gaine fort (Valsalva contrôlée), pousse le sol, barre près du corps, verrouille sans hyperextension.`, mistakes: `Dos arrondi, hanches trop basses au départ, barre qui décolle du corps.` },
    { type: 'exercise', name: 'Développé militaire', muscles: 'Épaules, triceps, gainage', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Debout, fessiers et abdos serrés, pousse à la verticale, tête qui avance légèrement en fin de course, verrouille.`, mistakes: `Cambrure lombaire, poussée vers l’avant, fin de course incomplète.` },
    { type: 'exercise', name: 'Tractions lestées', muscles: 'Grand dorsal, biceps', level: 'Avancé', video: `${D}/musculation`, technique: `Ceinture lestée, pars épaules basses, tire les coudes vers le bas/arrière, menton au-dessus de la barre, descente contrôlée complète.`, mistakes: `Amplitude partielle, kipping non voulu, charge trop lourde qui casse la technique.` },
    { type: 'exercise', name: 'Rowing barre', muscles: 'Dos, biceps, arrière d’épaules', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Buste 30-45°, dos plat, tire vers le bas-ventre, serre les omoplates, contrôle l’excentrique.`, mistakes: `Buste qui se redresse, dos rond, tirer trop haut.` },
    { type: 'exercise', name: 'Presse à cuisses', muscles: 'Quadriceps, fessiers', level: 'Débutant', video: `${D}/musculation`, technique: `Pieds adaptés à la cible, descends sans décoller le bas du dos, amplitude complète, pousse sans verrouiller brutalement.`, mistakes: `Dos qui décolle, amplitude courte, verrouillage sec.` },
    { type: 'exercise', name: 'Soulevé de terre roumain', muscles: 'Ischios, fessiers, dos', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Hanches en arrière, dos plat, étire les ischios, reviens en serrant les fessiers. Excentrique lent pour le gain.`, mistakes: `Dos arrondi, plier les genoux, barre qui s’éloigne.` },
    { type: 'exercise', name: 'Élévations latérales', muscles: 'Deltoïdes latéraux', level: 'Débutant', video: `${D}/musculation`, technique: `Léger, monte à l’horizontale, coudes légèrement fléchis, descente lente. Idéal pour drop sets et myo-reps.`, mistakes: `Trop lourd, élan, monter trop haut.` },
    { type: 'exercise', name: 'Face pull', muscles: 'Arrière d’épaules, rotateurs', level: 'Débutant', video: `${D}/musculation`, technique: `Poulie haute, tire la corde vers le visage, coudes hauts, rotation externe en fin de mouvement. Santé des épaules.`, mistakes: `Trop lourd, coudes qui tombent, tirer avec les bras.` },
    { type: 'exercise', name: 'Curl biceps', muscles: 'Biceps', level: 'Débutant', video: `${D}/musculation`, technique: `Coudes fixes, contraction haute, excentrique lent. Idéal pour rest-pause en finition.`, mistakes: `Élan, coudes qui avancent, amplitude partielle.` },
    { type: 'exercise', name: 'Extension triceps poulie', muscles: 'Triceps', level: 'Débutant', video: `${D}/musculation`, technique: `Coudes collés, étends complètement, contrôle le retour. Garde la tension constante.`, mistakes: `Coudes qui s’écartent, buste qui aide, amplitude courte.` },
    { type: 'exercise', name: 'Développé incliné haltères', muscles: 'Haut des pectoraux, épaules', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Banc ~30°, descente jusqu’à l’étirement, pousse en rapprochant légèrement les haltères. Excellent pour le haut des pecs souvent en retard.`, mistakes: `Banc trop incliné, amplitude courte, coudes verrouillés.` },
    { type: 'exercise', name: 'Split squat bulgare', muscles: 'Quadriceps, fessiers, équilibre', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Pied arrière surélevé sur un banc, descends le bassin à la verticale, genou avant dans l’axe, puis remonte dans le talon avant. Unilatéral, idéal pour corriger les déséquilibres.`, mistakes: `Buste trop penché, genou qui part vers l’intérieur, appui sur la jambe arrière.` },
    { type: 'exercise', name: 'Pull-over poulie', muscles: 'Grand dorsal, pectoraux', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Bras quasi tendus, amène la barre/corde des hanches vers le haut en gardant la tension sur le dos, puis reviens contrôlé. Étire et isole le dorsal.`, mistakes: `Plier les coudes (devient du triceps), amplitude courte, à-coups.` },
    { type: 'exercise', name: 'Hip thrust lesté', muscles: 'Fessiers, ischios', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Haut du dos sur un banc, barre sur les hanches, pousse dans les talons jusqu’à l’alignement, serre fort les fessiers en haut, descente contrôlée.`, mistakes: `Hyperextension lombaire, amplitude incomplète, pieds mal placés.` },

    { type: 'h1', text: 'Spécialisation des points faibles' },
    { type: 'p', text: `À ton niveau, tu peux dédier un bloc à un groupe en retard. Augmente sa fréquence et son volume, réduis légèrement le reste pour ne pas exploser la fatigue.` },
    { type: 'list', items: [
      `Choisis 1 seul point faible par bloc (ex. épaules, dos, mollets).`,
      `Ajoute 4 à 8 séries hebdo sur ce groupe, en 3e séance de fréquence.`,
      `Privilégie l’exécution parfaite et la connexion muscle-cerveau sur l’isolation.`,
      `Réduis de 2-4 séries un groupe « fort » pour compenser.`,
    ] },

    { type: 'h1', text: 'Détail des 12 semaines' },
    { type: 'table', headers: ['Semaine', 'RIR cible', 'Note'], rows: [
      ['S1-S2', '3 RIR', 'Volume haut, technique parfaite'],
      ['S3-S4', '2-3 RIR', '+ charge, bilan S4'],
      ['S5-S6', '2 RIR', 'Intensification, drop sets'],
      ['S7-S8', '1-2 RIR', '+ charge, RPE 8-9'],
      ['S9-S10', '1 RIR', 'Force, repos longs'],
      ['S11', '0-1 RIR', 'Pic d’intensité'],
      ['S12', 'Deload', 'Récup. + tests de force, bilan'],
    ] },

    { type: 'h1', text: 'Casser un plateau' },
    { type: 'list', items: [
      `Vérifie d’abord le sommeil, le stress et les calories : 80 % des plateaux viennent de là.`,
      `Fais un vrai deload : souvent, la fatigue masque les progrès.`,
      `Augmente le volume du groupe stagnant de 20-30 % pendant 3-4 semaines.`,
      `Change l’angle ou la variante d’exercice pour un nouveau stimulus.`,
      `Travaille la qualité d’exécution avant d’ajouter de la charge.`,
    ] },

    { type: 'h1', text: 'Erreurs à éviter' },
    { type: 'list', items: [
      `Empiler les techniques d’intensification : tu génères de la fatigue, pas du muscle.`,
      `Ignorer les deloads : le surentraînement fait reculer.`,
      `Négliger les points faibles ou les rotateurs/épaules (blessures).`,
      `Sous-estimer la nutrition et le sommeil à fort volume.`,
      `Changer de programme avant d’avoir donné 12 semaines au protocole.`,
    ] },
    { type: 'h2', text: 'Problème → solution' },
    { type: 'table', headers: ['Tu rencontres…', 'La solution'], rows: [
      ['Stagnation malgré l’effort', 'Deload, puis +volume ciblé 3-4 sem.'],
      ['Articulations douloureuses', 'Réduis les charges, + face pull/mobilité'],
      ['Fatigue chronique', 'Volume −30 %, +1 jour repos, dors +'],
      ['Force qui chute', 'Signe de surmenage : deload immédiat'],
    ] },

    { type: 'h1', text: 'Rester motivé(e)' },
    { type: 'list', items: [
      `Fixe des objectifs de force chiffrés et des objectifs visuels (point faible).`,
      `Filme tes séries lourdes : analyser ta technique est motivant et utile.`,
      `Photos & mensurations toutes les 4 semaines.`,
      `Rappelle-toi : à ton niveau, les progrès sont lents mais réels. La patience est une compétence.`,
    ] },

    { type: 'h1', text: 'Questions fréquentes' },
    { type: 'h2', text: 'Combien de volume est optimal ?' },
    { type: 'p', text: `16 à 22 séries par groupe et par semaine pour la plupart des avancés. Commence en bas de la fourchette, augmente si tu récupères bien. Plus n’est pas toujours mieux : c’est le volume que tu récupères qui compte.` },
    { type: 'h2', text: 'RIR ou RPE ?' },
    { type: 'p', text: `Deux faces de la même pièce. RIR = répétitions en réserve ; RPE = 10 − RIR. RIR 2 = RPE 8. Utilise celui qui te parle le plus pour autoréguler.` },
    { type: 'h2', text: 'Dois-je m’entraîner jusqu’à l’échec ?' },
    { type: 'p', text: `Rarement sur les composés lourds (risque/fatigue). Plus volontiers sur l’isolation en fin de séance. Le bloc de réalisation (S9-S11) se rapproche de l’échec ; le reste garde du RIR.` },
    { type: 'h2', text: 'Quels compléments à ce niveau ?' },
    { type: 'p', text: `Créatine (3-5 g/jour), whey, caféine pré-training. Éventuellement citrulline (pompe) et électrolytes en grosse séance. Le reste a un effet marginal.` },
    { type: 'h2', text: 'Comment gérer un manque de temps ?' },
    { type: 'p', text: `Passe en PPL 3 jours ou Haut/Bas 4 jours en gardant l’intensité. Mieux vaut 4 séances productives que 6 bâclées par manque de récupération.` },

    { type: 'h1', text: 'Cardio & conditionnement' },
    { type: 'p', text: `Le cardio bien dosé soutient ta récupération (meilleure circulation, capacité de travail) et limite la prise de gras sur les blocs en surplus - sans cannibaliser tes gains si tu respectes ces repères.` },
    { type: 'list', items: [
      `Marche quotidienne (8 000-12 000 pas) : la base, zéro impact sur la récupération.`,
      `2 à 3 séances de cardio modéré (zone 2, 25-35 min) par semaine, à distance des jambes.`,
      `Évite le cardio intense la veille ou le jour des séances lourdes de jambes/dos.`,
      `Sur un bloc de sèche : monte progressivement le cardio plutôt que de couper davantage les calories.`,
    ] },
    { type: 'table', headers: ['Type', 'Durée', 'Fréquence', 'But'], rows: [
      ['Marche (NEAT)', 'Quotidien', 'Tous les jours', 'Dépense, récupération'],
      ['Cardio zone 2', '25-35 min', '2-3×/sem', 'Capacité, santé'],
      ['Intervalle léger', '10-15 min', '1×/sem', 'Conditionnement'],
    ] },

    { type: 'h1', text: 'Mobilité & santé articulaire' },
    { type: 'p', text: `Plus tu charges, plus la mobilité et la santé des articulations comptent. Intègre-les en routine.` },
    { type: 'table', headers: ['Mouvement', 'Cible', 'Dose'], rows: [
      ['Face pull / band pull-apart', 'Épaules (prévention)', '2-3×/sem, 2-3 séries'],
      ['Mobilité hanches/chevilles', 'Squat & soulevé', 'Avant les jambes'],
      ['Étirement pectoraux', 'Épaules', '30 s / côté'],
      ['Suspension à la barre', 'Décompression du dos', '30-45 s'],
    ] },

    { type: 'h1', text: 'Sécurité' },
    { type: 'list', items: [
      `Utilise les barres de sécurité et/ou une parade en squat et développé couché.`,
      `Échauffe-toi avec des séries d’approche montantes sur chaque composé.`,
      `Apprends la manœuvre de Valsalva pour gainer en lourd (sans excès).`,
      `Ne sacrifie jamais la technique pour la charge : c’est la définition même de l’ego-lifting.`,
    ] },

    { type: 'h1', text: 'Et après tes 12 semaines ?' },
    { type: 'p', text: `À ton niveau, la clé du long terme c’est la variation intelligente et la gestion de la fatigue sur l’année.` },
    { type: 'list', items: [
      `Fais un vrai deload (1 semaine) avant de relancer un nouveau bloc.`,
      `Change les variantes d’exercices et l’ordre pour un nouveau stimulus.`,
      `Alterne des blocs orientés hypertrophie et des blocs orientés force sur l’année.`,
      `Dédie le prochain bloc à un point faible identifié pendant ces 12 semaines.`,
      `Selon l’objectif : enchaîne une sèche (Perte de Poids) ou une vraie phase de masse.`,
    ] },
    { type: 'note', text: `Pense « année », pas « 12 semaines ». Les meilleurs physiques se construisent par accumulation de blocs bien menés et de récupération respectée, sur des années.` },

    { type: 'h1', text: 'Bien tenir son carnet d’entraînement' },
    { type: 'p', text: `À l’avancé, ton carnet est l’outil n°1 de progression : il transforme l’entraînement en données pilotables. Sans lui, tu navigues à l’aveugle.` },
    { type: 'list', items: [
      `Note pour chaque exercice : charge × répétitions × séries, et le RIR de la dernière série.`,
      `Note ta forme du jour (énergie /10, sommeil) : ça explique tes bonnes et mauvaises séances.`,
      `Avant chaque série de travail, regarde ta perf précédente : ton objectif est de la battre.`,
      `Relis ton carnet chaque semaine : repère les exercices qui stagnent pour agir.`,
      `Garde une trace de tes deloads et de tes records : motivant et instructif sur le long terme.`,
    ] },
    { type: 'note', text: `« Ce qui se mesure s’améliore. » Deux pratiquants au même potentiel n’auront pas le même physique dans un an : celui qui note et ajuste prendra l’avantage.` },

    { type: 'h1', text: 'Suivi de ta progression' },
    { type: 'p', text: `Note tout : charges, séries, RIR, ressentis. À ton niveau, ton carnet est ton meilleur coach.` },
    { type: 'h2', text: 'Poids & mensurations' },
    { type: 'tracker', columns: ['Date', 'Poids', 'Bras', 'Cuisse', 'Poitrine', 'Taille'], rows: 7 },
    { type: 'h2', text: 'Force max (kg) sur les composés' },
    { type: 'tracker', columns: ['Mouvement', 'S1', 'S4', 'S8', 'S12'], rows: 5 },

    { type: 'h1', text: 'Checklist hebdomadaire' },
    { type: 'checklist', items: [
      `J’ai fait toutes mes séances et atteint mon volume cible.`,
      `J’ai respecté mes RIR cibles par bloc.`,
      `J’ai progressé sur au moins un mouvement clé.`,
      `J’ai atteint mes protéines et mes glucides cibles.`,
      `J’ai dormi 8 à 9 h la plupart des nuits.`,
      `J’ai géré ma fatigue (pas de baisse de force anormale).`,
      `J’ai travaillé mon point faible / ma mobilité.`,
      `J’ai tout noté dans mon carnet.`,
    ] },

    { type: 'h1', text: 'Notes personnelles' },
    { type: 'tracker', columns: ['Mes notes, charges, RIR et sensations de la semaine'], rows: 16 },

    { type: 'h1', text: 'Glossaire' },
    { type: 'list', items: [
      `RIR : répétitions en réserve (RIR 2 = il restait 2 reps).`,
      `Périodisation : organiser l’entraînement en blocs (volume, intensité, pic).`,
      `Accumulation / intensification / réalisation : les 3 phases d’un bloc périodisé.`,
      `Drop set, rest-pause, myo-reps : techniques d’intensification.`,
      `Valsalva : technique de gainage respiratoire pour les charges lourdes.`,
      `Autorégulation : ajuster charge/volume à la forme du jour via le RPE/RIR.`,
      `Deload : semaine de décharge pour dissiper la fatigue.`,
    ] },

    { type: 'note', text: `12 semaines bouclées ? Deload complet, teste tes maxis, prends tes mesures, puis relance un nouveau bloc en variant les exercices, ou enchaîne une phase de sèche/masse selon ton objectif. Crée ton compte sur xenotif.com.` },
  ],
}
