import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Programme Musculation Intermédiaire (FR). Gabarit premium XENOTIF® (≈30 pages).
export const musculationIntermediaire: Guide = {
  id: 'musculation-intermediaire',
  title: 'Programme Musculation Intermédiaire',
  subtitle: '12 semaines pour passer un cap : plus de volume, plus de muscle, plus de force',
  author: 'XENOTIF Coach - Préparation physique certifiée',
  level: 'Intermédiaire',
  duration: '12 semaines · 4 à 5 séances/sem',
  coverImage: 'cover.jpg',
  blocks: [
    { type: 'h1', text: 'Passe au niveau supérieur' },
    { type: 'p', text: `Tu maîtrises les bases et tu cherches à progresser plus vite ? Ce programme intermédiaire de 12 semaines augmente le volume, introduit un split structuré (Push / Pull / Legs ou Haut/Bas) et des techniques d’intensification. Objectif : plus de muscle, plus de force, une silhouette plus dense - sans stagner.` },
    { type: 'p', text: `Chaque exercice possède un QR code vers sa vidéo de démonstration sur XENOTIF®. Note tes charges : à ton niveau, c’est la surcharge progressive précise qui fait la différence.` },
    { type: 'meta', items: [
      { label: 'Objectif', value: 'Hypertrophie & force' },
      { label: 'Niveau', value: 'Intermédiaire (6+ mois)' },
      { label: 'Durée', value: '12 semaines (3 blocs)' },
      { label: 'Fréquence', value: '4 à 5 séances/sem' },
      { label: 'Matériel', value: 'Salle complète recommandée' },
      { label: 'Split', value: 'Push / Pull / Legs' },
    ] },
    { type: 'h2', text: 'Objectifs du programme' },
    { type: 'list', items: [
      `Gagner 2 à 4 kg de muscle sur 12 semaines.`,
      `Augmenter ta force sur les mouvements clés (squat, développé, soulevé de terre, tractions).`,
      `Améliorer la connexion muscle-cerveau et la qualité d’exécution.`,
      `Apprendre à périodiser ton entraînement pour progresser sur le long terme.`,
    ] },
    { type: 'h2', text: 'Es-tu prêt pour ce niveau ?' },
    { type: 'list', items: [
      `Tu t’entraînes régulièrement depuis au moins 6 mois.`,
      `Tu maîtrises la technique des mouvements de base.`,
      `Tu peux t’entraîner 4 à 5 fois par semaine.`,
      `Sinon, commence par le programme Musculation Débutant.`,
    ] },
    { type: 'note', text: `Règle d’or de l’intermédiaire : la progression n’est plus automatique. Tu dois la provoquer - surcharge progressive, volume suffisant, récupération et nutrition au rendez-vous.` },

    { type: 'h1', text: 'Comment ça marche' },
    { type: 'list', items: [
      `Split Push / Pull / Legs : poussée, tirage, jambes - répété 1,5 à 2 fois/semaine.`,
      `Volume : 12 à 20 séries par groupe musculaire et par semaine.`,
      `Séries × répétitions : « 4 × 8 » = 4 séries de 8 répétitions.`,
      `Tempo : 2-3 s en excentrique (descente), explosif en concentrique (montée) contrôlé.`,
      `Repos : 2-3 min sur les gros mouvements, 60-90 s sur l’isolation.`,
      `RPE 8-9 : 1 à 2 répétitions en réserve, la dernière série proche de l’échec.`,
    ] },
    { type: 'h2', text: 'Techniques d’intensification' },
    { type: 'p', text: `Pour continuer à progresser à ton niveau, utilise ces techniques avec parcimonie (1 à 2 par séance, sur les exercices d’isolation).` },
    { type: 'table', headers: ['Technique', 'Principe', 'Quand'], rows: [
      ['Superset', '2 exercices enchaînés sans repos', 'Gagner du temps, congestion'],
      ['Drop set', 'Baisser la charge à l’échec et continuer', 'Dernière série d’isolation'],
      ['Rest-pause', 'Mini-pauses de 10-15 s pour + de reps', 'Finition d’un exercice'],
      ['Tempo lent', 'Excentrique de 3-4 s', 'Connexion & contrôle'],
    ] },

    { type: 'h1', text: 'Échauffement' },
    { type: 'p', text: `Échauffement complet avant chaque séance, plus des séries d’approche sur le premier exercice lourd.` },
    { type: 'table', headers: ['Étape', 'Détail', 'Durée'], rows: [
      ['Cardio', 'Vélo / rameur', '3-5 min'],
      ['Mobilité ciblée', 'Articulations du jour (épaules / hanches)', '3 min'],
      ['Activation', 'Élastique, gainage', '2 min'],
      ['Séries d’approche', '40 %, 60 %, 80 % du 1er exercice', '3-4 séries'],
    ] },

    { type: 'photo', src: 'nutrition.jpg', caption: 'Le volume d’entraînement exige un carburant à la hauteur.' },
    { type: 'h1', text: 'Nutrition' },
    { type: 'p', text: `À ce volume d’entraînement, ta nutrition doit suivre. Léger surplus pour construire, protéines élevées, glucides généreux autour des séances.` },
    { type: 'meta', items: [
      { label: 'Calories', value: 'Maintenance +200/+400 kcal' },
      { label: 'Protéines', value: '1,8 à 2,2 g par kg' },
      { label: 'Glucides', value: '4 à 6 g/kg (énergie)' },
      { label: 'Hydratation', value: '3 L par jour' },
    ] },
    { type: 'h2', text: 'Les règles' },
    { type: 'list', items: [
      `Protéines réparties sur 4-5 prises dans la journée (~0,4 g/kg par repas).`,
      `Glucides avant et après l’entraînement pour la performance et la récupération.`,
      `Lipides de qualité (0,8-1 g/kg) pour les hormones.`,
      `Repas péri-training : protéines + glucides dans les 1-2 h autour de la séance.`,
    ] },
    { type: 'h2', text: 'Comprendre tes macros' },
    { type: 'table', headers: ['Macro', 'Rôle', 'Cible'], rows: [
      ['Protéines', 'Construction musculaire', '1,8-2,2 g/kg'],
      ['Glucides', 'Énergie & volume (glycogène)', '4-6 g/kg'],
      ['Lipides', 'Hormones, santé', '0,8-1 g/kg'],
    ] },
    { type: 'note', text: `Pèse-toi 2-3× par semaine et fais la moyenne hebdo. Vise +0,25 à +0,4 kg/semaine. Au-delà, réduis le surplus pour limiter le gras.` },

    { type: 'h1', text: 'Recettes' },
    { type: 'h2', text: 'Shake péri-training' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 500 kcal' }, { label: 'Protéines', value: '40 g' }] },
    { type: 'list', items: [`1 dose de whey`, `60 g de flocons d’avoine`, `1 banane`, `300 ml de lait`] },
    { type: 'p', text: `Préparation : mixe le tout. Parfait juste après la séance pour relancer la récupération.` },
    { type: 'h2', text: 'Bœuf-riz-légumes' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 700 kcal' }, { label: 'Protéines', value: '50 g' }] },
    { type: 'list', items: [`160 g de bœuf 5%`, `120 g de riz (cru)`, `Légumes`, `Sauce soja, épices`] },
    { type: 'p', text: `Préparation : saisis le bœuf, ajoute les légumes, sers sur le riz. Le repas costaud de la journée.` },
    { type: 'h2', text: 'Skyr protéiné' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 350 kcal' }, { label: 'Protéines', value: '35 g' }] },
    { type: 'list', items: [`250 g de skyr`, `1 dose de whey`, `Fruits rouges`, `Amandes`] },
    { type: 'p', text: `Préparation : mélange skyr et whey, ajoute fruits et amandes. Collation protéinée idéale.` },

    { type: 'photo', src: 'recovery.jpg', caption: 'Plus de volume = plus d’attention à la récupération.' },
    { type: 'h1', text: 'Récupération' },
    { type: 'list', items: [
      `Dors 7 à 9 h : non négociable au volume intermédiaire.`,
      `Laisse 48-72 h à un groupe musculaire avant de le retravailler.`,
      `Deload toutes les 4-6 semaines (volume −40 %) pour éviter le surentraînement.`,
      `Surveille les signes de fatigue excessive : sommeil dégradé, perte de force, irritabilité.`,
    ] },

    { type: 'photo', src: 'training.jpg', caption: 'Push / Pull / Legs : un classique qui fonctionne.' },
    { type: 'h1', text: 'Plan sur 12 semaines (3 blocs)' },
    { type: 'p', text: `Trois blocs progressifs : volume, intensité, force. Garde le même split, fais évoluer répétitions et charges.` },
    { type: 'table', headers: ['Bloc', 'Semaines', 'Focus', 'Répétitions'], rows: [
      ['Bloc 1', 'S1-S4', 'Volume & technique', '10 à 12'],
      ['Bloc 2', 'S5-S8', 'Hypertrophie', '8 à 10'],
      ['Bloc 3', 'S9-S12', 'Force & densité', '5 à 8'],
    ] },
    { type: 'h2', text: 'Semaine type (5 jours)' },
    { type: 'table', headers: ['Jour', 'Séance'], rows: [
      ['Lundi', 'Push (pecs, épaules, triceps)'],
      ['Mardi', 'Pull (dos, biceps)'],
      ['Mercredi', 'Legs (jambes, fessiers)'],
      ['Jeudi', 'Repos / cardio léger'],
      ['Vendredi', 'Upper (haut du corps)'],
      ['Samedi', 'Lower (bas du corps) + abdos'],
      ['Dimanche', 'Repos + suivi'],
    ] },

    { type: 'h1', text: 'Tes séances en détail' },
    { type: 'h2', text: 'Push - Pecs / Épaules / Triceps' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Développé couché', '4', '6 à 8', '150 s'],
      ['Développé incliné haltères', '4', '8 à 10', '120 s'],
      ['Développé militaire', '3', '8 à 10', '120 s'],
      ['Élévations latérales', '4', '12 à 15', '60 s'],
      ['Dips / extension triceps', '3', '10 à 12', '75 s'],
    ] },
    { type: 'h2', text: 'Pull - Dos / Biceps' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Tractions (ou tirage vertical)', '4', '6 à 10', '150 s'],
      ['Rowing barre', '4', '8 à 10', '120 s'],
      ['Tirage horizontal', '3', '10 à 12', '90 s'],
      ['Face pull', '3', '15', '60 s'],
      ['Curl biceps + marteau', '4', '10 à 12', '60 s'],
    ] },
    { type: 'h2', text: 'Legs - Jambes / Fessiers' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Squat', '4', '6 à 8', '180 s'],
      ['Soulevé de terre roumain', '4', '8 à 10', '150 s'],
      ['Presse à cuisses', '3', '12', '120 s'],
      ['Leg curl', '3', '12 à 15', '75 s'],
      ['Mollets', '4', '15 à 20', '45 s'],
    ] },

    { type: 'h1', text: 'Variante 4 jours (Haut / Bas)' },
    { type: 'p', text: `Tu ne peux t’entraîner que 4 fois par semaine ? Remplace le PPL par ce split Haut/Bas (lundi/mardi/jeudi/vendredi). Chaque moitié du corps est travaillée 2× par semaine - excellent pour la fréquence et la récupération.` },
    { type: 'h2', text: 'Haut du corps (A & B)' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Développé couché / incliné', '4', '6 à 10', '150 s'],
      ['Tractions / tirage vertical', '4', '8 à 10', '120 s'],
      ['Développé militaire', '3', '8 à 10', '120 s'],
      ['Rowing barre / horizontal', '3', '10', '90 s'],
      ['Élévations + curl + triceps', '3', '12', '60 s'],
    ] },
    { type: 'h2', text: 'Bas du corps (A & B)' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Squat / presse', '4', '6 à 10', '180 s'],
      ['Soulevé de terre roumain', '4', '8 à 10', '150 s'],
      ['Fentes / leg extension', '3', '12', '90 s'],
      ['Leg curl', '3', '12 à 15', '75 s'],
      ['Mollets + abdos', '4', '15', '45 s'],
    ] },

    { type: 'h1', text: 'Bibliothèque d’exercices' },
    { type: 'p', text: `Les mouvements clés du programme. Scanne le QR pour la vidéo de démonstration.` },
    { type: 'exercise', name: 'Développé couché', muscles: 'Pectoraux, triceps, épaules', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Omoplates serrées, légère cambrure, pieds ancrés. Descends la barre vers le bas des pectoraux, coudes ~45°, puis pousse. Contrôle l’excentrique.`, mistakes: `Coudes trop écartés, rebond sur la poitrine, fesses qui décollent, amplitude partielle.` },
    { type: 'exercise', name: 'Squat', muscles: 'Quadriceps, fessiers, ischios', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Barre sur le haut du dos, descends sous la parallèle si ta mobilité le permet, dos gainé, genoux dans l’axe des pieds, puis remonte explosif.`, mistakes: `Genoux qui rentrent, dos arrondi en bas, talons qui décollent.` },
    { type: 'exercise', name: 'Soulevé de terre', muscles: 'Chaîne postérieure, dos, fessiers', level: 'Avancé', video: `${D}/musculation`, technique: `Barre au-dessus du milieu du pied, dos plat, gaine, pousse le sol avec les jambes en gardant la barre près du corps, verrouille hanches et genoux en haut.`, mistakes: `Dos arrondi, barre qui s’éloigne, tirer avec le bas du dos, hyperextension en haut.` },
    { type: 'exercise', name: 'Tractions', muscles: 'Grand dorsal, biceps', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Prise pronation, pars épaules basses, tire les coudes vers le bas pour amener le menton au-dessus de la barre, puis descends contrôlé.`, mistakes: `Se balancer (kipping non voulu), amplitude partielle, épaules qui montent.` },
    { type: 'exercise', name: 'Rowing barre', muscles: 'Dos, biceps, arrière d’épaules', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Buste ~45°, dos plat, tire la barre vers le bas-ventre en serrant les omoplates, redescends lentement.`, mistakes: `Dos rond, buste qui se redresse, tirer trop haut.` },
    { type: 'exercise', name: 'Développé militaire', muscles: 'Épaules, triceps', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Debout, gainage serré, pousse la barre à la verticale sans cambrer le bas du dos, verrouille en haut.`, mistakes: `Cambrure lombaire, pousser vers l’avant, amplitude incomplète.` },
    { type: 'exercise', name: 'Soulevé de terre roumain', muscles: 'Ischios, fessiers, dos', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Pousse les hanches en arrière, dos plat, descends la barre le long des jambes jusqu’à l’étirement des ischios, puis reviens en serrant les fessiers.`, mistakes: `Dos arrondi, plier les genoux comme un squat, barre qui s’éloigne.` },
    { type: 'exercise', name: 'Presse à cuisses', muscles: 'Quadriceps, fessiers', level: 'Débutant', video: `${D}/musculation`, technique: `Pieds largeur d’épaules sur la plateforme, descends jusqu’à ~90° aux genoux sans décoller le bas du dos, puis pousse sans verrouiller brutalement.`, mistakes: `Dos qui décolle, genoux qui rentrent, amplitude trop courte.` },
    { type: 'exercise', name: 'Élévations latérales', muscles: 'Deltoïdes latéraux', level: 'Débutant', video: `${D}/musculation`, technique: `Haltères légers, monte les bras sur les côtés jusqu’à l’horizontale, coudes légèrement fléchis, descente lente. Léger et propre.`, mistakes: `Trop lourd, balancer, monter au-dessus des épaules.` },
    { type: 'exercise', name: 'Face pull', muscles: 'Arrière d’épaules, trapèzes', level: 'Débutant', video: `${D}/musculation`, technique: `À la poulie haute, tire la corde vers le visage en écartant les mains, coudes hauts, serre les omoplates. Excellent pour la santé des épaules.`, mistakes: `Trop lourd, tirer avec les bras, coudes qui tombent.` },
    { type: 'exercise', name: 'Curl biceps', muscles: 'Biceps', level: 'Débutant', video: `${D}/musculation`, technique: `Coudes fixes le long du corps, monte en contractant, descends lentement (2-3 s). Pas d’élan.`, mistakes: `Se balancer, coudes qui avancent, descente rapide.` },
    { type: 'exercise', name: 'Leg curl', muscles: 'Ischios', level: 'Débutant', video: `${D}/musculation`, technique: `Allongé ou assis selon la machine, fléchis les genoux pour amener le talon vers les fessiers, contracte, puis reviens contrôlé.`, mistakes: `Décoller le bassin, à-coups, amplitude partielle.` },
    { type: 'exercise', name: 'Développé incliné haltères', muscles: 'Haut des pectoraux, épaules', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Banc à ~30°, haltères à hauteur de poitrine, pousse vers le haut en rapprochant légèrement les haltères, descente contrôlée jusqu’à l’étirement.`, mistakes: `Banc trop incliné (devient des épaules), descente trop courte, coudes verrouillés en haut.` },
    { type: 'exercise', name: 'Tirage horizontal', muscles: 'Dos (milieu), biceps', level: 'Débutant', video: `${D}/musculation`, technique: `Assis, dos droit, tire la poignée vers le nombril en serrant les omoplates, sans reculer le buste, puis reviens en gardant la tension.`, mistakes: `Se balancer avec le buste, arrondir le dos, tirer trop haut.` },
    { type: 'exercise', name: 'Dips', muscles: 'Pectoraux bas, triceps', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Aux barres parallèles, corps gainé, descends en pliant les coudes jusqu’à ~90°, légère inclinaison avant pour les pecs, puis pousse pour remonter.`, mistakes: `Descente trop profonde (épaules), à-coups, épaules qui montent.` },
    { type: 'exercise', name: 'Curl marteau', muscles: 'Biceps, brachial, avant-bras', level: 'Débutant', video: `${D}/musculation`, technique: `Haltères en prise neutre (pouces vers le haut), monte en contractant, descente lente. Coudes fixes.`, mistakes: `Se balancer, coudes qui avancent, prise qui tourne.` },

    { type: 'h1', text: 'Abdos & core' },
    { type: 'p', text: `Travaille le tronc 2-3×/semaine en fin de séance. Un core solide améliore tes performances sur tous les gros mouvements et protège ton dos.` },
    { type: 'exercise', name: 'Gainage planche', muscles: 'Sangle abdominale, lombaires', level: 'Débutant', video: `${D}/musculation`, technique: `Avant-bras au sol, corps aligné, abdos et fessiers contractés. Tiens en respirant. Progresse en allongeant la durée ou en ajoutant du lest.`, mistakes: `Bassin qui s’affaisse, fesses hautes, tête relevée.` },
    { type: 'exercise', name: 'Relevé de jambes suspendu', muscles: 'Bas des abdos, gainage', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Suspendu à la barre, monte les genoux (ou jambes tendues) vers la poitrine en enroulant le bassin, puis redescends contrôlé sans balancer.`, mistakes: `Se balancer, monter uniquement les jambes sans enrouler le bassin, descente rapide.` },
    { type: 'list', items: [
      `Circuit core : planche 45 s + relevé de jambes 12 + gainage latéral 30 s/côté, 3 tours.`,
      `Ajoute du lest quand le poids du corps devient facile.`,
    ] },

    { type: 'h1', text: 'Détail des 12 semaines' },
    { type: 'p', text: `Garde le split, fais évoluer répétitions et charges selon le bloc.` },
    { type: 'table', headers: ['Semaine', 'Séries × Reps', 'Note'], rows: [
      ['S1-S2', '4 × 10-12', 'Volume, technique, RPE 7-8'],
      ['S3-S4', '4 × 10', '+ charge, bilan S4'],
      ['S5-S6', '4 × 8-10', 'Hypertrophie, 1 technique d’intensif./séance'],
      ['S7-S8', '4 × 8', '+ charge, RPE 8-9'],
      ['S9-S10', '5 × 6-8', 'Force, repos longs'],
      ['S11', '5 × 5-6', 'Pic d’intensité'],
      ['S12', 'Deload + tests', 'Deload puis tests de force, bilan'],
    ] },

    { type: 'h1', text: 'Progression & périodisation' },
    { type: 'p', text: `À ton niveau, la progression linéaire ne suffit plus : il faut périodiser (alterner volume et intensité) et gérer la fatigue.` },
    { type: 'list', items: [
      `Surcharge progressive : +2,5 kg ou +1 rep dès que tu atteins le haut de la fourchette sur toutes les séries.`,
      `Autorégulation : si tu es en forme, pousse ; si tu es fatigué, garde une rep de plus en réserve.`,
      `Deload obligatoire toutes les 4-6 semaines : volume −40 % une semaine.`,
      `Tiens un carnet : charge × répétitions × séries. C’est ta boussole.`,
    ] },

    { type: 'h1', text: 'Erreurs à éviter' },
    { type: 'list', items: [
      `Trop de volume d’un coup : augmente progressivement, sinon tu accumules la fatigue.`,
      `Abuser des techniques d’intensification : 1-2 par séance suffisent.`,
      `Sauter les jambes ou le tirage horizontal (déséquilibres et blessures).`,
      `Négliger le deload : le surentraînement fait reculer, pas avancer.`,
      `Mauvaise gestion du sommeil/nutrition : tu sabotes ton volume d’entraînement.`,
    ] },
    { type: 'h2', text: 'Problème → solution' },
    { type: 'table', headers: ['Tu rencontres…', 'La solution'], rows: [
      ['Stagnation de force', 'Deload 1 sem., vérifie sommeil & calories'],
      ['Fatigue persistante', 'Réduis le volume, ajoute un jour de repos'],
      ['Douleur d’épaule', 'Plus de face pull, revois l’angle des coudes'],
      ['Prise de gras trop rapide', 'Réduis le surplus, garde les protéines hautes'],
    ] },

    { type: 'h1', text: 'Rester motivé(e)' },
    { type: 'list', items: [
      `Fixe des objectifs de force chiffrés (ex. squat à 1,5× ton poids de corps).`,
      `Photos & mensurations toutes les 4 semaines.`,
      `Varie la musique, entraîne-toi avec un partenaire pour les jours sans envie.`,
      `Garde en tête : 12 semaines de constance valent mieux que 3 mois parfaits puis l’abandon.`,
    ] },
    { type: 'h2', text: 'Construis l’habitude' },
    { type: 'list', items: [
      `Bloque tes 4-5 créneaux comme des rendez-vous non négociables.`,
      `Prépare sac et repas la veille.`,
      `Ne brise jamais la chaîne 2 séances de suite.`,
    ] },

    { type: 'h1', text: 'Questions fréquentes' },
    { type: 'h2', text: 'PPL ou Haut/Bas ?' },
    { type: 'p', text: `Les deux marchent. Le PPL convient si tu peux t’entraîner 5-6×/semaine ; le Haut/Bas si tu vises 4×/semaine. Ce programme combine les deux pour 5 jours. Adapte à ton emploi du temps.` },
    { type: 'h2', text: 'Combien de séries par muscle ?' },
    { type: 'p', text: `12 à 20 séries hebdomadaires par groupe musculaire pour la plupart des intermédiaires. Commence à 12-14 et augmente progressivement si tu récupères bien.` },
    { type: 'h2', text: 'Faut-il aller à l’échec ?' },
    { type: 'p', text: `Garde 1-2 reps en réserve sur la majorité des séries. Réserve l’échec à la dernière série des exercices d’isolation, pas aux mouvements lourds (squat, soulevé de terre).` },
    { type: 'h2', text: 'Quels compléments à ce niveau ?' },
    { type: 'p', text: `Créatine monohydrate (3-5 g/jour) et whey restent les plus utiles. Caféine avant l’entraînement pour la performance. Le reste est accessoire.` },
    { type: 'h2', text: 'Cardio sans perdre de muscle ?' },
    { type: 'p', text: `Oui : 2-3 séances de cardio modéré (20-30 min) par semaine, séparées des séances de jambes si possible. Évite l’excès de cardio intense qui nuit à la récupération.` },

    { type: 'h1', text: 'Conditionnement & cardio' },
    { type: 'p', text: `Un peu de cardio améliore ta récupération entre les séries, ta capacité de travail et garde le gras à distance pendant le surplus - sans nuire à tes gains si tu le dose bien.` },
    { type: 'list', items: [
      `2 à 3 séances de cardio modéré (20-30 min) par semaine, idéalement les jours sans jambes.`,
      `Marche quotidienne (8 000-10 000 pas) : la base, sans impact sur la récupération.`,
      `Option « finisher » : 5-8 min de cardio intense en fin de séance haut du corps.`,
      `Évite les longues sorties intenses la veille des jambes.`,
    ] },
    { type: 'table', headers: ['Type', 'Durée', 'Fréquence', 'Effet'], rows: [
      ['Marche', '30-45 min', 'Quotidien', 'Dépense, récupération'],
      ['Cardio modéré (vélo/rameur)', '20-30 min', '2-3×/sem', 'Santé, capacité'],
      ['Finisher HIIT', '5-8 min', '1-2×/sem', 'Conditionnement'],
    ] },

    { type: 'h1', text: 'Étirements & mobilité' },
    { type: 'p', text: `Travaille la mobilité 2-3×/semaine pour soutenir des amplitudes complètes sous charge.` },
    { type: 'table', headers: ['Mouvement', 'Zone', 'Durée'], rows: [
      ['Mobilité épaules (barre/élastique)', 'Épaules', '1 min'],
      ['Mobilité hanches (fente profonde)', 'Hanches', '30 s / côté'],
      ['Mobilité chevilles', 'Chevilles', '30 s / côté'],
      ['Étirement pectoraux', 'Poitrine', '30 s / côté'],
      ['Suspension à la barre', 'Dos, épaules', '30 s'],
      ['Rotation thoracique', 'Colonne', '45 s'],
    ] },

    { type: 'h1', text: 'Sécurité & prévention' },
    { type: 'list', items: [
      `Échauffe-toi avec des séries d’approche avant chaque mouvement lourd.`,
      `Utilise une parade ou les barres de sécurité au squat et au développé couché.`,
      `Garde une technique parfaite quand tu charges : la blessure vient de l’ego.`,
      `Respecte les deloads et le sommeil : la récupération prévient 90 % des pépins.`,
    ] },

    { type: 'h1', text: 'Et après tes 12 semaines ?' },
    { type: 'p', text: `Tu as gagné en muscle et en force. Pour continuer à progresser, change de stimulus et fixe-toi un nouveau cap.` },
    { type: 'list', items: [
      `Passe au programme Musculation Avancé (techniques et volume plus poussés).`,
      `Objectif muscle : enchaîne une vraie phase de Prise de Masse.`,
      `Objectif définition : passe en Perte de Poids pour révéler le muscle construit.`,
      `Refais tes mesures, tes photos et tes tests de force pour mesurer le chemin parcouru.`,
    ] },
    { type: 'note', text: `Conseil : ne refais pas exactement le même programme à l’identique. Varie les exercices, les angles et les répétitions pour relancer la progression.` },

    { type: 'h1', text: 'Compléments alimentaires' },
    { type: 'p', text: `Aucun n’est obligatoire, mais quelques-uns ont un réel intérêt prouvé à ton niveau d’entraînement.` },
    { type: 'table', headers: ['Complément', 'Intérêt', 'Dose'], rows: [
      ['Créatine monohydrate', 'Force & volume, le + étudié', '3 à 5 g/jour'],
      ['Whey', 'Atteindre ses protéines facilement', '1 à 2 doses/jour'],
      ['Caféine', 'Performance & énergie pré-training', '3 mg/kg, 30-45 min avant'],
      ['Oméga-3 / Vitamine D', 'Récupération, articulations, santé', 'Selon besoins'],
    ] },
    { type: 'note', text: `La base reste l’alimentation et l’entraînement. Les compléments ne sont qu’un petit plus - ne compte jamais sur eux pour compenser un mauvais programme ou un mauvais sommeil.` },

    { type: 'h1', text: 'Suivi de ta progression' },
    { type: 'p', text: `Note tes charges chaque séance et tes mesures chaque semaine.` },
    { type: 'h2', text: 'Poids & mensurations' },
    { type: 'tracker', columns: ['Date', 'Poids (kg)', 'Bras', 'Cuisse', 'Poitrine', 'Taille'], rows: 7 },
    { type: 'h2', text: 'Force sur les mouvements clés (kg × reps)' },
    { type: 'tracker', columns: ['Exercice', 'S1', 'S4', 'S8', 'S12'], rows: 6 },

    { type: 'h1', text: 'Checklist hebdomadaire' },
    { type: 'p', text: `Coche chaque case en fin de semaine. Objectif : au moins 6 sur 8.` },
    { type: 'checklist', items: [
      `J’ai fait toutes mes séances cette semaine.`,
      `J’ai atteint mon volume cible par groupe musculaire.`,
      `J’ai progressé sur au moins un exercice clé.`,
      `J’ai atteint mes protéines chaque jour.`,
      `J’ai mangé en léger surplus contrôlé.`,
      `J’ai dormi 7 à 9 h la plupart des nuits.`,
      `J’ai respecté mes temps de repos.`,
      `J’ai noté toutes mes charges.`,
    ] },

    { type: 'h1', text: 'Notes personnelles' },
    { type: 'tracker', columns: ['Mes notes, charges et sensations de la semaine'], rows: 16 },

    { type: 'h1', text: 'Glossaire' },
    { type: 'list', items: [
      `PPL : Push / Pull / Legs (poussée / tirage / jambes).`,
      `Volume : nombre total de séries par muscle et par semaine.`,
      `Périodisation : organiser l’entraînement en blocs (volume, intensité, force).`,
      `Superset : deux exercices enchaînés sans repos.`,
      `Drop set : baisser la charge à l’échec pour continuer la série.`,
      `Deload : semaine allégée pour récupérer.`,
      `Autorégulation : ajuster l’effort selon ta forme du jour (RPE).`,
    ] },

    { type: 'note', text: `12 semaines bouclées ? Deload, teste ta force, prends tes mesures, puis enchaîne le programme Musculation Avancé ou une phase de Prise de Masse / Perte de Poids selon ton objectif. Crée ton compte sur xenotif.com.` },
  ],
}
