import type { Guide } from '@/lib/boutique/guides'

// d2 - Plan Nutrition Sèche 8 Semaines (FR). Programme NUTRITION (pas muscu) :
// 56 jours de menus, 40+ recettes, listes de courses, macros perso, version vegan.
// Gabarit premium XENOTIF® : couverture food, en-têtes image+titre, ≈30+ pages.
export const nutritionSeche: Guide = {
  id: 'd2',
  title: 'Plan Nutrition Sèche - 8 Semaines',
  subtitle: '56 jours de menus, 40+ recettes, listes de courses, macros perso, version vegan',
  author: 'XENOTIF Coach - Nutrition du sport certifiée',
  level: 'Tous niveaux',
  duration: '8 semaines · 56 jours de menus',
  coverImage: 'seche-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Bienvenue dans ta sèche' },
    { type: 'p', text: `Ce plan de 8 semaines va t’aider à révéler ta définition musculaire en perdant du gras - sans sacrifier le muscle durement gagné, sans régime extrême ni privation absurde. Une méthode progressive, tenable et basée sur la science. Tu y trouveras le calcul de tes besoins, 56 jours de menus détaillés, 40+ recettes, tes listes de courses et une version vegan complète.` },
    { type: 'p', text: `Ce document est ton plan alimentaire de poche : suis les menus jour par jour, prépare tes courses avec les listes fournies, et laisse la définition apparaître semaine après semaine.` },
    { type: 'meta', items: [
      { label: 'Objectif', value: 'Perdre du gras, garder le muscle' },
      { label: 'Niveau', value: 'Tous niveaux' },
      { label: 'Durée', value: '8 semaines (56 jours)' },
      { label: 'Déficit', value: '300 à 500 kcal / jour' },
      { label: 'Protéines', value: '2 à 2,4 g par kg' },
      { label: 'Inclus', value: 'Menus + recettes + courses' },
    ] },
    { type: 'h2', text: 'Ce que tu vas obtenir' },
    { type: 'list', items: [
      `Une perte de gras régulière (0,5 à 0,8 % de ton poids par semaine).`,
      `Le maintien de ta masse musculaire grâce à des protéines élevées.`,
      `56 jours de menus prêts à suivre, équilibrés et savoureux.`,
      `Des automatismes alimentaires que tu garderas après la sèche.`,
    ] },
    { type: 'h2', text: 'Comment utiliser ce plan' },
    { type: 'list', items: [
      `Calcule tes besoins (chapitre « Tes macros personnalisés »).`,
      `Suis les menus semaine par semaine, ou pioche dans les 40+ recettes.`,
      `Fais tes courses avec les listes hebdomadaires fournies.`,
      `Pèse-toi 1 fois/semaine, à jeun, et ajuste si besoin.`,
    ] },
    { type: 'note', text: `La sèche est un marathon, pas un sprint. Une perte régulière de 0,5 à 0,8 % de ton poids par semaine préserve le muscle. Aller plus vite = fondre du muscle et casser le métabolisme.` },

    { type: 'h1', text: 'Le principe de la sèche' },
    { type: 'p', text: `Sécher, c’est perdre de la masse grasse en préservant le muscle. Cela exige trois choses simultanément.` },
    { type: 'list', items: [
      `Un déficit calorique modéré : 15 à 20 % sous ta maintenance, pas plus.`,
      `Des protéines élevées : 2 à 2,4 g par kg pour protéger la masse maigre.`,
      `Le maintien de l’entraînement en force : c’est le signal qui dit au corps de garder le muscle.`,
    ] },
    { type: 'p', text: `Les glucides et lipides comblent le reste de tes calories : ils te donnent l’énergie pour t’entraîner et soutiennent tes hormones. On ne les supprime pas, on les ajuste.` },

    { type: 'chapter', title: 'Tes macros personnalisés', src: 'seche-1.jpg' },
    { type: 'p', text: `Voici comment calculer tes besoins en 3 étapes. Pas besoin de balance de précision : ces repères suffisent pour la grande majorité des cas.` },
    { type: 'h2', text: 'Étape 1 - Ta maintenance' },
    { type: 'p', text: `Estimation rapide : poids (kg) × 30 à 33 (selon ton activité). Exemple pour 75 kg, modérément actif : 75 × 31 ≈ 2 325 kcal/jour de maintenance.` },
    { type: 'h2', text: 'Étape 2 - Ton déficit' },
    { type: 'p', text: `Retire 15 à 20 % : 2 325 − 18 % ≈ 1 900 kcal/jour. C’est ton objectif calorique de sèche.` },
    { type: 'h2', text: 'Étape 3 - Répartir en macros' },
    { type: 'table', headers: ['Macro', 'Calcul', 'Exemple (75 kg, 1 900 kcal)'], rows: [
      ['Protéines', '2,2 g/kg', '165 g (660 kcal)'],
      ['Lipides', '0,8 g/kg', '60 g (540 kcal)'],
      ['Glucides', 'le reste', '175 g (700 kcal)'],
    ] },
    { type: 'h2', text: 'Repères calories selon le poids' },
    { type: 'table', headers: ['Poids', 'Maintenance ≈', 'Sèche ≈', 'Protéines'], rows: [
      ['60 kg', '1 860 kcal', '1 500 kcal', '130 g'],
      ['70 kg', '2 170 kcal', '1 750 kcal', '155 g'],
      ['80 kg', '2 480 kcal', '2 000 kcal', '175 g'],
      ['90 kg', '2 790 kcal', '2 250 kcal', '200 g'],
    ] },
    { type: 'note', text: `Ajuste après 2 semaines : pas de perte → retire 100-150 kcal (glucides du soir). Perte trop rapide (> 1 %/sem) ou perte de force → ajoute 100-150 kcal.` },

    { type: 'h1', text: 'Les règles d’or de la sèche' },
    { type: 'list', items: [
      `Une source de protéines à CHAQUE repas (0,4 g/kg par prise).`,
      `La moitié de l’assiette en légumes : volume, satiété, micronutriments.`,
      `Glucides surtout autour de l’entraînement (énergie + récupération).`,
      `2 à 2,5 L d’eau/jour : un grand verre avant chaque repas (effet satiété).`,
      `Limite le sucre liquide et l’alcool (calories vides qui sabotent le déficit).`,
      `1 repas plaisir par semaine pour tenir sur la durée sans craquer.`,
    ] },

    { type: 'chapter', title: 'Plan de repas - 56 jours', src: 'seche-2.jpg', intro: `Voici 8 semaines de menus prêts à suivre (≈1 800-1 900 kcal, ajuste les portions à TES macros). Chaque semaine alterne les repas pour éviter la lassitude. Toutes les recettes sont détaillées plus loin. Version vegan : voir le chapitre dédié.` },
    { type: 'h2', text: 'Semaine 1' },
    { type: 'table', headers: ['Jour', 'Petit-déj', 'Déjeuner', 'Dîner'], rows: [
      ['Lun', 'Skyr-avoine-fruits', 'Poulet-riz-brocoli', 'Saumon-patate douce-salade'],
      ['Mar', 'Omelette 3 œufs + pain', 'Bœuf maigre-quinoa-légumes', 'Tofu sauté-riz-courgette'],
      ['Mer', 'Skyr-avoine-fruits', 'Wrap poulet-crudités', 'Cabillaud-pommes de terre-haricots'],
      ['Jeu', 'Œufs brouillés + avocat', 'Dinde-riz complet-poivrons', 'Omelette légumes + salade'],
      ['Ven', 'Porridge protéiné', 'Salade pois chiches-thon', 'Poulet-patate douce-épinards'],
      ['Sam', 'Pancakes protéinés', 'Repas plaisir (raisonnable)', 'Soupe + œufs durs + pain'],
      ['Dim', 'Skyr-fruits-amandes', 'Bowl poulet-riz-légumes', 'Poisson blanc-quinoa-salade'],
    ] },
    { type: 'h2', text: 'Semaine 2' },
    { type: 'table', headers: ['Jour', 'Petit-déj', 'Déjeuner', 'Dîner'], rows: [
      ['Lun', 'Omelette + flocons', 'Bœuf-riz-brocoli', 'Tofu-quinoa-légumes verts'],
      ['Mar', 'Skyr-avoine-fruits', 'Poulet-patate douce-salade', 'Cabillaud-riz-courgette'],
      ['Mer', 'Toast avocat-œuf', 'Wrap dinde-crudités', 'Saumon-pommes de terre-haricots'],
      ['Jeu', 'Porridge protéiné', 'Salade quinoa-poulet', 'Omelette légumes + pain complet'],
      ['Ven', 'Pancakes protéinés', 'Poisson-riz complet-épinards', 'Poulet-courgettes-feta'],
      ['Sam', 'Skyr-fruits-amandes', 'Repas plaisir (raisonnable)', 'Soupe + thon + pain'],
      ['Dim', 'Œufs brouillés + avocat', 'Bowl bœuf-riz-légumes', 'Poisson blanc-patate douce-salade'],
    ] },
    { type: 'h2', text: 'Semaine 3' },
    { type: 'table', headers: ['Jour', 'Petit-déj', 'Déjeuner', 'Dîner'], rows: [
      ['Lun', 'Porridge protéiné', 'Poulet-quinoa-courgette', 'Cabillaud-patate douce-haricots'],
      ['Mar', 'Skyr-avoine-fruits', 'Bœuf maigre-riz-brocoli', 'Tofu sauté-riz-poivron'],
      ['Mer', 'Omelette + pain', 'Salade poulet-feta-tomate', 'Saumon-pommes de terre-épinards'],
      ['Jeu', 'Pancakes protéinés', 'Wrap dinde-crudités', 'Omelette légumes + salade'],
      ['Ven', 'Toast avocat-œuf', 'Thon-haricots blancs-tomate', 'Poulet-courgettes-quinoa'],
      ['Sam', 'Skyr-fruits-amandes', 'Repas plaisir (raisonnable)', 'Soupe légumes + œufs durs'],
      ['Dim', 'Œufs brouillés + avocat', 'Bowl poulet-riz-légumes', 'Poisson blanc-patate douce-salade'],
    ] },
    { type: 'h2', text: 'Semaine 4' },
    { type: 'table', headers: ['Jour', 'Petit-déj', 'Déjeuner', 'Dîner'], rows: [
      ['Lun', 'Skyr-avoine-fruits', 'Dinde-riz complet-poivrons', 'Crevettes sautées-riz-courgette'],
      ['Mar', 'Omelette 3 œufs', 'Poulet-patate douce-brocoli', 'Tofu-quinoa-légumes verts'],
      ['Mer', 'Porridge protéiné', 'Salade pois chiches-thon', 'Cabillaud-pommes de terre-haricots'],
      ['Jeu', 'Smoothie épinards-whey-banane', 'Bœuf maigre-quinoa-légumes', 'Omelette légumes + pain'],
      ['Ven', 'Pancakes protéinés', 'Wrap poulet-crudités', 'Saumon-patate douce-salade'],
      ['Sam', 'Skyr-fruits-amandes', 'Repas plaisir (raisonnable)', 'Soupe lentilles-légumes'],
      ['Dim', 'Toast avocat-œuf', 'Bowl bœuf-riz-légumes', 'Poisson blanc-quinoa-épinards'],
    ] },
    { type: 'h2', text: 'Semaine 5' },
    { type: 'table', headers: ['Jour', 'Petit-déj', 'Déjeuner', 'Dîner'], rows: [
      ['Lun', 'Porridge protéiné', 'Poulet-riz-brocoli', 'Tofu sauté-riz-courgette'],
      ['Mar', 'Skyr-avoine-fruits', 'Bœuf maigre-patate douce-salade', 'Cabillaud-quinoa-haricots'],
      ['Mer', 'Omelette + pain', 'Salade quinoa-edamame-tofu', 'Saumon-pommes de terre-épinards'],
      ['Jeu', 'Pancakes protéinés', 'Dinde-riz complet-poivrons', 'Omelette légumes + salade'],
      ['Ven', 'Toast avocat-œuf', 'Wrap poulet-crudités', 'Poulet-courgettes-feta'],
      ['Sam', 'Skyr-fruits-amandes', 'Repas plaisir (raisonnable)', 'Soupe + thon + pain'],
      ['Dim', 'Œufs brouillés + avocat', 'Bowl poulet-riz-légumes', 'Poisson blanc-patate douce-salade'],
    ] },
    { type: 'h2', text: 'Semaine 6' },
    { type: 'table', headers: ['Jour', 'Petit-déj', 'Déjeuner', 'Dîner'], rows: [
      ['Lun', 'Skyr-avoine-fruits', 'Bœuf maigre-riz-brocoli', 'Crevettes-riz-courgette'],
      ['Mar', 'Omelette 3 œufs', 'Poulet-quinoa-légumes', 'Tofu-quinoa-poivron'],
      ['Mer', 'Porridge protéiné', 'Salade poulet-feta-tomate', 'Cabillaud-pommes de terre-haricots'],
      ['Jeu', 'Pancakes protéinés', 'Thon-haricots blancs-tomate', 'Omelette légumes + pain'],
      ['Ven', 'Toast avocat-œuf', 'Dinde-patate douce-épinards', 'Saumon-quinoa-salade'],
      ['Sam', 'Skyr-fruits-amandes', 'Repas plaisir (raisonnable)', 'Soupe légumes + œufs durs'],
      ['Dim', 'Œufs brouillés + avocat', 'Bowl bœuf-riz-légumes', 'Poisson blanc-patate douce-salade'],
    ] },
    { type: 'h2', text: 'Semaine 7' },
    { type: 'table', headers: ['Jour', 'Petit-déj', 'Déjeuner', 'Dîner'], rows: [
      ['Lun', 'Porridge protéiné', 'Poulet-riz-brocoli', 'Tofu sauté-riz-courgette'],
      ['Mar', 'Skyr-avoine-fruits', 'Bœuf maigre-quinoa-légumes', 'Cabillaud-patate douce-haricots'],
      ['Mer', 'Omelette + pain', 'Wrap dinde-crudités', 'Saumon-pommes de terre-épinards'],
      ['Jeu', 'Smoothie épinards-whey-banane', 'Salade pois chiches-thon', 'Omelette légumes + salade'],
      ['Ven', 'Pancakes protéinés', 'Poulet-patate douce-poivrons', 'Crevettes-quinoa-courgette'],
      ['Sam', 'Skyr-fruits-amandes', 'Repas plaisir (raisonnable)', 'Soupe lentilles-légumes'],
      ['Dim', 'Toast avocat-œuf', 'Bowl poulet-riz-légumes', 'Poisson blanc-quinoa-salade'],
    ] },
    { type: 'h2', text: 'Semaine 8 (finition)' },
    { type: 'table', headers: ['Jour', 'Petit-déj', 'Déjeuner', 'Dîner'], rows: [
      ['Lun', 'Skyr-avoine-fruits', 'Poulet-riz-brocoli', 'Cabillaud-patate douce-haricots'],
      ['Mar', 'Omelette 3 œufs', 'Bœuf maigre-quinoa-légumes', 'Tofu-quinoa-poivron'],
      ['Mer', 'Porridge protéiné', 'Salade poulet-feta-tomate', 'Saumon-pommes de terre-épinards'],
      ['Jeu', 'Pancakes protéinés', 'Dinde-riz complet-légumes', 'Omelette légumes + salade'],
      ['Ven', 'Toast avocat-œuf', 'Thon-haricots blancs-tomate', 'Poulet-courgettes-quinoa'],
      ['Sam', 'Skyr-fruits-amandes', 'Repas plaisir léger', 'Soupe + œufs durs'],
      ['Dim', 'Œufs brouillés + avocat', 'Bowl poulet-riz-légumes', 'Poisson blanc-patate douce-salade'],
    ] },
    { type: 'note', text: `Astuce : tu peux garder le même petit-déjeuner 2-3 jours d’affilée pour simplifier - la variété compte sur la semaine. Ajuste toujours les PORTIONS à TES macros (chapitre précédent).` },

    { type: 'chapter', title: 'Tes listes de courses', src: 'seche-1.jpg', intro: `Fais tes courses 1 à 2 fois par semaine avec ces listes. Acheter les bons aliments = manger correctement sans réfléchir.` },
    { type: 'h2', text: 'Protéines' },
    { type: 'list', items: [`Poulet, dinde, bœuf maigre 5%`, `Poisson blanc, saumon, thon`, `Œufs, skyr, fromage blanc 0%`, `Tofu, tempeh, légumineuses`, `Whey (option)`] },
    { type: 'h2', text: 'Glucides & féculents' },
    { type: 'list', items: [`Riz, quinoa, pâtes complètes`, `Patate douce, pommes de terre`, `Flocons d’avoine, pain complet`, `Fruits (banane, pomme, fruits rouges)`] },
    { type: 'h2', text: 'Légumes & lipides' },
    { type: 'list', items: [`Brocoli, courgette, épinards, haricots verts, poivron, salade, tomate`, `Huile d’olive, avocat, amandes, noix`, `Citron, ail, herbes, épices (à volonté)`] },

    { type: 'chapter', title: 'Recettes - Petits-déjeuners', src: 'seche-2.jpg' },
    { type: 'h2', text: '1. Skyr-avoine-fruits rouges' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 350 kcal' }, { label: 'Protéines', value: '30 g' }] },
    { type: 'list', items: [`200 g de skyr`, `40 g de flocons d’avoine`, `1 poignée de fruits rouges`] },
    { type: 'p', text: `Mélange skyr et flocons, laisse reposer 5 min, ajoute les fruits.` },
    { type: 'h2', text: '2. Omelette protéinée' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 320 kcal' }, { label: 'Protéines', value: '28 g' }] },
    { type: 'list', items: [`3 œufs`, `Épinards, tomate`, `1 tranche de pain complet`] },
    { type: 'p', text: `Bats les œufs, cuis avec les légumes à feu doux, sers avec le pain.` },
    { type: 'h2', text: '3. Porridge protéiné' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 380 kcal' }, { label: 'Protéines', value: '32 g' }] },
    { type: 'list', items: [`50 g de flocons d’avoine`, `250 ml de lait`, `1 dose de whey`, `Cannelle`] },
    { type: 'p', text: `Chauffe les flocons dans le lait 3 min, hors du feu ajoute la whey et la cannelle.` },
    { type: 'h2', text: '4. Pancakes protéinés' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 360 kcal' }, { label: 'Protéines', value: '30 g' }] },
    { type: 'list', items: [`1 banane`, `2 œufs`, `40 g de flocons d’avoine`, `1/2 dose de whey`] },
    { type: 'p', text: `Mixe le tout, cuis de petites galettes à la poêle. Garnis de fruits.` },
    { type: 'h2', text: '5. Toast avocat-œuf' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 380 kcal' }, { label: 'Protéines', value: '22 g' }] },
    { type: 'list', items: [`2 tranches de pain complet`, `1/2 avocat`, `2 œufs`, `Citron, poivre`] },
    { type: 'p', text: `Écrase l’avocat sur le pain, ajoute les œufs (au plat ou pochés).` },

    { type: 'h1', text: 'Recettes - Déjeuners' },
    { type: 'h2', text: '6. Bowl poulet-riz-légumes' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 480 kcal' }, { label: 'Protéines', value: '42 g' }] },
    { type: 'list', items: [`130 g de poulet`, `100 g de riz (cru)`, `Légumes`, `Sauce soja`] },
    { type: 'p', text: `Cuis le riz, saisis le poulet et les légumes, assemble.` },
    { type: 'h2', text: '7. Wrap poulet-crudités' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protéines', value: '38 g' }] },
    { type: 'list', items: [`1 galette complète`, `120 g de poulet`, `Crudités`, `Fromage blanc + moutarde`] },
    { type: 'p', text: `Tartine, garnis, roule serré.` },
    { type: 'h2', text: '8. Salade pois chiches-thon' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protéines', value: '35 g' }] },
    { type: 'list', items: [`1 boîte de pois chiches`, `1 boîte de thon`, `Tomates, oignon`, `Citron, huile d’olive`] },
    { type: 'p', text: `Mélange le tout. Rapide, sans cuisson.` },
    { type: 'h2', text: '9. Bœuf maigre-quinoa' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 520 kcal' }, { label: 'Protéines', value: '45 g' }] },
    { type: 'list', items: [`140 g de bœuf 5%`, `80 g de quinoa (cru)`, `Légumes verts`, `Épices`] },
    { type: 'p', text: `Saisis le bœuf, sers sur le quinoa avec les légumes.` },

    { type: 'h1', text: 'Recettes - Dîners' },
    { type: 'h2', text: '10. Saumon-patate douce-salade' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 500 kcal' }, { label: 'Protéines', value: '38 g' }] },
    { type: 'list', items: [`130 g de saumon`, `200 g de patate douce`, `Salade verte`, `Huile d’olive, citron`] },
    { type: 'p', text: `Cuis le saumon et la patate douce au four, sers avec la salade.` },
    { type: 'h2', text: '11. Cabillaud-pommes de terre-haricots' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 430 kcal' }, { label: 'Protéines', value: '40 g' }] },
    { type: 'list', items: [`160 g de cabillaud`, `200 g de pommes de terre`, `Haricots verts`, `Herbes`] },
    { type: 'p', text: `Cuis le tout à la vapeur ou au four, assaisonne.` },
    { type: 'h2', text: '12. Tofu sauté-riz-courgette' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 450 kcal' }, { label: 'Protéines', value: '28 g' }] },
    { type: 'list', items: [`150 g de tofu ferme`, `80 g de riz (cru)`, `Courgette`, `Sauce soja, gingembre`] },
    { type: 'p', text: `Saisis le tofu, ajoute la courgette, sers sur le riz.` },
    { type: 'h2', text: '13. Omelette légumes du soir' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 320 kcal' }, { label: 'Protéines', value: '28 g' }] },
    { type: 'list', items: [`3 œufs`, `Épinards, poivron`, `Salade verte`] },
    { type: 'p', text: `Fais revenir les légumes, verse les œufs, accompagne d’une salade.` },

    { type: 'h1', text: 'Recettes - Collations' },
    { type: 'h2', text: '14. Skyr protéiné' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 220 kcal' }, { label: 'Protéines', value: '28 g' }] },
    { type: 'list', items: [`250 g de skyr`, `Fruits rouges`, `Cannelle`] },
    { type: 'p', text: `Mélange. Parfait entre deux repas ou après l’entraînement.` },
    { type: 'h2', text: '15. Shake protéiné' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 200 kcal' }, { label: 'Protéines', value: '25 g' }] },
    { type: 'list', items: [`1 dose de whey`, `250 ml d’eau ou lait écrémé`, `Glaçons`] },
    { type: 'p', text: `Mixe ou secoue. Pratique au bureau.` },
    { type: 'h2', text: '16. Œufs durs + crudités' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 180 kcal' }, { label: 'Protéines', value: '16 g' }] },
    { type: 'list', items: [`2 œufs durs`, `Bâtonnets de carotte/concombre`, `Sel, poivre`] },
    { type: 'p', text: `Cuis les œufs 9 min, sers avec les crudités.` },
    { type: 'h2', text: '17. Cottage cheese-ananas' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 200 kcal' }, { label: 'Protéines', value: '24 g' }] },
    { type: 'list', items: [`200 g de cottage cheese`, `100 g d’ananas`, `Cannelle`] },
    { type: 'p', text: `Mélange. Collation sucrée-salée très protéinée et peu calorique.` },
    { type: 'h2', text: '18. Crevettes sautées-riz-courgette' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 430 kcal' }, { label: 'Protéines', value: '38 g' }] },
    { type: 'list', items: [`150 g de crevettes`, `80 g de riz (cru)`, `Courgette, ail`, `Sauce soja`] },
    { type: 'p', text: `Saisis les crevettes à l’ail, ajoute la courgette, sers sur le riz.` },
    { type: 'h2', text: '19. Soupe lentilles-légumes' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 350 kcal' }, { label: 'Protéines', value: '22 g' }] },
    { type: 'list', items: [`100 g de lentilles (cru)`, `Carotte, oignon, tomate`, `Cumin, bouillon`] },
    { type: 'p', text: `Fais mijoter 25 min. Rassasiante, riche en fibres, parfaite le soir.` },
    { type: 'h2', text: '24 recettes express bonus' },
    { type: 'p', text: `Pioche aussi dans ces idées rapides (compose avec tes macros) - de quoi ne jamais tourner en rond :` },
    { type: 'table', headers: ['Recette', 'Type', 'Protéines'], rows: [
      ['Poulet-avocat sur galette', 'Déjeuner', '35 g'],
      ['Dinde grillée-courgettes', 'Dîner', '40 g'],
      ['Bowl quinoa-edamame-tofu', 'Déjeuner', '30 g'],
      ['Yaourt grec-noix-miel', 'Collation', '18 g'],
      ['Galette flocons-blanc d’œuf', 'Petit-déj', '24 g'],
      ['Œufs cocotte-épinards', 'Petit-déj', '20 g'],
      ['Salade thon-haricots verts-œuf', 'Déjeuner', '36 g'],
      ['Poêlée dinde-poivrons-riz', 'Déjeuner', '40 g'],
      ['Cabillaud en papillote-légumes', 'Dîner', '38 g'],
      ['Chili sin carne (tofu/haricots)', 'Dîner', '28 g'],
      ['Fromage blanc-fruits rouges-graines', 'Collation', '22 g'],
      ['Wrap saumon fumé-fromage frais', 'Déjeuner', '30 g'],
      ['Buddha bowl légumes-pois chiches', 'Déjeuner', '24 g'],
      ['Steak haché 5%-haricots verts', 'Dîner', '40 g'],
      ['Tortilla œufs-pommes de terre', 'Petit-déj', '26 g'],
      ['Smoothie protéiné fruits rouges', 'Collation', '28 g'],
      ['Poulet teriyaki-brocoli-riz', 'Déjeuner', '42 g'],
      ['Salade lentilles-feta-tomate', 'Déjeuner', '24 g'],
      ['Curry de pois chiches-épinards', 'Dîner', '22 g'],
      ['Blanc de dinde-crudités', 'Collation', '25 g'],
      ['Riz sauté œuf-légumes-edamame', 'Déjeuner', '26 g'],
      ['Cabillaud-purée patate douce', 'Dîner', '38 g'],
      ['Skyr-granola maison-fruits', 'Petit-déj', '28 g'],
      ['Soupe miso-tofu-légumes', 'Dîner', '20 g'],
    ] },
    { type: 'note', text: `Au total, plus de 40 recettes : combine-les librement avec les menus pour 8 semaines sans jamais te lasser.` },

    { type: 'chapter', title: 'Batch cooking & organisation', src: 'seche-2.jpg', intro: `Le secret d’une sèche réussie : ne jamais être pris au dépourvu. Cuisine 2 fois par semaine en grande quantité - tu manges mieux et tu ne craques pas sur le premier plat rapide.` },
    { type: 'list', items: [
      `Dimanche & mercredi : cuis 1 kg de protéines (poulet, bœuf, tofu) + 500 g de féculents (riz, quinoa).`,
      `Découpe et lave tes légumes à l’avance, stocke en boîtes.`,
      `Prépare 4-5 portions identiques, varie juste l’assaisonnement (sauce soja, citron, épices).`,
      `Garde toujours des œufs durs et du skyr au frigo pour les fringales.`,
      `Investis dans 4-5 boîtes hermétiques : c’est l’outil n°1 de la sèche.`,
    ] },

    { type: 'chapter', title: 'Version vegan', src: 'seche-1.jpg', intro: `La sèche fonctionne parfaitement en vegan : il suffit de viser des protéines végétales variées et complètes. Remplace simplement les protéines animales par leurs équivalents.` },
    { type: 'table', headers: ['Au lieu de…', 'Utilise…', 'Protéines'], rows: [
      ['Poulet / bœuf', 'Tofu ferme, tempeh, seitan', '15-25 g/100 g'],
      ['Œufs', 'Tofu brouillé, pois chiches', '8-19 g'],
      ['Skyr / fromage blanc', 'Yaourt de soja nature', '6-10 g'],
      ['Whey', 'Protéine de pois / riz', '20-25 g/dose'],
      ['Thon / poisson', 'Pois chiches, lentilles, edamame', '9-20 g'],
    ] },
    { type: 'list', items: [
      `Vise la variété : combine céréales + légumineuses pour des protéines complètes.`,
      `Complète en B12 (indispensable en vegan) et surveille le fer.`,
      `Les légumineuses apportent aussi des fibres rassasiantes - idéal en sèche.`,
    ] },

    { type: 'h1', text: 'Conseils pour réussir' },
    { type: 'list', items: [
      `Prépare tes repas à l’avance (batch cooking) 2 fois/semaine.`,
      `Bois un grand verre d’eau dès une fringale : on confond souvent soif et faim.`,
      `Garde des en-cas protéinés sous la main (skyr, œuf dur, blanc de dinde).`,
      `Dors 7-8 h : le manque de sommeil augmente la faim et freine la perte de gras.`,
      `Continue la musculation : c’est elle qui préserve ton muscle pendant le déficit.`,
    ] },

    { type: 'h1', text: 'Erreurs à éviter' },
    { type: 'list', items: [
      `Déficit trop agressif : tu perds du muscle, ton énergie chute, tu craques.`,
      `Zapper les protéines : la priorité n°1 en sèche.`,
      `Supprimer totalement les glucides : tu perds en énergie et en performance.`,
      `Te peser tous les jours : le poids fluctue, regarde la tendance sur 2 semaines.`,
      `Oublier l’alcool et les sauces : des calories cachées qui bloquent le déficit.`,
    ] },
    { type: 'h2', text: 'Problème → solution' },
    { type: 'table', headers: ['Tu rencontres…', 'La solution'], rows: [
      ['La balance stagne 2 sem.', 'Retire 100-150 kcal (glucides du soir)'],
      ['Faim constante', 'Plus de protéines + légumes + eau'],
      ['Manque d’énergie', 'Garde des glucides autour de l’entraînement'],
      ['Envie de sucre le soir', 'Skyr + fruits rouges, ou repas plaisir planifié'],
    ] },

    { type: 'h1', text: 'Questions fréquentes' },
    { type: 'h2', text: 'Combien de temps pour voir des résultats ?' },
    { type: 'p', text: `Dès 2-3 semaines pour les premiers changements (dont une part d’eau la 1re semaine). La définition visible arrive entre 4 et 8 semaines selon ton point de départ.` },
    { type: 'h2', text: 'Dois-je compter mes calories ?' },
    { type: 'p', text: `Au début, c’est utile pour calibrer. Ensuite, les menus et les repères de portions suffisent. L’important est la régularité du déficit sur la semaine.` },
    { type: 'h2', text: 'Puis-je suivre ce plan sans m’entraîner ?' },
    { type: 'p', text: `Tu perdras du poids, mais une partie sera du muscle. Pour une vraie sèche (perdre du gras en gardant la forme), garde au moins 2-3 séances de renforcement par semaine.` },
    { type: 'h2', text: 'Le repas plaisir va-t-il tout gâcher ?' },
    { type: 'p', text: `Non : 1 repas sur 21 reste un déficit hebdomadaire. Il préserve ta motivation et ta vie sociale - les vrais facteurs d’abandon.` },
    { type: 'h2', text: 'Et après les 8 semaines ?' },
    { type: 'p', text: `Remonte tes calories progressivement vers ta maintenance (+100 kcal/sem) pour éviter l’effet yo-yo, puis stabilise ou enchaîne une phase de prise de masse.` },

    { type: 'h1', text: 'Manger dehors & gérer les imprévus' },
    { type: 'p', text: `La sèche ne doit pas t’empêcher de vivre. Avec quelques réflexes, tu restes dans tes objectifs même au restaurant ou en déplacement.` },
    { type: 'list', items: [
      `Au resto : choisis une protéine maigre (viande grillée, poisson) + légumes, sauce à part.`,
      `Évite l’apéritif liquide (alcool, sodas) : remplace par de l’eau pétillante au citron.`,
      `Fast-food : opte pour les options grillées, salade, et saute les frites/sauces sucrées.`,
      `En déplacement : garde des barres protéinées, du skyr ou des œufs durs sur toi.`,
      `Une journée « hors plan » ne casse rien : reprends simplement au repas suivant.`,
    ] },
    { type: 'table', headers: ['Situation', 'Bon réflexe'], rows: [
      ['Restaurant', 'Protéine grillée + légumes, sauce à part'],
      ['Pizza/burger', 'Version simple, pas de menu XL, eau'],
      ['Apéro', 'Crudités, eau pétillante, 1 verre max'],
      ['Brunch', 'Œufs, fromage blanc, fruits, pain complet'],
    ] },

    { type: 'h1', text: 'Compléments utiles en sèche' },
    { type: 'p', text: `Aucun n’est obligatoire - l’alimentation passe avant tout. Mais certains aident à tenir le déficit et préserver le muscle.` },
    { type: 'table', headers: ['Complément', 'Intérêt en sèche', 'Dose'], rows: [
      ['Whey / iso', 'Atteindre ses protéines à peu de calories', '1 à 2 doses/jour'],
      ['Créatine', 'Maintien de la force pendant le déficit', '3 à 5 g/jour'],
      ['Café / caféine', 'Coupe-faim et énergie', 'Avec modération'],
      ['Psyllium / fibres', 'Satiété et transit', 'Selon besoins'],
      ['Multivitamines', 'Combler les éventuelles carences', '1/jour (option)'],
    ] },
    { type: 'note', text: `Méfie-toi des « brûleurs de graisse » miracles : aucun ne remplace le déficit calorique. Économise ton argent pour de bons aliments.` },

    { type: 'h1', text: 'Suivi de ta sèche' },
    { type: 'p', text: `Mesure-toi chaque semaine, à jeun, dans les mêmes conditions. La photo et le tour de taille sont souvent plus parlants que la balance.` },
    { type: 'h2', text: 'Poids & mensurations' },
    { type: 'tracker', columns: ['Date', 'Poids (kg)', 'Tour de taille (cm)', 'Énergie /10'], rows: 9 },
    { type: 'h2', text: 'Apports (optionnel)' },
    { type: 'tracker', columns: ['Date', 'Calories', 'Protéines (g)', 'Eau (L)'], rows: 7 },

    { type: 'h1', text: 'Checklist hebdomadaire' },
    { type: 'p', text: `Coche chaque case en fin de semaine. Objectif : au moins 6 sur 8.` },
    { type: 'checklist', items: [
      `J’ai respecté mon déficit calorique la plupart des jours.`,
      `J’ai atteint mes protéines chaque jour.`,
      `J’ai mangé des légumes à chaque repas principal.`,
      `J’ai bu 2 L d’eau par jour.`,
      `J’ai limité le sucre liquide et l’alcool.`,
      `J’ai gardé mes séances de renforcement.`,
      `Je me suis pesé(e) 1 fois, dans les mêmes conditions.`,
      `J’ai préparé mes repas à l’avance.`,
    ] },

    { type: 'h1', text: 'Notes personnelles' },
    { type: 'tracker', columns: ['Mes repas préférés, ressentis et ajustements de la semaine'], rows: 16 },

    { type: 'note', text: `8 semaines de sèche terminées ? Remonte tes calories en douceur, garde tes bonnes habitudes, puis enchaîne une prise de masse propre ou un maintien. Crée ton compte sur xenotif.com pour ton suivi et ton coach IA.` },
  ],
}
