import type { Guide } from '@/lib/boutique/guides'

const D = 'https://xenotif.com/disciplines'

// Programme Prise de Masse - 12 semaines (FR). Gabarit premium XENOTIF® :
// couverture photo, photos de section, QR vidéo par exercice, plan nutrition,
// calendrier, séances détaillées, suivi. ≈ 30 pages.
export const priseDeMasse12s: Guide = {
  id: 'd1',
  title: 'Programme Prise de Masse - 12 Semaines',
  subtitle: 'Split 4 jours/semaine, progression de charge guidée, plan nutrition + macros',
  author: 'XENOTIF Coach - Préparation physique & nutrition certifiées',
  level: 'Débutant - Intermédiaire',
  duration: '12 semaines · 4 séances/sem · 84 séances',
  coverImage: 'masse-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Bienvenue dans ta prise de masse' },
    { type: 'p', text: `12 semaines pour transformer ton physique : plus de muscle, plus de force, une silhouette plus dense. Pas de prise de masse « sale » qui te fait gonfler de gras - ici, on construit du muscle de qualité grâce à trois leviers : un léger surplus calorique, une surcharge progressive à l’entraînement, et une récupération soignée.` },
    { type: 'p', text: `Garde ce guide sur ton téléphone : chaque exercice a un QR code qui ouvre sa vidéo de démonstration sur XENOTIF®. Suis le plan, note tes charges, mange suffisamment - et le muscle suivra.` },
    { type: 'meta', items: [
      { label: 'Objectif', value: 'Prendre 2 à 5 kg de muscle' },
      { label: 'Niveau', value: 'Débutant à intermédiaire' },
      { label: 'Durée', value: '12 semaines (3 phases)' },
      { label: 'Fréquence', value: '4 séances par semaine' },
      { label: 'Matériel', value: 'Salle ou haltères + barre' },
      { label: 'Split', value: 'Haut / Bas (4 jours)' },
    ] },
    { type: 'h2', text: 'Objectifs du programme' },
    { type: 'list', items: [
      `Construire 2 à 5 kg de muscle sur 12 semaines (selon ton profil de départ).`,
      `Gagner nettement en force sur les mouvements de base.`,
      `Améliorer ta posture et densifier ta silhouette.`,
      `Apprendre une méthode d’entraînement et de nutrition que tu garderas à vie.`,
    ] },
    { type: 'h2', text: 'Comment utiliser ce guide' },
    { type: 'list', items: [
      `Lis le guide en entier avant de commencer, puis suis le calendrier des 12 semaines.`,
      `Note tes charges à chaque séance : la progression se pilote, elle ne s’improvise pas.`,
      `Échauffe-toi 5-10 min avant chaque séance (page dédiée).`,
      `Scanne le QR d’un exercice pour revoir la technique en vidéo.`,
      `Pèse-toi 1 fois/semaine et remplis ton suivi le dimanche.`,
    ] },
    { type: 'note', text: `Règle d’or : pas de muscle sans surplus calorique ET sans surcharge progressive. Manger plus sans t’entraîner dur = du gras. T’entraîner dur sans manger assez = pas de progrès. Les deux ensemble = du muscle.` },

    { type: 'h1', text: 'Comment ça marche' },
    { type: 'list', items: [
      `Surplus calorique modéré : mange 200 à 400 kcal au-dessus de ta maintenance.`,
      `Surcharge progressive : augmente charge ou répétitions presque chaque semaine.`,
      `Séries × répétitions : « 4 × 8 » = 4 séries de 8 répétitions.`,
      `Tempo : 2 s en phase descendante (excentrique), 1 s en phase montante.`,
      `Repos : 90 à 120 s sur les gros mouvements, 60 s sur l’isolation.`,
      `RPE 8 : garde ~2 répétitions en réserve, sauf indication contraire.`,
    ] },
    { type: 'h2', text: 'La surcharge progressive, expliquée' },
    { type: 'p', text: `Le muscle grossit quand on lui demande plus que ce à quoi il est habitué. Concrètement : chaque semaine, vise +1 à 2 répétitions par série, ou +2,5 kg quand tu atteins le haut de la fourchette de répétitions. Tiens un carnet : c’est le seul moyen de battre tes performances de la semaine précédente.` },

    { type: 'h1', text: 'Échauffement & mobilité' },
    { type: 'p', text: `Un bon échauffement augmente tes performances et protège tes articulations sous charge. Ne le saute jamais, surtout avant les mouvements lourds.` },
    { type: 'h2', text: 'Échauffement type (8 minutes)' },
    { type: 'table', headers: ['Étape', 'Détail', 'Durée'], rows: [
      ['Cardio léger', 'Vélo / corde / marche rapide', '3 min'],
      ['Mobilité', 'Épaules, hanches, chevilles', '2 min'],
      ['Activation', 'Gainage + élastique (dos/épaules)', '2 min'],
      ['Séries d’approche', '2 séries légères du 1er exercice', '1 min'],
    ] },

    { type: 'chapter', title: 'Plan nutrition prise de masse', src: 'seche-1.jpg' },
    { type: 'p', text: `Le muscle se construit avec un surplus calorique modéré et beaucoup de protéines. L’objectif : prendre du muscle en limitant le gras. Mieux vaut +0,25 kg/semaine propre que +1 kg sale.` },
    { type: 'meta', items: [
      { label: 'Surplus visé', value: '200 à 400 kcal / jour' },
      { label: 'Protéines', value: '1,8 à 2,2 g par kg' },
      { label: 'Glucides', value: 'Élevés (énergie & volume)' },
      { label: 'Prise de poids', value: '0,2 à 0,4 kg / semaine' },
    ] },
    { type: 'h2', text: 'Les 5 règles d’or' },
    { type: 'list', items: [
      `Protéines à chaque repas (1,8-2,2 g/kg/jour) : c’est la brique du muscle.`,
      `Glucides généreux autour de l’entraînement (riz, pâtes, patate douce, avoine).`,
      `3 à 5 repas par jour pour atteindre tes calories sans te gaver d’un coup.`,
      `Privilégie les aliments denses si tu peines à manger assez (oléagineux, beurre de cacahuète, avoine, huile d’olive).`,
      `Surveille le miroir et la balance : si le gras monte trop vite, réduis le surplus.`,
    ] },
    { type: 'h2', text: 'Combien manger ?' },
    { type: 'p', text: `Estimation rapide de ta maintenance : poids (kg) × 33 environ (si tu es actif). Exemple pour 70 kg : ≈ 2 300 kcal. Vise alors 2 500 à 2 700 kcal/jour. Ajuste après 2 semaines : pas de prise de poids → +150 kcal ; prise trop rapide (> 0,5 kg/sem) → −150 kcal.` },
    { type: 'h2', text: 'Journée type (≈ 2 600 kcal)' },
    { type: 'table', headers: ['Repas', 'Exemple', 'Protéines'], rows: [
      ['Petit-déj', 'Flocons d’avoine + lait + banane + beurre de cacahuète + whey', '45 g'],
      ['Déjeuner', 'Bœuf maigre + riz + légumes + huile d’olive', '45 g'],
      ['Collation', 'Skyr + fruits + amandes', '25 g'],
      ['Post-training', 'Poulet + pâtes + sauce tomate', '45 g'],
      ['Total', '≈ 2 600 kcal · surplus modéré', '≈ 160 g'],
    ] },
    { type: 'h2', text: 'Liste de courses' },
    { type: 'list', items: [
      `Protéines : bœuf maigre, poulet, dinde, œufs, poisson, skyr, whey.`,
      `Glucides : riz, pâtes complètes, patate douce, flocons d’avoine, pain complet.`,
      `Lipides : huile d’olive, avocat, amandes, beurre de cacahuète.`,
      `Légumes & fruits : brocoli, épinards, poivron, banane, fruits rouges.`,
    ] },
    { type: 'note', text: `Tu n’arrives pas à manger assez ? Bois tes calories : un shake avoine + lait + banane + whey + beurre de cacahuète = 600-700 kcal faciles entre deux repas.` },
    { type: 'h2', text: 'Comprendre tes macros' },
    { type: 'p', text: `Tu n’as pas besoin de tout peser, mais comprendre le rôle de chaque macronutriment t’aide à composer de meilleures assiettes de prise de masse.` },
    { type: 'table', headers: ['Macro', 'Rôle', 'Par g', 'Priorité en masse'], rows: [
      ['Protéines', 'Construisent le muscle', '4 kcal', 'HAUTE - 1,8-2,2 g/kg'],
      ['Glucides', 'Énergie & volume musculaire', '4 kcal', 'HAUTE - autour des séances'],
      ['Lipides', 'Hormones (testostérone)', '9 kcal', 'Modérée - 0,8-1 g/kg'],
    ] },
    { type: 'list', items: [
      `Protéines : la brique. Sans elles, pas de construction, peu importe le reste.`,
      `Glucides : ton carburant à l’entraînement et le « volume » du muscle (glycogène).`,
      `Lipides : ne descends jamais trop bas, ils soutiennent tes hormones anabolisantes.`,
    ] },

    { type: 'h1', text: 'Recettes prise de masse' },
    { type: 'h2', text: 'Shake prise de masse maison' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 650 kcal' }, { label: 'Protéines', value: '45 g' }] },
    { type: 'list', items: [`300 ml de lait`, `60 g de flocons d’avoine`, `1 banane`, `1 dose de whey`, `1 c. à soupe de beurre de cacahuète`] },
    { type: 'p', text: `Préparation : mixe le tout 30 secondes. Idéal au petit-déj ou après l’entraînement.` },
    { type: 'h2', text: 'Bowl bœuf-riz post-training' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 700 kcal' }, { label: 'Protéines', value: '50 g' }] },
    { type: 'list', items: [`150 g de bœuf haché 5%`, `120 g de riz (poids cru)`, `Légumes au choix`, `Sauce soja, épices`] },
    { type: 'p', text: `Préparation : saisis le bœuf, ajoute les légumes, sers sur le riz. Riche, simple, parfait après la séance.` },
    { type: 'h2', text: 'Porridge protéiné du matin' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 550 kcal' }, { label: 'Protéines', value: '38 g' }] },
    { type: 'list', items: [`80 g de flocons d’avoine`, `300 ml de lait`, `1 dose de whey vanille`, `1 c. à soupe de miel + fruits rouges`] },
    { type: 'p', text: `Préparation : chauffe les flocons dans le lait 3 min, hors du feu ajoute la whey, le miel et les fruits. Petit-déj de champion.` },
    { type: 'h2', text: 'Omelette costaud + patate douce' },
    { type: 'meta', items: [{ label: 'Calories', value: '≈ 600 kcal' }, { label: 'Protéines', value: '42 g' }] },
    { type: 'list', items: [`4 œufs + 2 blancs`, `200 g de patate douce`, `Épinards, fromage`, `Huile d’olive`] },
    { type: 'p', text: `Préparation : cuis la patate douce au four/micro-ondes, prépare l’omelette aux épinards et fromage. Repas complet et rassasiant.` },

    { type: 'chapter', title: 'Récupération', src: 'recovery.jpg' },
    { type: 'list', items: [
      `Dors 7 à 9 h : c’est pendant le sommeil que la synthèse musculaire est maximale.`,
      `Laisse 48 h à un muscle avant de le retravailler (d’où le split Haut/Bas).`,
      `Hydrate-toi (3 L/jour) : le muscle est composé à ~75 % d’eau.`,
      `Une semaine « deload » (charges −40 %) toutes les 6 semaines évite la stagnation.`,
    ] },

    { type: 'chapter', title: 'Plan sur 12 semaines (3 phases)', src: 'masse-1.jpg' },
    { type: 'p', text: `Le programme progresse en 3 phases. Respecte l’ordre : volume d’abord, intensité ensuite.` },
    { type: 'table', headers: ['Phase', 'Semaines', 'Focus', 'Répétitions'], rows: [
      ['Phase 1', 'S1 à S4', 'Adaptation & volume', '12 à 15'],
      ['Phase 2', 'S5 à S8', 'Hypertrophie', '8 à 12'],
      ['Phase 3', 'S9 à S12', 'Force & densité', '6 à 8'],
    ] },
    { type: 'h2', text: 'Semaine type (split Haut / Bas)' },
    { type: 'table', headers: ['Jour', 'Séance', 'Focus'], rows: [
      ['Lundi', 'Haut du corps A', 'Pecs, dos, épaules, bras'],
      ['Mardi', 'Bas du corps A', 'Quadriceps, fessiers, mollets'],
      ['Mercredi', 'Repos / cardio léger', 'Récupération'],
      ['Jeudi', 'Haut du corps B', 'Dos, pecs, bras'],
      ['Vendredi', 'Bas du corps B', 'Ischios, fessiers, gainage'],
      ['Week-end', 'Repos + suivi', 'Récupération'],
    ] },

    { type: 'h1', text: 'Tes séances en détail' },
    { type: 'h2', text: 'Haut du corps A' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Développé couché (ou pompes lestées)', '4', '8 à 10', '120 s'],
      ['Tirage horizontal / rowing', '4', '10', '90 s'],
      ['Développé militaire', '3', '10', '90 s'],
      ['Tirage vertical', '3', '12', '75 s'],
      ['Curl biceps', '3', '12', '60 s'],
      ['Extension triceps', '3', '12', '60 s'],
    ] },
    { type: 'h2', text: 'Bas du corps A' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Squat', '4', '8 à 10', '120 s'],
      ['Presse à cuisses (ou fentes)', '4', '12', '90 s'],
      ['Soulevé de terre roumain', '3', '10', '90 s'],
      ['Leg curl (ou pont fessier lesté)', '3', '12', '75 s'],
      ['Mollets debout', '4', '15', '45 s'],
    ] },
    { type: 'h2', text: 'Haut du corps B' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Tractions (ou tirage vertical)', '4', '8 à 10', '120 s'],
      ['Développé incliné haltères', '4', '10', '90 s'],
      ['Rowing haltère unilatéral', '3', '12', '75 s'],
      ['Élévations latérales', '3', '15', '60 s'],
      ['Curl marteau', '3', '12', '60 s'],
      ['Dips (ou extension triceps)', '3', '10', '60 s'],
    ] },
    { type: 'h2', text: 'Bas du corps B' },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Soulevé de terre (ou hip thrust)', '4', '6 à 8', '120 s'],
      ['Fentes marchées haltères', '3', '12 / jambe', '90 s'],
      ['Leg extension (ou squat bulgare)', '3', '15', '75 s'],
      ['Pont fessier lesté', '3', '12', '75 s'],
      ['Gainage planche + latéral', '3', '40 s', '45 s'],
    ] },

    { type: 'h1', text: 'Calendrier des 12 semaines' },
    { type: 'p', text: `Trois phases progressives. Garde le même split Haut/Bas chaque semaine, mais fais évoluer répétitions et charges selon la phase.` },
    { type: 'h2', text: 'Phase 1 - Adaptation & volume (S1 à S4)' },
    { type: 'table', headers: ['Semaine', 'Répétitions', 'Intensité', 'Note'], rows: [
      ['S1', '12 à 15', 'RPE 7', 'Technique avant tout'],
      ['S2', '12 à 15', 'RPE 7-8', '+1 rep / série'],
      ['S3', '12 à 15', 'RPE 8', '+ charge légère'],
      ['S4', '12 à 15', 'RPE 8', 'Bats tes perfs S1'],
    ] },
    { type: 'h2', text: 'Phase 2 - Hypertrophie (S5 à S8)' },
    { type: 'table', headers: ['Semaine', 'Répétitions', 'Intensité', 'Note'], rows: [
      ['S5', '8 à 12', 'RPE 8', 'Augmente les charges'],
      ['S6', '8 à 12', 'RPE 8', 'Deload léger en fin de semaine'],
      ['S7', '8 à 12', 'RPE 8-9', '+ charge'],
      ['S8', '8 à 12', 'RPE 9', 'Séries au plus proche de l’échec'],
    ] },
    { type: 'h2', text: 'Phase 3 - Force & densité (S9 à S12)' },
    { type: 'table', headers: ['Semaine', 'Répétitions', 'Intensité', 'Note'], rows: [
      ['S9', '6 à 8', 'RPE 8', 'Charges lourdes, repos longs'],
      ['S10', '6 à 8', 'RPE 8-9', '+ charge'],
      ['S11', '6 à 8', 'RPE 9', 'Pic d’intensité'],
      ['S12', '6 à 8 puis deload', 'Variable', 'Bilan + photos + mensurations'],
    ] },

    { type: 'h1', text: 'Variante : full body 3 jours' },
    { type: 'p', text: `Tu ne peux pas t’entraîner 4 fois par semaine ? Remplace le split Haut/Bas par ce schéma full body 3 jours (lundi / mercredi / vendredi). Chaque séance travaille tout le corps : c’est très efficace pour les débutants et les emplois du temps chargés.` },
    { type: 'table', headers: ['Exercice', 'Séries', 'Répétitions', 'Repos'], rows: [
      ['Squat', '4', '8 à 10', '120 s'],
      ['Développé couché (ou pompes)', '4', '8 à 10', '120 s'],
      ['Rowing / tirage', '4', '10', '90 s'],
      ['Développé militaire', '3', '10', '90 s'],
      ['Soulevé de terre roumain', '3', '10', '90 s'],
      ['Gainage + curl/extension', '3', '12', '60 s'],
    ] },
    { type: 'note', text: `Sur le full body, alterne légèrement les exercices entre les 3 séances (ex. squat lundi, fentes mercredi, presse vendredi) pour varier les stimuli.` },

    { type: 'h1', text: 'Bibliothèque d’exercices' },
    { type: 'p', text: `Maîtrise ces mouvements de base : ils construisent l’essentiel de ta masse. Scanne le QR pour la vidéo de démonstration.` },
    { type: 'exercise', name: 'Squat', muscles: 'Quadriceps, fessiers, ischios, gainage', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Barre sur le haut du dos, pieds largeur d’épaules. Descends en poussant les fesses vers l’arrière, dos gainé, jusqu’à cuisses parallèles, puis remonte en poussant dans les talons.`, mistakes: `Genoux qui rentrent, talons qui décollent, dos qui s’arrondit. Garde le buste fier et le poids dans les talons.` },
    { type: 'exercise', name: 'Développé couché', muscles: 'Pectoraux, triceps, épaules', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Allongé sur le banc, omoplates serrées, légère cambrure. Descends la barre vers le bas des pectoraux, coudes à ~45°, puis pousse en gardant les pieds ancrés au sol.`, mistakes: `Coudes trop écartés, rebond sur la poitrine, fesses qui décollent. Contrôle la descente.` },
    { type: 'exercise', name: 'Soulevé de terre roumain', muscles: 'Ischios, fessiers, dos', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Barre devant les cuisses, dos plat. Descends la barre le long des jambes en poussant les hanches vers l’arrière, légère flexion des genoux, jusqu’à sentir l’étirement des ischios, puis reviens en serrant les fessiers.`, mistakes: `Dos arrondi, barre qui s’éloigne du corps, flexion des genoux excessive (ça devient un squat).` },
    { type: 'exercise', name: 'Rowing barre', muscles: 'Dos, biceps, arrière d’épaules', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Buste penché ~45°, dos plat. Tire la barre vers le bas-ventre en serrant les omoplates, puis redescends lentement. Le mouvement vient du dos, pas des bras.`, mistakes: `Dos rond, buste qui se redresse à chaque répétition, tirer trop haut vers la poitrine.` },
    { type: 'exercise', name: 'Développé militaire', muscles: 'Épaules, triceps, gainage', level: 'Intermédiaire', video: `${D}/musculation`, technique: `Debout, barre au niveau des clavicules, gainage serré. Pousse la barre au-dessus de la tête sans cambrer le bas du dos, puis redescends contrôlé.`, mistakes: `Cambrure lombaire excessive, pousser vers l’avant au lieu de la verticale, fin de course incomplète.` },
    { type: 'exercise', name: 'Tirage vertical', muscles: 'Grand dorsal, biceps', level: 'Débutant', video: `${D}/musculation`, technique: `Assis, prise large. Tire la barre vers le haut de la poitrine en abaissant les épaules et serrant le dos, puis remonte contrôlé en gardant la tension.`, mistakes: `Se balancer en arrière, tirer derrière la nuque, relâcher en haut.` },
    { type: 'exercise', name: 'Fentes haltères', muscles: 'Quadriceps, fessiers, équilibre', level: 'Débutant', video: `${D}/musculation`, technique: `Haltères en main, grand pas en avant, genou arrière vers le sol, buste droit. Pousse dans le talon avant pour revenir. Alterne les jambes.`, mistakes: `Pas trop court, buste penché, genou qui part vers l’intérieur.` },
    { type: 'exercise', name: 'Curl biceps', muscles: 'Biceps', level: 'Débutant', video: `${D}/musculation`, technique: `Coudes collés au corps, monte les haltères en contractant les biceps, puis redescends lentement (2 s). Pas d’élan.`, mistakes: `Balancer le corps, coudes qui avancent, descente trop rapide.` },
    { type: 'exercise', name: 'Extension triceps', muscles: 'Triceps', level: 'Débutant', video: `${D}/musculation`, technique: `À la poulie ou avec haltère, coudes fixes, étends l’avant-bras complètement puis reviens contrôlé. Seul l’avant-bras bouge.`, mistakes: `Coudes qui s’écartent, amplitude partielle, élan du buste.` },
    { type: 'exercise', name: 'Gainage planche', muscles: 'Sangle abdominale, lombaires', level: 'Débutant', video: `${D}/musculation`, technique: `Appui avant-bras et pointes de pieds, corps aligné, abdos et fessiers contractés. Tiens la position en respirant calmement.`, mistakes: `Bassin qui s’affaisse, fesses trop hautes, tête relevée.` },

    { type: 'h1', text: 'Progression recommandée' },
    { type: 'p', text: `La surcharge progressive est le moteur de la prise de masse. Voici comment avancer sans te blesser.` },
    { type: 'table', headers: ['Phase', 'Objectif', 'Comment progresser'], rows: [
      ['S1-S4', 'Apprendre & encaisser le volume', '+1-2 reps/semaine'],
      ['S5-S8', 'Maximiser l’hypertrophie', '+2,5 kg au haut de la fourchette'],
      ['S9-S12', 'Gagner en force', 'Charges plus lourdes, reps plus basses'],
    ] },
    { type: 'list', items: [
      `Quand tu atteins le haut de la fourchette de reps sur toutes les séries, ajoute du poids.`,
      `Note chaque séance : charge × répétitions. Bats ce chiffre la fois suivante.`,
      `Deload toutes les 6 semaines : volume −40 % pendant 1 semaine, puis repars plus fort.`,
    ] },

    { type: 'h1', text: 'Erreurs à éviter' },
    { type: 'list', items: [
      `Manger trop (« dirty bulk ») : tu gagnes surtout du gras qu’il faudra reperdre.`,
      `Changer de programme toutes les 2 semaines : le muscle a besoin de constance.`,
      `Négliger les jambes : un physique se construit aussi (surtout) par le bas.`,
      `Ego-lifting : charge trop lourde, technique dégradée → blessure assurée.`,
      `Sauter les protéines ou le sommeil : pas de construction sans matériaux ni repos.`,
    ] },
    { type: 'h2', text: 'Problème → solution' },
    { type: 'table', headers: ['Tu rencontres…', 'La solution'], rows: [
      ['Tu ne prends pas de poids', '+150-200 kcal/jour, ajoute un shake'],
      ['Tu prends trop de gras', 'Réduis le surplus, garde les protéines hautes'],
      ['Tu stagnes en force', 'Deload 1 semaine, vérifie sommeil & calories'],
      ['Douleur articulaire', 'Allège, revois la technique (scanne la vidéo)'],
    ] },

    { type: 'h1', text: 'Rester motivé(e)' },
    { type: 'list', items: [
      `Photographie-toi toutes les 4 semaines : la masse se voit mieux qu’elle ne se sent.`,
      `Fixe-toi des objectifs de force (ex. « squat à 1× mon poids de corps »).`,
      `Entoure-toi : un partenaire d’entraînement booste l’intensité et l’assiduité.`,
      `Sois patient : 2 à 5 kg de muscle en 12 semaines, c’est un excellent résultat.`,
    ] },
    { type: 'h2', text: 'Construis l’habitude' },
    { type: 'list', items: [
      `Bloque tes 4 créneaux d’entraînement dans ton agenda comme des rendez-vous.`,
      `Prépare ton sac et tes repas la veille : zéro friction le jour J.`,
      `Ne brise jamais la chaîne 2 séances de suite.`,
    ] },

    { type: 'h1', text: 'Questions fréquentes' },
    { type: 'h2', text: 'Je suis débutant, ce programme est pour moi ?' },
    { type: 'p', text: `Oui. Commence léger pour maîtriser la technique (utilise les variantes au poids du corps si besoin), puis ajoute de la charge progressivement. Les débutants progressent très vite les premiers mois.` },
    { type: 'h2', text: 'Vais-je prendre du gras ?' },
    { type: 'p', text: `Un peu, c’est normal et nécessaire pour construire du muscle. Avec un surplus modéré (200-400 kcal) et beaucoup de protéines, la prise reste majoritairement musculaire.` },
    { type: 'h2', text: 'Puis-je le faire à la maison ?' },
    { type: 'p', text: `Oui avec une paire d’haltères réglables et une barre. Sinon, remplace par les variantes au poids du corps (pompes lestées, fentes, tractions, dips) en visant l’échec propre.` },
    { type: 'h2', text: 'Faut-il des compléments ?' },
    { type: 'p', text: `Aucun n’est obligatoire. Les plus utiles : whey (atteindre ses protéines), créatine monohydrate (3-5 g/jour, le complément le plus étudié pour la force et le volume).` },
    { type: 'h2', text: 'Combien de cardio ?' },
    { type: 'p', text: `Un peu (2 × 20 min léger/semaine) pour la santé et garder le gras à distance, sans excès pour ne pas brûler tes calories de construction.` },
    { type: 'h2', text: 'Faut-il aller jusqu’à l’échec ?' },
    { type: 'p', text: `Pas à chaque série : garde 1 à 2 répétitions en réserve sur la plupart des séries (RPE 8). Réserve l’échec à la dernière série d’un exercice d’isolation. Aller systématiquement à l’échec fatigue le système nerveux et freine la récupération.` },
    { type: 'h2', text: 'Que faire si je rate une séance ?' },
    { type: 'p', text: `Reprends simplement à la séance suivante du planning, ne tente pas de tout rattraper. Sur 12 semaines, une séance manquée ne change rien - l’abandon, si.` },
    { type: 'h2', text: 'Je suis « hardgainer », je ne prends pas. Que faire ?' },
    { type: 'p', text: `Dans 95 % des cas, tu manges moins que tu ne crois. Augmente les portions, ajoute un shake liquide entre les repas, et pèse-toi : si le poids ne monte pas sur 2 semaines, ajoute 200 kcal.` },

    { type: 'h1', text: 'Sommeil, stress & hormones' },
    { type: 'p', text: `La construction musculaire ne se joue pas qu’à la salle : tes hormones (testostérone, hormone de croissance) et ta récupération dépendent largement de ton sommeil et de ta gestion du stress.` },
    { type: 'list', items: [
      `Vise 7 à 9 h de sommeil : la majorité de la récupération musculaire a lieu la nuit.`,
      `Couche-toi à heure régulière ; coupe les écrans 30 min avant.`,
      `Le stress chronique élève le cortisol, qui freine la prise de muscle - apprends à décompresser.`,
      `Évite l’excès d’alcool : il perturbe le sommeil et la synthèse protéique.`,
      `Expose-toi à la lumière du jour le matin pour caler ton horloge interne.`,
    ] },

    { type: 'h1', text: 'Étirements & mobilité' },
    { type: 'p', text: `Après chaque séance, consacre 5 à 10 minutes aux étirements pour préserver ta mobilité sous charge et limiter les courbatures. Tiens chaque position 20 à 30 s.` },
    { type: 'table', headers: ['Étirement', 'Zone', 'Durée'], rows: [
      ['Étirement pectoraux au mur', 'Poitrine, épaules', '30 s / côté'],
      ['Suspension à la barre', 'Dos, épaules', '30 s'],
      ['Étirement quadriceps debout', 'Avant de cuisse', '30 s / côté'],
      ['Étirement ischios assis', 'Arrière de cuisse', '30 s / côté'],
      ['Pigeon (fessiers)', 'Fessiers, hanches', '30 s / côté'],
      ['Rotation thoracique au sol', 'Colonne', '45 s'],
    ] },

    { type: 'h1', text: 'Adapter chaque exercice' },
    { type: 'p', text: `Pas de matériel ou mouvement trop dur ? Voici une alternative pour chaque exercice de base, sans perdre l’efficacité.` },
    { type: 'table', headers: ['Exercice', 'Sans matériel / plus facile', 'Plus dur'], rows: [
      ['Squat barre', 'Squat gobelet / au poids du corps', 'Squat bulgare lesté'],
      ['Développé couché', 'Pompes (pieds surélevés)', 'Développé incliné lourd'],
      ['Tractions', 'Tirage élastique / rowing', 'Tractions lestées'],
      ['Soulevé de terre', 'Hip thrust / pont fessier', 'Soulevé de terre lourd'],
      ['Développé militaire', 'Pompes piké', 'Développé debout lourd'],
    ] },

    { type: 'h1', text: 'Compléments alimentaires' },
    { type: 'p', text: `Aucun n’est obligatoire - l’alimentation passe avant tout. Mais quelques compléments ont un réel intérêt, prouvé par la science.` },
    { type: 'table', headers: ['Complément', 'Intérêt', 'Dose'], rows: [
      ['Créatine monohydrate', 'Force, volume, le + étudié', '3 à 5 g / jour'],
      ['Whey', 'Atteindre ses protéines facilement', '1 à 2 doses / jour'],
      ['Vitamine D', 'Si peu d’exposition au soleil', 'Selon avis médical'],
      ['Oméga-3', 'Récupération, articulations', '1 à 2 g / jour'],
    ] },
    { type: 'note', text: `Méfie-toi des « gainers » sucrés et des produits miracles : ils coûtent cher pour peu d’effet. La créatine et la whey suffisent dans 99 % des cas.` },

    { type: 'h1', text: 'Et après tes 12 semaines ?' },
    { type: 'p', text: `Tu as construit du muscle : il s’agit maintenant de le conserver et de continuer à progresser. Deux options selon ton objectif.` },
    { type: 'h2', text: 'Option 1 - Révéler le muscle (sèche)' },
    { type: 'list', items: [
      `Passe en léger déficit (−300 à −500 kcal) pour faire fondre le gras pris pendant la masse.`,
      `Garde les protéines hautes et l’entraînement en force pour conserver le muscle.`,
      `Enchaîne avec le programme Perte de Poids pour révéler ta définition.`,
    ] },
    { type: 'h2', text: 'Option 2 - Continuer à construire' },
    { type: 'list', items: [
      `Fais une semaine de deload, puis relance un cycle avec des charges plus lourdes.`,
      `Change quelques exercices pour varier les stimuli et éviter la routine.`,
      `Vise de nouveaux records de force comme fil conducteur.`,
    ] },
    { type: 'note', text: `Quoi que tu choisisses : ne relâche pas tout d’un coup. Le muscle se perd vite si tu arrêtes complètement de t’entraîner et de manger suffisamment de protéines.` },

    { type: 'h1', text: 'Suivi de ta progression' },
    { type: 'p', text: `Note tes charges et ton poids chaque semaine : c’est ton tableau de bord. Ce qui se mesure se pilote.` },
    { type: 'h2', text: 'Poids & mensurations' },
    { type: 'tracker', columns: ['Date', 'Poids (kg)', 'Bras (cm)', 'Cuisse (cm)', 'Poitrine (cm)'], rows: 7 },
    { type: 'h2', text: 'Charges sur les mouvements de base (kg)' },
    { type: 'tracker', columns: ['Exercice', 'S1', 'S4', 'S8', 'S12'], rows: 6 },

    { type: 'h1', text: 'Checklist hebdomadaire' },
    { type: 'p', text: `Coche chaque case en fin de semaine. Objectif : au moins 6 cases sur 8.` },
    { type: 'checklist', items: [
      `J’ai fait mes 4 séances cette semaine.`,
      `J’ai atteint mon objectif de protéines chaque jour.`,
      `J’ai mangé en léger surplus (poids stable ou +).`,
      `J’ai augmenté une charge ou des répétitions.`,
      `J’ai dormi 7 à 9 h la plupart des nuits.`,
      `Je me suis hydraté(e) (≈ 3 L/jour).`,
      `J’ai noté mes charges et mes performances.`,
      `Je me suis pesé(e) 1 fois, dans les mêmes conditions.`,
    ] },

    { type: 'h1', text: 'Notes personnelles' },
    { type: 'tracker', columns: ['Mes notes, charges et sensations de la semaine'], rows: 18 },

    { type: 'h1', text: 'Glossaire' },
    { type: 'p', text: `Les termes qui reviennent dans ce guide, expliqués simplement.` },
    { type: 'list', items: [
      `Hypertrophie : croissance de la taille des fibres musculaires (le « volume »).`,
      `Surcharge progressive : augmenter régulièrement charge ou répétitions pour forcer l’adaptation.`,
      `RPE : intensité ressentie sur 10. RPE 8 = il te restait ~2 répétitions en réserve.`,
      `Tempo : vitesse d’exécution (ex. 2 s en descente, 1 s en montée).`,
      `Excentrique : phase où le muscle s’allonge sous tension (la descente).`,
      `Deload : semaine allégée pour récupérer et mieux repartir.`,
      `Maintenance : nombre de calories qui maintient ton poids stable.`,
      `Split : façon de répartir les groupes musculaires sur la semaine (ici Haut/Bas).`,
    ] },

    { type: 'note', text: `12 semaines bouclées ? Fais une semaine de deload, reprends tes mensurations et tes photos, puis enchaîne un nouveau cycle ou une phase de sèche (Perte de Poids) pour révéler le muscle construit. Crée ton compte sur xenotif.com.` },
  ],
}
