import type { Guide } from '@/lib/boutique/guides'

// d4 - Guide Running : du 5K au Marathon (FR). Plans 5K/10K/semi/marathon,
// nutrition course, prévention blessures, mental de compétiteur, renforcement.
// Gabarit premium XENOTIF® : couverture running, en-têtes image+titre. ≈30 pages.
export const runningGuide: Guide = {
  id: 'd4',
  title: 'Guide Running - Du 5K au Marathon',
  subtitle: 'Plans 5K / 10K / semi / marathon, nutrition course, prévention blessures, mental',
  author: 'XENOTIF Coach - Entraîneur athlétisme FFA',
  level: 'Débutant → Confirmé',
  duration: '4 plans · 5K à marathon',
  coverImage: 'run-cover.jpg',
  blocks: [
    { type: 'h1', text: 'Bienvenue, coureur' },
    { type: 'p', text: `Que tu veuilles courir ton premier 5 km ou décrocher un marathon, ce guide t’accompagne sur tout le chemin. Il rassemble 4 plans d’entraînement complets (5K, 10K, semi-marathon, marathon), la science des allures, la nutrition de course, la prévention des blessures, le renforcement du coureur et le mental de compétiteur.` },
    { type: 'p', text: `Lis d’abord les chapitres sur les allures et la technique : ce sont eux qui feront la différence sur ta progression et ta prévention des blessures. Chaque exercice de renforcement a un QR code vers sa vidéo de démonstration.` },
    { type: 'meta', items: [
      { label: 'Objectif', value: 'Courir 5K à marathon' },
      { label: 'Niveau', value: 'Débutant à confirmé' },
      { label: 'Plans', value: '5K · 10K · semi · marathon' },
      { label: 'Séances', value: '3 à 4 par semaine' },
      { label: 'Matériel', value: 'Une bonne paire de chaussures' },
      { label: 'Inclus', value: 'Plans + nutrition + mental' },
    ] },
    { type: 'h2', text: 'Comment utiliser ce guide' },
    { type: 'list', items: [
      `Choisis ton plan selon ton objectif (5K, 10K, semi ou marathon).`,
      `Lis les chapitres « allures » et « prévention » avant de commencer.`,
      `Respecte les jours de repos : la progression se fait pendant la récupération.`,
      `Fais le renforcement 1-2×/semaine (chapitre dédié, avec QR vidéos).`,
      `Note tes sorties et tes sensations dans le suivi.`,
    ] },
    { type: 'note', text: `La règle des 80/20 : 80 % de tes kilomètres en endurance fondamentale (lente, tu peux parler), 20 % en intensité. C’est la base de toute progression durable en course.` },

    { type: 'h1', text: 'La science des allures' },
    { type: 'p', text: `Courir « vite tout le temps » est l’erreur n°1 du débutant : ça mène au surentraînement et aux blessures. La progression vient de la VARIÉTÉ des allures.` },
    { type: 'table', headers: ['Allure', 'Intensité', 'Ressenti', 'Usage'], rows: [
      ['Endurance fondamentale', 'Faible', 'Tu tiens une conversation', '80 % du volume'],
      ['Allure marathon', 'Modérée', 'Confortablement dur', 'Sorties longues'],
      ['Allure semi/10K', 'Soutenue', 'Phrases courtes', 'Tempo / seuil'],
      ['Allure 5K / VMA', 'Élevée', 'Quelques mots', 'Fractionné'],
      ['Sprint', 'Maximale', 'Impossible de parler', 'Lignes droites'],
    ] },
    { type: 'list', items: [
      `Endurance fondamentale (EF) : la base. Cours lentement, vraiment lentement.`,
      `Fractionné (VMA) : des répétitions rapides avec récupération (ex. 8 × 400 m).`,
      `Tempo / seuil : une allure soutenue tenue 15-30 min, pour repousser ton seuil.`,
      `Sortie longue : progressive en durée, à allure facile, clé pour le semi et le marathon.`,
    ] },

    { type: 'h1', text: 'Calcule tes allures d’entraînement' },
    { type: 'p', text: `Pour t’entraîner efficacement, chaque type de séance a sa propre allure. Repère ton objectif chrono dans le tableau et lis les allures correspondantes (en min/km). Ce sont tes repères pour tout le guide.` },
    { type: 'table', headers: ['Objectif', 'Endurance (EF)', 'Allure seuil', 'Allure VMA/5K'], rows: [
      ['5K en 30 min', '7:00 - 7:30', '5:40', '5:20'],
      ['5K en 25 min', '6:15 - 6:45', '4:45', '4:30'],
      ['10K en 55 min', '6:30 - 7:00', '5:10', '4:55'],
      ['10K en 50 min', '6:00 - 6:30', '4:40', '4:25'],
      ['Semi en 2 h', '6:30 - 7:00', '5:25', '5:05'],
      ['Semi en 1 h 45', '5:45 - 6:15', '4:45', '4:25'],
      ['Marathon en 4 h 30', '7:00 - 7:30', '5:55', '5:30'],
      ['Marathon en 4 h', '6:15 - 6:45', '5:15', '4:55'],
    ] },
    { type: 'note', text: `Tu ne connais pas ton niveau ? Cours 5 km à fond une fois échauffé : ton temps te place dans le tableau. Refais ce test toutes les 4-6 semaines pour ajuster tes allures à mesure que tu progresses.` },

    { type: 'chapter', title: 'La foulée parfaite', src: 'run-2.jpg', intro: `Une bonne technique de course, c’est moins de fatigue, plus de vitesse et beaucoup moins de blessures. Quelques principes simples à intégrer progressivement.` },
    { type: 'list', items: [
      `Cadence : vise environ 170-180 pas par minute. Une cadence élevée raccourcit la foulée et réduit l’impact.`,
      `Attaque du pied : pose le pied sous ton bassin, pas loin devant toi (évite l’attaque talon jambe tendue).`,
      `Posture : buste droit, léger gainage, regard à l’horizon, épaules relâchées.`,
      `Bras : pliés à ~90°, mouvement d’avant en arrière (pas de croisement devant le buste), mains décontractées.`,
      `Respiration : ventrale et régulière, calée sur ta foulée (ex. 3 pas inspire / 2 pas expire en EF).`,
    ] },
    { type: 'h2', text: 'Le test de la cadence' },
    { type: 'p', text: `Compte tes appuis d’un seul pied sur 30 secondes, puis multiplie par 4. Moins de 80 ? Travaille à raccourcir et accélérer ta foulée, notamment grâce aux gammes athlétiques du chapitre renforcement.` },

    { type: 'h1', text: 'Échauffement & retour au calme' },
    { type: 'p', text: `Ne saute jamais l’échauffement avant une séance de qualité (fractionné, seuil, course). Le retour au calme accélère la récupération.` },
    { type: 'h2', text: 'Échauffement type (15 min)' },
    { type: 'table', headers: ['Étape', 'Durée', 'Contenu'], rows: [
      ['Footing lent', '10 min', 'Mise en route progressive du corps'],
      ['Mobilité', '2 min', 'Cercles de hanches, chevilles, balanciers de jambes'],
      ['Gammes', '2 min', 'Montées de genoux, talons-fesses, pas chassés'],
      ['Accélérations', '1 min', '3 à 4 lignes droites progressives'],
    ] },
    { type: 'h2', text: 'Retour au calme (10 min)' },
    { type: 'list', items: [
      `5 min de footing très lent pour faire redescendre le cœur.`,
      `5 min d’étirements doux des principaux groupes musculaires (voir chapitre étirements).`,
      `Réhydrate-toi et prends une collation glucides + protéines dans l’heure.`,
    ] },
    { type: 'h2', text: 'Mobilité avant de courir (5 min)' },
    { type: 'p', text: `Pour les footings faciles, un échauffement plus court suffit, mais quelques mouvements dynamiques préparent les articulations et réduisent le risque de blessure.` },
    { type: 'table', headers: ['Mouvement', 'Répétitions', 'Cible'], rows: [
      ['Balanciers de jambe (avant-arrière)', '10 / jambe', 'Hanches, ischios'],
      ['Balanciers latéraux', '10 / jambe', 'Adducteurs, hanches'],
      ['Cercles de chevilles', '10 / sens', 'Chevilles'],
      ['Fentes marchées', '8 / jambe', 'Quadriceps, fessiers'],
      ['Talons-fesses sur place', '20 s', 'Ischios, mise en route'],
    ] },
    { type: 'note', text: `Évite les étirements statiques longs AVANT de courir : ils diminuent temporairement la puissance musculaire. Garde-les pour le retour au calme. Avant l’effort, privilégie le mouvement (dynamique).` },

    { type: 'h1', text: 'Grand débutant : le programme courir-marcher' },
    { type: 'p', text: `Tu pars de zéro ou tu reprends après une longue pause ? Commence ici avant le plan 5K. L’objectif : courir 30 minutes en continu en 6 semaines, sans te blesser.` },
    { type: 'table', headers: ['Semaine', 'Séance (×3/sem)', 'Total'], rows: [
      ['S1', '6 × (1 min course / 1,5 min marche)', '~20 min'],
      ['S2', '6 × (2 min course / 1 min marche)', '~22 min'],
      ['S3', '5 × (3 min course / 1 min marche)', '~25 min'],
      ['S4', '4 × (5 min course / 1 min marche)', '~28 min'],
      ['S5', '3 × (8 min course / 1 min marche)', '~30 min'],
      ['S6', '2 × (14 min course / 1 min marche)', '~30 min'],
    ] },
    { type: 'note', text: `Cours toujours lentement (tu dois pouvoir parler). Si une semaine est trop dure, recommence-la : il n’y a aucune honte à progresser à ton rythme. Une fois les 30 min en continu acquises, enchaîne sur le plan 5K.` },

    { type: 'chapter', title: 'Plan 5K (8 semaines)', src: 'run-1.jpg', intro: `Idéal pour débuter ou viser ton premier 5 km en courant. 3 sorties par semaine. Alterne course et marche au début si besoin.` },
    { type: 'table', headers: ['Semaine', 'Sortie 1', 'Sortie 2', 'Sortie 3 (longue)'], rows: [
      ['S1', '20 min course/marche', 'Repos / marche', '25 min course/marche'],
      ['S2', '25 min EF', 'Repos', '30 min EF'],
      ['S3', '25 min EF', '6 × 1 min vite / 1 min lent', '35 min EF'],
      ['S4', '30 min EF', '8 × 1 min vite / 1 min lent', '35 min EF'],
      ['S5', '30 min EF', '2 × 6 min tempo', '40 min EF'],
      ['S6', '30 min EF', '10 × 1 min vite / 1 min lent', '40 min EF'],
      ['S7', '30 min EF', '3 × 6 min tempo', '35 min EF'],
      ['S8', '20 min EF', '2 × 4 min allure 5K', 'COURSE 5K'],
    ] },

    { type: 'h1', text: 'Plan 10K (8 semaines)' },
    { type: 'p', text: `Pour celles et ceux qui courent déjà 5 km et visent le 10. 3 à 4 sorties par semaine.` },
    { type: 'table', headers: ['Semaine', 'Sortie 1', 'Sortie 2', 'Sortie 3 (longue)'], rows: [
      ['S1', '35 min EF', '8 × 400 m allure 5K', '45 min EF'],
      ['S2', '35 min EF', '2 × 8 min tempo', '50 min EF'],
      ['S3', '40 min EF', '10 × 400 m', '55 min EF'],
      ['S4', '40 min EF', '3 × 8 min tempo', '60 min EF'],
      ['S5', '40 min EF', '6 × 800 m allure 10K', '65 min EF'],
      ['S6', '45 min EF', '2 × 12 min tempo', '70 min EF'],
      ['S7', '40 min EF', '5 × 1000 m allure 10K', '50 min EF'],
      ['S8', '30 min EF', '2 × 5 min allure 10K', 'COURSE 10K'],
    ] },
    { type: 'h2', text: 'Réussir ton 10K' },
    { type: 'list', items: [
      `EF = endurance fondamentale (lente). C’est 80 % du plan : ne la cours jamais trop vite.`,
      `Les séances « tempo » se courent à allure seuil (cf. chapitre allures), soutenue mais maîtrisée.`,
      `Place un jour de repos après chaque séance de qualité (fractionné, tempo).`,
      `La semaine de course (S8), allège : tu dois arriver frais, pas fatigué.`,
      `Vise un negative split : pars prudemment, accélère sur la seconde moitié.`,
    ] },

    { type: 'chapter', title: 'Plan semi-marathon (10 semaines)', src: 'run-2.jpg', intro: `21,1 km. La sortie longue devient ta séance reine. 3 à 4 sorties par semaine, dont une longue le week-end.` },
    { type: 'table', headers: ['Semaine', 'Tempo / seuil', 'Fractionné', 'Sortie longue'], rows: [
      ['S1', '2 × 10 min', '8 × 400 m', '1 h 10'],
      ['S2', '2 × 12 min', '6 × 800 m', '1 h 20'],
      ['S3', '3 × 10 min', '10 × 400 m', '1 h 30'],
      ['S4', '20 min seuil', '5 × 1000 m', '1 h 40'],
      ['S5', '2 × 15 min', '6 × 1000 m', '1 h 30 (allégée)'],
      ['S6', '25 min seuil', '4 × 1500 m', '1 h 50'],
      ['S7', '2 × 15 min allure semi', '8 × 800 m', '2 h 00'],
      ['S8', '30 min allure semi', '6 × 1000 m', '1 h 45'],
      ['S9', '20 min allure semi', '4 × 800 m', '1 h 10 (affûtage)'],
      ['S10', '15 min footing', '3 × 3 min', 'SEMI-MARATHON'],
    ] },

    { type: 'h1', text: 'Plan marathon (12 semaines)' },
    { type: 'p', text: `42,195 km : le plan le plus exigeant. Prérequis : courir déjà ~1 h confortablement. La régularité et les sorties longues font tout.` },
    { type: 'table', headers: ['Semaine', 'Séance qualité', 'Sortie longue'], rows: [
      ['S1', '2 × 12 min seuil', '1 h 30'],
      ['S2', '6 × 1000 m', '1 h 45'],
      ['S3', '3 × 12 min seuil', '2 h 00'],
      ['S4', '8 × 800 m', '1 h 45 (allégée)'],
      ['S5', '25 min allure marathon', '2 h 15'],
      ['S6', '2 × 15 min seuil', '2 h 30'],
      ['S7', '30 min allure marathon', '2 h 00 (allégée)'],
      ['S8', '5 × 2000 m', '2 h 45'],
      ['S9', '40 min allure marathon', '3 h 00 (la reine)'],
      ['S10', '2 × 20 min seuil', '2 h 15 (affûtage)'],
      ['S11', '20 min allure marathon', '1 h 30 (affûtage)'],
      ['S12', '15 min footing léger', 'MARATHON'],
    ] },
    { type: 'note', text: `Affûtage (2 dernières semaines) : réduis le volume de 40-50 % tout en gardant un peu d’intensité. Tu arriveras frais et affûté le jour J. Ne fais JAMAIS de grosse sortie la dernière semaine.` },

    { type: 'h1', text: 'Stratégie de course le jour J' },
    { type: 'p', text: `Une course se gère. Le « negative split » (deuxième moitié plus rapide que la première) est la meilleure stratégie sur toutes les distances. Partir trop vite est l’erreur n°1.` },
    { type: 'table', headers: ['Distance', '1er tiers', 'Milieu', 'Fin'], rows: [
      ['5K', 'Contrôlé, jamais à fond', 'Allure cible', 'Tout donner le dernier km'],
      ['10K', 'Légèrement sous l’allure cible', 'Allure cible stable', 'Accélère sur les 2 derniers km'],
      ['Semi', 'Très contrôlé', 'Allure cible régulière', 'Garde des forces pour les 5 derniers km'],
      ['Marathon', 'Lent, économe (le piège du début)', 'Allure marathon régulière', 'Gère le mur, finis fort si possible'],
    ] },
    { type: 'list', items: [
      `Repère-toi sur tes allures (chapitre « calcule tes allures »), pas sur les autres coureurs.`,
      `Bois et mange dès le début sur semi/marathon, avant d’avoir faim ou soif.`,
      `Découpe mentalement la course (voir chapitre mental) : un segment à la fois.`,
      `Prépare ton matériel et ton petit-déjeuner la veille : zéro improvisation le matin.`,
    ] },
    { type: 'note', text: `Règle d’or : « commence lentement, puis ralentis » est une blague de coureurs… mais elle dit vrai. La quasi-totalité des contre-performances viennent d’un départ trop rapide. La discipline des premiers kilomètres fait les belles fins de course.` },

    { type: 'chapter', title: 'Nutrition du coureur', src: 'run-1.jpg', intro: `Bien manger et bien s’hydrater, c’est gagner des minutes et éviter le mur. Voici les repères avant, pendant et après l’effort.` },
    { type: 'h2', text: 'Au quotidien' },
    { type: 'list', items: [
      `Des glucides suffisants : ce sont ton carburant principal en course.`,
      `Des protéines à chaque repas pour la récupération musculaire (1,4-1,8 g/kg).`,
      `Hydratation constante : 2 à 3 L/jour, plus selon la chaleur et le volume.`,
    ] },
    { type: 'h2', text: 'Avant / pendant / après' },
    { type: 'table', headers: ['Moment', 'Quoi', 'Pourquoi'], rows: [
      ['Avant (2-3 h)', 'Repas riche en glucides, pauvre en fibres/gras', 'Faire le plein sans alourdir'],
      ['Pendant (> 1 h)', 'Eau + glucides (gels, boisson, fruits secs) toutes les 30-45 min', 'Éviter la panne (le « mur »)'],
      ['Après (0-1 h)', 'Glucides + protéines + eau', 'Récupération & reconstitution'],
    ] },
    { type: 'note', text: `Le « mur » du marathon (vers le 30e km) = épuisement des réserves de glycogène. On l’évite en s’alimentant DÈS le début de course (pas quand on a faim), et en ayant fait des sorties longues à l’entraînement.` },

    { type: 'h2', text: 'Hydratation & ravitaillement selon l’effort' },
    { type: 'p', text: `Adapte ton ravitaillement à la durée de la sortie. Au-delà d’une heure, l’apport en glucides devient déterminant.` },
    { type: 'table', headers: ['Durée', 'Boisson', 'Glucides'], rows: [
      ['< 45 min', 'Pas indispensable', 'Aucun'],
      ['45 min - 1 h', 'Eau si chaleur', 'Optionnel'],
      ['1 h - 2 h', '~500 ml/h', '30-40 g/h (gel, boisson)'],
      ['> 2 h (marathon)', 'Eau + électrolytes', '60-90 g/h, dès le départ'],
    ] },
    { type: 'list', items: [
      `Teste TOUT à l’entraînement (gels, boissons, marques) : jamais de nouveauté le jour de la course.`,
      `Par forte chaleur, ajoute des électrolytes (sodium) pour éviter crampes et hyponatrémie.`,
      `Signal d’alerte de déshydratation : urines foncées, bouche sèche, baisse de performance, vertiges.`,
      `Après l’effort, pèse-toi : bois ~1,5 L par kilo perdu pour bien te réhydrater.`,
    ] },
    { type: 'h2', text: 'Ravitaillement : maison ou du commerce ?' },
    { type: 'p', text: `Les gels du commerce sont pratiques en course, mais on peut très bien se ravitailler « maison » à l’entraînement, pour moins cher et plus digeste.` },
    { type: 'table', headers: ['Option', 'Glucides', 'Quand'], rows: [
      ['Gel énergétique', '~25 g', 'Course, intensité élevée'],
      ['Pâte de fruits', '~20 g', 'Sorties longues'],
      ['Banane', '~25 g', 'Sortie longue tranquille'],
      ['Fruits secs (dattes, abricots)', '~15-20 g', 'Sorties longues'],
      ['Boisson de l’effort maison', '~30-40 g/500 ml', 'Toute sortie > 1 h'],
    ] },
    { type: 'note', text: `Recette boisson maison (500 ml) : eau + 30 g de sucre (ou sirop) + une pincée de sel + un filet de citron. Simple, efficace et bien moins chère que les boissons du commerce.` },

    { type: 'chapter', title: 'Prévention des blessures', src: 'run-2.jpg', intro: `La course est traumatisante pour le corps. 80 % des blessures du coureur viennent d’erreurs évitables : trop, trop vite, mauvaise récupération.` },
    { type: 'list', items: [
      `Règle des 10 % : n’augmente pas ton volume hebdomadaire de plus de 10 % par semaine.`,
      `Échauffe-toi avant les séances de qualité (footing + gammes).`,
      `Renforce-toi 1-2×/semaine (chapitre suivant) : un coureur fort se blesse moins.`,
      `De bonnes chaussures adaptées à ta foulée, remplacées tous les ~800-1000 km.`,
      `Écoute les douleurs : une gêne articulaire qui persiste = repos + avis médical.`,
      `Alterne les surfaces (route, chemin) et ne néglige jamais les jours de repos.`,
    ] },
    { type: 'h2', text: 'Problème → solution' },
    { type: 'table', headers: ['Symptôme', 'Cause fréquente', 'Solution'], rows: [
      ['Périostite (tibia)', 'Volume trop rapide', 'Réduis, glace, surfaces souples'],
      ['Genou du coureur', 'Faiblesse fessiers/quadris', 'Renforcement + réduire l’allure'],
      ['Tendon d’Achille', 'Trop d’intensité', 'Repos, étirements mollets'],
      ['Ampoules', 'Chaussures/chaussettes', 'Bon matériel, anti-frottement'],
    ] },

    { type: 'chapter', title: 'La récupération du coureur', src: 'run-1.jpg', intro: `Tu ne progresses pas pendant l’effort, mais pendant la récupération. La négliger, c’est stagner et se blesser. Voici comment bien récupérer.` },
    { type: 'list', items: [
      `Sommeil : 7 à 9 h par nuit. C’est le premier outil de récupération, loin devant tout le reste.`,
      `Jours de repos : non négociables. Au moins 1-2 jours sans course par semaine selon ton plan.`,
      `Récupération active : marche, vélo doux ou natation les jours off favorisent la circulation.`,
      `Alimentation : glucides + protéines + hydratation dans l’heure qui suit les grosses séances.`,
      `Automassage : rouleau et balle de massage sur mollets, quadriceps et fessiers.`,
      `Écoute les signaux de surentraînement : fatigue persistante, sommeil dégradé, FC de repos élevée, baisse de motivation.`,
    ] },
    { type: 'h2', text: 'La semaine d’allègement' },
    { type: 'p', text: `Toutes les 3-4 semaines, réduis ton volume de ~30 %. Ces semaines « light » permettent à ton corps d’assimiler le travail et de revenir plus fort. Elles font partie de la progression, ce n’est pas du temps perdu.` },

    { type: 'chapter', title: 'Bien choisir ses chaussures', src: 'run-2.jpg', intro: `C’est ton seul équipement vraiment essentiel. De bonnes chaussures adaptées à ta foulée préviennent la majorité des blessures.` },
    { type: 'table', headers: ['Type', 'Pour qui', 'Usage'], rows: [
      ['Amorti / max-cushion', 'Débutants, gros gabarits', 'EF, sorties longues, route'],
      ['Polyvalente', 'La plupart des coureurs', 'Entraînement quotidien'],
      ['Légère / dynamique', 'Coureurs réguliers', 'Séances rapides, courses'],
      ['Plaque carbone', 'Confirmés (compétition)', 'Courses (5K à marathon)'],
      ['Trail', 'Hors route', 'Chemins, montagne, boue'],
    ] },
    { type: 'list', items: [
      `Fais-toi conseiller en magasin spécialisé (analyse de foulée).`,
      `Prends une demi-pointure de plus que ta taille de ville (les pieds gonflent).`,
      `Remplace tes chaussures tous les ~800-1000 km (l’amorti s’use même sans trous visibles).`,
      `Garde 2 paires en alternance sur gros volume : elles durent plus et varient les contraintes.`,
    ] },

    { type: 'h1', text: 'Courir par tous les temps' },
    { type: 'p', text: `Il n’y a pas de mauvaise météo, seulement un mauvais équipement. Adapte-toi pour courir toute l’année en sécurité.` },
    { type: 'table', headers: ['Météo', 'Conseils'], rows: [
      ['Forte chaleur', 'Tôt le matin/soir, hydratation + électrolytes, allure réduite, casquette'],
      ['Grand froid', 'Plusieurs couches respirantes, gants/bonnet, échauffement plus long'],
      ['Pluie', 'Casquette à visière, vêtements techniques, anti-frottement, chaussettes de rechange'],
      ['Nuit', 'Vêtements réfléchissants, lampe frontale, parcours connu et éclairé'],
      ['Vent', 'Pars contre le vent, reviens vent dans le dos ; reste prudent en bord de route'],
    ] },
    { type: 'h2', text: 'Règles de sécurité' },
    { type: 'list', items: [
      `Préviens un proche de ton parcours et de l’heure de retour sur les sorties longues.`,
      `Cours face à la circulation quand il n’y a pas de trottoir, et reste visible.`,
      `Garde un volume sonore bas (ou un seul écouteur) pour entendre ton environnement.`,
      `Emporte ton téléphone et une pièce d’identité sur les longues distances.`,
      `Par canicule ou verglas, n’hésite pas à reporter : aucune séance ne vaut une blessure.`,
    ] },

    { type: 'h1', text: 'Renforcement du coureur' },
    { type: 'p', text: `Un corps fort court plus vite et se blesse moins. Fais ce circuit 1 à 2 fois par semaine (hors jours de grosse séance). Scanne le QR pour la vidéo de démonstration.` },
    { type: 'exercise', name: 'Gainage planche', muscles: 'Sangle abdominale, posture de course', level: 'Débutant', technique: `Avant-bras au sol, corps aligné, abdos et fessiers serrés. Tiens 30-60 s. Un tronc solide stabilise ta foulée et économise ton énergie.`, mistakes: `Bassin qui s’affaisse, fesses hautes, tête relevée.` },
    { type: 'exercise', name: 'Squats', muscles: 'Quadriceps, fessiers', level: 'Débutant', technique: `Pieds largeur d’épaules, descends fesses en arrière dos droit jusqu’aux cuisses parallèles, remonte. Renforce la poussée et protège les genoux.`, mistakes: `Genoux qui rentrent, talons qui décollent, dos arrondi.` },
    { type: 'exercise', name: 'Fentes', muscles: 'Fessiers, quadriceps, équilibre', level: 'Débutant', technique: `Grand pas en avant, genou arrière vers le sol, buste droit, pousse pour revenir. Renforce chaque jambe et corrige les déséquilibres.`, mistakes: `Pas trop court, buste penché, perte d’équilibre.` },
    { type: 'exercise', name: 'Pont fessier', muscles: 'Fessiers, ischios', level: 'Débutant', technique: `Sur le dos, genoux fléchis, pousse dans les talons pour monter le bassin, serre les fessiers. Des fessiers forts protègent genoux et hanches.`, mistakes: `Cambrer le dos, monter trop haut.` },
    { type: 'exercise', name: 'Mollets debout', muscles: 'Mollets, tendon d’Achille', level: 'Débutant', technique: `Monte sur la pointe des pieds le plus haut possible, marque un temps, redescends lentement. Sur une marche pour plus d’amplitude.`, mistakes: `Amplitude courte, rebond, descente rapide.` },
    { type: 'exercise', name: 'Gainage latéral', muscles: 'Obliques, stabilité du bassin', level: 'Débutant - Intermédiaire', technique: `Sur le côté, appui sur l’avant-bras, corps aligné, hanches décollées. Stabilise le bassin pour une foulée efficace.`, mistakes: `Hanches qui descendent, corps qui bascule.` },
    { type: 'exercise', name: 'Montées sur step', muscles: 'Quadriceps, fessiers, équilibre', level: 'Débutant', technique: `Monte sur une marche/banc en poussant dans la jambe avant, contrôle la descente. Travaille la puissance unilatérale spécifique à la course.`, mistakes: `S’aider de la jambe arrière, descente non contrôlée.` },
    { type: 'exercise', name: 'Gammes : montées de genoux', muscles: 'Technique de course, fléchisseurs', level: 'Débutant', technique: `Sur 20 m, exagère la montée des genoux à hauteur de hanche, rythme rapide, gainage actif. Améliore la technique et la fréquence de foulée.`, mistakes: `Buste en arrière, genoux trop bas, foulée lourde.` },
    { type: 'exercise', name: 'Gammes : talons-fesses', muscles: 'Technique de course, ischios', level: 'Débutant', technique: `Sur 20 m, ramène les talons vers les fessiers, rythme rapide. Active les ischios et fluidifie la foulée.`, mistakes: `Buste penché, amplitude courte.` },
    { type: 'exercise', name: 'Foulées bondissantes', muscles: 'Puissance, propulsion', level: 'Intermédiaire', technique: `Sur 20-30 m, exagère la phase de poussée et de suspension, comme des bonds vers l’avant. Développe la puissance et l’économie de course.`, mistakes: `Réception raide, manque d’amplitude, bras passifs.` },
    { type: 'h2', text: 'Le circuit complet (2×/semaine)' },
    { type: 'p', text: `Enchaîne ces exercices en circuit, 2 à 3 tours, hors jours de grosse séance. 15-20 minutes suffisent pour un coureur plus fort et plus résistant.` },
    { type: 'table', headers: ['Exercice', 'Séries × reps', 'Repos'], rows: [
      ['Gainage planche', '3 × 30-45 s', '30 s'],
      ['Gainage latéral', '3 × 30 s / côté', '30 s'],
      ['Squats', '3 × 15', '45 s'],
      ['Fentes', '3 × 12 / jambe', '45 s'],
      ['Pont fessier', '3 × 15', '30 s'],
      ['Mollets debout', '3 × 20', '30 s'],
      ['Montées sur step', '3 × 12 / jambe', '45 s'],
    ] },
    { type: 'note', text: `Les gammes (montées de genoux, talons-fesses, foulées bondissantes) se font plutôt à l’échauffement des séances de qualité, sur 20-30 m, 2 à 3 passages chacune.` },

    { type: 'h1', text: 'Étirements & mobilité' },
    { type: 'p', text: `Après chaque sortie, 5-10 min d’étirements ciblés. Tiens chaque position 20-30 s, sans à-coups.` },
    { type: 'table', headers: ['Étirement', 'Zone', 'Durée'], rows: [
      ['Mollets au mur', 'Mollets, Achille', '30 s / côté'],
      ['Quadriceps debout', 'Avant de cuisse', '30 s / côté'],
      ['Ischios jambe tendue', 'Arrière de cuisse', '30 s / côté'],
      ['Fente basse (psoas)', 'Fléchisseurs de hanche', '30 s / côté'],
      ['Étirement fessier (figure 4)', 'Fessiers', '30 s / côté'],
      ['Bandelette ilio-tibiale', 'Extérieur de cuisse', '30 s / côté'],
    ] },
    { type: 'h2', text: 'Automassage au rouleau' },
    { type: 'p', text: `1 à 2 fois par semaine, passe un rouleau de massage 30-60 s sur chaque zone (mollets, quadriceps, fessiers, bandelette). Va lentement et insiste sur les points sensibles, sans rouler directement sur les articulations. Cela améliore la souplesse et accélère la récupération.` },
    { type: 'note', text: `Quand s’étirer ? Plutôt à froid en fin de journée ou après le retour au calme, jamais en force sur un muscle non échauffé. Les étirements ne « préviennent » pas toutes les blessures, mais entretiennent ta mobilité et ton confort de foulée.` },

    { type: 'h1', text: 'Le mental de compétiteur' },
    { type: 'p', text: `Sur les longues distances, le mental fait autant que les jambes. La bonne nouvelle : ça se travaille, exactement comme l’endurance. Voici comment forger ta tête de coureur.` },
    { type: 'h2', text: 'Les piliers du mental' },
    { type: 'list', items: [
      `Découpe la course en segments : ne pense pas « 42 km » mais « le prochain ravitaillement ».`,
      `Prépare des mantras (« je suis fort », « un pas après l’autre ») pour les moments durs.`,
      `Visualise ta course et ta ligne d’arrivée les jours précédents.`,
      `Pars prudemment : la plupart des contre-performances viennent d’un départ trop rapide.`,
      `Accepte l’inconfort : sur le marathon, le dur fait partie du plan, il finit toujours par passer.`,
    ] },
    { type: 'h2', text: 'Avant la course : gérer le stress' },
    { type: 'list', items: [
      `Le trac est normal et même utile : il te rend disponible et concentré.`,
      `Prépare tout la veille (dossard, tenue, petit-déjeuner) pour libérer ton esprit.`,
      `Respire lentement (inspiration 4 s, expiration 6 s) pour faire baisser la tension.`,
      `Fixe-toi 3 objectifs : un ambitieux, un réaliste, un « minimum acceptable ».`,
    ] },
    { type: 'h2', text: 'Pendant la course : tenir quand ça fait mal' },
    { type: 'table', headers: ['Moment difficile', 'Technique mentale'], rows: [
      ['Début trop facile', 'Te freiner : « patience, la course commence à mi-parcours »'],
      ['Coup de mou', 'Mantra + focus sur la foulée et la respiration'],
      ['Le mur (marathon)', 'Segmenter : « juste jusqu’au prochain km », sourire, relâcher'],
      ['Envie d’abandonner', 'Te rappeler ton « pourquoi » et les heures d’entraînement investies'],
      ['Dernier kilomètre', 'Tout donner : « c’est maintenant que je récolte »'],
    ] },
    { type: 'note', text: `Entraîne ton mental à l’entraînement : les sorties longues et les fins de fractionné sont l’endroit idéal pour pratiquer tes mantras et la segmentation. Le jour J, ce ne sera qu’une habitude de plus.` },

    { type: 'h1', text: 'Équipement essentiel' },
    { type: 'p', text: `Bonne nouvelle : courir coûte peu. En dehors des chaussures (chapitre dédié), voici l’équipement utile, classé par priorité - n’investis pas tout d’un coup.` },
    { type: 'table', headers: ['Équipement', 'Priorité', 'À quoi ça sert'], rows: [
      ['Chaussures adaptées', 'Indispensable', 'Confort et prévention des blessures'],
      ['Chaussettes techniques', 'Indispensable', 'Évacuer la transpiration, éviter les ampoules'],
      ['Tenue respirante', 'Recommandé', 'Rester au sec, réguler la température'],
      ['Brassière de maintien', 'Indispensable (femmes)', 'Confort et protection'],
      ['Montre GPS / appli', 'Recommandé', 'Suivre allure, distance, fréquence cardiaque'],
      ['Ceinture / soft flask', 'Utile (sorties longues)', 'Transporter eau et ravitaillement'],
      ['Anti-frottement', 'Utile', 'Protéger les zones sensibles (cuisses, aisselles)'],
      ['Lampe frontale + réfléchissant', 'Selon usage', 'Sécurité pour courir de nuit'],
    ] },
    { type: 'h2', text: 'Montre GPS ou smartphone ?' },
    { type: 'p', text: `Une appli gratuite sur ton téléphone (Strava, Nike Run Club…) suffit pour débuter : elle mesure distance, allure et trace. La montre GPS devient un vrai plus quand tu travailles tes allures et ta fréquence cardiaque au quotidien : lecture immédiate au poignet, sans sortir le téléphone.` },
    { type: 'note', text: `Le piège du débutant : tout acheter d’un coup. Commence par de bonnes chaussures et une tenue respirante. Le reste, tu l’ajouteras au fil de ta progression et de tes objectifs.` },

    { type: 'h1', text: 'Questions fréquentes' },
    { type: 'h2', text: 'Je ne tiens pas 5 min en courant, je peux commencer ?' },
    { type: 'p', text: `Oui : le plan 5K alterne course et marche au début. Augmente progressivement la part de course. En 8 semaines, tu courras ton 5K.` },
    { type: 'h2', text: 'À quelle vitesse courir mes footings ?' },
    { type: 'p', text: `En endurance fondamentale, tu dois pouvoir tenir une conversation. Si tu es essoufflé, tu cours trop vite. 80 % de tes sorties doivent être à cette allure.` },
    { type: 'h2', text: 'Combien de temps avant un marathon ?' },
    { type: 'p', text: `Si tu cours déjà ~1 h confortablement, 12 semaines suffisent. Sinon, fais d’abord le plan 10K puis semi avant de te lancer sur marathon.` },
    { type: 'h2', text: 'Que faire en cas de douleur ?' },
    { type: 'p', text: `Une gêne musculaire passagère : adapte. Une douleur articulaire ou qui persiste : repose-toi et consulte. Ne « pousse » jamais à travers une vraie douleur - c’est l’arrêt garanti.` },
    { type: 'h2', text: 'Faut-il faire du renforcement ?' },
    { type: 'p', text: `Oui, 1-2×/semaine. C’est ce qui te rend plus rapide ET plus résistant aux blessures. Le renforcement n’est pas optionnel pour progresser durablement.` },
    { type: 'h2', text: 'Tapis de course ou extérieur ?' },
    { type: 'p', text: `Les deux fonctionnent. Le tapis amortit et permet de contrôler l’allure (mets 1 % d’inclinaison pour simuler l’extérieur). L’extérieur travaille l’équilibre, le relief et le mental. Idéalement, alterne.` },
    { type: 'h2', text: 'Mon point de côté, comment l’éviter ?' },
    { type: 'p', text: `Évite de manger trop près de la sortie, échauffe-toi progressivement et travaille ta respiration ventrale. En cas de point, ralentis et expire à fond en appuyant légèrement sur la zone.` },
    { type: 'h2', text: 'Je stagne, que faire ?' },
    { type: 'p', text: `Vérifie d’abord ta récupération et ton sommeil. Ajoute de la variété (fractionné, seuil), respecte le 80/20, et fais des semaines d’allègement. La progression n’est jamais linéaire : la patience paie.` },
    { type: 'h2', text: 'Combien de fois courir par semaine ?' },
    { type: 'p', text: `3 sorties suffisent pour le 5K et le 10K, 3-4 pour le semi et le marathon. Mieux vaut 3 sorties régulières et de qualité que 5 bâclées. La régularité bat l’intensité ponctuelle.` },

    { type: 'h1', text: 'Suivi de tes sorties' },
    { type: 'p', text: `Note chaque sortie : distance, durée, allure, sensations. C’est ton journal de progression.` },
    { type: 'tracker', columns: ['Date', 'Distance (km)', 'Durée', 'Allure', 'Sensations /10'], rows: 13 },
    { type: 'h2', text: 'Records personnels' },
    { type: 'tracker', columns: ['Distance', 'Objectif', 'Réalisé', 'Date'], rows: 6 },

    { type: 'h1', text: 'Checklist hebdomadaire' },
    { type: 'p', text: `Coche chaque case en fin de semaine.` },
    { type: 'checklist', items: [
      `J’ai fait mes sorties prévues cette semaine.`,
      `80 % de mon volume était en endurance fondamentale.`,
      `Je n’ai pas augmenté mon volume de plus de 10 %.`,
      `Je me suis échauffé(e) avant mes séances de qualité.`,
      `J’ai fait 1-2 séances de renforcement.`,
      `J’ai fait mes gammes et travaillé ma cadence.`,
      `Je me suis étiré(e) après les sorties.`,
      `J’ai dormi 7 à 9 h par nuit.`,
      `Je me suis bien hydraté(e) et alimenté(e).`,
      `J’ai respecté mes jours de repos.`,
      `J’ai noté mes sorties et mes sensations.`,
      `J’ai pris du plaisir à courir cette semaine.`,
    ] },

    { type: 'h1', text: 'Motivation & régularité' },
    { type: 'p', text: `Le plus dur n’est pas de courir vite, c’est de courir RÉGULIÈREMENT. Voici comment tenir dans la durée.` },
    { type: 'list', items: [
      `Inscris-toi à une course : un dossard est le meilleur des moteurs.`,
      `Prépare tes affaires la veille : moins de friction = moins d’excuses.`,
      `Cours à heure fixe pour en faire une habitude automatique.`,
      `Trouve un partenaire ou un club : on se lève plus facilement à deux.`,
      `Célèbre chaque progrès (premier 5K sans marcher, nouveau record) : la motivation se nourrit des victoires.`,
      `Les jours sans envie, fixe-toi juste « 10 minutes ». Le plus souvent, tu finiras ta sortie.`,
    ] },
    { type: 'note', text: `La régularité bat le talent. Un coureur moyen qui s’entraîne 3×/semaine pendant un an progresse plus qu’un coureur doué qui s’entraîne une semaine sur trois. Sois ce coureur régulier.` },

    { type: 'h1', text: 'Glossaire du coureur' },
    { type: 'p', text: `Le vocabulaire essentiel pour décrypter les plans et les conversations entre coureurs.` },
    { type: 'table', headers: ['Terme', 'Définition'], rows: [
      ['EF', 'Endurance fondamentale : allure lente où l’on peut parler'],
      ['VMA', 'Vitesse Maximale Aérobie : vitesse à laquelle on atteint sa conso max d’oxygène'],
      ['Seuil', 'Allure soutenue limite tenable ~1 h ; améliore l’endurance à haute intensité'],
      ['Fractionné', 'Répétitions rapides entrecoupées de récupérations (ex. 8 × 400 m)'],
      ['Fartlek', 'Jeu d’allures libre : on accélère et ralentit selon ses sensations'],
      ['Tempo', 'Effort continu à allure soutenue (proche du seuil)'],
      ['Negative split', 'Courir la 2e moitié plus vite que la 1re'],
      ['Affûtage', 'Réduction du volume avant une course pour arriver frais'],
      ['Le mur', 'Épuisement brutal du glycogène (souvent vers le 30e km du marathon)'],
      ['Drop', 'Différence de hauteur talon/avant-pied d’une chaussure'],
      ['Cadence', 'Nombre de pas par minute'],
      ['Allure', 'Temps pour parcourir 1 km (min/km)'],
    ] },

    { type: 'h1', text: 'Notes personnelles' },
    { type: 'tracker', columns: ['Mes sorties, sensations et objectifs de la semaine'], rows: 20 },

    { type: 'h1', text: 'Et après ta course ?' },
    { type: 'p', text: `Tu as franchi la ligne d’arrivée : bravo ! Mais l’aventure ne s’arrête pas là. Voici comment transformer cette réussite en progression durable.` },
    { type: 'list', items: [
      `Récupère vraiment : 1 semaine très allégée après un 5K/10K, 2 à 3 semaines après un marathon.`,
      `Fixe-toi un nouveau défi : la distance supérieure, ou le même chrono… en plus rapide.`,
      `Garde une base d’endurance fondamentale toute l’année : c’est ce qui rend les reprises faciles.`,
      `Continue le renforcement et les gammes : un coureur entretenu est un coureur qui dure.`,
      `Rejoins une communauté ou un club : courir à plusieurs entretient la motivation sur le long terme.`,
    ] },
    { type: 'h2', text: 'Choisis ta prochaine cible' },
    { type: 'table', headers: ['Tu viens de courir', 'Prochain objectif logique'], rows: [
      ['Ton premier 5K', 'Améliorer ton chrono, puis viser le 10K'],
      ['Un 10K', 'Le semi-marathon'],
      ['Un semi-marathon', 'Le marathon, ou un semi plus rapide'],
      ['Un marathon', 'Un nouveau marathon visé au chrono, ou le trail'],
    ] },
    { type: 'note', text: `Félicitations Accorde-toi une vraie récupération, puis repars vers un nouvel objectif. Crée ton compte sur xenotif.com pour suivre tes sorties, planifier tes allures et échanger avec ton coach IA. On se retrouve sur la ligne de départ !` },
  ],
}
